### ISSUE TITLE
[Bug]:   KryptonRibbon/RibbonAppButton/AppButtonMenuItems fails in designer and in code

### ISSUE THREAD

**Issue by ja72** [Krypton-Suite/Standard-Toolkit#1005]
**Describe the bug**
While designing a ribbon control, I am unable to design the app button menu. Specifically, the `AppButtonMenuItems` collection fails to add menu items because the designer is trying to add an instance of `KryptonContextMenuItemBase` but it is an abstract class. 

**To Reproduce**
1. Open up the Forms Designer
2. Add a `KryptonRibbon`
3. Expand the `RibbonAppButton` node in the properties window
4. Click On the ellipsis `[..]` of the `AppButtonMenuItems` row
5. Click the `Add` button under the members' list.

**Expected behavior**
I expected a new `KryptonContextMenuItem` to be added to the collection and its properties displayed for editing on the property grid inside the dialog box.

**Screenshots**

Here is an image of the error message in the designer when the `AppButtonMenuItems` collection dialog is opened up and a new item is added.

![image](https://user-images.githubusercontent.com/22509289/232793944-c5f2c646-6da2-4f4c-ad9a-c0c86907ce95.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2
 - Visual Studio 2017/2022
 - WinForms/.NET Framework 4.8

**Additional context**
I tried adding the menu items programmatically when the form loads with the following code

```
    KryptonContextMenuItem newItem = new KryptonContextMenuItem("New")
    {
        SplitSubMenu = true,
    };

    KryptonContextMenu menu = new KryptonContextMenu()
    {
        PaletteMode = PaletteMode.Global,
    };
    menu.Items.Add(newItem);

    kryptonRibbon1.RibbonAppButton.AppButtonMenuItems.Add(menu);
```

and I get an argument exception with the message `Type to be added is not allowed in this collection.` when the `menu.Items.Add(newItem);` command is reached.

**Comment by Smurf-IV** [comment]
> WinForms/.NET Framework 4.8

Please can you show the order of the TFM's in your csproj file please.

Note. The above is seen when using .netcore projects onwards.

**Comment by ja72** [comment]
What are TFM’s?

As I said, I am not using .netcore but .NET Framework 4.8.

***@***.***

**Comment by Smurf-IV** [comment]
Ok, some missing info then..
Can you state what version of Krypton you are using please
And still include you csproj so that it can be tested.. as It might be a VS 2022 flavour thing that we are using and not seeing the problem because of it.

**Comment by ja72** [comment]
Krypton 4.6.0.0 it seems

***@***.***

The .csproj was created with VS2017, but the problem exists in both VS2017 and VS2022

Attached is the whole project

**Comment by Wagnerp** [comment]
Hi @ja72 

Unfortunately we don't support 4.6.0.0. It looks as if the version that you're currently using is a older version (CF) from 2017. Please check [here](https://github.com/Krypton-Suite/Krypton-Toolkit-Suite-Version-Dashboard) for currently supported versions.

cc. @Smurf-IV

**Comment by Wagnerp** [comment]
No problem
