### ISSUE TITLE
[Feature Request]: Show a tooltips on a KryptonContextMenuItem

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1015]
### Discussed in https://github.com/Krypton-Suite/Standard-Toolkit/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **mbagattini** May  4, 2023</sup>
I'm using the KryptonRibbon control and I have several KryptonRibbonGroupButton in said ribbon. Some of these buttons have ButtonType = DropDown and are linked to a KryptonContextMenu. Finally, each KryptonContextMenu has a series of KryptonContextMenuItem.

Is there a way to show a Tooltip when the cursor rolls over one of these KryptonContextMenuItem? I have Tooltip set for main KryptonRibbonGroupButtons but I can't find a way to display additional info related to the drop down menu items.

Thanks!</div>

**Comment by Smurf-IV** [comment]
It appears that the `KryptonContextMenuItem` doe snot have a tooltip associated with it. :-(

Seems like this has been missed when Tooltips where introduced in .Net 2:
https://stackoverflow.com/questions/58245/showing-a-tooltip-for-a-menuitem

**Comment by Smurf-IV** [comment]
A Dev hint on how to solve when implementing in Krypton:
https://github.com/DevExpress-Examples/how-to-show-tooltips-for-menu-items-e3133

**Comment by Smurf-IV** [comment]
And maybe use something like this:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ff21fe35-07db-4ee8-88fb-74ebfa9f0dbf)

**Comment by Smurf-IV** [comment]
Add the `Tooltip` values under **Behavior** to match the standard content menu designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b6569940-efa4-4495-b4f5-c0b3c3020153)

**Comment by Smurf-IV** [comment]
Cannot seem to get the Designer to Display the contents of the "ToolTip Child items" within the Menu Designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/becaa9fa-27df-479c-ae1e-59a305aa05a2)

But it's okay in the Properties designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/9a118128-5ec5-4472-992f-7a285f3972b5)

**Comment by Smurf-IV** [comment]
Got it working.
![MenuTooltip](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/86d34b8c-8bc4-4e19-a809-e3d29c5cd9bb)

Now to sort the designer issue...
