### ISSUE TITLE
[Bug]: `KryptonInputBox` does not compile

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#102]
The `KryptonInputBox` does not compile!

Solution:
Re-implement the `KryptonInputBox` on original code, while adding new features, i.e. cue text/font etc.

**Comment by Smurf-IV** [comment]
Can this also sort out #77 ?

**Comment by Wagnerp** [comment]
> Can this also sort out #77 ?

Yes! ;)
