### ISSUE TITLE
[Bug]: Cannot add a `KryptonPage` to a `KryptonNavigator`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1020]
As found in today's nightly build, 142.

![KNavigator](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/ec546cd2-72a7-4d2b-9222-533d61f6c53c)

**Comment by Smurf-IV** [comment]
What version ov VS is that, perhaps they are starting to be more restrictive on the framework designer ??

**Comment by Wagnerp** [comment]
> What version of VS is that?

Version 17.6.x, happens when using **both** .NET Framework & .NET

**Comment by Smurf-IV** [comment]
I have been noticing that when trying to build / run the existing demo apps in the designer, that there are many errors.
I think it is an impact of the partial understanding of the `nullable` work that is still in progress.
OR, it is an impact of the designer moving forward forcing the rework required to use the new Visual Studio Way Of Working.

**Comment by Wagnerp** [comment]
> I have been noticing that when trying to build / run the existing demo apps in the designer, that there are many errors. I think it is an impact of the partial understanding of the `nullable` work that is still in progress. OR, it is an impact of the designer moving forward forcing the rework required to use the new Visual Studio Way Of Working.

@Smurf-IV Think I've worked it out... _we're_ not checking for `null` when certain events are raised https://github.com/Krypton-Suite/Standard-Toolkit/issues/1023#issuecomment-1588810368

**Comment by Smurf-IV** [comment]
Also found via the fix for https://github.com/Krypton-Suite/Theme-Palettes/issues/51

**Comment by Smurf-IV** [comment]
It's gonna take a while to sort and fix all these ..
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e3280827-9f58-4192-b42e-2aca78bb3d91)

**Comment by Wagnerp** [comment]
I think @MHartmann-427 said that ReSharper can assist with this https://github.com/Krypton-Suite/Standard-Toolkit/issues/1023#issuecomment-1596772886

**Comment by Smurf-IV** [comment]
It can, but first you have to modify all the `eventhandlers` to be nullable....

**Comment by MHartmann-427** [comment]
No, ReSharper can assist you with this issue out-of-the-box.
Here's a small example:

![ReSharper](https://github.com/Krypton-Suite/Standard-Toolkit/assets/102691912/b719c033-656f-414e-92d7-337a15232447)


The blue squiggle comes from ReSharper telling you about possible NullReferenceException.
So you can use menu "ReSharper" => "Inspect" => "Code Issues in Solution" and filter the result to show only "Possible 'System.NullReferenceException'" issue.

**Comment by Wagnerp** [comment]
Once a few are done (in a file), you can let AI do the rest

**Comment by Wagnerp** [comment]
@Smurf-IV I've now fixed this, will be in the next PR :)

**Comment by Wagnerp** [comment]
Please test in latest nightly >= .178

**Comment by MHartmann-427** [comment]
There are still a lot of nullability issues in the code.
Next crash (again a NullReferenceException) in class "ViewDrawMenuItem", method "ShowSubMenu".

Here's the stack trace:
   bei Krypton.Toolkit.ViewDrawMenuItem.ShowSubMenu(Boolean keyboardActivated)
   bei Krypton.Toolkit.MenuItemController.ShowSubMenu()
   bei Krypton.Toolkit.ViewContextMenuManager.OnDelayTimerExpire(Object sender, EventArgs e)
   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Can't tell you which object is NULL and causes this exception, sorry.

I think the alpha branch is far, far away from being testable because of all those nullability issues. I still can't understand, why all the nullability checks that exist in version 70 are removed in version 80.

**Comment by Wagnerp** [comment]
Might need more work to be done on this

**Comment by Wagnerp** [comment]
> There are still a lot of nullability issues in the code.
> Next crash (again a NullReferenceException) in class "ViewDrawMenuItem", method "ShowSubMenu".
> 
> Here's the stack trace:
>    bei Krypton.Toolkit.ViewDrawMenuItem.ShowSubMenu(Boolean keyboardActivated)
>    bei Krypton.Toolkit.MenuItemController.ShowSubMenu()
>    bei Krypton.Toolkit.ViewContextMenuManager.OnDelayTimerExpire(Object sender, EventArgs e)
>    bei System.Windows.Forms.Timer.OnTick(EventArgs e)
>    bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> Can't tell you which object is NULL and causes this exception, sorry.
> 
> I think the alpha branch is far, far away from being testable because of all those nullability issues. I still can't understand, why all the nullability checks that exist in version 70 are removed in version 80. 

Duplicate of #1034

**Comment by Smurf-IV** [comment]
It's gonna take a while to sort and fix all these ..
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e3280827-9f58-4192-b42e-2aca78bb3d91)

**Comment by Smurf-IV** [comment]
I'll start to work on this bug (And others I have found during the investigation) when PtIV(#1046) has been merged (It'll probably be next weekend now)

**Comment by Smurf-IV** [comment]
Build after PtIV merge appears to work (May have been fixed earlier, but this is what the following video is from)
Taken with Current alpha (After PtIV merge) in Visual Studio 17.7.P3
![NavigatorPages](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/00b299f3-55f0-4c1b-be2c-7b020637823f)
