### ISSUE TITLE
[Bug]: Cannot add controls to KryptonGroup & KryptonGroupBox

### ISSUE THREAD

**Issue by Axel123inkt** [Krypton-Suite/Standard-Toolkit#1036]
Cannot add controls to  KryptonGroup & KryptonGroupBox

1. Add  KryptonGroup & KryptonGroupBox to form
2. Add control to either one of them
3. Error

**Expected behavior**
It should work?

![afbeelding](https://github.com/Krypton-Suite/Standard-Toolkit/assets/64073735/2649fc97-bf40-40a3-9323-96e976c1cd62)

**Desktop (please complete the following information):**
Windows 10
Version 22H2
.Net 6.0

**Comment by Smurf-IV** [comment]
What version of the toolkit are you using please ?

**Comment by Axel123inkt** [comment]
Krypton.Toolkit 70.22.11.312

**Comment by Smurf-IV** [comment]
Seems to have been fixed along with the changes done for #1020 (In alpha branch)
