### ISSUE TITLE
[Bug]: Nightly "Build" option causes erros in build sequences

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1038]
Using latest VS preview:
and alpha branch:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1218df78-b4f9-4eef-8ff9-dd6ca178d499)

**Comment by Smurf-IV** [comment]
No problem with Debug or release options:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7155890b-306c-4668-b9fb-507fe745427b)

**Comment by Wagnerp** [comment]
You need to build it via launching `run.cmd` located in the root directory, unlike the ET, ST can't be built in the VS IDE, as the build toolchain relies on scripts.

**Comment by Smurf-IV** [comment]
> You need to build it via launching `run.cmd` located in the root directory, unlike the ET, ST can't be built in the VS IDE, as the build toolchain relies on scripts.

I did, that is what caused me to then try in VS as well.
They both reported errors

**Comment by Wagnerp** [comment]
> > You need to build it via launching `run.cmd` located in the root directory, unlike the ET, ST can't be built in the VS IDE, as the build toolchain relies on scripts.
> 
> I did, that is what caused me to then try in VS as well. They both reported errors

Umm... works for me:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/d144a096-d2a9-43f6-ad7a-8a7abf682efd)

Can you verify what .NET/Frameworks you have installed?

**Comment by Smurf-IV** [comment]
Seems to be okay with the latest "PtV" branch I go this morning and vs 17.7.P3:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/47a4a78d-11fb-4f57-866d-e6aadcfbbc3e)

Closing.
