### ISSUE TITLE
[Bug]: Toolbox Icons do not show in VisualStudio 2019

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#104]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2418812/118388133-74ce1580-b61a-11eb-9b3a-fbe31d712d22.png)

**To Reproduce**
Whilst investigating #94 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version Canary

**Comment by Smurf-IV** [comment]
Seems like it is an issue with both nuget and .net 5
https://vsf-prod.westus.cloudapp.azure.com/content/problem/1210749/usercontrols-toolbox-icon-doesnt-appear-in-net50ne.html

**Comment by DarthVader85PA** [comment]
Hello @Smurf-IV
Hello @Wagnerp,

Same issue with Visual Studio 2017.
Best regards from Germany,
Danny

**Comment by Smurf-IV** [comment]
Help Required:
Does anyone have this working ?
- If so, What version of Visual Studio  / Framework / Krypton are you using ?

**Comment by DarthVader85PA** [comment]
**Visual Studio 2019 Professional - Version: 16.9.5** 
**Project:** 

- .NET-Framework 4.7.2
- Krrypton-Standard (NuGet) - Version 5.550.2103.1
- x86 - Language: VB.NET

**Visual Studio 2017 Professional - Version: 15.9.35** 
**Project:** 

- .NET-Framework 4.7.2
- Krrypton-Standard (NuGet) - Version 5.550.2103.1
- x86 - Language: VB.NET

Project and Project-Settings are the same. I work with both Visual Studio Versions at the moment and TFS 2018 SP3.
Greetings, Danny

**Comment by Wagnerp** [comment]
@Smurf-IV & @DarthVader85PA 

Might be a bug with Visual Studio itself. What happens if you build the code from scratch, then directly import the built DLLs into the toolbox?

**Comment by Smurf-IV** [comment]
It is a bug with visual studio (16.9.5) - when using the `Microsoft.NET.Sdk` form of the csproj
- Create a new `Winform1` solution
- Add User Control
- add following above user control
``` c#
     [ToolboxItem(true)]
    [ToolboxBitmap(typeof(TreeView))]
```
- Build
- Close / open solution (To force fresh of toolbox)
- Open Form1 in designer
- Expected to see the `UserControl1` with the treeview icon
- Drag UserControl onto form1
- Open Document View and see that the UserControl has the TreeView icon as expected.

Anyone got a way of reporting this to MS ?
Anyone want to repeat with other project types ?

**Comment by Smurf-IV** [comment]
Just tested with the "WindowsFormApp" - Same!
![image](https://user-images.githubusercontent.com/2418812/118393385-c389a880-b636-11eb-9f1e-f6f68f012325.png)

**Comment by Smurf-IV** [comment]
And also the same in 16.10.Preview 3 !

**Comment by DarthVader85PA** [comment]
I think so too, because the controls from Syncfusion, implements over NuGet too, have the same issue.

![grafik](https://user-images.githubusercontent.com/32876506/118393764-f89af880-b640-11eb-98b7-ac95ad7e7849.png)

**Comment by Wagnerp** [comment]
> It is a bug with visual studio (16.9.5) - when using the `Microsoft.NET.Sdk` form of the csproj
> 
> * Create a new `Winform1` solution
> * Add User Control
> * add following above user control
> 
> ```cs
>      [ToolboxItem(true)]
>     [ToolboxBitmap(typeof(TreeView))]
> ```
> 
> * Build
> * Close / open solution (To force fresh of toolbox)
> * Open Form1 in designer
> * Expected to see the `UserControl1` with the treeview icon
> * Drag UserControl onto form1
> * Open Document View and see that the UserControl has the TreeView icon as expected.
> 
> Anyone got a way of reporting this to MS ?
> Anyone want to repeat with other project types ?

Yes, there is **if** you are using the preview version of VS, there is a `Report a bug` feature.

**Comment by Smurf-IV** [comment]
> 
> Yes, there is **if** you are using the preview version of VS, there is a `Report a bug` feature.

![image](https://user-images.githubusercontent.com/2418812/118394845-16fff480-b63f-11eb-8eb8-1a4e24fcd046.png)
:-(

**Comment by Wagnerp** [comment]
> > Yes, there is **if** you are using the preview version of VS, there is a `Report a bug` feature.
> 
> ![image](https://user-images.githubusercontent.com/2418812/118394845-16fff480-b63f-11eb-8eb8-1a4e24fcd046.png)
> :-(

I can do this if you want, as it might be a corporate restriction.

**Comment by Smurf-IV** [comment]
Used by Company account...
https://developercommunity.visualstudio.com/myfeedback?port=1025&fsid=fd77291c-0541-4292-b819-b55af71fd99e&entry=myfeedback

Also found these:
https://developercommunity2.visualstudio.com/t/Toolboxs-Choose-Items-still-cannot-brow/1141745?entry=problem&ref=native&refTime=1621163678844&refUserId=80c6fce5-56e4-6817-a4c0-2e9d6d20b2ed

https://developercommunity2.visualstudio.com/t/UserControls-toolbox-Icon-doesnt-appea/1210749?entry=problem&ref=native&refTime=1621163678843&refUserId=80c6fce5-56e4-6817-a4c0-2e9d6d20b2ed

**Comment by Wagnerp** [comment]
Seems to be an unresolved bug

**Comment by Wagnerp** [comment]
@Smurf-IV Yet they do if you import the `DLL`s directly into VS!

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Yet they do if you import the `DLL`s directly into VS!

Not for me:
![image](https://user-images.githubusercontent.com/2418812/132949596-e939005f-4da7-46fe-9f93-b620269cc1b5.png)

**Comment by Smurf-IV** [comment]
Hmm Seems like a I suffered this:
https://stackoverflow.com/questions/7789297/how-to-undo-a-reset-toolbox-in-vs2008

**Comment by Smurf-IV** [comment]
nope, drag and drop still looks like blank Icons !

**Comment by Smurf-IV** [comment]
Something is telling lies:
https://www.visualbasicplanet.info/visual-studio/the-toolbox-bitmap.html

**Comment by Smurf-IV** [comment]
Because of the following statement
``` c#
internal static class FXAssembly
{
    // NB: this must never-ever change to facilitate type-forwarding from
    // .NET Framework, if those are referenced in .NET project.
     internal const string Version = "4.0.0.0";
}
```
Taken from Winforms (5 or 6) Github `$\src\System.Windows.Forms\src\AssemblyRef.cs`

I wonder if the workaround that MS have done, is to force the designers and the resources into a .net48 framework dll only !!

**Comment by giduac** [comment]
@Smurf-IV, @Wagnerp 

In one of the links above there has been an update to this "problem" from MS.
https://developercommunity2.visualstudio.com/t/UserControls-toolbox-Icon-doesnt-appea/1210749?entry=problem&ref=native&refTime=1621163678843&refUserId=80c6fce5-56e4-6817-a4c0-2e9d6d20b2ed

I tried this on VS2022:
Net31/50/60 shows the icons.
Net48 does not.

Seems that this can be closed since MS wont be fixing this in 2019 as it looks...

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be closed as per @giduac 's comment?
