### ISSUE TITLE
[Feature Request]: Automatically upgrade incompatible theme (XML) files

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1050]
Currently, there is a separate binary for  'Palette Upgrade Tool' (PUT) that the user must install to 'upgrade' palette XML files. To streamline things, it would be beneficial to bring this functionality directly into the toolkit, rather than having a standalone binary.

**Comment by Smurf-IV** [comment]
I think it should just "Automatically" perform the upgrade within the toolkit usage.
And place the upgrade also into the "Palette Designer".
Leave the exceptions etc, so that the Toolkit "User" can catch them and then perform a designer upgrade.

**Comment by Wagnerp** [comment]
> I think it should just "Automatically" perform the upgrade within the toolkit usage. And place the upgrade also into the "Palette Designer". Leave the exceptions etc, so that the Toolkit "User" can catch them and then perform a designer upgrade.

@Smurf-IV I'll work on these features ASAP

**Comment by Smurf-IV** [comment]
> Automatic upgrading should be done within the `Import()` function, **but** we need to warn the user so that they can cancel it.

Only if there is a problem, otherwise it should be UI silent (maybe log out) and continue on it's way.

**Comment by Wagnerp** [comment]
> > Automatic upgrading should be done within the `Import()` function, **but** we need to warn the user so that they can cancel it.
> 
> Only if there is a problem, otherwise it should be UI silent (maybe log out) and continue on it's way.

So, it needs to go in the `Import(bool silent)` function. Should the upgraded file go in the application's executable path, if so, that may cause issues if the system is locked down?

**Comment by Smurf-IV** [comment]
> it needs to go in the Import(bool silent) function. 

Ok, That could be a way around the auto messagebox thing, that you are creating


> Should the upgraded file go in the application's executable path, if so, that may cause issues if the system is locked down?

Correct, it needs to be in memory, and then passed into what the import should have been using to activate the theme.

**Comment by Wagnerp** [comment]
@Smurf-IV Might need some thinking, as I thought that I could compare the version with the defined 'maximum version', but then realised that you had to do XML parsing in the `Import()` function to get the right node (see lines 3028 - 3030 in `KryptonCustomPaletteBase` for an example). Feel free to give it a go.

**Comment by Smurf-IV** [comment]
Will perform changes / tests via the following app 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/366cec58-800e-40c4-934a-7096ecc08e02)

to:
- Add "Auto Import" button
- Add functionality in Toolkit to perform "as near" silent upgrade

**Comment by Smurf-IV** [comment]
Coming to a PR Soon:
![SilentUpgrade](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ee44b255-0295-4e8b-97be-121f2924182a)

**Comment by Smurf-IV** [comment]
Implemented via a new API, that takes a "Positionable" `stream`
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6b23243e-19ef-419a-87a2-d1afab6c5c06)

So that if the xml is an application resource it, can still be upgraded in memory.

**Comment by Wagnerp** [comment]
> Implemented via a new API, that takes a "Positionable" `stream` ![image](https://user-images.githubusercontent.com/2418812/258381268-6b23243e-19ef-419a-87a2-d1afab6c5c06.png)
> 
> So that if the xml is an application resource it, can still be upgraded in memory.

Might need to put this in 'breaking changes' so that the dev knows whether to update their documentation (or not)

**Comment by Smurf-IV** [comment]
> Might need to put this in 'breaking changes' so that the dev knows whether to update their documentation (or not)

It's not a breaking change. It's a new API. That's why I chose to do it that way in the end.
The "ChangeLog" allows the devs to follow the links to things like this to find out how "New" features may be used.
