### ISSUE TITLE
[Feature Suggestion] AutoDataGridViewFilter onCellPaint event handler

### ISSUE THREAD

**Issue by realband** [Krypton-Suite/Standard-Toolkit#1053]
https://github.com/Krypton-Suite/Standard-Toolkit/blame/896008b760dea81505c1a30aa38c4b1b56a46452/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonDataGridView.cs#L1514

The e.handled command in the onCellPaint event does not allow the AutoDataGridViewFilter Nuget to be easily implemented without overriding the onCellPaint event.

**Comment by Smurf-IV** [comment]
If "you" are handling the "OnCellPainting" then you do not need to derive from a Krypton Cell / column type.

Do you have an example of when this would be needed ?

**Comment by Smurf-IV** [comment]
Not answered - Closing
