### ISSUE TITLE
[Bug]: `KryptonWrappedLinkLabel` does not accept escape characters

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1055]
The `KryptonWrappedLinkLabel` does not accept escape characters, for example, '\n'. This may cause a problem when used in a KMessagebox.

**Comment by Smurf-IV** [comment]
Using the following in the designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/726ac094-6504-42a7-9198-b925a711855a)

Results in the following in the view:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/14228f21-09b9-43cc-9f77-07025feac3ba)
