### ISSUE TITLE
[Bug]: 'MethodImplOptions' does not contain a definition for 'AggressiveInlining'

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#106]
**Describe the bug**
When building the code, the error 'MethodImplOptions' does not contain a definition for 'AggressiveInlining' for `MissingFrameWorkAPIs.cs` appears

**To Reproduce**
1. Open `cmd`
2. Navigate to the source root directory
3. Run `run.cmd`

**Comment by Smurf-IV** [comment]
That should have the `#if` guard put round it 
I did that recently in one of the PR's

**Comment by Smurf-IV** [comment]
I understand now.. Also needs to be guarded for `.net40`

**Comment by Wagnerp** [comment]
Fixed in the August 2021 update
