### ISSUE TITLE
[Bug]: `ToolTipValues` not found in `KryptonContextMenuItem`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1063]
As found in the `alpha` branch.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/fa306ef1-7623-40e2-95d6-9b3deb582ccb)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8d54727d-a418-4999-9a2f-abcece4b6bd0)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/e8338b69-1373-4fbe-a974-c84566da4a93)

**Comment by Smurf-IV** [comment]
Will sort as part of #1015
