### ISSUE TITLE
[Bug]: "PaletteOffice2010BlackDarkMode" Throws excpetion for tooltip color usage

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1070]
Using todays alpha:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/2df8b80c-f2a0-4205-a2d3-0a5ee374c706)

**Comment by Smurf-IV** [comment]
Also happens in `{Krypton.Toolkit.PaletteMicrosoft365DarkGray}`:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/9566d8df-9481-4326-8a8f-26e35e5c6013)

**Comment by Smurf-IV** [comment]
And:
- `{Krypton.Toolkit.PaletteOffice2010DarkGray}`
- `{Krypton.Toolkit.PaletteOffice2013DarkGray}`

Did not find any others from the current dropDown combo selection

**Comment by Wagnerp** [comment]
Colours ought to have proper mapping to enum values (if not already). Maybe a separate feature request?

**Comment by Smurf-IV** [comment]
Currently the exception closes the program. So it's a bug.
If it is fixed by using an enum then that would be good, but currently not a feature request for that.

**Comment by giduac** [comment]
@Smurf-IV 

I tried the tooltip of a couple of Ribbon components but can't reproduce the error.
Under which conditions does this happen?

**Comment by Smurf-IV** [comment]
Blimey, No longer working at the company that was using that app.
Will have to look at using the Toolkit examples and adding a tooltip to a menu.
Will not be for a while....

**Comment by Smurf-IV** [comment]
In V90, Todays Alpha
- ![image](https://github.com/user-attachments/assets/6041b7ed-1f06-4afc-849e-d9226e48c3ad) is ok
- ![image](https://github.com/user-attachments/assets/dc3e4640-a89d-48b2-8252-51f7ee6b4414) is ok.
-

**Comment by Smurf-IV** [comment]
re: V85 -> V90
The non _Silver_ "Dark Gray" modes (e.g. 
![image](https://github.com/user-attachments/assets/adee68d1-b922-45c9-ae4e-93d677f28cc8) ) have been removed from V90

Therefore closing this as a won't fix as they are not supported going forward/

**Comment by PWagner1** [comment]
> re: V85 -> V90 The non _Silver_ "Dark Gray" modes (e.g. ![image](https://private-user-images.githubusercontent.com/2418812/371835250-adee68d1-b922-45c9-ae4e-93d677f28cc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTU1NzgsIm5iZiI6MTcyNzU5NTI3OCwicGF0aCI6Ii8yNDE4ODEyLzM3MTgzNTI1MC1hZGVlNjhkMS1iOTIyLTQ1YzktYWU0ZS05M2Q2NzdmMjhjYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDczNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmNTI1MzNmY2FjMjljYmUwNDA2ZTZjYTUxZGM5MmVjNzNhMDkyNDJkOGEyN2E5NzFjZjRmMTNmZThhOTFjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bZXIife6fmKg3CFjfkffHl09LB76FvBpRVVgbXAhI1Y) ) have been removed from V90
> 
> Therefore closing this as a won't fix as they are not supported going forward/

@Smurf-IV 

They're going to be part of V100/110
