### ISSUE TITLE
[Bug]: Clicking "RootItem->Items" in a designer causes an exception to be thrown

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1072]
Using todays alpha branch

- Run the BreadCrumb Example to get the designer
- Expand the `RootItem`
- Click the `Items` to open the selection designer
Boom:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/cc799412-9938-4773-a37d-d2395f561ee8)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/558ddbca-c798-4b23-9bf9-acda5c8ccd68)

**Comment by Wagnerp** [comment]
@Smurf-IV Does it give any indication of what's missing, or should I add _all_ the `PaletteState` entries?

**Comment by Smurf-IV** [comment]
Image updated

**Comment by Wagnerp** [comment]
Now fixed

![1072](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/16077efe-3349-4b7c-bf9f-5cd1da4ae4c0)
