### ISSUE TITLE
[Bug]: Krypton File Dialogs Missing Buttons

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1091]
As found in todays `alpha`

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/f39a5be1-6fc7-4835-b4f9-1ff5d4c1990e)

**Comment by Smurf-IV** [comment]
Hmm..
Can you state what OS this is on please ?

**Comment by Wagnerp** [comment]
> Hmm.. Can you state what OS this is on please ?

Using latest Windows 11

**Comment by Wagnerp** [comment]
![1091](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/41036289-be69-4304-98c2-ec9ec09be8cb)

**Comment by Smurf-IV** [comment]
I have just tried this with todays alpha on Win 10 H22 x64 and various scaling sizes, and it appears to be okay.

**Comment by Wagnerp** [comment]
> I have just tried this with todays alpha on Win 10 H22 x64 and various scaling sizes, and it appears to be okay.

Weird, wonder if it's Win 11 specific?

**Comment by Smurf-IV** [comment]
> Weird, wonder if it's Win 11 specific?

I think so, What does a Win 11 Winform "File open dialog" look like?

**Comment by Wagnerp** [comment]
> > Weird, wonder if it's Win 11 specific?
> 
> I think so, What does a Win 11 Winform "File open dialog" look like?

Like the Win 10 one...

![Win11OpenFileDialog](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/da5f2d57-73fe-4cff-9c7b-1ad394598cbb)

**Comment by Smurf-IV** [comment]
I'm Creating a VM for Win 11 then will start this investigation.

**Comment by Smurf-IV** [comment]
@Wagnerp can you run the sample, because it appears to be "Okay" with the current "Alpha" builds:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b0c920e0-fcc6-47bf-a6cd-24f6fc0dbf70)

**Comment by Smurf-IV** [comment]
Mine is 22H2:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/4ac290d6-e482-425d-ab82-13b7500e11a5)

**Comment by Wagnerp** [comment]
What happens if you call `Import/Export` via code?

**Comment by Smurf-IV** [comment]
>What happens if you call Import/Export via code?

I do not understand the context ?

**Comment by Wagnerp** [comment]
> > What happens if you call Import/Export via code?
> 
> I do not understand the context ?

What happens if you call `kryptonCustomPalette.Import()`?

**Comment by Smurf-IV** [comment]
What is `kryptonCustomPalette.Import()`
I cannot find it in the code for `KryptonCustomPaletteManager`

**Comment by Wagnerp** [comment]
> What is `kryptonCustomPalette.Import()` I cannot find it in the code for `KryptonCustomPaletteManager`

Sorry, I meant `Import()`

**Comment by Smurf-IV** [comment]
I'm missing something, Can you attach a small project please ?

**Comment by Wagnerp** [comment]
> I'm missing something, Can you attach a small project please ?

Here's a test project

[Bug1091.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/13060343/Bug1091.zip)

**Comment by Smurf-IV** [comment]
By Using a direct reference to the code base (i.e. remove the nuget) via a "Nightly debug build"
net481:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/809dcba5-a35e-4fdf-b597-8207274e738a)
net6.0-windows 7 & 8:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6235f8ee-0614-45c1-951c-62441e5e01ba)

**Comment by Smurf-IV** [comment]
Same (as above) when reapplying the following nuget:
``` c#
    <ItemGroup>
	  <PackageReference Include="Krypton.Toolkit.Nightly" Version="80.23.10.291-alpha" />
	</ItemGroup>
```

**Comment by Smurf-IV** [comment]
Win 11 appears to be okay as well:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/fe38f46e-560d-40f3-8f7b-83ef64033a12)

**Comment by Wagnerp** [comment]
@Smurf-IV I do have an idea for a fix, but I'll need to spin up a Win 10 VM to test my theory

**Comment by Wagnerp** [comment]
Now uses standard Win32 open/save dialogs for action lists.
