### ISSUE TITLE
[Bug]: Custom themes not being applied

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1092]
When a custom theme is loaded, the `KryptonManager` does not automatically set itself to 'Custom'.

**Comment by Smurf-IV** [comment]
Please retest now that #1224 is completed

**Comment by Wagnerp** [comment]
> Please retest now that #1224 is completed

Will do! :)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

Has this one been verified as working yet?

**Comment by giduac** [comment]
@Wagnerp 

I'll look into this if you like then please assign to me??

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> I'll look into this if you like then please assign to me??

@giduac 

Done, if you need custom themes to test with, there are a load [here](https://github.com/Krypton-Suite/Theme-Palettes/tree/master/Palettes/XML%20Format).

**Comment by giduac** [comment]
Hi @Wagnerp,

There are several properties in KManager that do more or less the same.
Do you have a working code example of how to load a Custom theme?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> There are several properties in KManager that do more or less the same. Do you have a working code example of how to load a Custom theme?

Hi @giduac 

You can use the `Import()` API to load a custom theme...

**Comment by giduac** [comment]
> > Hi @Wagnerp,
> > There are several properties in KManager that do more or less the same. Do you have a working code example of how to load a Custom theme?
> 
> Hi @giduac
> 
> You can use the `Import()` API to load a custom theme...

And which of the properties (preferably) to use for assignment?

Also the ThemeManager has a public method for loading themes.
Is that really a necessity or wouldn't it be better to do all of that via a single method?

**Comment by Wagnerp** [comment]
> > > Hi @Wagnerp,
> > > There are several properties in KManager that do more or less the same. Do you have a working code example of how to load a Custom theme?
> > 
> > 
> > Hi @giduac
> > You can use the `Import()` API to load a custom theme...
> 
> And which of the properties (preferably) to use for assignment?
> 
> Also the ThemeManager has a public method for loading themes. Is that really a necessity or wouldn't it be better to do all of that via a single method?

The `GlobalCustomPalette` property should be used if you have a `KryptonCustomPaletteBase`, **but** if this is assigned, it does not change the `GlobalPaletteMode` to 'Custom'.

**Comment by giduac** [comment]
@Wagnerp 

One more question: is there a form in TestForm for loading custom themes?

**Comment by giduac** [comment]
@Wagnerp 

Fixed, please close

**Comment by giduac** [comment]
@Wagnerp

Fixed, please close
