### ISSUE TITLE
[Bug]: `KryptonManager` - Setting the `GlobalPaletteMode` to 'Global' throws a error

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1093]
Whilst testing custom palettes, I noticed that setting the `GlobalPaletteMode` on `KryptonManager` to 'Global' throws a error.

![KManager](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9511873b-1b28-4624-8cda-ac789a957f73)

**Comment by giduac** [comment]
Hi @Wagnerp,

This one looks finished.
Can it be closed ?
