### ISSUE TITLE
[Bug]: Failed to create component `KryptonWorkspace`

### ISSUE THREAD

**Issue by msh2050** [Krypton-Suite/Standard-Toolkit#1097]
**Describe the bug**
when I drag the kryptonworkspace from the toolbox to the form I get an error 

**To Reproduce**
great krypton form and drag and drop the kryptonworkspace of dockablekryptonworkspace control 

**Screenshots**
![Screenshot 2023-08-12 011630](https://github.com/Krypton-Suite/Extended-Toolkit/assets/9201213/2fa9dd93-3884-4dc9-8304-b840d353dd18)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - visual stodio 2022
 - net framework 4.8.1
 

**Additional context**

**Comment by Wagnerp** [comment]
Moved to standard toolkit, as bug was filed in the incorrect repository.

**Comment by Smurf-IV** [comment]
@msh2050 Please can you state what version of the Framework you are using please ?

@Wagnerp Can the template be modified to ask for the framework / suite version as well ?

**Comment by Wagnerp** [comment]
> Can the template be modified to ask for the framework / suite version as well ?

@Smurf-IV Yes, sure. From the message it looks like it's version `70.22.12.312`. This is the latest stable version, not sure if it's present in v80?

**Comment by msh2050** [comment]
thanks for the replay Dears,
I can not reproduce the error,
before posting the bug I tried the latest stable and canary version and I tried the Suite.Extended.Ultimate 
all have the same error ...
then I tried with .net core 7 (it works) closed application and start a new .net framework and it is working now...
I don't know what was causing the error and how it is solved but I have to document my actions.

regards
