### ISSUE TITLE
[Feature Request] Problem with SwitchDockedCellToAutoHiddenGroupRequest

### ISSUE THREAD

**Issue by herledant** [Krypton-Suite/Standard-Toolkit#11]
Hello Wagnerp,

I don't know if it's a bug or a bad use of the function.

I try to switch programatically from a docked page to autoHidden Page.

This is working (docking):  

>  KryptonDockingManager1.SwitchAutoHiddenGroupToDockedCellRequest("Filters")

This is not working:

> KryptonDockingManager1.SwitchDockedCellToAutoHiddenGroupRequest("Filters")
![image](https://user-images.githubusercontent.com/9166449/81331811-74637c00-90a2-11ea-8927-dd7f11d19489.png)

I would like by clicking on a button to dock or undock the page.

Regards

**Comment by Smurf-IV** [comment]
I do not understand, If something is working, then put that in the code behind the click event for the "Pin" ?

Please add an example of what you current have ?

**Comment by giduac** [comment]
Hi @Smurf-IV,

This ticket from @herledant is awaiting feedback for a long time.
I suggest closing this, if needed it can be reopened....
