### ISSUE TITLE
[Bug]: `KryptonPropertyGrid` background colour/text don't display correctly for some (most) themes

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1108]
The `KryptonPropertyGrid` background colour/text don't display correctly in black (dark modes)

![263517148-fd846564-f893-4c55-84df-47894e396a67](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/fc6742ee-d3b3-4bd1-8e27-91bd0b280d4a)

**Comment by Smurf-IV** [comment]
Not just the PropertyGrid, also the comboBox's:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ddd75e5b-7e6e-4317-b8fe-e40b04ffc38a)

**Comment by Smurf-IV** [comment]
Silver is "broken" as well:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ae469c25-defd-4ea1-ab85-9c9d753c1ddc)

**Comment by Smurf-IV** [comment]
BUT:
Using the PropertyGrid example, the above is unproduceable ??
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/d634ca60-e815-4d0a-9186-77825c38a4bd)

Then switch to silver:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/94b74266-c9a6-49c7-8139-7bce344e907c)

**Comment by Wagnerp** [comment]
@Smurf-IV Do we know what palette colour entry the text is using?

**Comment by Wagnerp** [comment]
Wait... why is the text using the `ButtonText` and _not_ the `LabelText` entry?

**Comment by Wagnerp** [comment]
Ok, I found out why, the text is using the `TextButtonNormal`. We can't use white button text in O2k7 themes due to the glossy background. The solution is to use `TextLabelControl` for the text colour. Hope this makes sense?

**Comment by Smurf-IV** [comment]
The "Colours" are coming from 
`_stateCommon = new PaletteInputControlTripleRedirect(_paletteRedirect, PaletteBackStyle.InputControlStandalone, PaletteBorderStyle.InputControlStandalone, PaletteContentStyle.InputControlStandalone, null);`

I'll check what `PaletteBackStyle.InputControlStandalone` can be replaced with to give `TextLabelControl` equivalent(s)
