### ISSUE TITLE
[Bug]: `KryptonPropertyGrid` 'jagged' text

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1109]
While investigating #1105, I noticed that the text in `KryptonPropertyGrid` was 'jagged' 

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9e01fd6e-7dfe-41ba-a2c4-66074f0889cf)

This does not happen in the designer

**Comment by Smurf-IV** [comment]
The "Jagged Text" is a result of the following being set to `true`:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/5599c1ea-0461-4af7-8460-7686c143ccd8)

**Comment by Wagnerp** [comment]
@Smurf-IV Might be worth putting a note about this in the `Readme`
