### ISSUE TITLE
[Feature Request]: Themeable `KryptonToolTips`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#111]
**Is your feature request related to a problem? Please describe.**
Is it possible to have `KryptonToolTips` that follow the krypton theme design, i.e Office 2007/2010/365 blue, black & silver?

**Comment by Smurf-IV** [comment]
Good point.. 
Where as the "Normal Tooltips" are just system as well.
This will also need to be clearly documented !

**Comment by Wagnerp** [comment]
Maybe have corner rounding as well?

**Comment by Smurf-IV** [comment]
They already are Themed ....
![Tooltips](https://user-images.githubusercontent.com/2418812/179358791-9fa8fbbf-1252-4301-85c8-ad28afb20d50.gif)
