### ISSUE TITLE
[Bug]: Erratic mouse movements while using `KryptonNavigator`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1112]
_Originally posted by Tobias on Discord_

Hello. I've recently found Krypton Toolkit and, while converting my app, I encountered an issue where I have no clue where to start debugging.

I'm using an `Edge WebView2` control which hosts a javascript `three js` 3d-viewport. Mouselook can be toggled in this viewport and works as expected when the control is placed in a regular Form.

However, when I move the control to a `KryptonPage` with a simple docking setup, mouselook begins to jump around erratically with small mouse movements as seen in the screen recording.

I assume that this happens when the mouse cursor leaves the `webview` client area, but I don't know what is happening or why the problem only occurs with Krypton Docking. Do you have any ideas about what could be going on?

https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/ea9c07f9-87a8-4c5a-aefa-d3fc955e35b5

**Comment by Smurf-IV** [comment]
I seem to remember this being an issue with hosted ActiveX / WPF / Magic controls in the past.

Here is a specific with devs having problems (There are many search criteria that can be used for mouse event transitions that give advice for solutions):
https://github.com/MicrosoftEdge/WebView2Feedback/issues/425

**Comment by Smurf-IV** [comment]
@Wagnerp Please add the answer from discord and close

**Comment by Wagnerp** [comment]
> @Wagnerp Please add the answer from discord and close

@Smurf-IV Now added answer
