### ISSUE TITLE
[Feature Request]: Is it possible to have the KForm back colour as the KPanel colour

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1117]
Is it possible to have the default KForm back colour as the KPanel colour, rather than the system 'control' colour?

**Comment by Smurf-IV** [comment]
I thought the default was "Panel - Client" as the default,
Or have the recent changes to the Default values become corrupt "again" !!

**Comment by Wagnerp** [comment]
> Or have the recent changes to the Default values become corrupt "again" !!
Might have been 'lost', was that assigned to the `BackColor` values?

**Comment by Smurf-IV** [comment]
No.. Seems to be okay, when placing a new panel onto a form:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6019f804-f9dd-4ff5-8220-fd05f24e38cd)

**Comment by Smurf-IV** [comment]
Oops, I think I'm confusing things here..
You asked about the KForm BackColour, I assumed KForms had a panel by default now.
If not then I'm not sure "They" should have "Panel - client" as default.... If anything it should be:
`this.BackStyle = Krypton.Toolkit.PaletteBackStyle.FormMain;`

**Comment by Smurf-IV** [comment]
And....
As per other K Controls, direct access to the `BackColor` in the design should not be visible:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e333ddcd-035e-46c4-83f9-304b591a662b)

And it seems that the `BackStyle` is not being used anyway ??

It's a bit of a mess at the Form level !

**Comment by Wagnerp** [comment]
> Oops, I think I'm confusing things here.. You asked about the KForm BackColour, I assumed KForms had a panel by default now. If not then I'm not sure "They" should have "Panel - client" as default.... If anything it should be: `this.BackStyle = Krypton.Toolkit.PaletteBackStyle.FormMain;`

Yes, as it would save time setting up a KPanel as the background to achieve the same thing. I did try using a KPanel as a 'embedded' control in the past, but that 'locked' everything out.

**Comment by Wagnerp** [comment]
I was thinking more of changing 

> And.... As per other K Controls, direct access to the `BackColor` in the design should not be visible: ![image](https://user-images.githubusercontent.com/2418812/265248246-e333ddcd-035e-46c4-83f9-304b591a662b.png)
> 
> And it seems that the `BackStyle` is not being used anyway ??
> 
> It's a bit of a mess at the Form level !

So the question is should this be part of `StateCommon` then 'hide' the `BackColor` property?

**Comment by Smurf-IV** [comment]
> So the question is should this be part of StateCommon then 'hide' the BackColor property?

Yes,
And:
- Hide Background image
- Hide Background image layout
- Hide Font, and use force the theme font (Unless overridden by the styles)
- Hide ForeColor
- Work out what "UseSystemBackColor" was trying to do

**Comment by Wagnerp** [comment]
> Work out what "UseSystemBackColor" was trying to do

I can answer this one... it was something I added to try & get this working. Will remove as part of the PR for #1072 :)

**Comment by Smurf-IV** [comment]
- Make the KryptonForm colors represents the controlled values from the StateCommon
- Remove Confusing Designer elements that try to override the StateCommon-Back settings
- 
![NormalFormColours](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/d13a23ec-226a-4a17-8db1-3468574e49b5)

**Comment by Smurf-IV** [comment]
Needs to be reimplemented to be compatible with "Ribbon Forms" and work out what makes it "Flicker" in certain implementations ....

**Comment by Smurf-IV** [comment]
In Testing:
- Designers work
- `TestForm` (From suite solution) works
- `Font Dialog` (And I suspect the other common dialog overrides) is **broken**!

**Comment by Smurf-IV** [comment]
`Docking` is now sorted:
![image](https://github.com/user-attachments/assets/c7cd047f-7e59-43aa-b1b3-e1c3f64604db)

**Comment by Smurf-IV** [comment]
MDI now fixed as well:
![image](https://github.com/user-attachments/assets/9082bc42-8d2c-4e6c-9aee-4cf45b2328a0)
