### ISSUE TITLE
[Feature Request]: WebBrowser is a Standard ToolBox Item, Why not have a Krypton Editor Wrapper as well

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#113]
**Is your feature request related to a problem? Please describe.**
There is a `RichTextBox Editor` Wrapper in Krypton, but not a standard `WebBrowser` (via `MSHTML`) `Editor` wrapper

**Describe the solution you'd like**
A Krypton themeable `WebBrowser Editor` in the standard Toolkit

**Describe alternatives you've considered**
- https://stackoverflow.com/a/59119227
- https://www.codeproject.com/Articles/15559/A-Windows-Forms-based-text-editor-with-HTML-output
- Converting RTF to HTML: http://www.codeproject.com/KB/vb/RTFToHTML.aspx
- https://github.com/joergkrause/netrix

**Additional context**
Even tho' the WebBrowser does not show in the Toolbox for a .net 5 winform project.
It is still usable

The following"May" be necessary (But didn;t seem to make a difference): 
If being used in .NetCore 3.1 and above, then the following works:
``` c#
<PackageReference Include="Unofficial.Microsoft.mshtml.NetStandard" Version="7.0.3300.2" Condition="$(TargetFramework.StartsWith('net5'))" />
```

**Comment by Smurf-IV** [comment]
https://www.openntf.org/Projects%5Cpmt.nsf/0/1D4AC915638D7193862571490030163F/%24file/E1.JPG

**Comment by Smurf-IV** [comment]
Why not go with "WebView2" I here you ask (Well I didnit but I asked myself ;-))

It turns out it could be done, but would then require a massive download in the projects to ensure that the developer, and the installer of the target developed application would work as expected:
More here:
https://weblog.west-wind.com/posts/2021/Jan/14/Taking-the-new-Chromium-WebView2-Control-for-a-Spin-in-NET-Part-1

**Comment by lorinkundert** [comment]
Legacy WebBrowser is deprecated and will disappear by end of year as per Microsoft, use WebView2

**Comment by Smurf-IV** [comment]
> 
> 
> Legacy WebBrowser is deprecated and will disappear by end of year as per Microsoft, use WebView2

But it has a lighter footprint, and lot's of things "Just work"; especially if all you need is a "Rich Text Editor"

**Comment by lorinkundert** [comment]
DOS has a lighter footprint too, haha

**Comment by Smurf-IV** [comment]
> 
> 
> DOS has a lighter footprint too, haha

And "Most" of it is installed by default ;-)
