### ISSUE TITLE
[Bug]: `KryptonNavigator` close button disappearing

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1130]
_Originally posted by 'Pixel-ink' via Discord_

Hello,
Has the Close button issue been fixed yet?
In design time you can set the filter to hide the "X" close button.
But, when you drag a page to a new location the "X" button appears.
I submitted this issue a year or so ago.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/879fccb8-a006-46af-a915-e2a2741750b9)

**Comment by Smurf-IV** [comment]
I cannot reproduce this with the Navigator or ribbon examples
