### ISSUE TITLE
[Feature Request]: Please provide multi-language support

### ISSUE THREAD

**Issue by kelilive** [Krypton-Suite/Standard-Toolkit#1135]
**Is your feature request related to a problem? Please describe.**
My customer is Chinese and I would like the software interface to display Chinese content.

**Describe the solution you'd like**
Provide multi-language version of resx to display Chinese content when my user selection area is set to Chinese.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Wagnerp** [comment]
Hi @kelilive 

This should be resolved with the `KryptonLanguageManager` in v80 coming in November. You can test this right now using the `Canary` packages.

**Comment by Wagnerp** [comment]
Hi @kelilive 

Does this relate to the controls?

**Comment by kelilive** [comment]
Sorry, just now seeing your reply. Is there a demo demo address? It would be great if you could be more specific, I'm not sure exactly where and how to use the two tech libraries you mentioned.

**Comment by Wagnerp** [comment]
Hi @kelilive 

The `KryptonLanguageManager` only relates to specific strings used in the toolkit. Have you tried toggling the `Localizable` property on a `KryptonForm`?

**Comment by kelilive** [comment]
Based on the designer is indeed the most common practice, but when I open it, the designer throws an exception, in which case it seems like I should fix the exception before I can continue. But form designer exceptions are usually more complex ones that need to be analyzed and troubleshooted for the cause, and I'm not sure how to deal with that.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/142982913/f57294f7-74ba-4577-9818-6b8106c0da93)

**Comment by Wagnerp** [comment]
@Smurf-IV Any ideas?

**Comment by Smurf-IV** [comment]
What branch is this ?

**Comment by Wagnerp** [comment]
> What branch is this ?

I think it's `alpha`

**Comment by kelilive** [comment]
> > What branch is this ?
> 
> I think it's `alpha`

It is based on the current master branch.

**Comment by Smurf-IV** [comment]
Then please test with the alpha or a Canary nuget

**Comment by kelilive** [comment]
Hi, @Wagnerp @Smurf-IV

I'm sorry, that's my problem. Microsoft Form Designer is designed that way and does not give a reasonable fix. It's unlikely in the future, as it's not imminently fatal. The most adopted answer in the link below is the best explanation.

https://stackoverflow.com/questions/481305/the-designer-must-create-an-instance-of-cannot-because-the-type-is-declared-ab
