### ISSUE TITLE
[Bug]:  BinaryFormatter is deprecated due to possible security risks and will be removed with .NET 9.

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1138]
Severity	Code	Description	Project	File	Line
Warning (active)	MSB3825	Resource "_imageList.ImageStream" of type "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" is deserialized via BinaryFormatter at runtime. BinaryFormatter is deprecated due to possible security risks and will be removed with .NET 9. If you wish to continue using it, set property "GenerateResourceWarnOnBinaryFormatterUse" to false.
           More information: https://aka.ms/msbuild/net8-binaryformatter	Krypton.Toolkit 2022 (net8.0-windows), Krypton.Toolkit 2022 (net9.0-windows)	Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Designers\UX\KryptonContextMenuCollectionForm.resx	1

 or :

``` c#
Severity	Code	Description	Project	File	Line
Warning (active)	MSB3825	Resource "_imageList.ImageStream" of type "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" is deserialized via BinaryFormatter at runtime. BinaryFormatter is deprecated due to possible security risks and will be removed with .NET 9. If you wish to continue using it, set property "GenerateResourceWarnOnBinaryFormatterUse" to false.
           More information: https://aka.ms/msbuild/net8-binaryformatter	Krypton.Toolkit 2022 (net8.0-windows), Krypton.Toolkit 2022 (net9.0-windows)	Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Designers\UX\KryptonContextMenuCollectionForm.resx	1
```

**Comment by Wagnerp** [comment]
Would this also affect the planned theme binary import feature?

**Comment by AngeloCresta** [comment]
the issue is opened also in the dotnet/winforms git
[https://github.com/dotnet/winforms/issues/9701#issuecomment-1803290602](https://github.com/dotnet/winforms/issues/9701#issuecomment-1803290602)

**Comment by AngeloCresta** [comment]
If you need to run the code in .net9 without changing the sources you can add this on the Toolkit project files
`
<PropertyGroup>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
		<NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
		<GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
</PropertyGroup>
`
Angelo

**Comment by Smurf-IV** [comment]
Remove the errant resx file, and then checked that the designer still works:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7b635ec8-5045-40cd-9952-be4ab057c707)
