### ISSUE TITLE
KryptonSplitContainer ContextMenu Not Available

### ISSUE THREAD

**Issue by MEGA-GAGA** [Krypton-Suite/Standard-Toolkit#1141]
When I create a .NET 6 project from scratch with Visual Studio 2022 Version 17.6.5, which is the actual one, add Krypton Toolkit from Nuget Package Manager, add a KryptonSplitContainer the context menu does not show up as in the Toolkit Examples.

When I work on base of the project from the examples every thing is fine. I assume it is something with the setttings of the project in the csproj, app.config or app.manifest file. On a first look I could not find out the reason and unfortunately I am not a professional at the site.

What is the cause of the behavior described above?

**Working**

![Snag_443b441](https://github.com/Krypton-Suite/Standard-Toolkit/assets/144467942/e98bef28-4eb1-465c-a25c-d58368f91b97)

**Not Working**

![Snag_4367573](https://github.com/Krypton-Suite/Standard-Toolkit/assets/144467942/6441e0a1-6dcc-4c3e-a5c5-e3e66545c184)

![Snag_436810b](https://github.com/Krypton-Suite/Standard-Toolkit/assets/144467942/7f6d3c2b-7c3d-4b22-b45c-97b9dbbb56a4)

Thank you!

**Comment by Smurf-IV** [comment]
Please see this:
https://github.com/Krypton-Suite/Documentation/blob/main/Documents/Development/Designer-Fix.md
