### ISSUE TITLE
[Question]: How do I set the size of page when calling KryptonDockingManager.LoadConfigFromArray or File

### ISSUE THREAD

**Issue by MEGA-GAGA** [Krypton-Suite/Standard-Toolkit#1142]
How can I achieve restoring the size of a page when calling KryptonDockingManager.LoadConfigFromArray or File?

E. g. "Docking Persistence 2022" project restores position and visibility but not size.

Thank you!

**Comment by Smurf-IV** [comment]
I suspect you can override via the callbacks when things are loaded. (Create and Custom data - I would go with the later)
Please see the example mentioned in the following:
https://github.com/Krypton-Suite/Standard-Toolkit-Demos/issues/234
