### ISSUE TITLE
[Bug]: when I drag a kryptonTextBox from the krypton.toolkit toolbox to the kryptonheadergroup control, the VS popup a errer dialog

### ISSUE THREAD

**Issue by socky886** [Krypton-Suite/Standard-Toolkit#1143]
**Describe the bug**
when I drag a kryptonTextBox from the krypton.toolkit toolbox to the kryptonheadergroup control, the VS popup a errer dialog 

**To Reproduce**
I install the krypton.toolkit form the nuget in the VS2022
1. drag and drop the kryptonHeaderGroup component to the  form1 designer
2. drag the kryptonTextBox from the toolbox and drop over  the panel of the kryptonHeaderGroup component.
3. and then See the error
4.  if I switch the krypton.toolkit to 70.22.11.312 the issue is also happen.
**Expected behavior**

**Screenshots**
![图片](https://github.com/Krypton-Suite/Standard-Toolkit/assets/27987791/9f4babaf-7c33-47c1-9441-2b6235c3f41f)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version: [e.g..net 6.0] 
 - Toolkit Version: [e.g. 65.22.4.94]

**Additional context**

**Comment by Smurf-IV** [comment]
Please see this:
https://github.com/Krypton-Suite/Documentation/blob/main/Documents/Development/Designer-Fix.md

**Comment by Smurf-IV** [comment]
@socky886 
Can this be closed now ?

**Comment by Wagnerp** [comment]
Things to note do not use the preview versions of VS

**Comment by giduac** [comment]
Hi @Wagnerp,

It's been a long time since @socky886 was asked if this could be closed...

I suggest to close this, if needed it an be reopened.

**Comment by Wagnerp** [comment]
Closing
