### ISSUE TITLE
[Bug]: Maximize and minimize bars get duplicated

### ISSUE THREAD

**Issue by JustAzex** [Krypton-Suite/Standard-Toolkit#1145]
-Bug Description:
When opening a sub-form in windows forms the top bar for maximizing and minimizing gets duplicated (image 1) when opening the form for the first time, after minimizing and maximizing the form it works as expected (image 2)

-To Reproduce:
Steps to reproduce the behavior (in our case):
1. Having an aplication as a main form that acts like a Fatherform
2. Open a Childform 
3. The maximize and minimize buttons are duplicated.

-Expected behavior:
Maximize and minimize bar not being duplicated upon entering the form.

Sent 2 screenshots, first is how it is bugged, second is how it is supposted to be

 - OS: Windows 11/Windows 10
 - Version: Any version
 - Framework/.NET Version: 4.8
 - Toolkit Version: 70.22.11.312

-Additional context:
We updated from version 4.6.0.0. We know its outdated and it doesn't recieve support anymore.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/62765788/e927e3fc-26c7-46c4-afc2-4b9e72db44dc)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/62765788/5659114a-dd5b-4fb0-a7f8-0b4fe19cbdae)

**Comment by Smurf-IV** [comment]
1) Can you replicate using the samples
2) Can you add a small demo project to this please ?

**Comment by JustAzex** [comment]
Hey there!

I'll be letting you here a sample proyect with the issue happening, I have to use a google drive link since the file is bigger thabn what GitHub allows.

https://drive.google.com/file/d/1_uiI8hP79pWra3m7pX401yCqJSw4PCiu/view?usp=sharing

**Comment by Smurf-IV** [comment]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6e1fc52d-2dd1-47c8-be80-4a14bd418f0e)

**Comment by Smurf-IV** [comment]
@JustAzex 
Try removing the build output / .vs / github / and other build generated files before creating the zip.
Should only then be a few MB's in zip :-)

**Comment by JustAzex** [comment]
[SampleProyect.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/13407910/SampleProyect.zip)
Here you have it!

**Comment by Smurf-IV** [comment]
@JustAzex re the sample project:
- "We" do not have `DevExpress`
- The Modules reference `Iritec.Windows.Forms` which is not included
- Please upgrade the Krypton references to 80.23.### **or** the latest alpha 90.xx.xx
- Please study how the "MDI Ribbon" demo application works (If I remember correctly: The child forms have to have a certain "Style")
- Create a new sample that only has Krypton Components
- Thanks

**Comment by Smurf-IV** [comment]
Appears to be fixed in current alpha

**Comment by JustAzex** [comment]
Is this version in the latest released AKA 80.24.3.64 or we still have to wait ?

**Comment by Wagnerp** [comment]
> Is this version in the latest released AKA 80.24.3.64 or we still have to wait ?

Hi @JustAzex Unfortunately not. It is fixed in the latest v90 canary build if you want to give it a try. The latest stable only fixes #1314.
