### ISSUE TITLE
[Feature Request]: MessegeBox CheckBox option

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1148]
Currently testing in `Extended-Toolkit`, but will be implemented in v90

![Animation](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/b35ea23d-abf7-4080-a692-979a1b473da2)

**Comment by Wagnerp** [comment]
@Smurf-IV I was wondering if I should create 2 more `ShowCore` methods, `bool` & `CheckState` to return the value of the checkbox. Thoughts?

**Comment by Wagnerp** [comment]
Maybe 'hook' into the existing `ShowCore` method to do a if/else?

**Comment by Smurf-IV** [comment]
Or 
- extend the DialogResult to be a masked enum and have a state for the check state.
- Have an accessor for the CheckState
- No more parameters, there are already a load that should not be there (i.e forced optional and it confuses the intellisense !)

**Comment by Wagnerp** [comment]
Might be the completely wrong way to do this, but:

```cs
 [Flags]
    public enum KryptonMessageBoxResult
    {
        None = DialogResult.None,
        Ok = DialogResult.OK,
        Cancel = DialogResult.Cancel,
        Abort = DialogResult.Abort,
        Retry = DialogResult.Retry,
        Ignore = DialogResult.Ignore,
        Yes = DialogResult.Yes,
        No = DialogResult.No,
        Checked = 8,
        CheckState = 9
    }
```

**Comment by Smurf-IV** [comment]
Flags have to be bitfields, so yes that's wrong.
If the "other" fields are sequential, then they will need to be converted to bit as well.
And I would stick the "New ones" right at the end of the int field.

BTW what is "CheckState" supposed to be different from "Checked" ?

**Comment by Wagnerp** [comment]
> BTW what is "CheckState" supposed to be different from "Checked" ?

Yes, the KCheckBox can have 3 states, `Unchecked`, `Intermediate` & `Checked`. Checked will be a 'normal' `bool` value`.

**Comment by Wagnerp** [comment]
@Smurf-IV Should the KMessageBox be extended to support this? The current implementation only returns a `DialogResult`, maybe a custom enum with various options is needed, i.e. bool, three state, `DialogResult`, string, timeout etc, & call it `KryptonMessageBoxResponseType`?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Should the KMessageBox be extended to support this? The current implementation only returns a `DialogResult`, maybe a custom enum with various options is needed, i.e. bool, three state, `DialogResult`, string, timeout etc, & call it `KryptonMessageBoxResponseType`?

No, BUT that new type should be available via a get call, so that it does not break existing code, Or modifications to the return type when keeping up with Winform changes

**Comment by Wagnerp** [comment]
> > @Smurf-IV Should the KMessageBox be extended to support this? The current implementation only returns a `DialogResult`, maybe a custom enum with various options is needed, i.e. bool, three state, `DialogResult`, string, timeout etc, & call it `KryptonMessageBoxResponseType`?
> 
> No, BUT that new type should be available via a get call, so that it does not break existing code, Or modifications to the return type when keeping up with Winform changes

I am looking at these for ideas...

https://github.com/sijinjoseph/MessageBoxEx

https://github.com/nmoschkin/MessageBoxEx

https://github.com/bezzad/BlurMessageBox (GPL-3 - can't use code)

https://github.com/DmitryGaravsky/AutoClosingMessageBox

https://github.com/JohannBlais/InformationBox (maybe a new feature request, since it's already in the extended toolkit?)

**Comment by Wagnerp** [comment]
Ok... so I asked ChatGPT for ideas on this, and it came up with the idea of using a persistent value. Wonder if we could modify the `Storage` API to do this?

**Comment by tobitege** [comment]
> Ok... so I asked ChatGPT for ideas on this, and it came up with the idea of using a persistent value. Wonder if we could modify the `Storage` API to do this?

How would that work? The box could be called for any number of purposes and each could have the option to not appear anymore.  
Isn't it more the responsibility of the coder who's using this to save/restore options for such?
Any you never know what the coder's preference for where and how to store app settings.

**Comment by Wagnerp** [comment]
Hi @tobitege 

> Isn't it more the responsibility of the coder who's using this to save/restore options for such?

Yes, I was going on the basis of adding **both** a bool & a `CheckState` return API, in addition to the current `DialogResult` one. You can test this theory using the toasts in the latest `nightly` build.

**Comment by Smurf-IV** [comment]
> Isn't it more the responsibility of the coder who's using this to save/restore options for such?

Agreed, It has to be part of the parameters being passed into the API: i.e. the coders responsibility for storage of the result from previous calls As it might also need to be reset for different versions etc.

**Comment by giduac** [comment]
Hi,

If I seen it correct then there's also an effort to incorporate a timer next to the checkbox. It might be a tall order to get all that working without creating breaking changes.

How about a sort of [MessageDialog](https://learn.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog?view=winrt-22621) like in UWP that can be instantiated, configured and then shown.

....

**Comment by Smurf-IV** [comment]
> How about a sort of [MessageDialog](https://learn.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog?view=winrt-22621) like in UWP that can be instantiated, configured and then shown.


I like this better, then MessageBox replicate winforms (As it should).. And this new thing can do whatever is trying to be shoe horned into KMB  currently.
It would require backing out a lot of changes,
But they would not be wasted, as they would go into the equivalent "new" thing, and then make KMB stable and drop in replaceable again.

**Comment by giduac** [comment]
Also the DialogResult enum remains intact and prevents confusion about all the additional values in there since DialogResult is not only used by KMessageBox

For example:
```cs
MessageDialog dlg = new();
dlg.Checked = false;
DialogResult res = dlg.ShowDialog();

if ( res == DialogResult.OK &&  dlg.Checked ) {
   . . .
}
```
In that instantiated dialog you can embed all kinds of nifty stuff like timers / hyperlinks / scrollable text / etc. and as soon as the user closes it you can examine the dialog properties for the choices the user made.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV, @tobitege & @giduac 

Closing this thread & will be opening a new feature request for the 'MessageDialog`, since it'll be a new feature. Will also remove changes made in the KMBox.
