### ISSUE TITLE
[Bug -> Enhancement]: `KryptonManager` Designer usage needs a drastic overhaul to allow "Sensible" usage of fields

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1151]
## Actions

- [X] Remove the `Font Size`   (as it is already covered by the actual font !) #1206
- [X] #1222
- [X] #1221
- [X] #1223
- [X] #1224
- [X] https://github.com/Krypton-Suite/Standard-Toolkit-Demos/issues/171
- [x] #1225
- [x] #1226
- [x] #1227

## Original is below
win10 22H2
KT Alpha 290 build
VS 17.7.5
.net48 & net7.0

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/91e214c7-fa66-4c76-bb9d-be203207e30b)

Running app:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/676962b0-028d-48c1-9a94-beaf1846a632)

**Comment by Smurf-IV** [comment]
Found the problem.
If the Designer has set a "GlobalPaletteMode" and a GlobalPalette font,
Then the font will be overridden in "Most" of the controls..
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ddf0d406-5ba8-4b01-a791-4583b7e7a3b5)

**Comment by Smurf-IV** [comment]
Applying a `CustomPaletteBase` to the `KryptonManager` also does not work:
Custom = 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1f9fd2c8-7910-492d-9668-937397de9ad7)
Manager in Designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c5d3769e-a7f5-4c66-8374-a7a5840a2626)
Shows the Font, but not the Dark theme...
Running:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/500047c2-eef6-4128-ae3b-d66b9598ba50)

@Wagnerp The whole of the designer for the KryptonManager is mess of circular resets !

**Comment by Smurf-IV** [comment]
@Wagnerp 
Q) Any ideas on how to ratify this ?

**Comment by Wagnerp** [comment]
> @Wagnerp Q) Any ideas on how to ratify this ?

@Smurf-IV Have the resets existed since the original CF implementation? If not, I wonder if we could use the `IsDefault` feature in the `GlobalId` API somehow?

**Comment by Smurf-IV** [comment]
comparing with the 202 version:
Apart from a few "Type Name Changes" and a some more themes added,
There is the addition of `public KryptonCustomPaletteManager? CustomPaletteManager`
The answer appears to be yes.

But 
Q) where is the history before 2020 ?

**Comment by Wagnerp** [comment]
> comparing with the 2020 version: Apart from a few "Type Name Changes" and a some more themes added, There is the addition of `public KryptonCustomPaletteManager? CustomPaletteManager` The answer appears to be yes.
> 
> But Q) where is the history before 2020 ?

@Smurf-IV [Here](https://github.com/Krypton-Suite-Legacy-Archive/Krypton-Toolkit-Suite-Extended-NET-5.470) is the previous code before the 2020 .NET/Core conversion

**Comment by Wagnerp** [comment]
It goes way back to November 2017

**Comment by Smurf-IV** [comment]
> It goes way back to November 2017

I was looking at the alpha branch ....

**Comment by Smurf-IV** [comment]
Proposal:
Leave as is for V8 
or attempt to fix now ? (Not sure how long the fix will take as it will have impact all sorts of things!)

Either way will introduce a "BIG" breaking change

**Comment by Wagnerp** [comment]
> Proposal: Leave as is for V8 or attempt to fix now ? (Not sure how long the fix will take as it will have impact all sorts of things!)
> 
> Either way will introduce a "BIG" breaking change

@Smurf-IV If it's going to require a big overhaul, I'd leave it for V9. Thoughts?

**Comment by Smurf-IV** [comment]
> @Smurf-IV If it's going to require a big overhaul, I'd leave it for V9. Thoughts?

Agreed.

**Comment by Smurf-IV** [comment]
A neater layout in Designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b7ec143d-d259-4e45-b96a-9dfbd9e714e9)
