### ISSUE TITLE
[Bug]: Unable to resize control dragged from Navigator via KryptonDockingManager.FloatingWindowAdding event

### ISSUE THREAD

**Issue by Ptkatz** [Krypton-Suite/Standard-Toolkit#1152]
In the latest version I changed FloatingWindow.ClientSize and still cannot resize the control, but it was possible before version 6.2201.4.
```
        private void kryptonDockingManager_FloatingWindowAdding(object sender, FloatingWindowEventArgs e)
        {
            e.FloatingWindow.ClientSize = new Size(600, 500);
        }
```

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/72463595-6ce5-4dd5-9ed7-930c625e4c6e)

**Comment by Smurf-IV** [comment]
This was caused by #452

**Comment by Smurf-IV** [comment]
PR in alpha coming to do this:
![DragStartBiggerThanMin](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e577be5f-72e2-46cf-88b0-b31c7c821f64)

**Comment by Ptkatz** [comment]
I used the alpha branch of the library, but an exception occurs when dragging the page.

![ezgif-2-8ab7a863c1](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/5876514e-b8a7-4123-ad4f-48cd7da343da)

**Comment by Wagnerp** [comment]
> I used the alpha branch of the library, but an exception occurs when dragging the page.
> 
> ![ezgif-2-8ab7a863c1](https://user-images.githubusercontent.com/112046443/277159953-5876514e-b8a7-4123-ad4f-48cd7da343da.gif) [ ![ezgif-2-8ab7a863c1](https://user-images.githubusercontent.com/112046443/277159953-5876514e-b8a7-4123-ad4f-48cd7da343da.gif) ](https://user-images.githubusercontent.com/112046443/277159953-5876514e-b8a7-4123-ad4f-48cd7da343da.gif) [ ](https://user-images.githubusercontent.com/112046443/277159953-5876514e-b8a7-4123-ad4f-48cd7da343da.gif)

@Ptkatz Was that using the code that was merged today?

**Comment by Smurf-IV** [comment]
@Wagnerp @Ptkatz This is what https://github.com/Krypton-Suite/Standard-Toolkit/issues/1153 is for.
