### ISSUE TITLE
[Bug]: `KryptonMaskedTextBox` mask feature not working

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1162]
_Originally posted by Zakk on Discord_

Hi

I am having some problems with `KryptonMaskTextBox`, I am defining the mask in the designer, but when running program, with the `KryptonMaskTextBox` mask, it's not possible to type any letter or number, I want to know if anyone can help me with this, I'm making a phone mask using `() ___=__`, but it does not work.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/2b01409e-5a42-43a1-9892-93d287b2a23b)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/b45ccf6a-e67a-4450-9e48-491b708bea2e)

**Comment by Smurf-IV** [comment]
I think you are using the wrong formatting inside the designer. Here is a representation for something similar via the demo app:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/37bf74e6-047a-4cc6-8e6a-2e4977232f75)

**Comment by Wagnerp** [comment]
@Smurf-IV Will update Zakk
