### ISSUE TITLE
[Bug]: Button Spec Krypton Context Menu (Canary)

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#1169]
Using Winforms NET6 with VS2022 on Windows 11.

Recently upgraded to Canary 80.23.10.296 and found an issue with Button Spec context menus. Did some checking and the issue appears in Canary 80.23.8.233. The KryptonForm ButtonSpec property KryptonContextMenu is assigned a KryptonContextMenu object, but the menu no longer appears when clicking the button. Thanks!

**Comment by sdreb3421** [comment]
Will this fix be captured in the new NET 8 release? Thanks

**Comment by Wagnerp** [comment]
> I know you guys are a small team, but you guys tend to introduce more issues than you fix. Context menus are fundamental.

Hi @sdreb3421 Is the issue with the `KryptonForm` or the `KryptonContextMenu`, as I've had a look at the `alpha` code and it seems to be ok?

**Comment by sdreb3421** [comment]
I'm not totally sure honestly, it could be either the button or the context menu. I have a KryptonForm with multiple ButtonSpecAny (ButtonSpecs Collection) in the title bar. Within the ButtonSpecAny designer properties I have assigned a KryptonContextMenu to the property. However, the menu no longer appears on click starting with Canary 80.23.8.233.

Here is the designer code to validate what is actually happening. 
// 
// btnFileMenu
// 
btnFileMenu.Enabled = ButtonEnabled.True;
btnFileMenu.KryptonContextMenu = menuFile;
btnFileMenu.Text = " File ";

**Comment by Wagnerp** [comment]
@sdreb3421 Would you mind uploading a small project demonstrating the issue, so I can verify what's going on?

**Comment by Wagnerp** [comment]
Wonder if it's defined as `null`

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/3e3469b1-62d3-41bb-81b7-489035bc60c1)

@Smurf-IV Any ideas?

**Comment by sdreb3421** [comment]
Here is a simple example of the issue. If you change the nuget package back to 80.23.7.305 then it works again. Thanks!

[KryptonContextMenuExample.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/13353668/KryptonContextMenuExample.zip)

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

I think that I've narrowed it down to [this](https://github.com/Krypton-Suite/Standard-Toolkit/pull/1073) PR

**Comment by sdreb3421** [comment]
Ahh, that makes sense. It's probably messing with the button spec clicks somehow.

**Comment by Smurf-IV** [comment]
> I know you guys are a small team, but you guys tend to introduce more issues than you fix. Context menus are fundamental.

Ouch..
That is why the alpha's and canary's get created.
This project is huge, and has a lot of implementations
Testing is done in the area the "Feature / bug" fix is in, but impacts on other parts "may" happen.
We try our best for the time We try to allocate to this unpaid endeavour.

Any way; I'll take a look.

**Comment by Wagnerp** [comment]
Building on @Smurf-IV last comment, any fix implemented won't make its way into v80, both:

A) It needs to be tested
B) If it's injected into `master` it'll mess up the development 'flow' between `canary` & `alpha` because `master` will be 'ahead' of these

**Comment by Smurf-IV** [comment]
![DefaultMenuAction](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/97db9c4c-ee77-43d4-bb92-b25552a529ce)
Also make sure that the default actions still work (i.e. Close button!)

**Comment by Smurf-IV** [comment]
Note: Workaround for Canary / Master V80 is to add a DropDown, as per the request PR that "Broke" the default.

**Comment by sdreb3421** [comment]
It's fine honestly. I'll just keep using 80.23.7.305

**Comment by Wagnerp** [comment]
> It's fine honestly. I'll just keep using 80.23.7.305

Hi @sdreb3421 

The fixes will be included in the next Canary, hopefully targeted for Wednesday with other fixes.

**Comment by sdreb3421** [comment]
Oh very nice, I didn't realize you found the issue, well done 👍🏼👍🏼👍🏼

**Comment by Wagnerp** [comment]
> Oh very nice, I didn't realize you found the issue, well done 👍🏼👍🏼👍🏼

It was to do with the 'new' drop down button spec type. We can't put it into v80, as this would cause 'merge hell' later down the line, with `master` being ahead of the other testing branches.

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

Please retry using `canary` build >= 326

**Comment by sdreb3421** [comment]
Working! Thank you, great work
