### ISSUE TITLE
[Feature Request]: Toolbar - 'standard item' images

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1171]
When inserting standard items to a toolbar or QAT, the images used should follow those that are used by the corresponding buttonspec items.

**Comment by Smurf-IV** [comment]
Can you expand on what you mean please ?
i.e. reading this cold, it does not have enough information...

**Comment by Wagnerp** [comment]
Currently, when a user clicks the 'Insert Standard Items' tag on ToolStrip, it'll insert system images. Wondering if a future KToolStrip could use those already implemented for the equivalent ButtonSpecs?
 
![1171](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/1e4466e4-cbe0-4c9f-9202-b022837025dd)

**Comment by Smurf-IV** [comment]
But, Toolstrip images can also be "Large", so that would mean having duplicate "Large" images as well, which would / might cause confusion.
`toolStrip1.ImageScalingSize = new Size(40, 40);`

**Comment by Wagnerp** [comment]
> But, Toolstrip images can also be "Large", so that would mean having duplicate "Large" images as well, which would / might cause confusion. `toolStrip1.ImageScalingSize = new Size(40, 40);`

Good point, as a developer could enlarge it for touch etc

**Comment by Wagnerp** [comment]
Not going to implement this.
