### ISSUE TITLE
[Feature Request]: KryptonDropButton without arrow

### ISSUE THREAD

**Issue by addyzorb** [Krypton-Suite/Standard-Toolkit#1173]
Please consider adding an option to remove/hide the dropdown arrow from the KryptonDropButton.

![menu](https://github.com/Krypton-Suite/Standard-Toolkit/assets/150266437/43eecbb1-e033-489d-ad22-55de38a877d2)

It could be useful e.g., if there is already text in the button so the user knows what to expect when clicks on it.

**Comment by Smurf-IV** [comment]
A way of doing this that "does not require any code changes inside Krypton", is to set a common image to be a transparent box.
Here is the equivalent with a black box:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e62dc3e8-d6ce-4f1b-8bd8-2d715d20a2e3)
