### ISSUE TITLE
[Bug]: `KryptonForm` Flickers when using features in #1117

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1175]
As noted by @AngeloCresta, this is caused by the looping in `VisualForm` as per comment in #1174 

```cs
// Force repaint of Background etc.
            OnBackColorChanged(EventArgs.Empty);
            OnBackgroundImageChanged(EventArgs.Empty);
            OnBackgroundImageLayoutChanged(EventArgs.Empty);
            OnFontChanged(EventArgs.Empty);
            OnForeColorChanged(EventArgs.Empty);
```

Might be better to move it in its own method?

**Comment by Smurf-IV** [comment]
I did not see any flickering when I was did this conversion. (And as not seen when the recording was done) 
Can I have a project that demonstrates it, as it might be some interaction with child controls that causes refreshing weirdness....

**Comment by Wagnerp** [comment]
> I did not see any flickering when I was did this conversion. (And as not seen when the recording was done) Can I have a project that demonstrates it, as it might be some interaction with child controls that causes refreshing weirdness....

Happens with a `StatusStrip`, will upload a demo shortly

**Comment by Wagnerp** [comment]
Edit: Ignore, can't get it to reproduce

**Comment by Smurf-IV** [comment]
> Edit: Ignore, can't get it to reproduce

Is the code still removed ?

**Comment by Wagnerp** [comment]
> > Edit: Ignore, can't get it to reproduce
> 
> Is the code still removed ?

Yes, because that particular block still affects the ribbon.

**Comment by giduac** [comment]
Hi @Wagnerp & @Smurf-IV,

I tried this with build 80.24.3.64 and cant get it to reproduce.
Is this fixed then?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp & @Smurf-IV,
> 
> I tried this with build 80.24.3.64 and cant get it to reproduce. Is this fixed then?

Hi @giduac 

Partly, #1117 is still outstanding

**Comment by giduac** [comment]
@Wagnerp 
Not sure how those two are connected to one another?

**Comment by Smurf-IV** [comment]
> @Wagnerp Not sure how those two are connected to one another?

When the code is _restored_, then this bug becomes apparent.

**Comment by Wagnerp** [comment]
> @Wagnerp Not sure how those two are connected to one another?

Hi @giduac 

If you uncomment/restore code for #1117, you'll see what I mean

**Comment by Smurf-IV** [comment]
#1177 has been done a different way, so this can now be closed ;-)
