### ISSUE TITLE
[Bug]: KryptonProgressBar: small values escape drawing area: Toolit 80.23.11.320

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1176]
Appreciate the work done with progressbars ( rounding etc ) but

The coloured area is outside of the rounded progressbar at the start ( when around 20% is reached it fixes itself )
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/84494183/0ca20f67-678c-4505-99d0-0201e2025aac)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/84494183/c363b201-ddcc-4bd2-b76c-8a21278b7209)

The area outside the rounded portion is still visible
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/84494183/3a4e82d2-05ec-4319-8355-56ceb4f96ce2)

**Comment by Smurf-IV** [comment]
Yupe, Spotted now :-(
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/407d60f0-522c-4dd5-a38e-6b8a7aa0d61e)

**Comment by Smurf-IV** [comment]
Sorted:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c16ffa2f-4019-4119-8e6a-6c844c51d6b8)

**Comment by MattH-Work** [comment]
Just testing V90
Appreciate that the small values no longer escape
![image](https://github.com/user-attachments/assets/3ccc1b41-ed3f-40ec-b60d-00e82e587d78)
but
The progress bar background is still visibale againts the form
![image](https://github.com/user-attachments/assets/5176eeda-4296-4314-8d79-33f14c597940)

**Comment by giduac** [comment]
KButton has to also...

**Comment by Wagnerp** [comment]
So does the KForm...

**Comment by Smurf-IV** [comment]
i.e the default background for Krypton Components is the same as a KryptonPanel, which they expect to be placed upon.
Therefore, set the background to be transparent if placed onto a "Normal" Winform area.

**Comment by MattH-Work** [comment]
With the progressbar, I cannot find anywhere to change the background colour
![image](https://github.com/user-attachments/assets/aa3c66df-ef30-420a-b447-b277a8099ebd)

**Comment by Smurf-IV** [comment]
A few things..
- Can this be moved into a separate item (i.e. new bug / discussion)
- Why are expecting Krypton components to work on a non Krypton panel
- Krypton Form **does not** use the theme backgrounds, and "_currently_" needs to have a Panel docked by the developer to get it to work correctly.

**Comment by MattH-Work** [comment]
_"Why are expecting Krypton components to work on a non Krypton panel"_

Why would I not?

**Comment by Smurf-IV** [comment]
> _"Why are expecting Krypton components to work on a non Krypton panel"_
> 
> Why would I not?

Just a question ;-)
Have you tried setting the border to transparent, and a "Fat value" ?
In the mean-time, please open a new item for the scenario you are using this in, so that it can be reviewed and worked on in the V90 timescale.
