### ISSUE TITLE
[Feature Request]: MDI Parent Forms

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1185]
Looking through the C# items, one thing that is missing is the Krypton equivalent to an 'MDI Parent Form'.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6f841ceb-631a-497b-9f6d-19fc5be1f5c5)

**Comment by Smurf-IV** [comment]
> Looking through the C# items, one thing that is missing is the Krypton equivalent to an 'MDI Parent Form'.

How so, it is implemented:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/52278d42-2276-44ea-b13a-995d302fc9e9)

And
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f417b2dd-d293-42db-8285-4d2896717646)

**Comment by Smurf-IV** [comment]
@PWagner1 can this be closed ?
