### ISSUE TITLE
[Bug]: The Context and Next/Pervious buttons of the KryptonDockableNavigator cannot be used

### ISSUE THREAD

**Issue by Ptkatz** [Krypton-Suite/Standard-Toolkit#1189]
Krypton Versin: Stable 80.23.11.321

https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/16b73782-da54-4c81-be15-ce1292e24c43

**Comment by Ptkatz** [comment]
The Context button of the KryptonDockableNavigator control cannot drop down the list when clicked.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/f9e3fcd5-cb9e-4fdd-843f-fa38f7906cbe)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/75e04819-d8d2-492f-a5be-9f810b04d9fa)

**Comment by Smurf-IV** [comment]
This has been fixed (I think) in the latest alpha, can you give that a try ?

**Comment by Wagnerp** [comment]
Or todays `canary` build 326

**Comment by Wagnerp** [comment]
Confimed working in latest `canary`

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/1098c8c0-b6bc-4904-8663-073d08b68f8a)
