### ISSUE TITLE
[Feature Request]: Use `TableLayoutPanel` for MessageBox Buttons

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1191]
Is it possible to use `TableLayoutPanel` for MessageBox Buttons, as you can set the padding via the designer rather than code. Plus it could reduce the amount of back-end code.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

Since a overhaul of the KMBox is being planned for V100 along with the introduction of https://github.com/Krypton-Suite/Standard-Toolkit/issues/1376, which will do more, I think this should be a V100 item.

Thoughts?

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV & @Ahmed-Abdelhameed

The current changes to KMB by @Ahmed-Abdelhameed are looking very good and will probably solve all known problems.
Imo, this will spare us a review of KMB further on and this can be closed.

**Comment by giduac** [comment]
> @Wagnerp & @Smurf-IV & @Ahmed-Abdelhameed
> 
> The current changes to KMB by @Ahmed-Abdelhameed are looking very good and will probably solve all known problems. Imo, this will spare us a review of KMB further on and this can be closed.

Closing because of the changes a while ago.
