### ISSUE TITLE
[Feature Request]: Re-route 'extra' `KryptonMessageBox` params to `KryptonMessageBoxData`

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1202]
As per discussion on PR #1199, Re-route 'extra' `KryptonMessageBox` params to `KryptonMessageBoxData` and set entries that are non winforms standard to obsolete.

**Comment by Smurf-IV** [comment]
`KryptonMessageBoxData` is no longer a class as the `KMBDep` has been removed in V100
