### ISSUE TITLE
[Bug]: Microsoft 365 - Black (Dark Mode) Drop button is not visible

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1207]
**Describe the bug**
Using today alpha and the toolkit test Form1

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/acc45c36-8c75-4934-ad46-f23ad2761ca8)

**Comment by Wagnerp** [comment]
I can add a 'ArrowColor' property, since it's set here:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/86603cfd-7266-477f-8c60-5bcf8ca682c1)

**Comment by Wagnerp** [comment]
@Smurf-IV Fixed, but this ought to be set within the palette itself, same w/ a KColorButton

![#1207](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8457321d-0766-4888-aae8-031e4095302b)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Fixed, but this ought to be set within the palette itself, same w/ a KColorButton

Create a Feature request so that it is "not forgotten"
