### ISSUE TITLE
[Bug]: "GlobalPaletteMode" Drop Box shows 4 "Globals"

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1208]
**Describe the bug**
Using todays alpha branch and the demo Form1 project

![Lot'sOfGlobals](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1bf616fb-fe98-40f9-ae6b-7e7880139271)

**Comment by giduac** [comment]
Hi @wagner,

Investigated this but in the current alpha branch this is not present.
I think this can be closed.
