### ISSUE TITLE
[Feature Request]: `KryptonRichTextBox` Why is it not possible to have the `ButtonSpecs` aligned to the top of a control

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#121]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/2418812/120158283-dc27c000-c1eb-11eb-92ba-7a667c78a563.png)

**Describe the solution you'd like**
Create a `Krypton Rich Text Box`
Add Some `button specs`
Attempt to align them to the top of the control - Fail

**Comment by MattH-Work** [comment]
Would it also be possible for multiple ButtonSpecs to be stacked vertical (1 column, multiple rows) aswell as the current horizontal (1 row, multiple columns) and maybe even arrayed (multiple columns & rows, proberly asking to much with that one!)
It would allow for more buttons without taking up more space, or reducing the input area of the control

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

Added this to V90, as it is classified as a bug

**Comment by Smurf-IV** [comment]
> Would it also be possible for multiple ButtonSpecs to be stacked vertical (1 column, multiple rows) aswell as the current horizontal (1 row, multiple columns) and maybe even arrayed (multiple columns & rows, proberly asking to much with that one!) It would allow for more buttons without taking up more space, or reducing the input area of the control

@MattH-Work 
Best to do that sort of thing in a separate control (and use a tableLayout for finer control like that!)

**Comment by giduac** [comment]
> I propose to remove the ability to "Add" ButtonSpecs to a RTB. @PWagner1 @giduac Thoughts ?
> 
> ![image](https://private-user-images.githubusercontent.com/2418812/394222978-3cf36e8d-cdeb-437e-97a1-39500ca6a611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjUyNzYsIm5iZiI6MTczMzgyNDk3NiwicGF0aCI6Ii8yNDE4ODEyLzM5NDIyMjk3OC0zY2YzNmU4ZC1jZGViLTQzN2UtOTdhMS0zOTUwMGNhNmE2MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMTAwMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmEzMmEwZTNhNWIyNDg3MzIzZDMxMWI4YzcxZGJhNWI5MDI3YWY1ZmEwMzY2YTQwYTI2ODFiYTY0MzVhNjhhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wAPuFg5psG6nlc4G_XATKbmHEKNoJNLH8QQdhDuurH8)

Changing the orientation keeps them vertically aligned in the edit window.
Can't see that anybody has been using those without filing a complaint...

So on that note, let's remove it.

**Comment by Smurf-IV** [comment]
**[Breaking Change]** 
    - `ButtonSpecs` have been removed from the `KryptonRichTextBox`
    - Use another layout to align in the designers
