### ISSUE TITLE
[Feature Request]: Button 'drop down' arrows should use palette text colour

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1211]
The button 'drop down' arrows should use palette text colour, as discussed in #1207.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/c6ef242c-aef5-4168-831b-c20458cb3d10)

Note: ColourButton has been done in #1212

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Theme-Palettes/issues/74

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Theme-Palettes/issues/74 is completing

**Comment by Smurf-IV** [comment]
![image](https://github.com/user-attachments/assets/3f5094ee-4f2d-49d6-b49b-1409535736d9)
