### ISSUE TITLE
[Feature Request]: KColorButton 'drop-down' arrow should be drawn

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1212]
The KColorButton 'drop-down' arrow should be properly drawn, rather than use an image.

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Theme-Palettes/issues/74

**Comment by Smurf-IV** [comment]
PR incoming:
01: Old method (#1211)
02: New draw and colour usage

![image](https://github.com/user-attachments/assets/c5567e63-e849-46be-b3c7-d2518c906ff3)

**Comment by Smurf-IV** [comment]
And Also:
![image](https://github.com/user-attachments/assets/cfe71dda-930a-4699-87c1-5aab8b961194)

**Comment by Smurf-IV** [comment]
**Breaking Change**:
![image](https://github.com/user-attachments/assets/e2edfabd-31b9-4379-8223-66655add74c2)
