### ISSUE TITLE
[Bug]: placing a KryptonStatusStrip in the Designer causes an exception

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#122]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2418812/120166249-4e040780-c1f4-11eb-9f4c-fe7e3945afd5.png)

**To Reproduce**
Unknown error occurs when placing a status strip (net48 project)
Perform the name change by hand, and then debugging visual studio gives the above Exception

**Comment by Wagnerp** [comment]
Fixed in the August 2021 (Canary) update
