### ISSUE TITLE
Move `GlobalPaletteMode` into `GlobalPalette` and rename

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1224]
![276123494-91e214c7-fa66-4c76-bb9d-be203207e30b](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/5e155d9a-98a6-48d2-a9be-3c8e55b14f18)

**Comment by Smurf-IV** [comment]
@Wagnerp thoughts?
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c45c6e34-d43e-4096-9b94-92e5ce072cdd)

**Comment by Wagnerp** [comment]
> @Wagnerp thoughts? ![image](https://private-user-images.githubusercontent.com/2418812/290999299-c45c6e34-d43e-4096-9b94-92e5ce072cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDE2MjMsIm5iZiI6MTcwMjc0MTMyMywicGF0aCI6Ii8yNDE4ODEyLzI5MDk5OTI5OS1jNDVjNmUzNC1kNDNlLTQwOTYtOWI5NC05MmU1Y2UwNzJjZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTU0MjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWIyNDcxMzNjZjdmYTMzOWFiOTM2NjFmYTBhNmIwODZmMjBmNTliZDgzYjMxNGRmM2FkNmFmOGZiOTk5ZGVjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rytFdXGnFJBoy4rCQwHqwKbsNQCzy1kX_OnW9WYNuz4)

Works well! :)
