### ISSUE TITLE
[Feature Request]: Use `SourceLink` for NuGet packages

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1232]
As per discussion https://github.com/NuGet/Home/issues/13081#issuecomment-1850588783

**Comment by Wagnerp** [comment]
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

**Comment by giduac** [comment]
@PWagner1 
This has been handled in another ticket short time ago ...?

**Comment by PWagner1** [comment]
> @PWagner1 This has been handled in another ticket short time ago ...?

@giduac 

Yes it was... closing.

**Comment by PWagner1** [comment]
Covered by #1792
