### ISSUE TITLE
[Feature Request]: Backport `StockIconId` feature

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1236]

**Comment by Wagnerp** [comment]
Seems that `StockIconId` is a .NET 8 & higher thing and does not contain **all** `shell32/imageres` images, https://github.com/dotnet/winforms/pull/8878/files#diff-7afffb5fcac7496d5621c334451483d531566e0c942c374df43e950dce4fe0ac.

**Comment by Wagnerp** [comment]
@Smurf-IV Ok, so I've been digging around in the 'WinForms' code, and it seems to be 4 additional files:-

- `StockIconId`
- `StockIconOptions`
- `SystemIcons`
- `Interop.SHGetStockIconInfo`

They seem to be independent, so...

**Comment by giduac** [comment]
@PWagner1 

You have look at this. 
https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shgetstockiconinfo

If this will be used it could lead to memory leak(s)  it says there if the icons aren't freed after use by DestroyIcon()...
