### ISSUE TITLE
[Feature Request]: Core 'Toast' UI

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1237]

**Comment by Wagnerp** [comment]
@Smurf-IV Some progress...

![1237](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/14a695da-5412-467b-bf9d-6dc54c7ec285)

**Comment by Smurf-IV** [comment]
That's a lot of wasted real estate..
I think it should not have a Form Title bar
Does it have "Positional" pop locations ?

**Comment by Wagnerp** [comment]
> Does it have "Positional" pop locations ?

Can allow for location changing

> I think it should not have a Form Title bar

Will set border to 'none' _if_ close box = false

> That's a lot of wasted real estate..

Will make it 'smaller'

At the moment, I just want to get the fundamentals working before tinkering with the UI :)

**Comment by Wagnerp** [comment]
Revised version

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/acc8401d-6271-4901-90a5-3d219a86a678)

**Comment by Wagnerp** [comment]
Some changes

![1237](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/81e85bed-8674-48d0-b36c-15b7ba51dfe4)

**Comment by Smurf-IV** [comment]
Can  / Will it have a checkbox option, for things like "Do not show again" style workflows ?

**Comment by Wagnerp** [comment]
Now featuring progress bars!

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/fb98512b-8174-4399-975e-c10a05b27f6e)

**Comment by Wagnerp** [comment]
> Can / Will it have a checkbox option, for things like "Do not show again" style workflows ?

Yes, and user inputs
