### ISSUE TITLE
[Feature Rerquest]: When setting `AllowFormChrome = false`, then the Form Bar should still be Theme rendered

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#124]
**Describe the bug**
As per discussion in  #114.

**Expected behavior**
When setting `AllowFormChrome = false` then the Form Title bar should still follow Krypton themeing

**Screenshots**
![image](https://user-images.githubusercontent.com/2418812/120177613-86a9de00-c200-11eb-9b46-f859b5ae81f4.png)

**Comment by Smurf-IV** [comment]
- `AllowFormChrome` has been removed and replaced with `UseThemeFormChromeBorderWidth` to better explain what it is doing
 - It means that a theme can get closer to "Material Design", and that the Title bar can still be themed (And rounded)
 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/306f977e-4980-4761-8eaf-ee4710ad11af)

Things of note in the above image:
- "Form1" is the normal Blue themed bar and border
- "Form7" is the child form with:
  - `UseThemeFormChromeBorderWidth` set false
  - Form Rounding = 10
  - Still resizeable
  - Still "Clips" correctly at the corners (See the right button clipping)

**Comment by Wagnerp** [comment]
> `AllowFormChrome` has been removed and replaced with `UseThemeFormChromeBorderWidth` to better explain what it is doing

Should this be mentioned as a "breaking change"?

**Comment by Smurf-IV** [comment]
> > `AllowFormChrome` has been removed and replaced with `UseThemeFormChromeBorderWidth` to better explain what it is doing
> 
> Should this be mentioned as a "breaking change"?

Yes. It will be in the PR that performs the fixes above.
Got to go and check that it does not break ribbon etc ;-(

**Comment by Smurf-IV** [comment]
- `AllowFormChrome` has been removed and replaced with `UseThemeFormChromeBorderWidth` to better explain what it is doing
 - It means that a theme can get closer to "Material Design", and that the Title bar can still be themed (And rounded)
 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/306f977e-4980-4761-8eaf-ee4710ad11af)

Things of note in the above image:
- "Form1" is the normal Blue themed bar and border
- "Form7" is the child form with:
  - `UseThemeFormChromeBorderWidth` set false
  - Form Rounding = 10
  - Still resizeable
  - Still "Clips" correctly at the corners (See the right button clipping)

An Example of the value change @ runtime:
![example](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1a0ee745-1f1b-4faa-824f-f7b0dd35b406)
