### ISSUE TITLE
[Bug]: KryptonDataGridViewComboBoxColumn Ignores ValueMember in Binding

### ISSUE THREAD

**Issue by cuppm** [Krypton-Suite/Standard-Toolkit#1241]
**Describe the bug**
The KryptonDataGridViewComboBoxColumn appears to ignore the property you specify in the DataSource object to use as the ValueMember.  When parsing the value to send to the data bound property it sends the value of the DisplayMember.  If you change the DisplayMember to be the ValueMember, it displays the wrong item in the dropdown control but will successfully save the selected item's value to the DataGridView's row item.

Here is a simple example that shows the behavior.
[Program.cs.txt](https://github.com/Krypton-Suite/Standard-Toolkit/files/13709049/Program.cs.txt)

**To Reproduce**
1. Build and run the attached simple app
2. Click "Yes" button to run as Krypton version
3. Create a new row by entering a test value in Name column.  When you leave the cell it will display the value that was attempted to be parsed and set to the data bound object for the row in the top textbox at the bottom.  Note that the Option column displays the string value of Guid.Empty instead of the expected "_Blank_"
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/2c1e42a1-6ebd-4f90-a6bd-2963fa6f2561)
4. Open the dropdown for the first row and select "Option 2", then leave the cell to force the parsing
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/08d096d8-4df3-4423-9c7c-059b58902c68)
5. The bottom textbox at the bottom shows the exception message thrown by the datagrid and the top shows the value it tried to parse was the "Option 2" instead of the guid value for that option.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/7257f6e8-e581-4053-a71a-3edbf718b426)

**Expected behavior**
If you run the simple app and select the "No" button at startup to run the WinForms version, it will correctly bind to the ValueMember of the combobox DataSource.

Correctly displaying the Guid.Empty display value of "_Blank_":
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/501ac572-8983-4177-9cc6-55cc6730682b)

Successful parsing of Option 2:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/aa74f82b-0fb1-4c56-8e5b-a26a6b08a130)

**Screenshots**
inlined above

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version: 19045.3693
 - Framework/.NET Version: 4.8 
 - Toolkit Version: 80.23.11.321

**Additional context**

**Comment by DarthVader85PA** [comment]
Hey @cuppm 

I had the same problem. My workaround: I changed the column in the `KryptonDataGridView` to `DataGridViewComboBoxColumn` and did NOT use the `KryptonDataGridViewComboBoxColumn`. For the design I used the `FlatStyle`-property by setting it to "Flat".

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/482ba155-6dc1-4625-89ba-f8a5795fd4e2)

Merry X-Mas from Germany

**Comment by cuppm** [comment]
@DarthVader85PA Vielen Dank!  That'll do as a work around for now.  `FlatStyle = Flat` makes it much cleaner, can't say I've ever messed with that property before.

**Comment by giduac** [comment]
Hi @cuppm & @DarthVader85PA  cc: @Smurf-IV, @PWagner1 

A bit of a heads up here.

I've been testing with this and created another data source that has a string and decimal column. And using that one the value is actually retrieved as it should.

```cs
    public class Car
    {
        public string Model {
            get; set;
        }

        public decimal Price {
            get; set;
        }

        public Car()
        {
        }

        public Car(string model, decimal price)
        {
            Model = model;
            Price = price;
        }
    }
```
Can you have a look at this to see if this can be attributed to certain data types?
Maybe @DarthVader85PA has some more info concerning this...?

**Comment by giduac** [comment]
Hi @cuppm  & @DarthVader85PA 

I've had a test with a different list and class. Instead of using the Guid this uses a StringBuilder as a property.
Interestingly, this also works as intended.

```cs
        public StringBuilderItem[] GetStringBuilderItems()
        {
            return new StringBuilderItem[] {
                new ("item 1", "item 1 text"),
                new ("item 2", "item 2 text"),
                new ("item 3", "item 3 text"),
                new ("item 4", "item 4 text"),
                new ("item 5", "item 5 text"),
                new ("item 6", "item 6 text")
            };
        }

    public class StringBuilderItem
    {
        public StringBuilderItem()
        {

        }

        public StringBuilderItem(string strName, string sampleString)
        {
            this.StringBuilder = new StringBuilder(sampleString);
            this.Name = strName;
        }

        public StringBuilder StringBuilder {
            get; set;
        }

        public string Name {
            get; set;
        }
    }
```

Do you might have a different sample that produces the same error as the Guid based type does?

**Comment by DarthVader85PA** [comment]
Hello @giduac,

we have using ID fields with Integer-Values.
So have a look on my Demo. So I hope you see the issue.

[Uploading KryptonDemoDgvComboBox.zip…]()

**Comment by giduac** [comment]
Hi @cuppm & @DarthVader85PA,

A heads up here as there's no solution at the moment and it will "probably" take some more time to get this and the other grid problems sorted. wouldn't be surprised if there are more. Also we are all short of time for the time being or as always.

Found out myself than when using a datetime format in a krypton text column this can have weird effects... :-(

**Comment by giduac** [comment]
KryptonDataGridView and it components have several shortcomings which we will try to address in the V100 release or earlier if possible.

**Comment by giduac** [comment]
Hi @PWagner1, @cuppm & @DarthVader85PA,

A PR for this is underway.

I'd like to ask you to give this a test as soon as the next nightly will be out. 
Probably in the coming week.

Thanks.

**Comment by PWagner1** [comment]
Need to do this for V90 - Patch 1 (`V95` branch)

**Comment by giduac** [comment]
PR underway
