### ISSUE TITLE
[Bug]: Krypton Navigator - outlook full Nav Mode

### ISSUE THREAD

**Issue by almendieta** [Krypton-Suite/Standard-Toolkit#1243]
When you try to place krypton navigator in VS IDE, it crashes Visual Studio 2022. Krypton Navigator version: 80.23.11.231. Version 70 is working correctly, but get back to it it's a REAL nightmare.

**To Reproduce**
![error-krypton](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/13ed0df1-b66a-4250-a4cd-16b81f355cb3)

 - OS: Windows 10 64b
 - Version: 19042.631
 - Framework/.NET Version:  4.8.1
 - Toolkit Version: 70.22.12.312

**Comment by Wagnerp** [comment]
Hi @almendieta 

I think this has been fixed in v90, please retry using the either the latest `nightly` or `canary` build.

**Comment by Wagnerp** [comment]
Hi @almendieta 

Please re-test using todays `nightly`, build .8
