### ISSUE TITLE
[Bug]: Visual Studio do not open Form after Nuget-Package-Update

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#1245]
**Describe the bug**
Visual Studio crashes when open a KryptonForm after Nuget-Package-Update (Version 80...)

**To Reproduce**
1. Update Nuget-Packages for project to new version of Krypton.
2. Open form in Visual Studio Designer
3. Exception while opening the form will show
4. After click on OK, Visual Studio crashed and restarted

**Expected behavior**
Open KryptonForm in Visual Studio Designer

**Screenshots**
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/31c058fb-59ac-4b65-b638-e8a51e0c86eb)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Framework:  4.8.1
 - Toolkit Version: 80.23.11.321

**Comment by DarthVader85PA** [comment]
The error above will occurred in `KryptonNavigator` when I add the control in a split container (`KryptonSplitContainer`) and change the mode into "Outlook Full"... Perhaps it's helps!?

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/954ef2f5-4026-46b6-8b23-e1ed3bc3cd4a)

**Comment by DarthVader85PA** [comment]
Same Issue to #1243 
Sorry, can be handle in that thread.

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

I think this has been fixed in v90, please retry using the either the latest `nightly` or `canary` build.

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

I have installed `Canaray`, latest NuGet build. The bug in the designer still exists. Of course: only when I change the `Mode`-Property to `Outlook - Full`. My workaround: I set the property `Mode` to `Bar - RibbonTabs` and change it into `Outlook - Full` on runtime in Sub `New`.

Error in Designer:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/de61a94a-6152-4b89-9dc1-ddf5cf5f1fcb)

Workaround in Designer:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/54ac22cf-9b56-480b-87a5-09e8cce3c3b7)

Change Mode in runtime:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/eebb3779-e426-4a84-acb9-0b4babb45adb)

App in Runtime-Mode:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/23aae0d6-21bf-4360-840b-9f6ae11df34c)

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

I'm unable to replicate using the latest alpha build. Can you attach a demo project so I can take a look?

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp and a happy new year to you,

here my Demo, created with:
 - VisualStudio 2019 Professional 16.11.32
 - .NET-Framework 4.8.09037


[Test-Krypton.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/13809202/Test-Krypton.zip)

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Thanks for sending over a sample, and happy new year to you too. Unfortunately, I still can't replicate the issue, is it possible to attach a screen recording?

**Comment by DarthVader85PA** [comment]
Here my Error-Video.
I hope it helps?

https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/6ec3c3c2-f662-48d9-acd1-d87d5f483e5c

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Thanks for the reply, I've repeated the same steps on my latest 'dog fooding' (90.24.1.2) build in VS 2022, and it seems to be ok. Not sure if there might be a config issue, but the next `nightly` build is scheduled to drop next Monday 8/1. Would you mind retesting then?

![1245](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/da4fd019-dbd8-43fe-a84c-b9f24d43de0e)

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

I don't know but I tested it with VS 2017 Pro, VS 2019 Pro, VS 2022 Community. Same issue in each VS-Edition.
After I clicked OK, VisualStudio will crashed and restart. I removed `canary`-Nuget-Package and installed `nigthly`-Nuget-Package again.

For your info: I created all my WinForms-Projects with .NET-Framework (Ver. 4.8), NOT .NET-Core:
```
New Project => Language: VB/C#, Plattform: Windows, Project-Type: Desktop => Select Windows Forms-App (.NET-Framework) => Next => .NET-Framework-Version: 4.8
```

I will test it again next week.

**Comment by DarthVader85PA** [comment]
> Hi @DarthVader85PA
> 
> Thanks for the reply, I've repeated the same steps on my latest 'dog fooding' (90.24.1.2) build in VS 2022, and it seems to be ok. Not sure if there might be a config issue, but the next `nightly` build is scheduled to drop next Monday 8/1. Would you mind retesting then?
> 
> ![1245](https://private-user-images.githubusercontent.com/949607/293744738-da4fd019-dbd8-43fe-a84c-b9f24d43de0e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTU2MjAsIm5iZiI6MTcwNDIxNTMyMCwicGF0aCI6Ii85NDk2MDcvMjkzNzQ0NzM4LWRhNGZkMDE5LWRiZDgtNDNmZS1hODRjLWI5ZjI0ZDQzZGUwZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjFjMTJmYTQxNmRjYTcxMzFhZjQxZTFkMmUxZTE4MTJmYjU5N2I4NmJkODljZjNiMjM4NDRkZjQwMzZlMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1Q8vZ6mG4BTe1hNTeOLF3jf5M8mai0NHAMwIAx9K_0) [ ![1245](https://private-user-images.githubusercontent.com/949607/293744738-da4fd019-dbd8-43fe-a84c-b9f24d43de0e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTU2MjAsIm5iZiI6MTcwNDIxNTMyMCwicGF0aCI6Ii85NDk2MDcvMjkzNzQ0NzM4LWRhNGZkMDE5LWRiZDgtNDNmZS1hODRjLWI5ZjI0ZDQzZGUwZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjFjMTJmYTQxNmRjYTcxMzFhZjQxZTFkMmUxZTE4MTJmYjU5N2I4NmJkODljZjNiMjM4NDRkZjQwMzZlMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1Q8vZ6mG4BTe1hNTeOLF3jf5M8mai0NHAMwIAx9K_0) ](https://private-user-images.githubusercontent.com/949607/293744738-da4fd019-dbd8-43fe-a84c-b9f24d43de0e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTU2MjAsIm5iZiI6MTcwNDIxNTMyMCwicGF0aCI6Ii85NDk2MDcvMjkzNzQ0NzM4LWRhNGZkMDE5LWRiZDgtNDNmZS1hODRjLWI5ZjI0ZDQzZGUwZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjFjMTJmYTQxNmRjYTcxMzFhZjQxZTFkMmUxZTE4MTJmYjU5N2I4NmJkODljZjNiMjM4NDRkZjQwMzZlMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1Q8vZ6mG4BTe1hNTeOLF3jf5M8mai0NHAMwIAx9K_0) [ ](https://private-user-images.githubusercontent.com/949607/293744738-da4fd019-dbd8-43fe-a84c-b9f24d43de0e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTU2MjAsIm5iZiI6MTcwNDIxNTMyMCwicGF0aCI6Ii85NDk2MDcvMjkzNzQ0NzM4LWRhNGZkMDE5LWRiZDgtNDNmZS1hODRjLWI5ZjI0ZDQzZGUwZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjFjMTJmYTQxNmRjYTcxMzFhZjQxZTFkMmUxZTE4MTJmYjU5N2I4NmJkODljZjNiMjM4NDRkZjQwMzZlMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1Q8vZ6mG4BTe1hNTeOLF3jf5M8mai0NHAMwIAx9K_0)

Do you use Nuget-Package?

**Comment by Wagnerp** [comment]
> Do you use Nuget-Package?

No, I directly linked it, but testing it with NuGet now

**Comment by DarthVader85PA** [comment]
> > Do you use Nuget-Package?
> 
> No, I directly linked it, but testing it with NuGet now

Thanks a lot. 
Another question: What happens in this Sub: https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonGroupPanel.cs#L474

In this sub occured this error: a null check fails: Object reference was not set to an object instance

**Comment by Wagnerp** [comment]
@DarthVader85PA 

Something weird happens in VS 2022, it doesn't crash?

![1245-1](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/7c685f2c-e0f4-48ec-a29d-a7a34adebedc)

**Comment by Wagnerp** [comment]
> > > Do you use Nuget-Package?
> > 
> > 
> > No, I directly linked it, but testing it with NuGet now
> 
> Thanks a lot. Another question: What happens in this Sub:
> 
> https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonGroupPanel.cs#L474
> 
> In this sub occured this error: a null check fails: Object reference was not set to an object instance

That has appeared to have been resolved since

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Please re-test using todays `nightly`, build .8

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

I have updated to latest nightly build (NuGet). Good news: It works. :)
So now we can close this post and #1243 too I think. Thanks a lot!
