### ISSUE TITLE
[Bug]: `VisualMessageBoxForm` Throws Exception when run from Example Code

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1247]
Using todays alpha:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/861ef003-40bd-44cd-895b-33a8df7e408b)

Via:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/18f9f3b5-b34b-4aa9-b9f8-78e8aec9a628)

**Comment by Wagnerp** [comment]
Maybe put

```cs
if (string.IsNullOrEmpty(text))
{
       // Set link area length to 0
}
else
{
       // Set link area length to text.Length
}
```
