### ISSUE TITLE
[Bug]: Ribbon Form Bars are no longer Drawn with the theme colouring

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1249]
**Describe the bug**
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7cf5b49f-c58c-4b56-a25e-baaa7d9efe70)

**To Reproduce**
It's been like this since 2023-05-21 (The last time I created a release build of the Ribbon Gallery Example)

- In the design (Using todays Alpha) you can see the Theme colouring,
- When the application is run, it has the OS's Control Title frame BUT with the Orb drawn over it !

**Comment by Smurf-IV** [comment]
More Info:
Changing this does not do Anything !
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/46488682-aa97-4db5-a55f-81f3d03df5a0)

I suspect that it is "Stuck" to be true in the code somewhere !

**Comment by Wagnerp** [comment]
@Smurf-IV This is a Windows 7 aero thing, so from Windows 8 and up are also affected.

**Comment by Smurf-IV** [comment]
The screenshots are from Win 10 22H2 x64, so I expect the theme to be applied to the Form Bar !

**Comment by Wagnerp** [comment]
> The screenshots are from Win 10 22H2 x64, so I expect the theme to be applied to the Form Bar !

This might be a version checking thing. If I remember correctly, if you ran it in XP, the theme would apply to the title bar as well. I need to go back to Phil's original 2017 version & fire up a XP, Vista & 7 VM to check this...

**Comment by Wagnerp** [comment]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/d2275e7c-13cf-47aa-89c6-f660fb86bdb3)

Works as expected in XP

**Comment by Wagnerp** [comment]
Vista...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8a49d98e-e317-4e1e-82c4-94efbbe43756)

**Comment by Wagnerp** [comment]
7...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/97b6261d-ba84-49e5-abac-d6fe0121e13e)

A setting might be stuck

**Comment by Smurf-IV** [comment]
Where those apps the 4.4 versions or the V8 versions ?

**Comment by Wagnerp** [comment]
> Where those apps the 4.4 versions or the V8 versions ?

4.x versions from https://github.com/ComponentFactory/Krypton/tree/master/Bin

**Comment by Smurf-IV** [comment]
So what happens when running the V8 versions on the same Os's as above ?

**Comment by Wagnerp** [comment]
> So what happens when running the V8 versions on the same Os's as above ?

I'll get back to you... Does XP support 4.6.2?

**Comment by Smurf-IV** [comment]
> I'll get back to you... Does XP support 4.6.2?

No.
Perhaps Check with V5/6 ?
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/43009d50-0757-4042-85bb-70d85b099723)

**Comment by Wagnerp** [comment]
Going to test with v5.400 (.NET Framework 4)

**Comment by Wagnerp** [comment]
Version 5.400

Windows 11

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/cf75db6f-6a02-4eea-9934-f433a7844b86)

Windows 10

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9ac32093-0ce6-44d5-9f77-eab6079242e7)

Windows 8.1

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/c9edfe75-c01d-4685-b0db-9d7171abd551)

Windows 8

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/4ac6302c-5787-40dc-8609-db5d623fe63a)

Windows 7

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/b0dd42cc-a953-4b78-aab8-aa676ab73f1c)

Windows Vista

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8493489e-07a6-430d-a545-5ac8454dac19)

Windows XP

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/afe62af3-0eb7-45e6-a513-936b8effb850)

**Comment by Wagnerp** [comment]
It goes berserk when the classic theme is applied

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/a9f82079-b859-44a4-ab06-625c46264c1b)

**Comment by Smurf-IV** [comment]
So I see the Aero "Bing Turned off", 
But looking at the Outlook clone in Windows 8.1 - That is what i was expecting to happen regardless of the OS.

What I am seeing is when something similar to the "It goes berserk" for some instances of border style being applied to current alpha and windows 10.

So the "Bug Stands"; Make it work like the Win 8.1 outlook clone regardless of OS ! i.e
- Themed Title bar
- Visible Borders
- No Aero
- No Berserk mode drawing ;-)

**Comment by Wagnerp** [comment]
@Smurf-IV This is how Office looks if no Aero is applied

2007

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/fe610d8e-2354-4810-b456-c90fe22e2017)

2010

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/bfb3a114-7e64-49b5-ba81-65b315f2a773)

For 10/11 should it act the same, as I don't think that WinForms supports Mica etc?

**Comment by Smurf-IV** [comment]
That's a lot better, but that's not on win 10 or above is it ?

I'm not "Concerned" about the lack of Transparency (i.e. Aero per se) but about the theme being applied to the **Form And borders** when in ribbon mode for >= Win 8

**Comment by Wagnerp** [comment]
> but that's not on win 10 or above is it ?

No, it's the default if you choose the classic theme on Win Vista & 7. It would work well on 10/11, I think 'Aero' is controlled in the `General` > `DesktopWindowManager` class, maybe this:- 

```cs
 /// <summary>
        /// Is composition currently enabled for the desktop.
        /// </summary>
        public static bool IsCompositionEnabled
        {
            get
            {
                switch (Environment.OSVersion.Version.Major)
                {
                    // Desktop composition is only available on Vista upwards
                    case < 6:
                        return false;
                    case < 10:
                        // Ask the desktop window manager is composition is currently enabled
                        return PI.Dwm.IsCompositionEnabled();
                    //Win 10
                    default:
                        return UserSystemPreferencesService.IsTransparencyEnabled;
                }
            }
        }
```

**Comment by Wagnerp** [comment]
Re: Last comment, I wonder what would happen if you did this?

```cs
    case < 6:
    case 10:
      return false;
   case < 10
       ....
```

**Comment by Wagnerp** [comment]
@Smurf-IV PR incoming

![1249](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/4c962793-5bac-4ab6-a3b1-41e1c2cdfefe)

**Comment by Wagnerp** [comment]
@Smurf-IV Can we just make `AllowFormIntegrate` a Win 7/8 & 8.1 thing?

**Comment by Smurf-IV** [comment]
@Wagnerp Or remove it, as it does not make sense for a theme not to be applied !

**Comment by Wagnerp** [comment]
> @Wagnerp Or remove it, as it does not make sense for a theme not to be applied !

@Smurf-IV Might raise it as a new request, as I don't know how deep the feature goes
