### ISSUE TITLE
[Bug]: Why does `CornerRoundingRadius` override the KRyptonForm `StateCommon.Border.Rounding` value

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1255]
`CornerRoundingRadius` should not exist, because that is what the `StateCommon.Border.Rounding` value is for;

especially when it does the following:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f16e1029-d700-48ba-9d00-ced8b865b775)

This is very confusing when setting border values in the Statecommon and then it is overridden in the OnPaint, and if the other states are used to have different thicknesses !!

**Comment by Smurf-IV** [comment]
Suggest removal of `CornerRoundingRadius` from the designer!

**Comment by Wagnerp** [comment]
@Smurf-IV Yes
