### ISSUE TITLE
[Bug]: `KryptonThemeComboBox` does not sync with `KryptonManager`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1264]
After some testing, it would appear that the `KryptonThemeComboBox` does not sync with `KryptonManager` theme value

![Bug](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/94727684-f6ba-4e1e-9ac6-49fb536e0369)

**Comment by Smurf-IV** [comment]
The gif shows a designer issue, is that what this is about ?

**Comment by Wagnerp** [comment]
> The gif shows a designer issue, is that what this is about ?

Yes, though the KM seems to have extra entries as well

**Comment by giduac** [comment]
@Wagnerp ,
This can e closed as it has been solved through the work on theme selectors.
thanks

**Comment by Wagnerp** [comment]
> @Wagnerp , This can e closed as it has been solved through the work on theme selectors. thanks

@giduac 

Closing...
