### ISSUE TITLE
[Bug] Since V 5.400, the QAT button is supposed to perform the close, therefore the Close Form button should not be visible

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1266]
In the following images the "Close Form button" is disabled, but it should be not be drawn !

              Version 5.400

Windows 11

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/cf75db6f-6a02-4eea-9934-f433a7844b86)

Windows 10

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9ac32093-0ce6-44d5-9f77-eab6079242e7)

Windows 8.1

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/c9edfe75-c01d-4685-b0db-9d7171abd551)

Windows 8

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/4ac6302c-5787-40dc-8609-db5d623fe63a)

Windows 7

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/b0dd42cc-a953-4b78-aab8-aa676ab73f1c)

Windows Vista

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8493489e-07a6-430d-a545-5ac8454dac19)

Windows XP

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/afe62af3-0eb7-45e6-a513-936b8effb850)

_Originally posted by @Wagnerp in https://github.com/Krypton-Suite/Standard-Toolkit/issues/1249#issuecomment-1870452281_

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp, @Smurf-IV 

For your Info:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/1c99a691-0a3d-4f2c-aed1-c9d18664d6d5)

Windows 10
Krypton Version 70.22.11.312
Control `KryptonRibbon`, Property `AllowFormIntegrate`: True

**Comment by Wagnerp** [comment]
> Hi @Wagnerp, @Smurf-IV
> 
> For your Info: ![grafik](https://private-user-images.githubusercontent.com/32876506/294440651-1c99a691-0a3d-4f2c-aed1-c9d18664d6d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDUwODYsIm5iZiI6MTcwNDQ0NDc4NiwicGF0aCI6Ii8zMjg3NjUwNi8yOTQ0NDA2NTEtMWM5OWE2OTEtMGEzZC00ZjJjLWFlZDEtYzlkMTg2NjRkNmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4NTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTI1YzFiY2Y4ODQxMmRmYzExOTUzNTYyNjVkNTMwNmM3NGRlZmY1N2FmY2NlNTg3NzU0ODY4MjE2OTRjNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZccZmDREY4QxHWccrmlKYvI6yFEOPtevKgcP6hm1H0)
> 
> Windows 10 Krypton Version 70.22.11.312 Control `KryptonRibbon`, Property `AllowFormIntegrate`: True

Hi @DarthVader85PA & @Smurf-IV 

Thanks for the info, should `AllowFormIntegrate` be `False` for Win 10 and up, thereby 'fixing' #1249?

**Comment by Smurf-IV** [comment]
@Wagnerp @DarthVader85PA I think the last 2 comments should be in the linked bug, not this one.
This is about the usage of `QAT` and the Form `Close` button visibility

**Comment by Smurf-IV** [comment]
Done:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/83b66fc1-b881-46d9-a188-8f11d36a9dc8)

Via designer default of:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/8639e7d2-a1f0-4fd7-864c-6051c7372ca2)

**Comment by Wagnerp** [comment]
@Smurf-IV Should this also work for O2k10 themes, as I've tried this but it doesn't work?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Should this also work for O2k10 themes, as I've tried this but it doesn't work?

Depends if the Designer setting has been set to "true / false" as highlighted above

**Comment by Wagnerp** [comment]
> > @Smurf-IV Should this also work for O2k10 themes, as I've tried this but it doesn't work?
> 
> Depends if the Designer setting has been set to "true / false" as highlighted above

It is set to "true", see TestApp for example. Works with O2k7 & MS 365 themes.

**Comment by tobitege** [comment]
I'm having difficulties with the design decision to hide the close button so that the user has to double-click the "File" button as soon as Ribbons are used.  
That might have been the desire back in 2010 by MS, but it was/is a bad usability decision ever since.  
We are on Windows and in 2024.  
Please do not make it the default to hide the primary close button, i.e. "FormCloseBoxVisible" should be True as default.
