### ISSUE TITLE
[Feature Request]: Remove `AllowFormIntegrate` for Krypton Ribbons

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1269]
As per discussion in #1249, `AllowFormIntegrate` should be removed as it's a legacy feature that does not work well on modern versions of Windows.

**Comment by Wagnerp** [comment]
@Smurf-IV Whilst investigating I noticed that this feature is deeply entrenched with KForm composition code that also needs to be removed. Should I proceed,, as it would mean cutting off Win 7, 8 & 8.1 features?

**Comment by Smurf-IV** [comment]
> mean cutting off Win 7, 8 & 8.1 features

Please expand in this ?

**Comment by Wagnerp** [comment]
> > mean cutting off Win 7, 8 & 8.1 features
> 
> Please expand in this ?

When a ribbon app is running on Win 7, the aero glass will extend into the chrome. If we remove the composition code, it'll remove this feature

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/1ebb357f-1996-42b9-a1a6-f060e345e232)

Suggestion, turn `AllowFormIntegrate` on by default, or to make it a Win 7 feature only, hiding it in the designer

**Comment by Smurf-IV** [comment]
> `AllowFormIntegrate` on by default

That was my expectation, in that 
- Where-ever some code was checking for it, then it would just be true, i.e. no check just do it.
- Then this would lead to the composite code being removed as well.

> hiding it in the designer

No value to hide, as it does not exist.

**Comment by Wagnerp** [comment]
Fancy taking a shot at it? I may be over thinking it, as I thought  ` _allowFormIntegrate = Environment.OSVersion.Version.Major >= 6 || Environment.OSVersion.Version.Major < 10;` was meant to do this, or have OS version checking in the code?

**Comment by Smurf-IV** [comment]
@Wagnerp Win10 does have transparency for some apps
See the settings side bar:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/909b3efa-9a77-4c98-9ecd-4fba805cbf40)

Is the same sort of thing still in Win 11 ?

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, in Win 10 it's called Fluent UI, in 11 it's called Mica

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/5205a98e-3cdd-457b-a4e8-a8ef77ba2728)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9366d605-77e8-4a9b-bd65-2929261ca1eb)

**Comment by Smurf-IV** [comment]
@Wagnerp thoughts ?
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/33c2a580-62aa-4d60-9701-2854a9ec79f9)

Bottom is running on Win 10

PR coming soon - just doing some more testing

**Comment by Wagnerp** [comment]
> @Wagnerp thoughts ? ![image](https://private-user-images.githubusercontent.com/2418812/296538886-33c2a580-62aa-4d60-9701-2854a9ec79f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjIyNzIsIm5iZiI6MTcwNTIyMTk3MiwicGF0aCI6Ii8yNDE4ODEyLzI5NjUzODg4Ni0zM2MyYTU4MC02MmFhLTRkNjAtOTcwMS0yODU0YTllYzc5ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMDg0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE5NTdkZWNkYzZjYTMyMDQwMThiODcyZGE3ZmMyYjhmYjc4OGU4OTlmMzZjNTM0MGYxMTk2ZjNjNjgyMzY2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fxaaMriRvSm9T6FC1LdqRIZjmymz1YD-nrfYJXZQbgk)
> 
> Bottom is running on Win 10
> 
> PR coming soon - just doing some more testing

@Smurf-IV Might be worth asking for feedback when the Jan canary build is released?
