### ISSUE TITLE
[Feature Request]: `KryptonButton` - Wrap text

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1272]
_Originally posted by @blaktro on CF original repository_

"Please tell me that there is any way automatically wrap text for KryptonButon (default for System.Windows.Forms.Button).

I have been using the last licensed version of Krypton Toolkit (4.32) for many years and didn't know that it is open source now.
Unfortunately, the same 'feature' still exist here, it does not wrap text for buttons.

Problem may sound trivial but for localization of large project it's a huge pain."

**Comment by Smurf-IV** [comment]
Yes there is, as that is what is being done in the "Long Text" for CommandLink Buttons
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/645fb6fb-2a32-4481-b81e-12f31a01bb35)

And it can be set for normal buttons via these settings:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e17fcead-fde0-49de-b617-0446bb67e526)
