### ISSUE TITLE
[Bug]: The background of a disabled combo box is always painted in white and cannot be modified

### ISSUE THREAD

**Issue by kmsbecker** [Krypton-Suite/Standard-Toolkit#1279]
**Describe the bug**
the background of a disabled combo-box is always painted in white, regardless which background color was defined for the disabled state before.

**To Reproduce**

.MyKryptonComboBox.StateDisabled.ComboBox.Back.Color1 = System.Drawing.Color.Green
MyKryptonComboBox.Enabled = False

**Expected behavior**
the background of MyKryptonCombobox should now change to green, since it was disabled. Instead the background is painted in white (it is always painted in white, regardless of the background color it had in the enabled state before).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 21H2
 - NET Version: 4.8
 - Toolkit Version: 90.24.1.8-alpha

**Comment by Smurf-IV** [comment]
Just tested this with the demo app (Using Todays alpha), and I can state that it works as expected:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/cd05f8c8-1a95-46ec-ad3e-b7cc3c441049)

These are the designer changes:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f1a69686-94d6-40e1-8b5c-584fbc384f95)

**Comment by Smurf-IV** [comment]
@kmsbecker Can this be closed ?
Or can you provide an example where it does not work please ?

**Comment by Smurf-IV** [comment]
@kmsbecker Closing, as no feedback concerning it works in the demo app.
Please re-open with an attached demo zip if you still have the issue - Thanks
