### ISSUE TITLE
[Feature Request]: Implement User Input Types

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1281]

**Comment by Smurf-IV** [comment]
Can you put in an example pictures and a task for each of the "Types" please ?

**Comment by Wagnerp** [comment]
> Can you put in an example pictures and a task for each of the "Types" please ?

Yes, sure, it'll be stuff like textbox, combobox, numeric up/down etc

**Comment by Smurf-IV** [comment]
@Wagnerp This has a merge. Is it still open ?
And there are no images added !

**Comment by Wagnerp** [comment]
> @Wagnerp This has a merge. Is it still open ? And there are no images added !

Still open, I haven't done the RTL versions yet

**Comment by Wagnerp** [comment]
Working on this next week :)
