### ISSUE TITLE
How to not display the original title bar

### ISSUE THREAD

**Issue by xiaotangdou2021** [Krypton-Suite/Standard-Toolkit#1283]
After adding ribbon components, the original form title bar still exists compared to the old version, as shown in the figure below. The left side is the original component version, and the right side is the new version effect. How to achieve the same effect as the left side?
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/99980031/875e4909-c52c-4f3b-941c-1bda26ce0c9c)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/99980031/1376ed88-518d-41c9-9e2e-09047e76bc4b)
I want the first one. 
Thank，you.

**Comment by Wagnerp** [comment]
Hi @xiaotangdou2021 

Thanks for posting, this is a known bug and is currently under investigation #1188.
