### ISSUE TITLE
[Bug]: ComboBox does not update when Enabled is changed

### ISSUE THREAD

**Issue by KAINLabs** [Krypton-Suite/Standard-Toolkit#1296]
When changing the Enabled property from false to true, the color style remains disabled and the control cannot be interacted with, even though the property says it is set to true/enabled.

**To Reproduce**
1. Add a KryptonComboBox to a form and set the combo box's Enabled property to false at design time.
2. During runtime, programmatically change the combo box's Enabled property to true.
3. The combo box does not visually change, nor can it be interacted with.

**Expected behavior**
The visual color scheme should change to active/enabled and the user should be able to interact with it. 

**Desktop**
 - OS: Windows 10
 - Framework/.NET Version: 4.8
 - Toolkit Version: 80.23.11.321

**Additional context**
Looking at the source code for the KryptonComboBox, this issue may have something to do with there being 2 OnEnabledChanged override events in the control. The newer one has comments about not forwarding the event as a fix for issue 662.

**Comment by Wagnerp** [comment]
Hi @KAINLabs 

Thanks for reporting, just 'fixed' it, but changes don't show up in the designer. Any thoughts @Smurf-IV?

**Comment by Smurf-IV** [comment]
> but changes don't show up in the designer. Any thoughts @Smurf-IV?

You have to add an attribute so that the designer forces a refersh of the displayed control when the value changes.

**Comment by Wagnerp** [comment]
> > but changes don't show up in the designer. Any thoughts @Smurf-IV?
> 
> You have to add an attribute so that the designer forces a refersh of the displayed control when the value changes.

`RefreshProperties` attribute?

**Comment by Smurf-IV** [comment]
> RefreshProperties attribute?

Yes that's appears to be the one I was thinking about..

And / Or checking if `InDesignerMode` and calling `Refresh()` to perform a designer invalidate.

**Comment by Wagnerp** [comment]
Fixes may need to be applied to **all** controls.

**Comment by Wagnerp** [comment]
Hmm... I don't understand why this won't work?

```cs
 /// <inheritdoc />
        [RefreshProperties(RefreshProperties.Repaint)]
        public new bool Enabled
        {
            get => base.Enabled;

            set
            {
                base.Enabled = value;

                if (DesignMode)
                {
                    Refresh();
                }
            }
        }
```

**Comment by Smurf-IV** [comment]
@Wagnerp re: The commit referenced above; What did it do for this bug ?

**Comment by Wagnerp** [comment]
> @Wagnerp re: The commit referenced above; What did it do for this bug ?
> 
> Because you started down the designer route, when the Original was at runtime ?

@Smurf-IV Nothing, works at runtime but not in the designer. But I think this is standard WinForms practice.

**Comment by giduac** [comment]
@Wagnerp 

Is this one still on or cant it be closed, since Smurf added the wont fix label?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Is this one still on or cant it be closed, since Smurf added the wont fix label?

@giduac 

Works at runtime, but not in the designer, just like any other WinForm control. So I'd say yes.
