### ISSUE TITLE
[Bug]: Not Implemented - Please Submit?

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#1299]
**Describe the bug**
After Update to the last `canary`-NuGet-Release the following message box will shown:

**To Reproduce**
RibbonTab with context selected programatically.

**Screenshots**
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/127c358c-0c54-4dc9-84ec-d986c6b6a24d)
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/90704552-e2dd-45f8-b248-f20be7e740b4)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Visual Studio 2019 Pro
 - Framework/.NET Version: 4.8.1
 - Toolkit Version: 90.24.1.22 (canary)

**Comment by DarthVader85PA** [comment]
I have perharps some more information with following video and Exception-Stack-Trace:

https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/7b07d5e3-3ea8-4969-98f8-36df505c1ac0

## Exception-StackTrace: ##
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unbehandelte Ausnahme</Description><AppDomain>SchWaWi.exe</AppDomain><Exception><ExceptionType>System.InvalidOperationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Die Sammlung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.</Message><StackTrace>   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   bei System.Collections.Generic.List`1.Enumerator.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   bei Krypton.Toolkit.ViewControl.OnPaint(PaintEventArgs e)
   bei System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   bei System.Windows.Forms.Control.WmPaint(Message&amp;amp; m)
   bei System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   bei Krypton.Toolkit.ViewControl.WndProc(Message&amp;amp; m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</StackTrace><ExceptionString>System.InvalidOperationException: Die Sammlung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   bei System.Collections.Generic.List`1.Enumerator.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   bei Krypton.Toolkit.ViewControl.OnPaint(PaintEventArgs e)
   bei System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   bei System.Windows.Forms.Control.WmPaint(Message&amp;amp; m)
   bei System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   bei Krypton.Toolkit.ViewControl.WndProc(Message&amp;amp; m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</ExceptionString></Exception></TraceRecord>

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Thanks for reporting, it seems that there might be a missing 'state':

```cs
case PaletteRibbonBackStyle.RibbonGroupArea:
                    switch (state)
                    {
                        case PaletteState.Normal:
                        case PaletteState.CheckedNormal:
                            return PaletteRibbonColorStyle.RibbonGroupAreaBorder3;
                        case PaletteState.ContextCheckedNormal:
                            return PaletteRibbonColorStyle.RibbonGroupAreaBorder4;
                        case PaletteState.Tracking:
                            return PaletteRibbonColorStyle.RibbonGroupNormalTrackingLight;
                        case PaletteState.FocusOverride:
                            return PaletteRibbonColorStyle.RibbonTabFocus2010;
                        default:
                            // Should never happen!
                            Debug.Assert(false);
                            DebugTools.NotImplemented(state.ToString());
                            break;
                    }
```

Does this happen in _all_ themes?

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

Yes, the exception occures in every theme that i can choose.
I think there are many design issues here?

## Some Screenshots ## 
### Office 2010 Blue ###
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/0d6e0591-454d-4945-b47c-af7cdcb68f10)

### Microsoft 365 Blue ###
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/b7ecacd2-2bac-41d9-9611-14e8dfc3c62f)

### VisualStudio 2010 ###
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/4a816b54-e09c-460e-8577-2bb3d38e1b73)
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/68cd402a-086f-4805-b5e4-002153d4e7ef)

### Office 2010 Blue with Krypton Version 5.550.2106.1 looks create ###
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/32876506/79da0013-8164-4fa4-afb9-35c0f7f2be12)

**Comment by Wagnerp** [comment]
@Smurf-IV Is this something to do with the removal of `AllowFormIntegrate`?

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Are you able to put together a small demo, so I can investigate?

**Comment by tobitege** [comment]
Imho, the full KryptonCustomPaletteBase class needs to be re-checked wherever there's a "switch (state)" statement to get on top of this issue and avoid repeated reports about every single theme.

**Comment by Smurf-IV** [comment]
Agreed, there is a "LOT" of repeated code structure in the themes

**Comment by Wagnerp** [comment]
> Agreed, there is a "LOT" of repeated code structure in the themes

Anything image related _should_ be done in the base classes, and the theme classes should only control the colours

**Comment by Smurf-IV** [comment]
No idea why this was marked as _V85_, and it clearly states it's to do with V90 Nightly!

**Comment by Smurf-IV** [comment]
> Hi @Wagnerp
> 
> Yes, the exception occures in every theme that i can choose. I think there are many design issues here?
> 
> If I click on the Tab with Context ("Ressourcen"), so the error occoures too.
> ## Some Screenshots
> ### Office 2010 Blue
> 
> ![grafik](https://private-user-images.githubusercontent.com/32876506/299061369-0d6e0591-454d-4945-b47c-af7cdcb68f10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzAyMTksIm5iZiI6MTcyNDE2OTkxOSwicGF0aCI6Ii8zMjg3NjUwNi8yOTkwNjEzNjktMGQ2ZTA1OTEtNDU0ZC00OTQ1LWI0N2MtYWY3Y2RjYjY4ZjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE2MDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOWQzOGMwODM0NDE1ZTRkYWJlNTdjZjhhMGI4YzgzYWRhMTMxYTQ2Y2NmODRjYTE1ZDY5ZTNkMjgyM2YwNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHPjtgv3o_8jauXMErXRpAzQvnkPRac3Y3jNA2NcqFk)

Cannot seem to get those black lines using the build mentioned:
![image](https://github.com/user-attachments/assets/bea7d809-fcd9-42e4-9c50-af156f5e335b)

**Comment by Smurf-IV** [comment]
> Hi @DarthVader85PA
> 
> Are you able to put together a small demo, so I can investigate?

I am unable to reproduce using "90.24.1.22" nuget usage or Today's alpha of both Suite and Ribbon demo's debug code bases

**Comment by PWagner1** [comment]
Hi @DarthVader85PA 

Would you please confirm that this is the same as #1715?

cc. @Smurf-IV & @giduac

**Comment by PWagner1** [comment]
Hi @DarthVader85PA 

Please follow #1715 for updates.

cc. @Smurf-IV & @giduac
