### ISSUE TITLE
[Bug]: Bug in Krypton Workspace, versions 70 and 80

### ISSUE THREAD

**Issue by almendieta** [Krypton-Suite/Standard-Toolkit#1300]
**Describe the bug**
If you place a Krypton Workspace control in a form using VS 2022, add 1 or 2 pages, and after that (figure out) how to reach the KryptonWorkSpaceCell (I couldn't find a way to go straightly to change NavigatorMode in KryptonWorkspace properties), when you try to change mode to Outlook - Full, VS chrashes, so is not possible to use Outlook interface.

**To Reproduce**
1. Place a KryptonWorkSpace control in a VS2022 form
2. Change NavigatorMode to Outlook - Full
3. VS 2022 will crash.
Note: I'm using Windows 10 64b, PC: Intel I5, RAM: 12GB, VS2022 as noted already.

**Expected behavior**
In my opinion, NavigatorMode property must be placed directly with the other properties in KryptonWorkSpace control. It was driving me crazy trying to find a way  to change the WorkSpace interface, so I had to look at old (4.5) examples trying to get a clue. Finally accidentally found NavigatorMode property in a semi-hidden layer, called KryptonWorkspaceCell, changed this property and get the crash. If you know a better way to configure this control (not in code) to get it working quickly, I will thank you in advance for a tutorial!

**Desktop:**
 - OS:  Windows 10 
 - Version: 20H2 19042.631
 - Framework/.NET Version: 4.8.1
 - Toolkit Version: 70 and 80
 
**Screenshots**
![2024-01-23 20_31_20-Window](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/890faa71-a7a1-4785-933f-e7ea96ff89bb)

**Comment by Wagnerp** [comment]
Hi @almendieta 

Please try the latest `canary`, as this has been fixed in v90

**Comment by Smurf-IV** [comment]
@Wagnerp 
Can this be closed now ?

**Comment by Wagnerp** [comment]
> @Wagnerp Can this be closed now ?

Yes, since it's been 30 days with no comment from OP.

**Comment by almendieta** [comment]
Thanks for your response. After try Canary, now Krypton forms shows a steady black background, and some controls appear as a mosaic in one of them. Any idea about the reason? Thanks in advance for your answer.

**Comment by almendieta** [comment]
Just for clarify: I'm using Canary now, and all forms shows black background.

**Comment by Smurf-IV** [comment]
@almendieta 
Can you please add some pictures and an example src that shows this ?

**Comment by almendieta** [comment]
> @almendieta Can you please add some pictures and an example src that shows this ?

Please look attachments. Furthermore, background captures last screen inside form if you change tab.
![01](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/a50911be-3b87-4fcd-aaad-6e7ee2439868)
![02](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/d7b8f85b-5a90-4dbf-a1a7-c62e9d6102c6)

**Comment by Smurf-IV** [comment]
The second image is indicating that it is using a `transparent` colour as a background (Or EMPTY)
Probable Workaround:
- Place a KPanel in the Form 
- and set `Dock` to `Full`

**Comment by Wagnerp** [comment]
@almendieta & @Smurf-IV 

New entry for above opened here #1370

**Comment by almendieta** [comment]
> The second image is indicating that it is using a `transparent` colour as a background (Or EMPTY) Probable Workaround:
> 
> * Place a KPanel in the Form
> * and set `Dock` to `Full`

Thanks for the answer.  The problem it's a MDI form, and need to set a background random image in it each time it starts. I will try it anyway, thanks.

**Comment by Smurf-IV** [comment]
> Thanks for your response. After try Canary, now Krypton forms shows a steady black background, and some controls appear as a mosaic in one of them. Any idea about the reason? Thanks in advance for your answer.

#1370 bug raised for the KForms issue

**Comment by Wagnerp** [comment]
@almendieta Can you remember what build number you were using that this started?

**Comment by almendieta** [comment]
> @almendieta Can you remember what build number you were using that this started?

Not sure at all. Updated to Canary and did not see that detail. I will check anyway, hope to find any reference, but can not offer anything for sure.

**Comment by almendieta** [comment]
Krypton.Toolkit.70.22.11.312

**Comment by almendieta** [comment]
> @almendieta Can you remember what build number you were using that this started?

Hey, got this info: Krypton.Toolkit.70.22.11.312

**Comment by Wagnerp** [comment]
> > @almendieta Can you remember what build number you were using that this started?
> 
> Hey, got this info: Krypton.Toolkit.70.22.11.312

No problem, we've tracked the bug down to 90.24.2.45 (valentines day)

**Comment by Wagnerp** [comment]
So, referring to the first image, it lead me to this:

```cs
/// <summary>
        /// Raises the VisibleChanged event.
        /// </summary>
        /// <param name="e">An EventArgs containing the event data.</param>
        protected override void OnVisibleChanged(EventArgs e)
        {
            VisibleChanged?.Invoke(this, e);

            base.OnVisibleChanged(e);
        }
```

@Smurf-IV Shouldn't be `VisibleChanged!.Invoke(this, e);`?

**Comment by Smurf-IV** [comment]
@almendieta Now that the KForms is not doing the black area thing,
Can you try with an Alpha / nighlty build and see if this is still reproducible?

@Wagnerp I have removed the regression as this was also broken in V70, therefore it can be fixed n the V90 Release.

**Comment by almendieta** [comment]
> @almendieta Now that the KForms is not doing the black area thing, Can you try with an Alpha / nighlty build and see if this is still reproducible?

Ok, I will check it today. By the way, there are a number of bugs in DataGridView, and a strange focus issue with comboboxes, I guess that have to open a bug incident to those.

**Comment by Smurf-IV** [comment]
> By the way, there are a number of bugs in DataGridView, and a strange focus issue with comboboxes, I guess that have to open a bug incident to those.


Yes, Try and keep the bug to reporting against a single issue per component please ?

**Comment by almendieta** [comment]
![01](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/82aef219-3f21-48b1-bc3f-6496de369135)
Apparently now it's working. Same in run time.

**Comment by Wagnerp** [comment]
> ![01](https://private-user-images.githubusercontent.com/11827218/322228381-82aef219-3f21-48b1-bc3f-6496de369135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzc2OTksIm5iZiI6MTcxMzA3NzM5OSwicGF0aCI6Ii8xMTgyNzIxOC8zMjIyMjgzODEtODJhZWYyMTktM2YyMS00OGIxLWJjM2YtNjQ5NmRlMzY5MTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA2NDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0N2FjZmIyYmExNzIyYTc0ODU4ZjE1NzgwYmQ1ZTFkZTgyMmE2Njk3YmE5ZDEzMTUzNWU1NWM3ZTVlYzM4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UBu-wPVw7PUo-1AqcjE4ta165MCxIkUlFkqrJCRiSBs) Apparently now it's working. Same in run time.

@almendieta Is that with v90?

**Comment by almendieta** [comment]
> 
> @almendieta Is that with v90?
![01](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/c5d81a25-8c81-4a1e-bc7e-0ec4b0da54b7)
