### ISSUE TITLE
[Bug]: When Maximised - intergrated `KryptonRibbon` has titlebar issues

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1301]
While testing there are noticeable `KryptonRibbon` Issues including flickering title bars and offset context tab headers.

![Krypton Ribbon](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/38dcdecc-00a5-4014-9b29-fa0e9de3e3d1)

***Edit:*** Updated image for better clarity

**Comment by Smurf-IV** [comment]
@Wagnerp 
- Did / Does it also do this in Win 10 ?
- Does it do this with V80 or earlier ?

**Comment by Wagnerp** [comment]
@Smurf-IV 

> Did / Does it also do this in Win 10 ?

Yes, same result in Win 10 & the 'AppButton' O2k7 is affected as well

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/47f80fca-70a0-49e1-8015-c132180286bf)

> Does it do this with V80 or earlier ?

No, as it uses 'Aero' by default.

**Comment by Smurf-IV** [comment]
Problem happens between alpha releases 
90.24.1.15 - Ok
90.24.1.15 - Broken

**Comment by Smurf-IV** [comment]
Will try to investigate the following as well:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/1336#issuecomment-2016766817
, whilst doing this bug

**Comment by Smurf-IV** [comment]
> Problem happens between alpha releases 90.24.1.08 - Ok 90.24.1.15 - Broken

This PR did it
https://github.com/Krypton-Suite/Standard-Toolkit/commit/e750bc7b6222d57c36ff8cd6f01bea57b36dbf88
