### ISSUE TITLE
[Bug]: Font being used by "Professional" theme is pants !

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1302]
Using Todays Alpha and the Ribbon example.
The Font used by the "Professional" themes is _**very bad**_:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/3970012e-8f25-4420-a1f4-65aafd8c235b)

Compared this with the Office 2007 theme font:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ac6364d3-5bb6-45f4-a002-42b918949d0e)

**Comment by Wagnerp** [comment]
Maybe use Arial as the default for professional, or is this something else?

**Comment by tobitege** [comment]
Office 2007 default font was Calibri

**Comment by giduac** [comment]
Hi @Wagnerp,

It looks like this one has been tackled?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> It looks like this one has been tackled?

@giduac 

Append to v90 changelog list.

**Comment by Smurf-IV** [comment]
> Hi @Wagnerp,
> 
> It looks like this one has been tackled?

No, Still the same:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/bd380fc1-0a49-4ca1-94c5-21b59eb0c67a)

**Comment by Smurf-IV** [comment]
Note: 2007 Professional Blue looks okay:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c4d1f60e-42a0-4613-9bd0-47b00dc2754c)

**Comment by Smurf-IV** [comment]
If I remove the following from the `App.manifest` file, then it works (But looks pants)

**Comment by Wagnerp** [comment]
@Smurf-IV Is it something to do with the text rendering?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is it something to do with the text rendering?

But that should be affected regardless of the font.

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is it something to do with the text rendering?
> 
> But that should be affected regardless of the font.
> 
> And why in some apps does it not do it ? e.g.: https://github.com/giduac/Standard-Toolkit-Demos/tree/ribbon-controls-themes-test Demo Solution: Krypton Ribbon Examples 2022 (Debug) - Nuget Project: Application Menu 2022 TK: Latest Nightly 169

Is it something in the app manifest?

**Comment by Smurf-IV** [comment]
> Is it something in the app manifest?

Nope, they are the same, as is the program.cs.
No clues in the designer file either...

**Comment by Smurf-IV** [comment]
Found the "Problem". It will be a breaking change.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/5bee7cbf-201f-4503-b232-50d9780f7b2a)

**Comment by Wagnerp** [comment]
> Found the "Problem". It will be a breaking change. ![image](https://private-user-images.githubusercontent.com/2418812/341978253-5bee7cbf-201f-4503-b232-50d9780f7b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjc3OTEsIm5iZiI6MTcxOTA2NzQ5MSwicGF0aCI6Ii8yNDE4ODEyLzM0MTk3ODI1My01YmVlN2NiZi0yMDFmLTQ1MDMtYjIzMi01MGQ5NzgwZjdiMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMTQ0NDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M1OTYyNWJkYTE3ZjQwOWUwNWNjMDQ0ZmQ5M2E2ZmNiZjNhYjk5ZjYyMmFlN2JmOWM5YjFkZWQwNjFjZWM4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nVnhK7HEECj2Vw4p3AJljY82g4E_2ilusexlCR2KvUU)

What was it?

**Comment by Smurf-IV** [comment]
> What was it?

Usage redirect for this:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/3a801a68-1961-44aa-b21f-20b411f56255)
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.text.textrenderinghint?view=net-8.0

Which is "Not" appropriate for a theming suite like this !!
