### ISSUE TITLE
[Bug]: Palette color issues in v90.24.1.22

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1304]
For Krypton Toolkit v90.24.1.22-beta (via NuGet)

# **Issue**

Some builtin themes use fore-/background color combinations which make the elements' text either invisible or unreadable.

# **To Reproduce**

Using an app with Krypton ribbons (tabs and groups). A KryptonPage on a KryptonWorkspaceCell.
In it a KryptonPanel with a KryptonTreeView, a KryptonNumericUpDown, as example.
 
## Theme Microsoft365SilverDarkMode

Ribbon Tab normal titles appear as "white on white", i.e. unreadable, unless selected/tracked.  
A single KryptonPage in a KryptonWorkSpaceCell with "NavigatorMode" being "Bar - CheckButton - Group - Outside", the tab title appears as black on (very) dark gray, becoming unreadable.

## Theme Microsoft365BlackDarkMode 

Input controls, like a KryptonNumericUpDown have as input area background black as color, just like KryptonPanels.
Not sure if this is the desired effect, but a (very) dark gray - anything noticable above black - would serve the identifiability of the controls much better as they now appear like "labels" at first glance.
 
## Themes Microsoft365SilverDarkMode, Microsoft365BlueDarkMode
Ribbon group "sub titles" become invisible.  
A selected node within the treeview becomes unreadable as the text is way too close to the background color (no contrast).

# **Expected behavior**
Text of all elements should be clearly readable (visible) and not "melt" into the background.

# **Desktop:**
 - OS: Windows 11 Pro
 - Version: 23H2, Build 22631.3085
 - Framework/.NET Version: 4.8.1
 - Toolkit Version: 90.24.1.22-beta (via NuGet)
 - Visual Studio 2019, v16.11.33

**Comment by Smurf-IV** [comment]
Most of this is covered by:
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/883
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/876
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/619

@tobitege Can you add specific themes with pictures please ?

**Comment by tobitege** [comment]
## Microsoft365BlueDarkMode
see the KryptonPage tab (or whatever it is called), darker blue on dark blue gradient. Should be e.g. white font color (the below screenshot appears zoomed in, it is clearer to read than live on a 4K screen).
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/d6a4c690-1f3c-4d37-9e34-9f35e9c174b5)

## Microsoft365SilverDarkMode
Same as above, but also the ribbon tabs are completely invisible now (white on white):
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/1269411c-7fd9-44ad-90dc-799e40bace75)
Tree node selected, unreadable
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/d67d03f5-66a4-4fa1-97c8-864a73eaefb0)

## Microsoft365BlackDarkMode
Black background inside entry areas like numupdown component. 
Might be personal preference, but background should be a smidge brighter than that:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/0a69de37-4c4e-4ad3-a2f0-fd60431e20f0)

**Comment by Wagnerp** [comment]
> Black background inside user input areas like numupdown component.

Input areas do share common colours now (from Office 2021)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9c93ecde-48ec-42eb-b580-7d559bbc5314)

The normal black theme will retain a white background

**Comment by Wagnerp** [comment]
@Smurf-IV & @tobitege 

There does seem to be a white band now where tabs are. If this is solved, then it may fix several bugs.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/1cf43257-c4a1-4d17-bafc-68fed8c804e6)

**Comment by tobitege** [comment]
at runtime I use this to fix the white on white in the SilverDark theme:
myPalette.Ribbon.RibbonTab.StateNormal.TextColor = Color.Black;
either the theme has it as White or even empty?

**Comment by Wagnerp** [comment]
> at runtime I use this to fix the white on white in the SilverDark theme: myPalette.Ribbon.RibbonTab.StateNormal.TextColor = Color.Black; either the theme has it as White or even empty?

The white band will need to be fixed/removed as I think it's a old Aero/DWM thing. If you look at the O2k7 counterparts, they all work as expected.

**Comment by tobitege** [comment]
**Regarding the "Microsoft 365 - Black" theme**  

the KryptonTreeView shows nodes with white on white text as in below image (tested in Canary and Alpha):  

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/63d57384-db58-4f0c-83d3-c0d3a86ef60c)

**Comment by Wagnerp** [comment]
> **Regarding the "Microsoft 365 - Black" theme**
> 
> the KryptonTreeView shows nodes with white on white text as in below image (tested in Canary and Alpha):
> 
> ![grafik](https://private-user-images.githubusercontent.com/10787084/301815302-63d57384-db58-4f0c-83d3-c0d3a86ef60c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTEwOTEsIm5iZiI6MTcwNjg5MDc5MSwicGF0aCI6Ii8xMDc4NzA4NC8zMDE4MTUzMDItNjNkNTczODQtZGI1OC00ZjBjLTgzZDMtYzBkM2E4NmVmNjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWZhZTc0M2JkYzA5NWNjNDY0MmM2YmVjNzQxYzI4Zjc1NGExZmE5ODU3NjA2MDZjODEzZDlhMGI4NzZhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nt2XO5VAVxTS6UZGevXSWF1hsOGRKStCgsOB4n__m8)

@tobitege This uses `TextLabelContrl`, but no idea where it's assigned to?

**Comment by tobitege** [comment]
> @tobitege This uses `TextLabelContrl`, but no idea where it's assigned to?

I don't know the source that well, debugging a node drawing almost makes my brain melt. :D  

Eventually it seems to end up here:  
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/f0c54856-9ec4-4573-87fa-af35dd9a1a15)

This call stack is something else.... :P   
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/e03ea1fb-6d70-4633-9c09-8e335b6273ba)

Hopefully that helps

**Comment by tobitege** [comment]
I think the bug is in the PaletteMicrosoft365Black.cs file, where in line 144 the TextLabelControl color was set to White. In my screenshot I commented out that line activated the "old" colors, rebuilt the toolkit and tested again and the font color is readable again.  
However, I haven't checked if that change would be bad for any other components.  

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/1be5f7ff-50f5-4aa1-becb-9a125f92d545)

This is how it looks in my test app now:  
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/4700f4e2-64f3-44f5-a810-82f31f752682)

**Comment by Wagnerp** [comment]
> > @tobitege This uses `TextLabelContrl`, but no idea where it's assigned to?
> 
> I don't know the source that well, debugging a node drawing almost makes my brain melt. :D
> 
> Eventually it seems to end up here: ![grafik](https://private-user-images.githubusercontent.com/10787084/301943458-f0c54856-9ec4-4573-87fa-af35dd9a1a15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDY4MTgsIm5iZiI6MTcwNjk0NjUxOCwicGF0aCI6Ii8xMDc4NzA4NC8zMDE5NDM0NTgtZjBjNTQ4NTYtOWVjNC00NTczLTg3ZmEtYWYzNWRkOWExYTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA3NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMDJjOWFhOTA0YTY2Mjc0NTlmMjVjZWU1MTRkZTVhZmI0NzE1NTUyZWRiZDQ3ZWQ5MTRkNjIzMzZiZDViNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeRoKOrRCAHX_5p9IVomQf-vFoNiIIksRlR_RsWaKeU)
> 
> This call stack is something else.... :P ![grafik](https://private-user-images.githubusercontent.com/10787084/301943886-e03ea1fb-6d70-4633-9c09-8e335b6273ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDY4MTgsIm5iZiI6MTcwNjk0NjUxOCwicGF0aCI6Ii8xMDc4NzA4NC8zMDE5NDM4ODYtZTAzZWExZmItNmQ3MC00NjMzLTljMDktOGUzMzViNjI3M2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA3NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNmI0ZWVjMzM5N2U5YzY4MzM4NWFkM2Y0NjI3MTRhOGZjNzIxMzJhODU4ZWY5YjQ2MGVmZjhjMThiYmE3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXGvjXAQR2Zrg_duhcg3WT6PtUpskPCajmr_hsPaq1E)
> 
> Hopefully that helps

@tobitege Thanks for your help, it does assist, as I can now assign it to another colour :)

**Comment by tobitege** [comment]
In alpha branch currently, the Testform application in the standard toolkit, the MS 365 black and Office 2010 Black themes show white-on-white text in some areas (also in Treeview):
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/edeb1a93-97c3-4761-9d19-6f7c602d9fd4)

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/ecd81602-b990-4a29-8fe1-10e7db2818f5)

**Comment by Wagnerp** [comment]
> In alpha branch currently, the Testform application in the standard toolkit, the MS 365 black and Office 2010 Black themes show white-on-white text in some areas (also in Treeview): ![grafik](https://private-user-images.githubusercontent.com/10787084/303080327-edeb1a93-97c3-4761-9d19-6f7c602d9fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjc4MjQsIm5iZiI6MTcwNzMyNzUyNCwicGF0aCI6Ii8xMDc4NzA4NC8zMDMwODAzMjctZWRlYjFhOTMtOTdjMy00NzYxLTlkMTktNmY3YzYwMmQ5ZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3Mzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ODliYWZiYjUxYjc4OWU0M2QzMjgyMzA4N2M3MDMyNzRhYmQ0OGE5MTUzOWM3MTUyZTY4ZjExMjQ5Nzg5NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yuXcC4v93JNvmltwGdZo0It0hDjs3MvKgPwRN11VOkY)
> 
> ![grafik](https://private-user-images.githubusercontent.com/10787084/303080364-ecd81602-b990-4a29-8fe1-10e7db2818f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjc4MjQsIm5iZiI6MTcwNzMyNzUyNCwicGF0aCI6Ii8xMDc4NzA4NC8zMDMwODAzNjQtZWNkODE2MDItYjk5MC00YTI5LThmZTEtMTBlN2RiMjgxOGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3Mzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOWNiM2IyZTE5MTk2OGZmMTIzNjUyMmIzYzBhYTg5OGYyYmQ0N2M0MmEzOTEyYjQ3Y2VlNjJmNWYxMWZjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JdsF-FHO2D6oueLUxdj05Dwecs5qB-NiJx4B1jZz5dc)

@tobitege This will be fixed in next weeks build. I've already identified the bug location.

**Comment by giduac** [comment]
Hi @Wagnerp & @tobitege,

Has this been resolved so far ?

**Comment by tobitege** [comment]
Hello,
I hope to get to test this this evening today (GMT+2). 🍰

**Comment by Wagnerp** [comment]
Hi @giduac & @tobitege 

It should be...

**Comment by giduac** [comment]
@Wagnerp 
We'll give him a day or two...for feedback... ;)

**Comment by tobitege** [comment]
Closing this for now. I have to rework my app a bit more to get up-to-date with the changes since last time.
IF I'd find anything, I'd keep you posted, but till then: Thanks a LOT for your work, guys! 🥇
