### ISSUE TITLE
[Bug]: KryptonThemeComboBox wrong item display; ThemeSelectedIndex error in designer

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1306]
# **Issues**

### The combo shows and switches in design mode to a different theme than is selected as **DefaultPalette** in the properties
(index seems to be off by 2).

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/62b9db2e-7843-4138-9974-5a5736aee35e)

### Having saved the form after adding the combo, the form cannot be compiled anymore because of this line in the form.designer.cs file. Error is that ThemeSelectedIndex "set" accessor is not accessible:

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/4777fb30-1aad-4f99-8757-8b2715253cfd)

# **To Reproduce**

In my case, I put such a combo on an existing form that already had docking and ribbon components on it. But no theme was explicitly set.
 
# **Expected behavior**
DefaultPalette and the actually applied theme should be identical.

# **Desktop:**
 - OS: Windows 11 Pro
 - Version: 23H2, Build 22631.3085
 - Framework/.NET Version: 4.8.1
 - Toolkit Version: 90.24.1.22-beta (via NuGet)
 - Visual Studio 2019, v16.11.33

**Comment by Wagnerp** [comment]
This is a known bug https://github.com/Krypton-Suite/Standard-Toolkit/issues/1264
