### ISSUE TITLE
[Bug]: Issue with `KryptonDockingManager.LoadConfigFromFile` in C# .NET Core 8

### ISSUE THREAD

**Issue by dicri95** [Krypton-Suite/Standard-Toolkit#1310]
Hello,
I am currently experiencing an issue with the kryptonDockingManager.LoadConfigFromFile function in my C# .NET Core 8 application. Despite successfully saving the XML file, the loading process results in an empty workspace.
Thank you.

 - OS: [Windows 10]
 - Version: [19044.3930]
 - Framework/.NET Version: [.Net Core 8.0] 
 - Toolkit Version: [80.23.11.321]

**Comment by Smurf-IV** [comment]
@dicri95 
- Can you please test V70 to see if this is a ling standing problem ?
- And also either a newer canary or v90 alpha, to see if it still exists
- And also supply a simple src zip to replicate the issue.
-
