### ISSUE TITLE
[Bug]: White background in tabs area

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1313]
Whilst testing, I came across a white background in tabs area while using _all_ Office 2010 & Microsoft 365 themes.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/63409e78-60a8-4c76-ac4f-e657f2b5d1c2)

Expected result:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/eba93527-6d82-4c8b-8b47-2be0e9dff6d2)

**Comment by Wagnerp** [comment]
@Smurf-IV Where does this gradient come from?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/921cbf90-65ad-4f77-8ce1-5e79b69c30e2)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Where does this gradient come from?


For some reason the colours used are hardcoded:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ba512897-cf1a-4a9a-9a7d-e6585e41550a)

I would expect them to be using these colours:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b0b8d4dc-3c23-4265-bd69-63066f26e35f)

**Comment by Wagnerp** [comment]
Might solve this bug then?

**Comment by tobitege** [comment]
In other themes, the ribbon panel's background color is taken from PaletteBackStyle.PanelClient (see GetBackColor1 methods).

However, I'd suggest to use a color entry, that is actually named something like "RibbonPanel*" to avoid confusion and separate it from the regular panels' background color?

**Comment by Smurf-IV** [comment]
>RibbonPanel*

That's still confusing, Mentioning `Panel##`, makes into the panel that the ribbon tab would be associated with.

This is the bar area, that is not a tab, which is the area occupied by the minimise area.

@Wagnerp I think the the `PaintRectangle` function should do whatever is needed to paint that area, regardless of the panel colours etc.
And then make sure that the colours are "done up" correctly via the Theme designer as well.

**Comment by Wagnerp** [comment]
> @Wagnerp I think the the PaintRectangle function should do whatever is needed to paint that area, regardless of the panel colours etc.
And then make sure that the colours are "done up" correctly via the Theme designer as well.

Sounds good to me

**Comment by Wagnerp** [comment]
Hmm... am I doing something wrong?

```cs
switch (_ribbon.RibbonShape)
                {
                    case PaletteRibbonShape.Office2010:
                    case PaletteRibbonShape.VisualStudio2010:
                        {
                            //Adjust Color of the gradient
                            Color gradientColor = KryptonManager.CurrentGlobalPaletteMode.ToString()
                                .StartsWith(PaletteMode.Office2010Black.ToString())
                                ? _palette.GetRibbonMinimizeBarDark(PaletteState.Normal) //Color.FromArgb(39, 39, 39)
                                : _palette.GetRibbonMinimizeBarLight(PaletteState.Normal); //Color.White;

                            using var backBrush = new LinearGradientBrush(
                                rect with { Y = rect.Y - 1, Height = rect.Height + 1 }, Color.Transparent,
                                gradientColor, 90f);
                            backBrush.Blend = _compBlend;
                            g.FillRectangle(backBrush, rect with { Height = rect.Height - 1 });
                            break;
                        }
                    case PaletteRibbonShape.Office2013:
                    case PaletteRibbonShape.Microsoft365:
                    case PaletteRibbonShape.VisualStudio:
                        {
                            using var backBrush = new SolidBrush(_palette.GetRibbonMinimizeBarLight(PaletteState.Normal)/*Color.White*/);
                            g.FillRectangle(backBrush, rect with { Height = rect.Height - 1 });
                            break;
                        }
                }
```

**Comment by Wagnerp** [comment]
Yes, I did. Schoolboy error, but this is now fixed. PR incoming.

**Comment by Wagnerp** [comment]
Colours need updating (next weeks' job), but here's what it looks like:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/02caae3d-b679-4df6-91a5-f2f1ca8f7831)

@tobitege Will test with panel colours on MS365 themes (RibbonMinimizeBarDark & RibbonMinimizeBarLight)

**Comment by tobitege** [comment]
Thanks, great progress!
Pulled all just now, but "invoices.xml" is missing currently for TestForm.csproj?

**Comment by Wagnerp** [comment]
@tobitege Here's the missing file

[invoices.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/14230054/invoices.zip)
