### ISSUE TITLE
[Bug]: Exception at design time When Assigning CustomPalette to PropertyGrid / TreeGrid

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1322]
**Exception during design time**

"_**Specified argument was out of the range of valid values.
Parameter name: ContextNormal**_"

![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/675fd004-0d84-48ce-9a24-f4c10e5cf0bd)

**To Reproduce**
- Added to the TestForm -> TreeView example form a KryptonCustomPaletteBase (customPalette) as well as a KryptonManager component.
- No changes done to either components yet.
- In properties of the manager switched the "GlobalCustomPalette" to "customPalette" and the exception occured.
- The GlobalPaletteMode was still default of "Microsoft 365 - Blue" at that time.
- Also tried switching the latter to "Custom" and then GlobalCustomPalette to the new palette component, but again an exception:

**Expected behavior**
No exceptions if possible. :)

**Screenshots**
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/6cdc24c8-630c-4533-a374-e19ef2249304)

**Desktop (please complete the following information):**
 - OS: Windows 11 (German)
 - Version: 23H2 with all current updates
 - Framework/.NET Version: 4.8
 - Toolkit Version: latest alpha

**Comment by Smurf-IV** [comment]
Done - PR coming soon
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7b028b3c-ee4d-4a9f-946a-6cb63d1e0de9)

**Comment by Smurf-IV** [comment]
@tobitege Thanks for the clear repro steps, made it easier to track this down (With Dual VS 17.10 p1#s running ;-))

**Comment by tobitege** [comment]
> @tobitege Thanks for the clear repro steps, made it easier to track this down (With Dual VS 17.10 p1#s running ;-))

Happy to have helped! Thanks for working on this, appreciated a lot!
