### ISSUE TITLE
[Bug]: `RibbonTabTextNormal` in O2k10 themes does absolutely nothing 

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1324]
Whilst testing, it has been found that the `RibbonTabTextNormal` in O2k10 themes does absolutely nothing. This is because it is not assigned anywhere.

**Comment by PWagner1** [comment]
Duplicate of #1399. Closing.

**Comment by Smurf-IV** [comment]
Note: Should normally close the newer one ....
