### ISSUE TITLE
[Question]: about ribbon

### ISSUE THREAD

**Issue by mohatchaks** [Krypton-Suite/Standard-Toolkit#1327]
first of all sorry for my bad english .
so im using extended toolkit 
with - visual studio 2022 , .net framework 4.8 
my problem is the title bar dont take the theme style here is
screenshoot

![Capture3](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/9326bcf1-04ae-4ee4-a258-6966260169dd)
also i want to hide the text of of the ribbon

in the main form
```
public partial class Main : KryptonForm
{
    public Main()
    {
        InitializeComponent();
    }
}
```
![Capture](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/a4045c7e-0710-449e-a00c-4dee88ff6eb4)

and here is my settings
![Capture1](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/a8a485e8-3e32-4ddf-baa3-2aebde73fd06)
![Capture2](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/0a1a7ee6-914c-458c-a08c-3c540e81d453)
![Capture4](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/a5ffcdcb-620d-4040-8a0c-28216ce5fe54)
![Capture5](https://github.com/Krypton-Suite/Extended-Toolkit/assets/121371944/dd2bd9f6-ab63-4964-b332-e11359aeece7)

**Comment by Wagnerp** [comment]
Hi @mohatchaks 

Please retry using the latest `canary`, as this is now fixed

**Comment by Smurf-IV** [comment]
@mohatchaks And also have a look at the Ribbon Examples at how different Themes - have different layouts.
