### ISSUE TITLE
[Bug/Question]: `ViewManager` is visible in the designer as a readonly field, when it should be invisible !

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1337]
Why is the `KryptonDateTimePicker` displaying `ViewManager` in properties, when it's not editable?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/c348e0f2-c755-43bb-8099-3d29ea890e4e)

**Comment by Smurf-IV** [comment]
> Why is the `KryptonDateTimePicker` displaying `ViewManager` in properties, when it's not editable?

Probably because it is a public member (via `get` hence no update) and no attributes have been used to hide it in the designer.

This will need to be made into a bug.

**Comment by Smurf-IV** [comment]
And it is also visible in other controls:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b67c3ffb-c37f-4344-a664-4f2710b48247)
