### ISSUE TITLE
[Question]: Where does the window title text colour come from?

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1341]
Upon working on #1329 & #1340, I can't seem to find a title text colour definition in the palette files. So, where does it come from?

**Comment by Smurf-IV** [comment]
I do not understand what is meant by this ?
What control are you asking for the "Title Text" for ?

**Comment by Wagnerp** [comment]
> I do not understand what is meant by this ? What control are you asking for the "Title Text" for ?

The form 'text' colour doesn't appear to have a entry unlike other controls

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/a3f358bd-2054-451b-a2cc-b8db50bd5e47)

**Comment by Smurf-IV** [comment]
> The form 'text' colour doesn't appear to have a entry unlike other controls

Still not following.

Form Text colour cannot be applied to Krypton Controls, because it is to do with the WinForm thing. 
It should be hidden, and was done as part of the WinformColor mods done back in Sept '23, which was backed out due to flickering etc.

**Comment by Wagnerp** [comment]
@Smurf-IV I may put the code that was pulled out into the extended toolkit, so we can do some testing on it, before bringing it to here. How does this sound?

**Comment by Smurf-IV** [comment]
> @Smurf-IV I may put the code that was pulled out into the extended toolkit, so we can do some testing on it, before bringing it to here. How does this sound?

No.. I'll get round to it eventually.
What does need to be done before that is a related item to `hide the "Winform Designer" elements` from within a KryptonForm

**Comment by Wagnerp** [comment]
> Member

Ok, should I close this?

**Comment by Smurf-IV** [comment]
Yes, and use it as the link to the "Enhancement" please .
