### ISSUE TITLE
[Question]: `AppButton` definable back/fore colour

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1342]
Where in the palette can you define the `AppButton` back colour, as it seems to be always set to blue?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/00b7f541-2cf3-45ad-a549-a261a7da8946)

**Comment by Smurf-IV** [comment]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1409565f-2fb1-4b2f-9010-486af231d03f)

**Comment by Wagnerp** [comment]
> ![image](https://private-user-images.githubusercontent.com/2418812/305694915-1409565f-2fb1-4b2f-9010-486af231d03f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQyNjEsIm5iZiI6MTcwODI0Mzk2MSwicGF0aCI6Ii8yNDE4ODEyLzMwNTY5NDkxNS0xNDA5NTY1Zi0yZmIxLTRiMmYtOTAxMC00ODZhZjIzMWQwM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDgxMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFkMjM2ZThlNDVhYmQ4NDg0MDJlNzJhYjE0ODM4Yjk0NDQ3N2M1NWIzMjA2NGM3MjgzMGEyZmM5MjFlNjAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZmKn5lOQpe8jBMqvrBPgce_v3k3Q6bSKil6-1dRnbWY)

Is there a way to track down where it's defined in the code?

**Comment by Smurf-IV** [comment]
> Is there a way to track down where it's defined in the code?

Set it in the designer and see what is sets:
`kryptonRibbon.RibbonAppButton.AppButtonBaseColorDark = System.Drawing.Color.FromArgb(255, 128, 128);`

Then follow the code back and you will see "Yet Another" hardcoded value :-(
        [DefaultValue(typeof(Color), "31, 72, 161")]

**Comment by Wagnerp** [comment]
> > Is there a way to track down where it's defined in the code?
> 
> Set it in the designer and see what is sets: `kryptonRibbon.RibbonAppButton.AppButtonBaseColorDark = System.Drawing.Color.FromArgb(255, 128, 128);`
> 
> Then follow the code back and you will see "Yet Another" hardcoded value :-( [DefaultValue(typeof(Color), "31, 72, 161")]

I wonder if we could use the `PanelAlternate` colour?

**Comment by Smurf-IV** [comment]
> I wonder if we could use the `PanelAlternate` colour?

No, The "App Button" is normally a different colour from the other ribbon tabs.
I think the theme should be extended to include the three colours required:
- Dark
- Light
- Text.

Actions (to cover the three items above):
- Close this as answered
- Create 2 new Feature requests related to this
  - 1 in this repo
  - 1 in the themes palette repo
Note: Default colours are the current hardcoded (set in the themes - not in code !)

Thoughts ?

**Comment by Wagnerp** [comment]
> > I wonder if we could use the `PanelAlternate` colour?
> 
> No, The "App Button" is normally a different colour from the other ribbon tabs. I think the theme should be extended to include the three colours required:
> 
> * Dark
> * Light
> * Text.
> 
> Actions (to cover the three items above):
> 
> * Close this as answered
> * Create 2 new Feature requests related to this
>   
>   * 1 in this repo
>   * 1 in the themes palette repo
>     Note: Default colours are the current hardcoded (set in the themes - not in code !)
> 
> Thoughts ?

I agree, seems that palette functionality will need to be altered
