### ISSUE TITLE
[Bug]: Opening an existing (Or creating a new) RibbonBar creates incorrect designer code for new `ToolBarImages` object(s)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1361]
Using todays alpha code base
- Open Alpha Toolkit demos and load Ribbon Toolkit examples
- Goto `Quick Access Toolbar` project and double click Form1.cs to open the deisnger
- close designer and attempt to build the code

Expected:
- Modified Designer code to work
- Or, No designer modification

Actual:
- Incorrect creation of a new `ToolbarImageStorage` object
- Incorrect attempt to assign new object to `ToolbarImages`
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/adb61d76-dca8-4e9b-b02d-37d3a2836284)

**Comment by Wagnerp** [comment]
Missing the serialization marker
