### ISSUE TITLE
[Bug]: Incorrect usage of storage objects

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1363]
Highlighted in yellow, `KryptonManager` -> `Strings`.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/de9eb351-2c51-4b76-9937-44af9b9a865d)

**Comment by giduac** [comment]
Hi @Wagnerp ,

Can this one be closed ?
