### ISSUE TITLE
[Bug]: `KryptonForm` background colour

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1370]
As reported by @almendieta in #1300 

[sic] ... _After try Canary, now Krypton forms shows a steady black background, and some controls appear as a mosaic in one of them. Any idea about the reason?_

Happens in current `alpha`  too.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/fb25ceb9-79bf-4738-9997-1f77bac9ba16)

**Comment by Wagnerp** [comment]
From #1300 

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/71f05726-9413-47b8-a156-ae66af09bc15)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/017a9bcb-2da5-485d-9af4-7d6f8406e21e)

**Comment by Smurf-IV** [comment]
@Wagnerp Q: Should All regression marked bugs be "Fixed" in the 8.5 timeline ?

**Comment by Smurf-IV** [comment]
Hi @almendieta
I am not able to replicate this using the Code base from V80..

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7daea286-c2b6-4b0e-9aa3-dc2e08a952d8)

Win 10 22H2
VS 2022 17.9.4

**Comment by Smurf-IV** [comment]
@almendieta
Also Cannot replicate using the nuget package for V70.
- Start new Winforms project - Set to net60 
- Add nuget package
- Build to check
- Change to use KryptonForm
- Check Deisnger - Still okay
- run - Still okay ??

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krypton.Toolkit" Version="70.22.11.312" />
  </ItemGroup>

</Project>
```

**Comment by Smurf-IV** [comment]
When I do change the back colour then it is reflected in th designer and the app as expected:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6666b09f-5265-467f-8020-7af3c50e96df)

**Comment by Wagnerp** [comment]
> @Wagnerp Q: Should All regression marked bugs be "Fixed" in the 8.5 timeline ?

@Smurf-IV Yes, but any fixes included in v85 should also be included in v90.

**Comment by Smurf-IV** [comment]
> > @Wagnerp Q: Should All regression marked bugs be "Fixed" in the 8.5 timeline ?
> 
> @Smurf-IV Yes, but any fixes included in v85 should also be included in v90.

Of Course ;-)

**Comment by Wagnerp** [comment]
> When I do change the back colour then it is reflected in th designer and the app as expected: ![image](https://private-user-images.githubusercontent.com/2418812/316299285-6666b09f-5265-467f-8020-7af3c50e96df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzQwMjIsIm5iZiI6MTcxMTI3MzcyMiwicGF0aCI6Ii8yNDE4ODEyLzMxNjI5OTI4NS02NjY2YjA5Zi01MjY1LTQ2N2YtODAyMC03YWYzYzUwZTk2ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMDk0ODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RmZDUxNTZlNzg2ZjZjZTJlZmEwYTQ1OTYyYmE5MDMzNjg1ZTQwYzU5NDMxYWRiNjNhNmNkMDRmOGY0NzVmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UyzFNcR7G_La5JYsvlqeeKiF-0Mg9vsoZoWVqmYT160)

@Smurf-IV Is `BackColor` in either `VisualForm` or `KryptonForm` assigned a default value, or is it just `Color.Empty`?

**Comment by Wagnerp** [comment]
@Smurf-IV Works correctly in the January 2024 canary build...

**Comment by Wagnerp** [comment]
Something's not right here...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/d09f58c4-8220-40b4-9934-7a33ada4ae0a)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Works correctly in the January 2024 canary build...
> 
> Bug starts with `nightly` build >= 45, from 14/02/2024. The build .44, from 13/02/2024 is ok.

Reproed with build 45:
- Just resize the form in the desinger:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b4e3be6f-b479-4494-b8e6-025264af6b00)

**Comment by Smurf-IV** [comment]
@Wagnerp It's between these 2 commits....
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e38b02a3-adef-47e4-a451-af75c47c136a)

**Comment by Wagnerp** [comment]
> @Wagnerp It's between these 2 commits.... ![image](https://private-user-images.githubusercontent.com/2418812/318184291-e38b02a3-adef-47e4-a451-af75c47c136a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTE5MzcsIm5iZiI6MTcxMTc5MTYzNywicGF0aCI6Ii8yNDE4ODEyLzMxODE4NDI5MS1lMzhiMDJhMy1hZGVmLTQ3ZTQtYTQ1MS1hZjc1YzQ3YzEzNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDk0MDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEyYTZmNGQ0NGU5OTY2ZjNkYjg4ODQ2M2IxZDZmZjU3NGVkYjdlMGYxNGQyYjkyNGQ1MmE3ZDVkNWMzM2NmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yirWG2-lcNrkC75l3We3RtIeyn8s0E97N3GzpJWY2UE)

@Smurf-IV Have a look at this [PR](https://github.com/Krypton-Suite/Standard-Toolkit/pull/1331).

**Comment by Smurf-IV** [comment]
Yup..

It's this:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/86ec4b21-a447-4071-91c2-95d0ccadd83c)
You've overridden the default, therefore no background painting is going to happen !

Will test and fix in a moment.

**Comment by Wagnerp** [comment]
> Yup..
> 
> It's this: ![image](https://private-user-images.githubusercontent.com/2418812/318184945-86ec4b21-a447-4071-91c2-95d0ccadd83c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTI3NjYsIm5iZiI6MTcxMTc5MjQ2NiwicGF0aCI6Ii8yNDE4ODEyLzMxODE4NDk0NS04NmVjNGIyMS1hNDQ3LTQwNzEtOTFjMi05NWQwY2NhZGQ4M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDk1NDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNjMWNjZGZlYjUwOTgzOTU5MWUxODM1OTYzZjgzNmNhNzQ2ZmZiNTExOGM4NjAxMjhhY2Q2NjQ1Zjc3YmE1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BUpZ-A2EDpqSdwziCkMxZYlsRKcPqP1MhqPZiHQbDgU) You've overridden the default, therefore no background painting is going to happen !
> 
> Will test and fix in a moment.
> 
> Edit: That was it !!

Must have been something I forgot to remove when removing the other Acrylic stuff
