### ISSUE TITLE
[Question]: Is it possible to get notified when a hidden KryptonPage is going to be shown?

### ISSUE THREAD

**Issue by daxnet** [Krypton-Suite/Standard-Toolkit#1372]
I am using docking system with KryptonPages, after clicking on the Close button, by default the page will be hidden. I then used `dockingManager.Show(PageIdentifier)` method to get it shown again on the docking area, but at this point I'd like to get notified (e.g., having a `PageShown` event on some object so that I could subscribe), is it possible to do that?

**Comment by Smurf-IV** [comment]
@daxnet 
- What is `dockingManager.Show(PageIdentifier)` 
  - I do not see a `DockingManager` class in Krypton
- If you are using the `KryptonWorkSpaceCell` then there are many event s that can be used for page addition etc.
  - `BeforePageReorder`
  - `SelectedPageChanged`
  - `TabCountChanged`
  - `TabVisibleCountChanged`
  - others

**Comment by Wagnerp** [comment]
@Smurf-IV 

> I do not see a DockingManager class in Krypton

The only thing I can find is the `KryptonDockingManager` class. I think that @daxnet has renamed it for their project?

**Comment by Smurf-IV** [comment]
> @Smurf-IV
> 
> > I do not see a DockingManager class in Krypton
> 
> The only thing I can find is the `KryptonDockingManager` class. I think that @daxnet has renamed it for their project?

OK, FYI: Something weird is happening to my search.. It did not find anything when search for `dock`. Time to restart !!

**Comment by daxnet** [comment]
@Wagnerp: yes, `dockingManager` is an instance of `KryptonDockingManager` in my case.
@Smurf-IV: Currently I used the `SelectedPageChanged` event, yes, that does the trick.
Thank you all for the replying.

**Comment by daxnet** [comment]
Closed since my question has been answered.
