### ISSUE TITLE
[Bug]: Getting an application crash when pressing the Delete key.

### ISSUE THREAD

**Issue by Tape-Worm** [Krypton-Suite/Standard-Toolkit#1373]
**Describe the bug**
In my application, I have a grid containing a list of files. I also have a Krypton ribbon present. When I press my delete key, I expect the application to ask me if I want to delete the file.  

Instead, what happens is an unhandled exception is thrown. This is weird, because my code should have trapped the exception. It did not.

Here is the stack trace that is given on the crash:
```
Error Message: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Windows.Forms.Keys,System.Windows.Forms.ToolStripMenuItem]' to type 'System.Collections.Hashtable'.
Exception Type:  System.InvalidCastException
Source:  System.Private.CoreLib
Target Site:  System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper
Stack trace
   at Gorgon.Editor.Program.Main(String[] args) in Program.cs:line 197
   at Gorgon.UI.GorgonApplication.Run(ApplicationContext context, Func`1 idleMethod) in GorgonApplication.cs:line 782
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.Microsoft.Office.IMsoComponent.FPreTranslateMessage(MSG* msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at Krypton.Ribbon.KryptonRibbon.PreFilterMessage(Message& m)
   at Krypton.Ribbon.KryptonRibbon.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonTab.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroup.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroupTriple.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroupButton.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Toolkit.CommonHelper.CheckContextMenuForShortcut(ContextMenuStrip cms, Message& msg, Keys keyData)
<<<END>>>
```

As you can see, it ends up in a Krypton Toolkit Helper class.

 - Framework/.NET Version: [8.0] 
 - Toolkit Version: [80.23.11.321]

**Additional context**
@Wagnerp , since you forked my repo, you can reproduce this in the Gorgon Editor application. Just create a new file and then select it in the file pane and press your delete key. If you get the develop branch, you'll get the .NET 8 version.

**Comment by Wagnerp** [comment]
Hi @Tape-Worm 

This might be a errant `null` check within the Krypton Toolkit. Is the behaviour the same in any other framework versions?

**Comment by Tape-Worm** [comment]
.NET 6.0 with krypton version 5.550.2103, works as expected.  No error.

.NET 6.0 with krypton version 80.23.11.321, works as expected.  No error.

Seems this is only occurring on .NET 8.

**Comment by Wagnerp** [comment]
Hi @Tape-Worm 

Are there any instructions on how to compile Gorgon, as every time I try to compile, I run into 'library' missing errors?

**Comment by Tape-Worm** [comment]
Did you update the submodules?

**Comment by Wagnerp** [comment]
> Did you update the submodules?

I've cloned the copy of your `development` branch. The only thing I updated is `Krypton.Ribbon` as we pushed an minor update out about a week ago.

**Comment by Wagnerp** [comment]
Getting a lot of `D3DImage` errors

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8cb1f9c1-7f33-444f-99b9-eea01015c76d)

**Comment by Wagnerp** [comment]
Does it require the DirectX SDK to be installed?

**Comment by Tape-Worm** [comment]
Nope. It shouldn't. I don't have it installed.

**Comment by Wagnerp** [comment]
> Nope. It shouldn't. I don't have it installed.
> 
> You may need to do this? https://allthings.how/how-to-install-and-use-directx-graphics-tools-on-windows-11/
> 
> The article looks to be a little out of date, the Optional Features is now located under "System". ![image](https://private-user-images.githubusercontent.com/9710137/313291455-4a2e08f2-8fc8-4f43-8436-8433e1b1b450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjYzMjAsIm5iZiI6MTcxMDUyNjAyMCwicGF0aCI6Ii85NzEwMTM3LzMxMzI5MTQ1NS00YTJlMDhmMi04ZmM4LTRmNDMtODQzNi04NDMzZTFiMWI0NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTgwNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM1YzIyZWQyZDk3YzA2MjNhYTI2N2I4MWVkYjJjZWIzMmRjMzIyZjczMDNjNzkwNGUzZGJjNmE3MjllNmFhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xkZuyQWNv0CSHgKRMJmRe6loxvgrkw454ZWpKtoBMP0)

I thought that is was odd that I couldn't find it

**Comment by Tape-Worm** [comment]
So, I just pulled it down to a neutral location on my harddrive, and it compiles just fine.  I did run into a problem at first because I had put it under a directory with spaces in the name. Once I moved it out of there, it compiled fine.

I'll have to fix that spaces in path problem.

**Comment by Tape-Worm** [comment]
Oh, I should also warn you that you _may_ see an error about RoboCopy, just Build again if that pops up. I dunno why it doesn't work sometimes.

**Comment by Wagnerp** [comment]
Interesting, I still can't compile the dependencies, as the `GlassCube.WPF` project blocks it.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/5d5ca5e8-df5b-49ee-8848-e01042e8515b)

Unloading the WPF projects fixes this, but still can't quite get my head around the AppHost problem?

**Comment by Tape-Worm** [comment]
I have no idea what "AppHost" is. Although, it seems to be something to do with the C++/CLI compiler:
https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1145

The Microsoft.Wpf.Interop.DirectX_winsdk is a C++/CLI assembly. Do you have the C++ components installed?

**Comment by Wagnerp** [comment]
> Do you have the C++ components installed? It needs the v143 platform toolset.

I've now got C++/CLI stuff installing. If that fails, then I'll try it in one of my VMs.

**Comment by Tape-Worm** [comment]
Just FYI, I also had it crash while I was holding down the CTRL key to zoom in on something.  Same stack trace.

**Comment by Wagnerp** [comment]
@Tape-Worm I haven't forgotten about this, been fixing/implementing new stuff recently.

**Comment by Tape-Worm** [comment]
No worries my friend. I'm currently doing a major upgrade to .NET 8, and it'll take a while before I hit the UI related stuff.

**Comment by giduac** [comment]
Hi @Tape-Worm,

I've been looking into another datagrid issue https://github.com/Krypton-Suite/Standard-Toolkit/issues/1280.
Here also a bug has been reported using Toolkit Version: 80.23.11.321.

When testing with TK 80.24.3.64 I didn't get the error,
Tested this with Net 48 / 6 / 7 / 8

Could you give that TK version a try please ?

**Comment by giduac** [comment]
@Wagnerp or @Smurf-IV,

No response received from @Tape-Worm.
Please close the ticket. If needed it can be reopened.

ty.

**Comment by giduac** [comment]
Hi @Tape-Worm,
cc: @Wagnerp (please reopen the ticket, ty)

Sorry to hear that and wishing you all the best.

Thanks for responding I will look in to as soon as there's time (of which we don't have enough...)

**Comment by Wagnerp** [comment]
Hi @giduac 

I've reopened this, which version tag should I assign? I think it's something to do with the ribbon.

@Tape-Worm Sorry to hear that, wishing you and your partner all the best!

**Comment by giduac** [comment]
@Wagnerp , V85 & V90 tags

**Comment by giduac** [comment]
Hi @Tape-Worm,

Some questions for you:
- Can you give some more context about the grid you are using and how this is setup.
- When you press DEL is the focus on the grid?
- You mention the ribbon, do you think there's a connection.
- The trace shows: `Error Message: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Windows.Forms.Keys,System.Windows.Forms.ToolStripMenuItem]' to type 'System.Collections.Hashtable'.` What kind of cast is being performed in the code?
- Can you reproduce the error in a test app that has nothing to do with the project your working on?

**Comment by Tape-Worm** [comment]
1. It's a DataGridView which I've extended a tiny bit.  You can find the code here: https://github.com/Tape-Worm/Gorgon/blob/develop/Tools/Editor/Gorgon.Editor/FileSystem/Views/DataGridViewEx.cs
2. Yes, the point is that the delete key deletes the selected file. The code in https://github.com/Tape-Worm/Gorgon/blob/develop/Tools/Editor/Gorgon.Editor/FileSystem/Views/FileExploder.cs shows the keydown and keyup events.  However, even with breakpoints, the code is *NEVER* executed, it crashes immediately (see the picture).
3. Probably because the stack trace contains: 
```
  at Krypton.Ribbon.KryptonRibbon.PreFilterMessage(Message& m)
   at Krypton.Ribbon.KryptonRibbon.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonTab.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroup.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroupTriple.ProcessCmdKey(Message& msg, Keys keyData)
   at Krypton.Ribbon.KryptonRibbonGroupButton.ProcessCmdKey(Message& msg, Keys keyData)
```
4. I have no idea, that's happening in the Krypton code, not in my code.
5. That will take a while.

Please note that up until .NET 8, this code worked flawlessly. Nothing has been changed. Once converted to .NET 8 (just the project file), it stopped working.  

In this image you'll see the two break points, these are NEVER hit when I press the delete key. The key is being consumed by the ribbon (again, as shown in the stack trace).
![image](https://github.com/user-attachments/assets/6d19a8cc-5da8-4226-9d65-a10ec040f5a9)

**Comment by Tape-Worm** [comment]
I just tested, and the application crashed with the same exception, and stack trace when I press the shift key.  

I don't have anything bound to shift. No file or directory was selected either.

**Comment by Tape-Worm** [comment]
I had a quick look through the Krypton code, and this line is almost certainly where your problem is:
https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Toolkit/General/CommonHelper.cs#L152

**Comment by Tape-Worm** [comment]
I've done some further digging, and it appears Krypton is picking up one of my context menus (MenuCreate) which is a standard windows forms context menu strip. 

And when it calls the GetValue method on the ShortCuts property it returns this:
`System.Collections.Generic.Dictionary`2[[System.Windows.Forms.Keys, System.Windows.Forms, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]`

Which the Krypton code immediately tries to cast to a `Hashtable` type.  This of course breaks.

As I said before, this worked fine in .NET 6, but they may have changed the type returned for .NET 8. 

Regardless, this is not my code doing this. This is the .NET 8 Windows Forms code. I have no control over this, so you're going to need to fix Krypton to handle this case.

**Comment by Tape-Worm** [comment]
If you update https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Toolkit/General/CommonHelper.cs#L132

To this code:
```csharp
// Get any menu item from context strip that matches the shortcut key combination

Hashtable? hashTableShortCuts = _cachedShortcutPI!.GetValue(cms, null) as Hashtable;
ToolStripMenuItem? menuItem = null;

if (hashTableShortCuts is null)
{
  Dictionary<Keys, ToolStripMenuItem>? dictionaryShortcuts = _cachedShortcutPI!.GetValue(cms, null) as Dictionary<Keys, ToolStripMenuItem>;

  if (dictionaryShortcuts is not null)
  {
    dictionaryShortcuts.TryGetValue(keyData, out menuItem);
  }
  else
  {
    return false;
  }
}
else
{
  menuItem = (ToolStripMenuItem?)hashTableShortCuts[keyData];
}
```

And remove
```csharp
var shortcuts = (Hashtable)_cachedShortcutPI!.GetValue(cms, null);
var menuItem = (ToolStripMenuItem)shortcuts[keyData];
```

The problem will likely be fixed (I've tried this on my end and it now works as expected). I don't have the time to fork + PR this right now, and I've a _very_ busy week ahead of me, so I don't expect I'll be able to get to this anytime soon.

**Comment by giduac** [comment]
@Tape-Worm  Thanks!! for digging into this.

One last question: is there more to know to compile your project locally?

**Comment by Tape-Worm** [comment]
All information to compile Gorgon is located here:
https://www.tape-worm.net/GorgonDocs/articles/CompilingGorgon.html

**Comment by giduac** [comment]
@Tape-Worm Great!!
I'll get back to you...

**Comment by Tape-Worm** [comment]
I should also note that the context strip menu was attached to a button on my ribbon:
`this.ButtonCreate.ContextMenuStrip = this.MenuCreate;`

You'll probably need to do something like this to cause it to crash in a small test app.

**Comment by giduac** [comment]
@Tape-Worm 
If anything more comes to mind just drop a note please...

**Comment by Tape-Worm** [comment]
You'll also need to set the button type to DropDown (which I guess kinda goes without saying considering we're hitting a context menu).

I just tried a small test app, which I've attached here.  You'll need to point it at your Krypton DLLs as I have it pointing to mine on my local drive.

[RibbonCrashRepo.zip](https://github.com/user-attachments/files/16230393/RibbonCrashRepo.zip)

**Comment by giduac** [comment]
@Tape-Worm 
A possible work-around, if you use a KryptonContextMenu the error does not happen.

In the mean while we'll be looking into it further since it's also a bit weird that the Ribbon process the key stroke that's intended for the grid.

I'll keep you posted.

**Comment by Tape-Worm** [comment]
It has nothing to do with the grid.

**Comment by giduac** [comment]
> It has nothing to do with the grid. If you pull the grid out of that sample, and use the Krypton Ribbon Lite on nuget, you will get exactly the same issue. The grid has nothing to do with this.
> 
> The ribbon is processing all key strokes and checking to see if they are used on the attached context menu strip. That's all that function is doing.
> 
> I've attached another sample without a grid, and you'll see that it crashes just the same. Again, this has _nothing_ to do with grids.
> 
> [RibbonCrashRepo.zip](https://github.com/user-attachments/files/16239328/RibbonCrashRepo.zip)

@Tape-Worm 
I did try too without a grid and got the same error.
Although with a grid and the grid having the focus it's a bit weird that that key stroke ends up with that button.
Tried .Net 9 preview, same problem.
And upcoming Toolkit V90 has it also.

KryptonContextMenu gets a different treatment in the RibbonGroupButton code
```cs
if (ButtonType is GroupButtonType.DropDown or GroupButtonType.Split)
{
    if (KryptonContextMenu != null)
    {
        if (KryptonContextMenu.ProcessShortcut(keyData))
        {
            return true;
        }
    }

    if (ContextMenuStrip != null)
    {
        if (CommonHelper.CheckContextMenuForShortcut(ContextMenuStrip, ref msg, keyData))
        {
            return true;
        }
    }
}
```
Anyways will put your fix in asap

**Comment by Tape-Worm** [comment]
I have a custom tree with a standard text box that I use for renaming nodes. When that textbox is on screen, you'd think it'd have first crack at the input. Nope, it doesn't. The ribbon previews that as well.

To verify this, I took that sample app, and added a textbox.  Just a standard basic textbox that comes with windows forms. When the app loads, I give focus to the textbox and hit 'A' and boom, crash again (using the current nuget version of the krypton ribbon).

For some reason the designers of this component have decided to intercept all keystrokes on the ribbon. I agree it's really strange. But not only that, it's potentially problematic because if I were to hit a key associated with a menu item, it will (I tested this as well) execute that menu items functionality. That breaks the rules of context awareness.

I think this method needs to check to ensure that the ribbon has focus or something like that before it tries processing anything. Or better yet, stop capturing everything.

**Comment by giduac** [comment]
Hi @Tape-Worm, 
PRs are in

> Re: The KryptonContextMenu.
> I don't want to use any more Krypton controls than I'm currently using. Given the issues that I have right now, I'm on the fence as to whether I want to keep using this library or not. Adding more references just makes my life a lot harder. Also, I provide extensibility functionality in the application, and I want my users to have minimal interaction with a control set that they may be unfamiliar with or not want to use.

We are currently working and reducing open issues for the rest of V90. V100 will mostly encompass improving it further to raise the quality.  If you have ideas for improvement then we are always interested to hear...

**Comment by Tape-Worm** [comment]
The main issue that's a major problem for me is the designer not working with the Ribbon (which I brought a couple years back). At this point, I do not wish to put in support for .NET 4.8 just so I can create/edit a control (I also then have to litter my code with #if NET80_OR_GREATER conditionals, which I despise having to do).

But that's not relevant to this issue, I think we can safely close this now?

**Comment by Tape-Worm** [comment]
> Your PRs are merged. If you're in need of this fix you can build nugets from the cloned repo using branch master-V85 in this case.

Thanks!  I don't need it right away, so I can wait until you guys do another stable release.
