### ISSUE TITLE
Improper TextRendering Issue for naormal Winforms buttons - when only a single Krypton Button is added

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [Krypton-Suite/Standard-Toolkit#1379]
**Describe the bug**
We drag and drop the Krypton button from the toolbox. Then, we add the MSButton with UseCompatibleRendering set to true in the code-behind.

**To Reproduce**
1. Run the sample

**Expected behavior**
The button text must render correctly when using Krypton button controls.

**Screenshots**
Without Krypton Button
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124787498/a7ea20d1-4385-4304-b505-857fc883a401)

With Krypton Button
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124787498/21e56b28-336c-4856-b2b8-6e82b9550748)

**Sample for your reference**
[WindowsFormsApp.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/14757558/WindowsFormsApp.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 22H2
 - Framework/.NET Version: .NetFramework 4.7.2
 - Toolkit Version: 80.24.3.64

**Additional context**
Need to ensure the fix works for all three below scenarios.
* MSButton with UseCompatibleRendering as true.
* Default MSButton.
* Custom Button inherited from MSButton.

**Comment by Wagnerp** [comment]
Hi @ChidanandMurugaiah Isn't it the same as [this](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1109)?

**Comment by ChidanandMurugaiah** [comment]
Hi @Wagnerp, I have reviewed the issue you mentioned. In that query, they indicated that the problem occurred due to passing the parameter true to the `Application.SetCompatibleTextRenderingDefault` method in Program.cs. However, in our scenario, we pass the parameter as false. Despite this, the text rendering remains improper.

**Comment by Smurf-IV** [comment]
Looks like a different font is being used inthe 2nd picture.
Also if you are drawing text then you needs to set-up things so that the font "Looks good" in all zoomed scenarios (i.e GDI Quality settings in the current graphics instance)

**Comment by Smurf-IV** [comment]
Ok, I rolled back the nuget package to 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c7e2053a-5a1d-41b9-8b3b-d7e95a62d5ca)

And it is still present..

I am tempted to make this a "Won't fix" as the idea of Krypton is to help replace the default winform controls.

@Wagnerp Thoughts ?

**Comment by Smurf-IV** [comment]
@ChidanandMurugaiah 

To fix this, then you have to explicitly set the Compatible rendering to `false`:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f4648fa4-5fd8-4550-a42b-fd9bf67b398e)

And this then results in this:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/852008ce-db2d-42a1-b1c3-27cee56d996e)

(I added a panel and placed a normal winform button with italic text to show differences as well !)

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, since it's already mentioned in the 'breaking changes'

**Comment by ChidanandMurugaiah** [comment]
@Smurf-IV, As we mentioned in the previous update, we set `CompatibleTextRenderingDefault` to `false` for both the application and the control. This issue occurs when we use the `graphics.DrawString` method. In the provided sample, we derived a custom button from the MS Button and overrode the `OnPaint` method to use `graphics.DrawString` for rendering text. However, when the Krypton button is added to the form, the custom button renders improperly. We have explicitly set `CompatibleTextRenderingDefault` to `false` at both the application level and the control level.

Sample - [WindowsFormsApp1.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/15470094/WindowsFormsApp1.zip)

Without Krypton Button
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124787498/3c2ad3c8-3273-4e1a-a002-9b8ababc7e7b)

With Krypton Button
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124787498/fff4776d-652b-4fd2-a323-4f1d7e536e0e)

**Note :- UseCompatibleTextRendering is false in both application and control.**

**Comment by Smurf-IV** [comment]
OK, With this latest sample, I changed the code to do this:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/5d94b60f-43de-4068-af42-91a18d4fff75)

**Comment by ChidanandMurugaiah** [comment]
Why does the `Graphics.DrawString` method cause rendering issues? and are there any workarounds to resolve this issue using the `Graphics.DrawString` method itself?

**Comment by Smurf-IV** [comment]
google has lot's of answers.
And it may also be down to how MS have changed the kernel for an app that starts to use `DrawText` and messes up everything else....

**Comment by ChidanandMurugaiah** [comment]
We are a bit unclear about your explanation. Could you clarify why the `Graphics.DrawString` method causes rendering issues only when a Krypton button is used? `Graphics.DrawString` behaves properly when the Krypton button is not used.

**Comment by Smurf-IV** [comment]
> Could you clarify why the Graphics.DrawString method causes rendering issues only when a Krypton button is used? 

I did not look into that, only a solution that currently works, as previously just setting false did.

> Graphics.DrawString behaves properly when the Krypton button is not used.

I agree, most perplexing.

**Comment by ChidanandMurugaiah** [comment]
@Smurf-IV, We believe that our issue has not been resolved yet. Could you please reopen this issue for further follow-up?

**Comment by giduac** [comment]
Hi @ChidanandMurugaiah, @Smurf-IV,

The example Smurf gave clearly shows that when using the *.NET advised method* for drawing text, the results are substantially better.
```cs
TextRenderer.DrawText(pevent.Graphics, Text, font, new Point( (int)x, (int)y ), this.ForeColor);
``` 
[MS themselves advise to use this way.](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.usecompatibletextrendering?view=windowsdesktop-8.0#system-windows-forms-buttonbase-usecompatibletextrendering)

This difference in rendering quality is clearly related to .NET and not to Krypton.

Therefore I suggest to close this ticket.
