### ISSUE TITLE
[Bug]: `KryptonListView` throws a `System.Resources.MissingManifestResourceException`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#138]
**Describe the bug**
Drag-and-drop a `KryptonListView` onto a KForm to trigger the bug.

**Comment by Smurf-IV** [comment]
@Wagnerp I'm confused...
`KryptonListView` does not exist in the current standard alpha branch ??

**Comment by Smurf-IV** [comment]
And due to the preview stuff of moving the `Using`s, I cannot build in Visual Studio 16.10 !!

**Comment by Wagnerp** [comment]
> @Wagnerp I'm confused...
> `KryptonListView` does not exist in the current standard alpha branch ??
> ![image](https://user-images.githubusercontent.com/2418812/120884147-107af200-c5d9-11eb-864e-fa9be9cdc5f3.png)

@Smurf-IV Ahh, forgot, I removed the files from the `alpha` branch during testing. Will re-upload these files.

**Comment by Smurf-IV** [comment]
Just found them in Master.. As they are "Experimental"..Then they should really have never got into master, and should have stayed in Alpha / Canary !

**Comment by Wagnerp** [comment]
> Just found them in Master.. As they are "Experimental"..Then they should really have never got into master, and should have stayed in Alpha / Canary !

Yes, that was the reason behind `2106.1` stable.

**Comment by Smurf-IV** [comment]
Ok assigning to you, to :
- Remove from master (And canary ?)
- Move to alpha
- Make code compile in 16.10 ??

Then assign back to me when above 2 (or 3) are done ;-)

**Comment by Wagnerp** [comment]
@Smurf-IV Have you tried compiling with `build.cmd`?

**Comment by Wagnerp** [comment]
@Smurf-IV Changed assignments, removed files from both `master/signed` and `canary`.  Don't forget to compile by using `build.cmd`, as VS doesn't work ;)

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/120885389-833b9b80-c5e0-11eb-906b-bd36c18cf01b.png)

![image](https://user-images.githubusercontent.com/949607/120885401-8f275d80-c5e0-11eb-96be-b372115be3b3.png)

**Comment by Smurf-IV** [comment]
Still in progress.. I've not forgotten about it.
(I can see why it was not in the original list of controls - It's a bit of a mare !)

**Comment by Smurf-IV** [comment]
> Don't forget to compile by using `build.cmd`, as VS doesn't work ;)

Not helpful when trying to debug!

**Comment by Wagnerp** [comment]
> > Don't forget to compile by using `build.cmd`, as VS doesn't work ;)
> 
> Not helpful when trying to debug!

I don't know if a debug script can be set up.

**Comment by Smurf-IV** [comment]
Taking a step back.....
- I've tried to follow the pattern done by other Krypton Controls (Like TreeView and List) and dug a very deep hole.

Starting again !

**Comment by Smurf-IV** [comment]
@Wagnerp Darn this new stupid Visual studio..Did a Push and it went straight into Alpha without setting up a merge request
Please see the changelist

**Comment by Smurf-IV** [comment]
And also this went into Demo's as well !
https://github.com/Krypton-Suite/Standard-Toolkit-Demos/commit/597a9f853029ee64ef07570ed5949f875dcada43

**Comment by Smurf-IV** [comment]
@Wagnerp Please set this to closed when reviewed ;-)

**Comment by Wagnerp** [comment]
@Smurf-IV Ok, I've reviewed the changes, looks good. Will update the readme today ;-)
