### ISSUE TITLE
[Bug]: Closing last Page in undocked page group prevents addition of further Pages via `KryptonDockingManager.AddToWorkspace`

### ISSUE THREAD

**Issue by stigzler** [Krypton-Suite/Standard-Toolkit#1383]
**Describe the bug**
Sorry to post again! Love Krypton and hence wanting to get it perfect! If you close the final Page that has been added via KryptonDockingManager.AddToWorkspace, then if you try to add a new Page via this method, it does not display and is not added to the Pages. 

I think what's happening is when Pages that aren't placed inside a Cell that's inside a DockingPanel, then when the last of these Pages are closed, Krypton also destroys the container Cell. This is demonstrated below:

**To Reproduce**
I have updated my sample app to demonstrate the problem. Find it here:
[Demo Git Page](https://github.com/stigzler/KryptonDocking)

Steps to reproduce the behaviour:
1. Add a page via the plus button, then click the info button to see how many Cells and Pages there are (3 and 5 from stock)
2. Close all of the Text Document Pages. Then Click Info - you'll notice the number of cells reduces to 2. 
3. Try add a page again. It doesn't add the page and the number of cells remains at 2. Implying KryptonDockingManager.AddToWorkspace is adding neither a new Cell nor Page

**Expected behavior**
A new Page is added to the Workspace. 

**Desktop (please complete the following information):**
 - OS: Windows 11
- Framework/.NET Version: 4.7.2
- Toolkit Version: 80.24.3.64

**Comment by stigzler** [comment]
OK. So I forked this and think I've isolated the issue (the fix, though is sadly beyond me). If I step through following trying to add a new Page to a workspace where the last tabbed Page has been closed, this line and beyond is of interest:

[Master source link](https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Docking/Elements%20Impl/KryptonDockingSpace.cs#L76)

A couple of interesting points:
1. `cell` Visible = false
2. `var childMinSize = cell.GetMinSize();` returns Width = -2147483648 Height = -2147483611 (this  value not returned when there's a Page in the Cell)

Further investigation into `KryptonWorkspaceCell.GetMinSize()` shows this gets the negative values from `KryptonWorkspaceCell.GetMinSize(ControlCollection controls)` where the default return is set to `int.MinValue`. `controls` is `null` therefore these int.min values are returned. 

The height value is modified by the first `GetMinSize` method, thus the discrepancy with Height....

So, I've tired chaging a few things in KryptonDockingSpace.Append such as setting the `Cell` to visible and using some dummy positive values for `childMinSize` (removing the negatives) but no dice. I'm wondering whether the problme lies elsewhere as the above implies that the relevant KryptonWorkspaceCell doesn't contain any controls (which if it contained a Page, it should contain a control). 

Anyways, burnt out on this issue now and given I don't know the wider architecture, it's hard to troubleshoot. Hope you guys can give this some attention (I appreciate you have a long list!) as it is a bit of a major issue (adding new pages to fully closed document groups).

**Comment by stigzler** [comment]
I couldn't let it lie, so found a possible solution. See the pull request for details.

**Comment by Wagnerp** [comment]
@stigzler & @Smurf-IV Is the fix a candidate for v85 as well?

**Comment by Smurf-IV** [comment]
> @stigzler & @Smurf-IV Is the fix a candidate for v85 as well?

Did it "Work" in earlier versions of V80 or V70 ?? If so then yes. - Otherwise no.

**Comment by Wagnerp** [comment]
> > @stigzler & @Smurf-IV Is the fix a candidate for v85 as well?
> 
> Did it "Work" in earlier versions of V80 or V70 ?? If so then yes. - Otherwise no.

Not in v80.
