### ISSUE TITLE
[Feature Request]: Ribbon notification banners

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1389]
Is it possible to implement something like this?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/47a0a110-5f1f-4e9a-bdbb-43d687c12380)

https://docs.devexpress.com/WindowsForms/404480/controls-and-libraries/ribbon-bars-and-menu/ribbon/visual-elements/ribbon-message?utm_source=SupportCenter&utm_medium=website&utm_campaign=docs-feedback&utm_content=T1201562

Reason: Krypton currently does not have such a feature, and this has been a 'thing' since Office 2010

**Comment by Smurf-IV** [comment]
I do not think it is a specific "Ribbon" thing, more like a panel, and can be easily done by have a table layout with the top line being the notification that becomes visible when needed.
It "Could" be done as a control, but the amount of work for all the options would be lost amongst the amount of work the dev would actually do for themselves.

Also defaulting to "Light" Yellow on a dark theme would look bad.

**Comment by Wagnerp** [comment]
Leave the dev to do this themselves.
