### ISSUE TITLE
[Bug]: Ribbon tab text O2K10 colours

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1399]
Changing the tab text colours for Office 2010 themes does not work.
Also mentioned in: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1324

![Screenshot 2024-04-13 083503](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/640a5bb3-d94e-4665-add9-0988e559cc9e)

![Screenshot 2024-04-13 083525](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/0b078646-2409-4fa5-a0c3-7a5920614c91)

![Screenshot 2024-04-13 083548](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9e90259b-64ff-4e8b-bd56-097a00ec1ac7)

![Screenshot 2024-04-13 083559](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/f5ed68e3-d77b-44a8-91e2-bd0dc5c0def2)

**Comment by Smurf-IV** [comment]
Did it ever ?

**Comment by Wagnerp** [comment]
> Did it ever ?

That I don't know... but it's hard to read the text, compared to the other variations

**Comment by Wagnerp** [comment]
They should be using these values...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/cd859d4b-aa7d-4a76-af54-7982ad70a7fa)

**Comment by giduac** [comment]
Ann mentioned in: [https://github.com/Krypton-Suite/Standard-Toolkit/issues/1324](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1324)

**Comment by giduac** [comment]
@PWagner1 

From which theme has O2K10 been "derived" ?

**Comment by PWagner1** [comment]
> @PWagner1
> 
> From which theme has O2K10 been "derived" ?

@giduac 

I think it is derived from O2K7 themes.

**Comment by giduac** [comment]
@PWagner1 

Ok, thanks, i'll have look at it...

**Comment by PWagner1** [comment]
> @PWagner1
> 
> Ok, thanks, i'll have look at it...

@giduac 

Or at least a large proportion of it was. The 'base' files may help.

**Comment by giduac** [comment]
@PWagner1 

Looks like the text does get a different color, see vid.
can it be that a different scheme color is assigned??


https://github.com/user-attachments/assets/2e804ebf-7e86-414e-88f0-9691dc956911

**Comment by PWagner1** [comment]
> @PWagner1
> 
> Looks like the text does get a different color, see vid. can it be that a different scheme color is assigned??
> 
>  TestForm_uyY5691Ha4.mp4

@giduac 

Is there any way of knowing which colours they use?

**Comment by giduac** [comment]
Dont think so.... :(

Am I in the right spot here ?

![image](https://github.com/user-attachments/assets/ec57d079-765d-431b-b0ee-745ee748da78)

**Comment by PWagner1** [comment]
> Dont think so.... :(
> 
> Am I in the right spot here ?
> 
> ![image](https://private-user-images.githubusercontent.com/96108132/380489092-ec57d079-765d-431b-b0ee-745ee748da78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzAwMDgsIm5iZiI6MTczMDAyOTcwOCwicGF0aCI6Ii85NjEwODEzMi8zODA0ODkwOTItZWM1N2QwNzktNzY1ZC00MzFiLWIwZWUtNzQ1ZWU3NDhkYTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDExNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMTI3YjQ4YWYyOWM1NWUwOTc5ZDgzMjZkNDI2MTA2YjU5MWY1ODkyNjllYmZiYjI0OTY5YjdkNjg2ZjQzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s8uGw-OZxBRzQFe6oIl9TNc9DICotETDDB6n-Ly_R6w)

@giduac 

Yes you are, the `_schemeOfficeColors` should match the values of a specific enum

**Comment by giduac** [comment]
@PWagner1 
Doesnt seem to be a color in the state* objects for the inactive tab ... or is there ?

**Comment by PWagner1** [comment]
To help you, there is a extension that shows the colours

**Comment by giduac** [comment]
Doing a physical binary search among the scheme colours, getting closer....

**Comment by PWagner1** [comment]
> @PWagner1 Doesnt seem to be a color in the state* objects for the inactive tab ... or is there ?

@giduac 

It might be easier to do a diff comparison between the arrays

**Comment by giduac** [comment]
Working this way is a big pain in the hynies....

**Comment by giduac** [comment]
Looks like this is hardcoded.
Set all to red in officeColors...but the inactive tab text stays blackish...

![image](https://github.com/user-attachments/assets/f31d871b-7ebb-433f-b07e-a7f3bf0f8280)

**Comment by giduac** [comment]
@PWagner1 

Found it:

![image](https://github.com/user-attachments/assets/061cd454-3eae-4974-a124-5680bd167be9)

Indeed a sort of fixed color....override

**Comment by giduac** [comment]
@PWagner1 

I disabled this override after the first line.

Can you give this fix test on this branch
https://github.com/giduac/Standard-Toolkit/tree/1399-ribbon-tab-text-O2k10-colours-not-correct.

If this goes right we'll pop it in...

**Comment by PWagner1** [comment]
> @PWagner1
> 
> I disabled this override after the first line.
> 
> Can you give this fix test on this branch https://github.com/giduac/Standard-Toolkit/tree/1399-ribbon-tab-text-O2k10-colours-not-correct.
> 
> If this goes right we'll pop it in...

@giduac 

Yes, that works

**Comment by giduac** [comment]
V95 done
V85 coming a bit later...

**Comment by Smurf-IV** [comment]
> Need to do this for V90 - Patch 1

And why was V85 removed from the list. It should be done in there as well (As it was supposed to be the them stabilisation version!)
