### ISSUE TITLE
[New Feature Request]: Access Fonts via Action Lists

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#14]
As the title says.

**Comment by Smurf-IV** [comment]
Justification ?
How Many Controls will this impact ?
Estimate time of impact?
Alternatives? (i.e. document current steps on how to do it, IF needed)

**Comment by Wagnerp** [comment]
1) To access control font with 2-3 clicks
2) Any control associated with text
3) Minimal impact (if possible)
4) `StateCommon` > `ShortText` > `Font` (for a `KryptonButton` can be longer for other controls)
