### ISSUE TITLE
[Feature Request]: Implement a `KryptonExceptionDialog`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1413]
To add a new `KryptonExceptionDialog` to the toolkit. Rather than use a normal message box to display an exception, the `KryptonExceptionDialog` will allow a option to display the full stack trace in a new modal window. The modal window will then allow the user to either copy the text, save to a file, or direct the user to a URL. specified by the developer for further investigation.

**Comment by Smurf-IV** [comment]
Probably better to bring in the `Expanding MessageBox` and use that.

**Comment by Wagnerp** [comment]
@Smurf-IV @giduac

This can be part of #1376
