### ISSUE TITLE
[Bug]: Cannot add elements on Krypton Group

### ISSUE THREAD

**Issue by pankiwi** [Krypton-Suite/Standard-Toolkit#1417]
Cannot add elements on Krypton Group on designer

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/87942313/266b4ed3-2bad-4054-8150-3adbc5ff9f93)

https://github.com/Krypton-Suite/Standard-Toolkit/assets/87942313/ed16947b-f047-4d1b-af17-d8ca26e480a4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22631.3447
 - Framework/.NET Version: .net 6
 - Toolkit Version: 80.24.3.64

**Comment by Wagnerp** [comment]
@Smurf-IV Wasn't this fixed quite recently in v90?

**Comment by giduac** [comment]
Hi @pankiwi,
In your `.csproj` file change:
`<TargetFramework>net6.0-windows</TargetFramework>` 
to:
`<TargetFrameworks>net48;net6.0-windows</TargetFrameworks>` 

Mind the 'S' TargetFrameworkS, and net48 must be the first of the two.

**Comment by Wagnerp** [comment]
Hi @pankiwi 

Building on the response from @giduac, you can find more complete documentation [here](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html).

**Comment by giduac** [comment]
@Wagnerp

No further response from @pankiwi since two weeks.
Please close the ticket. If needed it can be reopened.
