### ISSUE TITLE
[Other Issues]: Cleanup warnings KT/Ribbon/Controller

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1418]
Keeping track of files handled in the topic start and possible discussion about this can be done in this thread.

2024-05-22 | 1418-cleanup-warnings-0043 | PR 
Warnings: 

```
1418-cleanup-warnings-0042 | PR 1487 | Warnings 4 | Removes the publickey warnings CS1700
1418-cleanup-warnings-0041 | PR 1486 | Warnings 32 | Cleanup remaining warnings.
1418-cleanup-warnings-0031 | PR 1474 | Warnings 81 Revisits previously disabled throw statements.
1418-cleanup-warnings-0040 | PR 1472 | Warnings 402 | Check on CommonHelper
1418-cleanup-warnings-0030 | PR 1471 | Warnings 420 | Several warnings removed
1418-cleanup-warnings-0027 | PR 1459 | Warnings 429 | Toolkit third part
1418-cleanup-warnings-0026 | PR 1458 | Warnings 3014 | Toolkit second part
1418-cleanup-warnings-0025 | PR 1457 | Warnings 12922 | Toolkit first part
1418-cleanup-warnings-0020 | PR 1453 | Warnings 17614 | Workspace complete
1418-cleanup-warnings-0012 | PR 1451 | Warnings 19721 | Navigator second part (count is off, build without merging alpha)
1418-cleanup-warnings-0011 | PR 1446 | Warnings 19273 | Navigator first part
1418-cleanup-warnings-0010 | PR 1445 | Warnings 20224 | Docking module
1418-cleanup-warnings-0007 | PR 1444 | Warnings before: 20258 | Warnings after: 20061
1418-cleanup-warnings-0006 | PR 1443 | Warnings before: 26097 | Warnings after: 20258
1418-cleanup-warnings-0005 | PR 1440 | Warnings before: 29131 | Warnings after: 26097
1418-cleanup-warnings-0004 | PR 1438 | Warnings before: 29869 | Warnings after: 29131
1418-cleanup-warnings-0003 | PR 1437 | Warnings before: 30125 | Warnings after: 29869
1418-cleanup-warnings-0002 | PR 1429 | Warnings before: 30386 | Warnings after: 30164
1418-cleanup-warnings-0001 | PR 1421 | Warnings before: 30666 | Warnings after :30386
```

**Comment by giduac** [comment]
Hi @Wagnerp 
Since some strings are needed with the throw exceptions it might be better to put those in central location and reuse them.
Where could those be stored and how to go about it ?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp Since some strings are needed with the throw exceptions it might be better to put those in central location and reuse them. Where could those be stored and how to go about it ?

Hi @giduac 

You can use `GlobalStaticValues`.cs

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> Can these be methods be added there as well?
> 
> ```cs
> public static string VariableCannotBeNull( string variableName ) => $"Variable {variableName} cannot be null.";
> public static string PropertyCannotBeNull( string propertyName ) => $"Property {propertyName} cannot be null.";
> ```
> 
> Maybe in a separate region

Hi @giduac 

Yes they can, since they're `static`

**Comment by giduac** [comment]
@Wagnerp 
Shall we put them in a separate section or where else?

**Comment by Wagnerp** [comment]
> @Wagnerp Shall we put them in a separate section or where else?

@giduac 

You can define a new region, or create a new `GlobalStaticMethods` class.

**Comment by giduac** [comment]
@Wagnerp 
Then we'll add a region "Methods".
TY

**Comment by giduac** [comment]
@Smurf-IV @Wagnerp 

Before I turn this into a ticket can you have a look at this code as it imo contains a bug.

file: `TK/Ribbon/Controllers/QATExtraButtonController.cs`
method: `public void KeyTipSelect(KryptonRibbon ribbon)`
Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));``
The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter.

**Comment by giduac** [comment]
@Wagnerp 

Could you please have a look  at this file: `Krypton.Toolkit\General\WinFormsDefinitions.cs`
Line 9: there's a warning about: `"SystemIconsCustom.GetStockIcon(StockIconId, StockIconOptions)`
And again on 484.

Do you have an idea which method in the xml that should be?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Could you please have a look at this file: `Krypton.Toolkit\General\WinFormsDefinitions.cs` Line 9: there's a warning about: `"SystemIconsCustom.GetStockIcon(StockIconId, StockIconOptions)` And again on 484.
> 
> Do you have an idea which method in the xml that should be?

@giduac 

That can be commented out, it's an attempt at backporting `StockIcon` features

**Comment by Wagnerp** [comment]
Hi @giduac 

There seems to be a issue in `PaletteTripleJustImage` as shown below?

![Bug](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/c78d917a-520a-43a7-a423-4cc885c852e3)

**Comment by giduac** [comment]
@Wagnerp 
That's been fixed in alpha.

**Comment by Wagnerp** [comment]
> @Smurf-IV @Wagnerp
> 
> I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> 
> file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> 
> And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> 
> Shall we handle the null input or change the null param to a valid reference and what should that be ?

Hi @giduac 

I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`

**Comment by giduac** [comment]
Hi @Wagnerp ,

Could you please have a look at 
`KryptonThemeComboBoxDesigner.cs`
and
`KryptonThemeComboBox.cs`

There are several warnings in the build log (from alpha) there but I'm not fully sure if those fields mentioned can be removed or moved to another location.

If you want to correct it that's ok of course or tell met what to do and I'll fix it along with the others?

**Comment by giduac** [comment]
> > @Smurf-IV @Wagnerp
> > I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> > file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> > And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> > Shall we handle the null input or change the null param to a valid reference and what should that be ?
> 
> Hi @giduac
> 
> I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`
@Wagnerp 
I'm sorry but that's not the solution.

The `KeyTipSelect(KryptonRibbon? ribbon)` method does not process a null reference. It actually will crash on null.
This part of the Ribbon could does not seem to get called since there are no bug tickets about it.

So there are two options, imo:
1. Make sure the callers pass a valid reference to KeyTipSelect()?
2. Have KeyTipSelect() accept a null reference and handle it?

**Comment by Wagnerp** [comment]
> > > @Smurf-IV @Wagnerp
> > > I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> > > file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> > > And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> > > Shall we handle the null input or change the null param to a valid reference and what should that be ?
> > 
> > 
> > Hi @giduac
> > I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`
> > @Wagnerp
> > I'm sorry but that's not the solution.
> 
> The `KeyTipSelect(KryptonRibbon? ribbon)` method does not process a null reference. It actually will crash on null. This part of the Ribbon does not seem to get called since there are no bug tickets about it.
> 
> So there are two options, imo:
> 
> 1. Make sure the callers pass a valid reference to KeyTipSelect()?
> 2. Have KeyTipSelect() accept a null reference and handle it?

Hi @giduac 

Had another look, that parameter can be removed, since it's _**not**_ used anywhere in the method.

**Comment by Wagnerp** [comment]
> Hi @Wagnerp ,
> 
> Could you please have a look at `KryptonThemeComboBoxDesigner.cs` and `KryptonThemeComboBox.cs`
> 
> There are several warnings in the build log (from alpha) there but I'm not fully sure if those fields mentioned can be removed or moved to another location.
> 
> If you want to correct it that's ok of course or tell met what to do and I'll fix it along with the others?

Hi @giduac 

Does it say which fields are unused?

**Comment by giduac** [comment]
@Wagnerp 




> > > > @Smurf-IV @Wagnerp
> > > > I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> > > > file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> > > > And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> > > > Shall we handle the null input or change the null param to a valid reference and what should that be ?
> > > 
> > > 
> > > Hi @giduac
> > > I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`
> > > @Wagnerp
> > > I'm sorry but that's not the solution.
> > 
> > 
> > The `KeyTipSelect(KryptonRibbon? ribbon)` method does not process a null reference. It actually will crash on null. This part of the Ribbon does not seem to get called since there are no bug tickets about it.
> > So there are two options, imo:
> > 
> > 1. Make sure the callers pass a valid reference to KeyTipSelect()?
> > 2. Have KeyTipSelect() accept a null reference and handle it?
> 
> Hi @giduac
> 
> Had another look, that parameter can be removed, since it's _**not**_ used anywhere in the method.

Let me explain it again (sorry for being overly clear), hoped that works better:

in file:
`TK/Ribbon/Controllers/QATExtraButtonController.cs` 

on line 152 contains method:
`public void KeyTipSelect(KryptonRibbon ribbon)`

which executes statement:
`keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));`

in file:
`Krypton.Ribbon\View Layout\ViewLayoutRibbonQATContents.cs`

on line 112 the method is located that is called. 
`public KeyTipInfo[] GetQATKeyTips(KryptonForm ownerForm)`

That is the method where the null param goes in.
And that method does not handle null for the ownerForm param.

Back to the two possible choices:
1. Make sure the callers pass a valid reference to GetQATKeyTips()?
2. Have GetQATKeyTips() accept a null reference and handle it?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> > > > > @Smurf-IV @Wagnerp
> > > > > I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> > > > > file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> > > > > And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> > > > > Shall we handle the null input or change the null param to a valid reference and what should that be ?
> > > > 
> > > > 
> > > > Hi @giduac
> > > > I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`
> > > > @Wagnerp
> > > > I'm sorry but that's not the solution.
> > > 
> > > 
> > > The `KeyTipSelect(KryptonRibbon? ribbon)` method does not process a null reference. It actually will crash on null. This part of the Ribbon does not seem to get called since there are no bug tickets about it.
> > > So there are two options, imo:
> > > 
> > > 1. Make sure the callers pass a valid reference to KeyTipSelect()?
> > > 2. Have KeyTipSelect() accept a null reference and handle it?
> > 
> > 
> > Hi @giduac
> > Had another look, that parameter can be removed, since it's _**not**_ used anywhere in the method.
> 
> @Wagnerp Let me explain it again (sorry for being overly clear), hope that works better:
> 
> in file: `TK/Ribbon/Controllers/QATExtraButtonController.cs`
> 
> on line 152 contains method: `public void KeyTipSelect(KryptonRibbon ribbon)`
> 
> which executes statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));`
> 
> in file: `Krypton.Ribbon\View Layout\ViewLayoutRibbonQATContents.cs`
> 
> on line 112 the method is located that is called. `public KeyTipInfo[] GetQATKeyTips(KryptonForm ownerForm)`
> 
> That is the method where the null param goes in. And that method does not handle null for the ownerForm param.
> 
> Back to the two possible choices:
> 
> 1. Make sure the callers pass a valid reference to GetQATKeyTips()?
> 2. Have GetQATKeyTips() accept a null reference and handle it?

Hi @giduac 

Possibly have it pass a valid reference, as changing it in `IRibbonKeyTipTarget` would cause chaos.

**Comment by giduac** [comment]
> > @Wagnerp
> > > > > > @Smurf-IV @Wagnerp
> > > > > > I posted this earlier but received no response. Before I turn this into a ticket can you have a look at this code as it imo contains a bug.
> > > > > > file: `TK/Ribbon/Controllers/QATExtraButtonController.cs` method: `public void KeyTipSelect(KryptonRibbon ribbon)` Statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));` The code in method `GetQATKeyTips()` does not perform a null check on it's input parameter. Actually null cause a crash.
> > > > > > And in `KT/Ribbon/Controls Ribbon/KryptonRibbon.cs` at line 2360 a similar call Did a search for `GetQATKeyTips()` in the entire solution and that came up with these 2.
> > > > > > Shall we handle the null input or change the null param to a valid reference and what should that be ?
> > > > > 
> > > > > 
> > > > > Hi @giduac
> > > > > I've just changed it to `public void KeyTipSelect(KryptonRibbon? ribbon)`
> > > > > @Wagnerp
> > > > > I'm sorry but that's not the solution.
> > > > 
> > > > 
> > > > The `KeyTipSelect(KryptonRibbon? ribbon)` method does not process a null reference. It actually will crash on null. This part of the Ribbon does not seem to get called since there are no bug tickets about it.
> > > > So there are two options, imo:
> > > > 
> > > > 1. Make sure the callers pass a valid reference to KeyTipSelect()?
> > > > 2. Have KeyTipSelect() accept a null reference and handle it?
> > > 
> > > 
> > > Hi @giduac
> > > Had another look, that parameter can be removed, since it's _**not**_ used anywhere in the method.
> > 
> > 
> > @Wagnerp Let me explain it again (sorry for being overly clear), hope that works better:
> > in file: `TK/Ribbon/Controllers/QATExtraButtonController.cs`
> > on line 152 contains method: `public void KeyTipSelect(KryptonRibbon ribbon)`
> > which executes statement: `keyTipList.AddRange(popupOverflow.ViewQATContents.GetQATKeyTips(null));`
> > in file: `Krypton.Ribbon\View Layout\ViewLayoutRibbonQATContents.cs`
> > on line 112 the method is located that is called. `public KeyTipInfo[] GetQATKeyTips(KryptonForm ownerForm)`
> > That is the method where the null param goes in. And that method does not handle null for the ownerForm param.
> > Back to the two possible choices:
> > 
> > 1. Make sure the callers pass a valid reference to GetQATKeyTips()?
> > 2. Have GetQATKeyTips() accept a null reference and handle it?
> 
> Hi @giduac
> 
> Possibly have it pass a valid reference, as changing it in `IRibbonKeyTipTarget` would cause chaos.

And thats the question what reference from the caller would that be...

**Comment by Wagnerp** [comment]
> KryptonThemeComboBoxDesigner

Hi @giduac 

I've now fixed these, quite trivial :)

**Comment by giduac** [comment]
> > KryptonThemeComboBoxDesigner
> 
> Hi @giduac
> 
> I've now fixed these, quite trivial :)

Can you put that in a PR so it gets merged in the morning..?

**Comment by Wagnerp** [comment]
> > > KryptonThemeComboBoxDesigner
> > 
> > 
> > Hi @giduac
> > I've now fixed these, quite trivial :)
> 
> Can you put that in a PR so it gets merged in the morning..?

Will do, log is at 357. It has gone down since the removal of .NET 7.
