### ISSUE TITLE
[Bug]: Based on #1383 bug, version 85 code testing

### ISSUE THREAD

**Issue by Herbgh** [Krypton-Suite/Standard-Toolkit#1423]
**Describe the bug**
Based on #1383 bug, version 85 code testing found that the #1383 issue was fixed, but a new bug appeared, moving the page to the up and down left and right floating page was no problem, and when moved back to the workspace, the entire workspace crashed and disappeared

**Screenshots**

https://github.com/Krypton-Suite/Standard-Toolkit/assets/32830146/a170f1b3-0574-4ba8-b9ea-f8442c7d546b

**Comment by Smurf-IV** [comment]
@Herbgh Hello,
Can you have a look at the example as shown in the following, showing that it works as expected, following what you have shown in your vid.
Note this is running in debug and no exceptions etc are being detected.
![Workspace](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7580e935-aa39-46ff-9aa8-3cdb0bac570c)

**Comment by Smurf-IV** [comment]
And I have just repeated the test (In both net48 and 6.0) with just the nuget that you have mentioned - And it still works:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/14fa1a9b-10bc-438e-afb7-704b4d258a23)

Can you provide the a sample project with the problem please ?

**Comment by giduac** [comment]
Hi @Smurf-IV,

Since @Herbgh did not respond I would suggest to close this ticket.
If needed, it can be reopened.
