### ISSUE TITLE
[Bug]: `KryptonMessageBox` does not obey tab characters like `MessageBox`

### ISSUE THREAD

**Issue by cuppm** [Krypton-Suite/Standard-Toolkit#1424]
I'm switching usages of MessageBox to KryptonMessageBox and I noticed that the Krypton version does not display tabs in the message the same way that the WinForms version does.

**To Reproduce**
```
string strMessage = "First line\r\nSecond line\r\n\r\nFourth line\r\nLeft\tTabbed by 1\r\nLeft\t\tTabbed by 2";
MessageBox.Show(strMessage);
KryptonMessageBox.Show(strMessage);
```

**Expected behavior**
The text to be tabbed over from the left margin like the WinForms MessageBox does.

**Screenshots**
WinForms
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/e906a69b-65d3-4c40-a354-d483ec9e6d53)

Krypton
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/c693c064-b85e-4bec-a302-1eadcbbd2b40)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 19045.4291
 - Framework/.NET Version: Framework 4.8 
 - Toolkit Version: v4.0.30319

**Comment by Smurf-IV** [comment]
@Wagnerp Should this be fixed in 8.5 as well ?

**Comment by Smurf-IV** [comment]
@cuppm You state that the toolkit version is `v4.0.30319`
This GitHub version does not support that.
Can you please use a recent version (i.e. V80.xx.x..)

**Comment by Wagnerp** [comment]
> @Wagnerp Should this be fixed in 8.5 as well ?

@Smurf-IV Yes it should, as the bug is present in older versions. I remember submitting a bug report about a similar issue a few months ago...

**Comment by Smurf-IV** [comment]
> > @Wagnerp Should this be fixed in 8.5 as well ?
> 
> @Smurf-IV Yes it should, as the bug is present in older versions. I remember submitting a bug report about a similar issue a few months ago...

Can you find it and link please?

And I've just checked and it is still broken in the Current Alpha:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ddb5dc1b-d653-4a51-9b2b-ffd1773d9a46)

**Comment by Wagnerp** [comment]
> > > @Wagnerp Should this be fixed in 8.5 as well ?
> > 
> > 
> > @Smurf-IV Yes it should, as the bug is present in older versions. I remember submitting a bug report about a similar issue a few months ago...
> 
> Can you find it and link please?
> 
> And I've just checked and it is still broken in the Current Alpha: ![image](https://private-user-images.githubusercontent.com/2418812/326167633-ddb5dc1b-d653-4a51-9b2b-ffd1773d9a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDkwMDIsIm5iZiI6MTcxNDIwODcwMiwicGF0aCI6Ii8yNDE4ODEyLzMyNjE2NzYzMy1kZGI1ZGMxYi1kNjUzLTRhNTEtOWIyYi1mZmQxNzczZDlhNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDkwNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU1YzA1ZGEzYzM5YjhiNzk0NTkxZTgxMWM5YTg2ZTE4OGFkOGQ1NWFlMmFkMmQxYjg3ODI0ZWM0NGRiMmEwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sv1XFLesKkH8moPe8_tFwrq8Uq1hbyEwNY2qMIzMIIo)

Will do, once/if I can find it

**Comment by Smurf-IV** [comment]
@Wagnerp Q: Why are the Font and the Text colour hard coded ? They should use the themes colours ??
Or is this just in 8.5 ?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ed4b4e13-d4c5-43a8-a271-b9de73c0671f)

**Comment by Wagnerp** [comment]
> @Wagnerp Q: Why are the Font and the Text colour hard coded ? They should use the themes colours ?? Or is this just in 8.5 ?
> 
> ![image](https://private-user-images.githubusercontent.com/2418812/326168107-ed4b4e13-d4c5-43a8-a271-b9de73c0671f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDk0ODIsIm5iZiI6MTcxNDIwOTE4MiwicGF0aCI6Ii8yNDE4ODEyLzMyNjE2ODEwNy1lZDRiNGUxMy1kNGM1LTQzYTgtYTI3MS1iOWRlNzNjMDY3MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDkxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIzMjhkMmQ5ZmZhMThkM2Y5M2IxMGY3ZGI3NDNmNmVjNjI0NGE1OWViMmVjZjU0NjQ2OTZhZjNkNTYxMDkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WPn_JGhLU3l6Bizsd20gdD4DmI9KXpyuuuF25Sq5Eeg)

@Smurf-IV I think it's a left over from a older version.

**Comment by Smurf-IV** [comment]
FYI:
KWrapLabel is based on the winform Label; Which cannot do tabs :-(
https://stackoverflow.com/questions/2154623/winforms-label-text-property-not-displaying-t-tab-character

**Comment by Wagnerp** [comment]
> FYI: KWrapLabel is based on the winform Label; Which cannot do tabs :-( https://stackoverflow.com/questions/2154623/winforms-label-text-property-not-displaying-t-tab-character

Extend the `Label`?

**Comment by Smurf-IV** [comment]
> Option 3:

Winforms just redirects to the underlying Win32 MessageBox in the `User32` system dll !!

**Comment by Wagnerp** [comment]
> Option 2: Change to use a Text box without edit or border to ensure text formatting

Could use `KryptonRichTextBox`, as that offers far more flexibility, i.e. inline hyperlinks etc.

**Comment by Wagnerp** [comment]
Is there a way to capture tabs, and replace them with `alt-255`?

>  What I ended up doing was using alt code alt-255 5 times.

**Comment by Smurf-IV** [comment]
> Is there a way to capture tabs, and replace them with `alt-255`?
> 
> > What I ended up doing was using alt code alt-255 5 times.

Yes: that's option 1...

**Comment by Smurf-IV** [comment]
Option 2 gives this:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/307c7fee-bcce-4b3d-ab22-e68287fe271e)

I'll now investigate using an RichTextBox

**Comment by Smurf-IV** [comment]
`RichTextBox` makes a mess of the LinkLabel usages, So I will not change that.
As LinkLabels are going to be removed from the V90 messageBox to restore it back to stand usage - Yes ?

**Comment by Wagnerp** [comment]
> `RichTextBox` makes a mess of the LinkLabel usages, So I will not change that. As LinkLabels are going to be removed from the V90 messageBox to restore it back to stand usage - Yes ?

Yes, as they can be used in the newer expandable version.

**Comment by cuppm** [comment]
> @cuppm You state that the toolkit version is `v4.0.30319` This GitHub version does not support that. Can you please use a recent version (i.e. V80.xx.x..)

Sorry, I copied the .NET runtime version string instead of the Krypton toolkit version.  As you've already deduced it affected the current release of 80.24.3.64.

Thanks for fixing this.
