### ISSUE TITLE
[Other Issues]: Update documentation to allow for longer path/file names

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1431]
**Describe the bug**
The Alpha branch wont build after a commit from last Saturday.
This was first mentioned in:  https://github.com/Krypton-Suite/Standard-Toolkit/pull/1430

@Wagnerp 
The path errors (to long file names) errors I had, have been solved by allowing Windows to use longer names through a policy.

I tried the Alpha branch but it still doesn't build. 

2 files are involved which we both edited.
TK/Ribbon/Controller/AppButtonController.cs
TK/Ribbon/Controller/AppTabController.cs

There are 6 errors produced at the end of the build and those are related to these merges:

This is the merge that went first:
Merge pull request [#1421](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1421) from giduac/1418-cleanup-warnings-0001

Second went:
https://github.com/Krypton-Suite/Standard-Toolkit/commit/78b012722ed2a3cb2a14d4b031d0d4f2ed4bb969
Which alters both files and the change in AppButtonController.cs causes the errors.

Looking at your last commit you removed the error in the 1281-.... branch.
In the next PR I'll be posting, those 2 files will have some more changes. 

Looks like your last commit should be merged first.

**Comment by Wagnerp** [comment]
Hi @giduac 

Going to update docs to state that the command `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" ` -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force` must be run to allow longer path names

cc. @Smurf-IV

**Comment by giduac** [comment]
@Smurf-IV 
Gpedit sets it via the policy which under the hood changes the registry value.
Often Gpedit can make policies take effect instantly as manual registry change mostly do not.

If you go down the registry road you might need a logoff/logon or a reboot for the changes to take effect.

I tested it with a 300 character long file name....

**Comment by Wagnerp** [comment]
> @Smurf-IV @Wagnerp Gpedit sets it via the policy which under the hood changes the registry value. Often Gpedit can make policies take effect instantly as manual registry change mostly do not.
> 
> If you go down the registry road you might need a logoff/logon or a reboot for the changes to take effect.
> 
> I tested it with a 300 character long file name....

@giduac 

Would you mind telling me where in `gpedit` the setting is, so that I can update the docs? Thanks!

**Comment by giduac** [comment]
It's called the Group Policy Editor.
You can find it in the start menu by type group...

Or start an (admin) command prompt and type: gpedit.msc

there are a lot of those *.msc files which are Microsoft Management Consoles.
compmgmt.msc for example runs Computer Management.

**Comment by giduac** [comment]
@Wagnerp 
I saw you changed the title, but is it some how possible to give this merge from your side a little priority?
I'm kind of stuck here now...

**Comment by Wagnerp** [comment]
> @Wagnerp I saw you changed the title, but is it some how possible to give this merge from your side a little priority? I'm kind of stuck here now...

@giduac 

Going to create a PR now

**Comment by giduac** [comment]
@Wagnerp 
Great!

**Comment by giduac** [comment]
@Wagnerp 
Sorry i missed that policy settings path you asked for, misread your question:
You can add it from this explanation:
https://thegeekpage.com/make-windows-11-accept-file-paths-over-260-characters/
