### ISSUE TITLE
[Bug]: Assignment of `CustomPalette` to a `KryptonComboBox` (Within Designer) causes runtime - Dependent on creation order.

### ISSUE THREAD

**Issue by pankiwi** [Krypton-Suite/Standard-Toolkit#1447]
Error on build proyect combo box

1. Place custom palette
2. Set palette on the form
3. Place krypton combobox 
4. Build it

**Expected behavior**
I think Someone default values on  palette break something on the font

**Screenshots**
![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/87942313/90ee06b6-3bd4-49b1-9a92-a8c1397eb91b)
![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/87942313/95d18fdd-e643-4f6a-a705-dfa3c5583e29)

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  - Version: 22631.3447
 - Framework/.NET Version: net 4.8 && net 7.0 windows [multi targets]
 - Toolkit Version: 80.24.3.64

**Comment by giduac** [comment]
Hi @pankiwi 
cc: @Smurf-IV 

Looks like this is the same error as has been resolved in [Issue 1462](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1462). 

I'd like to suggest that you try the next Nightly build to test if this has been resolved?

Please keep us posted, ty.

**Comment by giduac** [comment]
Hi @pankiwi 
A new Nightly has arrived....
