### ISSUE TITLE
[Bug]: **Regression** KComboBox text is clipped; as height is incorrect.

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1455]
Using April 2024 alpha:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/9b9515b3-a798-40b6-818e-2a1ae7c708d7)

Win 10 22H2 (Latest)

**Comment by Smurf-IV** [comment]
<PackageReference Include="Krypton.Toolkit.Canary" Version="80.22.11.325-beta" />:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/21705e40-14e8-4df1-9d8f-e5d2ad950b38)

**Comment by Smurf-IV** [comment]
I'm confused, With that much clipping, surely someone would have mentioned it as a show stopper before now !!?

**Comment by Smurf-IV** [comment]
It seems it's just the MessageBox Demo app (At the moment)

If I use the workaround mentioned here: #685 615
the Height is sorted, but the text is still clipped !!
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/66092aca-b020-453a-a12d-61b833e9dc83)

**Comment by Smurf-IV** [comment]
This "Maybe" a clue.
- If I force a font into the StateCommon -> ComboBox -> Content
  - Then the size in the designer and the UI will be correct.

So the clue might be the designer (and at runtime) is picking up a null or small font for the height of the text area,
But when the text is actually drawn using the the them font, it is obviously "clipping out" due to "Not enough height"

**Comment by giduac** [comment]
Hi @Wagnerp,

Please assign this one to me.
TY.

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> Please assign this one to me. TY.

Hi @giduac 

Done, should this be for v85?

**Comment by giduac** [comment]
@Wagnerp 
Not sure yet.

Testing this on alpha & the latest V80 release.
The results are slightly different. It's actually more prominent and/or better reproduceable in alpha atm.
Needs an hour an extra hour of fiddling to have it all tested...

**Comment by giduac** [comment]
@Wagnerp,

V90 Fix (PR underway)
Itemheight is derived from Font.Height and in one accocasion (addresses in the code below) the ItemHeight = Font.Height -1
which causes the lower part of the text to become clipped.

```cs
// Working on Windows XP or earlier systems?
if (_osMajorVersion < 6)
{
	// Fudge by adding one to the font height, this gives the actual space used by the
	// combo box control to draw an individual item in the main part of the control
	ItemHeight = Font.Height + 1;
}
else
{
	// Vista performs differently depending of the use of themes...
	if (IsAppThemed)
	{
		// Fudge by subtracting 1, which ensure correct sizing of combo box main area
		//ItemHeight = Font.Height - 1;
		
		// #1455 - lower part of the text can become clipped with chars like g, y, p, etc.
		// when subtracting one from the font height. 
		ItemHeight = Font.Height;
	}
	else
	{
		// On under Vista without themes is the font height the actual height used
		// by the combo box for the space required for drawing the actual item
		ItemHeight = Font.Height;
	}
}
```

**Comment by giduac** [comment]
@Wagnerp 

In motion:

https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/b2758826-c4b8-42ee-b129-1d78f6ef43f4

**Comment by giduac** [comment]
Hi @Wagnerp,

Problem is fix. 
Please close, ty.

**Comment by Smurf-IV** [comment]
Using .net8 then the compressed combobox is still visible:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6ec0ef29-6d3c-4034-90e1-d28a195c680b)

**Comment by giduac** [comment]
@Smurf-IV 
Weird, looks good here with .net 8


https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/128998d2-1e2b-4d15-b9b2-6c4ef305b980

**Comment by giduac** [comment]
Its in alpha or the latest nightly

**Comment by Smurf-IV** [comment]
> Weird, looks good here with .net 8


I'm running on Win 10

> Its in alpha or the latest nightly

Yup, just latest on both repo's and built

**Comment by Smurf-IV** [comment]
If I remove the following from the `App.manifest` file, then it works (But looks pants)

**Comment by giduac** [comment]
Can try the test thingy:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/371#issuecomment-2183954858
see how that goes

**Comment by giduac** [comment]
Is it only with the ribbon combo or also the normal ones?

**Comment by giduac** [comment]
@thats the correct post:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/371#issuecomment-2183952112

**Comment by Smurf-IV** [comment]
> @thats the correct post: [#371 (comment)](https://github.com/Krypton-Suite/Standard-Toolkit/issues/371#issuecomment-2183952112)

That app when set to run in net48 does not show a ribbon ??
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/261bc217-ea65-4655-aaec-9589d1cfdf1c)

**Comment by giduac** [comment]
how does it look 8.0?

**Comment by giduac** [comment]
net48....
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/5a44284c-2544-483f-84fa-0e5289589d0b)

**Comment by Smurf-IV** [comment]
I do not get that view, Do you have several branches in your duplicate repro I'm supposed to use ?

**Comment by giduac** [comment]
https://github.com/giduac/Standard-Toolkit-Demos/tree/ribbon-controls-themes-test
**Demo Solution: Krypton Ribbon Examples 2022 (Debug) - Nuget**
**Project: Application Menu 2022**
TK: Latest Nightly 169

**Comment by Smurf-IV** [comment]
Squished when running in .net8:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/3d998786-cf24-4ac5-b74b-e5bbb0d6c754)

**Comment by giduac** [comment]
@Smurf-IV 
That DTPicker has a bigger height

That inner combo is still pretty close to the lower edge.
That was previously also the case.

Can the inner combo be placed slightly higher?

**Comment by giduac** [comment]
@Smurf-IV 
Well in 11 the combo has the same height as the DTPicker
So its not the text but control that gets a different size in 10...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/de2305b3-540e-4670-97ea-875503364fd4)

**Comment by giduac** [comment]
W10 22H2 X64 Net 80 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/862a262b-298f-49a7-be07-8b6182c702b3)

**Comment by giduac** [comment]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/680b0508-d8bc-4522-87e6-274909cbe372)

**Comment by Smurf-IV** [comment]
Mine is slightly newer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e9b9bd0f-882a-40bc-ad25-164527919b98)

**Comment by giduac** [comment]
can do a fresh install later on with full updates.
But it's not consistently wrong.......

**Comment by giduac** [comment]
@Smurf-IV 
Or you do an update on that one ?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Or you do an update on that one ?

I cannot go backwards ??

**Comment by giduac** [comment]
No rather forward to if still exists then.
Then you should look for a fix cause here all looks as it should...

**Comment by giduac** [comment]
But it could just as well be something in that W10 setup

**Comment by Smurf-IV** [comment]
> No rather forward to if still exists then. Then you should look for a fix cause here all looks as it should...

My number is way higher than yours.. 
I do not understand.

> But it could just as well be something in that W10 setup

Agreed, but it'll need sorting

**Comment by giduac** [comment]
Can you install a fresh Win10 VM from ISO with the network detached so it cant update. ??
I'll do one and let it do all the updates (probably takes half a day or so :( ).

Gives us some more reference material

**Comment by giduac** [comment]
And the outlook clone looks good here too. 
Tends strongly towards Windows....

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/bde8531b-2f2c-4a71-9388-eb23e8e928aa)

**Comment by giduac** [comment]
Old Skool W10
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/5f0495bd-2267-478e-a7ee-9b68d04dc9ec)

**Comment by giduac** [comment]
W10 New Skool
Not reproduceable .....
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/141afed1-7efb-4663-8d28-d6bda036c5ba)

**Comment by Smurf-IV** [comment]
@Wagnerp @giduac I know this is marked as 8.5, but I'll have to look at it next w/e (i.e. end of June after release of 8.5 patch!)

**Comment by Wagnerp** [comment]
> @Wagnerp @giduac I know this is marked as 8.5, but I'll have to look at it next w/e (i.e. end of June after release of 8.5 patch!)

@Smurf-IV 

Can be released after tomorrows release... no big rush.

**Comment by Smurf-IV** [comment]
Investigation(Using today's Alpha's from both repo's):
- after fixing the issue with the demo not "building" for the OP App - I get the expected result:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/62bb0c3b-1f8a-4933-9bc9-d001d8d2be3f)

Moving on to the Ribbon app Demo
- In the designer the font is **as expected**:
  - ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/bebb5dbb-c09a-43d1-890a-89747e393229)
- when running it is forced to be **something else** (net48)
  - ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/d9e248c6-41df-43b2-a298-cbf341e0cd7a)
- Darn it, the font for the combo was being overridden in the Form create !!

Unable to reproduce today on the same machine that was producing problems as captured above (Last weekend), now looks like:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/9547035c-0ce6-4e43-9677-ca41f016a060)
