### ISSUE TITLE
[Question]: Are the `AssemblyInfo.cs` files now redundant

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#146]
Are the `AssemblyInfo.cs` files now redundant, can they be removed?

**Comment by Smurf-IV** [comment]
No they are not, as the csproj files do not contain the data needed to replace them.
So this is either a task to remove and update the csproj's (To ensure that the copyrights etc are generated correctly)
Or leave them as is !

**Comment by Wagnerp** [comment]
Ok, I think they might be linked to #118

**Comment by Wagnerp** [comment]
I'll have a look at how the `csproj` files can be updated to handle the data

**Comment by Wagnerp** [comment]
@Smurf-IV Yes! I've done the work & got the total # of warnings down from 1055 to 800.

**Comment by Wagnerp** [comment]
A solution has been issued in the August 2021 (Canary) update.
