### ISSUE TITLE
[Feature Request]: Remove designer visibility of `MouseDoubleClick` and `DoubleClick` Events for the `KryptonComboxBox`

### ISSUE THREAD

**Issue by lesandrog** [Krypton-Suite/Standard-Toolkit#1461]
**Describe the bug**.
KryptonComboxBox MouseDoubleClick and DoubleClick Event is not triggered.

**To Reproduce**
Add a KryptonComboBox.
Add the KryptonComboBox1.MouseDoubleClick event.

    Private Sub KryptonComboBox1_MouseDoubleClick(sender As Object, e As MouseEventArgs) Handles KryptonComboBox1.MouseDoubleClick
        MessageBox.Show("test")
    End Sub

**Expected behavior**
With a double click on the combobox, the event should trigger the messagebox, but this does not happen.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 22631.3527
 - Framework/.NET Version: 4.8 (vb.net \ Windows Forms)
 - Toolkit Version: Krypton.Toolkit 80.24.3.64

**Comment by Smurf-IV** [comment]
The KComboBox should **NOT** have the `DoubleClick` event anyway :
Here's the Winform ComboBox:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7d84299d-f123-46bd-8045-4bdb6e82d2aa)

**Comment by Smurf-IV** [comment]
And I cannot get a normal winform comboBox to fire the following either:
`this.comboBox1.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.comboBox1_MouseDoubleClick);`

**Comment by Smurf-IV** [comment]
HMM:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/2e7d888c-d523-40d2-80d7-d4822d4d8219)
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.doubleclick?view=netframework-4.8

So there is a bug in the KComboBox, in that it "Should **NOT**" be showing this event in the designer !

**Comment by Wagnerp** [comment]
?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8aba9dd7-6927-4d6e-bbd3-dcb390462378)

**Comment by Smurf-IV** [comment]
Yes, You can programmatically add it, as it is part of the base control class, but it does nothing (i.e. does not fire) in a combobox, because the first click is absorbed to perform the select.

**Comment by Wagnerp** [comment]
The KComboBox derives from `VisualControlBase`, is it possible to 'hide' these options for this case?

**Comment by Smurf-IV** [comment]
> The KComboBox derives from `VisualControlBase`, is it possible to 'hide' these options for this case?

Yes, by overriding them and making them designer hidden via attribute(s)

**Comment by Smurf-IV** [comment]
More info:
`By default, a combo box cell cannot receive a double-click with the left mouse button. The cell goes into edit mode on the first click, so the next click goes to the Combo control that is the subeditor.`
