### ISSUE TITLE
[Question]: Krypton group visualization problem when resizing the form, the group "detaches" from the Ribbon

### ISSUE THREAD

**Issue by mbagattini** [Krypton-Suite/Standard-Toolkit#1463]
After upgrading a project from .NET 4.8 to .NET 6 I'm getting this misbehaviour (among others)  on a Ribbon: upon resizing, the control does not scale correctly and show this sort of overflow popup.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/941612/51b2c411-747e-48f5-bdbc-8d1823494c1d)

Any way to disable it? I changed that triple container to behave with MaximumSize = Large and MinimumSize = Medium, the ribbon instead of scaling other controls is doing as pictured.

**Comment by Smurf-IV** [comment]
@mbagattini 
- Version of Krypton ?
- Multi target the application to be both 4,8 and core 6 and run both side by side!
- Add an Example project to here ?
- Try running the examples and see what happen on your environment !

**Comment by mbagattini** [comment]
I'm on 70.x, will surely try with 80.x. Can't upgrade at the moment, I thought maybe this was a known behaviour avoidable by setting some property but looks like it is now. Feel free to close this one for the time being, I think I will be able to check version 80.x only in a few weeks.

**Comment by Smurf-IV** [comment]
@mbagattini 
With todays alpha branch I get this:
![ShrinkingV90](https://github.com/user-attachments/assets/aa3dad50-2fed-4308-b164-02903549ccfb)

And I get the same response (Different colours) in the V85 which should be the same as V80)
![image](https://github.com/user-attachments/assets/f9ba5182-a3e8-481c-8d71-eb1a1865a4d7)

Please repopen if you can give an example please ?

**Comment by mbagattini** [comment]
Thanks for the ping, will try the updated version sooner or later and eventually update here.
