### ISSUE TITLE
[Bug]:  Using version: 80.24.3.64 I have an anomaly on the form display when it is maximized.

### ISSUE THREAD

**Issue by Fux-Paolo** [Krypton-Suite/Standard-Toolkit#1464]
**Describe the bug**

**To Reproduce**
![Ribbon](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124615976/0982976d-53bc-4045-92e5-a20d50a7d81b)
![Ribbon](https://github.com/Krypton-Suite/Standard-Toolkit/assets/124615976/c1d8945b-6246-412b-bbe9-10f573378f8a)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version: [e.g. 4.8.1] 
 - Toolkit Version: [e.g. 70.22.12.312]

**Additional context**

**Comment by giduac** [comment]
Hi @Fux-Paolo 

Can you please add a sample project that exhibits the error?

**Comment by Fux-Paolo** [comment]
https://github.com/Krypton-Suite/Standard-Toolkit/assets/124615976/dad2f62e-c03a-4261-9174-5f0f9400f065

[TestRibbon.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/15333057/TestRibbon.zip)

**Comment by Fux-Paolo** [comment]
Good morning giduac, are there any updates?
Is there a way to fix the display?
Grazie
Paolo

**Comment by Smurf-IV** [comment]
@Fux-Paolo Hello
This was fixed when the (If I remember correctly) when the `AllowFormIntegrate` was removed from the Ribbon designer.
It can be tested with the following in your project:
``` c#
  <ItemGroup>
    <PackageReference Include="Krypton.Ribbon.Canary" Version="90.24.4.113-beta" />
  </ItemGroup>
```
Nothing else is required in your vbproj.

You will also need to modify your `designer` file 
- to remove `AllowFormIntegrate`
- And if you still want a close to be driven by the app bar, then add `KryptonRibbon1.RibbonFileAppButton.FormCloseBoxVisible = True`

**Comment by Fux-Paolo** [comment]
Thanks Simon, everything is working properly nowSimon,
Paolo
