### ISSUE TITLE
[Bug]: Canary - KryptonCustomPaletteBase --> null reference

### ISSUE THREAD

**Issue by AngeloCresta** [Krypton-Suite/Standard-Toolkit#1465]
Hi, I have a reference null exeption in SetPalette(..) method KryptonCustomPaletteBase.cs (ln 5845 - Canary)  

I suggest to modify the code initializing the basePalette if null:

```
   private void SetPalette(PaletteBase basePalette)
        {
            if (basePalette == null)
            {
                basePalette  = new KryptonCustomPaletteBase();
            }
            ....
```
Regards, 
Angelo

**Comment by giduac** [comment]
Hi @AngeloCresta 

Which version of the toolkit are you using?
Did you try other versions, and if so was the error present as well ?
Can you please provide a simple sample project that demonstrates the error?

**Comment by AngeloCresta** [comment]
`<TargetFrameworks>net8.0-windows</TargetFrameworks>`
Angelo

**Comment by giduac** [comment]
Which **Canary** version of the toolkit are you using?

**Comment by AngeloCresta** [comment]
I grab the version from GitHub yesterday, based on your label v90.24.4.113-beta

**Comment by giduac** [comment]
The above video does show anything going wrong.
The current code actually does null checking and that code is also present in the master branch. So earlier versions will act the same.

So we need some more info about how & what exactly is happening?

```cs
        private void SetPalette(PaletteBase basePalette)
        {
            if (basePalette != _basePalette)
            {
                Debug.Assert(_basePalette != null);

                // Unhook from current palette events
                if (_basePalette != null)
                {
                    _basePalette.PalettePaint -= OnPalettePaint;
                    _basePalette.ButtonSpecChanged -= OnButtonSpecChanged;
                    _basePalette.BasePaletteChanged -= OnBasePaletteChanged;
                    _basePalette.BaseRendererChanged -= OnBaseRendererChanged;
                }

                // Remember the new palette
                _basePalette = basePalette;

                // Make sure the redirector passes requests onto the base palette
                _redirector.Target = _basePalette;

                // Update the color table we inherit from
                ToolMenuStatus.BaseKCT = _basePalette.ColorTable;

                // Hook to new palette events
                if (_basePalette != null)
                {
                    _basePalette.PalettePaint += OnPalettePaint;
                    _basePalette.ButtonSpecChanged += OnButtonSpecChanged;
                    _basePalette.BasePaletteChanged += OnBasePaletteChanged;
                    _basePalette.BaseRendererChanged += OnBaseRendererChanged;
                }
            }
        }
```

**Comment by AngeloCresta** [comment]
No, because I've added this on the method:
```
   private void SetPalette(PaletteBase basePalette)
        {
            if (basePalette == null)
            {
                basePalette  = new KryptonCustomPaletteBase();
            }
            ....
```

Commenting it out I have:

![ModernUI-KryptonIntegration-Error](https://github.com/Krypton-Suite/Standard-Toolkit/assets/12256319/1c5a71ca-c23d-41fd-8927-6be34b0864dd)

But, as I said, is up to you ... 
Angelo

**Comment by giduac** [comment]
I see, but: basePalette is not nullable and should be a valid param to a palette.

**Comment by AngeloCresta** [comment]
Ok, I'll update my code to be sure that the custom palette is always inialized.
Thanks
