### ISSUE TITLE
[Bug]: Build Scripts will run when no suitable environment is detected. | Add BinLog option to build-nightly.cmd

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1475]
**Describe the bug** [PR 1476](https://github.com/Krypton-Suite/Standard-Toolkit/pull/1476)
When no suitable environment is detected by the build scripts will still try to run.

Excerpt from `build-nightly.cmd`.
```batch
@echo off

if exist "%ProgramFiles%\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin" goto vs17prev
if exist "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" goto vs17ent
if exist "%ProgramFiles%\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin" goto vs17pro
if exist "%ProgramFiles%\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin" goto vs17com
if exist "%ProgramFiles%\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin" goto vs17build

echo "Unable to detect suitable environment. Check if VS 2022 is installed."

pause

:vs17prev
set msbuildpath=%ProgramFiles%\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin
goto build

```
### Proposed solution:
Add a `goto exitbatch` statement after `pause`.
Add the `:exitbatch` label at the end of the file.

### Add the "/bl" parameter to the msbuild line of  `build-nightly.cmd`
```batch
"%msbuildpath%\msbuild.exe" -t:%targets% nightly.proj /fl /flp:logfile=build.log /bl
```
This will output, next to the build.log, a msbuild.binlog that can be viewed/examined with ["MSBuild Binary and Structured Log Viewer"](https://msbuildlog.com/).

**Comment by giduac** [comment]
Hi @Wagnerp,
Please assign to me.
TY!

**Comment by Wagnerp** [comment]
> Hi @Wagnerp, Please assign to me. TY!

Hi @giduac 

Done, you might want to bump the version up. Currently it's 1.9.

**Comment by giduac** [comment]
@Wagnerp 
Where is the version located and what would the next version number be?
Then I'll add it to the PR.

**Comment by Wagnerp** [comment]
> @Wagnerp Where is the version located and what would the next version number be? Then I'll add it to the PR.

Hi @giduac 

It's on line 9 of the batch file.

**Comment by giduac** [comment]
> > @Wagnerp Where is the version located and what would the next version number be? Then I'll add it to the PR.
> 
> Hi @giduac
> 
> It's on line 9 of the batch file.

Got it, I'll make it 2.0

**Comment by giduac** [comment]
Hi @Wagnerp ,

May be another interesting switch to use with msbuild.
This one removes unnecessary output:
```cmd
 /consoleloggerparameters:Summary /verbosity:quiet
```
[More info here](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)

**Comment by Wagnerp** [comment]
> Hi @Wagnerp ,
> 
> May be another interesting switch to use with msbuild. This one removes unnecessary output:
> 
> ```batchfile
>  /consoleloggerparameters:Summary /verbosity:quiet
> ```
> 
> [More info here](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)

Hi @giduac 

That does lower the verbosity a lot! I wonder if we can also package the binaries into `zip` files for distribution?

**Comment by giduac** [comment]
@Wagnerp 
I was thinking about a Windows frontend for building. But needs a decent redirection of the msbuild console output into th.
Adding compression could be a part, etc....

**Comment by giduac** [comment]
@Wagnerp 
For zipping you can use 7zip. 
It's free and has a command line zipper: 7z.exe
That can be scripted.

**Comment by Wagnerp** [comment]
> @Wagnerp For zipping you can use 7zip. It's free and has a command line zipper: 7z.exe That can be scripted.

Hi @giduac 

If you want to take a shot at this, then go ahead. The zip file should contain _all_ DLL & XML files as laid out in the `bin` directory. As for the file name, I think it should be `Standard_Toolkit-<#BUILD-VERSION#>-<#DATE#>-<alpha/beta/stable>.zip`. Thoughts @giduac & @Smurf-IV?

**Comment by giduac** [comment]
> > @Wagnerp For zipping you can use 7zip. It's free and has a command line zipper: 7z.exe That can be scripted.
> 
> Hi @giduac
> 
> If you want to take a shot at this, then go ahead. The zip file should contain _all_ DLL & XML files as laid out in the `bin` directory. As for the file name, I think it should be `Standard_Toolkit-<#BUILD-VERSION#>-<#DATE#>-<alpha/beta/stable>.zip`. Thoughts @giduac & @Smurf-IV?
@Wagnerp 
What is the use of these zips as you can get all builds from Nuget?

**Comment by Wagnerp** [comment]
> > > @Wagnerp For zipping you can use 7zip. It's free and has a command line zipper: 7z.exe That can be scripted.
> > 
> > 
> > Hi @giduac
> > If you want to take a shot at this, then go ahead. The zip file should contain _all_ DLL & XML files as laid out in the `bin` directory. As for the file name, I think it should be `Standard_Toolkit-<#BUILD-VERSION#>-<#DATE#>-<alpha/beta/stable>.zip`. Thoughts @giduac & @Smurf-IV?
> > @Wagnerp
> > What is the use of these zips as you can get all builds from Nuget?

@giduac Another way to distribute builds, via WinGet?

**Comment by giduac** [comment]
> > > > @Wagnerp For zipping you can use 7zip. It's free and has a command line zipper: 7z.exe That can be scripted.
> > > 
> > > 
> > > Hi @giduac
> > > If you want to take a shot at this, then go ahead. The zip file should contain _all_ DLL & XML files as laid out in the `bin` directory. As for the file name, I think it should be `Standard_Toolkit-<#BUILD-VERSION#>-<#DATE#>-<alpha/beta/stable>.zip`. Thoughts @giduac & @Smurf-IV?
> > > @Wagnerp
> > > What is the use of these zips as you can get all builds from Nuget?
> 
> @giduac Another way to distribute builds, via WinGet?
@Wagnerp 
And winget is integratable with VStudio ?

**Comment by giduac** [comment]
@Wagnerp 
I've been fiddling a bit with a windows frontend for creating builds. 
It's pretty simple atm. But building works fine and the msbuild screen output is redirected into the program and can be handled.
Looks interesting and promising....

**Comment by Wagnerp** [comment]
> @Wagnerp I've been fiddling a bit with a windows frontend for creating builds. It's pretty simple atm. But building works fine and the msbuild screen output is redirected into the program and can be handled. Looks interesting and promising....

Hi @giduac 

I've been wondering for some time now whether to create a app to batch upload nugets. At the moment it's done by batch files, but I can't integrate it into the build system, as it would expose the API key to everyone.

**Comment by giduac** [comment]
> > @Wagnerp I've been fiddling a bit with a windows frontend for creating builds. It's pretty simple atm. But building works fine and the msbuild screen output is redirected into the program and can be handled. Looks interesting and promising....
> 
> Hi @giduac
> 
> I've been wondering for some time now whether to create a app to batch upload nugets. At the moment it's done by batch files, but I can't integrate it into the build system, as it would expose the API key to everyone.
So that's done kind of manually.

That front end can have an option for that which would only work if an API key is available in a certain location or so...
Or run those batch files in the background...
