### ISSUE TITLE
[Bug]: Krypton Navigator - Crash after selecting modes

### ISSUE THREAD

**Issue by JeanPasquini** [Krypton-Suite/Standard-Toolkit#1477]
### **Describe the bug**

The control Krypton.Toolkit.KryptonGroupPanel has thrownan unhandled exception in the designer and has beendisabled.

Exception:
Object reference not set to an instance of an object.

After to select any 2 modes, the kripton gave me an error message and crash the IDE (Visual Studio 2022 V.17.9.7).

**Message:**

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126198701/5a3d58d6-ef4f-4351-88ab-0bc6c6fc6bed)

----------------

### **To Reproduce**
1. Add a KryptonNavigator in form.
2. In modes, select these 2 options ("Stack - CheckButton - HeaderGroup" or "Outlook - Full").

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126198701/8f606c3e-959a-4325-a2bf-401f486766a0)

------------------

### **Expected behavior**
After selecting the mode, it would change the appearance and customize the navigator, like with other modes.

-----------------

### **About my versions**

 - OS: Windows 11 (V.23H2)
 - Framework/.NET Version: 8.0.300 
 - Toolkit Version: 80.24.3.64

**Comment by Wagnerp** [comment]
Hi @JeanPasquini 

This has been fixed in V90.
