### ISSUE TITLE
[Bug]: Toolkit Nightly Alpha - KryptonHeaderGroup doesn't disappear

### ISSUE THREAD

**Issue by JeanPasquini** [Krypton-Suite/Standard-Toolkit#1478]
### **Describe the bug**
Error message when I try to delete the KryptonHeaderGroup. After to try delete, the component doesn't disapper in the form, so I need to open again the Visual Studio.

Screenshots:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126198701/00105614-b5e7-4289-a5a6-b879aecb1b76)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126198701/4187032d-22c8-4d66-a48a-9d894e3dfb60)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126198701/9551e962-c8a7-4c69-85e6-2265a1947079)

-------------

### **To Reproduce**
1. Put the KryptonHeaderGroup in form
2. Try exclude the component
3. Error message

--------------

### **Expected behavior**
Delete the component without leaving Visual Studio.

--------------
### **Desktop:**

 - Visual Studio (17.9.7)
 - OS: Windows 11 (V23H2)
 - Framework/.NET Version: 4.8
 - Toolkit Nightly Version: 90.24.5.141-alpha

**Comment by giduac** [comment]
@JeanPasquini 

I'm having a look into this. It's the result of ongoing work.
It can take a bit before a change is merged.

**Comment by giduac** [comment]
Hi @JeanPasquini,

I got it fixed so far and will do some more testing tomorrow.
Probably will be in next week's Nightly build.
I'll let you know here when the PR goes in.

**Comment by giduac** [comment]
@Wagnerp 
Please assign to me.
TY!

**Comment by Wagnerp** [comment]
> @Wagnerp Please assign to me. TY!

@giduac 

Now assigned to you

**Comment by JeanPasquini** [comment]
Is this 'Nightly' version available to contribute?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> The KListview class uses the KTreeviewDesigner, this KTreeviewDesigner has it's own action list which does not seem compatible with KListview. I tried an older stable release (80.23.11.321) and there the action list doesn't show in the designer as well.
> 
> The Class header as it is now:
> 
> ```cs
>     [ToolboxItem(true)]
>     [ToolboxBitmap(typeof(ListView))]
>     [DefaultEvent("AfterSelect")]
>     [DefaultProperty("Nodes")]
>     [Designer(typeof(KryptonTreeViewDesigner))]
>     [DesignerCategory(@"code")]
>     [Description(@"A Kryptonised listview. Does not support the `List or Details View` types")]
>     public class KryptonListView : ListView
> ```
> 
> So the KListview action list works when the Designer is changed to:
> 
> ```cs
>     [Designer(typeof(KryptonListViewDesigner))]
> ```
> 
> I looked back in the history and it has been set to the KTreeviewDesigner ever since.
> 
> I there a reason for this or is it a mistake?

Hi @giduac 

It was possibly overlooked.

**Comment by giduac** [comment]
@JeanPasquini 
> Would u like to put a new issue or can I describe here and edit the title?

Thanks, it's ok. 
No need to change things.
I actually found this as well, we'll handle it in this ticket.
If needed the title and topic start can be adjusted later on when all is complete.

**Comment by giduac** [comment]
Hi @JeanPasquini,
[Just posted the PR.](https://github.com/Krypton-Suite/Standard-Toolkit/pull/1480)

**Comment by giduac** [comment]
Hi @JeanPasquini,
The PR has been merged.
If you like you can pull from alpha and see if all works now?

**Comment by JeanPasquini** [comment]
Hi @giduac,
Thanks, I'll check later and post here.

**Comment by JeanPasquini** [comment]
Hi @giduac,
I checked here and it fixed the bug, thanks.

**Comment by giduac** [comment]
Hi @JeanPasquini,
Good to hear, TY.

This fix is also in the latest Nightly build on Nuget.

**Comment by giduac** [comment]
> Hi @JeanPasquini
> 
> If you wish to contribute, all changes _**must**_ be done on the `alpha` branch. Documentation can be found [here](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Contributing.html).

Hi @JeanPasquini,

Did you have a try working on the toolkit already?
If we can help you getting started, please let us know.

**Comment by JeanPasquini** [comment]
Hello @giduac,

I'm developing a software/app using the Krypton Toolkit (https://github.com/JeanPasquini/SpaceCalc), so always when I find a bug or something that I can improve, I'll create an issue or try to fix for you.
