### ISSUE TITLE
[Bug]: Latest alpha does not build in 17.10 or 17.11ps VS

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1485]
- get the latest alpha branch
- (Ensure .Net 9 SDK P4 is installed)
- Open in either VS 17.10 or 17.11p1
- Perform clean build

Keeps getting the following error 

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NETSDK1045	The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download	Krypton.Docking 2022 (net9.0-windows), Krypton.Navigator 2022 (net9.0-windows), Krypton.Ribbon 2022 (net9.0-windows), Krypton.Toolkit 2022 (net9.0-windows), Krypton.Workspace 2022 (net9.0-windows)	C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	166

**Comment by Wagnerp** [comment]
Just tested it, not getting any build errors?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6d7a322f-e0cb-4f79-8f36-6a359bd7f751)

**Comment by Smurf-IV** [comment]
neither did I, until I got everything clean again ???
I'll try running repair on the VS installs.

**Comment by Smurf-IV** [comment]
Ok, Full remove and reinstall of both those versions now has the build working !!!
