### ISSUE TITLE
[Bug]: The Krypton.Navigator does not work when the Windows Form project is only compiled against 'net7.0-windows'

### ISSUE THREAD

**Issue by Kebrite01** [Krypton-Suite/Standard-Toolkit#1501]
The problem is that the Navigator component will not work when used in a Windows Form Project that compiles only against 'net7.0-windows'.   We need this as we are moving our whole solution from being a .Net Framework solution to a .Net Core solution.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/bb2f1e02-7d73-4b7b-a677-5151c6a9896a)

When this is done and you drag the Navigator to the form, the Navigator does not have any default tabs, as it does when the Windows Form project references 'net48' (refer 1st screenshot).  Even though you can add tab pages manually, you cannot click on the tab pages in the VS2022 designed environment.   It's like the Krypton.Navigator is disabled or ResumeLayout() is never called.

The demo 'Windows Form' project code that is supplied through GitHub compiles against 'net48' and the Navigator control is created with two default pages.  You are able to click on each individual page and place whatever other controls on the tabs.

**To Reproduce**
1. Download and compile the GitHub code ('Toolkit Suite 2022 - VS2022')
2. Change the 5 Krypton component projects to only compile with 'net7.0-windows'
3. ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/bb2f1e02-7d73-4b7b-a677-5151c6a9896a)
4. Change the TestForm project to compile with 'net7.0-windows'
5. Compile the whole solution so all the projects are just built using 'net7.0-windows'
6. Add a new form "Form7"
7. Drag the Navigator onto Form7
8. BUG: the Navigator is not created with default tabs and when manually added, the tabs are not selectable.

**Expected behavior**
When dragging a new Navigator onto a Form, I expect it to look like the 2nd screenshot and the tab pages are able to be selected.  Even if the tabs are not automatically added, when they are manually added then they again should be able to be selected on the form.

**Screenshots**
This is what it looks like when the Windows Form project compiled against 'net7.0-windows'
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/cdac52f4-9dda-44c9-97e3-826efccfdb17)

This is what it looks like when the Windows Form project compiled against 'net48'.  As you can see, it is created with 2 tab pages automatically and the pages work as expected.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/6e6ffd56-6163-4ad8-919f-4af385fb9e0d)

**Desktop (please complete the following information):**
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/31477807-a2b7-4f2c-be41-501c66df535b)

 - Framework/.NET Version: 7.0
 - Toolkit Version: used the GitHub code with the 'Toolkit Suite 2022 - VS2022'

**Comment by giduac** [comment]
Hi @Kebrite01,

In the new version ( github branch alpha ) 7.0 will be removed since it has reached End of Life. You might consider migrating to a LTS release.

We advise to use the Nuget packages for "daily" use.

To resolve the error, please follow this instruction:
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html

**Comment by Kebrite01** [comment]
Hi @giduac ,  

First I really appreciate the quick response and if I could just get this Navigator to work, we'd be dedicated and loyal followers of Krypton as the other controls are great!

I have tried all of the below packages and they all do the same thing.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/24f2b708-a202-48f8-bdf6-d95159a9ea48)

Here is the simple Windows app screenshot.   
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/c4f8d857-bb72-4bad-acb4-089b68528fac)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101280803/23643eec-b37b-4a14-861e-323ceec7ef14)

I tested all three Navigator packages by repeating the following steps 3 times.
1. Load a package
2. Verify that it then added the Navigator to the Toolbox
3. Added the navigator to the form
4. It then failed to have any tab pages
5. Removed the Navigator from the form
6. Removed the Package
7. Confirmed the Navigator was no longer in the Toolbox
8. Restarted my VS2002 solution


Also the below instructions are not really a fix as it still implies that you need a .Net Framework **4.81** for it to work.  We need to remove all .Net Framwork from our solution as Microsoft are moving to .Net Core now and the Framework has a limited future.

_"If you are experiencing issues while using the components in the designer, you might need to replace <TargetFramework>net[##Current-Version##]-windows</TargetFramework> with <TargetFrameworks>**net481**;net[##Current-Version##]-windows</TargetFrameworks> in your project configuration files._"


**Has anyone got it to work when not specifying "481" in the target framework?**

Thanks again for any assistance!

**Comment by giduac** [comment]
No the designer part must net48.

Here's more background on this:
https://github.com/Krypton-Suite/Standard-Toolkit/discussions/684

**Comment by Kebrite01** [comment]
@giduac 

Thanks for the effort in making me understand.   So even though our project may be compiled with .Net Core 7.0 in mind, we still need to have "net48;net7.0-windows" in the target framework to use it in the designer.

You are a legend!!!!

**Comment by giduac** [comment]
Yes. 48 is needed for designing interfaces.
At runtime all works with higher versions and without 48.
All components can be "manipulated" from code at runtime using .NET > 48...

**Comment by giduac** [comment]
If this answers your question, please close the ticket.
Thank you.
