### ISSUE TITLE
[Bug]: `Docking Perstence` demo application is broken with recent changes made in Canary and nughtly builds

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1502]
**Describe the bug**
whilst investigating #1381

**To Reproduce**
1. Load nuget version of `Docking Persistence 2022`
2. Switch to latest Canary (Or nighlty) builds
3. Attempt to run app

**Expected behavior**
Stuff to still work

**Screenshots**
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/05b9fc35-7526-4f68-87d0-b92f19260424)

**Comment by Smurf-IV** [comment]
@giduac - Can you look into this, as I feel it's something to do with all the changes being made for the `nullable`  warnings fixes

**Comment by giduac** [comment]
@Smurf-IV,
OK, assign to me please..

**Comment by Smurf-IV** [comment]
@giduac.. Ok, This threw me for a moment...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/dda6e5c4-93bd-4907-8d98-7d929d9cd177)
Can you see what the problem is ?

**Comment by Smurf-IV** [comment]
Back to the OP problem..
When initialising, there is no "ActivePage" !!

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6423fddd-aea7-4a31-bf54-04f5946147ee)

**Comment by giduac** [comment]
Hi @Smurf-IV,
PR Posted 1504

**Comment by Smurf-IV** [comment]
> @giduac.. Ok, This threw me for a moment...
> 
> ![image](https://private-user-images.githubusercontent.com/2418812/335791750-dda6e5c4-93bd-4907-8d98-7d929d9cd177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTM2NTcsIm5iZiI6MTcxNzMxMzM1NywicGF0aCI6Ii8yNDE4ODEyLzMzNTc5MTc1MC1kZGE2ZTVjNC05M2JkLTQ5MDctOGQ5OC03ZDkyOWQ5Y2QxNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMDcyOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRhMGQ2MTE5MWIwMTMwZmY0M2Y4MzkzODRkN2FlYjExMDA4Y2ZlM2QwMDdmMzE1ZmRjZjU0NWUyZTk5NjNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gzHkxQFYozWqL_Pt7i96ii6W4JaPLWCrNBPDxL07veo) Can you see what the problem is ?

You didn;t fix this in your PR,.

**Comment by Smurf-IV** [comment]
@giduac Please run "All" the example demo code for Workspace, after you have fixed the issue(s) in a debugger.
Thanks

**Comment by Smurf-IV** [comment]
@giduac This is still broken:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/8d555501-9b3c-4edf-a5b4-cbe38746cb8b)

**Comment by giduac** [comment]
Hi @Smurf-IV ,
Corrected in PR 1512: https://github.com/Krypton-Suite/Standard-Toolkit/pull/1512

**Comment by giduac** [comment]
Hi @Smurf-IV,

I assume this can be closed ?
