### ISSUE TITLE
[Other Issues]: Revise Theme Selector Controls

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1507]
Revise all ~three~ four Theme Selector controls:
1. `KryptonThemeComboBox`
2. `KryptonThemeListBox`
3. `KryptonRibbonGroupThemeComboBox`

Changes to be made:
- Bring the code base inline,
- Remove redundant code,
- Replace palette assignments via PaletteMode values themes dictionary data.
- Replace global: `public const int GLOBAL_DEFAULT_THEME_INDEX` with `GLOBAL_DEFAULT_PALETTE_MODE`.
- PaletteMode will only serve as a unique identifier further on.
- Hookup the controls to the KryptonManager.GlobalPaletteChanged event so they react to external theme changes.

This is in continuation of issue 1328:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/1328

**Removed properties:**
- KryptonManager Manager: not needed to be exposed publicly, internal var will suffice, the property has been removed.
- ThemeSelectedIndex: redundant since indexes have been removed.
- ReportSelectedThemeIndex: redundant since indexes have been removed.
- SynchronizeDropDownWidth: 
    - When maximum size is changed the property isn't updated and needs a refresh.
    - Also on a CBB that is anchored left and/or right the size might vary as well and needs an update.
    - Default the control DropDownwidth has the same width as the control itself.
    - This property would better be off in the KComboBox class as a new feature, considering the above when implementing.

**Comment by giduac** [comment]
Hi @Wagnerp,
Please assign to me, TY.

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> Please assign to me, TY.

Hi @giduac I have now assigned it to you

**Comment by giduac** [comment]
Hi @Smurf-IV & @Wagnerp,

Didn't know about `KryptonThemeBrowser`.
I guess that'll be looked into as well in this ticket.

Are there more Theme Switching controls out there besides the four mentioned here ?

**Comment by giduac** [comment]
@tobitege
You might keep an eye on this, could be interesting for you.
First PR on this: https://github.com/Krypton-Suite/Standard-Toolkit/pull/1511

**Comment by tobitege** [comment]
You're doing awesome work, thanks so much!!

**Comment by giduac** [comment]
Hi @tobitege,

PR 1511 has been merged into alpha.
If you have time to give KThemeCBB a spin and let us know your findings that would be most appreciated?

**Comment by giduac** [comment]
Hi @Wagnerp & @Smurf-IV 

One of the last steps is to remove the ReportSelectedThemeIndex from the theme switcher controls.
A scan through the source showed that a couple of the toast forms use this property.

Can we agree that the toast forms will not be touched for 1 or 2 days so I have the time to update everything and post the resulting PR?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp & @Smurf-IV
> 
> One of the last steps is to remove the ReportSelectedThemeIndex from the theme switcher controls. A scan through the source showed that a couple of the toast forms use this property.
> 
> Can we agree that the toast forms will not be touched for 1 or 2 days so I have the time to update everything and post the resulting PR?

Hi @giduac 

Yes that's fine, I'll be working on #619 anyway.

**Comment by giduac** [comment]
OK @Wagnerp & @Smurf-IV,

Than I'll finish 1507
