### ISSUE TITLE
[Bug]: DOT NET 8, Visual Studio 2022 ( 17.10.1 ) Cannot add or drag items to KryptonGroup or KryptonGroupBox in WinForms Designer

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1509]
**Describe the bug**
Cannot add items to KryptonGroupBox in WinForms Designer

**To Reproduce**
1. Create new Project
2. Add Form
3. Add KryptonGroupBox
4. Try to add any control to groupbox

**Expected behavior**
Expect to be able to add new or drag existing control(s) onto a Group / Groupbox.

**Screenshots**
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/84494183/a755b90d-4495-49fd-a387-2aaf5f57fb61)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio: 17.10.1 ( 2022 )
 - Framework/.NET Version: 8
 - Toolkit Version: 80.24.3.64

**Additional context**
Works as expected when using .NET 4.8...
Issues occurs on both New & Migrated projects when using .NET 8
[WinFormsApp1.zip](https://github.com/user-attachments/files/15548272/WinFormsApp1.zip)

**Comment by giduac** [comment]
Hi @MattH-Work,

Please try this:
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html

Additional background info:
https://github.com/Krypton-Suite/Standard-Toolkit/discussions/684

All the nifty stuff in the IDE designer only works with net48 included in the target frameworks.

**Comment by giduac** [comment]
@Wagnerp,

Please assign to me.
Thanks.

**Comment by Wagnerp** [comment]
@giduac Done

**Comment by MattH-Work** [comment]
> Hi @MattH-Work,
> 
> Please try this: https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html
> 
> Additional background info: #684
> 
> All the nifty stuff in the IDE designer only works with net48 included in the target frameworks.

Tried it, now getting the following error
" Could not resolve mscorlib for target framework '.NETFramework,Version=v4.8.1'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted. "

**Comment by giduac** [comment]
@MattH-Work 

A simple program sample please ?

**Comment by giduac** [comment]
Hi @MattH-Work,

First:
Your .vbproj file which should (and possibly already does) contain:
```xml
<TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
```

Second:
You are missing an assembly reference in the project, to mscorlib.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/109038dc-2e09-47f0-b335-18a4f7ab3d2d)

And then enter mscorlib in the search box and check it:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/1126a8d1-3062-4d78-8b57-cf0e28252ca3)

**Comment by MattH-Work** [comment]
Worked like a charm

I had originally just added ' **_net48_** ' to the existing' TargetFramework>**_net48_**;net8.0-windows</TargetFramework '

I hadn't registered that the two TargetFramework references are now plural 
TargetFrameworks>net48;net8.0-windows</TargetFrameworks

Secondily, I tried adding a reference to mscorlib but the ' Add > Assembly Reference ' was missing, hence not being able to self fix the issue
I needed to remove my existing form ( blank form, part of my template, not an issue ), add the reference to mscorlib then add a new form back in

Cheers

**Comment by giduac** [comment]
Nice @MattH-Work !

Looks like u are a happy customer :)

If so please close the ticket, thanks.

**Comment by MattH-Work** [comment]
Clsede, thanks
