### ISSUE TITLE
[Question]: Where does "Krypton.Toolkit.dll" get placed whe I build my project ( .NET8, VB 2022 )

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1510]
When building a project in VB 2019, .Net 4.8, 'Krypton.Toolkit.dll' automatically gets copied into the same folder as my DLL / EXE ( usually in my case, in the Debug folder )

Having just upgraded to VB20 22, .NET 8, there is no sign of the 'Krypton.Toolkit.dll' which causes my program to fail

Any suggestions

Cheers

Matt

**Comment by Smurf-IV** [comment]
I assume that a vbproj file layout has similar thing as csproj...
In a csproj the following can be added to determine the location of the output `root` directory
```
    <PropertyGroup>
        <OutputPath>..\..\..\Binaries\Krypton Demos\$(Configuration)\</OutputPath>
    </PropertyGroup>
```
Then the if there is no override for the framework moniker it will have the following layout:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/77ba7760-26cc-4e06-a0fa-478a2c26f7dc)
