### ISSUE TITLE
[Bug]: UpdateEnabled

### ISSUE THREAD

**Issue by almendieta** [Krypton-Suite/Standard-Toolkit#1513]
**Describe the bug**
error appears on load form, to krypton navigator. It seems it was provided an error mgr. Error showed on trying to enable a button from buttonspecsnavigator. If I try to enable it on form_load ( btnAnclar.Enabled = True) , errow will show up immediately. BUT if I try:
            `btnAnclar.Enabled = Krypton.Toolkit.ButtonEnabled.True`
Then control will open normally.

**To Reproduce**
1. Go to 'UpdateEnabled - ButtonSpecView'
2. Click on 'bug on form_load'
3. Scroll down to ' '

**Expected behavior**
Control loads plainly without any dialogs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 64b]
 - Version: [e.g. 19.0.42 631]
 - Framework/.NET Version: [4.8.1] 
 - Toolkit Version: [90.24.4.113]

![2024-06-09 13_57_45-Window](https://github.com/Krypton-Suite/Standard-Toolkit/assets/11827218/c22798f2-8177-4bb2-a301-def6c7304175)

**Comment by Wagnerp** [comment]
Hi @almendieta 

Thanks for posting. Would you mind attaching a sample for further investigation?

**Comment by giduac** [comment]
@Wagnerp,

Please assign to me.
Ty.

**Comment by giduac** [comment]
Hi @almendieta,

The enabled property for a ButtonSpec button is not a `boolean` type, but of the type `ButtonEnabled`. Like you already found.
Please use that type for ButtonSpec types.

If this does not solve your problem, please provide a sample program that reproduces the problem clearly.

Otherwise you can close this ticket, thank you.

**Comment by giduac** [comment]
Hi @Wagnerp,

No response from @almendieta so far.
Please close, if needed we'll reopen it.
ty.
