### ISSUE TITLE
[Bug]: Theme Office 2010 Black Dark Mode causes a crash.

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1516]
**Describe the bug**
Theme Office2010 Black Dark Mode causes a crash.
Only happens in combination with the Ribbon.

**To Reproduce**
1. Start TestForm from VStudio in debug mode
2. Click: Ribbon
3. Select theme: Office 2010 Black Dark Mode
4. Press ALT (which invokes the Ribbon Key Tips)

**Expected behavior**
N/A

**Screenshots**
https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/49413d8d-b3b0-468a-a155-2ac177649173

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Alpha branch, could well be in older versions too and might be also a needed fix for V85
 - Framework/.NET 48
 - alpha branch

**Additional context**
N/A.

https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/49413d8d-b3b0-468a-a155-2ac177649173

**Comment by giduac** [comment]
Hi @Wagnerp,

This is an error in the theme itself, you'll see it when it crashes in a VStudio debug session.
Probably a quick fix.

Can you pick this one up, please?
Thanks.

**Comment by Wagnerp** [comment]
Hi @giduac 

Yes, it's a easy fix. Going to fix for v85 as well as v90.

**Comment by Wagnerp** [comment]
@giduac Fixed, but the tooltip back colours for MS365 themes need some work...

![1516](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/801da0f8-c67c-458e-b0e6-aaae1f010639)

**Comment by giduac** [comment]
Nice
