### ISSUE TITLE
[Other Issues]: Check ThemeManager & KryptonManager for the use of hard coded theme indexes

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1522]
**Breaking Changes Overview**
- Replaced: index based theme change functionality with `PaletteMode` identifier based access.
- Removed: the `ThemeIndex` property
- Removed: `ReturnPaletteMode()`
- Removed: All `Propagate*` methods.
- Removed: `RibbonThemeManager`
- Removed: `SetThemeIndex()`
- Removed: `GetThemeIndex()`
- Modified return value to non-nullable: `GetThemeManagerMode()`
- Modified: `public static string ReturnPaletteModeAsString(PaletteMode paletteMode, KryptonManager? manager)` to only use the `manager` parameter since there already is an overloaded method that uses `PaletteMode` as a single parameter.
- Added property: `DefaultGlobalPalette` which returns the System Default Global Palette.
- Make method public: `private static void ApplyTheme(PaletteMode mode, KryptonManager manager)`. As this is inline with switching themes via `PaletteMode` identifiers.

**Comment by giduac** [comment]
@Wagnerp ,

Please assign to me.
ty.

**Comment by Wagnerp** [comment]
@giduac Done

**Comment by giduac** [comment]
Hi @Smurf-IV, @Wagnerp 

Questions based on this source version:
https://github.com/giduac/Standard-Toolkit/blob/1522-Check-ThemeManager-KryptonManager-for-hard-coded-theme-indexes/Source/Krypton%20Components/Krypton.Toolkit/Rendering/ThemeManager.cs

Some questions about the ThemeManager:
1. Line 50, ReturnPaletteMode().
Is this method necessary?
2. Line 29 , ThemeIndex property
This, imo, needs to be replaced with a PaletteMode based property to avoid index problems like those solved earlier?
3. Line 164 & 187 (one of the propagate methods)
What are the propagate methods used for?

4. RibbonThemeManager
Source:
https://github.com/giduac/Standard-Toolkit/blob/1522-Check-ThemeManager-KryptonManager-for-hard-coded-theme-indexes/Source/Krypton%20Components/Krypton.Ribbon/Palette/RibbonThemeManager.cs

While working on 1507 I found that in the KRibbonGroupThemeCBB a different ThemeManager was used. I reverted this to using the same code as the other two theme selectors use.

Imo this RibbonThemeManager is redundant (theme changes from there are actually forwarded to the regular TManager) and there are no other occurrences in the code that that use this component.

I'd like to suggest to remove it and handle everything through ThemeManager as single point.

**Comment by Smurf-IV** [comment]
1) No idea
2) Yes and the `enum` not an `int`
3) ??
4) Good idea !

**Comment by giduac** [comment]
@Wagnerp 
Can you please give your input on the questions above?
thanks.

**Comment by Wagnerp** [comment]
1. It was a test, so can be removed
2. Yes
3. I think it was test code, so can be removed
4. Yes, no need for duplication
