### ISSUE TITLE
[Feature Request/Bug]: Tracking colours need reviewing

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1528]
Following discussions from #619, the tracking colours may need reviewing.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

Progress...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6bc00803-8e77-4d6d-9b11-5baa6fba8c96)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

For v90, I'm planning to completely redo the dark silver themes using these palettes

![shades-x11-color-silver-c0c0c0-hex-31578-colorswall](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/dbc96116-019f-4f8e-984e-17349dc08b6d)

or

![5 _Dark_Gray_Color_Palette_Color_Palette_with_Night_Hex_111111_Eerie_Black_Hex_232323_Jet_Hex_343434_Outer_Space_Hex_464646_Davy_S_Gray_Hex_575757_Color_Palette_with_Hex_Codes](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/870dc6b8-0b11-4594-b7e5-c50b8a037398)

or

![71706E59585641403F2B2A29171614000000](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/008dc456-0f90-4cb1-b56c-6aeffe0ca6a5)

Thoughts?

**Comment by Smurf-IV** [comment]
Not sure, Just a note, The existing dark themes have messed up the tracking of the Hover over drop button on ComboBox's

**Comment by Wagnerp** [comment]
> Not sure, Just a note, The existing dark themes have messed up the tracking of the Hover over drop button on ComboBox's

Hi @Smurf-IV 

That might need to be a separate bug, as the drop-down arrow thing is not legible on other themes as well! Do we know if this is controlled by a colour, or is it a image?

**Comment by giduac** [comment]
> Reference in

That's a lot of work at the moment
If it's only the drop button my choice would be to fix it.

We have lot of work already which we need to get a grip on imo.

**Comment by Wagnerp** [comment]
> > Reference in
> 
> That's a lot of work at the moment If it's only the drop button my choice would be to fix it.
> 
> We have lot of work already which we need to get a grip on imo.

I'll create a new bug report.

**Comment by giduac** [comment]
Also I think that these are pretty good.
Creating a copy or new one with those new colors is also an option.

Another thought: when using a new version devs are not confronted with a changed theme (a bit of a breaking change) which can be undesirable...

**Comment by Wagnerp** [comment]
> Also I think that these are pretty good. Creating a copy or new one with those new colors is also an option.
> 
> Another thought: when using a new version devs are not confronted with a changed theme (a bit of a breaking change) which can be undesirable...

The problem is that the current iteration is too 'blue' in my opinion.

**Comment by giduac** [comment]
> > Also I think that these are pretty good. Creating a copy or new one with those new colors is also an option.
> > Another thought: when using a new version devs are not confronted with a changed theme (a bit of a breaking change) which can be undesirable...
> 
> The problem is that the current iteration is too 'blue' in my opinion.

Well even if there are a lot of blue themes it's still a user's choice to use them or not.

To catch up with current trends I would go for a set of new themes that are minimalistic and approach Material Design as much as possible. So Winforms apps can stay on par with other strong UI trends.

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV 

Adding to the above my view on the current state of KT:
- Currently there are more than 60 bugs open, several for months or longer.
- There are a lot of tickets addressing (let's call it incompleteness in) themes.
- Capacity wise we are short of man power.
- That all leaves no room for new features atm.

If we don't get a grip on the current state and keep adding new features to the kit which in turn cause more work it will only get out of control further.

My thoughts are to first stop adding new stuff for now and finish what there is.
Draw up rules by which we work and more important react to situations.

For example introduce a max open bug count 5 or 10. If that number is reached more capacity will be directed to solving them.

Introduction of new features only via a plan that is draw up by us and agreed upon by all, so we:
- know what to work on
- what the outcome will be
- we can measure how far a new feature has progressed
- when done, it it does what what it should.

**Comment by Wagnerp** [comment]
Hi @giduac 

The alternate silver mode themes can be tacked on to the v100 milestone. However to avoid losing the colour swatches, a new feature request will need to be opened.
