### ISSUE TITLE
[Question]: GroupBoxes and Tabs

### ISSUE THREAD

**Issue by PontusLindberg** [Krypton-Suite/Standard-Toolkit#1541]
I have a problem with groupboxes and tab pages with the latest nuget package. I run .net 8 and VS 2022.

I start clean with a new Windows Forms project in VS and add a Krypton group box to a form. So far so good. But after that, it's not possible to add any components to the groupbox (drag & drop).

For older projects upgraded from .net Framework (with older Krypton version), controls inside the groupbox can not be selected/edited.

Is this a known issue? Do you need more info from me?

Kind regards,  Pontus

**Comment by giduac** [comment]
Hi @Wagnerp,

Question has been answered, please close the call.
TY.

**Comment by PontusLindberg** [comment]
Well, this solution is unfortunately not acceptable to us. It's important for us to know if/when this is fixed. If you have any info, please share.

**Comment by Wagnerp** [comment]
Hi @PontusLindberg 

Can you please provide screenshots of what's happening? It is a known issue that MS has broken the designer since .NET Core. Unfortunately we can't do anything until MS fixes the designer for .NET.

**Comment by PontusLindberg** [comment]
Thankyou for answering so quickly. I will do it first thing tmw.

**Comment by Wagnerp** [comment]
@Smurf-IV Is there any way to debug this?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/d56b1e9e-a68b-43df-ab0b-2ba533ecde7b)

**Comment by PontusLindberg** [comment]
This is pretty much it, the last two posts from you. Also, when we upgrade from .net 4.8 to .net 8, all controls within a groupbox can't be selected in designer mode. Runtime is fine, except scaling. There is a similar issue with tab pages that I can explain tmw.

**Comment by Wagnerp** [comment]
Hi @PontusLindberg 

You do need to add `net481` to `TargetFrameworks` in your csproj/vbproj files in order to regain control of the designer. We can't fix this in the toolkit, as it is a bug within .NET itself.

**Comment by PontusLindberg** [comment]
We can't do that I'm afraid. We have loads of other dependencies that stop working. Ok, I get it, nothing you can do. 

I really appreciate the feedback, thankyou!

**Comment by Wagnerp** [comment]
> We can't do that I'm afraid. We have loads of other dependencies that stop working. Ok, I get it, nothing you can do.
> 
> I really appreciate the feedback, thankyou!

Really sorry about this, but we're all waiting on MS to fix it.

**Comment by Wagnerp** [comment]
Hi @PontusLindberg 

Just wondering, is it possible to give a list of all your dependencies to see if there's a workaround?

**Comment by Smurf-IV** [comment]
> We can't do that I'm afraid. We have loads of other dependencies that stop working. Ok, 

FYI: This is **only** to allow the designer to so it's thing, 
- You still build as .net 6/7/etc 
- and nugets will still work as they pull in the correct versions.

**Comment by PontusLindberg** [comment]
However, like you say, it works in runtime. 

The issue has been there for I long time if I get it right. So we can't expect this to be fixed soon?

We have two options I guess. Either edit the designer file manually, or do UI development in a 4.8 environment and copy the designer file into the 8 environment (and adjust).

**Comment by Wagnerp** [comment]
> > Hi @PontusLindberg
> > Just wondering, is it possible to give a list of all your dependencies to see if there's a workaround?
> 
> Hello! That's very kind of you, but it's a lot of them. We are creating add-in dlls to run in another (big) software.

Hi @PontusLindberg 

If some are in-house, then you can change the `TargetFrameworks` configuration like in the article described above for those projects.

**Comment by giduac** [comment]
> However, like you say, it works in runtime.
> 
> The issue has been there for I long time if I get it right. So we can't expect this to be fixed soon?
> 
> We have two options I guess. Either edit the designer file manually, or do UI development in a 4.8 environment and copy the designer file into the 8 environment (and adjust).

A possible approach:

You might setup the rough interface in the designer. 
All controls can be added to a form on .Net > 48.
Do all the designing you can do there and the rest in code.

**Comment by giduac** [comment]
@Wagnerp,

Please close as there's no follow-up from @PontusLindberg.
If needed the ticket can be reopened.
