### ISSUE TITLE
[Bug]: KComboBox DropDown arrow is illegible in certain themes 

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1548]
As per discussion in #1528, the KComboBox DropDown arrow is illegible in certain themes. It is not identified yet if these are controlled by a colour or if they are an image.

**Comment by Wagnerp** [comment]
**Note:** Look at `DropButton()` in `KryptonComboBox` for clues...

**Comment by Wagnerp** [comment]
![image](https://github.com/user-attachments/assets/22e6ef34-df73-4072-acce-842dc29b7854)

**Comment by Smurf-IV** [comment]
@Wagnerp 
Please see related:
- #1211
- #1212
As such changing milestone to V85
