### ISSUE TITLE
[Question]: Ribbon bar does not integrate correctly with form when maximized, how do I restore previous versions behavior?

### ISSUE THREAD

**Issue by mbagattini** [Krypton-Suite/Standard-Toolkit#1549]
I'm having this issue after updating to version 80 (specifically, 80.24.3.64).

As you can see from the snippet, the ribbon bar stops being integrated in the form header once the form is maximized. It returns integrated if I resize the window. The form title is displayed twice and the top area uses twice the required space.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/941612/dea7b041-deaa-45a3-b30f-3a9412be3376)

As a side issue, also the colors changed after the update and now the top of my form is white.

Any help would be greatly appreciated.

**Comment by giduac** [comment]
Hi @mbagattini,

Can you please post a sample that reproduces the problem?

**Comment by mbagattini** [comment]
I'll try to. 

Creating a sample from scratch with this library is a bit difficult at the moment, since the design time support is limited after the switch to .NET, I'm having troubles designing new controls (some options are just not available anymore, some operations crash my VS entirely). 

My hope was that this is a known, no-brainer issue that I could fix by enabling some property, but it looks like it's not that easy.

**Comment by giduac** [comment]
@mbagattini 

If you create a sample and apply this info to the csproj file you can design from within VStudio:
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html

**Comment by mbagattini** [comment]
Thank you for your suggestion. I tried that before (it was suggested in another thread) but, unfortunately, the application I'm working on stopped compiling, emitting a plethora of errors, like:

- A MessageBox saying that "Could not retrieve project assembly output path. Parameter name: hierarchy"
- A golden bar saying "The project 'MyProjectName' ran into a problem during the last operation: The value of the 'TargetFrameworkMoniker' and 'NuGetTargetMoniker' properties in the 'Debug|x64' configuration are both empty. This configuration will not contribute to NuGet restore, which may result in restore and build errors. You may need to reload the solution after fixing the problem. 
- A golden bar saying "Visual Studio ran into an unexpected problem with one or more projects. You may need to reload affected projects or the solution to prevent further problems."

Anyway, I'm digressing. I'll see if I can make a sample in the coming days.

**Comment by giduac** [comment]
HI @mbagattini,

I've had a look at it but can't find how you got the form title twice in there.
You could inspect the form designer source for that string. That might help.

Try to replicate the problem in a new program if you can using the earlier info we gave you.

**Comment by giduac** [comment]
@Wagnerp 
Please assign to me ty.

**Comment by mbagattini** [comment]
@giduac I've been able to get around this behavior by placing the ribbon inside a panel, that way I have a less disrupted UI. I'll try to save a bit of time in the coming days to make a small sample, sorry for not being able to make it today but I'm swamped. Thank you again in the meantime.

**Comment by mbagattini** [comment]
> @giduac I think this has been fixed in v90 & maybe v85?

I'm not super into this kind of stuff, does v90 run in a .NET 6 context? 'Cause that version also fixes an issue we found with v80 and navigator not supporting a certain configuration (top of my mind, something Outlook style; I'm not currently on my work laptop so I can't check more precisely).

**Comment by giduac** [comment]
V90 does have have the same problem and is something we cant fix.
Here is more info on why this doesn't work.
https://github.com/Krypton-Suite/Standard-Toolkit/discussions/684

**Comment by giduac** [comment]
> @giduac I've been able to get around this behavior by placing the ribbon inside a panel, that way I have a less disrupted UI. I'll try to save a bit of time in the coming days to make a small sample, sorry for not being able to make it today but I'm swamped. Thank you again in the meantime.

Putting it in a panel wont solve this. See the last message.
It's probably the problem you have, another place to look at...

**Comment by Smurf-IV** [comment]
FYI
> A golden bar saying "Visual Studio ran into an unexpected problem with one or more projects. You may need to reload affected projects or the solution to prevent further problems."

That's what VS does when you edit the f*.vcsproj file directly and it is currently in a cache.
Reload or Close and reopen VS will s most of those bars out

**Comment by giduac** [comment]
Hi @mbagattini,

Since you are using the Ribbon in a panel the overlay that "covers" the title bar will not work as expected when using a KForm.
Please close the ticket if your questions are answered, ty.

**Comment by mbagattini** [comment]
I have created a project from scratch, .NET 6 with latest stable version of Krypton. On my machine this reproduces the same issue described above, when maximized:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/941612/69714d0a-da1d-422b-9461-1275946d62b1)

The ribbon doesn't get integrated with the window's chrome (in the following image, VS design window in background showing the custom chrome while the running app uses the default Windows chrome). Source is attached.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/941612/fc92f5a8-45c2-432b-9962-1e8bc3dd0c67)

[KryptonRibbonTest.zip](https://github.com/user-attachments/files/15967261/KryptonRibbonTest.zip)

Thanks for your patience and time.

**Comment by giduac** [comment]
Hi @mbagattini ,

The sample you provided works correct and does not show the error....

**Comment by mbagattini** [comment]
So you're not seeing the same screens I posted above? Have to be something on my computer then. Any idea about what it can be?

**Comment by giduac** [comment]
I see the second picture
In your proj the QATLocation is set to above which puts the ribbon over the title bar.

**Comment by mbagattini** [comment]
May I ask you for a screenshot of what you see with the window maximized? Specifically the top-left area

**Comment by giduac** [comment]
When maximized the form title is shown twice.
When using 90.24.6.176-beta it works as it should.

Please file a bug and refer to this ticket which you can close.

Include all the findings in the description of the bug ticket, ty.

**Comment by mbagattini** [comment]
Created a bug at #1572 as requested, closing this question.
