### ISSUE TITLE
[Bug]: Launching TestForms -> Controls Test results in Exception message box

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1556]
Using today's alpha:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/861a5dc1-4c89-4517-9f31-aef65e29a5ce)

@giduac
Appears to be theme selection related

**Comment by Smurf-IV** [comment]
And when launching Calendar:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/131b7b32-905d-40ab-8bde-ec1c0fd67412)

**Comment by giduac** [comment]
Hi @Wagnerp,

Please assign to me, ty.

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> Please assign to me, ty.

Hi @giduac 

Done

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 

These messages do not happen consistently. 
I had it one time yesterday. Then tried another 10 times or so with problems.

Seems that somewhere a setting gets changed that triggers a debugtools warning/message...
That gets triggered then when a theme changed  is performed....

Next to that: 
- Outlookgrid.cs has problems
- Fade form hangs the program when the form is closed

**Comment by giduac** [comment]
Hi @Wagnerp & @Smurf-IV,

A question about form fading.

Which was the reason to add the `ModernFadeFormIn` and `ModernFadeFormOut` methods to `KryptonFormFadeController`?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp & @Smurf-IV,
> 
> A question about form fading.
> 
> Which was the reason to add the `ModernFadeFormIn` and `ModernFadeFormOut` methods to `KryptonFormFadeController`?

Hi @giduac 

They were designed specifically to work with .NET. Problem with fading though is there is a bug where the KForm 'pops' in at the very last second.

**Comment by giduac** [comment]
@Wagnerp 
Ok, thanks.

The modern fadeout method doesn't work since the loop is infinite. Making all programs using this and .NET hang on fade out.
The < .NET and this version  also has some flickering when fading.

I'll make the FadeForm with some test controls to show a more fine grained fade in and out which is more fluent. But that will always be a bit speculative since not all computers are the same and also the load on a system can influence that.

With the findings of that FadeForm we can then adjust those methods and maybe the .NET Framework ones also.

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 

I'd like you to test the updated FadeForm and play with the added controls to see what you think are good settings so we can update the methods in the KFormFadeController.

See the above post.

**Comment by Smurf-IV** [comment]
Can the "FadeForm" be moved to the extended toolkit, as it appears to have never "Really" worked due to the number of bugs.
And, also move the bugs as well ?

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp,

If someone get these Debug messages (as those are not replicable) make sure to hit break in the debugger so we can see where these come from.

**Comment by giduac** [comment]
Hi @Wagnerp,
Seems that this error has gone.
When reappears this can be reopened.
Please close ty.
