### ISSUE TITLE
[Bug]: Disbled Button Text in Ribbons is not visible in some themes

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1564]
Using todays alpha branches and the Ribbon Controls app (.net core)

Expected:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/6682c230-77f1-4267-b45a-7ce4e7680b30)

Actual:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1e8fa755-f039-4a32-a4f1-de614c508a56)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/bbab6c68-9af6-4b4a-83c8-77a86f54c3be)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/8a288274-0c89-41fa-b692-67c861e5b347)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/fa1b7cf8-bcc9-4b2b-8b43-65bbb92497a9)

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e0065ed0-9728-4abd-a123-b3d6b06b3c0f)

And it goes on ....

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

As the 'enabled' text colour in Sparkle themes is white, it means that the inverted colour is black. Thoughts?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/06bbda4c-cbf0-4da8-9b83-902490050f23)

**Comment by giduac** [comment]
@Wagnerp,

Something not so black... 
Something not so white...

**Comment by Wagnerp** [comment]
> @Wagnerp,
> 
> Something not so black... Something not so white...

@giduac 

Personally, I think they should be taken back to the OG 4.x colours...

![Screenshot 2024-07-11 073159](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/1324da48-c850-4fe8-a9c8-66faa54ddfa1)

![Screenshot 2024-07-11 073247](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/8dd3edae-4902-42a8-bdce-bf88f9e272c4)

**Comment by giduac** [comment]
@Wagnerp 
Keep it consistent with other color combinations that are already in use for enabled/disabled states as far as that can be.

**Comment by Wagnerp** [comment]
What do you think @Smurf-IV?
