### ISSUE TITLE
[Bug]: Ribbon backcolours to match theme panel colour(s)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1565]
Using today's alpha and the Ribbon Controls demo (.net core)

Expected:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7b3c3965-9807-4e4b-a05c-6abc28414d21)

Actual:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/912d6ca5-5a8b-4c89-ab6f-4a90c86d1af3)

etc.

**Comment by Wagnerp** [comment]
This will likely fix #1564

**Comment by Wagnerp** [comment]
Appears to be controlled by

```cs
Color.FromArgb(190, 190, 190), // RibbonGroupsArea1
            Color.FromArgb(210, 210, 210), // RibbonGroupsArea2
            Color.FromArgb(213, 219, 231), // RibbonGroupsArea3
            Color.FromArgb(249, 249, 249), // RibbonGroupsArea4
            Color.FromArgb(243, 245, 249), // RibbonGroupsArea5
```

**Comment by Wagnerp** [comment]
Ok, so the back colour is controlled by these values

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/cb0b883d-2e27-44b7-9207-aa7f94dbb470)

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV,

The Visual Studio and 365 varieties have the same background color as the Panel.
But for my taste it also looks good when the Ribbon contrasts against the Panel. 
I think that should be the choice of the user and should be left as it is...

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV,

The Visual Studio and 365 varieties have the same background color as the Panel.
But for my taste it also looks good when the Ribbon contrasts against the Panel.
I think that should be the choice of the user and be left as it is...

**Comment by giduac** [comment]
Reporter is not responding.
Ticket will be closed, if needed it can be reopened.

**Comment by Smurf-IV** [comment]
> Reporter is not responding. Ticket will be closed, if needed it can be reopened.

Hey, I was on holiday! 
3 days - hmph.

**Comment by giduac** [comment]
@I.ve asked a couple of weeks ago as well ...

**Comment by giduac** [comment]
https://discord.com/channels/620577714889424916/784104286074175539/1278935160254894174
