### ISSUE TITLE
[Bug]: KCheckedListbox & KListBox do not respect 'disabled' back colours

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1573]
While investigating #371, it was found that  KCheckedListbox & KListBox (and possibly other controls) do not respect 'disabled' back colours, opting to use 'normal' colours.

**Comment by Smurf-IV** [comment]
@Wagnerp Curious, because when set directly it does use the colour from the designer:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c1e4ad82-71c4-4969-9732-f31e1c94af00)

I'll see what else I can find

**Comment by Smurf-IV** [comment]
Currently: I think that the minimal code change to allow the colours to works as expected, will be to change these to be the defaults:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1db4cb3a-ffdc-4c97-b009-938939bdb00a)

I've got some testing to do !

**Comment by Smurf-IV** [comment]
BackStyle == Panel is not right, as this is an "Input Control"

**Comment by Wagnerp** [comment]
> BackStyle == Panel is not right, as this is an "Input Control"

Is this the same for other affected controls?

**Comment by Smurf-IV** [comment]
> Is this the same for other affected controls?

Yes (And no). e.g. for a textBox: There is no `BackStyle`, But the whole control is done via:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/a6bd4d7f-1b4b-4634-8575-b693674471fd)
AND, for a textBox, even tho it has "AlwaysActive" set, it does not _override_ the display state when disabled (Like it does in the ListBox!)

The Minefield continues.

**Comment by Smurf-IV** [comment]
> Is this the same for other affected controls?

Turns out:
A number of controls being modified will be in the PR

**Comment by Smurf-IV** [comment]
Fixed...
Before:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b4948aea-be4f-4a8c-beb2-192cd83d2a47)


After:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/49baa1a0-fc03-41c1-a19a-fac85eff9fc7)


Note: ListView(s) will be done in the linked bug
