### ISSUE TITLE
[Bug]: Changing to certain modes in KryptonNavigator can cause a System.NullReferenceException

### ISSUE THREAD

**Issue by Legingo** [Krypton-Suite/Standard-Toolkit#1580]
**Describe the bug**
  Using KryptonNavigator  and changing to either mode "Stack - CheckButton - HeaderGroup"  or "Outlook - Full"  will cause a
  NullReferenceException.

**To Reproduce**

1. Go to Krypton\Standard-Toolkit-Demos\Source\Krypton Navigator Examples\Navigator Modes\Navigator Modes 2022.csproj
2. Build and run
3. Choose mode "Stack - CheckButton - HeaderGroup"   (will cause NullReferenceException)
4. Restart the program
5. Choose mode "Outlook - Full"                      (will cause NullReferenceException)

**Expected behavior**
To work, no NullReferenceException.

**Desktop:**
 - OS: Windows 10 Pro
 - Version: Version	22H2
 - OS build: 19045.4412
 - Toolkit Version: 85.24.06.180
 
 Tested against the following frameworks
 - Framework Version:  4.8                   
 - .Net Version: .Net6-windows             
 - .Net Version: .Net7-windows             

**Additional context**

 Investigation of the "Stack - CheckButton - HeaderGroup" NullReferenceException.

 Following the code with the debugger showed that you can legitimately end up
 at the code below with _headerGroup set to null. Based on the comments in
 the code that author was aware of this condition but forgot to add
 a null reference check.

```
Krypton\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\View Builder\ViewBuilderStackCheckButtonHeaderGroup.cs
Line: 68

 public override void PageVisibleStateChanged(KryptonPage? page)
        {
            // If is possible the header group has not been created yet
            // Ensure buttons are recreated to reflect different previous/next visibility
            // _headerGroup.UpdateButtons();         <=== This needs to be changed
             _headerGroup?.UpdateButtons();          // Include embedded check for a null value

            // Let base class do standard work
            base.PageVisibleStateChanged(page);
        }
```

  Investigation of the "Outlook - Full" NullReferenceException.
  This one is a little bit more complicated that the previous bug.

  Conceptually the "Outlook - Full" View is created then the Button
  Manager is created (in this order due to interdependences between the Button Manager
  and the View).

  The view creation calls some overridden methods in the base class that eventually
  lead to a call to UpdateButtons (but in the case of "Outlook - Full" the
  Button Manager has yet be created) and boom!

  Again the fix is simply a null reference check.

```
Krypton\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\View Builder\ViewletHeaderGroup.cs
Line: 118

  public void UpdateButtons() =>
            // Ensure buttons are recreated to reflect different page
            //_buttonManager?.RecreateButtons();      <=== This needs to be changed
            _buttonManager?.RecreateButtons();        // Include embedded check for a null value
```

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac

Although this is patched in V90, I'm going to apply a patch for V85.

cc. @Legingo
