### ISSUE TITLE
[Bug]: Trying to add a "KTheme" Combo or List box to a form causes a "Universe not found exception

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1583]
Using today's alpha branches from both repo's.

Open Designer for "KryptonListBox Example"
Drag a KComboBox onto form - Ok it does it
Drag a Themed KCombo or KListBox and there is a universe cannot be resolved error:
Win 10 22H2 latest

Using VS 17.11 p2.1
![ThemedBox](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f7745d28-02ff-49b6-9142-1420be0552a4)

In VS 17.10.3 (and 17.9.6) then you also get an extra box thrown **over** the universe box:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/79c039ab-54c0-4125-b688-efd7012acc1a)

**Comment by giduac** [comment]
Hi @Smurf-IV,

It's also with other controls, but not all.

The message can be  removed by adding an "Assembly reference" to the project for `System.Design`.

**Comment by Smurf-IV** [comment]
> It's also with other controls, but not all.

Hence the reason for this bug. Adding a designer to the Dev projects that uses Krypton should not be  the _solution_.

**Comment by giduac** [comment]
Hi @Smurf-IV,

Ok, got it.

The designers/action lists are up for a review in V100, https://github.com/Krypton-Suite/Standard-Toolkit/issues/1521.

ThemeCombo & ThemeListbox both inherit there designers and action lists from the KCombo & KListbox. These actionlists expose properties that are unwanted for these controls.

I tested a dummy designer that does nothing and derives from `ControlDesigner`. 
```cs
    internal class KryptonNullDesigner : ControlDesigner
    {
    }
```
This removes the "universe" errors. Possibly can used for other controls as well.

The ThemeCombo header is changed to this (KThemeListbox is similar of course)
```cs
    /// <summary>Allows the user to change themes using a <see cref="KryptonComboBox"/>.</summary>
    /// <seealso cref="KryptonComboBox" />
    [Designer(typeof(KryptonNullDesigner))]
    public class KryptonThemeComboBox : KryptonComboBox, IKryptonThemeSelectorBase
```

I'd like your OK on this before checking all other controls ?
And, please assign the ticket me, ty.

**Comment by giduac** [comment]
Hi @Smurf-IV,

Please have a look at the above and let me know if this is OK ?

**Comment by Smurf-IV** [comment]
Assigned, and please "Fix" in the v85 branch as well please ?

**Comment by giduac** [comment]
> Assigned, and please "Fix" in the v85 branch as well please ?

@Smurf-IV 
Thanks & I'll check V85 as well.

**Comment by giduac** [comment]
@Smurf-IV or @Wagnerp 
This can be closed then, ty.
