### ISSUE TITLE
[Other Issues]: Move "FadeForm" into Extended kit until issues are sorted (i.e. start <-> end background colours if OS desktop is not in Dark Theme

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1584]
Dodgy timing issue
Unable to app close during fade
Start or end colours if OS theme is not like the theme being used by Krypton App

**Comment by giduac** [comment]
Hi @Smurf-IV & @Wagnerp 

The faber can be made to work but needs some more attention then that infinite loop only. I also think it can be compacted. All up for  debate.

How about if we (for now) disable the fader in KForm and pick it up in V100 ?

**Comment by Smurf-IV** [comment]
Still reckon it's an "ext" thing _until_ stable..

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV 
So shall we remove it from KForm and put it in for V100?
The fader controller class itself can be moved to extended?

**Comment by Wagnerp** [comment]
My $0.02 cents

Disable the feature for now, come back to it in V100 & copy the controller class to ext for further development.

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV 

Will take care of this:
- Disable the fader property in KForm
- Move the fader to extended 
- Put a throw statement in the fader constructor to make it unusable.
- Create a FR for the fader & tag it for V100
- Have this ticket closed.

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 
Completed the above.
Please close, ty.

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp
Completed the above.
Please close, ty.
