### ISSUE TITLE
[Bug]: Office 365 tracking colours are wrong

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#159]
**Describe the bug**
The Office 365 tracking colours are wrong. Need help tracking down where these values are stored.

**Comment by Wagnerp** [comment]
![Bug159](https://user-images.githubusercontent.com/949607/121774713-97047600-cb7b-11eb-8cfa-fee5079e9eb9.gif)

**Comment by Smurf-IV** [comment]
Another Palette Designer requirement ?

**Comment by Wagnerp** [comment]
Yes

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Standard-Toolkit-Demos/issues/26 ?

**Comment by Wagnerp** [comment]
Found the code

**Comment by Wagnerp** [comment]
Fixed in build 2109
