### ISSUE TITLE
[Bug]: KPropertyGrid text disabled colours need reviewing

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1591]
Using todays alpha

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6f48e289-d2ce-49da-b51b-6a5aadf9eaef)

**Comment by giduac** [comment]
Hi @Smurf-IV,

Has this been addressed through https://github.com/Krypton-Suite/Standard-Toolkit/issues/1108 ?

**Comment by Smurf-IV** [comment]
> Hi @Smurf-IV,
> 
> Has this been addressed through #1108 ?

@giduac Should have been. As that view is also _before_ the changes to the listview(s).
@Wagnerp Has the Demo app been updated to include those 2 new grids ?

**Comment by Wagnerp** [comment]
> @Wagnerp Has the Demo app been updated to include those 2 new grids ?

On the 'internal' test app, yes, but not within the demos repo.

**Comment by Smurf-IV** [comment]
> > @Wagnerp Has the Demo app been updated to include those 2 new grids ?
> 
> On the 'internal' test app, yes, but not within the demos repo.

I have "Todays" alpha, and I do not see the PropertyGrid(s) added ? (Or the scrollbars etc)
@Wagnerp Can you update please ?

**Comment by Wagnerp** [comment]
> > > @Wagnerp Has the Demo app been updated to include those 2 new grids ?
> > 
> > 
> > On the 'internal' test app, yes, but not within the demos repo.
> 
> I have "Todays" alpha, and I do not see the PropertyGrid(s) added ? (Or the scrollbars etc) @Wagnerp Can you update please ?

@Smurf-IV 

PR incoming

**Comment by Smurf-IV** [comment]
AS of this mornings "Alpha":
![image](https://github.com/user-attachments/assets/df8e38c6-e2c9-43ee-a988-489e620d610f)
![image](https://github.com/user-attachments/assets/527c80e7-2d1a-404c-9ef5-e446bdce789f)

I think this is "All good" apart from the Black Text on the Very Dark background in the active part..

Closing.
