### ISSUE TITLE
[Bug]: KMessageBox cuts off text

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1592]
Using latest `nightly`

![KMB](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6043df80-ff7d-4837-a2d2-4824e47feb20)

Plus artificing in corners

**Comment by giduac** [comment]
@Wagnerp 
Might help if it is a regression:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/607

**Comment by giduac** [comment]
> @Wagnerp Might help if it is a regression: #607

@Wagnerp 
I had a brief look at the code but the fix from 607 is also in alpha.
As a start you might look in the same area for this ticket

**Comment by Wagnerp** [comment]
> > @Wagnerp Might help if it is a regression: #607
> 
> @Wagnerp I had a brief look at the code but the fix from 607 is also in alpha. As a start you might look in the same area for this ticket

@giduac 

I don't know if the problem is with the window sizing, as I know the code was reset a couple of months ago...

**Comment by giduac** [comment]
@Wagnerp 
Switching between themes shows that it happens with certain themes. So my first thought is that the font is different.

Try this as a start and a value to the returned Size object to see if that changes the behaviour.

From the fix
```cs
            return new Size( 
                textSize.Width + 
                _messageIcon.Width + 
                _messageIcon.Margin.Left + 
                _messageIcon.Margin.Right +
                _messageText.Margin.Left +
                _messageText.Margin.Right, 
                Math.Max(_messageIcon.Height + 10, textSize.Height));
```

Does it also happen when a messagebox icon is displayed??

**Comment by Wagnerp** [comment]
@giduac 

> Does it also happen when a messagebox icon is displayed??

Only when a icon is displayed

- [ ]

**Comment by giduac** [comment]
In your test video there's no icon....

**Comment by Wagnerp** [comment]
@giduac 

Update, tested it again today and it works fine

**Comment by giduac** [comment]
I actually did a quick try on alpha and couldn't find it....

**Comment by Wagnerp** [comment]
Closing, cannot replicate
