### ISSUE TITLE
[Bug]: KryptonMessageBox cuts off the last line (sometimes)

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#1599]
When using KryptonMessageBox to display multiple lines, it sometimes cuts off the last line. I noticed it when displaying exactly three lines, so I ran some tests. <s>AFAICT, it only happens when displaying exactly 3 or 4 lines (less bad for 4 lines though).</s> (this is only true for .NET Core. See comment below for .NET Framework test).

Not sure if this is related to #1592 but it happens whether or not an icon is displayed.

### Screenshots:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/545a73f3-dd4a-45c0-9870-c0eb10751e6c) ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/a3597461-d20b-4a78-b93e-229383e01715)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/d64aa4ec-d5a9-4871-8dc1-9339f435ed23) ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/1d8c835a-ea00-4403-a8ed-968980f5ed3c)

### Code to reproduce:

```
for (int max = 1; max <= 20; max++)
{
    var lines = Enumerable.Range(1, max).Select(i => $"This is line #{i}.").ToList();
    string joined = string.Join("\r\n", lines);
    KryptonMessageBox.Show(joined);
    KryptonMessageBox.Show(joined, "Error", KryptonMessageBoxButtons.YesNo, KryptonMessageBoxIcon.Error);
}
```

Tested on latest stable (v85.24.6.176) and latest nightly (v90.24.7.183-alpha).

**Comment by Ahmed-Abdelhameed** [comment]
### Update:

The above test was done on .NET 8.0. The situation is much worse on .NET Framework:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/ec67de34-ea74-4ccd-ac46-da7024068eae) ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/582ebca8-99d1-4c95-94c3-7e3e0de1d4b2)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/e6205755-08f5-434d-92c7-aaf6bc7077e5) ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/afa31201-eb3d-4e0d-a007-6d093c5a1695)

```
for (int max = 1; max <= 20; max++)
{
    var lines = Enumerable.Range(1, max).Select(i => $"This is line #{i}.").ToList();
    string joined = string.Join("\r\n", lines);
    KryptonMessageBox.Show(joined, $"NumOfLines={max}", KryptonMessageBoxButtons.OK, KryptonMessageBoxIcon.Information);
}
```

**Comment by giduac** [comment]
Hi @Ahmed-Abdelhameed,

I'll have look at this. 
Might take a bit since we are under staffed ;).

One question though: If possible would a scrollbar be an option to limit the size of the dialog (e.g. a percentage of the screen) as the WinForms MB does overshoot the screen when getting to big?

@Wagnerp 
Please assign to me.

**Comment by Wagnerp** [comment]
Hi @giduac 

Now assigned to you

> Will there be V86

No, there will be a patch for v85 in July, fixing the navigator issue (already been dealt with), so you can append to that. In V100, I suggest that we look at the possibility of overhauling `VisualMessageBoxForm`, as it's causing a lot of issues like this one.

**Comment by Ahmed-Abdelhameed** [comment]
@giduac
Okay, I did some digging, found the root cause of the problem, and was going to create a PR but there are a few things that I'm not sure I understand.

First, the cause of the problem is that in `KryptonMessageBoxForm`, there's a [method ](https://github.com/Krypton-Suite/Standard-Toolkit/blob/master-v85/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/KryptonMessageBoxForm.cs#L573) called `UpdateMessageSizing`; in which, the text is measured based on `_messageText.Font`, which is incorrect because that's not the font used to display the text.

I checked the history of the file and looks like this bug was introduced in [this commit](https://github.com/Krypton-Suite/Standard-Toolkit/commit/6ae97b512ef15e40b4acfac0fa5cd1b5672546ba) when `_messageText` was changed from a `KryptonWrapLabel` to a `KryptonTextBox`. Previously, `_messageText.UpdateFont();` was being called before measuring the text in order to assign the current state's font to the control's `.Font` property, but [that line was removed](https://github.com/Krypton-Suite/Standard-Toolkit/commit/6ae97b512ef15e40b4acfac0fa5cd1b5672546ba#diff-787f10df5bc740511d6237ed6514904ec3f8afed7f3a8d70d067ee085ee289f5L591) (presumably because `UpdateFont()` is not a member of `KryptonTextBox`).

Now, I'm not sure whether the right thing to do is replicate that same logic for `KryptonTextBox` because I'm not exactly sure why `KryptonTextBox` was used in the first place. Looks like there was a problem with `KryptonWrapLabel` not displaying tab chars but I don't think switching to a text box was the best option. I don't have time to check that bug in the wrap label right now but I'll try to look into it tomorrow. Perhaps fixing that and switching back to using the wrap label would be the best option?

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

One question though: If possible would a scrollbar be an option to limit the size of the dialog (e.g. a percentage of the screen) as the WinForms MB does overshoot the screen when getting to big?

Sure, that might be a nice-to-have to consider in the future. Although it's not really best practice to display a message box with text that would fill the entire height of the screen, so I wouldn't prioritize this if I were you.

**Comment by giduac** [comment]
> @giduac
> 
> Okay, I did some digging, found the root cause of the problem, and was going to create a PR but there are a few things that I'm not sure I understand.
> 
> First, the cause of the problem is that in `KryptonMessageBoxForm`, there's a [method ](https://github.com/Krypton-Suite/Standard-Toolkit/blob/master-v85/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/KryptonMessageBoxForm.cs#L573) called `UpdateMessageSizing`; in which, the text is measured based on `_messageText.Font`, which is incorrect because that's not the font used to display the text.
> 
> I checked the history of the file and looks like this bug was introduced in [this commit](https://github.com/Krypton-Suite/Standard-Toolkit/commit/6ae97b512ef15e40b4acfac0fa5cd1b5672546ba) when `_messageText` was changed from a `KryptonWrapLabel` to a `KryptonTextBox`. Previously, `_messageText.UpdateFont();` was being called before measuring the text in order to assign the current state's font to the control's `.Font` property, but [that line was removed](https://github.com/Krypton-Suite/Standard-Toolkit/commit/6ae97b512ef15e40b4acfac0fa5cd1b5672546ba#diff-787f10df5bc740511d6237ed6514904ec3f8afed7f3a8d70d067ee085ee289f5L591) (presumably because `UpdateFont()` is not a member of `KryptonTextBox`).
> 
> Now, I'm not sure whether the right thing to do is replicate that same logic for `KryptonTextBox` because I'm not exactly sure why `KryptonTextBox` was used in the first place. Looks like there was a problem with `KryptonWrapLabel` not displaying tab chars but I don't think switching to a text box was the best option. I don't have time to check that bug in the wrap label right now but I'll try to look into it tomorrow. Perhaps fixing that and switching back to using the wrap label would be the best option?

Hi @Ahmed-Abdelhameed 

The measuring and sizing thereafter is indeed the problem.
Had a quick look but the KTextBox does not support auto scrollbars. So it's on or off. But would be a quick fix.
Shall have a closer look to what works best.

I'll keep you posted.

**Comment by giduac** [comment]
Hi @Smurf-IV & @Wagnerp,
cc: @Ahmed-Abdelhameed 

I've been testing a bit with this.
Most prominent in .NET framework.

Since @Wagnerp said that KMB will get a review in V100 I suggest a quick fix for now. KMB is really not suited for "pages" of text and more centered toward simple messages and questions as is the standard Win(forms) KMB.

The easiest certain thing to do for now is to enlarge the calculated vertical message size by a certain percentage....???

Your advice please...

**Comment by Ahmed-Abdelhameed** [comment]
Hi @giduac 

Yeah, once I found out the root cause, it became clear why it's more prominent in .NET Framework (i.e., because the default `Control.Font` is different between runtime versions).

Re: "quick fix"
If KTextBox will be kept as the control to display the message for now, can we at least replicate the same logic that was used for KWrapLabel? I think that should be easy enough and would be better than hardcoding a percentage. I can submit a PR today for this if you agree.

Note that this isn't about displaying pages of text or anything. It happens with as few as 3 lines. Check the following for example:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/1797676f-b6be-4f02-ba55-57897b066de6) ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/33bb9cb8-7496-485f-84ec-63cdeb531108)

**Comment by giduac** [comment]
> Hi @giduac
> 
> Yeah, once I found out the root cause, it became clear why it's more prominent in .NET Framework (i.e., because the default `Control.Font` is different between runtime versions).
> 
> Re: "quick fix" If KTextBox will be kept as the control to display the message for now, can we at least replicate the same logic that was used for KWrapLabel? I think that should be easy enough and would be better than hardcoding a percentage. I can submit a PR today for this if you agree.
> 
> Note that this isn't about displaying pages of text or anything. It happens with as few as 3 lines. Check the following for example:
> 
> ![image](https://private-user-images.githubusercontent.com/18140178/346502248-1797676f-b6be-4f02-ba55-57897b066de6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzEwNjUsIm5iZiI6MTcyMDQzMDc2NSwicGF0aCI6Ii8xODE0MDE3OC8zNDY1MDIyNDgtMTc5NzY3NmYtYjZiZS00ZjAyLWJhNTUtNTc4OTdiMDY2ZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYTU4MjZlOTJhYmI0ZmIzNzllMjgzNjk2NTljYTVmMzkwZmY1ZDFlOWRhMzhhYzgyNzcwYjBmYWNhYTUxYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4i23kp5kEc9mv6x5RXZE7vvxPRWuyHaNN-pNxRG_XBY) ![image](https://private-user-images.githubusercontent.com/18140178/346502467-33bb9cb8-7496-485f-84ec-63cdeb531108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzEwNjUsIm5iZiI6MTcyMDQzMDc2NSwicGF0aCI6Ii8xODE0MDE3OC8zNDY1MDI0NjctMzNiYjljYjgtNzQ5Ni00ODVmLTg0ZWMtNjNjZGViNTMxMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTNlYWUxNjY0YWM0Mjk3Y2YxMzVjZWQ0NDYxNGQ3YWE5ZjA2MTliOGVlYmFkMjUzNTViM2E3MTczZmI2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wyifXQTE6UqCDE82K2eZZYp1dwxFI8SaTV9gqNSD-lI)

How about if you for now push it to your own branch on you account (without submitting a PR).
We can have a look at it, wait the others' reaction and decide together how to proceed?

Let us know when you pushed the commit?

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Done: https://github.com/Ahmed-Abdelhameed/Standard-Toolkit/commit/a82ce8046b0252110b05adc10f0993641bb29c67

So, the font was not the only problem. There were a couple more that I fixed as well:
- The calculations did not include the KTextBox's content padding and its container's (KPanel) margin.
- `Graphics.MeasureString()` does not give accurate measurements when `UseCompatibleTextRendering` is false (which is the case). `TextRenderer.MeasureText()` is the right method to use here.

There are a couple of things left (I will fix in a separate commit):
1. Because KTextBox doesn't support vertical alignment, the text is not centered vertically when it consists of one line (or two but less obvious). As a temporary workaround, we could calculate an offset for the text box when the calculated text area's height is smaller than the icon area's height but there's a better way (See below).
2. Because the measurement is more accurate now, there's minimal margin at the top and bottom of the text increasing the margin will make it look better and will also avoid the other problem above.

I will push another commit for this shortly and will create a new issue for this so you can reference it in your own commit.

**Comment by giduac** [comment]
> @giduac
> 
> Done. Here's the commit: [Ahmed-Abdelhameed@a82ce80](https://github.com/Ahmed-Abdelhameed/Standard-Toolkit/commit/a82ce8046b0252110b05adc10f0993641bb29c67)
> 
> So, the font was not the only problem. There were a couple more that I fixed as well:
> 
> * The calculations did not include the KTextBox's content padding and its container's (KPanel) margin.
> * `Graphics.MeasureString()` does not give accurate measurements when `UseCompatibleTextRendering` is false (which is the case). `TextRenderer.MeasureText()` is the right method to use here.
> 
> There are a couple of things left (I will fix in a separate commit):
> 
> 1. Because KTextBox doesn't support vertical alignment, the text is not centered vertically when it consists of one line (or two but less obvious). As a temporary workaround, we could calculate an offset for the text box when the calculated text area's height is smaller than the icon area's height but there's a better way (See below).
> 2. Because the measurement is more accurate now, there's minimal margin at the top and bottom of the text increasing the margin will make it look better and will also avoid the other problem above.
> 
> I will push another commit for this shortly and will create a new issue for this so you can reference it in your own commit.

@Ahmed-Abdelhameed 

This commit was made against the V85 branch.
We always create a new branch from Alpha or Master-V85 to work on an issue.
That branch is pushed and used later on to publish the PR.
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Contributing.html

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Oh, okay. Let me fix that.

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Done: https://github.com/Ahmed-Abdelhameed/Standard-Toolkit/commit/16b44409993e3a8a6a2e32f658e8dc7d8e36e6f1

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed & @giduac 

My $0.02 cents on this...

Patch it for V90, then do a complete overhaul for V100. It is possible to use a KRichTextBox for the content area. The added benefits would be scrolling & detection of URLs. Doing a test for KToasts, using  KRichTextBoxes and it works really well.

Maybe either of you can come up with a todo list for the V100 overhaul?

cc. @Smurf-IV

**Comment by giduac** [comment]
@Ahmed-Abdelhameed 

I tested the fix, it works nicely and don't think there will be any objections to it.
Let's complete this for V85 first so the process we use is explained to you. 
I'll get back to you after that and set you up for V90.

So before we all publish a PR we always [build the project from the command line](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Contributing/How-to-Build.html) and include a screenshot of the results.

For V85 there maybe no errors of course. 
For V90 there may be no warnings as well.

Screenshot of the included build results image in a PR:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/788e1b84-b3d4-4087-9e4e-00a2a673c9d8)

Include a link to the issue being handled which makes the PR show up in the issue..
Personally I always include the branch name in both commits and PR  comments.

When  you create the PR in GitHub Desktop make sure to set it against the correct branch (V85 of course in this case).
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/f1ffcd68-9262-46fa-b7b1-b8523fe16045)


If you have questions .....

**Comment by Ahmed-Abdelhameed** [comment]
@giduac

PR submitted.

@Wagnerp

> It is possible to use a KRichTextBox for the content area. The added benefits would be scrolling & detection of URLs. Doing a test for KToasts, using KRichTextBoxes and it works really well.

RTB will most likely introduce more bugs and overcomplicate things. In my opinion, KMessageBox should be very simple and behave as close as possible to the original Win32 MessageBox. Then, for extra functionality (URLs, etc.), we can have another component like the one(s) that exist in the extended suite (I haven't tested any of them myself).

**Comment by giduac** [comment]
@Ahmed-Abdelhameed,

Nice, ty!!

This will (as most of the time) be checked tomorrow morning.

If you want to move ahead with V90 the process is practically the same.
- In GH Desktop
- Select the alpha branch (V90 currently) and make sure it's up to date
- Create a new branch from alpha
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/20c80be0-2752-4bce-988a-dcef20c499ff)

The V90 KMB  consists of 4 KMB's / Forms that need attention.
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/80f8761a-5e3f-4b43-84d0-8bc26b1b8a54)

**Comment by Ahmed-Abdelhameed** [comment]
@giduac

Looks like V90 requires the latest version of Visual Studio _Preview_, which I'm not using at the moment. I'll see if I can upgrade to it later.

**Comment by giduac** [comment]
@Ahmed-Abdelhameed ,
Yeah 9.0 preview is needed...

**Comment by Ahmed-Abdelhameed** [comment]
Hi @giduac 

Sorry for the sudden disappearance. It was a pretty hectic week for me.

Okay, I finally installed VS 2022 Preview so that I can build against .NET 9.0. Let me see what I can do.

**Comment by giduac** [comment]
@Ahmed-Abdelhameed 

If you are pressed for time I can finish the KMB tickets?

**Comment by giduac** [comment]
@Ahmed-Abdelhameed,

V85 was finished afaik.
@Wagnerp already forwarded some of the code into V90. Also the Change log entries have been added by him.
Best to check PR https://github.com/Krypton-Suite/Standard-Toolkit/pull/1622 and see what still needs to be done.

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Yes, I checked all that yesterday and already working on the fixes. I have one question though. Is there a reason that the icon in `VisualMessageBoxFormDep` has a height of 79 (compared to 35 in `VisualMessageBoxForm`), thus increasing the minimum height of the form?

CC: @Wagnerp

**Comment by giduac** [comment]
I think @Wagnerp is in charge of the icons around here ;)

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Well, the icon itself isn't the problem, but rather the PictureBox control that contains the icon (that's what I meant). The icon size is the same, AFAICT. I think we should make the default size the same as in `VisualMessageBoxForm` but I wanted to double-check that this wasn't done on purpose.

**Comment by Wagnerp** [comment]
> I think @Wagnerp is in charge of the icons around here ;)

The actual size of the image does not need to be changed, but the size of the form itself. This can be done in the `UpdateSizing` itself.

**Comment by giduac** [comment]
Hi @Ahmed-Abdelhameed,
cc: @Smurf-IV, @Wagnerp 

The WinForms MessageBox always closes on escape, the krypton kmb sometimes.

```cs
            // Escape key kills the dialog if we allow it to be closed
            if (ControlBox
                && (e.KeyCode == Keys.Escape)
               )
            {
                Close();
            }
            else if (e.KeyData == (Keys.Control | Keys.C))
```
Could you have look (when you have time) if `ControlBox` safely can be removed to replicate the WinForms behaviour.
Probably a new ticket if...

**Comment by Ahmed-Abdelhameed** [comment]
Hey @giduac 

> Could you please have look (when you have time) if `ControlBox` safely can be removed from the if

Definitely not. The WinForms MessageBox does _not_ always close with the Esc key. It only allows closing when it makes sense (i.e., when there's either an OK or a Cancel button), so for example, a `YesNo` MBox cannot be closed, whereas a `YesNoCancel` one can be. Looking at the code of KMessageBox, `ControlBox` is disabled when `KryptonMessageBoxButtons` is equal to `YesNo` or `AbortRetryIgnore`, which is the expected behavior.

**Comment by giduac** [comment]
> Hey @giduac
> 
> > Could you please have look (when you have time) if `ControlBox` safely can be removed from the if
> 
> Definitely not. The WinForms MessageBox does _not_ always close with the Esc key. It only allows closing when it makes sense (i.e., when there's either an OK or a Cancel button), so for example, a `YesNo` MBox cannot be closed, whereas a `YesNoCancel` one can be. Looking at the code of KMessageBox, `ControlBox` is disabled when `KryptonMessageBoxButtons` is equal to `YesNo` or `AbortRetryIgnore`, which is the expected behavior.

TY & Case closed then I would say :)

**Comment by Ahmed-Abdelhameed** [comment]
This is already fixed and merged into both V85 and alpha branches.

**Comment by giduac** [comment]
@Ahmed-Abdelhameed 
Nice job!
