### ISSUE TITLE
[BUG]: Taskbar Width ist offset in Docking operations

### ISSUE THREAD

**Issue by sneusse** [Krypton-Suite/Standard-Toolkit#16]
When docking or resizing dockspaces the guidelines are offset by the width of the taskbar.

**To Reproduce**
1. Use current stable version
2. Have your taskbar on the left screen edge
3. Dock or resize anything

**Expected behavior**
Would expect this to work with taskbar on the left side.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/1814523/88923576-3a091580-d272-11ea-8eea-38ce5126a3be.png)

**Comment by Wagnerp** [comment]
@sneusse Thank's for contributing! Will push out a update later today.
