### ISSUE TITLE
[Bug]: "MS365 - Black" theme is unreadable

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1607]
Using today's alpha, and the test app, the MS365 - Black theme is unreadable in both active and non focused states:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/afda3d51-e47d-47ac-9b76-8fd5a8a0ed7b)

And Active:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/17afdbd8-6d48-4692-8a1a-5e7e77bbacef)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

This is the value you want to play around with...

```cs
   SystemColors.Control, // InputControlBackDisabled
```

**Comment by Smurf-IV** [comment]
> This is the value you want to play around with...
> 
> ```cs
>    SystemColors.Control, // InputControlBackDisabled
> ```

What has this to do with the theme colours ?

**Comment by Wagnerp** [comment]
> > This is the value you want to play around with...
> > ```cs
> >    SystemColors.Control, // InputControlBackDisabled
> > ```
> 
> What has this to do with the theme colours ?

It's within the colours array of the theme, and controls the 'disabled' bg colour

**Comment by Smurf-IV** [comment]
Noting should be using `SystemColors.Control` as different people have different backgrounds etc (i.e. Dark OS themes have nothing to do with Dark Krypton themes)
And if the user has a light OS theme, then those system colours are going to be "Very wrong" for use with Dark Krypton themes.

**Comment by Wagnerp** [comment]
> Noting should be using `SystemColors.Control` as different people have different backgrounds etc (i.e. Dark OS themes have nothing to do with Dark Krypton themes) And if the user has a light OS theme, then those system colours are going to be "Very wrong" for use with Dark Krypton themes.

I think this has existed in previous themes since 4.x

> then those system colours are going to be "Very wrong" for use with Dark Krypton themes.

No, as these were changed in PR #1587 to be colour appropriate

**Comment by Wagnerp** [comment]
@Smurf-IV 

I think this should be more of a Bug/FR, since it's a legacy thing that needs updating to match modern design principals, i.e. dark/light modes introduced with Win 10.

Thoughts @giduac?

**Comment by giduac** [comment]
@Wagnerp & @Smurf-IV 

There are a lot of those tickets. 

@Wagnerp , can you make a concise overview of things you run into when fine tuning themes and maybe also defining the main color setup of themes.

So we can look into this together and what can be done about it.

**Comment by Wagnerp** [comment]
@giduac 

> can you make a concise overview of things you run into when fine tuning themes and maybe also defining the main color setup of themes.

Will post it in the discussions

**Comment by giduac** [comment]
Probably open a discussion where we can dig down a little deeper into this...

**Comment by Wagnerp** [comment]
> Probably open a discussion where we can dig down a little deeper into this...

Hi @Smurf-IV & @giduac 

Please see https://github.com/Krypton-Suite/Standard-Toolkit/discussions/1608 for how theme colours work

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac 

I now know where to fix this. Do you want me to apply the same fixes for the O2k7/10 themes as well, or leave them be?

**Comment by Smurf-IV** [comment]
My vote is to: Fixing themes is the focus for v90

**Comment by Wagnerp** [comment]
Fixed, PR incoming

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/d99c3e3a-8af7-4a54-99e8-81aeb77b263f)
