### ISSUE TITLE
[Bug]: KryptonMessageBox text is not centered vertically 

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#1613]
Because KMB now uses a KTextBox to display the text, the text doesn't get centered vertically when the height of the icon is larger, which doesn't look good if compared with the original MB or older versions of KMB:

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/5170d9c5-25dc-498c-84b9-af4c9f5c5ee5) vs ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/10d7e30b-f933-4eb2-8e0c-8b3a508ab944)

A workaround would be to calculate the size difference and use it to offset the text box but there's a simpler solution, IMO. That is, to just increase the top and bottom margin of the text area because I think it needs more margin anyway, especially after fixing #1599.

We just need to change one line in `KryptonMessageBoxForm.Designer.cs`:
```
this._panelContentArea.Margin = new System.Windows.Forms.Padding(4);
```
to
```
this._panelContentArea.Margin = new System.Windows.Forms.Padding(4, 12, 4, 12);
```

### Before:

| One line | Multiple lines | No icon |
|--------|--------|--------|
| ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/6a59e3da-a446-48f5-8ff7-60c889ad2276) | ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/a5c55e6a-fbf3-4336-a616-6f6869c34ef7) | ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/4356858a-3954-4385-8308-dd517a14ee20) |

### After:
| One line | Multiple lines | No icon |
|--------|--------|--------|
| ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/9d0c7f2c-a01a-44d8-8df7-3588a1bd822c) | ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/b39bae31-e808-4837-9020-5c89ca9618f6) | ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/18140178/cec648b6-01a5-4e06-b086-d9398b24796b) |

**Comment by giduac** [comment]
@Wagnerp 
Please assign to me and @Ahmed-Abdelhameed , ty.

**Comment by Wagnerp** [comment]
> @Wagnerp Please assign to me and @Ahmed-Abdelhameed , ty.

@Ahmed-Abdelhameed & @giduac 

Now assigned to both of you

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed & @giduac 

In V90, it's the opposite...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/126e659a-c00a-4b43-9006-ae6dcd57afe4)

**Comment by Ahmed-Abdelhameed** [comment]
This is already fixed and merged into both V85 and alpha branches.
