### ISSUE TITLE
[Bug]: KryptonMessageBox sometimes throws an exception after Esc key is pressed

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#1614]
This is not an easy one to reproduce because it happens randomly but when the Esc key is pressed, sometimes KMessageBox throws an exception of type `System.Runtime.InteropServices.ExternalException` and the bug is in [this part of the code](https://github.com/Krypton-Suite/Standard-Toolkit/blob/4c38c8492a2290291047e2f668fa17efe8417931/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/KryptonMessageBoxForm.cs#L705):

```
private void AnyKeyDown(object sender, KeyEventArgs e)
{
    // Escape key kills the dialog if we allow it to be closed
    if (ControlBox
        && (e.KeyCode == Keys.Escape)
       )
    {
        Close();
    }
    else if (!e.Control
             || (e.KeyCode != Keys.C)
            )
    {
        return;
    }

    // [Irrelevant code omitted]

    Clipboard.SetText(sb.ToString(), TextDataFormat.Text);
    Clipboard.SetText(sb.ToString(), TextDataFormat.UnicodeText);
}
```

The problem is that after `Close()` is called, the method doesn't return, allowing the execution to continue while the form is being disposed of. To fix this, we could either add `return;` after `Close();` or to avoid having two `return;` statements, we can turn the `else if` into its own `if` statement:

```
private void AnyKeyDown(object sender, KeyEventArgs e)
{
    // Escape key kills the dialog if we allow it to be closed
    if (ControlBox
        && (e.KeyCode == Keys.Escape)
       )
    {
        Close();
    }

    if (!e.Control || (e.KeyCode != Keys.C)) return;

    // [Irrelevant code omitted]

    Clipboard.SetText(sb.ToString(), TextDataFormat.Text);
    Clipboard.SetText(sb.ToString(), TextDataFormat.UnicodeText);
}
```

**Comment by Wagnerp** [comment]
> @Wagnerp Please assign to me and @Ahmed-Abdelhameed, ty.

@Ahmed-Abdelhameed & @giduac 

Now assigned to both of you

**Comment by giduac** [comment]
@Ahmed-Abdelhameed 

Btw.: we always use curly braces also on control statements with one line.
I think this is fine. 

```cs
            if (ControlBox && e.KeyCode == Keys.Escape))
            {
                Close();
                return;
            }
            
            if (!e.Control || e.KeyCode != Keys.C)
            {
                return;
            }
```

What do you think ?

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

> Btw.: we always use curly braces also on control statements with one line.

 Got it 👍

If we're going to repeat `return;`, then the second one should remain in an `else if`. Either two `if`'s with one `return;` or `if... else if` with two `return;`'s, Otherwise, it's quite redundant. No?

**Comment by giduac** [comment]
> @giduac
> 
> > Btw.: we always use curly braces also on control statements with one line.
> 
> Got it 👍
> 
> If we're going to repeat `return;`, then the second one should remain in an `else if`. Either two `if`'s with one `return;` or `if... else if` with two `return;`'s, Otherwise, it's quite redundant. No?

Or....
```cs
            if (ControlBox && e.KeyCode == Keys.Escape)
            {
                Close();
            }
            else if (e.Control && e.KeyCode == Keys.C)
            {
                const string DIVIDER = @"---------------------------";
                const string BUTTON_TEXT_SPACER = @"   ";
                // Pressing Ctrl+C should copy message text into the clipboard
                var sb = new StringBuilder();

                sb.AppendLine(DIVIDER);
                sb.AppendLine(Text);
                sb.AppendLine(DIVIDER);
                sb.AppendLine(kwlblMessageText.Text);
                sb.AppendLine(DIVIDER);
                sb.Append(_button1.Text).Append(BUTTON_TEXT_SPACER);
                if (_button2.Enabled)
                {
                    sb.Append(_button2.Text).Append(BUTTON_TEXT_SPACER);
                    if (_button3.Enabled)
                    {
                        sb.Append(_button3.Text).Append(BUTTON_TEXT_SPACER);
                    }

                    if (_button4.Enabled)
                    {
                        sb.Append(_button4.Text).Append(BUTTON_TEXT_SPACER);
                    }
                }

                sb.AppendLine(string.Empty);
                sb.AppendLine(DIVIDER);

                Clipboard.SetText(sb.ToString(), TextDataFormat.Text);
                Clipboard.SetText(sb.ToString(), TextDataFormat.UnicodeText);
            }

```

**Comment by giduac** [comment]
@Ahmed-Abdelhameed,
Plenty of choice... :)

**Comment by Ahmed-Abdelhameed** [comment]
@giduac 

Yeah sure, that works too. One other minor thing though. Instead of `else if (e.Control && e.KeyCode == Keys.C)`, we should be using either

```
else if (e.KeyData == (Keys.Control | Keys.C))
```
Or:
```
else if (e.Modifiers == Keys.Control && e.KeyCode == Keys.C)
```

Because the current logic will be triggered by Ctrl+Shift+C and Ctrl+Alt+C.

**Comment by giduac** [comment]
@Ahmed-Abdelhameed 
First one imo...
Second one will do as well...

**Comment by Wagnerp** [comment]
@giduac & @Ahmed-Abdelhameed 

Also, if you are using `if... else...` statements, you could possibly use `?:` to  shorten them.

**Comment by giduac** [comment]
@Wagnerp,

Please close ty.

**Comment by Ahmed-Abdelhameed** [comment]
This is already fixed and merged into both V85 and alpha branches.
