### ISSUE TITLE
[Feature Request]: Default rounding of control corners

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#162]
**Is your feature request related to a problem? Please describe.**
At the moment, all controls have a default rounding of `-1` (no rounding). The proposal is to change this to `5` or higher, to fit in better with the new 'Sun Valley' UX updates.

**Comment by Smurf-IV** [comment]
This will break the assumption of "Material Design" style
It should be a theme controlled value

**Comment by Wagnerp** [comment]
> This will break the assumption of "Material Design" style
> It should be a theme controlled value

@Smurf-IV I've put in place a `MATERIAL_THEME_CORNER_ROUNDING_VALUE` for use with Material Design styles. It's set to -1.

**Comment by Wagnerp** [comment]
Can control it in the 'Palette Bases'

**Comment by Wagnerp** [comment]
Available in the August 2021 (Canary) build.
