### ISSUE TITLE
[Bug]: Why does `KryptonThemeComboBox` set itself to using `Professional - System`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1624]
When using V90, why does `KryptonThemeComboBox` set itself to using `Professional - System` instead to MS365 - Blue?

**Comment by giduac** [comment]
@Wagnerp 

Can you post a test project that shows this?

**Comment by Wagnerp** [comment]
@giduac 

Here you go...

![1624](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/0b867ede-b82f-4c9c-9043-8b6122f78005)

**Comment by giduac** [comment]
@Wagnerp 
Confirmed. 
Needs a little TLC.

Please turn this into a bug, V90 and assign it to me.

**Comment by Wagnerp** [comment]
> @Wagnerp Confirmed. All three theme selectors are affected by this since it's in the common part. Needs a little TLC.
> 
> Please turn this into a bug, V90 and assign it to me.
> 
> Oh, is it possible that I can be made to edit the topic start?

Hi @giduac 

Now assigned to you

**Comment by giduac** [comment]
@Wagnerp 
Please close, ty.
