### ISSUE TITLE
[Bug]: KryptonRibbon - clicking the Mini QAT Menu Button causes an exception.

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1633]
**Describe the bug**
When the QAT mini menu button is clicked the application crashes

**To Reproduce**
1. Add a Ribbon to a KForm 
2. Run the program
3. Click the QAT Mini Button

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - current alpha branch

**Additional context**
Also happens when the Ribbon is on a control like KPanel.
Caused by: ViewLayoutRibbonQATMini.OwnerForm property being NULL / uninitialized.
PR incoming

@Wagnerp 
Please assign to me and tag for V90 & V85, ty.

V85 is not affected.

**Comment by Wagnerp** [comment]
@giduac 

Now assigned to you

**Comment by giduac** [comment]
@Wagnerp 
V85 is not affected.
Please close, ty.
