### ISSUE TITLE
[Build System] EditorConfig null masking needs to be "Unhidden"

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1650]
Hi @Ahmed-Abdelhameed & @giduac 

I don't think the changes made to `editorconfig` should **not** be reverted, as prior to this it was hiding 7000+ nullable warnings. Plus the toolkit has non-standard WinForms features, i.e. ButtonSpecs which need to be considered.

cc. @Smurf-IV

_Originally posted by @Wagnerp in https://github.com/Krypton-Suite/Standard-Toolkit/issues/1636#issuecomment-2232587056_

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 
This means that we will have a new warning removal "session" to complete?

**Comment by Wagnerp** [comment]
> @Smurf-IV & @Wagnerp This means that we will have a new warning removal "session" to complete?

@giduac 

Yes, since it was hiding more warnings
