### ISSUE TITLE
[Bug]: What is/does "GenericToolkitImages" supposed to do ?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1657]
Using todays alpha, the designer shows a strange "Modified" against an item that does not appear to be modified or even do anything !

![image](https://github.com/user-attachments/assets/0f96977b-bfe9-419b-9bb0-fe27c8078c1c)

Please remove, because:
- Application icon is controlled via the project settings
- It does not appear to work correctly
- The "properties "Help text" does not indicate it usage

**Comment by Wagnerp** [comment]
That's supposed to control the image shown in the ribbon 'orb'.

**Comment by Smurf-IV** [comment]
> That's supposed to control the image shown in the ribbon 'orb'.

But then that would be in the "Ribbon Designer" not the manager of "All things" = KryptonManager class
![image](https://github.com/user-attachments/assets/90cf4204-a6de-45c6-a34e-664d45616e18)

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 

Best you read up on this: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1632 and my  findings.

**Comment by giduac** [comment]
@Wagnerp, @Smurf-IV 

See the above message, first please.

I like to suggest to remove ToolkitImages completely from KManager.
The code needs a rewrite but next to that and more important it is in wrong the spot and has nothing to do with KManager.

Your thoughts...

**Comment by Wagnerp** [comment]
@giduac 

I think I made some comments on Discord...

**Comment by Smurf-IV** [comment]
> I like to suggest to remove ToolkitImages completely from KManager. 

Agreed.
