### ISSUE TITLE
[Bug]: Todays Alpha: clicking the "Old Style Main" causes a messageBox to appear

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1658]
![image](https://github.com/user-attachments/assets/ceb22794-b8aa-4936-a74f-ce71175cdca1)

It's also showing that:
- the Message text is not centered to the icon;
- There is lot's of white space under that text
- Carriage returns in the message appear to not be used within the text

**Comment by giduac** [comment]
Tested this today and cannot reproduce this error. 
Form opens as expected.
