### ISSUE TITLE
[Question]: Will there be an update to the NuGet package of V85 to reflect the recent changes?

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#1667]
Quite a few changes were made to V85 recently (mainly related to KMessageBox). Are there any plans to update the NuGet package(s) any time soon to ship these changes?

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed 

Yes, build .204 was published today.

**Comment by Ahmed-Abdelhameed** [comment]
Thanks a lot, @Wagnerp!
