### ISSUE TITLE
[Bug]: TestForm: MessageBox "No Close button" is not respected anymore

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1686]
@Wagnerp Was this a "New" feature that should not be related to the Base KMB??"

- Using todays alpha
- Clearing the "Show Close Button"
- still displays the close button !
![image](https://github.com/user-attachments/assets/a28053c1-79f1-4f65-9218-d5757ff00491)

**Comment by Wagnerp** [comment]
@Smurf-IV 

Yes, this was related to the 'new' style, but can be added to the base iteration
