### ISSUE TITLE
[Bug]: "TaskDialog" has many issues

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1687]
Using todays alpha
Via the testForm:
![image](https://github.com/user-attachments/assets/dda8483c-dec2-4cc0-94b1-1fb4ffbc655c)

- There are "Things" in the top border area
- It is resizable
- Icon is not displayed correctly

**Comment by giduac** [comment]
Hi @Smurf-IV,

Had a brief look at this
- Current alpha is not resizable
- The "things" are not visible. Tried some 10 themes.
- The image displayed is actually an Icon. Unless that is stretched it won't get much bigger than that....
This the property:

```cs
        /// <summary>
        /// Gets and sets the predefined icon.
        /// </summary>
        [Category(@"Appearance")]
        [Description(@"Predefined icon.")]
        [DefaultValue(KryptonMessageBoxIcon.None)]
        public KryptonMessageBoxIcon Icon
        {
            get => _icon;

            set
            {
                if (_icon != value)
                {
                    _icon = value;
                    OnPropertyChanged(new PropertyChangedEventArgs(nameof(Icon)));
                }
            }
        }
```

**Comment by giduac** [comment]
Hi @Smurf-IV,

Please have a look at the previous message.
Thanks.

**Comment by giduac** [comment]
Unable to reproduce.
Reporter is not responding.
Ticket will be closed, if needed it can be reopened.
