### ISSUE TITLE
[Bug]: MessageBox text is "Hard to read" when using MS 365 dark theme"

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1689]
Using Todaya alpha

![image](https://github.com/user-attachments/assets/696d127a-5a5a-47db-a76d-dfb2a6875ef6)

**Comment by Wagnerp** [comment]
Yes, going to change to white (if I can find the right entry :))

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac 

Thoughts?

![image](https://github.com/user-attachments/assets/f9357dfa-dc05-4015-a6f4-9343f4768a6d)

Note this change will globally affect label text colours in black themes...

**Comment by giduac** [comment]
looks good
