### ISSUE TITLE
[Bug]: `KryptonMessageBox` text should not be using `TextLabelControl` colours whilst using standard black themes

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1692]
While investigating #1689, it was found that `InputText` were using `TextLabelControl` colours. Consider using `TextButtonNormal` instead.

**Comment by giduac** [comment]
@Wagnerp 

Can you please add some more context that describes what has to be corrected here?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Can you please add some more context that describes what has to be corrected here?

@giduac 

So, when I changed the MessageBox from black to white in the normal black themes, it also affected the dropdown/list controls.

**Comment by giduac** [comment]
> > @Wagnerp
> > Can you please add some more context that describes what has to be corrected here?
> 
> @giduac
> 
> So, when I changed the MessageBox text from black to white in the normal black themes, it also affected the dropdown/list controls.

So one of the two uses the wrong color definition?
Can you also please specify the definition(s) used by both?

**Comment by Wagnerp** [comment]
> > > @Wagnerp
> > > Can you please add some more context that describes what has to be corrected here?
> > 
> > 
> > @giduac
> > So, when I changed the MessageBox text from black to white in the normal black themes, it also affected the dropdown/list controls.
> 
> So one of the two uses the wrong color definition? Can you also please specify the definition(s) used by both?

Yes, so all labels should be using the suggested `TextLabelControl` definition, **but** using the same for 'InputText' does not make sense.

**Comment by giduac** [comment]
> > > > @Wagnerp
> > > > Can you please add some more context that describes what has to be corrected here?
> > > 
> > > 
> > > @giduac
> > > So, when I changed the MessageBox text from black to white in the normal black themes, it also affected the dropdown/list controls.
> > 
> > 
> > So one of the two uses the wrong color definition? Can you also please specify the definition(s) used by both?
> 
> Yes, so all labels should be using the suggested `TextLabelControl` definition, **but** using the same for 'InputText' does not make sense.

@Wagnerp 
Ooh, but in the mean time  we also changed from ktextbox to krichtextbox. Both are input controls. Before that it was a Kwarplabel which isn't an input control.

So KMB and it's brothers and sisters need to have the KRTB text and background set to the definitions KWarplabel uses.

Do you know which definitions that would be?

**Comment by Wagnerp** [comment]
@giduac & @Smurf-IV 

So, an idea I had is to create 2 new `InputControlStyle`s to invert the text colours. Thoughts?

![image](https://github.com/user-attachments/assets/b577f3f0-800b-4def-9fa2-c7c56e7d96cb)

**Comment by Smurf-IV** [comment]
Using the text `Inverted` does not state where it is "Intended" to be used. 
Currently misleading, especially when related to this bug.
