### ISSUE TITLE
[Bug]: `KryptonCustomPaletteBase` Illegal characters in path

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1693]
Using todays `Alpha`

---------------------------
Exception Caught
---------------------------
An unexpected error has occurred:

Class: D:\Development\Krypton\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonCustomPaletteBase.cs
Method: PerformUpgrade
Line: 2288
Message: Illegal characters in path.

Stacktrace:
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Krypton.Toolkit.KryptonCustomPaletteBase.PerformUpgrade(Stream stream) in D:\Development\Krypton\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonCustomPaletteBase.cs:line 2259

---------------------------
O&K   
---------------------------

**Comment by giduac** [comment]
@Wagnerp 

Can you give some more info please:
- What is the path that causes this
- Add a sample program that demonstrates the bug

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Can you give some more info please:
> 
> * What is the path that causes this
> * Add a sample program that demonstrates the bug

@giduac 

Yes, so if you try importing & upgrading any custom XML palette in V90, it should trigger the issue. Use the `ImportWithUpgrade` function, I don't exactly know what's going wrong.

**Comment by giduac** [comment]
@Wagnerp 

Give this a try, as this works normally here with the theme in the code snippet.

```cs
        private void kryptonButton4_Click(object sender, EventArgs e)
        {
            KryptonManager kryptonManager = new();
            
            string theme = @"D:\Krypton\Theme-Palettes\Palettes\Other\Asphalt_v19.xml";

            FileStream fileStream  = new FileStream(path: theme, mode: FileMode.Open);

            KryptonCustomPaletteBase kryptonCustomPaletteBase = new();
            kryptonCustomPaletteBase.ImportWithUpgrade(fileStream);

            kryptonManager.GlobalCustomPalette = kryptonCustomPaletteBase;
            kryptonManager.GlobalPaletteMode = PaletteMode.Custom;

            fileStream.Close();
            fileStream.Dispose();
        }


```
