### ISSUE TITLE
[Bug]: V85.24.7 Update is unstable / unusable

### ISSUE THREAD

**Issue by JeanPasquini** [Krypton-Suite/Standard-Toolkit#1696]
Good morning.

I use the 80.24.3.64 version of Toolkit Krypton 

![image](https://github.com/user-attachments/assets/90b27a52-e31f-4d6c-a781-1dc6ec124f49)

But when I was update for the new version, almost forms in my application give me an error of object invalid, look the example:

![image](https://github.com/user-attachments/assets/8444cb67-eaad-43da-be81-758279bd658d)
![image](https://github.com/user-attachments/assets/f939b09c-8768-4c89-b852-d732fb364c8d)
![image](https://github.com/user-attachments/assets/8b82e66e-330e-4d72-a57f-10e37bc43ace)
 
---

I was updating because when I put a textbox with multilines, it didn't set the size that I wanted, so I thought if update it fix the problem.

Don't have a lot of informations, but any answer or help I'm grateful, tks

---

If need more informations I will answer soon

**Comment by giduac** [comment]
Hi @JeanPasquini,

If you go back to the previous (nuget) version is everything then back to normal again?

**Comment by JeanPasquini** [comment]
Hi @giduac ,

Yes, when I go back to the previous version the applications is normal again.

**Comment by JeanPasquini** [comment]
I did a test with the next version of 80.24.3.64 (v85.24.6.176) and it works normally.

**Comment by giduac** [comment]
@JeanPasquini,

Ok, when you use the latest (that causes the error) is it possible to build and run the program using CTRL+F5 ?
If so, do you get an error message ?

**Comment by JeanPasquini** [comment]
Other thing that I see...

When I put textbox with multilines in a groupbox 

![image](https://github.com/user-attachments/assets/f3822fb8-a11a-4995-8fc2-ea6155e373e1)

When run the program, the size of textbox is alternate 

![image](https://github.com/user-attachments/assets/9b1d8d94-7129-4abf-ae11-15e1a60ec157)

and It happens only when I put into a groupbox.

**Comment by JeanPasquini** [comment]
Yeah I can run the program, but when I use a form with the krypton give an error 

![image](https://github.com/user-attachments/assets/b9ae9f36-1f75-44b8-a594-7dc699ebafd9)

'Object reference not set to an instance of an object.' 

But all were working normally

**Comment by giduac** [comment]
Looks like this is related to this:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/1675

But this fix will be in the next update for V85

**Comment by JeanPasquini** [comment]
Undestand, so I'll wait for next update, in time I use v85.24.6.176, tks for attention and sorry for no look this.

**Comment by giduac** [comment]
You can clone the repo and create local nugets using branch master-v85 if you are in a hurry...

https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Contributing/How-to-Build.html
