### ISSUE TITLE
[Bug]: Upgraded from 85.24.7.204 to 85.24.6.176 - Receive following error on start

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1698]
**Describe the bug**
Upgraded to newest Krypton toolkit, error thrown on start ( no changed to code )
Cannot continue

**Screenshots**
![image](https://github.com/user-attachments/assets/b01593ae-041d-4815-8206-c0f95de89658)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 119045.4717]
 - Framework/.NET Version: [e.g. 4.8] 
 - Visual Studio [2022, 17.10.5, (VB)] 
 - Toolkit Version: [e.g. 85.24.6.176]

Downgraded back to 85.24.7.204 ( no code change ) works as expected

**Comment by giduac** [comment]
Hi @MattH-Work,

Same as this issue: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1696
