### ISSUE TITLE
[Bug]:  85.24.7.204: NullReferenceException on application start

### ISSUE THREAD

**Issue by justcurious** [Krypton-Suite/Standard-Toolkit#1699]
It was working fine in Krypton Lite version 85.24.6.176. I updated all packages to 85.24.7.204 and now the app won't start. 

![image](https://github.com/user-attachments/assets/8dbff111-041c-4a06-80a3-8514d8cc292c)

These are the packages I'm using (this version works for me)
```
    <PackageReference Include="Krypton.Docking.Lite" Version="85.24.6.176" />
    <PackageReference Include="Krypton.Navigator.Lite" Version="85.24.6.176" />
    <PackageReference Include="Krypton.Ribbon.Lite" Version="85.24.6.176" />
    <PackageReference Include="Krypton.Toolkit.Lite" Version="85.24.6.176" />
    <PackageReference Include="Krypton.Workspace.Lite" Version="85.24.6.176" />
```

I've attached a simplified net8.0-windows project in VS2022 that duplicates the problem.

Windows 10 Pro, 10.0.19045 Build 19045

The only change I made between it running and not running was updating those NuGet packages.

To duplicate, build and run the solution in VS2022 and it should fail.  If you downgrade the packages to Version="85.24.6.176" it will run.

P.s. Cheers for this fantastic framework!

Also, an unrelated question: do you have any plans to release a net8.0 LTS release of the KryptonExplorer samples? I downloaded a Canary release recently and couldn't quite figure out how to get them running in my project, so reverted.  But maybe the problem is me :)

[Krypton - NullException.zip](https://github.com/user-attachments/files/16479328/Krypton.-.NullException.zip)

**Comment by Smurf-IV** [comment]
@justcurious With a few changes the following can be used as a workaround
![image](https://github.com/user-attachments/assets/5b45ba48-a868-4a60-b169-8f36a8c31f6d)

**Comment by Smurf-IV** [comment]
@wagnerp I think "85.24.7.204" should be removed from nuget and replaced with the later version that has the null fix in it (I know it hasn't been built yet!)

**Comment by Wagnerp** [comment]
> @Wagnerp I think "85.24.7.204" should be removed from nuget and replaced with the later version that has the null fix in it (I know it hasn't been built yet!)

@Smurf-IV Marked them as having 'critical bugs' & do not use.
