### ISSUE TITLE
[Bug]: Remove properties from `KryptonRichtTextBox`

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1704]
**Describe the bug**
KRTB State(*).Content objects have a property called: SynchronizeDropDownWidth.
This does not belong there and can be removed.

![image](https://github.com/user-attachments/assets/fc6f742c-0cdb-4244-88fe-e04b5f9dce0d)

**Comment by giduac** [comment]
@Wagnerp 
Oh and... if the property is serializable this might cause breakage if it's also in V85

**Comment by Wagnerp** [comment]
@giduac 

It's not in v85... v90 only

**Comment by giduac** [comment]
@Wagnerp 

Just refreshed the branch but in the krichtextbox the properties are still visible ...?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Just refreshed the branch but in the krichtextbox the properties are still visible ...?

@giduac 

From latest `alpha`

![image](https://github.com/user-attachments/assets/6ac4f96e-34ff-40df-bd0e-63b98bd090d1)

**Comment by giduac** [comment]
@Wagnerp 
Didn't rebuild ..... sorry for the commotion :)
