### ISSUE TITLE
[Other Issues]: TestForm Alpha: adding a Colors Testimonials form

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1712]
Adds a form for color testimonials.
Inverting colors at first....

Pr underway

**Comment by giduac** [comment]
This update adds NUDs for the inverted side so the color can also be set from inverted color information.
Reorganizes the layout a little.
Never mind the buttons.

![image](https://github.com/user-attachments/assets/b497f9ab-3c71-403f-afa1-40721d83a171)

**Comment by giduac** [comment]
Update:
- Added: Copies color values to the clipboard
- Added: Use hex based color codes (#FFFFFF )
- Use the `System.Windows.Forms` `Dark` & `Light` methods to make a color lighter or darker.

![image](https://github.com/user-attachments/assets/9c87ebc5-1e3d-40c1-b84c-ee4c7ea7b6ca)

**Comment by Wagnerp** [comment]
@giduac 

I did create a lot of colour controls in the ET. Might be good to see if there's any candidates that can be bought over in V100.
