### ISSUE TITLE
[Bug]: 90.24.7.204-beta:  Close Box Button not visible / CloseBox boolean resetting to false

### ISSUE THREAD

**Issue by DigitalMills** [Krypton-Suite/Standard-Toolkit#1714]
**Describe the bug**
For component KryptonForm. the Close Box property continually resets to false, and the close form button is not displayed when the form is built.

**To Reproduce**
1. In Visual Studio, for a Krypton Form, ensure CloseBox property is set to True, and Control Box is set to True:
<img width="229" alt="image" src="https://github.com/user-attachments/assets/cdc57f43-c2cc-4adf-822f-6a1a3e9f77a4">
<img width="87" alt="image" src="https://github.com/user-attachments/assets/1a395db8-fa82-4ea6-a7f4-d63e197814ce">

2. Save the form, close the designer and reopen the designer for the Krypton Form

**Expected behavior**
The close box property is still True, and the close box is present on the form

**Actual behavior**
The close box property is false, and the close box is not present on the form

<img width="104" alt="image" src="https://github.com/user-attachments/assets/84f9dced-c658-4e37-ac16-ce58f313b632">
<img width="309" alt="image" src="https://github.com/user-attachments/assets/81179ab4-de02-4c76-955e-c76767a29955">

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Business
 - Version: 10.0.22631 Build 22631
 - Framework/.NET Version: net8.0-windows
 - Toolkit Version: 90.24.7.204-beta

**Additional context**
When trying to explicitly set these properties within the generated Designer.cs class, the result is still the same, the close box still does not load at runtime.

**Comment by PWagner1** [comment]
Hi @Smurf-IV & @giduac 

Do we know when the last known working build for this was from?

cc. @DigitalMills

**Comment by DigitalMills** [comment]
Hi @Smurf-IV  / @giduac  / @PWagner1,

Is there any progress on this one please? Unfortunately it's a blocker for us at the moment.

Much appreciated

**Comment by giduac** [comment]
Hi @DigitalMills,

I cannot reproduce this on current alpha branch.
Can you please attach a simple project that exhibits the error.

Thanks.

**Comment by pinibz** [comment]
I also encountered this. It seems to be OK on new projects. The problem seems to happen when moving from 85 to 90 in an existing project. I tried nightly 267.

**Comment by giduac** [comment]
> * Toolkit Version: 90.24.7.204-beta

Hi @pinibz ,

@DigitalMills encountered this in `Toolkit Version: 90.24.7.204-beta`...
How is this triggered as I couldn't reproduce this in 239 and alpha branch?

**Comment by pinibz** [comment]
Hi

The best I can trace it is that I had a project using 85 stable. However, this version had this issue:
https://github.com/Krypton-Suite/Standard-Toolkit/issues/1785

So, following the advice I tried latest nightly which fixed this issue, but caused the close box problem which is exactly like @DigitalMills described.

**Comment by giduac** [comment]
> Hi
> 
> The best I can trace it is that I had a project using 85 stable. However, this version had this issue: #1785
> 
> So, following the advice I tried latest nightly which fixed this issue, but caused the close box problem which is exactly like @DigitalMills described.

Interesting @pinibz,

Can you please post a simple sample project that demonstrates this behaviour?

Thanks.

**Comment by pinibz** [comment]
Hi

Yes, I attached it here. 

[WindowsFormsApp1_krypClose.zip](https://github.com/user-attachments/files/17147174/WindowsFormsApp1_krypClose.zip)



it seems to happen when you move from v85 to v90.

The steps I did:

1. created a new project and added Toolkit and Ribbon stable 85 from nuget.
2. Subclassed KryptonForm and added a ribbon. I set RibbonAppButton.AppButtonVisible to false.
3. It compiled and ran OK.
4. I removed the stable v85 and replaced it with v90 with nightly v90.
5. In order for it to compile (or even open the Form in designer) I had to manualy comment out in the designer file the lines:

	this.kryptonRibbon1.AllowFormIntegrate = true;
	this.kryptonRibbon1.RibbonAppButton.AppButtonVisible = false;
	
6. Now the problem is reproduced and the CloseBox does not show even if CloseBox is set to true.
7. it does not happen on a new project using V90.

I hope you can resolve this quickly  or find a workaround as currently it is not usable.

Thanks

**Comment by giduac** [comment]
> > Hi
> > The best I can trace it is that I had a project using 85 stable. However, this version had this issue: #1785
> > So, following the advice I tried latest nightly which fixed this issue, but caused the close box problem which is exactly like @DigitalMills described.
> 
> Interesting @pinibz,
> 
> Can you please post a simple sample project that demonstrates this behaviour?
> 
> Thanks.

@pinibz, @DigitalMills,

Can you try this property:

![image](https://github.com/user-attachments/assets/e0e156b0-6823-48da-977b-67a7fa363a7c)

**Comment by giduac** [comment]
@pinibz 
A very naughty property.....

**Comment by DigitalMills** [comment]
@PWagner1  @giduac  

Can confirm that setting FormCloseBoxVisible on the KryptonRibbon component worked for me too, thanks all!

**Comment by giduac** [comment]
@DigitalMills, thanks for the feedback 👍

**Comment by jonferreira** [comment]
Took me WAY too long than it should to find this out. Crazy!
