### ISSUE TITLE
[Bug]: KryptonComboBox does not scale correct. Text becomes clipped.

### ISSUE THREAD

**Issue by PontusLindberg** [Krypton-Suite/Standard-Toolkit#1725]
Hi!

I have an issue with Krypton ComboBox height (not scaling correctly). I am running .net8 and the latest stable version of Krypton.Toolkit (85.24.6.176). I have seen the bug reported about this, but it does not seem to be fixed in the latest stable version? If not, when can I expect it to be fixed? Is there any workaround?

My form is upgraded from 4.6.1 and no problems there.

Windows version:  Windows 11 Pro, 22631.3880
Toolkit: Krypton.Toolkit (85.24.6.176)
Net. 8.0
The KCBB is placed on a panel (not inside a TableLayoutPanel)

Screenshot:
![image](https://github.com/user-attachments/assets/4a6565bf-e544-472a-9124-aacc26d0c761)

Kind regards,  Pontus

**Comment by giduac** [comment]
Hi @PontusLindberg,

There was a fix for the text being clipped in the CBB, a while ago in this issue: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1455. This fix is in the release you are using.

Is this what you are experiencing?
If not please provide some more info on how to replicate and/or a sample that demonstrates the error.

**Comment by PontusLindberg** [comment]
My problem is that the ComboBox height does not scale. As long as I stick to 100% in development and runtime, everything looks fine. If I change to 150% in runtime (I stick to 100% at development) the ComboBox height does not scale at all, so it's clipped. Other controls look fine. My form is upgraded from 4.6.1 and no problems there. I will try and recreate a ComboBox to see if that helps.

**Comment by giduac** [comment]
@PontusLindberg 

Can you please add to the topic start:
- The Windows version.
- A screenshot when the CBB is scaled.

**Comment by PontusLindberg** [comment]
Windows version: Windows 11 Pro, 22631.3880
The comboox is inside a regular Windows panel

<img width="563" alt="image" src="https://github.com/user-attachments/assets/b04c51e3-50d4-41d6-b288-76e087bbdc17">

**Comment by Smurf-IV** [comment]
Hmm, Something is amiss:
- Using todays alpha
- ![image](https://github.com/user-attachments/assets/d2dceee2-56b2-46cf-8607-c46443c26b34)
- ![image](https://github.com/user-attachments/assets/a23351a4-d3ff-473a-b07b-864c4b586fe1)
- ![image](https://github.com/user-attachments/assets/0558f6cd-0ca8-4efb-a658-4a6ccf222eef)

**Comment by Smurf-IV** [comment]
But using the nuget package "90.24.6.176" gives the messed up formatting:
- Without scaling to 200%!!
- .Net8 & 9 are messed up
  - ![image](https://github.com/user-attachments/assets/34554627-521e-450f-8a58-991da128932d)
- .Net 4.8 is fine !!
- Net 6.0 is fine !

**Comment by Smurf-IV** [comment]
@Wagnerp Just used the latest branch of V85 and it appears to work as expected.
When will the next V85 be released ?

**Comment by PontusLindberg** [comment]
This is critical for me, so I very much appreciate the info from @Smurf-IV. And I would also like to know when?

**Comment by Wagnerp** [comment]
> @Wagnerp Just used the latest branch of V85 and it appears to work as expected. When will the next V85 be released ?

@Smurf-IV 

Scheduled to be Monday
