### ISSUE TITLE
[Feature Request]: Add `ForceDesignerDPIUnaware` option

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1734]
Add `ForceDesignerDPIUnaware` option to `csproj` files

**Comment by giduac** [comment]
@Wagnerp 

Still having problems on TestForm after this change. 
When opening a KForm in the designer there's an error:

![image](https://github.com/user-attachments/assets/e5f69707-e096-427f-a761-503e6bc9289a)

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Still having problems on TestForm after this change. When opening a KForm in the designer there's an error:
> 
> ![image](https://private-user-images.githubusercontent.com/96108132/359346996-e5f69707-e096-427f-a761-503e6bc9289a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI5ODMsIm5iZiI6MTcyNDE2MjY4MywicGF0aCI6Ii85NjEwODEzMi8zNTkzNDY5OTYtZTVmNjk3MDctZTA5Ni00MjdmLWE3NjEtNTAzZTZiYzkyODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE0MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzYxNWIxYWFhZTk5ZGZhNzczODE3MGFiOWFjODZiOWY0M2YwZmYxMWUzNDZjMGE3YTI3N2E0ZTNjN2IyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AX1BRZ9wOfEY7cA8lOTXWEifmXp02OofYdsNt8izKMw)
> 
> Also happens when changing KForm to Form:
> 
> ![image](https://private-user-images.githubusercontent.com/96108132/359347731-93e289b2-c620-4a3c-965a-4972b3a848d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI5ODMsIm5iZiI6MTcyNDE2MjY4MywicGF0aCI6Ii85NjEwODEzMi8zNTkzNDc3MzEtOTNlMjg5YjItYzYyMC00YTNjLTk2NWEtNDk3MmIzYTg0OGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE0MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Yjc0ODVlYWRiMWVjYjBjY2EzMWQyYjYzYjY2MmUyZWY3M2RiODkwMWZlY2VhZTk0NTlkYWVkY2RkOWE3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6QncMzLejnZSynp2ixgceR8FcVqEah1sM3VakowllE)

@giduac 

Please try a full clean and rebuild. Might be out-of-date.

**Comment by giduac** [comment]
> > @Wagnerp
> > Still having problems on TestForm after this change. When opening a KForm in the designer there's an error:
> > ![image](https://private-user-images.githubusercontent.com/96108132/359346996-e5f69707-e096-427f-a761-503e6bc9289a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI5ODMsIm5iZiI6MTcyNDE2MjY4MywicGF0aCI6Ii85NjEwODEzMi8zNTkzNDY5OTYtZTVmNjk3MDctZTA5Ni00MjdmLWE3NjEtNTAzZTZiYzkyODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE0MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzYxNWIxYWFhZTk5ZGZhNzczODE3MGFiOWFjODZiOWY0M2YwZmYxMWUzNDZjMGE3YTI3N2E0ZTNjN2IyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AX1BRZ9wOfEY7cA8lOTXWEifmXp02OofYdsNt8izKMw)
> > Also happens when changing KForm to Form:
> > ![image](https://private-user-images.githubusercontent.com/96108132/359347731-93e289b2-c620-4a3c-965a-4972b3a848d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI5ODMsIm5iZiI6MTcyNDE2MjY4MywicGF0aCI6Ii85NjEwODEzMi8zNTkzNDc3MzEtOTNlMjg5YjItYzYyMC00YTNjLTk2NWEtNDk3MmIzYTg0OGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE0MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Yjc0ODVlYWRiMWVjYjBjY2EzMWQyYjYzYjY2MmUyZWY3M2RiODkwMWZlY2VhZTk0NTlkYWVkY2RkOWE3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6QncMzLejnZSynp2ixgceR8FcVqEah1sM3VakowllE)
> 
> @giduac
> 
> Please try a full clean and rebuild. Might be out-of-date.

Already did that....

**Comment by Wagnerp** [comment]
Hi @giduac 

Would you mind cleaning it from the `Run` script, then rebuilding, as this works for me?

**Comment by giduac** [comment]
@Wagnerp 
Thanks, that did it.

**Comment by giduac** [comment]
@Wagnerp 

Got it back again. This time cleaning won't help anymore.
Before these commits all was hunky dory....

I cant open forms from TestForm and on the right there's an exclamation mark on the Forms assembly...

![image](https://github.com/user-attachments/assets/b8ee780e-a6f5-4359-b74b-6eecf38fd67e)

**Comment by giduac** [comment]
Restoring previously made unneeded changes:

![image](https://github.com/user-attachments/assets/a769bdff-96a2-4f47-b3d0-86dd20218e9b)
