### ISSUE TITLE
[Bug]: Extended Ultimate Navigator Outlook - Full

### ISSUE THREAD

**Issue by mohatchaks** [Krypton-Suite/Standard-Toolkit#1742]
**Describe the bug**
Problem with navigator in last version ( not nightly or canary ) . also there is a lot of problem in nightly version i will try to report it

**Screenshots**
![Capture](https://github.com/user-attachments/assets/ac092ccb-52d2-4078-b2b1-69235b0bc0e5)
![Capture1](https://github.com/user-attachments/assets/25914db3-0d3e-4700-92a1-13b35644be85)
![Capture2](https://github.com/user-attachments/assets/3be5b533-868c-4788-98a6-db74750a75b1)

 screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  Windows 10]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version: 4.7.2 
 
also is there something like XtraTabbedMdiManager in krypton toolkit ?

**Comment by Wagnerp** [comment]
Hi @mohatchaks 

This is going to be rectified in the next patch of V85, due to be released on Monday.

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac 

Closing, due to duplicate as per https://canary.discord.com/channels/620577714889424916/620577714889424918/1260138689141669968

**Comment by mohatchaks** [comment]
ah there is discord didn't knew that xd

**Comment by Wagnerp** [comment]
> ah there is discord didn't knew that xd

@mohatchaks 

No problem :) are you a member of the server, as we post updates there?

**Comment by mohatchaks** [comment]
just joined right now 👍 thanks
