### ISSUE TITLE
[Bug] Rounded Form borders have "Triangles" in corners

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1749]
_Originally posted by @Smurf-IV in https://github.com/Krypton-Suite/Standard-Toolkit/issues/1271#issuecomment-2304977265_

### Expected (V85)
![image](https://github.com/user-attachments/assets/66a6c2be-4e0e-4555-ac58-6a0b27f5b26f)

### Actual (V90 alpha):
![image](https://github.com/user-attachments/assets/57ebee53-9f90-4d71-8d54-782f3ae442f6)

**Comment by Smurf-IV** [comment]
It is more "Noticeable" when rounding is increased:
![image](https://github.com/user-attachments/assets/4aee7844-fde2-48da-a7fc-f148645d5d74)

Notes:
- seems to be always a single pixel around the border
- The corner "triangles" are drawn in the equivalent of transparent, which then renders through to the desktop back theme (Not the desktop image!)

**Comment by Smurf-IV** [comment]
I have been chasing my tail on this: and it appears that my statement that it has been there a while is true.
Because settings borders to be visible (i.e.not default) also cause the triangles and the "single pixel line" to appear in V80 as well:
![image](https://github.com/user-attachments/assets/7adf6e27-8ea9-4863-97e1-461252c7fb5a)

**Comment by giduac** [comment]
@Smurf-IV 
Does it differ between themes / gets more or less worse / stays the same?
Which color does Windows use for transparency?

**Comment by Smurf-IV** [comment]
> Does it differ between themes 

Yes, as some do not have the default rounding

> gets more or less worse / stays the same? 

In v90 2They" all have the obvious small triangle without the need to force the coloured border.
Coloured borders (i.e. setting thickness and roundness to be a "Big" value" cause it to be exaggerated (As per V80 image)


> Which color does Windows use for transparency?

for NC area, it is supposed to be black, and then state it is not in clipping;
If within a form, then it can be set to a specific colour or via opaqueness.

**Comment by giduac** [comment]
This is alpha on W11

![image](https://github.com/user-attachments/assets/d3bd06c3-8944-4c08-9b47-e0224cb4dd38)

**Comment by giduac** [comment]
This is with `this.TransparencyKey = Color.Black;`

![image](https://github.com/user-attachments/assets/693ef63e-b135-4425-8d5f-db8a2be2c307)

**Comment by giduac** [comment]
Setting the TransparencyKey to Magenta or Transparent results in the black corner again

![image](https://github.com/user-attachments/assets/21fb95a0-f8a4-46a2-bdb6-d3919d64f136)

**Comment by Smurf-IV** [comment]
> This is with `this.TransparencyKey = Color.Black;`

Good find, That's a great ;-)
But, does it mean that each Theme will have to a Transparency key,  otherwise dark themes will become transparent ??

**Comment by Smurf-IV** [comment]
Anything that is not a Krypton object is then obliterated:
![image](https://github.com/user-attachments/assets/ee756c29-2272-43af-9f96-ceb58647d51a)

**Comment by giduac** [comment]
DrawString versus DrawText ?

**Comment by Smurf-IV** [comment]
Yay fixed.
Rather simpler when the "big file" is done !
Thanks @giduac for the pointer.. Just had to put it in the correct place ;-)

![image](https://github.com/user-attachments/assets/fb4a8d11-a3fe-49ba-b87f-e948e6d5cfdf)

And 
![image](https://github.com/user-attachments/assets/9392c4aa-a15b-49c6-ae34-6a65b2f210e6)

**Comment by giduac** [comment]
@Smurf-IV 
Rounding looks good now.
But, forms now have a thin magenta border...

**Comment by giduac** [comment]
@Smurf-IV 

The thin border always shows when the width is set to any value but zero.

https://github.com/user-attachments/assets/a3b2b581-e862-4a00-a23e-e0c8086129a7

**Comment by Smurf-IV** [comment]
> @Smurf-IV
> 
> The thin border always shows when the width is set to any value but zero.


Please raise another bug ;-(
