### ISSUE TITLE
[Bug]: FormBorderStyle resizing when set to fixed

### ISSUE THREAD

**Issue by KorruptEU** [Krypton-Suite/Standard-Toolkit#1751]
**Describe the bug**
When using KryptonForm and setting the "FormBorderStyle" in properties to anything other then "none" you are still able to resize the form when it should not be resizable.

**To Reproduce**
1. Go to properties with KryptonForm selected.
2. Click on the FormBorderStyle dropdown and select "FixedToolWindow".
3. run project and see if you can re-size form.

**Expected behavior**
Shouldn't be able to resize the form at all.

**Desktop (please complete the following information):**
 - OS: Windows 11]
 - Framework/.NET Version: 8
 - Toolkit Version: 90.24.7.204-beta Canary

**Comment by Smurf-IV** [comment]
@KorruptEU This does not appear to be the case in current alpha branch:
![Sizing](https://github.com/user-attachments/assets/c3608c98-4db7-48f9-a471-3a9c8f2acfad)

Can you test in a later canary or use an alpha please?
And / Or add a demo project ?

**Comment by giduac** [comment]
@KorruptEU 

FormBorderStyles are conform to: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.formborderstyle?view=windowsdesktop-8.0

You can use the ControlBox, MaximizeBox & MinimizeBox properties to assert more control over the windows behaviour the user has access to.

**Comment by KorruptEU** [comment]
> @KorruptEU This does not appear to be the case in current alpha branch: ![Sizing](https://private-user-images.githubusercontent.com/2418812/361190680-c3608c98-4db7-48f9-a471-3a9c8f2acfad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODM1MTUsIm5iZiI6MTcyNDU4MzIxNSwicGF0aCI6Ii8yNDE4ODEyLzM2MTE5MDY4MC1jMzYwOGM5OC00ZGI3LTQ4ZjktYTQ3MS0zYTljOGYyYWNmYWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTA1MzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU5NWFmOGQ3MTgwOTgyYTk2MWE4ZTA4ZGZkZDUwODNjYTViODRiMGIwYTVmMzdlMWRjOWJjMTE5ZWU5OTgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ru-SpVl_S_I4HKk7hI2hbyzWekJnPhFgI9nNYy2RWeU) [ ![Sizing](https://private-user-images.githubusercontent.com/2418812/361190680-c3608c98-4db7-48f9-a471-3a9c8f2acfad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODM1MTUsIm5iZiI6MTcyNDU4MzIxNSwicGF0aCI6Ii8yNDE4ODEyLzM2MTE5MDY4MC1jMzYwOGM5OC00ZGI3LTQ4ZjktYTQ3MS0zYTljOGYyYWNmYWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTA1MzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU5NWFmOGQ3MTgwOTgyYTk2MWE4ZTA4ZGZkZDUwODNjYTViODRiMGIwYTVmMzdlMWRjOWJjMTE5ZWU5OTgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ru-SpVl_S_I4HKk7hI2hbyzWekJnPhFgI9nNYy2RWeU) ](https://private-user-images.githubusercontent.com/2418812/361190680-c3608c98-4db7-48f9-a471-3a9c8f2acfad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODM1MTUsIm5iZiI6MTcyNDU4MzIxNSwicGF0aCI6Ii8yNDE4ODEyLzM2MTE5MDY4MC1jMzYwOGM5OC00ZGI3LTQ4ZjktYTQ3MS0zYTljOGYyYWNmYWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTA1MzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU5NWFmOGQ3MTgwOTgyYTk2MWE4ZTA4ZGZkZDUwODNjYTViODRiMGIwYTVmMzdlMWRjOWJjMTE5ZWU5OTgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ru-SpVl_S_I4HKk7hI2hbyzWekJnPhFgI9nNYy2RWeU) [ ](https://private-user-images.githubusercontent.com/2418812/361190680-c3608c98-4db7-48f9-a471-3a9c8f2acfad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODM1MTUsIm5iZiI6MTcyNDU4MzIxNSwicGF0aCI6Ii8yNDE4ODEyLzM2MTE5MDY4MC1jMzYwOGM5OC00ZGI3LTQ4ZjktYTQ3MS0zYTljOGYyYWNmYWQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTA1MzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU5NWFmOGQ3MTgwOTgyYTk2MWE4ZTA4ZGZkZDUwODNjYTViODRiMGIwYTVmMzdlMWRjOWJjMTE5ZWU5OTgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ru-SpVl_S_I4HKk7hI2hbyzWekJnPhFgI9nNYy2RWeU)
> 
> Can you test in a later canary or use an alpha please? And / Or add a demo project ?

I am using the later canary, i removed that and tried the alpha(nightly)80.22.12.347-alpha and done what you have done above however im still getting the same result, ie being able to rezise the form.
These are the packages i have installed 
![image](https://github.com/user-attachments/assets/5f3bec4e-5505-4587-b840-d3a947245d31)

**Comment by KorruptEU** [comment]
@Smurf-IV It seems its working when i change controlbox to true from false, thanks anyway. guess resolved.
