### ISSUE TITLE
[Question]: UseThemeFormChromeBorderWidth appears to have no effect

### ISSUE THREAD

**Issue by EliotVU** [Krypton-Suite/Standard-Toolkit#1758]
**Describe the bug**
The UseThemeFormChromeBorderWidth appears to have no effect, on or off.

**Screenshots**
![image](https://github.com/user-attachments/assets/b529897f-0e41-4136-a957-e30a5075bcfa)

As you can see, a wide border remains regardless of the theme settings. Also the window close and minimize buttons are messed up (not seen in the screenshot)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - .NET Version: [8.0] 
 - Toolkit Version: [90.24.8.240-alpha]

**Comment by giduac** [comment]
@PWagner1 & @Smurf-IV 

What is the expected behaviour for this property?

**Comment by giduac** [comment]
@PWagner1 & @Smurf-IV

What is the expected behaviour for this property?

**Comment by PWagner1** [comment]
> @PWagner1 & @Smurf-IV
> 
> What is the expected behaviour for this property?

@giduac 

I think it's supposed to adjust the border width based on the theme, @Smurf-IV may know more

**Comment by Smurf-IV** [comment]
This was a feature request to use the default Windows OS theme border. To help in the move towards FluentUI really thin borders applied to the OS:
![ChromBorder](https://github.com/user-attachments/assets/79b62545-837b-42b0-a3a7-cc8ad53d5fd9)

**Comment by EliotVU** [comment]
Thanks for the effort, but I'm still struggling to get rid of the padding around the MainForm even with the "fix", while the "Width" does now have an effect, however setting it to -1 or 0 does not remove the padding that between the `Form` and the `StatusStrip`

Example (including Notepad for comparison):
![image](https://github.com/user-attachments/assets/638a46ac-a7f1-4604-9e2e-47c62cd3341c)

**Comment by Smurf-IV** [comment]
@EliotVU The Status strip padding is another issue, and will need a separate investigation.
Please raise as such - Thanks

**Comment by EliotVU** [comment]
@Smurf-IV Done! #1807
