### ISSUE TITLE
[Feature Request]: Colours for `KryptonRibbon` contexts need sorting out

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1765]
Building on top of the fixes made in #1715, the colours for `KryptonRibbon` contexts need sorting out

Edit from Giduac:
Also takes this along:
https://github.com/Krypton-Suite/Standard-Toolkit/pull/1764#issuecomment-2335990578

**Comment by giduac** [comment]
@PWagner1 
Can this please be sorted before we get (bug)tickets from this..?
