### ISSUE TITLE
[Bug]: `KryptonThemeComboBox` crashes on scrolling

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1766]
While testing the fix for #1715, I noticed that if you use the keyboard arrows to scroll through the `KryptonThemeComboBox`, it will crash the application.

![KTCB](https://github.com/user-attachments/assets/abca69d6-65ca-46cd-b607-411df00003fc)

**Comment by giduac** [comment]
@PWagner1 

Tried that on my "old branch" from 2 weeks ago, which was also used yesterday to 1715 fixed, and the error is not in there...

Best to first find the commit from where this originates...

**Comment by giduac** [comment]
14 days ago was around this commit (the same as yesterday) 
`c7499ffb8dc416797696b8831c9473cdceb5d92e`

**Comment by PWagner1** [comment]
> 14 days ago was around this commit (the same as yesterday) `c7499ffb8dc416797696b8831c9473cdceb5d92e`

@giduac 

Not linked?

**Comment by giduac** [comment]
@PWagner1 

This one's yours... ;)

**Comment by PWagner1** [comment]
> @PWagner1
> 
> This one's yours... ;)

@giduac 

Do we know where the last known working build was, so I can go back and work forward?

**Comment by giduac** [comment]
14 days ago was around this commit (the same as yesterday) 
**_c7499ffb8dc416797696b8831c9473cdceb5d92e_**

**Comment by PWagner1** [comment]
Cannot replicate on latest `alpha`, closing...
