### ISSUE TITLE
[Bug]: After the fix of 1715, colours have to be assigned to the newly added states

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1769]
**Describe the bug**
Refer to https://github.com/Krypton-Suite/Standard-Toolkit/issues/1715 for the newly added states

**Comment by giduac** [comment]
There was an FR created which I overlooked.

**Comment by PWagner1** [comment]
@giduac 

> There was an FR created which I overlooked.

No problem, I thought it would be better to spit it into 2 items
