### ISSUE TITLE
[Bug]: kryptonRibbon MDI opens the child form, maximizes it, and then closes it,causing some unexpected effects

### ISSUE THREAD

**Issue by rollyfy** [Krypton-Suite/Standard-Toolkit#1770]
**Describe the bug**
1.kryptonRibbon+MDI 
Krypton.Ribbon version="85.24.8.239"
Krypton.Toolkit version="85.24.8.239"

2.Open three child forms in sequence while maximizing
  2.1.When a child form is opened or closed, the upper end of the parent form blinks, Repeat title display
![image](https://github.com/user-attachments/assets/c230ea93-3261-49c0-81c2-8e49f325763e)

  2.2.After closing the child forms in turn, the following appears

![image](https://github.com/user-attachments/assets/e3a933cf-901b-4995-9ee8-dff98e45cc2a)

**Comment by rollyfy** [comment]
<package id="Krypton.Ribbon" version="85.24.8.239" targetFramework="net48" />
  <package id="Krypton.Toolkit" version="85.24.8.239" targetFramework="net48" />

**Comment by rollyfy** [comment]
Krypton.Ribbon" version="85.24.8.239" targetFramework="net48"
Krypton.Toolkit" version="85.24.8.239" targetFramework="net48"

**Comment by giduac** [comment]
hi @rollyfy,

Thanks for posting.

Can you please include a sample project that demonstrates the error so we are all on the same page.

Ty.

**Comment by rollyfy** [comment]
demo
[WindowsFormsApp1.zip](https://github.com/user-attachments/files/17000360/WindowsFormsApp1.zip)

**Comment by PWagner1** [comment]
Hi @rollyfy 

This has been addressed in V90. Due to the amount of code changes required, it cannot be backported to V85.

cc. @giduac

**Comment by giduac** [comment]
Hi @PWagner1 & @rollyfy 

Can this be closed then ?

**Comment by PWagner1** [comment]
> Hi @PWagner1 & @rollyfy
> 
> Can this be closed then ?

Yes
