### ISSUE TITLE
[Bug]: .NET 9 RC 1 throws WFO1000

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1771]
After installing  .NET 9 RC 1, building now throws WFO1000. Details [here](https://www.c-sharpcorner.com/article/property-x-does-not-configure-the-code-serialization-for-its-property-content/).

**Comment by PWagner1** [comment]
@Smurf-IV & @giduac 

Should I set all affected properties to

```cs
[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
```

**Comment by giduac** [comment]
How many errors are there when you run a full build?

**Comment by PWagner1** [comment]
> How many errors are there when you run a full build?

Around 300+

**Comment by giduac** [comment]
@PWagner1  & @Smurf-IV 
No time now as I need to install a VS Preview release for that.

Also there are more breaking changes which we need to have a good look at. Possibly resulting in more actions/work toward DN9 RTM.
[https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0](https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0)

I suggest to disable the warning for now and have a look later on or when DN9-RC2 will be ready

**Comment by giduac** [comment]
Will further be handled in: [ https://github.com/Krypton-Suite/Standard-Toolkit/issues/1777](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1777)
