### ISSUE TITLE
[Discussion]: Evaluate .NET 9 Release Candidates and General Availability Release Breaking Changes

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1777]
Evaluate breaking changes for DN9:
- [https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0](https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0)
- https://devblogs.microsoft.com/dotnet/dotnet-9-rc-2/

**Investigate the remediation of warning WFO1000**
**Will be handled in Issue <https://github.com/Krypton-Suite/Standard-Toolkit/issues/1840>**
> The .NET error WFO1000 was introduced in .NET 9 RC-1 and occurs primarily in WinForms applications. It signifies that a property within a component is not properly configured for serialization. This issue arises when properties lack appropriate serialization attributes, causing the application to throw the error during compilation.

- The above points to the fact that each affected property needs to be inspected and that the solution below does not fit each occurrence of WFO1000.
- So some properties might be made hidden other need to receive proper serialization and reset routines and DefaultValues to remove the error.
- WFO1000 seems to be undocumented.
https://github.com/dotnet/docs/issues/42724
- Currently the info on the web is very limited.
- Possible solution https://www.c-sharpcorner.com/article/property-x-does-not-configure-the-code-serialization-for-its-property-content/
- Can a single change for all affected properties be applied or are multiple scenarios possible?
- [dotnet-sdk-9.0.100-rc.2.24470.13 Some Winfroms Apps build with error: Property 'XXX' does not configure the code serialization for its property content](https://github.com/dotnet/winforms/issues/12220) 
- [New security analyzers](https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/security-analyzers)

The DesignerSerializationVisibility enum in .NET is used to control how a property or event is serialized by the designer (like the Visual Studio designer) into the source code. It has three options:

**Visible (DesignerSerializationVisibility.Visible):**
The property or event is serialized by the designer.
This is the default setting and is used for properties that should appear in the designer’s generated code.
When set to Visible, the designer serializes the property's value, enabling it to be saved in the form's code and restored at runtime.

**Hidden (DesignerSerializationVisibility.Hidden):**
The property or event is not serialized by the designer.
Properties set to Hidden are ignored by the designer, meaning their values will not be saved to the form’s generated code, even if you set them in the designer.
This setting is used for properties that are calculated or transient, or for those that don’t need to be persisted.

**Content (DesignerSerializationVisibility.Content):**
The designer serializes the contents of the property, rather than the property itself.
This is typically used for complex properties like collections or custom types with nested properties. When set to Content, the designer serializes each item or subproperty within the property instead of the entire property.
This is useful for properties that contain a collection of items (e.g., a list of buttons within a panel), allowing each item to be individually serialized.

**Winforms: BindingSource.SortDescriptions doesn't return null**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/sortdescriptions-return-value
***- No occurrences found in the source.***

**Changes to nullability annotations (Windows Forms)**
- V100 Handled in PR #1875 
- V95 later on
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/nullability-changes
- Two occurrence found and both pass a valid reference.

**********
**********
**ComponentDesigner.Initialize throws ArgumentNullException**
- https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.design.componentdesigner.initialize?view=windowsdesktop-8.0
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/componentdesigner-initialize
- Multiple occurrences found in Standard and some in Extended do a search in files using Notepad++ with search term (".Initialize(").
***- No occurrences found in the source.***

**DataGridViewRowAccessibleObject.Name starting row index**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/datagridviewrowaccessibleobject-name-row
***- No occurrences found in the source.***

**IMsoComponent support is opt-in**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/imsocomponent-support
- Not sure if any of this is applicable to the Toolkit or even would pose a problem.
***- No occurrences found in the source.***

**New Security Analyzers**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/security-analyzers
***- No occurrences found in the source.***

**No exception if DataGridView is null**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/datagridviewheadercell-nre
***- No occurrences found in the source.***

**PictureBox raises HttpClient exceptions**
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/9.0/httpclient-exceptions
- Not sure if loading remote images using a PictureBox component is used within the Toolkit?
***- No occurrences found in the source.***

**Comment by giduac** [comment]
@Smurf-IV, @PWagner1 & @Ahmed-Abdelhameed,

I'm getting reluctant to go full throttle on .NET 9 RC1 at this point. 
https://github.com/dotnet/sdk/issues/43339

I think we should evaluate the breaking changes and see what needs to be done on toolkit and can prepare what is possible ahead of RC2.

From there we wait until RC2 is released to see if that proves stable.

**Comment by Smurf-IV** [comment]
> From there we wait until RC2 is released to see if that proves stable.

Agreed.

**Comment by giduac** [comment]
Hi @PWagner1, @Smurf-IV & @Ahmed-Abdelhameed,

I've updated the topic start with my findings so far.

Can you all please evaluate the Breaking changes for yourselves and see what needs to be done?

**Comment by giduac** [comment]
Hi @PWagner1, @Smurf-IV & @Ahmed-Abdelhameed,

I've updated the topic start with my findings so far.

Can you all please evaluate the Breaking changes for yourselves and see what needs to be done?

**Comment by giduac** [comment]
@PWagner1 @Smurf-IV @Ahmed-Abdelhameed,

Topic start updated...

**Comment by PWagner1** [comment]
Only the two highlighted

**Comment by giduac** [comment]
Checks for DN9 breaking changes have been completed.
Two PRs need to be added to V95 as soon as V100 PRs prove to be correct.

We'll check on that later in December so we can get it in V95 Patch 1.
