### ISSUE TITLE
[Bug]: Many controls are missing if the project is .NET 5/6

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#178]
**Describe the bug**
If you install the NuGet package in a project using .NET 5/6, half of the controls are missing.

**Workaround:** Configure projects to use `net48` to get access to the full toolkit suite.

Needs to be investigated.

**Comment by Smurf-IV** [comment]
Is this applicable to Alpha ?

**Comment by Wagnerp** [comment]
> Is this applicable to Alpha ?

Yes, though I don't know if this is a VS issue?

**Comment by Smurf-IV** [comment]
If you set the Palette Designer to be just 
`<TargetFramework>net5.0-windows</TargetFramework>`
Then none of the control from the linked Krypton projects show in the Toolbox

**Comment by Smurf-IV** [comment]
#104

**Comment by Smurf-IV** [comment]
Because of the following statement
``` c#
internal static class FXAssembly
{
    // NB: this must never-ever change to facilitate type-forwarding from
    // .NET Framework, if those are referenced in .NET project.
     internal const string Version = "4.0.0.0";
}
```
Taken from Winforms (5 or 6) Github `$\src\System.Windows.Forms\src\AssemblyRef.cs`

I wonder if the workarounf that MS have done, is to force the designers and the resources into a .net48 framework dll only !!

**Comment by Smurf-IV** [comment]
@Wagnerp Just spitballing an idea..
How easy is it for Nuget to
1) gacutil a dll ?
2) copy a dll into a protected area
3) copy a dll into a %user% directory that is specific to the Visual studio version loading it
4) add a reference to a dll that only is to be used in visual studio and not the deliverable build target directories

Like I said, just chucking things in the air to see what happens ;-)

**Comment by Wagnerp** [comment]
@Smurf-IV 

Might need looking into, could ask on forums

**Comment by Wagnerp** [comment]
@Smurf-IV Had an idea, as this might be impossible to do via NuGet, what if on every build it generates a zip file containing the DLLs and a batch file to gacutil the DLLs?

**Comment by Smurf-IV** [comment]
Why a zip ?
And another thing 
5) if a dll is only going to be used for Resource - Designer work, then it needs to be marked as such in the proj file (Similar to how analyzers are added)

**Comment by Wagnerp** [comment]
> Why a zip ?
> And another thing
> 5) if a dll is only going to be used for Resource - Designer work, then it needs to be marked as such in the proj file (Similar to how analyzers are added)

Can distribute the zip files on the `Releases` page if the developer decides not to use NuGet

**Comment by Smurf-IV** [comment]
Creating a separate "Designer only code dll" (ala original krypton 4.x) and setting it as only /net48/ does not work
- It will not load into a .net5 only project !!
- Visual Studio recognises the Designer code
- Visual studio then states that they are not applicable to the TFM in use !!!!!!!

ugg.
Ok, fix something else whilst I think again about this

**Comment by Smurf-IV** [comment]
This is still a problem when project is `.net5-windows` and opening in vs2019 16.11.xx

**Comment by Smurf-IV** [comment]
Whilst investigating #742 in VS2022.preview3.1
I am getting the following overrides in the deiisgner verbose output:
![image](https://user-images.githubusercontent.com/2418812/172791737-7ee60e97-9013-4ae1-bf4e-f1397d68cd80.png)

**Comment by jgreywolf** [comment]
Question - would this be at all related to an issue where during runtime the control does not appear at all?  As in, new solution using net 6.0, form inherits from KryptonForm, add any Krypton component - run program, no controls visible

**Comment by Smurf-IV** [comment]
> Question - would this be at all related to an issue where during runtime the control does not appear at all? As in, new solution using net 6.0, form inherits from KryptonForm, add any Krypton component - run program, no controls visible

No, not seen that happen.

**Comment by jgreywolf** [comment]
> > Question - would this be at all related to an issue where during runtime the control does not appear at all? As in, new solution using net 6.0, form inherits from KryptonForm, add any Krypton component - run program, no controls visible
> 
> No, not seen that happen.

FYI - I started a new project and installed the 65.22.4.94 version of the package(s), and now this is not happening
