### ISSUE TITLE
[Bug]: KForm borders incorrect

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1783]
[**Describe the bug**
see: [https://github.com/Krypton-Suite/Standard-Toolkit/pull/1782#issuecomment-2367371932](https://github.com/Krypton-Suite/Standard-Toolkit/pull/1782#issuecomment-2367371932)

**Comment by Smurf-IV** [comment]
It appears that the 2 issues that are mentioned:
- Grey around title bar
- White border
Have been there for a very long time:
![image](https://github.com/user-attachments/assets/a02d9853-6044-447e-ac0d-e5973b1939b3)

**Comment by Smurf-IV** [comment]
And it's even worse in the "Old" version, when `Draw: False` is used:
![image](https://github.com/user-attachments/assets/569bc21a-9a03-47df-85c3-f80cf41e5005)

Whereas the current alpha does have that part "Sorted":
![image](https://github.com/user-attachments/assets/64906147-8f60-4f06-9f17-597c9cfe6a8c)

**Comment by Smurf-IV** [comment]
Workaround for the whiteline issue:
- Set the Width to be **-2**

![image](https://github.com/user-attachments/assets/adbde68e-0201-41b0-98d5-ec6458742c85)

**Comment by Smurf-IV** [comment]
Workaround for the Left bit of grey:
- Rounding must be -1
- Width must be 0
- DrawBorder must be Bottom, left, Right

![image](https://github.com/user-attachments/assets/4fd64263-b015-41f0-a862-73318b6950b2)

**Comment by Smurf-IV** [comment]
FYI: The "Grey Lines appear for the Office2010 derived themes.
I'm Checking the others
![image](https://github.com/user-attachments/assets/8f0d4150-5d5a-4a78-a558-35dc19af9701)

**Comment by Smurf-IV** [comment]
V95 PR incoming
