### ISSUE TITLE
[Question]: QA buttons are not placed on Form caption when maximized

### ISSUE THREAD

**Issue by pinibz** [Krypton-Suite/Standard-Toolkit#1785]
Hi

Using latest version of KryptonRibbon, Krypton form, when the app window is maximized, the QA buttons are placed in a bar bellow the caption.

When the window is not maximized, the QA buttons appear on the caption as it should.

this was reproduced with a simple test app as you can see.

Maximized
![kr_max](https://github.com/user-attachments/assets/5e5aa9a6-fe54-4485-9551-76a597d9391a)

Normal
![kr2](https://github.com/user-attachments/assets/7af532a4-b227-4414-82b8-e5b41fd23423)

Is this a bug?

thanks

**Comment by pinibz** [comment]
Now I see that this is a known issue that was discussed before.
I am using version 85.24.8.239, still no fix for this?

**Comment by PWagner1** [comment]
> Now I see that this is a known issue that was discussed before. I am using version 85.24.8.239, still no fix for this?

Hi @pinibz 

Would you mind testing the latest `canary` please, as we've made some changes in V90 that should negate this?

**Comment by pinibz** [comment]
Hi
Just tested it and it seems to work OK. i.e. when maximized the QA buttons are on the caption as they should.

1. There is a purple border around the the form Window.
2. Is it safe to use this version in a large project?
thanks

**Comment by PWagner1** [comment]
> Hi Just tested it and it seems to work OK. i.e. when maximized the QA buttons are on the caption as they should.
> 
> 1. There is a purple border around the the form Window.
> 2. Is it safe to use this version in a large project?
>    thanks

Hi @pinibz 

The purple border is a known bug and has been fixed in the latest `nightly` build. The final V90 build is set to release to the public on November 12, but `canary` should be safe to use.

**Comment by pinibz** [comment]
Hi
Thanks for your help. When will the nightly be pushed to canary?

**Comment by PWagner1** [comment]
> Hi Thanks for your help. When will the nightly be pushed to canary?

Hi @pinibz 

The next planned release for `canary` is 21st October. Please see this [article](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Package%20Version%20Descriptions.html) for release cadence details.
