### ISSUE TITLE
[Bug]: Office 2k10 & 2k7 Silver (Dark Mode) Ribbon hovered button text is hard to read

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1787]
Using todays alpha:

2k10:
![image](https://github.com/user-attachments/assets/dfe0e588-6e51-4c36-83e4-873ef73030b8)

2k7:
![image](https://github.com/user-attachments/assets/dd687bb8-66a7-43a3-a5d9-37b73818638f)

**Comment by PWagner1** [comment]
Is this linked https://github.com/Krypton-Suite/Standard-Toolkit/issues/1326?

**Comment by Smurf-IV** [comment]
> Is this linked #1326?

Probably will have an impact.

**Comment by Smurf-IV** [comment]
FYI with V85:
2k10:
![image](https://github.com/user-attachments/assets/34e73d35-c2e4-40ba-ad81-2ee2bc8c8712)


2k7:
![image](https://github.com/user-attachments/assets/cdfa5172-40e3-42dc-8ad4-5f63e7c66ffc)
