### ISSUE TITLE
[Question]:  how to put "close button" inside the docking tab ?

### ISSUE THREAD

**Issue by blackholeearth** [Krypton-Suite/Standard-Toolkit#1797]
how to enable close button inside the docking tab ?
 
-------- **SOLVED** : -> [HERE](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1797#issuecomment-2404548312) --------

![trying to put close button here](https://github.com/user-attachments/assets/bf18f935-fd6d-4f97-89ed-9872e59637b8)

 

İm using demo repo:   Docking customized example.... 
https://github.com/Krypton-Suite/Standard-Toolkit-Demos/blob/master/Source/Krypton%20Docking%20Examples/Docking%20Customized/

**Comment by giduac** [comment]
Hi @blackholeearth,

Can you please post a simple sample program that demonstrates the error.

Thnaks.

**Comment by PWagner1** [comment]
Hi @blackholeearth 

Please have a look at the `ContextLogic` property

**Comment by blackholeearth** [comment]
I Searched this  repo for ContextLogic .
0 result coming up ??

**Comment by giduac** [comment]
So it's working now on your side?

**Comment by PWagner1** [comment]
@blackholeearth What control are you using?

**Comment by giduac** [comment]
@PWagner1 

His approach produces the question already and a screenshot won't cut it in this case.
@blackholeearth should provide a simple example to take out all the guess work....

**Comment by Smurf-IV** [comment]
> how to enable close button inside the docking tab ?


The following example code will allow "any" ButtonSpec to be used (i.e. one of them is a `close`):
![image](https://github.com/user-attachments/assets/b5ed2b7e-98a1-4cb0-8fa7-05cb96dcb73c)

**Comment by blackholeearth** [comment]
İm using demo repo:   
Docking customized example....

https://github.com/Krypton-Suite/Standard-Toolkit-Demos/blob/master/Source/Krypton%20Docking%20Examples/Docking%20Customized/

![image](https://raw.githubusercontent.com/Krypton-Suite/Standard-Toolkit-Demos/refs/heads/master/Source/Krypton%20Docking%20Examples/Docking%20Customized/example.png)

![Screenshot_20241006_110300_Opera](https://github.com/user-attachments/assets/72d2e29d-8dde-4f3e-8c6d-dc757c855684)

-----


**Sorry** for the guess work;;
i forgot that this repo has other controls. 
 
Because i was so focused on the docking , İ assumed " you would instantly understand me."

**Comment by PWagner1** [comment]
Hi @blackholeearth 

Have you looked at the `ButtonSpec` properties?

**Comment by blackholeearth** [comment]
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Docking/Krypton%20Docking%20Flags.html

İ think i found it.

**DockingAllowClose**
This flag causes a close button to appear on the page header. 


------ Or this ----

**Buttonspec** property you mentioned..

![ Buttonspec property..]( https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Docking/DockFlags1.png )

**Comment by PWagner1** [comment]
Hi @blackholeearth 

Just curious, what version of the toolkit are you currently using?

**Comment by blackholeearth** [comment]
*sorry for delayed response. was sick for couple of days.*

![close button finally](https://github.com/user-attachments/assets/0bb8238c-da6c-4244-9cb1-04bf7d86f6f3)
buttonspec   and per-tab example got in the right path. got it working.
i used the demo Project: "docking Customized"  . modified on it.

this code is added into the form1_load
````csharp

//page2
var kpage2 = NewDocument();
//buttonSpec puts close button, 
ButtonSpecAny bsa2 = new ButtonSpecAny();
bsa2.Style = PaletteButtonStyle.FormClose;
bsa2.Type = PaletteButtonSpecStyle.FormClose;
bsa2.Tag = "";
bsa2.Click += (s1, e1) => { kryptonDockingManager.RemovePage(kpage2, true); };
kpage2.ButtonSpecs.Add(bsa);

kryptonDockingManager.AddToWorkspace("Workspace", new[] { kpage1, kpage2, NewDocument(), });
````

**Comment by blackholeearth** [comment]
i think i will use this style. looks better, less warningy

 ![close button better](https://github.com/user-attachments/assets/20d165a2-ec0d-458c-8baa-34dec4bca37b)

**Comment by blackholeearth** [comment]
----

**one question.??**  
can we make this  click_event   free from external referance.  ("kryptonDockingManager" and kpage2)

current:
`bsa2.Click += (s1, e1) => { kryptonDockingManager.RemovePage(kpage2, true); };`

what i expect:
` bsa2.Click += (s1, e1) => { (KryptonPage )s1.close() }; `

if possible dont event wantt to write click event.?

----

> Just curious, what version of the toolkit are you currently using?

i am using the latest one, from the demo repository  . vs2019 , net4.8

**Comment by giduac** [comment]
Looks answered, so closing...
