### ISSUE TITLE
[Bug]: KryptonDataGridViewButtonColumn looks disabled but it is clickable (but greyed out)

### ISSUE THREAD

**Issue by deemuzi** [Krypton-Suite/Standard-Toolkit#1806]
KryptonDataGridViewButtonColumn looks disabled but it is clickable (but greyed out). Buttons are Enabled=true and ReadOnly=false. Data is binded using BindingSource

![kr2](https://github.com/user-attachments/assets/349e77af-7951-48c7-a87e-e5ed7cfac26d)
![kr1](https://github.com/user-attachments/assets/89368544-73f7-4162-a7f9-ec3ba73dbbf5)

**Comment by Smurf-IV** [comment]
I feel like this is a duplicate, I'll check at the weekend if no one finds it in the meantime

**Comment by giduac** [comment]
KryptonDataGridView and it components have several shortcomings which we will try to address in the V100 release or earlier if possible.

**Comment by giduac** [comment]
Hi @deemuzi,

Can you please update the topic start and the Toolkit version you are using?
Thanks.

**Comment by giduac** [comment]
Hi @deemuzi,

I tried this with Toolkit V90.24.9.267-beta and the used the settings form your screenshot.
This works fine on this side.

Can you please add a simple program that demonstrates the error.
That makes it easier so we don't have to explore all avenues of where it might come from...
Thanks.

**Comment by giduac** [comment]
Hi @deemuzi,

I tried this with Toolkit V90.24.9.267-beta and the used the settings form your screenshot.
This works fine on this side.

Can you please add a simple program that demonstrates the error.
That makes it easier so we don't have to explore all avenues of where it might come from...
Thanks.

**Comment by giduac** [comment]
Cannot reproduce.
No further response to our questions from the reporter.
Issue will be closed.
