### ISSUE TITLE
[Bug]: ChromeBorderWidth and Padding

### ISSUE THREAD

**Issue by EliotVU** [Krypton-Suite/Standard-Toolkit#1807]
**Describe the bug**

While the Chrome's border width can be adjusted, there is an apparent intrinsic padding between that of the border and the form's content which cannot be changed.

**Screenshots**

Example (including Notepad for comparison):
![image](https://github.com/user-attachments/assets/638a46ac-a7f1-4604-9e2e-47c62cd3341c)

**Desktop**
 - OS: Windows 10
 - .NET Version: 8.0
 - Toolkit Version: 90.24.10.275-alpha

**Comment by Smurf-IV** [comment]
I'll **not** fix this in V85, as there is a reason why the ChromeStuff option was removed in V90.

**Comment by Smurf-IV** [comment]
Nearly there:
![image](https://github.com/user-attachments/assets/e8609e60-43c2-4ff8-9ec3-91f5d5750373)
Shows the sides are the border size set, in the designer (Can even be "0")
But the Status bar is still "Lifted" !

**Comment by Smurf-IV** [comment]
**0:**
![image](https://github.com/user-attachments/assets/90c4c65f-d472-49b7-988c-e2c54844f325)


**10:**
![image](https://github.com/user-attachments/assets/fd567f82-d12e-4d07-9e55-58cd651c772a)


Or even a crazy **20:**
![image](https://github.com/user-attachments/assets/223b9dd1-1e51-4d1c-bd4c-30232468ba2b)


I think it looks way better now, BUT this has thrown a few issues for the Theme border colouring, which might prompt a revisit
