### ISSUE TITLE
[Bug]: Form ControlBox does not look native

### ISSUE THREAD

**Issue by EliotVU** [Krypton-Suite/Standard-Toolkit#1810]
**Describe the bug**

The Minimize, Maximize, and Close button of the Form's so called ControlBox do not appear to be rendered in accordance with operating system.

**Expected behavior**

The buttons should look like native to the operating system as seen in the screenshot below.

**Screenshots**

The first control box is the native one for Windows 10 (Notepad), the second control box is Krypton.
![GIF 7-10-2024 22-09-54](https://github.com/user-attachments/assets/b803f70d-443d-41db-9811-6ed5290f32fd)

**Desktop**
 - OS: Windows 10
 - .NET Version: 8.0
 - Toolkit Version: 90.24.10.275-alpha

**Comment by Smurf-IV** [comment]
All form elements are themed

**Comment by PWagner1** [comment]
Hi @EliotVU 

`KryptonForm`s are themed, so they don't follow the system design, so it's not a bug :)

**Comment by giduac** [comment]
Only way to mix this is to use a normal `Form` and place `KryptonPanel` on it.
Form border and title bar incl control buttons will not be themed of course.

That's as good as it gets.
