### ISSUE TITLE
[Other Issues]: Workaround for designer issues is not practical

### ISSUE THREAD

**Issue by ICloneableX** [Krypton-Suite/Standard-Toolkit#1817]
In the [documentation](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html), it says that to avoid issues with the designer, one should replace 

```xml
<TargetFramework>net[##Current-Version##]-windows</TargetFramework>
```

with

```xml
<TargetFrameworks>net481;net[##Current-Version##]-windows</TargetFrameworks>
```

However, this workaround is not practical except for very simple programs. If the program has any code or reference that is not supported in .NET Framework, the project will not compile.

Is there any other way to be able to use the designer in a .NET 8.0+ project?

**Comment by PWagner1** [comment]
Hi @ICloneableX 

Thanks for the post. Unfortunately there is no other workaround, until Microsoft fixes the designer for .NET. Until this happens, there is  no other option.
