### ISSUE TITLE
[Bug]: When adding a Ribbon, the border is hidden and the form title bar has no theme.

### ISSUE THREAD

**Issue by lesandrog** [Krypton-Suite/Standard-Toolkit#1819]
**Describe the bug**
When adding a Ribbon, the border is hidden and the form title bar has no theme.

**To reproduce**
I created a Windows Form project in Visual Basic.
Add a form and a ribbon to it.
Set a theme.

**Expected behavior**
The form has no border and the form title bar has no theme.

**Screenshots**
![image](https://github.com/user-attachments/assets/229d3f5b-425a-47ce-87e4-949ec825b45f)
[WindowsApp3.zip](https://github.com/user-attachments/files/17396745/WindowsApp3.zip)

**Desktop (fill in the following information):**
- OS: Windows 10
- Version: 22h2 19045.5011
- Framework/.NET version: 4.8
- Toolkit version: 85.24.10.288
- Ribbon version: 85.24.10.288

**Additional context**
The problem occurs with versions 80.23.11.318 ~ 85.24.10.288.
In versions 70.22.11.312 and 90.24.9.267-beta, the problem does not occur.

**Comment by lesandrog** [comment]
It seems to be the same issue #1572.

**Comment by PWagner1** [comment]
Hi @lesandrog 

This will be fixed in a few weeks time with V90
