### ISSUE TITLE
[Bug]: KryptonDataGridView does not add Krypton Columns on Auto Generate

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1820]
**Describe the bug**
The KDGV does not add krypton columns when AutoGenerate is set.

The PR connected corrects this.

A new property is added: `AutoGenerateKryptonColumns`

When `AutoGenerateColumns `is set and `AutoGenerateKryptonColumns` is set (this the default) Krypton based columns are used for auto generation.

Version 90 for now.

**Comment by PWagner1** [comment]
@giduac 

Can this be closed?

**Comment by giduac** [comment]
@PWagner1 
Naah, not yet, will have look later on to put it in V85

**Comment by giduac** [comment]
For V85 also completed.
