### ISSUE TITLE
[Question]: Beginner Question

### ISSUE THREAD

**Issue by 5yazza** [Krypton-Suite/Standard-Toolkit#1830]
Hi, im a very beginner in visual basic and i want to download and add these krypton toolbox component in my vb.net, can anyone assist me step by step?

**Comment by PWagner1** [comment]
Hi @5yazza 

I would suggest that you read through the [documentation](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/intro.html) first.
