### ISSUE TITLE
[Bug]: Setting `KryptonTextBox.Multiline` to true shrinks the textbox's height to zero

### ISSUE THREAD

**Issue by ICloneableX** [Krypton-Suite/Standard-Toolkit#1842]
**Describe the bug**
When the `Multiline` property of `KryptonTextBox` is set to true (in the designer), the textbox essentially disappears because its height is set to 0.

**To Reproduce**
1. Add a `KryptonTextBox` control to the form.
2. From the Properties window, set the `Multiline` property to true.
3. The `KryptonTextBox` will no longer be visible on the form because it now has a height of 0.

**Expected behavior**
The control's height should remain the same.

**Desktop:**
 - OS: Windows 10
 - Framework/.NET Version: .NET 8.0
 - Toolkit Version: 85.24.10.288

**Work around**
Set the `MinimumSize` to the same values as `Size` property before enabling `MultiLine`.

**Comment by giduac** [comment]
Confirmed.
Tested V90 RTM which has it also. So V85 / V95 / V100 need fixing.

**Comment by giduac** [comment]
Added workaround to the topic start.

**Comment by giduac** [comment]
In `KryptonTextBox.cs`  needs altering of method `AdjustHeight`

```cs
        private void AdjustHeight(bool ignoreAnchored)
        {
            // If any of the vertical edges are anchored then we might need to ignore the call
            if (!ignoreAnchored || ((Anchor & (AnchorStyles.Bottom | AnchorStyles.Top)) != (AnchorStyles.Bottom | AnchorStyles.Top)))
            {
                // If auto sizing the control and not in multiline mode then override the height
                //Height = _autoSize && !Multiline ? PreferredHeight : _cachedHeight;

                // #1842 when autosize == true and MultiLine is true and the _cachedHeight == -1 which is the initial value
                // the box collapses. Only when _cachedHeight > -1 it will be assigned. Otherwise Height is left alone.
                if (_autoSize && !Multiline)
                {
                    Height = PreferredHeight;
                }
                else if (_cachedHeight > -1)
                {
                    Height = _cachedHeight;
                }
            }
        }
```

**Comment by giduac** [comment]
PR incoming...
