### ISSUE TITLE
[Bug]: Navigator tabs  ButtonSpecs on Navigator tabs are cut off

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1843]
Upgraded from 85.24.10.288 to 90.24.11.317, ButtonSpecs on Navigator tabs are cut off

Upper image shows 85.... ( desired ) result ( using a 16 x 16 image for the ButtonSpec) 
Lower image shows 90..... ( erroneous ) result ( top row of image is cut, essentially 16 x 15 )

Both tabs are 25 high, nothing else changed during or after toolkit upgrade

![image](https://github.com/user-attachments/assets/325567d5-8d9e-4f1b-ae1a-9f0b1df8cbb6)

**Comment by MattH-Work** [comment]
Newly added ButtonSpecs show the full image, but it is squashed to 16 x 15
![image](https://github.com/user-attachments/assets/62e2b7fe-253b-4765-9b4b-51a00ad7eb7d)

Issue is when ButtonSpec is Styled as List Item ( newly added buttons style as ButtonSpec / Inherited )

**Comment by giduac** [comment]
Hi @MattH-Work,

Thanks for posting.
I've had a quick look at it but can't reproduce this.

Could you please add a simple project that shows the error?

Thanks.

**Comment by MattH-Work** [comment]
How would I best go about uploading the solution? it zips to 26mb, 25 is the git limit

**Comment by PWagner1** [comment]
> How would I best go about uploading the solution? it zips to 26mb as it uses both Krypton.toolkit.lite & Krypton.Navigator.Lite, 25 is the git limit

Is it possible to upload it to DropBox. or if you have Windows 11 24h2 it is possible to compress to `7z`?

**Comment by MattH-Work** [comment]
Now that's too obvious! ( was just wondering if there was any GitHub magic I wasn't aware of )

Here is a link to download a small example of the issue

https://autode.sk/4eFyNfd

**Comment by giduac** [comment]
Hi @Smurf-IV, @PWagner1,
cc: @MattH-Work 

Been doing some testing on this;
The ButtonSpec image does also this on a textbox (probably other controls as well).
In the video it show that several styles produces a different size and make the button move slightly.

I'd would please have some direction on this as where these buttons / styles are drawn/processed.

https://github.com/user-attachments/assets/c2a467c4-444d-4e7f-8bf1-bda0715d24a8

**Comment by PWagner1** [comment]
Hi @giduac 

Is it possible to add a 'height' property to button specs?

**Comment by Smurf-IV** [comment]
> I'd would please have some direction on this as where these buttons / styles are drawn/processed.

@giduac try "playing with these settings" in each of the themes:
![image](https://github.com/user-attachments/assets/fdf81e0b-8edc-4621-8bde-5c729813f83a)

Also a lot of these will be "Demangled" if I manage to get #1807 done as it is getting quite involved, and will make some of these setting obsolete

**Comment by giduac** [comment]
Hi @Smurf-IV
I'm working on it
Below it the current state but will be updated later on as some circumstances are changing.
Will have a look at your answer as well.

This here might be some kind of rounding error:
```cs
  var ratio = 1.0f * 
    Math.Min(memento.Image.Width, memento.Image.Height) / Math.Max(memento.Image.Width, memento.Image.Height);

  // Resize image to fit display area
  memento.Image = CommonHelper.ScaleImageForSizedDisplay(
    memento.Image, displayRect.Width * ratio, displayRect.Height * ratio);
``` 

I added a Size property which might be handy (at least for testing now).

**BUT** it doesn't solve the problem. It looks like the image is moved out of view.
Also:
- when the control is made larger the problem remains. (see image)
In the image the button is centered and 16x16 the textbox has a height of 30 and still the image is shifted up.
- when the Button style is set to list item (thus shows problem) and the (malformed) image is copied to the clipboard the image is intact and not cropped.
*That might point to the positioning of the image within the control.*

These tickets are about the same thing.
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/623
- https://github.com/Krypton-Suite/Standard-Toolkit/issues/603
- https://github.com/Krypton-Suite/Standard-Toolkit/pull/627

In the ButtonSpecView class this routine has been altered to fit the Size property:

```cs
        /// <summary>
        /// Gets the content image.
        /// </summary>
        /// <param name="state">The state for which the image is needed.</param>
        /// <returns>Image value.</returns>
        public Image? GetImage(PaletteState state)
        {
            // Get value from button spec passing inheritance redirector
            var baseImage = ButtonSpec.GetImage(_redirector, state);

            // No need to perform scaling as it will be done @
            // $\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Rendering\RenderStandard.cs
            // line 5779: memento.Image = CommonHelper.ScaleImageForSizedDisplay(memento.Image, currentWidth, currentHeight);
            if (baseImage is not null)
            {
                baseImage = new Bitmap(baseImage, ButtonSpec.Size);
            }

            return baseImage;
        }
```
![image](https://github.com/user-attachments/assets/d6fd8919-bd23-4963-8599-7013d4c995d2)

https://github.com/user-attachments/assets/5cab2781-1b87-4aec-bb9d-4dcfdeefafa6

**Comment by giduac** [comment]
@Smurf-IV 

This is the problem (-1) at least for list item.
'private static readonly Padding _contentPaddingButtonListItem = new Padding(0, -1, 0, -1);' 
and this solves it
' private static readonly Padding _contentPaddingButtonListItem = new Padding(0, 0, 0, 0);' 

![image](https://github.com/user-attachments/assets/1cfadd70-a444-4199-82a1-d2c15407cdf3)

That would solve this problem.
But for some other states it seems that these paddings vary...

**Comment by giduac** [comment]
@Smurf-IV 

This looks stable even when certain styles use different paddings.
So I will change this one setting for all themes.

What do you think of a size property as a new feature for a ButtonSpec which is handled like this:

```cs
        /// <summary>
        /// Gets the content image.
        /// </summary>
        /// <param name="state">The state for which the image is needed.</param>
        /// <returns>Image value.</returns>
        public Image? GetImage(PaletteState state)
        {
            // Get value from button spec passing inheritance redirector
            var baseImage = ButtonSpec.GetImage(_redirector, state);

            // Use the size property to resize the image to the requested size
            if (baseImage is not null)
            {
                baseImage = new Bitmap(baseImage, ButtonSpec.Size);
            }

            // No need to perform scaling as it will be done @
            // $\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Rendering\RenderStandard.cs
            // line 5779: memento.Image = CommonHelper.ScaleImageForSizedDisplay(memento.Image, currentWidth, currentHeight);
            return baseImage;
        }
```

**Comment by giduac** [comment]
@Smurf-IV 

Maybe just one padding for buttonspecs regardless of the style might be an option for the V100 embedded themes...?
That would keep the size and position equal and the controls won' t be resized on a style change...?

**Comment by Smurf-IV** [comment]
> What do you think of a size property as a new feature for a ButtonSpec which is handled like this:

Not sure, As this will not then following the DPI size changing and might cause even more confusion !

**Comment by giduac** [comment]
> > What do you think of a size property as a new feature for a ButtonSpec which is handled like this:
> 
> Not sure, As this will not then following the DPI size changing and might cause even more confusion !

OK then that passes.
PRs underway

**Comment by PWagner1** [comment]
Looks much better!

**Comment by giduac** [comment]
@PWagner1 

That was the intention :).....
