### ISSUE TITLE
[Bug]: `ListViewItemStates` does not contain a definition for `HasFlag`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#186]
**Describe the bug**
While compiling, the compiler encounters an error with `KryptonListView`, stating that the `ListViewItemStates` does not contain a definition for `HasFlag`.

**To Reproduce**
Use `Build.cmd` or `Debug.cmd`

**Comment by Smurf-IV** [comment]
Another API for the "Missing" file

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/125940795-a96cbd9e-51f6-4de4-8b80-22693c4e41b7.png)
