### ISSUE TITLE
[Bug]: HeaderGroups are 'clipped' after upgrade to 90.24.11.317

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1871]
After upgrading from 85...... to 90.24.11.317, the right-hand edge / border of all Headers & HeaderGroups have been 'clipped'

HeaderGroups

![image](https://github.com/user-attachments/assets/31a3a555-0625-45b2-a863-f26c09037a4d)

![image](https://github.com/user-attachments/assets/d85966d2-ed07-455b-b4c6-d53d4b7b0dc8)

![image](https://github.com/user-attachments/assets/ef3494f7-d5ed-4100-8a53-23fe6ec08593)

Headers

![image](https://github.com/user-attachments/assets/02932aea-1194-45c6-8ca5-58f59bb11728)

**Comment by MattH-Work** [comment]
Navigator pages also suffer
![image](https://github.com/user-attachments/assets/b75d076c-a5de-4349-9fd2-5a3ece6d54df)

**Comment by Smurf-IV** [comment]
This work is being sorted via #1807
I'll keep this open just in case I cannot sort it out with the above tho!

**Comment by MattH-Work** [comment]
I use a KryptonCustomPalette to edit the global pallete, when making the same adjustments directly to the control it works as expected ( no clipping, consistent border width all round ) Issue might stem from the KryptonCustomPalette

**Comment by MattH-Work** [comment]
Stupid question, where do I find UseChrome?

**Comment by Smurf-IV** [comment]
> Stupid question, where do I find UseChrome?

Sorry, I shortened it !

![image](https://github.com/user-attachments/assets/efb4eacb-fb65-46c4-bdc4-6ba215b0eb5c)

**Comment by MattH-Work** [comment]
No dice, and I now have the Magenta border issue #1757   #1749

**Comment by Smurf-IV** [comment]
So far it appears to be something to do with the addition of the "CheckButton" style, even when it is in a stack:
![image](https://github.com/user-attachments/assets/5fd55591-3fc2-4fee-8907-78d424b03bde)

And Roll over (Hover) is even worse !

**Comment by Smurf-IV** [comment]
@MattH-Work AS a possible workaround, can you try the following settings ?
![image](https://github.com/user-attachments/assets/26a77e91-e1d3-484e-9c01-ef8c6f20e878)

**Comment by MattH-Work** [comment]
More evidence of clipping weirdness ( on a button )

![image](https://github.com/user-attachments/assets/98171bdf-c446-42a1-93f5-7f42c1998f62)
Border width = 2
DrawBorders = Top, Bottom, Left, Right

![image](https://github.com/user-attachments/assets/fcefe19e-08ef-4701-9856-ba550f7a5909)
Border width = 2
DrawBorders = Bottom, Left, Right

**Comment by Smurf-IV** [comment]
Found 1 of the issues:
![image](https://github.com/user-attachments/assets/db41c5f5-aca4-44ff-b5b5-72a7f71b5b36)

Also Sorted the Button thing directly above.

@MattH-Work 
Not able to repro a demo app for the OP Yet, Do you have it via a Toolkit Demo, or can you provide a simplified version that demos please ?

**Comment by Smurf-IV** [comment]
And with a value of 5:
![image](https://github.com/user-attachments/assets/da5bce99-4919-46b3-95c2-18d9ea31ad97)

Just need to find a header and an entry below to see what happen when set to -1 to check alignment.

**Comment by MattH-Work** [comment]
https://autode.sk/4eSC8rJ
Link to download updated test solution

**Comment by Smurf-IV** [comment]
Using the proposed V95 fixes:
![image](https://github.com/user-attachments/assets/041a3aea-ed04-4be4-99c2-afa87f12a461)

95 PR coming ;-)

**Comment by Smurf-IV** [comment]
Done, Alpha PR incoming...
