### ISSUE TITLE
[Bug]: KryptonGroupBox fails with non-default GroupBackStyle

### ISSUE THREAD

**Issue by neumatho** [Krypton-Suite/Standard-Toolkit#1872]
After I have upgraded from 85.24.10.288 to 90.24.11.317, UserControls with a KryptonGroupBox could not be opened in the designer. Also my program crashed when opening those windows having this control. It fails with a null reference exception in PaintTransparentBackgroup()

![image](https://github.com/user-attachments/assets/a82eca14-dae2-4984-b696-9cca7de3cc05)

I have figured out, it has something to do with with the GroupBackStyle and when it is not the default value.

To reproduce it, just create a UserControl and add a KryptonGroupBox control to it. Then change the GroupBackStyle property to "Tab - Low profile" and the exception is shown in the designer immediately.

I'm using .NET 9.0.

**Comment by giduac** [comment]
Hi @neumatho,
CC: @PWagner1 

This has been addressed in PR <https://github.com/Krypton-Suite/Standard-Toolkit/pull/1864>.
It will be released in the coming V90 Patch 1 release.

Until then, please use the work-around you've described.
