### ISSUE TITLE
[Bug]: KryptonListView is missing key events

### ISSUE THREAD

**Issue by astromediaonly** [Krypton-Suite/Standard-Toolkit#1878]
**Describe the bug**
It seems ``KryptonListView`` lost ``SelectedIndexChanged `` (and probably other usefull events) if I understand it correctly when it was reworked to not be derived from standard ``Winform.ListView``.

**To Reproduce**
1. Have installed version 80.23.11.321 (for example - my case) and use the event
2. Update to version 90.24.11.317 - the event is gone

**Expected behavior**
There has to be event for selection change

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Framework/.NET Version: 4.7.2
 - Toolkit Version: 90.24.11.317

**Comment by Smurf-IV** [comment]
TODO: Check to see when the `KListView` was "Migrated" and see if this is in v85 !?!
