### ISSUE TITLE
[Question]: Add sub-context menu items

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1885]
### Discussed in https://github.com/Krypton-Suite/Standard-Toolkit/discussions/1884

<div type='discussions-op-text'>

<sup>Originally posted by **danijelVR** November 30, 2024</sup>
Hello,
Is it possible to add sub-menu items on the existing context menu item, as it is shown on the image below?
So when I press "Print", two more items should appear on the right.
![063m0Qrwoq](https://github.com/user-attachments/assets/2d97de49-6de5-421f-86a3-0819521f6d1d)

Any help will be very appreciated.
</div>

**Comment by Smurf-IV** [comment]
Yes, Please see the example as per the picture:
![image](https://github.com/user-attachments/assets/d88ab9c0-98a5-4991-ac4e-3815c65828d5)

**Comment by PWagner1** [comment]
Tagging @danijelVR

**Comment by danijelVR** [comment]
I will try it. Thank you!
