### ISSUE TITLE
[Bug]: ToolStripLabels use the wrong colour for dark themes

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#189]
**Describe the bug**
Where is the `of 1` in the following image:

![image](https://user-images.githubusercontent.com/2418812/124909573-80b6d200-dfe2-11eb-8ad6-7f0a0645c5c0.png)

It should be "Themed" as "Panel - Label" so that it shows up against the dark background

![image](https://user-images.githubusercontent.com/2418812/124909908-e6a35980-dfe2-11eb-81cb-2a369693027b.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Is this fixed in the latest nightly?

**Comment by Smurf-IV** [comment]
@Wagnerp Can you please transfer this issue to the "Theme-palletes" repo, so that the toolstrip can be added to the "designer"
It refuses to move when I do it !

**Comment by Wagnerp** [comment]
> @Wagnerp Can you please transfer this issue to the "Theme-palletes" repo, so that the toolstrip can be added to the "designer" It refuses to move when I do it !

@Smurf-IV Done :)

**Comment by Wagnerp** [comment]
@Smurf-IV Created new issue here: https://github.com/Krypton-Suite/Theme-Palettes/issues/27
