### ISSUE TITLE
[BUG]: "Office 365 Silver" theme statusBar drag glyph, is not visible

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#19]
Office 365 - Silver Status bar:
![image](https://user-images.githubusercontent.com/2418812/71557345-c6352f00-2a3c-11ea-9da8-231180133457.png)

Office 2010 - Silver status bar:
![image](https://user-images.githubusercontent.com/2418812/71557352-d5b47800-2a3c-11ea-8507-ffba0b6441a5.png)

Office 2007 - Silver:
![image](https://user-images.githubusercontent.com/2418812/71557364-e95fde80-2a3c-11ea-94eb-9b111f175967.png)

**Comment by dax-leo** [comment]
I think in this case your dark color used for the glyph is identical (or very close) to the status strip background color for this specific theme.
Consider changing "DarkGlyph" color to something else in the Silver theme.
https://github.com/Krypton-Suite/Standard-Toolkit/blob/1f11648565d2ae1832f6f6cf218f79af4e9830ec/Source/Krypton%20Components/ComponentFactory.Krypton.Toolkit/Rendering/KryptonOffice365Renderer.cs#L806

Just to test if it works ok I used SeparatorDark instead. 
`using (SolidBrush darkBrush = new SolidBrush(KCT.SeparatorDark),
                              lightBrush = new SolidBrush(KCT.GripLight))`

![image](https://user-images.githubusercontent.com/70173560/95903707-d1bcd100-0d96-11eb-92ee-2af235993907.png)

**Comment by Wagnerp** [comment]
Hi @dax-leo 

Will look into it thanks. Just moving any relevant issues from older repos (5.400 to 5.480) over to here before I archive them.

**Comment by Wagnerp** [comment]
Just figured out that the bug exists in the 2013 renderer too, as 365 is a copy of the 2013 renderer.
