### ISSUE TITLE
[Other Issues]: Remove `KryptonMessageBoxDep` from V100 code base

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1900]
This is the deprecated MessageBox to help existing V80 code to the "Fixed" `KryptonMessageBox`

Needs to be removed from Alpha and thus V100

**Comment by Smurf-IV** [comment]
@PWagner1 @giduac Should this also be removed from V95 as well ?

**Comment by giduac** [comment]
Hi @Smurf-IV & @PWagner1 

Maybe mark it obsolete in V95 and removed it from V100....

**Comment by Smurf-IV** [comment]
It was a name change only to allow existing beat usages in V80 to continue to work, so not sure an attribute is needed.

**Comment by giduac** [comment]
@Smurf-IV 

There is a difference between the two ??

![image](https://github.com/user-attachments/assets/671749ba-bcea-4b16-8a6f-bd0699ff7353)

**Comment by Smurf-IV** [comment]
Correct, the ##dep has all the flow and lot's of extra stuff, and the problems that had been found, before refactoring back to something that worked.

**Comment by giduac** [comment]
@Smurf-IV 

Taskdialog can do all that afaik...
So if that is the case than TD is the replacement ...

Imo, the gradual approach is favorite for V95 and fully removed in V100.
