### ISSUE TITLE
[Bug]: `Sparkle` Themes have an issue with the Background

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1905]
Using V95 (And applicable to V85 as well !)

![image](https://github.com/user-attachments/assets/27c4abba-0b9a-4465-ac7e-75c117a2913d)

**Comment by Smurf-IV** [comment]
FYI: @PWagner1 
This is because the `Control - Client` colouring, is vastly different from `Panel - Client`
The radio buttons are in a `KryptonGroup` control, who's default "BackStyle" is `Control - Client`!

**Comment by Smurf-IV** [comment]
Also, a `KryptonHeaderGroup` contains a `KryptonGroupPanel`. 
The `KryptonHeaderGroup back style also defaults to `Control - Client`

Workaraound:
- In the designer change the back styles to be `Panel - Client`

For V100:
Either
- Make the Control Client colouring be the same as the `Panel - Client`
- Or,  Make the default for all back style be `Panel - Client`
Thoughts ?

**Comment by PWagner1** [comment]
> Also, a `KryptonHeaderGroup` contains a `KryptonGroupPanel`. The `KryptonHeaderGroup back style also defaults to `Control - Client`
> 
> Workaround:
> 
> * In the designer change the back styles to be `Panel - Client`
> 
> For V85 onwards: Either
> 
> * Make the Control Client colouring be the same as the `Panel - Client`
> * Or,  Make the default for all back style be `Panel - Client`
>   Thoughts ?

Hi @Smurf-IV 

My thoughts would be making the default for all back styles be `Panel - Client`

**Comment by Smurf-IV** [comment]
`Panel - Client` Style is now the default:
![image](https://github.com/user-attachments/assets/0fc2e16a-4748-4dbf-8f04-4f7c158d5d4e)

PR(s) incoming
