### ISSUE TITLE
[Bug]: KryptonDockingManager Save Config - Load Config from Array / File (Docking Persistence Project sample)

### ISSUE THREAD

**Issue by yp25** [Krypton-Suite/Standard-Toolkit#1907]
**Describe the bug**
Safe config to file and array seems not working correctly for workspace

**To Reproduce**
1. Open and run Project Docking Persistence
2. Click Save Array
3. Close Document 5, Properties 1, Input 2 
4. Click Load Array . Properties1(Control) and Input 2 (Control) can be loaded successfully but Document 5 (Workspace) is not loaded
5. Click Save To File
6. Close Document 6, Properties 1, Input 2
7. Click Load From File - > Properties 1 and Input 2 can be loaded successfully but Document 6 is not loaded

From config.xml there is tag KW KP 'Document' 

`<DM N="DockingManager" C="3">
    <DW N="Workspace" O="0" S="1006, 430">
      <KW V="1" A="Document 6">
        <CGD />
        <WS UN="5462F66039D342065462F66039D34206" S="T,0,50:T,0,50" D="Horizontal">
          <WC UN="40fa8862f7b64306b4fa450bbfab2f0b" S="T,0,50:T,0,50" NM="BarTabGroup" AR="True" MINS="150, 110" SP="Document 6">
            <KP UN="Document 6" S="False">
              <CPD>
                <CustomPageData SavedMilliseconds="795" />
              </CPD>
            </KP>
            <KP UN="Document 7" S="False">
              <CPD>
                <CustomPageData SavedMilliseconds="795" />
              </CPD>
            </KP>
          </WC>
        </WS>
      </KW>
    </DW>`

**Expected behavior**
Is the load and save behavior normal like this ? only able to save and restore Control ? o

**Screenshots**
![error krypton1](https://user-images.githubusercontent.com/2161156/213841143
![error krypton 2](https://user-images.githubusercontent.com/2161156/213841174-dd6b8831-a6a0-42b8-89b4-9020fb06ce92.png)
-f60e0a5e-6894-4361-9b86-3215b9860c0c.png)
![error krypton 3](https://user-images.githubusercontent.com/2161156/213841177-e8156c62-e5be-4a16-b8d1-3847fa8a3066.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 64 bit
 - VS 2022

**Comment by Smurf-IV** [comment]
Transferred to here, as it looked like a Demo app problem, But it's do with the core **_"Docking Persistence"_**!

**Comment by Smurf-IV** [comment]
I was going round in circles for this, So went back to the original 2016 code base (From component factory), and found that it is a bug in there !)
![image](https://github.com/user-attachments/assets/9c5ec8e7-fec9-48b7-b0d0-280a11980013)

Removing Regression!
I'll still attempt to find a fix in V85-LTS.

**Comment by Smurf-IV** [comment]
Also, In the original of the "WorkSpace Persistence" app, Loading from Array **works**,
BUT 
Loading from the saved file does "**NOT**"

![image](https://github.com/user-attachments/assets/b31c2f45-8e6f-4be0-9bbd-f17c49379f73)

**Comment by Smurf-IV** [comment]
Turns out that this **is** a bad example code problem, But it is **not** explained anywhere !!

### _To Fix:_
What you have to do is add function to respond to the following:
`this.kryptonDockingManager.RecreateLoadingPage += new System.EventHandler<Krypton.Workspace.RecreateLoadingPageEventArgs>(this.kryptonDockingManager_RecreateLoadingPage);`

and then in that to perform the following:
``` c#
        private void kryptonDockingManager_RecreateLoadingPage(object sender, Krypton.Workspace.RecreateLoadingPageEventArgs e)
        {
            e.Page = new KryptonPage(e.UniqueName, e.UniqueName);
        }
```
Job Done !

I'll fix in this in the V95 Demo's next time I'm in there.

**Comment by giduac** [comment]
@Smurf-IV

Are these connected https://github.com/Krypton-Suite/Standard-Toolkit/issues/980

**Comment by Smurf-IV** [comment]
@giduac No, 
This one is to do with the **_restore_** workflow.
980 is to do with the save.
