### ISSUE TITLE
[Feature Request]: Light/Dark Theme change based on time of day

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#191]
**Is your feature request related to a problem? Please describe.**
Ok, this may sound unusual, but given there are both white/black themes, would it be possible to automatically switch between these themes based on the time of day _**if**_ the developer/user chooses to do so?

**Comment by Smurf-IV** [comment]
This just leads into TimeZone nightmares
And what about "Midnight sun" places
I think it should just be an option that the developer places within their application, and should not be the responsibility of this suite.
