### ISSUE TITLE
[Question]: Host control in other control ( similar to ButtonSpecs) 

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#1930]
Is there a built in mechanism that would allow me to host a Combobox inside another control, similar to the way ButtonSpecs allow buttons to live inside other control
In my case, I would like Combox(s) to live in HeaderGroup Primary Headers

![image](https://github.com/user-attachments/assets/a57c21b7-7115-45c9-b02c-a994cf5dfa91)

**Comment by Smurf-IV** [comment]
@MattH-Work Not that I am aware of;
and this would be a "Feature" of the Advanced data grid view in the EXT suite if it did exist.
https://github.com/Krypton-Suite/Extended-Toolkit/blob/master/Source/Krypton%20Toolkit/Krypton.Toolkit.Suite.Extended.AdvancedDataGridView/Readme.md

**Comment by MattH-Work** [comment]
Appreciate the answer,

However, it’s not related to Data Grids ( although the image alludes to that, I just use ButtonSpecs as a convenient way to control filters of the Grid )
It is more to do with adding Comboboxes ( or maybe other controls ) into the headers of HeaderGroupBoxes so that the control ‘moves’ with the host, but is outside the host & can be enabled independently of the Host, I can get the behaviour by ‘floating’ the Combobox, but this needs extra management depending on size / position etc of the ‘host’ panel

Kindest Regards
Matt


***@***.***

Matt Hutchinson | Senior Application Engineer
Tel: 01254 301 888<tel:%2001254%20301%20888>
DDI: 01254 306 890<tel:%2001254%20306%20890>
Mob: 07764 687 767<tel:%2007764%20687%20767>
Web: www.quadrasol.co.uk<http://www.quadrasol.co.uk/>
Address: Quadra Solutions Limited, Ewbank House, Cannon Street, Accrington, Lancashire, BB5 1NJ
***@***.***<https://www.quadrasol.co.uk/mfg>     ***@***.*** <https://www.quadrasol.co.uk/ecadstar>
***@***.***

________________________________
Full Terms & Conditions and Quadra Solutions Confidentiality Notice can be found at www.quadrasol.co.uk/terms-conditions<http://www.quadrasol.co.uk/terms-conditions>
________________________________

***@***.***<https://www.credly.com/badges/47466190-4876-4367-ac73-f05738ea49ad/public_url>     ***@***.*** <https://www.credly.com/badges/466ee4d6-0daf-4f9c-a290-9d38696b1273/public_url>      ***@***.*** <https://www.credly.com/badges/ad097db4-13e8-44ef-bd80-f01e5a2e7019/public_url>

**Comment by Smurf-IV** [comment]
What I did to do something similar was have a KryptonRableLayout with the same border style as the grid, then added the controls etc into it.
And then whenever the grid columns where resized, I set the table columns to be the same.
