### ISSUE TITLE
[Bug]: `KryptonTextBox` CueHint Text

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1938]
**From TuPuRen via NuGet**

In Winform VB.NET 8.0 or 4.8, after setting CueHintText, a horizontal line appears above the text and below the upper border. When running, clicking on the control or switching KryptonPage causes the line to disappear.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version: 4.8 & 8.0
 - Toolkit Version:  90.24.11.317

**Comment by Smurf-IV** [comment]
Unable to replicate in the examples:
![image](https://github.com/user-attachments/assets/130ab462-956a-4220-b9f1-5f023af2a59b)

@PWagner1 Can you provide an example?
And, Does it replicate in the V95 code base ? (As used in the example picture ?)

**Comment by PWagner1** [comment]
@Smurf-IV I'll ask OP to post here if they can

**Comment by PWagner1** [comment]
@Smurf-IV 

It's in the designer

![image](https://github.com/user-attachments/assets/0d432050-7840-4948-b00c-417f20342d3f)

**Comment by Smurf-IV** [comment]
Thanks for the Hint.
I used these steps to prove it's fixed
- With designer closed
- Open and have default item as the button
## Before fix:
- Text hint would have a line drawn above until it got focus (And then was fine from then onwards !!)
## After Fix:
- Initial open does not have the line ;-)
![LaunchDesigner](https://github.com/user-attachments/assets/e2723548-510f-45ca-900f-d62e0ccef1e4)
