### ISSUE TITLE
[Bug]: `KryptonNavigator` KryptonPage

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#1939]
_From TuPuRen via NuGet_

In Winform VB.NET 8.0, it is not possible to directly switch KryptonPage in the form designer; the SelectedPage property must be selected to switch.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version: 8.0
 - Toolkit Version: 90.24.11.317

**Comment by Smurf-IV** [comment]
Is this the "Normal" designer issue of having to use TFM of 48 first in the project ?

**Comment by PWagner1** [comment]
@Smurf-IV I'll ask OP to post here if they can

**Comment by PWagner1** [comment]
Please have a look at this [article](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html).
