### ISSUE TITLE
[Bug]: Applying 5 as rounding style has broken existing layouts

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#194]
**Describe the bug**
Old style on left (Example bitmap), Alpha on right

![image](https://user-images.githubusercontent.com/2418812/126039383-d56f7a23-9c0c-4c55-8049-09586504be06.png)

**Comment by Smurf-IV** [comment]
Is this another breaking change that will need to be documented, or does it need fixing ?

**Comment by Wagnerp** [comment]
Fixed, 5 may have been a bit aggressive. Rounding values can be altered in `GlobalStaticValues`.
