### ISSUE TITLE
[Feature Request]: Rounding should use `float` or `double` instead of `int`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#197]
The `Rounding` should use `float` or `double` instead of `int`

**Why?** By using `float` or `double`, it allows for finer control, i.e. 0, 0.1 ... 0.9 - 1.0 etc. With `int` you're stuck with using 'whole' numbers.

**Comment by Smurf-IV** [comment]
Also check that individual controls can have different rounding values from the GlobalValue

**Comment by Wagnerp** [comment]
> Also check that individual controls can have different rounding values from the GlobalValue

Will do, may separate textboxes from buttons etc.

**Comment by Wagnerp** [comment]
Available in build 2108 August update (Canary)
