### ISSUE TITLE
[BUG]: Selected text in ComboBox is drawn in a different font

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#20]
Notice that the selected text in the ComboBox2 is shorter when it is selected:
![image](https://user-images.githubusercontent.com/2418812/61876182-35ce4d80-aee4-11e9-9dfe-66687b66cf81.png)

And when it is not, it the as expected
![image](https://user-images.githubusercontent.com/2418812/61876217-47aff080-aee4-11e9-8d97-1708c394ee47.png)

Notes: 
- This is the Professional - System theme, Not as "Noticeable" in the other themes, as the Font "Appears to be stretched" due to the selection box starting earlier (Look at the letter "k" positions): 
![image](https://user-images.githubusercontent.com/2418812/61876532-fe13d580-aee4-11e9-9572-2c2e72822749.png)

- This is probably applicable to the UpDowners as well (Domain / Numeric)

**Comment by dax-leo** [comment]
I looked quickly into paint method, but couldn't notice anything strange.  I am new to Krypton rendering solution so I need to familiarize myself with the this part of the code.
But what I did notice is this strange "stretching" effect. Very noticeable if you type in bunch of 3 numbers.
Feels like stretching effect is stronger at the beginning of the text, but barely noticeable. Is there some rendering effect which might be behind this behavior ?
Top line is normal text from textbox ... lower one is from combo...
![image](https://user-images.githubusercontent.com/70173560/95918227-b90ae600-0dab-11eb-9124-8793d0eca548.png)

**Comment by Wagnerp** [comment]
Might need to compare the `OnPaint` method, since something odd might be happening.

**Comment by dax-leo** [comment]
Hmmm... could it be that _InternalComboBox_ should be initialized with 
`DrawMode = DrawMode.OwnerDrawFixed;` instead of `DrawMode = DrawMode.OwnerDrawVariable;`  ?

https://github.com/Krypton-Suite/Standard-Toolkit/blob/1f11648565d2ae1832f6f6cf218f79af4e9830ec/Source/Krypton%20Components/ComponentFactory.Krypton.Toolkit/Controls%20Toolkit/KryptonComboBox.cs#L141

**Comment by Wagnerp** [comment]
I'll change it in the alpha code & test it.

**Comment by Smurf-IV** [comment]
This has been refixed via #517:
![ComboBox](https://user-images.githubusercontent.com/2418812/173082653-f5219b26-8f44-4dca-ac24-466685aa0c82.gif)
