### ISSUE TITLE
[Bug]: KryptonCombBox does not display the QueHint.

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#2009]
**Describe the bug**
Quehint is not displayed when set or it's values are altered

**To Reproduce**
- Take a KCombo and set the quehint\

**Desktop (please complete the following information):**
 - OS: Win11
 - Framework/.NET Version: 481
 - Toolkit Version: alpha branch

**Comment by Smurf-IV** [comment]
Appears to be working in V85-LTS
![image](https://github.com/user-attachments/assets/14b51532-b7da-457b-8797-de86db4d6e8f)

**Comment by Smurf-IV** [comment]
And Also in V90
![image](https://github.com/user-attachments/assets/b4a462c5-212e-4180-9625-fec526995a95)

**Comment by giduac** [comment]
@Smurf-IV 

But not in alpha, combo stays blank:

![image](https://github.com/user-attachments/assets/0fa0f38a-f220-41e3-8a2a-f70d3dcd147d)

**Comment by Smurf-IV** [comment]
It was caused by thew fix for #1938 :-(

**Comment by Smurf-IV** [comment]
Fixed, PR incoming
![image](https://github.com/user-attachments/assets/2543b44d-b6a1-4022-9fbe-9de3296a24c5)
