### ISSUE TITLE
[Other Issues]: Need to disable `CS0105`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#201]
Because the projects are using `C# 10`, the compiler (2019 & below) does not recognise the additions made to the `C# 10` spec, resulting in:

![image](https://user-images.githubusercontent.com/949607/126067964-5d1714fe-d67f-4028-a6b9-0019d8e47697.png)

**Comment by Smurf-IV** [comment]
Not yet it doesn't, Perhaps it will be fixed, via an option when autogenerating and the project is actually marked as `10` rather than `preview`

**Comment by Smurf-IV** [comment]
Fixed by PR  #206
