### ISSUE TITLE
[Bug]: KryptonGroup Transparency

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#202]
When using a KryptonGroup in WinForms, if the background color is set to Transparent, it does not automatically refresh if its parent control changes its background color. 

I was able to overcome this by deriving from KryptonGroup and using             SetStyle(ControlStyles.SupportsTransparentBackColor, true).

**Comment by sdreb3421** [comment]
I found a few additional things on the issue. 

1. The SetStyle fix is incomplete. The normal Control.BackColor property of the KryptonGroup must be set to transparent in addition to the StateCommon color for this to work.
2. The issue also applies to KryptonGroupBox and KryptonPanel.
3. The issue only appears when the child container is contained in a parent Krypton container, and the parent container back color is modified at runtime. If they are placed in a normal WinForms panel, the transparency functions normally.
4. Lastly, I also found the Paint event for each of these Krypton containers is never triggered, even when Invalidated. I thought this was a separate issue, but I'm guessing that this is the actual reason why the child Krypton containers aren't getting back color updates. I have no fix to get the Paint event to fire, but did try using SetStyle with ControlStyles.UserPaint with no success. 
6. In summary, the original fix is a good temporary work around, but ultimately need to fix the paint event issue.

**Comment by Smurf-IV** [comment]
Is this done now ? (In canary 2108 ?)

**Comment by Wagnerp** [comment]
> Is this done now ? (In canary 2108 ?)

Yes, sorry forgot to close. Did I mention it in the changelog?

**Comment by Smurf-IV** [comment]
Yupe:
![image](https://user-images.githubusercontent.com/2418812/128064886-fcff5991-dcee-4edf-8db4-e48dfb34df6c.png)
