### ISSUE TITLE
[Feature Request]: ProgressBars are part of the Standard winforms ToolBox, where is the Krypton Equivalent?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#203]
![image](https://user-images.githubusercontent.com/2418812/126623690-b7ed2697-d17d-4525-8a36-1344d10add9d.png)

**Comment by Smurf-IV** [comment]
Also requested via #5

**Comment by MattH-Work** [comment]
Maybe also add the abilty to have text
![image](https://user-images.githubusercontent.com/84494183/131696130-74b416e8-bc6f-4608-a91c-c168eea6fb28.png)

**Comment by Smurf-IV** [comment]
Done as part of 
#910
#1075

PR's in 
https://github.com/Krypton-Suite/Standard-Toolkit/pull/1088
