### ISSUE TITLE
[Feature Request]: 'DarkMode' for `KryptonRichTextBox`/`KryptonTextBox`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#207]
**Is your feature request related to a problem? Please describe.**
Something like this:

![image](https://user-images.githubusercontent.com/949607/126896321-63987d6f-c2d9-4529-8bc0-d76de0f68e95.png)

(The page background/forecolour)

**Comment by Smurf-IV** [comment]
This will ned to be extended to any edit entry, 
ComboBox, NumericUpDowner, WebBrowser / etc.

It should be in the Theme, and I do not understand why the dark themes enforce the white background.
The sparkle Blue I think is the only one that attempts to make them darker (And does a good job)

So the Dark themes, should have the Dark Backgrounds

**Comment by Wagnerp** [comment]
> This will ned to be extended to any edit entry,
> ComboBox, NumericUpDowner, WebBrowser / etc.
> 
> It should be in the Theme, and I do not understand why the dark themes enforce the white background.
> The sparkle Blue I think is the only one that attempts to make them darker (And does a good job)
> 
> So the Dark themes, should have the Dark Backgrounds
> 
> So I think this should be a Bug against the Dark themes !

I agree, ATM I've made it optional

**Comment by Smurf-IV** [comment]
Lets fix the themes and not introduce Yet Another Optional `thing` that will become mute when the proper fix is done.

**Comment by Wagnerp** [comment]
One theme that might be good to do in the future is the 'Cobalt' theme

![image](https://user-images.githubusercontent.com/949607/126898156-c48c31ca-62bd-489b-b8d9-2564d3b431ea.png)

**Comment by Smurf-IV** [comment]
Add that to the "Visual Studio Themes" request that already exists
(Ant Idea what font to use for that?)

**Comment by Wagnerp** [comment]
> Add that to the "Visual Studio Themes" request that already exists
> (Ant Idea what font to use for that?)

I use Cascadia Code https://github.com/microsoft/cascadia-code

**Comment by Smurf-IV** [comment]
Yes, but that is not going to be applicable to a theme :-(

**Comment by Wagnerp** [comment]
@Smurf-IV Are the back colours controlled by `InputControlBackNormal`?

**Comment by Wagnerp** [comment]
Ok, I think I can implement it on a theme level, but what should the blue themes be?

**Comment by Smurf-IV** [comment]
> 
> 
> Ok, I think I can implement it on a theme level, but what should the blue themes be?

Leave them as they are, or just use a vary pale "cream?" hint over the white.
This -I think- is normal for Blue themes to have white edit areas.

Or, 
Have new Blue themes called 2021 which have a better tint for the edit areas, (More Studio blue theme style - which has a definite colour difference from white
![image](https://user-images.githubusercontent.com/2418812/126901709-641990d7-7fb6-4804-9525-9ef43412baa0.png)

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Are the back colours controlled by `InputControlBackNormal`?

Looks like it, Not sure if these are applied to RTF and Browser tho, and I also do not know which is used by default:
![image](https://user-images.githubusercontent.com/2418812/126901874-8bbb3e73-b316-4509-aca3-7316afcd2198.png)

**Comment by Wagnerp** [comment]
> > Ok, I think I can implement it on a theme level, but what should the blue themes be?
> 
> Leave them as they are, or just use a vary pale "cream?" hint over the white.
> This -I think- is normal for Blue themes to have white edit areas.
> 
> Or,
> Have new Blue themes called 2021 which have a better tint for the edit areas, (More Studio blue theme style - which has a definite colour difference from white
> ![image](https://user-images.githubusercontent.com/2418812/126901709-641990d7-7fb6-4804-9525-9ef43412baa0.png)

Ok, checked in some 'black' theme changes, would you mind taking them for a test drive?

**Comment by Smurf-IV** [comment]
> Ok, checked in some 'black' theme changes, would you mind taking them for a test drive?

That'll have to wait, I'm pulling the Palette code apart, and also fixing more Warnings and messages.

I'll do the test after I create a PR for the changes mentioned.. So add more changes to the other themes if you like.

**Comment by Wagnerp** [comment]
Useful for the VS themes https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/color-value-reference-for-visual-studio?view=vs-2019

**Comment by Wagnerp** [comment]
I know that this might be a long shot, but do we know where we can find the radio button icons for MS Office?

**Comment by Smurf-IV** [comment]
That'll be version dependent, and they may be hidden in a resource MEF style dll
Could be C++ for the older versions, so probably be able to get them via a dll load into visual Studio.

BUT, They might draw them manually..

**Comment by Wagnerp** [comment]
> That'll be version dependent, and they may be hidden in a resource MEF style dll
> Could be C++ for the older versions, so probably be able to get them via a dll load into visual Studio.
> 
> BUT, They might draw them manually..

I wonder how Phil extracted these

![RB2007Blue](https://user-images.githubusercontent.com/949607/126905201-abea9ca0-4c7a-4338-9e8c-12a9ed4d58ef.png)

As it could open up adding support for the other colours

**Comment by Smurf-IV** [comment]
Is this done with the Canary Dark / Light themes ?
Or is it that the Boxes do not use the colours anyway ?

**Comment by Wagnerp** [comment]
> Is this done with the Canary Dark / Light themes ?
> Or is it that the Boxes do not use the colours anyway ?

No, it appears that the images are one kind

**Comment by Smurf-IV** [comment]
What is set in the Sparkle themes to make them go darker then ?

**Comment by Wagnerp** [comment]
> What is set in the Sparkle themes to make them go darker then ?

These:

![RBSparkleTC](https://user-images.githubusercontent.com/949607/128064938-542bc3d2-3430-47f5-a646-116b15eac646.png)
![RBSparkleD](https://user-images.githubusercontent.com/949607/128064941-9ea87b1b-fa52-4119-9a99-70a474418870.png)
![RBSparkleDC](https://user-images.githubusercontent.com/949607/128064943-907cb09f-81f8-4798-938a-1b274f3cf8a4.png)
![RBSparkleN](https://user-images.githubusercontent.com/949607/128064944-5b38ea28-4f30-4b1d-b55f-148b52ccfcb7.png)
![RBSparkleNC](https://user-images.githubusercontent.com/949607/128064947-e503069d-31f2-44cb-bb4e-6cd27128fe0b.png)
![RBSparkleOrangeNC](https://user-images.githubusercontent.com/949607/128064948-5e9bbc01-3d48-4465-a537-0bd653c5c02e.png)
![RBSparkleOrangeP](https://user-images.githubusercontent.com/949607/128064950-dcc94af7-b824-42d9-a35b-1e1d3b22161c.png)
![RBSparkleOrangePC](https://user-images.githubusercontent.com/949607/128064951-aacf8332-6e28-421d-803c-d06574ca6d30.png)
![RBSparkleOrangeT](https://user-images.githubusercontent.com/949607/128064953-ba180465-2375-4aa9-a857-0e2682e3b0b0.png)
![RBSparkleOrangeTC](https://user-images.githubusercontent.com/949607/128064956-36311f7a-25fd-4ddf-aa91-53b849d677d3.png)
![RBSparkleP](https://user-images.githubusercontent.com/949607/128064959-d7402d7c-ccfe-41e4-8dad-c1758e529316.png)
![RBSparklePC](https://user-images.githubusercontent.com/949607/128064961-42cd94ae-ebe0-4b58-aa1d-4252fd1b0933.png)
![RBSparklePurpleNC](https://user-images.githubusercontent.com/949607/128064962-a02b8f80-d610-476e-9de5-9b17bdd4d834.png)
![RBSparklePurpleP](https://user-images.githubusercontent.com/949607/128064966-3b68fb68-5167-4857-9065-ac0ed9d89496.png)
![RBSparklePurplePC](https://user-images.githubusercontent.com/949607/128064967-67f41683-38c2-4c55-9833-03463d5a6570.png)
![RBSparklePurpleT](https://user-images.githubusercontent.com/949607/128064969-afc6893e-422e-4942-bebe-0a136174fea5.png)
![RBSparklePurpleTC](https://user-images.githubusercontent.com/949607/128064971-c8a0eac6-838e-411d-8676-de42e92fca25.png)
![RBSparkleT](https://user-images.githubusercontent.com/949607/128064973-99f964bc-735c-4b32-a4d6-0f7f06efebc3.png)

**Comment by Smurf-IV** [comment]
And it is mentioned as fixed in Canary:
![image](https://user-images.githubusercontent.com/2418812/128065001-464dbdf1-f2a6-4f0f-9ecf-20603a712b75.png)

**Comment by Smurf-IV** [comment]
> 
> 
> > What is set in the Sparkle themes to make them go darker then ?
> 
> These:
> 
> ![RBSparkleTC](https://user-images.githubusercontent.com/949607/128064938-542bc3d2-3430-47f5-a646-116b15eac646.png)
> ![RBSparkleD](https://user-images.githubusercontent.com/949607/128064941-9ea87b1b-fa52-4119-9a99-70a474418870.png)
> ![RBSparkleDC](https://user-images.githubusercontent.com/949607/128064943-907cb09f-81f8-4798-938a-1b274f3cf8a4.png)
> ![RBSparkleN](https://user-images.githubusercontent.com/949607/128064944-5b38ea28-4f30-4b1d-b55f-148b52ccfcb7.png)
> ![RBSparkleNC](https://user-images.githubusercontent.com/949607/128064947-e503069d-31f2-44cb-bb4e-6cd27128fe0b.png)
> ![RBSparkleOrangeNC](https://user-images.githubusercontent.com/949607/128064948-5e9bbc01-3d48-4465-a537-0bd653c5c02e.png)
> ![RBSparkleOrangeP](https://user-images.githubusercontent.com/949607/128064950-dcc94af7-b824-42d9-a35b-1e1d3b22161c.png)
> ![RBSparkleOrangePC](https://user-images.githubusercontent.com/949607/128064951-aacf8332-6e28-421d-803c-d06574ca6d30.png)
> ![RBSparkleOrangeT](https://user-images.githubusercontent.com/949607/128064953-ba180465-2375-4aa9-a857-0e2682e3b0b0.png)
> ![RBSparkleOrangeTC](https://user-images.githubusercontent.com/949607/128064956-36311f7a-25fd-4ddf-aa91-53b849d677d3.png)
> ![RBSparkleP](https://user-images.githubusercontent.com/949607/128064959-d7402d7c-ccfe-41e4-8dad-c1758e529316.png)
> ![RBSparklePC](https://user-images.githubusercontent.com/949607/128064961-42cd94ae-ebe0-4b58-aa1d-4252fd1b0933.png)
> ![RBSparklePurpleNC](https://user-images.githubusercontent.com/949607/128064962-a02b8f80-d610-476e-9de5-9b17bdd4d834.png)
> ![RBSparklePurpleP](https://user-images.githubusercontent.com/949607/128064966-3b68fb68-5167-4857-9065-ac0ed9d89496.png)
> ![RBSparklePurplePC](https://user-images.githubusercontent.com/949607/128064967-67f41683-38c2-4c55-9833-03463d5a6570.png)
> ![RBSparklePurpleT](https://user-images.githubusercontent.com/949607/128064969-afc6893e-422e-4942-bebe-0a136174fea5.png)
> ![RBSparklePurpleTC](https://user-images.githubusercontent.com/949607/128064971-c8a0eac6-838e-411d-8676-de42e92fca25.png)
> ![RBSparkleT](https://user-images.githubusercontent.com/949607/128064973-99f964bc-735c-4b32-a4d6-0f7f06efebc3.png)

They are radio buttons, not the ####TextBox mentioned in the Title.
Should really create a new Issue for those.

**Comment by Wagnerp** [comment]
Pinning, due to useful resources
