### ISSUE TITLE
[New Feature Request]: The "public" `View Layout` classes should be combined with the panels to allow designer layouts

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#21]
i.e. the `ViewLayoutCenter` class can be combined with a `KryptonPanel`, to allow control(s) to be auto centered, when the parent form changes size.

and, `ViewLayoutFit` to "will split the space equally between the children" in the orientation provided.

**Comment by Smurf-IV** [comment]
Current workaround:
Is to place within a standard table and 
- Add columns set @ 50% around the Panel for the first,
- And 50% for all entries in the 2nd example.

**Comment by Wagnerp** [comment]
> Current workaround:
> Is to place within a standard table and
> 
> * Add columns set @ 50% around the Panel for the first,
> * And 50% for all entries in the 2nd example.

I think I posted this from the old 5.470 project, before I made it readonly.

**Comment by Smurf-IV** [comment]
This will not be needed if #245 is done.

**Comment by Smurf-IV** [comment]
A more active version of the API's
https://github.com/pierresprim/Windows-API-Code-Pack

**Comment by Wagnerp** [comment]
Closing as per #245
