### ISSUE TITLE
[Feature Request]: The `KryptonPropertyGrid` should be moved into the `Standard-Toolkit`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#212]
Should the `KryptonPropertyGrid` be moved into the `Standard-Toolkit`?

**Comment by Smurf-IV** [comment]
It shows up in the "All Windows Forms" - So the answer should be yes.

**Comment by Wagnerp** [comment]
> It shows up in the "All Windows Forms" - So the answer should be yes.

Self assigned this, will begin work after implementing #207

**Comment by Wagnerp** [comment]
Available in build 2109
