### ISSUE TITLE
[Bug]: KryptonTreeView Multi Node Select

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#215]
Most advanced TreeView controls in other libraries support selecting multiple nodes in the view. 

This could be visually added to the existing KryptonTreeView control with a simple workaround. Currently, the control uses the palette StateChecked coloring to draw the selected node (see line 1966 of KryptonTreeView.cs). A single designer property could be added to allow drawing the StateChecked coloring if the node is either selected OR if the node is checked. Then users could use each node's checked property to visually simulate multi selection.

Alternatively, the control could be updated with true multi selection, but this would be much more difficult.

**Comment by Smurf-IV** [comment]
My $0.02 worth:
The idea is to have the standard controls close to the originals with theming.

So that the developers can Add the extra features.
I'm in 2 minds whether this should be an addition to standard or an extension in Extended suite.

Note: The `TreeGridView` in the Extended suite, Version-next (V6) branch allows this.

**Comment by sdreb3421** [comment]
I agree, and this change would just be a theme upgrade which gives the user the ability to show the checked state with a node color instead of a checkbox image.

**Comment by Smurf-IV** [comment]
Having investigated this: I think that the `State###Pressed` is supposed to do this, but it does not seem to be used!
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/d77f80d7-6129-4700-a437-107aade3bd8f)

@Wagnerp thoughts ? Should this be converted to a bug ?

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, will add tags now

**Comment by Smurf-IV** [comment]
- Designer values named `State####Pressed` have changed to `State#####MultiSelect` to reflect usage
  - New TreeView Designer value `MultiSelect` allows drawing of selected items and retrieval via `CheckedNodes`

![example](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/867d55dd-8ca4-41a0-8d63-d2731ae97f9c)
