### ISSUE TITLE
[New Feature Request]: A Better LinkLabel 

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#22]
A windows like LinkLabel where you are able to assign links using Starting poistion/End position like the following:

`this.linkLabel1.Links[0].LinkData = "Register";
this.linkLabel1.Links.Add(24, 9, "www.microsoft.com");
this.linkLabel1.Links.Add(42, 3, "www.msn.com");
//The second link is disabled and will appear as red.
this.linkLabel1.Links[1].Enabled = false;`

**Comment by Wagnerp** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.linklabel.linkarea?view=netcore-3.1

**Comment by Smurf-IV** [comment]
@Wagnerp This can be achieved by using a `KLabel` -> `target`ting the `KLinkLabel`, and then `KLink Label` also using the `ExtraText` part for the rest of the message

**Comment by Wagnerp** [comment]
Closing
