### ISSUE TITLE
[Feature Request]: Can the build also echo out the DateTime, after the time elapsed

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#223]
Can the build also echo out the DateTime, after the time elapsed please?

So that can be used as "Build proof"

Current looks like this:

![image](https://user-images.githubusercontent.com/2418812/127780868-f2b06469-a932-4103-9be4-669ae5131ee4.png)

**Comment by Wagnerp** [comment]
Part of build 2108.1

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/127781481-9e6358e5-58c2-4810-a9d8-1cc054c4fa92.png)
