### ISSUE TITLE
[Bug]: 2108.0 Canary - Cannot set text of a button in designer

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#225]
**To Reproduce**
Add KryptonButton to form
Type something in the text
Tab off
Expected:
- Text to appear in the button
Actual:
- Button text remains the same

**Additional context**
Sigh...
If you go into the Forms designer of a normal button and check out the editor then it has the following:
`[Editor("System.ComponentModel.Design.MultilineStringEditor, System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof (UITypeEditor))]`

What has been done in the 2108 version is to remove everything after `MultilineStringEditor`

Will need to perform a "Search and replace" to put it back, and then retest in net5 / net 6 to see if it the same.

**Comment by Smurf-IV** [comment]
@Wagnerp WTF
![image](https://user-images.githubusercontent.com/2418812/128046918-28a502a6-75b0-4630-950d-dffeff17581d.png)

What is this persistent text thing attempting to do?
I think it should be removed !

**Comment by Smurf-IV** [comment]
The above is triggered in the designer when a user sets the text of a button, and then it is replaced during an `OnPaint`

**Comment by Smurf-IV** [comment]
The above functionality should be in the extended suite, it's nothing to do with standard "Operations" of a button !

**Comment by Wagnerp** [comment]
> @Wagnerp WTF
> ![image](https://user-images.githubusercontent.com/2418812/128046918-28a502a6-75b0-4630-950d-dffeff17581d.png)
> 
> What is this persistent text thing attempting to do?
> I think it should be removed !

@Smurf-IV 

Might have been something I was playing with about the KManager's action button's text. I thought I had put a `bool` value in to disable this feature. Can be removed.

**Comment by Smurf-IV** [comment]
> Might have been something I was playing with about the KManager's action button's text. I thought I had put a `bool` value in to disable this feature. Can be removed.

Will do.

**Comment by Wagnerp** [comment]
> > Might have been something I was playing with about the KManager's action button's text. I thought I had put a `bool` value in to disable this feature. Can be removed.
> 
> Will do.

@Smurf-IV 

Can you wait a bit, as I'm implementing a fix/solution :)

**Comment by Wagnerp** [comment]
Fixed in build 2109

**Comment by Smurf-IV** [comment]
@Wagnerp Can this be placed into Canary 2108.1 please ?

**Comment by Wagnerp** [comment]
> @Wagnerp Can this be placed into Canary 2108.1 please ?

@Smurf-IV See latest pulls
