### ISSUE TITLE
[Bug]: `OverrideFocus` Designer settings do not work or Prevent Ribbon MouseOver Highlighting

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#227]
There is currently no way to prevent ribbon groups from drawing a rounded white highlight when the mouse is over. This is barely noticeable in a light theme, but looks harsh in a dark theme, and interferes with button tracking/checked colors.

![ribbongrouphighlight](https://user-images.githubusercontent.com/1911567/127982047-a4364135-b059-4e37-b985-c839b49ad73a.png)

**Comment by Wagnerp** [comment]
@sdreb3421 

I'll have a look at it.

**Comment by Smurf-IV** [comment]
These are supposed to be overridden with the following
![image](https://user-images.githubusercontent.com/2418812/128063042-543177dc-c8dc-44fd-ac99-ceb5b4ff813d.png)

But even setting them to the orange does not work (I was expecting Transparent to solve the issue!)
The bug is in the usage of these colours (And the fact that they description to make them clear as to what they are supposed to be used for !)

**Comment by Smurf-IV** [comment]
So: Not an **Enhancement**, but a **bug** on `OverrideFocus` colour usage !

**Comment by Wagnerp** [comment]
> So: Not an **Enhancement**, but a **bug** on `OverrideFocus` colour usage !

@Smurf-IV 

Maybe a new bug report? Still, I need to fix the tab background colours for dark modes

**Comment by Wagnerp** [comment]
> These are supposed to be overridden with the following
> ![image](https://user-images.githubusercontent.com/2418812/128063042-543177dc-c8dc-44fd-ac99-ceb5b4ff813d.png)
> 
> But even setting them to the orange does not work (I was expecting Transparent to solve the issue!)
> The bug is in the usage of these colours (And the fact that they description to make them clear as to what they are supposed to be used for !)

@Smurf-IV 

Is this the issue:

```cs
Color.Empty,                      // RibbonTabTracking3
                                                                      Color.Empty,                      // RibbonTabTracking4
                                                                      Color.Empty,                      // RibbonGroupBorder3
                                                                      Color.Empty,                      // RibbonGroupBorder4
```

**Comment by Smurf-IV** [comment]
Those are defaults,
What I am showing above is an override, that is supposed to be applied, but they are not, so empty is being used, and then that reads the theme values only.

**Comment by sdreb3421** [comment]
Do you think this will make it into the next release? Anything I can do to help?

**Comment by Wagnerp** [comment]
Found the possible colours, but are these supposed to be theme colours?

![image](https://user-images.githubusercontent.com/949607/129674787-38d8f800-fa45-4d84-afa9-bb28063448f2.png)

**Comment by Smurf-IV** [comment]
Yes many colours to perform the "Rounded feel" of the track highlight,
But they are not being overridden when selected in the designer, so cannot be disabled in that way either !

**Comment by Wagnerp** [comment]
> Yes many colours to perform the "Rounded feel" of the track highlight,
> But they are not being overridden when selected in the designer, so cannot be disabled in that way either !

Somewhere in the code, the `SetStyle(ControlStyles.SupportsTransparentColor)` is not being used

**Comment by sdreb3421** [comment]
I could try to investigate. Any tips for where to start?

**Comment by Wagnerp** [comment]
> I could try to investigate. Any tips for where to start?

The bug would likely be within the ribbon controls portion of the toolkit i.e. anything to do with the tab & palettes

**Comment by sdreb3421** [comment]
I'll look into it. Do you know which of the listed colors above apply to the highlight? RibbonTabHighlight?

**Comment by Wagnerp** [comment]
> I'll look into it. Do you know which of the listed colors above apply to the highlight? RibbonTabHighlight?

These are taken from the O2k7 Black theme

![image](https://user-images.githubusercontent.com/949607/130350497-0649dbee-2d3c-449b-9ba7-1a707fca4a15.png)

![image](https://user-images.githubusercontent.com/949607/130350552-cf7266b0-76cc-46d4-99bd-4d2ba7f9f6c9.png)

Hope they help

**Comment by sdreb3421** [comment]
I've been digging around all day without success. I assumed there would be a MouseEnter event that could be tracked from method to method until the palette colors were applied, but it's a bit more complicated than that.

**Comment by Wagnerp** [comment]
> I've been digging around all day without success. I assumed there would be a MouseEnter event that could be tracked from method to method until the palette colors were applied, but it's a bit more complicated than that.

Might be in the palette 'base' code

**Comment by sdreb3421** [comment]
Found it! There is a PathGradientBrush named highlightBrush in the RenderMementos.cs file. The comments explain it is for drawing the rounded highlight at bottom center. The colors used look to be fixed. 

It is referenced in in a few classes such as RenderOffice365, but the code that modifies out is grayed out.

It would be nice to set these colors, but would be fine if there was just an option to turn it off, which might be less work.

**Comment by Wagnerp** [comment]
Can you give me the path? Maybe a user defined colour is needed?

**Comment by sdreb3421** [comment]
Source/Krypton Components/Krypton.Toolkit/Rendering/RenderMementos.cs

**Comment by Wagnerp** [comment]
I'll check it out tomorrow

**Comment by sdreb3421** [comment]
Nice, let me know if I can do anything else

**Comment by Wagnerp** [comment]
Do you know which lines they are?

**Comment by sdreb3421** [comment]
487 in rendermementos

**Comment by Wagnerp** [comment]
@Smurf-IV Might need assistance prizing this apart

**Comment by Smurf-IV** [comment]
Sure.. Thanks for the research 👍 
I'll have a bash this week at it

**Comment by Smurf-IV** [comment]
Getting there:
Showing Lime override:
![image](https://user-images.githubusercontent.com/2418812/131246166-d73a12d4-8ca1-47a1-bd77-2732b6669647.png)

**Comment by Smurf-IV** [comment]
New Designer area 
![image](https://user-images.githubusercontent.com/2418812/131246185-fa1afdd9-d08d-42c6-9c68-0615e518ce08.png)

**Comment by Smurf-IV** [comment]
The Fix works in All Themes apart from Office2k7 and Sparkle, where it is diminished but still highlights with white!

**Comment by Smurf-IV** [comment]
To disable highlighting - Just change the Above designer elements to `Transparent`

**Comment by sdreb3421** [comment]
Nice work!
