### ISSUE TITLE
[Bug]: 2108.0 Canary - Cannot set button text progrmatically

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#229]
maybe related to #225 

**Describe the bug**
If an event changes the text of a button, then it is not drawn in the view until the view is completely recreated.

**Comment by Smurf-IV** [comment]
![ButtonChangedProgmattically](https://user-images.githubusercontent.com/2418812/128056704-1c790d40-fc29-43a3-8a33-5e2f54949668.gif)

**Comment by Wagnerp** [comment]
Pushed fixes for #225, #229 & #230
