### ISSUE TITLE
[Bug]: Office 365 - Black (Dark mode) Messes up combo boxes

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#237]
![image](https://user-images.githubusercontent.com/2418812/128154965-de5142ec-096f-4e45-b999-c14aaee3dec0.png)

**Comment by Smurf-IV** [comment]
And Office 2007 - Black (Dark Mode)

**Comment by Wagnerp** [comment]
@Smurf-IV Is there a value that controls the CB dropdown background?

**Comment by Smurf-IV** [comment]
Yes
![image](https://user-images.githubusercontent.com/2418812/133976612-b0c3ef58-c296-4d82-b8f9-bf59afd63b0e.png)

And there is also the equivalent in the ComboBox back as well.

The Palette designer should have these as visible entities to check

**Comment by Wagnerp** [comment]
> Yes
> ![image](https://user-images.githubusercontent.com/2418812/133976612-b0c3ef58-c296-4d82-b8f9-bf59afd63b0e.png)
> 
> And there is also the equivalent in the ComboBox back as well.
> 
> The Palette designer should have these as visible entities to check

Ok, just need to decipher what value it is in the 'built-in palettes'

**Comment by Wagnerp** [comment]
I've worked out what controls it, **but** not the variable to change... yet!

![image](https://user-images.githubusercontent.com/949607/134048677-7bda0cb5-c62b-4ccb-a41d-513a29135596.png)

**Comment by Wagnerp** [comment]
I'm confused... I thought the following would operate it, but no it doesn't

```cs
Color.Black,                      // InputDropDownNormal1
Color.Transparent,                // InputDropDownNormal2
```

?

**Comment by Wagnerp** [comment]
@Smurf-IV How did you setup the colours for #138?

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV How did you setup the colours for #138?

138 has nothing to do with colours.. Another number ?

**Comment by Wagnerp** [comment]
> > @Smurf-IV How did you setup the colours for #138?
> 
> 138 has nothing to do with colours.. Another number ?

I don't think that colours from the base palettes were wired in, could you have a look please? :)

**Comment by Smurf-IV** [comment]
> 
> 
> > > @Smurf-IV How did you setup the colours for #138?
> > 
> > 
> > 138 has nothing to do with colours.. Another number ?
> 
> I don't think that colours from the base palettes were wired in, could you have a look please? :)

Again, what has 138 (Drag'n'Drop listview) got to do colours ?

**Comment by Wagnerp** [comment]
> > > > @Smurf-IV How did you setup the colours for #138?
> > > 
> > > 
> > > 138 has nothing to do with colours.. Another number ?
> > 
> > 
> > I don't think that colours from the base palettes were wired in, could you have a look please? :)
> 
> Again, what has 138 (Drag'n'Drop listview) got to do colours ?

I was thinking about the background of the item

![image](https://user-images.githubusercontent.com/949607/135406893-00a1c908-0bcd-4456-bf47-f5814e8d0ef7.png)

I just can't find where the dropdown code is handled.

**Comment by Wagnerp** [comment]
Finally, found the code that handles combobox drop down colours! :)

**Comment by Wagnerp** [comment]
Fixed in build 2201.
