### ISSUE TITLE
[Bug]: Toolstrip combo boxes do not have the theme background applied

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#239]
Found as part of the "Dark / Light" testing, but it applies to all themes.
The Drop Buttons are themed.
But the background is not:
![image](https://user-images.githubusercontent.com/2418812/128157374-6a3f24fc-e3ab-45f4-861a-960d07d94cae.png)

Cannot state if the highlight or fonts are also "Not" applied.

**Comment by giduac** [comment]
@Wagnerp 
This then would also be in the same category as 1524?

**Comment by Wagnerp** [comment]
@giduac Yes, tagging #1524

**Comment by Wagnerp** [comment]
Hi @giduac & @Smurf-IV 

So, the 'bug' is related to the `BackColor` property. I don't know how you'd like to go about this?

**Comment by giduac** [comment]
@Wagnerp 
Can the color be set through a theme ?

**Comment by Wagnerp** [comment]
> @Wagnerp Can the color be set through a theme ?

@giduac The theme colours can be theoretically routed through... Thoughts @Smurf-IV?

**Comment by Smurf-IV** [comment]
> > @Wagnerp Can the color be set through a theme ?
> 
> @giduac The theme colours can be theoretically routed through... Thoughts @Smurf-IV?

Of course, That's how KComboBoxs work.

**Comment by Wagnerp** [comment]
> > > @Wagnerp Can the color be set through a theme ?
> > 
> > 
> > @giduac The theme colours can be theoretically routed through... Thoughts @Smurf-IV?
> 
> Of course, That's how KComboBoxs work.

The other idea would be to place a KComboBox into a ToolStripControl i.e. https://github.com/Krypton-Suite/Extended-Toolkit/blob/master/Source/Krypton%20Toolkit/Krypton.Toolkit.Suite.Extended.Tool.Strip.Items/Controls/General/KryptonColourButtonToolStripMenuItem.cs

**Comment by Smurf-IV** [comment]
Yes of course, but that would be another control, 
and the static text and buttons etc are already handled via some "Magic" inside the theming

**Comment by giduac** [comment]
@Wagnerp 
There's also a [ToolStripControlHost Class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripcontrolhost?view=windowsdesktop-8.0) that can be used to embed non toolstrip controls into a toolstrip. 

Give that a go to see if the K-controls can be embedded in there as well??

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac 

I'll have a fiddle with the above mentioned `ToolStripControlHost` class. I think there's some code in the Extended TK, which can be bought over...

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 

`public class KryptonToolStrip : ToolStrip`

Derives from Winforms ToolStrip so the KStrip can take ToolstripControlHost objects.

**Comment by Wagnerp** [comment]
Done! PR incoming

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/a7301553-5611-4b6c-93ef-9d42ebd3146c)

**Comment by giduac** [comment]
Looks great!!
