### ISSUE TITLE
[Question]: Any plans for strongly named assembly in NuGet?

### ISSUE THREAD

**Issue by pankaj-nikam** [Krypton-Suite/Standard-Toolkit#24]
Hi team,

I used the older framework which is now deprecated, I tried upgrading to this version, however one of my project is signed. I cannot remove the signing and because of that, I am getting the following error when I run the project:

`'Could not load file or assembly 'Krypton.Toolkit, Version=5.550.2011.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'`

I also tried to uncheck the singing and check if its working, it works however, the project uses isolated storage, when we uncheck the signing, the isolated storage gets cleared which is not the correct way to handle it,

Can you please provide us with a strongly named assembly in nuget so that the people who were using it wont face this issue too?

Thanks.

**Comment by Wagnerp** [comment]
Hi @pankaj-nikam 

Thanks for posting your issue. I have now uploaded separate signed packages to NuGet which should fix this. Look for packages ending with either `*.Signed` or `*.Lite.Signed`.

**Comment by pankaj-nikam** [comment]
Hi @Wagnerp , Thank you for such quick update, however, when I installed the lite version, I am unable to see the designer, it is opening in C# editor, do I need a full version instead of lite for designer? Please guide.
Thanks.

**Comment by Wagnerp** [comment]
Hi @pankaj-nikam 

Have you removed all references to `ComponentFactory.` yet? Also are you using .NET Core?

**Comment by dax-leo** [comment]
@pankaj-nikam 
You are most likely using .net core. If true designer is not visible.
You need to have VS Preview version or wait for full .NET 5 release (coming soon) with proper VS update.

**Comment by pankaj-nikam** [comment]
Hi @Wagnerp ,@dax-leo no, it's dotnet 4.6.2.

**Comment by Wagnerp** [comment]
Hi @pankaj-nikam 

Are you using the 'Lite' versions, also have you tried using the full versions? Also what error messages (if any) are displayed?

**Comment by Wagnerp** [comment]
Hi @pankaj-nikam 

If you can, that would be great. Lite versions only contain binaries for .NET Framework 4.5, .NET Core 3.1 and .NET 5. Full versions support from .NET Framework 3.5 through to .NET 5.

**Comment by pankaj-nikam** [comment]
Hi @Wagnerp , Yes, installing the full version enabled the designer. Thank you so much for help and maintaining this project for the future version of .NET too 👍

**Comment by Wagnerp** [comment]
Hi @pankaj-nikam 

No problem, good to see that it's now working!

**Comment by IADTIL** [comment]
The libraries in the *.Signed NuGet packages (65.22.6.152) are not signed.
