### ISSUE TITLE
[Enhancement]: `CueHint` features does not exist on the `KryptonMaskedTextBox` control

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#240]
**Describe the bug**
The `CueHint` features found in the `KryptonTextBox` does not exist on the `KryptonMaskedTextBox` control

**Comment by Smurf-IV** [comment]
@Wagnerp I do not understand why this is needed..
The Masked Edit already has a "Hint" with the characters of the mask:
![image](https://user-images.githubusercontent.com/2418812/128593120-a0635f94-4120-48ad-a719-0bb8fcd6b827.png)

**Comment by Smurf-IV** [comment]
And the font / colour can be controlled via State#### designer elements as normal:
![image](https://user-images.githubusercontent.com/2418812/128593194-c9616ee9-8552-47a9-bb17-6d21696c08f7.png)

**Comment by Wagnerp** [comment]
Ahh... didn't realise, I was doing some work the other day & couldn't find it
