### ISSUE TITLE
[Bug]: 2108.2 Canary KryptonMessageBox display is off the left of the display area

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#242]
![image](https://user-images.githubusercontent.com/2418812/128522637-076606ad-cc5e-4ed5-b3e4-2f080eef4205.png)

**Comment by Smurf-IV** [comment]
The Text is retrieved from the tooltip which looks like this:
![image](https://user-images.githubusercontent.com/2418812/128522831-8a8a87ea-9b3c-4d48-82d8-1a8649f9275e.png)

**Comment by Smurf-IV** [comment]
Single line messageBox seems okay:
![image](https://user-images.githubusercontent.com/2418812/128523073-5f34b93e-b8eb-4de6-b2ef-09543230979b.png)

**Comment by Wagnerp** [comment]
Does it utilise a `KryptonWrapLabel`?

**Comment by Smurf-IV** [comment]
Looks like it:
![image](https://user-images.githubusercontent.com/2418812/128590922-db2332a2-c40f-465d-84ad-1adb80d644e0.png)

**Comment by Wagnerp** [comment]
How about adding an option to set the `TextAlignment`?

**Comment by Smurf-IV** [comment]
No.. It should work like a normal MessageBox, but with the current theme.
The KryptonMessageBox code it getting a little out of hand/scope in the "Standard Toolkit"

**Comment by Smurf-IV** [comment]
This is even worse that I thought - Where is the Icon ?
![image](https://user-images.githubusercontent.com/2418812/128593750-c2b51d8b-1f3b-4bb4-bc27-d0a9982ac79d.png)

And the Opening problem is created when there is no icon selected

**Comment by Wagnerp** [comment]
Would it be easier to completely redo the `KryptonMessageBox`, as the code is really clunky?

**Comment by Smurf-IV** [comment]
Yes it probably would be..
When were these introduced?
`float? cornerRadius, bool? useBlur, int? blurRadius, KryptonForm parentWindow = null`

**Comment by Wagnerp** [comment]
They were in build 2108. Plus I was struggling to find a solution to the checkbox text issue. I had thought about splitting the footer into two, but the design code makes it incredibly hard to figure out what does what.

**Comment by Smurf-IV** [comment]
So if it was removed, and these feature put into the Extended kit, then that would be better, (Along with the KryptonMessageBoxManager) ?

**Comment by Wagnerp** [comment]
Yes

**Comment by Smurf-IV** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2418812/128601353-2b1549b2-9718-49e0-b63f-14481a79b524.png)
