### ISSUE TITLE
[Feature Request]: Font Dialog is in the Main Forms elements - Where is Kryptons' Standard themed equivalent

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#243]
e.g. Dark theme:
![image](https://user-images.githubusercontent.com/2418812/128525944-5d2bf8d2-a769-4b3b-b57e-832b7def450a.png)

**Comment by Smurf-IV** [comment]
It might be a case of just deriving from the Winform, Catching the OnLoad, setting colours of elements, and then display..

Rather than trying to re-create the full path of code:
https://referencesource.microsoft.com/#system.windows.forms/winforms/Managed/System/WinForms/FontDialog.cs

Or using outdated interops to get to the base OS classes.

**Comment by Wagnerp** [comment]
This could help

https://www.codeproject.com/Articles/10706/Font-ListBox-and-ComboBox-Controls-with-Top-5-Favo

**Comment by Smurf-IV** [comment]
> 
> 
> This could help
> 
> https://www.codeproject.com/Articles/10706/Font-ListBox-and-ComboBox-Controls-with-Top-5-Favo

That would be a nice addition to the Extended ComboBox / List projects.
And
His other project would be nice as well:
https://www.codeproject.com/Articles/10688/BevelLine-Control-with-Designer-Selection-Rules
With the Standard Theme overrides applied ;-)

**Comment by Smurf-IV** [comment]
Getting there..
What I am trying to do is something similar to the Delphi VCL Theming (No idea how they do the magic - but they do not redesign a form to "Look" like a control [Like they do in mono - which is another option])
So the idea is 
- to keep the native control native
- Override their drawing via the re-use of Krypton drawing elements
- Make this code generic so that it can be applied to all "OS Common Dialogs"


The following picture shows 
- Test App in VS Designer
- App running and Office 2010 - Black selected
- "Kryptonised" FontDialog with the background and the `Colour:` label converted
- All control positions and text taken from the control.
![image](https://user-images.githubusercontent.com/2418812/128917552-d3505733-9f98-4714-b90a-11eb4f60009d.png)

**Comment by Wagnerp** [comment]
Can something similar be done for file dialogs?

**Comment by Smurf-IV** [comment]
Yes, What I am aiming for is anything that is derived from the `CommonDialog` base class wrapper

**Comment by Smurf-IV** [comment]
Another update to generic overloading
- Managed to improve the background colour replacement
- Group and label fonts are changed
- All Label colours are changed (Not Groups yet !)
![image](https://user-images.githubusercontent.com/2418812/129092090-42ec76d1-77e7-4528-8f05-5c84fdf0da99.png)

**Comment by Smurf-IV** [comment]
And tonights offering is:
![image](https://user-images.githubusercontent.com/2418812/129253006-2b2aecdd-27c8-4e70-a30f-30e50cf8d09d.png)

Button replacement !

**Comment by Smurf-IV** [comment]
Removed the Drawing blips around the buttons:
![image](https://user-images.githubusercontent.com/2418812/129257541-35a88098-7687-4c84-b6c2-911188a76917.png)

**Comment by Smurf-IV** [comment]
Erm.. Done:
![image](https://user-images.githubusercontent.com/2418812/129397631-05f6eb94-fae5-4bb1-b279-8a23108e51fe.png)

BUT,
Now need to extract the code into a utility class, so that it can be applied to the other Common Dialogs

**Comment by Smurf-IV** [comment]
Oh, and also to wrap the control in a KryptonForm as a toolbox ;-)
![image](https://user-images.githubusercontent.com/2418812/129397874-a226850d-fabd-4f81-b26b-1b80efe0029b.png)

**Comment by Wagnerp** [comment]
Is it going to be possible to use the breadcrumb control for file dialogs?

Still testing the new inputbox :)

**Comment by Smurf-IV** [comment]
> Is it going to be possible to use the breadcrumb control for file dialogs?


Not sure that will be a wise thing to do, as it entails lot's of linkage out to an existing control(s), so probably not.

**Comment by Smurf-IV** [comment]
Done:
![image](https://user-images.githubusercontent.com/2418812/129442576-141db79c-379f-41e1-bee0-c438687a5dd5.png)

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/129443562-6c296c39-9a8a-4273-97f4-1aa7c14a3c6a.png)
