### ISSUE TITLE
[Bug]: Ribbon on .NET core / .NET 5 winforms

### ISSUE THREAD

**Issue by russgreen** [Krypton-Suite/Standard-Toolkit#25]
I can get as far as adding a ribbon, creating tabs, adding ribbon groups to the tabs but when I try and add items to those groups I get a message.

Cannot create an instance of Krypton.Ribbon.KryptonRibbonGroupContainer it is an abstract class.

**Comment by Wagnerp** [comment]
Hi @russgreen 

Just a quick question, are you using the designer?

**Comment by russgreen** [comment]
The designer does work at all on the form. Creating via properties panel RibbonTabs...

**Comment by Wagnerp** [comment]
Have you tried adding `net48` to your `TargetFrameworks`, as this will restore the designer?

**Comment by russgreen** [comment]
I hadn’t.  But thank you.  That’s done the trick.

**Comment by Wagnerp** [comment]
It's because MS doesn't fully support the designer in .NET Core/.NET yet. I don't know why.
