### ISSUE TITLE
[Question]: Only support 64bit

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#258]
Given that the industry is moving away from supporting x86, is it time now to exclusively support 64bit architectures?

**Comment by Smurf-IV** [comment]
No. It is not the job of assemblies to dictate the "Bitness" of the application (Unless loading in legacy `c` DLL's, and even then it should be handled)
See how joveler does the loading of the system ZLib (or xz) dll's and still makes the assembly "AnyCPU"

Also - if this is going to be the case - then most of the support below `.net4.50 framework` can be removed.

**Comment by Smurf-IV** [comment]
Also, Prior to Studio 17, All versions are 32 bit, so that would mean that this would never work in a designer!!
