### ISSUE TITLE
[Feature Request]: Remove non-Krypton column type entries in KryptonDataGrid

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#26]
There are `ColumnType` entries in `KryptonDataGrid`, which are unneeded. Solution, is to remove them.

**Comment by Smurf-IV** [comment]
@Wagnerp Just Checked in `alpha`, and I cannot find `ColumnType`.

What is this referring to ?

**Comment by DarthVader85PA** [comment]
@Smurf-IV I think @Wagnerp reffered to my Bug #27. 
He made this "Feature Request" after I asked for help on Discord.

Greetings Danny

**Comment by Wagnerp** [comment]
> @Wagnerp Just Checked in `alpha`, and I cannot find `ColumnType`.
> 
> What is this referring to ?

@Smurf-IV This was linked to #27 referred to @DarthVader85PA . Sorry for the confusion :)

**Comment by Smurf-IV** [comment]
Fix this in #27 by removing the visibility of the Icon column type from the selection
