### ISSUE TITLE
[Question]: How goes the winforms designer work?

### ISSUE THREAD

**Issue by Tape-Worm** [Krypton-Suite/Standard-Toolkit#260]
It's been some time since you've released for 3.1 and .NET 5 (and soon .NET 6).

I can easily use the controls with .NET 5, but designing is another matter entirely. For example, the ribbon, it just does not work through the .NET 5 winforms designer. 

I know we can use the multi-target approach and that works somewhat, but it is a cumbersome hack at best. Also, I'm sure some others like me have zero desire to use .NET 4.x once we've upgraded our stuff to 5.

So how goes the work on getting the controls working in the designer? Are there any roadblocks that are keeping things from progressing?

**Comment by Smurf-IV** [comment]
Can you please have a go with the latest "2108.x Canary" build, as quite a lot has been done and investigated (And hopefully worked around) to get the designer to be "More happy" (About the best way I could put that) with the Krypton dll's.

I may have missed some controls, or even missed something completely due to having a dedicated Krypton Dev environment and not a Developer "Using Krypton" environment.

**Comment by Wagnerp** [comment]
Hi @Tape-Worm,

It's good to see you again!

The current workaround for this bug is to add the following to your `csproj` file:

`<TargetFrameworks>net48;net5.0-windows</TargetFrameworks>`

Hope this helps!

**Comment by Tape-Worm** [comment]
@Wagnerp 
I already knew about the workaround, I was just wondering how you guys were doing regarding getting the designers up and running.

@Smurf-IV 
I'll have a go at it some time tomorrow and let you know what I find.

**Comment by Wagnerp** [comment]
@Tape-Worm 

The designers do work under .NET/Core, but the smart tags don't

**Comment by Smurf-IV** [comment]
I have been concentrating on the "Many" control in the toolkit, I have not got round to all the idiosyncrasies of the other kits yet.
Is the above reported as a stand-alone bug ? And can it be linked to this.
Then this can be used as an investigation into all the controls as devs go through.

**Comment by Smurf-IV** [comment]
Don;t be frightened to raise bugs / defects / Issues.. 

We can then check to see if it's real and it helps others who then search through the bug discussions to see how things progressed / fixed / went away ;-)

**Comment by Tape-Worm** [comment]
I honestly didn't know if this was a bug or unfinished functionality, so I didn't want to make an assumption. I'll post as a bug next time I find something that's indeterminant.
