### ISSUE TITLE
[Bug]: `KryptonPalette` does not work (6.0.2108.x)

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#261]
**Describe the bug**
As posted by <#User#> on Discord

_I just started testing Standard Toolkit Canary (6.0.2108.1). I see that the KryptonManager has been integrated into the KryptonForm, that's nice. I added a palette to the form, assigned it as the GlobalPalette in the manager, and I'm seeing the palette changes in the designer. However, when I run the project, the palette is not being applied. When reverting to the previous canary version and utilizing an added KryptonManager, everything works. I tested this on both a Framework and NET5 project with the same results._

**Comment by sdreb3421** [comment]
I just upgraded to the latest stable build (5.550.2108) and found there is still an issue with the KryptonForm's built in KryptonManager and KryptonPalette. The following existing/new issues were found:

1. When keeping the old KManager object (added separately at design time), the built in KManager seems to reflect its state (unexpected).
2. When deleting the old KManager object, the built in KManager does not retain the selected palette after VisualStudio restart.
3. When using the built in KPalette, the palette changes are seen in the designer but not at runtime.
4. When keeping the old KManager and KPalette, everything still works as expected.

**Comment by sdreb3421** [comment]
The truth is that this is a small issue for me since the new features are not explicitly necessary.

**Comment by Smurf-IV** [comment]
@Wagnerp You have requested help, but why was this feature added ?

**Comment by Wagnerp** [comment]
@Smurf-IV Was intended to make switching themes easier, without having to use another control, but something is not updating to reflect the changes made to the KManager, yet it's fine if you use code.

**Comment by Smurf-IV** [comment]
The designer does not know when the values have been changed from the default, so, these will not be stored in the `##.Designer.cs file:`
![image](https://user-images.githubusercontent.com/2418812/133846956-4da8a76d-ddc8-4381-a7ba-7b977fd6195d.png)

**Comment by Smurf-IV** [comment]
@Wagnerp Do you want me to fix this ?

**Comment by Wagnerp** [comment]
> @Wagnerp Do you want me to fix this ?

@Smurf-IV Yes please :)

**Comment by Smurf-IV** [comment]
Having tried to work out what to do about the global serialisation of these values, I think that they should "NOT" belong to every form that is created in an application.
Therefore I propose the removal of these 2 things from the form properties, and go back to the default usage.
I.e. a single form contains a kryptonManager element, and "It" and only it modifies the global world !

**Comment by Wagnerp** [comment]
> @Wagnerp
> Having tried to work out what to do about the global serialisation of these values, I think that they should "NOT" belong to every form that is created in an application.
> Therefore I propose the removal of these 2 things from the form properties, and go back to the default usage.
> I.e. a single form contains a kryptonManager element, and "It" and only it modifies the global world !

@Smurf-IV 

Ok, I'll revert it
