### ISSUE TITLE
[Feature Request]: "FolderBrowser Dialog" is in the Main Forms elements - Where is Kryptons' Standard themed equivalent 

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#266]
Moving on from #243 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.commondialog?view=net-5.0

**Comment by Smurf-IV** [comment]
This one is a `sealed class`.
Also there are big differences in the Frameworks implementations..
I do not really want to aim at the lowest common denominator, so might take the .Net5/6 route

**Comment by Smurf-IV** [comment]
The Default winform Dialog:
![image](https://user-images.githubusercontent.com/2418812/129476803-8db079f6-4144-4be3-836d-0583b2c3a8e0.png)

**Comment by Smurf-IV** [comment]
1st Step done: Implement code to use "Latest" Dialog handlers, And the "Use Description For Title" which is not available by default :-)
![image](https://user-images.githubusercontent.com/2418812/129477600-e42a6bdd-3e7e-437b-9267-068baaffe923.png)

**Comment by Smurf-IV** [comment]
This "work" is way bigger than it should be.. And I still have not got the theming working.....!!!$%$^%$^^
Might have to **_park_** this

**Comment by Smurf-IV** [comment]
Got lost whilst implementing
Way too messy - Will not implement (Yet)

**Comment by Wagnerp** [comment]
@Smurf-IV Is the WindowsAPICodePack version different? I do have the source code if you want to have a look?

**Comment by Smurf-IV** [comment]
I do not want to use that, as it will bloat the dependencies of the standard kit.(i.e.none currently). 
It could go into the "Next-Version" extended as that is bloat aware anyway.

**Comment by Smurf-IV** [comment]
> WindowsAPICodePack

https://github.com/contre/Windows-API-Code-Pack-1.1/issues/38

Which means the same problems !

**Comment by Smurf-IV** [comment]
A more active version of the API's
https://github.com/pierresprim/Windows-API-Code-Pack
