### ISSUE TITLE
[Feature Request]: "Open / Save File Dialog" are in the Main Forms elements - Where is Kryptons' Standard themed equivalent 

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#267]
Moving on from #243 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.commondialog?view=net-5.0

**Comment by Smurf-IV** [comment]
Got lost whilst performing #263 
Way too messy - Will not implement (Yet)

**Comment by Smurf-IV** [comment]
OOki.Dialogs now has a Winform code base which could be used to fix this.
https://github.com/ookii-dialogs/ookii-dialogs-winforms

**Comment by Wagnerp** [comment]
Wonder if the same could be done for transfer & credential dialogs?

**Comment by Smurf-IV** [comment]
> Wonder if the same could be done for transfer & credential dialogs?

Those would be "Extended" feature requests ;-)

**Comment by Smurf-IV** [comment]
Hmm :-(
OOki.Dialogs.Winforms is a thin wrapper over the common FileDialog to force some things to always work.

**Comment by Smurf-IV** [comment]
Must remember that if setting readonly to force "Vista Style":
![image](https://user-images.githubusercontent.com/2418812/213867798-f3a8f039-0aac-429d-8a44-b77fe51fe95a.png)

Should be similar to this:
![image](https://user-images.githubusercontent.com/2418812/213867878-b9e2f51e-b764-4e92-9ed6-01b52e27b92c.png)

**Comment by Smurf-IV** [comment]
This appears to be hard work:
https://learn.microsoft.com/en-us/previous-versions/dotnet/articles/ms996463(v=msdn.10)?redirectedfrom=MSDN

**Comment by Wagnerp** [comment]
> This appears to be hard work: https://learn.microsoft.com/en-us/previous-versions/dotnet/articles/ms996463(v=msdn.10)?redirectedfrom=MSDN

Managed to download the `msi`, here's what's in it 
[Extensible Dialogs Source.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/10472458/Extensible.Dialogs.Source.zip)

**Comment by Smurf-IV** [comment]
So have been taking the code from Ookii, and Winforms .net 7 and have completed opening the "new" style Open Dialog.
But, there is still no "Hook" function just and Show, that then returns a DialogResult, with an event for the "DoFileOk" redirect (So that multiselect can be worked etc.)

Skinning by brute force is also something that has been tried (Via C++ direct) and it seems to fail often:
https://forum.codejock.com/problem-skinning-cfiledialog_topic17016.html

So the "only" way left now (I feel) is to have a complete Open / Save / Folder Form set-up, with Krypton controls := a massive effort!

**Comment by Wagnerp** [comment]
@Smurf-IV 

Have you had a look at the [winforms](https://github.com/dotnet/winforms) repo, specifically in `src/System.Windows.Forms/src/System/Windows/Forms`?

**Comment by Smurf-IV** [comment]
Yes, Like I stated I used the Winforms 7 code.

>Note: All dialogs are related to [this](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs)

Which is great for FileDialg using the old layout, BUT for the Vista style it is routed through the Com interfaces via https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs

Therefore: no HookProc.

**Comment by Smurf-IV** [comment]
Try this:
https://learn.microsoft.com/en-us/archive/msdn-magazine/2002/november/cutting-edge-using-windows-hooks-to-enhance-messagebox-in-net

**Comment by Wagnerp** [comment]
> Try this: https://learn.microsoft.com/en-us/archive/msdn-magazine/2002/november/cutting-edge-using-windows-hooks-to-enhance-messagebox-in-net

Source: 
[Source.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/10720530/Source.zip)

**Comment by Smurf-IV** [comment]
@Wagnerp This is as close as it will allow me to get to a fully themed FileOpen Form:
![image](https://user-images.githubusercontent.com/2418812/227784627-54f90322-43ae-48bd-b37f-d1dc7f350616.png)

Thoughts ?

**Comment by Wagnerp** [comment]
@Smurf-IV That's fine, we can put it into testing and ask devs for thoughts?

**Comment by Smurf-IV** [comment]
I'll do the `SaveAs` and then PR it next w/e

**Comment by Wagnerp** [comment]
> I'll do the `SaveAs` and then PR it next w/e

I'll continue on the toolbar buttons this week. Something has got mangled up somewhere...

**Comment by Smurf-IV** [comment]
Darn it.. Have to also take into account scaling ..
No PR this w/e !

**Comment by Smurf-IV** [comment]
And the Shell File Save control(s), is a mess compared with the Open !

**Comment by Smurf-IV** [comment]
![example](https://user-images.githubusercontent.com/2418812/230565780-3be0d2ea-1d02-4e7b-a858-8a17cad39704.png)

![example](https://user-images.githubusercontent.com/2418812/230565831-440bd24b-99a1-4072-a4f0-117c85480655.png)
