### ISSUE TITLE
[Feature Request]: "Print Dialog" is in the Main Forms elements - Where is Kryptons' Standard themed equivalent 

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#269]
Moving on from #243 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.commondialog?view=net-5.0

**Comment by Smurf-IV** [comment]
So this is the `XP style`
![image](https://user-images.githubusercontent.com/2418812/129934231-a4282910-e00b-4834-adbb-8210b10c29af.png)

**Comment by Smurf-IV** [comment]
And this is the `New` style (i.e. the `UseEXDialog` is the default `false`)
![image](https://user-images.githubusercontent.com/2418812/129934429-bfddbd16-a310-4563-920d-c2d195207013.png)

**Comment by Smurf-IV** [comment]
Disabled are not hidden (Apart from the `Apply` and `Help`)
![image](https://user-images.githubusercontent.com/2418812/129945102-2af22884-c8e8-4c60-881c-96f603583dad.png)

**Comment by Smurf-IV** [comment]
Darn it.. Another sealed class !!

**Comment by Smurf-IV** [comment]
Old:
![image](https://user-images.githubusercontent.com/2418812/130112213-92917591-f5d1-406a-88a3-1d73e818fdff.png)
Still some things to sort..

**Comment by Smurf-IV** [comment]
Nailed the "Standard"
![image](https://user-images.githubusercontent.com/2418812/130129629-8d5f2731-0273-4f90-8d22-0b5f09b8666b.png)

**Comment by Smurf-IV** [comment]
Going to have to leave the "EX Version":
as it does not give enough control over the objects being created, and some of them do not show up (i.e. the pictures and some text!)

So I could make the code clean and not support the EX, or leave it in for another attempt later ??

**Comment by Wagnerp** [comment]
Could the "EX Version" be a future extended toolkit feature?

**Comment by Smurf-IV** [comment]
Ok, I'll comment out the code for the Ex, so that it is not "Lost"
And then a revisit at some future point or placement into Extended if it is a "Revamp / Wholesale" replace.

**Comment by Smurf-IV** [comment]
Just noticed that the radio buttons where not being replaced !!!

**Comment by Smurf-IV** [comment]
![example](https://user-images.githubusercontent.com/2418812/130280667-85e25285-9496-4778-9f6e-1abcc616ed9d.png)
Done.
Tested that clicking the radio buttons etc act as they are supposed to (Does help if the collate becomes enabled :-))
