### ISSUE TITLE
[Bug]: Cannot use KryptonDataGridViewIconColumn with KryptonDataGridView

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#27]
**Describe the bug**
When a user selects `KryptonDataGridViewIconColumn` as a column type, a error is thrown stating a 'constructor cannot be found'.

**To Reproduce**
![error_datagrid_icon_column](https://user-images.githubusercontent.com/949607/99365466-3ea01b00-28af-11eb-954c-2c0a149c6ee3.gif)

**Comment by DarthVader85PA** [comment]
@Wagnerp Thanks! Greetings from Germany (James_007 in Discord) :)

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

I found the issue, it appears that the `KryptonDataGridViewIconColumn` class is the base for the other column types (the name is confusing). The resolution is to create another class for icons or to convert icons to bitmap images on the go.

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

At the moment I use `DataGridViewImageColumn`. That works for me.
![grafik](https://user-images.githubusercontent.com/32876506/99402877-1eda1880-28ea-11eb-8c9e-b2c53c2c8889.png)

**Comment by Smurf-IV** [comment]
Fix this by removing the visibility of the Icon column type from the selection

**Comment by Smurf-IV** [comment]
@Wagnerp Fix in `alpha` or `version-next` ?

**Comment by Wagnerp** [comment]
> @Wagnerp Fix in `alpha` or `version-next` ?

@Smurf-IV `version-next` would be best

**Comment by Smurf-IV** [comment]
Hmm.. "Version_Next" does not exist in Standard :-!

**Comment by Wagnerp** [comment]
> Hmm.. "Version_Next" does not exist in Standard :-!

Sorry, I meant `alpha` vNext is extended toolkit, getting confused

**Comment by Smurf-IV** [comment]
In Progress:
![image](https://user-images.githubusercontent.com/2418812/126065912-4fcdc6f1-c95e-4640-972c-20d39f028d7b.png)
