### ISSUE TITLE
[Bug]: CueHint text is "Bottom" clipped by default

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#271]
**Describe the bug**
![image](https://user-images.githubusercontent.com/949607/129474712-dbb45276-1b0f-4108-9009-35724a6ac9ac.png)

![image](https://user-images.githubusercontent.com/949607/129474725-20a51129-68ec-4f16-8c47-eea96fcc8378.png)

**Comment by Smurf-IV** [comment]
Also the "default" padding in the designer looks like it is modified when first placing a new text box:
![image](https://user-images.githubusercontent.com/2418812/129615237-e17eca52-1f5b-429a-bb18-0ad068f3427e.png)

**Comment by Smurf-IV** [comment]
Also added `TextV` so that it can be aligned in the middle of Mult-line boxes
![image](https://user-images.githubusercontent.com/2418812/129930553-b3f9013f-8bb4-4e2d-8e94-cb011b861bc8.png)
