### ISSUE TITLE
[Bug]: KryptonScrollbar: scroll value cannot be set

### ISSUE THREAD

**Issue by kmsbecker** [Krypton-Suite/Standard-Toolkit#281]
Dear developers,

its realy great that the newest version (Krypton.Toolkit.Canary.Light V6.0.2108.1) now has a KryptonScrollBar control! It was realy missing".

However, it is not possible to set the scroll position, neither programmatically nor in the designer window.
If I e.g. try to make an assignment as 'KryptonScrollBar.value = 50 nothing' nothing happens (and if I try to do the same the designer it simply resets the value of the input field back to zero).

best,
Klaus

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 10.0.19042]

**Additional context**

**Comment by Wagnerp** [comment]
Hi @kmsbecker 

Think I've fixed the bug, `Value` was not setting the field value `_value`

**Comment by kmsbecker** [comment]
wow, fast as light speed! Thanks! You made my day!
Klaus

⁣BlueMail for Android herunterladen ​

**Comment by Wagnerp** [comment]
Unfortunately, you'll need to wait until build 2109 for the fix. But it'll be only a week.

**Comment by Wagnerp** [comment]
Fixed in build 2109
