### ISSUE TITLE
[Question]: Should the default "Theme fonts" now be changed to Segoe UI 9 pt

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#288]
https://docs.microsoft.com/en-gb/dotnet/core/compatibility/winforms#default-control-font-changed-to-segoe-ui-9-pt

**Comment by Wagnerp** [comment]
Yes, or Segoe Variable UI (Windows 11)

**Comment by Smurf-IV** [comment]
Is Segoe on WinXP ? (As this suite still supports .net35 so could still be targetting that ?)
Cannot use "Segoe variable" as that is not "Everywhere"!

**Comment by Smurf-IV** [comment]
> Is Segoe on WinXP ? (As this suite still supports .net35 so could still be targetting that ?)

Not it is not unless Office 2007 (Or higher) has been installed:
https://en.wikipedia.org/wiki/Segoe#Availability

**Comment by Wagnerp** [comment]
Might need some sort of version check, as I understand, Segoe Variable UI was designed to support larger screen sizes (4k etc). It could come to Win 10 21h2.

**Comment by Smurf-IV** [comment]
As #290 has been completed, then the default font could be `Segoe UI 9` now.
As for the Variable style, That may not be needed due to handling the of the following in the Targey App exe's manifest
```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>
```

**Comment by Wagnerp** [comment]
@Smurf-IV I don't understand this, but _if_ I try to update the font in the theme bases, it won't update to the new font

**Comment by Wagnerp** [comment]
@Smurf-IV Just found this https://docs.microsoft.com/en-us/dotnet/desktop/winforms/whats-new/net60?view=netdesktop-6.0#change-the-default-font Is it as easy as configuring the `csproj` files?

**Comment by Smurf-IV** [comment]
No, AS the themes have their own fonts
The above link will be only applied to default winform elements.

**Comment by Wagnerp** [comment]
@Smurf-IV Is there any way to find the value of `baseFontName`?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is there any way to find the value of `baseFontName`?

No idea, does it not show up in the palette designer ? Cannot check at the moment.

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is there any way to find the value of `baseFontName`?
> 
> No idea, does it not show up in the palette designer ? Cannot check at the moment.

As far as I'm aware, there's no way to set a 'global' font. I'm not sure _if_ the controls inherits the standard WinForms font?

**Comment by Wagnerp** [comment]
@Smurf-IV Should this be transferred to the extended toolkit?

**Comment by Smurf-IV** [comment]
No, It should be "Copied" in both

**Comment by Smurf-IV** [comment]
Also, it should be linked to the new one that you created.

**Comment by Wagnerp** [comment]
For this to happen, https://github.com/Krypton-Suite/Standard-Toolkit/issues/703 needs to be done
