### ISSUE TITLE
[Question]: Should V6 only support "MS Supported" Net Frameworks ?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#290]
In order to allow the suite to move into the latest "Fonts", PInvokes, "Remove MissingFramework API's", Winform structures / etc.
Can V6 **only** support MS Net Frameworks that it will cover in its lifetime?
:
https://dotnet.microsoft.com/platform/support/policy/dotnet-framework

i.e. only .Net 4.6.2 onwards.

**Comment by Wagnerp** [comment]
So drop support anything below 4.6.2?

**Comment by Wagnerp** [comment]
I'd say yes

**Comment by Smurf-IV** [comment]
I have assigned to you to modify the build scripts (And TFM support)
And then assign back to me if you want me to go through and delete the "MissingFrameworks API's" or <net 462 #defines

**Comment by Wagnerp** [comment]
@Smurf-IV Back over to you, I've done the edits on `alpha-enh#290`

![image](https://user-images.githubusercontent.com/949607/130610172-92642761-90f7-4d5c-92d7-a18f5b95a2f2.png)

![image](https://user-images.githubusercontent.com/949607/130610220-71bcfc9a-7b29-4c66-ae24-4725d080df68.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Just a thought, since we're dropping support for below 4.6.2, should we also ditch the `lite` packages? I'll also mirror changes on the `Extended-Toolkit`.

**Comment by Smurf-IV** [comment]
> @Smurf-IV Just a thought, since we're dropping support for below 4.6.2, should we also ditch the `lite` packages?


That'll make the explanation text easier (i.e. it doesn't need it any more :-))
Description can then state something like "An update .... supporting `MS Supported Net Winform Frameworks` from .Net4.62 (inc) onwards"

**Comment by Wagnerp** [comment]
> > @Smurf-IV Just a thought, since we're dropping support for below 4.6.2, should we also ditch the `lite` packages?
> 
> That'll make the explanation text easier (i.e. it doesn't need it any more :-))
> Description can then state something like "An update .... supporting `MS Supported Net Winform Frameworks` from .Net4.62 (inc) onwards"

Also it'll make building `Extended-Toolkit` a heck of a lot easier! :)

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/130636311-794ebe8c-dd89-4005-b1e9-2fc230c28dcb.png)
