### ISSUE TITLE
[Feature Request]: Label "Back Color" needed in State#### Designer control(s)

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#296]
All controls in the Standard Toolkit allow setting back color, with the exception of KryptonLabel and KryptonTrackBar. The back color of these items can only be configured via the global palette style, which does not give control over individual items. The default WinForms Label and Trackbar both allow setting back color, so the Krypton versions ideally would too.

**Comment by Smurf-IV** [comment]
Question:
@Wagnerp @sdreb3421  If this is implemented, then should the `Checkbox`, `LinkLabel`, `WrapLabel` (Maybe others) Also need to have the backcolour styles added ?

**Comment by Wagnerp** [comment]
@Smurf-IV That is true, implementing such feature may break other controls, unless the KLabel can be changed to behave more like the `Checkbox`, `LinkLabel` & `WrapLabel`?

**Comment by sdreb3421** [comment]
For example, we want to add TrackBars to different areas of our UI where the back color is not identical. And there are areas in our UI where we let the user set the panel BackColor. 

If the change was implemented, maybe the default back color could be set to Transparent so it doesn't break anything.?

**Comment by sdreb3421** [comment]
@Smurf-IV After reviewing the issue, I think you were right to make the TrackBar back color its own issue. Even though the other controls (Label, CheckBox, etc) don't have a back color setting, they are transparent and take on the color of their parent control.  

However, the TrackBar is different. It is not transparent, doesn't have a back color setting, and the global palette BackStyle cannot be set transparent. So maybe close this issue and just continue with #304 .

**Comment by Smurf-IV** [comment]
I'm confused.
If the `KryptonLabel` (And in the example below a `KCheckbox`) are on a panel, and it has colour gradients etc.
Then by default, those panel colours show through:
![image](https://user-images.githubusercontent.com/2418812/131452751-7634005e-5c5e-40e3-99c0-990b820407e7.png)

Have you explicitly set the `BackColor` of those controls so that it bypasses Kryptons drawing ?
Or, Are you not using a `KryptonPanel` as the control(s) owner ?

**Comment by sdreb3421** [comment]
Your totally right. Check out my previous comment. I believe the only issue is with the TrackBar.

**Comment by Smurf-IV** [comment]
Ok, Closing this, Switching to #304
