### ISSUE TITLE
[Bug]: Office 2k7 colour usages are wrong

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#297]
Whilst investigating #227
I found that the colour order usage for O2k7 Themes is reversed

Expected for the orange Backcolor5 (Bottom Glow) to be:
![image](https://user-images.githubusercontent.com/2418812/131088350-9f851e9f-6d97-44e2-b5fe-e1c53326f823.png) 
![image](https://user-images.githubusercontent.com/2418812/131088392-470efcaa-8667-4ae3-a04c-e6bff62cf86a.png)

But for O2k7 Themes (And sparkle):
![image](https://user-images.githubusercontent.com/2418812/131088494-83849374-f474-4e91-8762-d79fc0284e63.png)
![image](https://user-images.githubusercontent.com/2418812/131088551-1e19a8d1-7707-43a7-b065-49b7503148c8.png)

**Comment by Smurf-IV** [comment]
Getting there:
Showing Lime override:
![ShowLimeOverride](https://user-images.githubusercontent.com/2418812/131244536-a3df0b5d-4473-4955-923d-86cfd378e197.gif)

**Comment by Smurf-IV** [comment]
New Designer area:
![image](https://user-images.githubusercontent.com/2418812/131244611-c2c43d07-29d1-4bb3-abd3-170d6c074ea0.png)

**Comment by giduac** [comment]
Hi @Smurf-IV,

Is this still being worked on?

**Comment by Smurf-IV** [comment]
I have been leaving all theme related stuff to wagnerP, unless it has something to do with functionality (As the merges above required highlighting to be done)

**Comment by giduac** [comment]
@Wagnerp 

Is this ticket still current or has it been solved over time?

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Is this ticket still current or has it been solved over time?

@giduac 

It's being solved over time, O2k7 themes are the hardest to get right, due to the 'glassy' effect.

**Comment by PWagner1** [comment]
@Smurf-IV & @giduac 

Is the problem that these colours are in the wrong place?

**Comment by Smurf-IV** [comment]
> @Smurf-IV & @giduac
> 
> Is the problem that these colours are in the wrong place?

According to the pictures - Yes

**Comment by PWagner1** [comment]
Note... Basckcolours 4 & 5 are reversed

**Comment by PWagner1** [comment]
@Smurf-IV & @giduac 

Apparently this was how it was supposed to be. Tested in V4 from CF

![{1E57BFB9-4B16-4557-B0F0-E11C861D1DB8}](https://github.com/user-attachments/assets/3027f991-d678-489d-893b-97fc58e0005a)

Is this really a bug or a FR?

**Comment by PWagner1** [comment]
@Smurf-IV & @giduac 

Found a fix, going to take a few days to implement, as I'm going to have to reverse back colours 1 & 2 with 5 & 4 and vice-versa for all affected palettes.
