### ISSUE TITLE
[Feature Request]: Track Bar "Back Color" needed in State#### Designer control(s)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#304]
Splitting this off from #296 to allow focused delivery of component functionality

![image](https://user-images.githubusercontent.com/2418812/131307168-d60eca81-2c84-4620-87ee-a98653ea35cf.png)

**Comment by Smurf-IV** [comment]
Or "Should be transparent" like the KLabel / KCheckbox (etc.) controls

**Comment by sdreb3421** [comment]
Making it transparent like KLabel would work. Or handle transparency for the TrackBar.BackStyle palette definition.

**Comment by Smurf-IV** [comment]
There is a "Hidden" public field
``` c#
        public Form1()
        {
            InitializeComponent();
            this.kryptonTrackBar15.DrawBackground = false;
        }
```

I will be making this "public in the designer";

But you can start to use it straight away 👍

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/131462364-36bca487-ae77-4354-a305-6fe48dc92ab1.png)

**Comment by sdreb3421** [comment]
I don't have that property in the designer or programmatically. I checked in the stable and canary versions just to be sure. ???

![image](https://user-images.githubusercontent.com/1911567/131462347-45c95904-74f2-49a2-ba9a-d5d685c340f2.png)

**Comment by Smurf-IV** [comment]
It is (Was) set to not be browsable, so will not show up in intellisense:
``` c#
[EditorBrowsable(EditorBrowsableState.Never)]
        [Browsable(false)]
        public bool DrawBackground
        {
            get => !_drawTrackBar.IgnoreRender;
            set => _drawTrackBar.IgnoreRender = !value;
        }
```
Just type it in and set it.

**Comment by sdreb3421** [comment]
Beautiful! I didn't realize intellisense could be set up to hide a public property.

**Comment by Smurf-IV** [comment]
Done:
![image](https://user-images.githubusercontent.com/2418812/131465489-5f34f58e-03d2-4a96-aedc-ead866a867a6.png)
