### ISSUE TITLE
[Bug]: Panel AntiAlias Border Problem

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#308]
Gray border lines are being drawn on the top/left when setting the GraphicsHint to AntiAlias on a KryptonPanel. This also shows up on the inner panel of a KryptonGroup with AntiAlias back, but only when the group is disabled. The image below shows an example of the weird lines for a KryptonGroup (left) and KryptonPanel (right).

![image](https://user-images.githubusercontent.com/1911567/131387627-119c6f09-3fff-4dae-a859-58cdaf2035b7.png)

To reproduce, add a KryptonPanel to a form. Set the GraphicsHint of the panel to be AntiAlias. Set the back color of the form and panel to be Black (not necessary but helps illuminate the issue).

Tested on both FrameWork and NET5 using 6.0.2108.1 as well as previous stable versions.

**Comment by Smurf-IV** [comment]
It's much worse than that..
Take the following (`KryptonForm` with `Full Dock` Default `KryptonPanel`, then with 2 KPanels set to Black and AntiAlias)
![image](https://user-images.githubusercontent.com/2418812/131494320-c4709dbf-0996-499e-a46c-63a54761b77a.png)

And the use the "OS magnifier app" on the screen, and it will be seen that the left and top borders are grey with corner rounding !

**Comment by Smurf-IV** [comment]
@sdreb3421 I'm confused with the pictures that you have shown..

Is the left a KryptonGroupBox (With rounding), set to black, and then the internal panel also set to black, but only the internal panel disabled ?

Or a KryptonGroup (With rounding) .. etc. ?

Or is it a KPanel with rounding ?

**Comment by Smurf-IV** [comment]
Please check the (Draft PR above) projects I have modified to see if I have replicated as you have explained

**Comment by sdreb3421** [comment]
The left image is a KryptonGroup with rounding and the StateCommon back set to black and AntiAlias. The inner panel properties are left default. The lines will only show up if it is originally enabled then disabled at runtime. I didn't explain in too much detail because I figured the KryptonPanel was the root cause.

**Comment by sdreb3421** [comment]
@Smurf-IV I've never looked at a PR before. I can see the files you've changed, but can't easily see if you've replicated it appropriately. Can I open the PR up in Visual Studio somehow?

**Comment by Smurf-IV** [comment]
Download (Select) the branch  to your machine
Then open as normal in visual studio.

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/131965856-2ade7593-e54d-4e4b-b12e-c5294e149d09.png)

**Comment by sdreb3421** [comment]
I was unsuccessful. We use Azure DevOps for our repos so I'm unfamiliar with the Git system. I connected to the Standard-Toolkit-Demos solution but it has tons of build errors so I can't open any of the forms. It looks like the projects aren't seeing the Krypton dlls/nuget. Should I add the canary nuget to all these projects?

**Comment by Smurf-IV** [comment]
Just open the nuget solution.
![image](https://user-images.githubusercontent.com/2418812/132118854-4712d10a-de1d-4e8c-9133-cba177d4e041.png)

**Comment by Smurf-IV** [comment]
@sdreb3421 
Can this be closed now, that the demo code is showing that it is functioning as expected ?

**Comment by sdreb3421** [comment]
We're you able to reproduce and fix the issue? I stopped using Krypton panels and groups as a workaround. Would there still be benefit to downloading the PR and verifying?

**Comment by Smurf-IV** [comment]
No I was not able to reproduce as per description.
And yes it would be good to see if the Demo App I created displays the same issue(s) that you saw on your machine, and then allow you to alter it if does not cause problem you describe to replicate it..

**Comment by Smurf-IV** [comment]
@sdreb3421 Can this be closed now ?

**Comment by sdreb3421** [comment]
I just made a commit to the code you provided. I added a button to the ColouredForm to enable/disable the groupbox and show the issue. Can you confirm on your end?

**Comment by sdreb3421** [comment]
@Smurf-IV just following up on issues I've opened tonight...

**Comment by Smurf-IV** [comment]
> I just made a commit to the code you provided. I added a button to the ColouredForm to enable/disable the groupbox and show the issue. Can you confirm on your end?

Github does not show your commit getting into the PR, either via a new update to this item, or directly into the PR:
![image](https://user-images.githubusercontent.com/2418812/172795781-5f1e5229-62a7-4ce4-bf65-0b188a2df32e.png)

**Comment by Smurf-IV** [comment]
Latest code removes the borders and rounding for panels and brings back the Disabled anti-alias lines:
![image](https://user-images.githubusercontent.com/2418812/172801912-cffa5389-0235-429d-ad49-866523cbd190.png)
