### ISSUE TITLE
[Bug]: KryptonMessagebox is not RTL compliant

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#313]
May have to do what Winforms internal do, and have a "Special" version of the messagebox for RTL. This would be the easiest way to ensure "compliance"

**Comment by Smurf-IV** [comment]
https://stackoverflow.com/a/46048548

What the enums are:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxoptions?view=net-5.0

What the enums do:
![image](https://user-images.githubusercontent.com/2418812/131654754-e99a61c2-ca14-4b34-ad6f-2c3a4b3a1930.png)

**Comment by Wagnerp** [comment]
This might actually straddle the `Toast` module in the ET as well.

**Comment by Smurf-IV** [comment]
What a `Winform MessageBox` looks like:
![image](https://user-images.githubusercontent.com/2418812/133127214-c2258216-c31f-477b-a467-b0a74ce271ee.png)

**Comment by Smurf-IV** [comment]
Just RightAlign looks like this:
![image](https://user-images.githubusercontent.com/2418812/133127521-77938c86-ee81-48f9-b8f7-5c4ea6586796.png)

And Just RTL looks like this:
![image](https://user-images.githubusercontent.com/2418812/133127610-c2a712fe-4a88-4726-afea-23abb28063ba.png)

So the settings appear to be exclusive. (Unless it detects RTL in the OS, and the Font used ??)

**Comment by Smurf-IV** [comment]
With the Fix:
Both Set:
![image](https://user-images.githubusercontent.com/2418812/133129265-b5c573be-db2f-449b-9148-4efa915414f6.png)

RightAlign only:
![image](https://user-images.githubusercontent.com/2418812/133129353-8c6541f6-246b-4a5d-8953-eadf6cf42bb5.png)

RTL Only:
![image](https://user-images.githubusercontent.com/2418812/133129400-edc5eaab-3294-4753-a23b-4a7419f392b7.png)

**Comment by Wagnerp** [comment]
Using today's `alpha` 13/01/2024

![Bug 313](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/9d91cc07-964c-42e3-811a-437041019a95)

**Comment by Wagnerp** [comment]
@Smurf-IV Was something changed between v70 & v80?

**Comment by Smurf-IV** [comment]
@Wagnerp 
I seem to remember that you introduced Layout tables for the Bottom extension stuff.

**Comment by Wagnerp** [comment]
> @Wagnerp I seem to remember that you introduced Layout tables for the Bottom extension stuff.

@Smurf-IV I wonder... What if we had two sets of tables? I'll prototype something this week...

**Comment by Wagnerp** [comment]
Fixed

![Bug 313](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6a82e037-9619-49ef-86c9-e3420ea3b923)

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed

Would you mind testing today's `nightly` build, .16 to see whether this works correctly? I know that the buttons and form chrome still needs to be flipped around.
