### ISSUE TITLE
[Feature Request]: Krypton Groupbox - ButtonSpec

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#314]
Whats the possibilty of adding ButtonSpecs to Krypton Groupboxes?
Looking to replicate this without using an additional KryptonButton
![image](https://user-images.githubusercontent.com/84494183/131657402-587b28d6-89e2-415d-aaf7-27df434aad95.png)

Cheers

MattH

**Comment by Smurf-IV** [comment]
Nice idea.
It won;t be easy, as the positioning of the Caption can be controlled, and the expectation would be for the buttons to also be controlled.
Also this would be expected for a  `KryptonGroup`  as well, not just the `KryptonGroupBox`

**Comment by MattH-Work** [comment]
Just discovered Header Groups, does extactly what I need with some as yet undiscovered / uneeded additional benefits
