### ISSUE TITLE
[Bug]: When adding a new KContextmenu, How do you change it's name etc

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#315]
Not sure when this became a Canary problem, but it's not in master.

Using 2109 Canary - There are difficulties in using the KryptonContextMenu Items Editor:

![image](https://user-images.githubusercontent.com/2418812/131798887-ed9abf03-c99e-4dd2-9051-5f9f7644b57c.png)
1) add new Item
2) How to change it label
3) How to change it's field variable name
4) how to allocate events

**Comment by Smurf-IV** [comment]
# This is a bug in the 2109 Canary

2108.1 shows this:

![image](https://user-images.githubusercontent.com/2418812/131959198-4cc54a7b-4160-4b9c-ac0b-d9926de4cd36.png)

**Comment by Smurf-IV** [comment]
Broken between PR #249 and #250 :-(

**Comment by Smurf-IV** [comment]
Sorted 👍 
![image](https://user-images.githubusercontent.com/2418812/132089733-ec9f855c-1666-4907-a344-c2167b455fae.png)

**Comment by DarthVader85PA** [comment]
Dear Simon (@Smurf-IV)

Is it possible to add (Name) to the properties?
So I can change the name of the control then?! :)
![grafik](https://user-images.githubusercontent.com/32876506/132090207-83d2621c-530c-4c00-b9cc-95ab8a97250f.png)

Greetings, Danny

**Comment by Smurf-IV** [comment]
> 
> 
> Dear Simon (@Smurf-IV)
> 
> Is it possible to add (Name) to the properties?
> So I can change the name of the control then?! :)
> ![grafik](https://user-images.githubusercontent.com/32876506/132090207-83d2621c-530c-4c00-b9cc-95ab8a97250f.png)
> 
> Greetings, Danny

Hello, Can you make this into a [Feature Request] please?
