### ISSUE TITLE
[Bug]: KInputBox layout is a mess

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#316]
**Describe the bug**
Using 2109 Canary
and the following code
`var label = KryptonInputBox.Show(string.Empty, @"Please enter the Label text", string.Empty, @"Label text", Color.CadetBlue, null, false);`

results in this:

![image](https://user-images.githubusercontent.com/2418812/131819795-547c2948-dc9e-42eb-b9cf-e079c00286f0.png)

**Comment by Wagnerp** [comment]
Shouldn't there be text in the label?

**Comment by Smurf-IV** [comment]
Not with those parameters..
Speaking of paramters it's really difficult to use, when the Nullable operator is in the list and the Code using it, is not nullable aware !

**Comment by Wagnerp** [comment]
@Smurf-IV Ok, I'll have a look into it when I come back from holiday the following Monday

**Comment by Smurf-IV** [comment]
I'll probably have a look whilst sorting the RTL for the KMessageBox
