### ISSUE TITLE
[Feature Request]: Can the `KryptonColorButton` Image be the `SelectedColor` itself?

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#318]
As title states

**Comment by Smurf-IV** [comment]
It already does this:
![image](https://user-images.githubusercontent.com/2418812/131959503-6f13508c-8914-4d49-9a47-74964810781c.png)

What are you wanting ?

**Comment by Wagnerp** [comment]
> It already does this:
> ![image](https://user-images.githubusercontent.com/2418812/131959503-6f13508c-8914-4d49-9a47-74964810781c.png)
> 
> What are you wanting ?

@Smurf-IV Ah, how is that done, as there's no obvious way?

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/131966100-74d0b9af-9da4-4fed-b5c4-eff844533ba7.png)

**Comment by Smurf-IV** [comment]
There is a problem with the "SelectedRect", in that it will not do anything but a "Square" so this could be changed into a bug to solve that !

**Comment by Wagnerp** [comment]
Ok thanks, maybe a 'new feature/bug' ticket is required to make it easier to change?
