### ISSUE TITLE
[Bug]: Packages on nuget do not have a strong name on the assemblies.

### ISSUE THREAD

**Issue by Tape-Worm** [Krypton-Suite/Standard-Toolkit#32]
**Describe the bug**
I'm using the Krypton.Toolkit.Lite and Krypton.Ribbon.Lite (v5.550.2011) from nuget and when I sign my projects I get warnings that these krypton assemblies do not have a strong name:

> ##[warning]CSC(0,0): Warning CS8002: Referenced assembly 'Krypton.Ribbon, Version=5.550.2011.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

This makes my apps crash when I run them (for obvious reasons).

**To Reproduce**
1. Pull the aforementioned packages from nuget
2. Sign your project with a snk file
3. Compile
4. See warning

**Comment by Wagnerp** [comment]
Hi @Tape-Worm 

Have you tried using the `*.Signed` packages?

**Comment by Tape-Worm** [comment]
Didn't even know they existed.

**Comment by Wagnerp** [comment]
They're quite new, as someone else had a similar problem.

**Comment by Tape-Worm** [comment]
Alrighty, I'll use those when I get to those parts of my project that require it.  Thanks.
