### ISSUE TITLE
[Bug]: `KryptonColorButton` "SelectedRect" will not do anything but a "Square" 

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#320]
As discussed in #318

**Comment by Wagnerp** [comment]
Be nice to display a circle or a rounded rectangle

**Comment by Smurf-IV** [comment]
> 
> 
> Be nice to display a circle or a rounded rectangle

Circle - no
Rounded Rect - yes (And the roundness for circle can come from the corner settings ;-))

**Comment by Smurf-IV** [comment]
As mentioned above circle, and rounded done.
![image](https://user-images.githubusercontent.com/2418812/133138361-fa752e46-7b38-4137-a0f0-1f86277a69a7.png)

Now for the Wide and Big !

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/133144422-22cbb022-2608-48b3-8940-b1c27618e30c.png)
