### ISSUE TITLE
[Bug]: KryptonCheckButton Click removes image

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#323]
![CheckboxClickRemovesImage](https://user-images.githubusercontent.com/2418812/132027681-c38d55e2-b4c8-4062-99bc-516074d2bb5c.gif)

found in 2109 Canary

Does not occur in 2108.1 Canary

**Comment by Smurf-IV** [comment]
Related to #317

**Comment by Smurf-IV** [comment]
Works as expected in PR270 !

**Comment by Smurf-IV** [comment]
Does not work in PR #276

**Comment by Smurf-IV** [comment]
@Wagnerp What is the idea behind this code ?
![image](https://user-images.githubusercontent.com/2418812/132102918-b909f0b1-683c-4869-88a2-791b87035793.png)

If it is a UAC button, then the icon should already be there, 
and, the 2nd if should be simplified 
and, **_why_** assign it to **null** afterwards ?

**Comment by Wagnerp** [comment]
@Smurf-IV I don't think that the UAC shield icon is applied automatically if it's meant to be elevated (I may be wrong though), but you can remove the _null_ part if it's causing issues :)

**Comment by Smurf-IV** [comment]
The `_processToElevate` should not be in this code, it is upto the developer to perform the action either via a `KCommand` or the `OnClick` method.

The `_useAsUACElevationButton` should just set the image, when the `Set` is called.

**Comment by Wagnerp** [comment]
> The `_processToElevate` should not be in this code, it is upto the developer to perform the action either via a `KCommand` or the `OnClick` method.
> 
> The `_useAsUACElevationButton` should just set the image, when the `Set` is called.

Maybe check to see if a `KCommand` is set before doing the `OnClick`, otherwise having nothing may cause issues?

**Comment by Wagnerp** [comment]
Or can a separate method be added to `KCommand` to perform elevated actions?

**Comment by Smurf-IV** [comment]
> Maybe check to see if a `KCommand` is set before doing the `OnClick`, otherwise having nothing may cause issues?

Nothing it should be.. AS it is a a developer choice what to do .. It might be that the UAC is there to then Ask for Login into an external system, 
Perform something dangerous
Delete the OS ;-)
It's a developer choice. not the Krypton Code base to choose !

**Comment by Smurf-IV** [comment]
> 
> 
> Or can a separate method be added to `KCommand` to perform elevated actions?

Nope, Let the developer make the choice

**Comment by Wagnerp** [comment]
Implementing fix now

**Comment by Smurf-IV** [comment]
Hmm, I was working n it.. Never mind..
Also move this into Extended `ExecuteProcessAsAdministratorEventArgs`

**Comment by Wagnerp** [comment]
Hold on... should the shield go in `OnPaint`?

**Comment by Smurf-IV** [comment]
> 
> 
> Hold on... should the shield go in `OnPaint`?

No.

**Comment by Smurf-IV** [comment]
Also in the above class, how is the process launched if the user already is an admin ?
![image](https://user-images.githubusercontent.com/2418812/132103688-1dac2a57-2357-43bb-bcac-acb7189f04dd.png)

Not sure any of this is appropriate for Krypton.

**Comment by Smurf-IV** [comment]
What I am expecting when  a Dev sets `kryptonButton12.UseAsUACElevationButton = true;`
is:
- If no image is set , then use the UAC icon
- If an image is set then do nothing,
- If it is set, and then image becomes null, to then display the UAc icon (i.e. it is replacing the `kryptonButton12.Values.Image` value at that point)
Nothing else needs to be done.

But, If the image is set, then the image size will need to be stored so that the Button is not resized _down_ to the 16*16 default UAC bitmap size !!

**Comment by Wagnerp** [comment]
Another question, why are all designers are set like this: `[Designer("Krypton.Toolkit.KryptonButtonDesigner, Krypton.Toolkit")]` surely using `typeof()` would be better?

**Comment by Wagnerp** [comment]
i.e. `[Designer(typeof(KryptonButtonDesigner))]`

**Comment by Smurf-IV** [comment]
That caused the dll's not to load into VS 2019 correctly, and it is what MS do in their Winforms projects, to perform a "Delay load" of the Dll's, thus allowing the designer to only load when needed.
It is covered by the Bug that I did to solve "Some" of the Designer loading issues.. Still got a few more to investigate.

**Comment by Wagnerp** [comment]
> That caused the dll's not to load into VS 2019 correctly, and it is what MS do in their Winforms projects, to perform a "Delay load" of the Dll's, thus allowing the designer to only load when needed.
> It is covered by the Bug that I did to solve "Some" of the Designer loading issues.. Still got a few more to investigate.

So... keep as is?

**Comment by Wagnerp** [comment]
@Smurf-IV DO NOT MERGE!! I've forgot to do the if/else statements

**Comment by Wagnerp** [comment]
Ok ready

**Comment by Wagnerp** [comment]
Fixed in build 2110
