### ISSUE TITLE
[Bug]: KryptonGroupPanel Paint Event Not Triggered

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#324]
I would like to draw an image/graphics on the KryptonGroupPanel (inside of KryptonGroup) using the standard graphics draw methods. 

Drawing graphics on a control is normally possible by subscribing to the Paint event, or by deriving from the class and overriding the OnPaint event. 

When subscribing to a KryptonGroupPanel Paint event, the event is never called. I found it is possible to derive from KryptonGroup and override its paint event, but this draws on the group container behind the KryptonGroupPanel, and not on the panel itself.

**Comment by Smurf-IV** [comment]
FYI: A KryptonPanel has an `Image` background variable; so it can be used like a standard picture box.
If you need to create an image, then just assign it to the panel afterwards, then it will not need to be recreated for every paint action that windows calls.

**Comment by sdreb3421** [comment]
That works. Thank you!
