### ISSUE TITLE
[Feature Request]: (Name) and other Standard-Properties in KryptonContextMenu Items Editor

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#327]
**Is your feature request related to a problem? Please describe.**
At Item Properties (right side) in "KryptonContextMenu Items Editor" is (Name)-Property missing. Other Standard-Properties like DataBinding too?! So if that possible? :)

If find the correct Item over Tag-Property (red):
![grafik](https://user-images.githubusercontent.com/32876506/132103721-21579755-c2ba-4d92-9c0e-d6f903f21117.png)

After create over "KryptonContextMenu Items Editor" I can choose it from list of Controls in the form:
And here are the Properties that are missing:
![grafik](https://user-images.githubusercontent.com/32876506/132103769-667c1f21-813d-4335-ae0d-43220a7fde46.png)

Same for Item itself:
![grafik](https://user-images.githubusercontent.com/32876506/132103836-e92b721b-4429-4a9f-b5cd-065861ac1981.png)
![grafik](https://user-images.githubusercontent.com/32876506/132103853-49d809de-3c76-431d-a106-fb0277161091.png)

I use following versions:
Krypton Standard-Toolkit: 5.550.2106.1
Visual Studio 2017/2019 Professional (same issue in both Versions of Visual Studio)
Windows 10 Professional
TFS 2018 SP3

Greetings, Danny

**Comment by Smurf-IV** [comment]
Thanks.. 
Note: These are "Still missing" in Canary 2109 ;-(

**Comment by Smurf-IV** [comment]
@DarthVader85PA re:
> I use following versions:
> Krypton Standard-Toolkit: 5.550.2106.1
> Visual Studio 2017/2019 Professional (same issue in both Versions of Visual Studio)
> Windows 10 Professional
> TFS 2018 SP3

What versions of the TFM are you using ?

**Comment by DarthVader85PA** [comment]
> 
> 
> @DarthVader85PA re:
> 
> > I use following versions:
> > Krypton Standard-Toolkit: 5.550.2106.1
> > Visual Studio 2017/2019 Professional (same issue in both Versions of Visual Studio)
> > Windows 10 Professional
> > TFS 2018 SP3
> 
> What versions of the TFM are you using ?

I use .NET-Framework 4.7.2 in all my Projects! Sorry I forgot that! 
And I implemented Krypton over NuGet Packet Manager.

**Comment by Smurf-IV** [comment]
> I use .NET-Framework 4.7.2

Good to know.. As V6 will support 4.6.2 onwards only!

**Comment by Smurf-IV** [comment]
Some of the main differences are:
- The KContext deisnger cannot access the `Components` `Site` instance members
- The KContext uses a different list then the Winform version
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7d72fac3-ec45-4d06-9da1-1ecb1503e955)

**Comment by Smurf-IV** [comment]
The reason it was not done originally, is because the default "Items" designer, is exposed, which then causes confusion for the actual designer being used:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ed79353c-ccb5-4d67-b0de-63212aca6423)

**Comment by Smurf-IV** [comment]
Done, PR Soon:
![DesignMenuEditor](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/8cf86299-8435-424f-8c7e-abaa4273de97)

**Comment by Smurf-IV** [comment]
Seems like i did not "Do this correctly": REOPENING
