### ISSUE TITLE
[Question]: .NET 5 - Cannot move components in designer view

### ISSUE THREAD

**Issue by jsavage7** [Krypton-Suite/Standard-Toolkit#33]
I don't know if this is a designer issue or something with the components, but when I drag any components onto the windows form it cannot be modified via the designer. Screenshot below shows how it looks when adding any components to the form. this example is of a textbox. 

Visual Studio 16.8.2

![KryptonTextBoxExample](https://user-images.githubusercontent.com/5059928/100818618-82029980-3418-11eb-83d1-e09dbced4e2e.PNG)

**Comment by Wagnerp** [comment]
Hi @jsavage7 

Thanks for posting your issue. Yes this is a known issue, a workaround is to add `net48` to your target frameworks in your project configuration file.

**Comment by Tape-Worm** [comment]
Well holy carp!  This works amazingly well.  I was wondering about this myself, so thank you.

**Comment by Wagnerp** [comment]
No problem, it's a bug within the .NET Core/.NET SDK itself.

**Comment by gurolgencel** [comment]
Where should we add can you help?

```
<OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework> 
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
```

**Comment by Wagnerp** [comment]
Hi @gurolgencel 

Where you have `<TargetFramework>net5.0-windows</TargetFramework>` simply replace it with:-

`<TargetFrameworks>net48;net5.0-windows</TargetFrameworks>`,

then recompile/rebuild

**Comment by gurolgencel** [comment]
Thanks a lot.
