### ISSUE TITLE
[Other Issues]: Designer Performance for Ribbons is painful

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#332]
Open "Outlook Mail Clone" example in Designer
Click on one of the buttons and select it image in the designer
Now change to another button

The whole Visual Studio is locked and no significant CPU cycles are observed.
Can take upto 4 mins to recover on a 4GHz machine !!
And sometimes this happens:
![image](https://user-images.githubusercontent.com/2418812/132494662-29ff201a-fa48-4669-a33f-78f52cbd051c.png)

Maybe related to #10

**Comment by Wagnerp** [comment]
Possibly something related to the old VS 2005 environment

**Comment by Wagnerp** [comment]
The designer might be using something that pre-dates .NET 4

**Comment by Smurf-IV** [comment]
Just tried this in vs 17.8.p1 with today's alpha in debug,
And it opens from a clean envtonment (No Forms had been opened since solution load) to displaying the designer form in under 30 secs
