### ISSUE TITLE
[Bug]: "Office 2010 And 365 Minimise Icons Change Size" on hover

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#336]
**Describe the bug**
When hovering over the minimise button, it is of a different size that it's normal state, and also the minimise icons moves.

Only applies to 201 and 365 themes 

Tested with 2109 Canary - May be applicable to earlier versions

![Office2010And365MinimiseIconsChangeSize](https://user-images.githubusercontent.com/2418812/132987151-948924f5-a0bd-404b-9596-a7d595c137d6.gif)

**Comment by Wagnerp** [comment]
Easy fix

**Comment by Smurf-IV** [comment]
> 
> 
> Easy fix

Just needs to be in about 10 themes: blue / silver / Black / Silver dark / Silver white / Black Dark / etc.

**Comment by Wagnerp** [comment]
> > Easy fix
> 
> Just needs to be in about 10 themes: blue / silver / Black / Silver dark / Silver white / Black Dark / etc.

As I thought, only requires a image resize

**Comment by Wagnerp** [comment]
@Smurf-IV Can you confirm which states the size changes?

**Comment by Smurf-IV** [comment]
`onHover` as per the video.

**Comment by Smurf-IV** [comment]
It's not just the size, it's also the "Lozenge" location moves up.

**Comment by Wagnerp** [comment]
> It's not just the size, it's also the "Lozenge" location moves up.

I'll take the O2k7 version & modify it

**Comment by Wagnerp** [comment]
Providing a fix tomorrow

**Comment by Wagnerp** [comment]
Fixed in build 2110
