### ISSUE TITLE
[Bug]: KryptonRibbon.RibbonAppButton.AppButtonMenuItems has error

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#34]
See [#164](https://github.com/ComponentFactory/Krypton/issues/164)

**Comment by Smurf-IV** [comment]
Following steps from https://github.com/ComponentFactory/Krypton/issues/164#issuecomment-471041552
Different error message in VS2019, but it's the "same meaning"
![image](https://user-images.githubusercontent.com/2418812/147645432-98b93296-2d34-444a-8a79-a0a8296b4493.png)

**Comment by Smurf-IV** [comment]
This is what a `KContextMenu Items Editor` should look like:
![image](https://user-images.githubusercontent.com/2418812/147645811-ab3563c7-1f8d-46e7-a632-d59cb1c5b281.png)

**Comment by Smurf-IV** [comment]
It is "Possible" to use the editor once t has some designer elements; 
e.g. via the Ribbon Example:
![image](https://user-images.githubusercontent.com/2418812/147646085-854624a4-96f0-425b-a411-64f1ce09a9af.png)

**Comment by Smurf-IV** [comment]
Done.
