### ISSUE TITLE
It is still not possible to create a KryptonStatusStrip on a form at design time.  

### ISSUE THREAD

**Issue by DavidWaite1962** [Krypton-Suite/Standard-Toolkit#35]
This happens within build .550.2011

Drag and drop a KryptonStatusStrip control onto a form or usercontrol

SystemNullReferenceException is returned within the OnRendererChanged event  at
System.Windows.Forms.Toolstrip.set_Renderer(ToolStripRenderer value)

A quick look at the source code for this control looks like it should be easy to identify & fix

**Comment by Wagnerp** [comment]
Hi @DavidWaite1962 

Found the bug, it's trying to render `ToolStripProgressBars` into Krypton which don't exist. Should be easy to fix with a try/catch statement. Can @Smurf-IV or @tbolon help find a more permanent solution?

**Comment by DavidWaite1962** [comment]
Hello Peter

Thanks I'd downloaded the source and was poking around too.  That's exactly
my current configuration too - think the code overrides Onrender if I
recall correctly too.

Workaround noted and will be sorted shortly.

A fantastic product set even so.  15 years since I've actively developed
due to job title going up the greasy pole but decided to embark on a little
project to illustrate to my team what can be done .  Wish it had been
around in my earlier days :-)  But then I go all the way back to punch tape
and cards and FORTRAN too.



Thanks David

**Comment by Wagnerp** [comment]
This is fixed in build 2103
