### ISSUE TITLE
[Bug]: Since the "Nightlies" have been created, loading the Standard toolkit project causes Visual Studio to go ape

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#358]
Something is wrong in the environment setting (Directory / props / etc) since the nightlies file build references have been added, that causes visual studio (16.11.2 or 3) to keep attempting to load the project nugets even tho it doesn;t have any !

See gif:

![MessedUpProjectLoad](https://user-images.githubusercontent.com/2418812/133481084-42137fd0-f24f-49c6-9667-0ccc1d7b40ef.gif)

**Comment by Wagnerp** [comment]
@Smurf-IV Yes the work around is to temporarily remove `.$(CurrentDate)` from `Directory.Build.props` not sure why it does this

**Comment by Smurf-IV** [comment]
nightlies.. So only need yyyyMMdd every second is being counted (Via VS) as a new version so it reloads !

**Comment by Smurf-IV** [comment]
Changed to this and now get a "Single" load ;-)
`<CurrentDate>$([System.DateTime]::Now.ToString(YYYYMMDD))</CurrentDate>
		`

**Comment by Wagnerp** [comment]
Fixed in build 2110
