### ISSUE TITLE
[Bug] Nightlies version needs to have something that allows installers to upgrade correctly

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#361]
Background info:
Windows installers (i.e. those that have msi buried in them somewhere) use the first 3 groups of numbers to determine if they should upgrade / replace a target dll

i.e. Major**.**Minor**.**Build**.**ServicePack

So the nightlies are using the standard 6.2110.0 as their number, meaning that when the final version of 2110 is released. it will never be replaced by an installer.

**Comment by Smurf-IV** [comment]
Major = 6
Minor = YYMM
Build = YearDayOffset (i.e. what day number of the year is it ?)
ServicePack = Hardly ever used nowadays due to windows ingoring it, / Continuos delivery / Linux hates it / etc
Special Build flag to indicate alpha / nightly

**Comment by Wagnerp** [comment]
Fixed in build 2110

**Comment by Smurf-IV** [comment]
Can there be a build to test this please ?

**Comment by Wagnerp** [comment]
> Can there be a build to test this please ?

Was going to deploy a test build, but hit a roadblock

![image](https://user-images.githubusercontent.com/949607/133653290-ab37b559-0aca-422c-8d95-8802f9a16814.png)

**Comment by Wagnerp** [comment]
Scratch that, it works really well!

**Comment by Smurf-IV** [comment]
Nope:
![image](https://user-images.githubusercontent.com/2418812/133659477-e8325663-0e57-4e6b-beec-23cb857d1dd8.png)

**Comment by Smurf-IV** [comment]
Also I think the Copyright should be changed so that the Component factory stuff comes last ;-)

**Comment by Wagnerp** [comment]
> Nope:
> ![image](https://user-images.githubusercontent.com/2418812/133659477-e8325663-0e57-4e6b-beec-23cb857d1dd8.png)

Ahh sorry, now I understand, easy to fix

**Comment by Smurf-IV** [comment]
The Nuget description is okay, just not what is inserted into the actual binary dll's
![image](https://user-images.githubusercontent.com/2418812/133659963-88ced7a7-589a-49fd-8348-4683b3ed129c.png)

**Comment by Smurf-IV** [comment]
> Ahh sorry, now I understand, easy to fix

No, it will not be that easy....

The 3rd and fourth number groups have a max value of int16.Max

That is why I suggested using the Day number (With an hour if you must)

**Comment by Smurf-IV** [comment]
The binary version numbers are stricter than the actual nuget strings.

**Comment by Wagnerp** [comment]
So, `6.110.1618`?

**Comment by Wagnerp** [comment]
Like so?

![image](https://user-images.githubusercontent.com/949607/133661105-47efe3e1-d5a2-4f6c-a5f2-d1a6a0c4cad3.png)

**Comment by Wagnerp** [comment]
@Smurf-IV 

TaDa!!!!!!!!!!!!

![image](https://user-images.githubusercontent.com/949607/133661987-d4aafb86-aa0b-4e6e-a694-9aa6c5b1bfc4.png)

Still got to do the copyright bit ;)

**Comment by Smurf-IV** [comment]
Yes, I think that "Might" be enough.. There's normally 3 values for version sin Windows dll's .. It gets confusing when they are all different / missing / not displayed / strings do not equal their binary manifest equivalents / etc.

**Comment by Smurf-IV** [comment]
Any news on this ?

**Comment by Wagnerp** [comment]
> Any news on this ?

The changes that were made are in today's nightly build. Though I don't know if the `ProductVersion` to `6.2110.MMdd`?

**Comment by Smurf-IV** [comment]
>  `6.2110.MMdd`

Needs to be `6.YYMM.ddd`

**Comment by Wagnerp** [comment]
> > `6.2110.MMdd`
> 
> Needs to be `6.YYMM.ddd`

I'll put it in now

**Comment by Smurf-IV** [comment]
Modify that.. 
`ddd` returns a string !! 
have to use the explicit call to `datetime.DayOfYear()`

**Comment by Wagnerp** [comment]
> Modify that..
> `ddd` returns a string !!
> have to use the explicit call to `datetime.DayOfYear()`

I think it's simply `dd`

**Comment by Wagnerp** [comment]
Something went wrong :(

![image](https://user-images.githubusercontent.com/949607/133830761-369d8366-7171-4d9f-b07f-f32a731e9d95.png)

**Comment by Smurf-IV** [comment]
`dd` is the day of month

**Comment by Wagnerp** [comment]
Same is true with the following code

![image](https://user-images.githubusercontent.com/949607/133831527-5e089b0a-d32b-464d-86c0-a4e60c433b19.png)

**Comment by Wagnerp** [comment]
@Smurf-IV RE: Build errors, forgot to say you need to use `yyyyMMdd` as it won't build

**Comment by Wagnerp** [comment]
Done

![image](https://user-images.githubusercontent.com/949607/133881576-670f71f2-210c-44e5-9c63-05b966088d9b.png)

**Comment by Smurf-IV** [comment]
Nope, File version and product version to be the same please (As well as the internal Library version)

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/133887850-543045c8-8ea6-4adb-a108-04231b7abe8b.png)

**Comment by Smurf-IV** [comment]
yay.

**Comment by Wagnerp** [comment]
Completed - 19/09/2021

**Comment by Smurf-IV** [comment]
Incorrect Nuget package versioning

![Uploading image.png…]()

**Comment by Smurf-IV** [comment]
Or is it Visual studio trying to be clever and tell me that because I install 2110 - that it has a "Better / newer" version ?

Can those be removed / withdrawn from nuget to be sure please ?

**Comment by Wagnerp** [comment]
> Or is it Visual studio trying to be clever and tell me that because I install 2110 - that it has a "Better / newer" version ?
> 
> Can those be removed / withdrawn from nuget to be sure please ?

Those have been 'unlisted'. As per NuGet rules, you can't fully remove packages, unless they contain sensitive info i.e passwords by accident.

**Comment by Smurf-IV** [comment]
Ok, So it's VS being "Clever"
I'll start from fresh tomorrow sometime.

**Comment by Smurf-IV** [comment]
Can you do another "Nightly" so that I can test to see if it detects for a VS studio package upgrade please ?

**Comment by Wagnerp** [comment]
> Can you do another "Nightly" so that I can test to see if it detects for a VS studio package upgrade please ?

There is a `6.2109.264` or do you mean do a `6.2109.264.1`?

**Comment by Smurf-IV** [comment]
Whatever todays will be.
I cannot remember which I used in the qa code base this morning.

**Comment by Wagnerp** [comment]
> Whatever todays will be.
> I cannot remember which I used in the qa code base this morning.

Todays one is 264 if that helps, no real changes, just removed some code to try & fix #376 later in the week

**Comment by Smurf-IV** [comment]
The current build format `6.yymm.doy` does not alow msi installers to use it correctly.
The spec states `byte.byte.word.word`
`yymm` is `> 255`

**Comment by Wagnerp** [comment]
> The current build format `6.yymm.doy` does not alow msi installers to use it correctly. The spec states `byte.byte.word.word` `yymm` is `> 255`

Unless installer versions are dealt differently, i.e `6.0.2xxx`?

**Comment by Smurf-IV** [comment]
The msi "Looks" at each file and performs a comparison on the version numbers.
If it is "dumb" (Which it mostly is, due to it having come from Vista) it might be looking at the wrong values and causing problems.
I'll have to do more testing.

**Comment by Smurf-IV** [comment]
@Wagnerp 
![image](https://user-images.githubusercontent.com/2418812/147741331-9b22f059-13b1-41c2-b164-f9b877657075.png)

**Comment by Smurf-IV** [comment]
@Wagnerp Just to throw "Yet another" spanner in the works..

If the first value reflects the framework, then should it not be 60 so that it represent 6.0, in case there is ever a 6.1 release (Quite likely as it it will be LTS), 
or in the future a 7.1

**Comment by Wagnerp** [comment]
> @Wagnerp Just to throw "Yet another" spanner in the works..
> 
> If the first value reflects the framework, then should it not be 60 so that it represent 6.0, in case there is ever a 6.1 release (Quite likely as it it will be LTS), or in the future a 7.1

@Smurf-IV Looking at the current lifecycle, this should not be an issue, as it'll go 7, 8 (LTS), 9, 10 (LTS)... Documentation (only up to .NET 8) https://github.com/dotnet/core/blob/main/roadmap.md

**Comment by Wagnerp** [comment]
@Smurf-IV To be 'safe' should I change it to `6.0.yyMM.doy`?

**Comment by Smurf-IV** [comment]
Possible 
but
- you would have to go and remove a load of nugets "again"
Going to 60, means that
- all existing installations that have been using 6.yymm (nightly or canary, etc) are covered as 60 is clearly bigger than 6 in the version checking
- Simple to document and understand.

**Comment by Wagnerp** [comment]
> you would have to go and remove a load of nugets "again"

Not now, I've found a neat CLI utility, which can batch unlist packages with one line. Total time to change ~10 mins.

**Comment by Smurf-IV** [comment]
But, I have found that it is nightmare to update installers, to go from 
6.2111 to 6.22.1
because 2111 > 22

**Comment by Wagnerp** [comment]
So, leave it alone?

**Comment by Smurf-IV** [comment]
No, to solve 6.**21xx** going to 6.**22**.xx, 

Would be to make the `6.` part be  `60.`

so 60.22.xx is always going to be bigger than 6.21xx

**Comment by Wagnerp** [comment]
> No, to solve 6.**21xx** going to 6.**22**.xx,
> 
> Would be to make the `6.` part be `60.`
> 
> so 60.22.xx is always going to be bigger than 6.21xx

Ok, so `60.2x.xx.xxx`, `70.2x.xx.xxx` etc?

**Comment by Wagnerp** [comment]
@Smurf-IV Please re-open if necessary

**Comment by Smurf-IV** [comment]
`60.`yy.mm.doy works and upgrades over the previous `6.`yymm.doy versions :-)

**Comment by Wagnerp** [comment]
> `60.`yy.mm.doy works and upgrades over the previous `6.`yymm.doy versions :-)

Great to hear!
