### ISSUE TITLE
[Bug]: Colors ComboBox problem

### ISSUE THREAD

**Issue by mbsysde99** [Krypton-Suite/Standard-Toolkit#362]
I want to create a `Custom ComboBox` containing a list of colors.

The `DrawItemEventHandler` event is only raised when the `DrawMode` property is set to `DrawMode.OwnerDrawFixed` or `DrawMode.OwnerDrawVariable`. 

I set `this.DrawMode = DrawMode.OwnerDrawFixed;` but `CustomComboBox_DrawItem` never executed, is this a bug of `KryptonComboBox`?

```
using Krypton.Toolkit;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Reflection;
using System.Windows.Forms;

namespace ColorComboBox
{
    public class CustomComboBox : KryptonComboBox
    {
        #region Fields
        private IPalette? _palette;
        private List<Color> _colorList = new List<Color>();
        #endregion

        #region Constructor
        public CustomComboBox()
        {
            SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer | ControlStyles.ResizeRedraw, true);

            _colorList = GetColorList();
            this.DataSource = _colorList;
            this.DropDownStyle = ComboBoxStyle.DropDownList;
            this.DrawMode = DrawMode.OwnerDrawFixed;
            this.DrawItem += CustomComboBox_DrawItem;
        }
        #endregion

        #region AvoidFlicker
        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams createParams = base.CreateParams;
                createParams.ExStyle |= 0x02000000;  // Turn on WS_EX_COMPOSITED
                return createParams;
            }
        }
        #endregion

        #region Color
        public List<Color> GetColorList()
        {
            List<Color> colorList = new List<Color>();
            foreach (PropertyInfo property in typeof(Color).GetProperties())
            {
                if (property.PropertyType == typeof(Color))
                {
                    object? objColor = property.GetValue(null);
                    if (objColor != null)
                    {
                        colorList.Add((Color)objColor);
                    }
                }
            }
            return colorList;
        }
        #endregion

        #region Render
        private void CustomComboBox_DrawItem(object sender, DrawItemEventArgs e)
        {
            e.DrawBackground();
            if (e.Index >= 0)
            {
                Color color = (Color)_colorList[e.Index];
                Rectangle r1 = new Rectangle(e.Bounds.Left + 1, e.Bounds.Top + 1, 2 * (e.Bounds.Height - 2), e.Bounds.Height - 2);
                Rectangle r2 = Rectangle.FromLTRB(r1.Right + 2, e.Bounds.Top, e.Bounds.Right, e.Bounds.Bottom);
                string txt = this.GetItemText(this.Items[e.Index]);
                using (var b = new SolidBrush(color))
                {
                    e.Graphics.FillRectangle(b, r1);
                    e.Graphics.DrawRectangle(Pens.Black, r1);

                    TextRenderer.DrawText(e.Graphics, txt, this.Font, r2, this.ForeColor, TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
                }
            }
        }
        #endregion
    }
}
```

**Comment by Smurf-IV** [comment]
I know that this may be counter intuitive, but as you are trying to perform the drawing actions, then you do not need any of the functionality that Krypton provides? 
So it might be better to drop back to the native `Winform ComboBox`

**Comment by mbsysde99** [comment]
I used Krypton.Toolkit -Version 5.550.2108.1. 
I resolved this problem with replace `Inheritance` from `KryptonComboBox` to `System.Windows.Forms.ComboBox`. Thanks

    public class CustomComboBox : System.Windows.Forms.ComboBox 
    {
       // ...
    }

Result:
![image](https://user-images.githubusercontent.com/38758714/133913129-865236d0-08a4-4274-b65a-66d9d5d49e67.png)

**Comment by Smurf-IV** [comment]
It does call it, but "Keeps" it private:
![image](https://user-images.githubusercontent.com/2418812/139803884-b399be38-b2a8-4fca-8bf2-44eed0838798.png)

Because it handling an "Internal" ComboBox override, to then provide all the control NonClient (Border etc) drawing in the Krypton theme.

**Comment by Wagnerp** [comment]
@mbsysde99 Is it possible to use this code in the extended toolkit as an 'officially' supported control?

**Comment by mbsysde99** [comment]
> @mbsysde99 Is it possible to use this code in the extended toolkit as an 'officially' supported control? Y es, of course

**Comment by mbsysde99** [comment]
I found a bug in `KryptonComboBox.cs`.

A. Look `OnComboBoxDrawItem` method in `KryptonComboBox.cs`
1. Add  `OnDrawItem(e);` in last line of  `OnComboBoxDrawItem`

        private void OnComboBoxDrawItem(object sender, DrawItemEventArgs e)
        {
	        // others code not displayed for easy reading
            // ...
            OnDrawItem(e); // add this to trigger CustomComboBox_DrawItem (BUG IN HERE, MISSING THIS IN LAST OF CODE )
        }

2.  Add `EnableColorComboBox` property  in `KryptonComboBox.cs`

        public static bool EnableColorComboBox { get; set; } = false;

3. Add `follows code` in `WndProc` method in  `KryptonComboBox.cs`

		protected override void WndProc(ref Message m)
		{
	        // others code not displayed for easy reading
            // ...
			switch (m.Msg)
			{				
				case PI.WM_.PAINT:
				{
					// Draw using a solid brush
					Rectangle rectangle = new(rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top);
					rectangle = CommonHelper.ApplyPadding(VisualOrientation.Top, rectangle,	states.Content.GetContentPadding(state));

					try
					{
						//using SolidBrush foreBrush = new(states.Content.GetContentShortTextColor1(state));
						//g.DrawString(Text, states.Content.GetContentShortTextFont(state), foreBrush, rectangle, stringFormat);

						if (EnableColorComboBox)
						{
							if (SelectedIndex >= 0)
							{
								var color = (Color)this.Items[SelectedIndex];
								var rect1 = new Rectangle((int)(rectangle.Left + 1), (int)(rectangle.Top + 1), (int)(2 * (rectangle.Height - 2)), (int)(rectangle.Height - 3));
								var rect2 = Rectangle.FromLTRB(rect1.Right + 2, (int)rectangle.Top, (int)rectangle.Right, (int)rectangle.Bottom);
								var text = this.GetItemText(this.Items[SelectedIndex]);
								using (var b = new SolidBrush(color))
								{
									g.FillRectangle(b, rect1);
									g.DrawRectangle(Pens.LightSteelBlue, rect1);

									TextRenderer.DrawText(g, text, this.Font, rect2, this.ForeColor, TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
								}
							}
						}							
					}
					catch (ArgumentException)
					{
						using SolidBrush foreBrush = new(ForeColor);
						g.DrawString(Text, Font, foreBrush, rectangle, stringFormat);
					}
				}

				// Remove clipping settings
				PI.SelectClipRgn(hdc, IntPtr.Zero);

				// Draw the drop down button
				DrawDropButton(g, dropRect);
			}
		}
	

B. Look `Constructor` of `CustomComboBox.cs`
1. Add `EnableColorComboBox = true;` in `CustomComboBox` method in  `CustomComboBox.cs`

		 #region Constructor
		 public CustomComboBox()
		 {
			// others code not displayed for easy reading
			// ...
			
			_colorList = GetColorList();		
			
			EnableColorComboBox = true;	 // add this to enable color mode	 	
			 
			this.DataSource = _colorList;
			this.DropDownStyle = ComboBoxStyle.DropDownList;
			this.DrawMode = DrawMode.OwnerDrawFixed;
			this.DrawItem += CustomComboBox_DrawItem;
		 }
		 #endregion

Result is
![image](https://user-images.githubusercontent.com/38758714/140257825-a467c362-fb5a-4278-8077-9d58669c2f68.png)

![image](https://user-images.githubusercontent.com/38758714/140257926-c5003ffa-21fc-4bcb-a4f2-a0d4436c37fb.png)

**Comment by Wagnerp** [comment]
> I found a bug in `KryptonComboBox.cs`.
> 
> A. Look `OnComboBoxDrawItem` method in `KryptonComboBox.cs`
> 
> 1. Add  `OnDrawItem(e);` in last line of  `OnComboBoxDrawItem`
>    ```
>     private void OnComboBoxDrawItem(object sender, DrawItemEventArgs e)
>     {
>         // others code not displayed for easy reading
>         // ...
>         OnDrawItem(e); // add this to trigger CustomComboBox_DrawItem (BUG IN HERE, MISSING THIS IN LAST OF CODE )
>     }
>    ```
> 2. Add `EnableColorComboBox` property  in `KryptonComboBox.cs`
>    ```
>    public static bool EnableColorComboBox { get; set; } = false;
>    ```
> 3. Add `follows code` in `WndProc` method in  `KryptonComboBox.cs`
>    ```
>     protected override void WndProc(ref Message m)
>     {
>         // others code not displayed for easy reading
>         // ...
>     	switch (m.Msg)
>     	{				
>     		case PI.WM_.PAINT:
>     		{
>     			// Draw using a solid brush
>     			Rectangle rectangle = new(rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top);
>     			rectangle = CommonHelper.ApplyPadding(VisualOrientation.Top, rectangle,	states.Content.GetContentPadding(state));
>    
>     			try
>     			{						
>     				if (EnableColorComboBox)
>     				{
>     					if (SelectedIndex >= 0)
>     					{
>     						var color = (Color)this.Items[SelectedIndex];
>     						var rect1 = new Rectangle((int)(rectangle.Left + 1), (int)(rectangle.Top + 1), (int)(2 * (rectangle.Height - 2)), (int)(rectangle.Height - 3));
>     						var rect2 = Rectangle.FromLTRB(rect1.Right + 2, (int)rectangle.Top, (int)rectangle.Right, (int)rectangle.Bottom);
>     						var text = this.GetItemText(this.Items[SelectedIndex]);
>     						using (var b = new SolidBrush(color))
>     						{
>     							g.FillRectangle(b, rect1);
>     							g.DrawRectangle(Pens.LightSteelBlue, rect1);
>    
>     							TextRenderer.DrawText(g, text, this.Font, rect2, this.ForeColor, TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
>     						}
>     					}
>     				}
>     			        else {
>     					using SolidBrush foreBrush = new(states.Content.GetContentShortTextColor1(state));
>     					g.DrawString(Text, states.Content.GetContentShortTextFont(state), foreBrush, rectangle, stringFormat);	
>     				}
>     			}
>     			catch (ArgumentException)
>     			{
>     				using SolidBrush foreBrush = new(ForeColor);
>     				g.DrawString(Text, Font, foreBrush, rectangle, stringFormat);
>     			}
>     		}
>    
>     		// Remove clipping settings
>     		PI.SelectClipRgn(hdc, IntPtr.Zero);
>    
>     		// Draw the drop down button
>     		DrawDropButton(g, dropRect);
>     	}
>     }
>    ```
> 
> B. Look `Constructor` of `CustomComboBox.cs`
> 
> 1. Add `EnableColorComboBox = true;` in `CustomComboBox` method in  `CustomComboBox.cs`
>    ```
>      #region Constructor
>      public CustomComboBox()
>      {
>     	// others code not displayed for easy reading
>     	// ...
>     	
>     	_colorList = GetColorList();		
>     	
>     	EnableColorComboBox = true;	 // add this to enable color mode	 	
>     	 
>     	this.DataSource = _colorList;
>     	this.DropDownStyle = ComboBoxStyle.DropDownList;
>     	this.DrawMode = DrawMode.OwnerDrawFixed;
>     	this.DrawItem += CustomComboBox_DrawItem;
>      }
>      #endregion
>    ```
> 2. Add `EnableColorComboBox = true;` in `CustomComboBox_DrawItem` method in  `CustomComboBox.cs`
>    ```
>     #region Render
>     private void CustomComboBox_DrawItem(object sender, DrawItemEventArgs e)
>     {
>     	if (EnableColorComboBox)
>     	{				
>     		e.DrawBackground();
>     		if (e.Index >= 0)
>     		{
>     			Color color = (Color)_colorList[e.Index];
>     			Rectangle r1 = new Rectangle(e.Bounds.Left + 1, e.Bounds.Top + 1, 2 * (e.Bounds.Height - 2), e.Bounds.Height - 2);
>     			Rectangle r2 = Rectangle.FromLTRB(r1.Right + 2, e.Bounds.Top, e.Bounds.Right, e.Bounds.Bottom);
>     			string txt = this.GetItemText(this.Items[e.Index]);
>     			using (var b = new SolidBrush(color))
>     			{
>     				e.Graphics.FillRectangle(b, r1);
>     				e.Graphics.DrawRectangle(Pens.Black, r1);
>    
>     				TextRenderer.DrawText(e.Graphics, txt, this.Font, r2, this.ForeColor, TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
>     			}
>     		}
>     	}
>     }
>     #endregion
>    ```
> 
> Result is ![image](https://user-images.githubusercontent.com/38758714/140257825-a467c362-fb5a-4278-8077-9d58669c2f68.png)
> 
> ![image](https://user-images.githubusercontent.com/38758714/140257926-c5003ffa-21fc-4bcb-a4f2-a0d4436c37fb.png)

I'll introduce it as an 'official' control in the extended toolkit.
