### ISSUE TITLE
[Bug]: KryptonSplitContainer Separator

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#364]
When manually dragging the separator of a KryptonSplitContainer and the form is not on the primary screen, the separator is shown moving on the primary screen. The image below shows the separator being drawn on the primary screen, but the form is on the secondary screen.

This occurs for all SeparatorStyles and all KryptonToolkit versions I have used (currently 5.550.2108 stable).

![Separator](https://user-images.githubusercontent.com/1911567/133831061-fd2ae416-2005-4a72-b7e3-0e8c0f689e92.png)
.

**Comment by Wagnerp** [comment]
@Smurf-IV Calculation error?

@sdreb3421 Is it possible to upload a demo project that reproduces this bug?

**Comment by Smurf-IV** [comment]
lol...

I wonder if it also does weird stuff if the monitor references are swapped (i.e. primary is right)
And taking it a step further, what about vertical alignments (1 above the other)

Any one want to test ?

**Comment by Smurf-IV** [comment]
Standard Demo Splitter does this when moved to the 2nd monitor when Primary is left.

**Comment by Wagnerp** [comment]
> Standard Demo Splitter does this when moved to the 2nd monitor when Primary is left.

Will do!

**Comment by Wagnerp** [comment]
Lol...

I can verify that the horizontal splitter has the same bug!

**Comment by sdreb3421** [comment]
Too easy!

**Comment by Smurf-IV** [comment]
> Too easy!


Unless the code I have fixed / removed then stops it working on Win 7 / Win 8.x and win 11 !!

**Comment by Wagnerp** [comment]
> > Too easy!
> 
> Unless the code I have fixed / removed then stops it working on Win 7 / Win 8.x and win 11 !!

@Smurf-IV Do you want me to test this fix on Win 7, 8, 8.1 & 11?

**Comment by Smurf-IV** [comment]
That would be sensible.
To run through al the examples with the nightly Nuget and see if they work
as expected. (i.e. match their example pictures at least.)

Note: Do you have Double screens native installations of those Os's,
otherwise the "Screen.###" code will only ever return a single entity

**Comment by Wagnerp** [comment]
> That would be sensible. To run through al the examples with the nightly Nuget and see if they work as expected. (i.e. match their example pictures at least.) Note: Do you have Double screens native installations of those Os's, otherwise the "Screen.###" code will only ever return a single entity
> […](#)
> On Sat, 18 Sept 2021 at 08:00, Peter Wagner ***@***.***> wrote: Too easy! Unless the code I have fixed / removed then stops it working on Win 7 / Win 8.x and win 11 !! @Smurf-IV <https://github.com/Smurf-IV> Do you want me to test this fix on Win 7, 8, 8.1 & 11?

That's going to be a issue, yes I do have dual screens, but don't have dual/multi booting set up.

**Comment by Smurf-IV** [comment]
A call to the users: Help required with testing this please

**Comment by Wagnerp** [comment]
Posted to Discord

**Comment by sdreb3421** [comment]
Confirm fixed on Windows 10 21H1 with a three screen monitor (left, primary, right).

**Comment by Smurf-IV** [comment]
> Confirm fixed on Windows 10 21H1 with a three screen monitor (left, primary, right).

Closing this.
