### ISSUE TITLE
[Bug]: KryptonNumericUpDown.TextAlign doesn't work properly

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#37]
**Describe the bug**
The alignment of the KryptonNumericUpDown's text doesn't work properly when the text is being edited. as shown in the gif below. 

**To Reproduce**
As demonstrated below:
1. Add a KryptonNumericUpDown control (its text alignment should be `Center` by default).
2. Move the focus in and out of the control and/or start typing.

**Expected behavior**
The text alignment should be the same whether or not the text is being edited.

**Screenshots**
![NUP](https://user-images.githubusercontent.com/18140178/102691752-79cb9c00-4217-11eb-90e7-bfdab0f7696e.gif)

**Desktop:**
 - OS: Windows 10
 - Build: 2004.

**Additional context**
The issue happens when the `TextAlign` property of the internal `_numericUpDown` WinForms control doesn't match the text alignment set for the Krypton NUP control. This happens in two cases:

1. By default, the alignment is set to `Center` but `_numericUpDown.TextAlign` is `Left`. This is probably caused by the following point anyway.
2. When the `.Content.TextH` of a state (e.g., `StateCommon`) is changed, it doesn't affect the `TextAlign` property.

I noticed that the `TextAlign` property does set the `_numericUpDown.TextAlign` property accordingly. But since the former has a `[Browsable(false)]` attribute, I'm assuming it's not to be used, in favor of the `TextH` property (which fails to update the `_numericUpDown.TextAlign` property).

So, the fix should be either to update `_numericUpDown.TextAlign` each time `TextH` is changed or if `TextAlign` is what should be used (I doubt it), make it visible and hide `TextH` instead.

**Comment by Wagnerp** [comment]
@Smurf-IV Would this be a similar bug as referenced in #20?

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Would this be a similar bug as referenced in #20?

#20 is font Selected issue (Via "Krypton Selected" values not being used I suspect)

**Comment by Smurf-IV** [comment]
This has (at least) 2 issues
OnMouse leave removes the Highlight (as per #38 ) which causes the edit to change
The Edit window is a different layout / control to the numeric display, and does not always perform a proper overwrite to f the edit control area

**Comment by giduac** [comment]
Hi,

I'd like to add some findings to this that I came across when using this control.

If the keyboard-cursor is in the control and the mouse pointer is not over the control:

- Win7/8 the mouse wheel can still scroll the value up or down.
- Win10/11 the above is only possible if the mouse pointer is over the control. The keyboard focus is maintained.

This behaviour also applies to other types of controls and is there (has been changed) since Win10

The KryptonNUD control does not have the ability (like the Winforms one) to position the cursor on the value with the mouse and start editing at the selected position (see video).

https://user-images.githubusercontent.com/96108132/152814620-30267c29-d146-4862-aad4-8f64ddc8c5f4.mp4

**Comment by Smurf-IV** [comment]
Solved initial opening point with as part of #39
@giduac Please retest when the new nightly is produced.

**Comment by giduac** [comment]
@Smurf-IV 
Tested with Nightly .59
KNUD control now works as it should and the cursor can be aimed and placed on the desired location.

Opened a new ticket for KDomainUpDown
[https://github.com/Krypton-Suite/Standard-Toolkit/issues/660](https://github.com/Krypton-Suite/Standard-Toolkit/issues/660)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Tested with Nightly .59 KNUD control now works as it should and the cursor can be aimed and placed on the desired location.

Great

> Opened a new ticket for KDomainUpDown #660

Good practice.. Thanks

**Comment by giduac** [comment]
@Smurf-IV
This can be closed then ... ??

**Comment by Smurf-IV** [comment]
It already was:
![image](https://user-images.githubusercontent.com/2418812/156206457-9d828fd2-fe9c-4001-80ef-f8cd3ff7afd7.png)
