### ISSUE TITLE
[Bug]: MinimumWidth (and possibly MaximumWidth) on ribbon group not DPI aware.

### ISSUE THREAD

**Issue by Tape-Worm** [Krypton-Suite/Standard-Toolkit#374]
I added a single button to a ribbon group, and because the group does not seem to resize based on the group caption (there should be an option for this btw), I set the MinimumWidth property on the group to 90 pixels.

In 96 DPI, I get this:
![image](https://user-images.githubusercontent.com/9710137/134038348-96b7cd13-a360-43a4-82fa-3bd25c2e1fcb.png)
And this is correct.

But, when I run it at my native DPI in 4k (150%):
![image](https://user-images.githubusercontent.com/9710137/134038444-792091c1-5dfa-4f0e-a070-74c960844dc8.png)
As you can see, the group text is now clipped.  

If you don't mind a suggestion: Instead of jumping through the hoops required to make it DPI aware, fix it up so that the group min width is based on the caption size (and if ```MinimumWidth > -1```, then use that instead).

**Comment by Smurf-IV** [comment]
It seems to be thinking that there are invisible buttons to take into account, I have not experienced this (As it also appears in your 96dpi picture.

**Comment by Tape-Worm** [comment]
Yeah, if you set the ```MinimumWidth``` to -1, it will squish the group down and cut off the text even in 96 DPI. I forgot to mention that.

I went through the code, and it appears it doesn't take the caption into account at all when trying to get the size. In fact, it was very difficult to retrieve the size of the caption, and even then, it clips that size to the width of the group.

**Comment by Smurf-IV** [comment]
It would also be nice if the caption is bigger, for the buttons to then be placed centrally in the group.. But small steps first :-)

**Comment by Smurf-IV** [comment]
Using the latest alpha build and .net48, I set the TrackBar Min width to be 250
On Non HDPI:
![image](https://user-images.githubusercontent.com/2418812/142211524-6ff744ef-f8a1-43fc-a6fa-8b26cce37ff2.png)

on HDPI (Note the Fuzzy look because the manifest file is missing)
![image](https://user-images.githubusercontent.com/2418812/142211648-a2de556a-2f87-4da5-ada2-060fb471a83f.png)

@Tape-Worm Can you retest please ?

**Comment by Smurf-IV** [comment]
@Tape-Worm Can you raise a "Feature request" for the min to take into account the Caption size please

**Comment by Smurf-IV** [comment]
Using todays alpha dev code base, and the `Ribbon Controls 2022` sample in HDPI OS screen gives the following:
![image](https://user-images.githubusercontent.com/2418812/142756822-4f79eeac-9990-4def-a331-db2128f7d2e8.png)

Will aim to set tracking to have a minimum width, and have a look at the other examples that use single buttons to see if they can be set also.

**Comment by Smurf-IV** [comment]
Min width is now respected:
![image](https://user-images.githubusercontent.com/2418812/142757085-55703c83-1481-4737-b15e-d9a753a3f5cd.png)

In `Ribbon Tooltips`; setting "Include" have a min of 300 causes the scrollbar to appears, (i.e. preventing shrink to small first)
![image](https://user-images.githubusercontent.com/2418812/142757198-0987f58f-70dd-487d-8e97-c246f43f2ec9.png)


Seems like #393 Fixed this issue.
