### ISSUE TITLE
[Bug]: Mouse over Ribbon Group Exception

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#375]
When a KryptonPalette is set as the KryptonRibbon Palette property, moving the mouse over any KryptonRibbonGroup causes a crashing exception. 

To reproduce, use Nightly build (6.2109.263-alpha), add a new form, add a new ribbon and group, add a new palette, set the ribbons palette property, run the project, move mouse over group.

![image](https://user-images.githubusercontent.com/1911567/134046133-b5fb94e5-6275-4699-9ee2-4ef1e4e934cd.png)

**Comment by Smurf-IV** [comment]
Can you attach the palette you are using, or state where it is from please ?

**Comment by sdreb3421** [comment]
The palette was totally untouched. I was able to reproduce with a totally new Form, Ribbon, Group and Palette.

**Comment by sdreb3421** [comment]
I did a little research. This is likely due to a null being returned on line 3829 of Krypton.Toolkit/Controls Toolkit/KryptonPalette.cs. Maybe a new case statement needs to be added to capture a new palette feature?

**Comment by Wagnerp** [comment]
@Smurf-IV Had a look, and it seems normal. @sdreb3421 What version did the issue start to appear in? The `default` case should never fire.

![image](https://user-images.githubusercontent.com/949607/134303943-f2538aeb-8ce6-4968-abc8-494bb16b300a.png)

**Comment by sdreb3421** [comment]
I noticed it when first testing a Nightly build. The code reference was just a guess based on the exception stack trace. We're you able to reproduce the exception?

**Comment by Wagnerp** [comment]
> I noticed it when first testing a Nightly build. The code reference was just a guess based on the exception stack trace. We're you able to reproduce the exception?

Is there a demo project that you can send?

**Comment by sdreb3421** [comment]
Of course, what's the best way to share a demo project?

**Comment by Wagnerp** [comment]
> Of course, what's the best way to share a demo project?

Any of the cloud hosting services should be fine

**Comment by Wagnerp** [comment]
I don't know if this would help?

![image](https://user-images.githubusercontent.com/949607/134375476-14af335f-8e29-451d-97e4-b64fdbc4b317.png)

**Comment by Wagnerp** [comment]
@sdreb3421 & @Smurf-IV 

I think it's fixed

![image](https://user-images.githubusercontent.com/949607/134377716-10d138b7-6216-43b4-bdc0-1b05bd504075.png)

**Comment by sdreb3421** [comment]
I can verify if it's fixed on the next nightly. I assume those come out nightly? If not, I'll post the demo project.

**Comment by Wagnerp** [comment]
> I can verify if it's fixed on the next nightly. I assume those come out nightly? If not, I'll post the demo project.

Was that 264 or 265?

**Comment by sdreb3421** [comment]
I found it in 263

**Comment by Wagnerp** [comment]
> I found it in 263

Sorry, I'm confusing myself now ;)

**Comment by Smurf-IV** [comment]
> 
> 
> I don't know if this would help?
> 
> ![image](https://user-images.githubusercontent.com/949607/134375476-14af335f-8e29-451d-97e4-b64fdbc4b317.png)

But then no-one find it in nuget packages ;-(

**Comment by Wagnerp** [comment]
> > I don't know if this would help?
> > ![image](https://user-images.githubusercontent.com/949607/134375476-14af335f-8e29-451d-97e4-b64fdbc4b317.png)
> 
> But then no-one find it in nuget packages ;-(

I've included it in todays nightly for testing. Seems that `tracking` was never put in, therefore it was tripping to null.

**Comment by Smurf-IV** [comment]
Ok, so it was my turn to be confusing myself ;-(
Perhaps the Debug.Assert should be more of throw not support exception with the value in the message.

**Comment by Wagnerp** [comment]
> Ok, so it was my turn to be confusing myself ;-(
> Perhaps the Debug.Assert should be more of throw not support exception with the value in the message.

Should I go to the original ComponentFactory code to find any differences?

**Comment by Smurf-IV** [comment]
you could try.
Winmerge between them and see lot's of things that are different, but there might be a clue.

**Comment by Wagnerp** [comment]
> you could try.
> Winmerge between them and see lot's of things that are different, but there might be a clue.

No changes, except for the new case definition I just put in

**Comment by sdreb3421** [comment]
Confirmed fixed in new nightly.
