### ISSUE TITLE
[Bug]: Sparkle - ## (Dark mode) and Sparkle - ## (Light mode) do not change anything when selected

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#376]
This is in Nightly 263

![SparkleModesDoNotChange](https://user-images.githubusercontent.com/2418812/134130323-26c57538-f0d6-4b8d-b9d0-770f87275e90.gif)

**Comment by Wagnerp** [comment]
Think it's something to do with the KManager, need to go back to the PR I did for the others, as I've forgot what changes I made ;)

**Comment by Wagnerp** [comment]
I'm a bit confused, as it should work

**Comment by Smurf-IV** [comment]
The video shows it is not.

**Comment by Wagnerp** [comment]
Fixed, though colours need to be re-looked at!
