### ISSUE TITLE
MDI Child form not fully maximizing not merging on the ribbon.

### ISSUE THREAD

**Issue by pgaraneta** [Krypton-Suite/Standard-Toolkit#380]
Hi.

Child form when maximized is not fully maximizing and/or merging to the parent form. Child form's heading bar remains beneath the ribbon.

![image](https://user-images.githubusercontent.com/85190700/134464783-5527b837-ad4f-4a5a-b937-6b98b6b4dc98.png)

I have to click collapse and expand ribbon minimize button to get have it behave as expected. This bug exist with multiple child forms as well.

This did not exist in the older ComponentFactory version. Happened after I have replaced the controls with canary versions of Krypton.Ribbon/Toolkit/Navigator.

![image](https://user-images.githubusercontent.com/85190700/134465080-a69d0d4c-2422-4f48-8d36-746aabaa6c21.png)

VS2019, VB.NET
Win10
.NET 4.72
Krypton 6.0.2108.1
Thanks!

**Comment by Smurf-IV** [comment]
Sounds like a Z-Order / Document declaration order problem.
![image](https://user-images.githubusercontent.com/2418812/134465883-5a004e93-474c-47d7-a715-dab23686fafe.png)

Have you see the order of the midi's in the "Midi Ribbon Demo" ?

**Comment by pgaraneta** [comment]
Hi, even if it has only 1 childform, behaves the same.

https://user-images.githubusercontent.com/85190700/134472841-d2f242c6-5e76-4bd2-8296-dd26d859cc62.mp4

Thanks!

**Comment by Smurf-IV** [comment]
![MDIRibbon](https://user-images.githubusercontent.com/2418812/134474355-085b15c0-0458-4506-aafc-723c8aa079a9.gif)

Do not see that in the demo code:

**Comment by pgaraneta** [comment]
Thanks! Guess I have to figure out where this is set. 

This occurred after I changed all controls from ComponentFactory to Krypton.Toolkit in the deisgner.

Thanks a lot for your time.

**Comment by pgaraneta** [comment]
> ![MDIRibbon](https://user-images.githubusercontent.com/2418812/134474355-085b15c0-0458-4506-aafc-723c8aa079a9.gif)
> 
> Do not see that in the demo code:

Have you tried maximizing the main or parent form and check?

**Comment by pgaraneta** [comment]
Hi, I checked it again, yes indeed it does not fully maximize when parent is maximized.

https://user-images.githubusercontent.com/85190700/134479444-94a27d47-cabd-434f-bfc0-883fad42f580.mp4

**Comment by DarthVader85PA** [comment]
Hello @Smurf-IV 

I created a Demo-Project with TFM .NET-Framework 4.8 in VisualStudio 2017 Pro. I have the same issue.
The MDI Child will correct maximized, when I hide the Ribbon-Menu and show it again?
Or I maximize the MDI-Parent-Form...

Greetings from Germany,
Danny

**Comment by Smurf-IV** [comment]
Arr.. Missed the point about the "Parent App" being **maximised**..
Gotcha !
Yupe demo app does that as well.

**Comment by Smurf-IV** [comment]
Another thing..
Whilst maximised parent, and then maximised MDI cause the problem shown;
Performing Restore down, and then maximise of parent shows what is expected !

**Comment by pgaraneta** [comment]
Further to that, if you notice, there are instances that when both child and parent forms are maximized, there's a gap at the bottom between the bottom borders of parent and child forms.

**Comment by Smurf-IV** [comment]
The "Maximising experience" has become broken in 6.22.1.4 !

**Comment by Smurf-IV** [comment]
@Wagnerp the "_The maximised panel doe not "Fill" the area of the parent app_" part, is caused by #483 
Looking into it now

**Comment by Smurf-IV** [comment]
Sorted the change for #483.
