### ISSUE TITLE
[Bug]: RibbonGroupNumericUpDown does not have tooltips

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#382]
![image](https://user-images.githubusercontent.com/2418812/134525902-3d1d1ff2-2f3a-4159-80d1-0aff6982bd0c.png)

The GroupColourButton does :

![image](https://user-images.githubusercontent.com/2418812/134525992-257cbf72-ad08-4c1b-a1ca-e8737eba1b93.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Think I've fixed it, please check the latest PR

**Comment by Smurf-IV** [comment]
@Wagnerp 
Reopening.
Values can be set, but tooltip does not show

**Comment by Smurf-IV** [comment]
Test that the normal KUpDowner has tips:
![image](https://user-images.githubusercontent.com/2418812/144750391-94eee730-7762-4bce-a04a-f6d22b78da47.png)

![image](https://user-images.githubusercontent.com/2418812/144750410-a4d680f5-7ee8-47ff-8bb5-ada8f741b24d.png)

**Comment by Smurf-IV** [comment]
Found #511 as part of the investigation for this

**Comment by Smurf-IV** [comment]
@Wagnerp The fix for this will introduce a breaking change for Ribbon usages with tooltips
How are these breaking changes going to be published ?

**Comment by Wagnerp** [comment]
> @Wagnerp The fix for this will introduce a breaking change for Ribbon usages with tooltips How are these breaking changes going to be published ?

@Smurf-IV That's fine, it could become part of a 'v7' release with .NET 7.

**Comment by Smurf-IV** [comment]
No, I Need this fix before the end of the year !

**Comment by Smurf-IV** [comment]
As V6 is not out of canary yet, it could still be in that !

**Comment by Wagnerp** [comment]
Ok, that's fine, but it does need to be clearly documented.

**Comment by Wagnerp** [comment]
@Smurf-IV Once the fix for this issue is in alpha, I may publish one last canary build for 2201, before merging `alpha-build2202` & `alpha` together. Hope this is ok?

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/144834153-deba79b7-77e5-4930-973e-cb80a2fbb7fa.png)

![image](https://user-images.githubusercontent.com/2418812/144834273-6a11516a-f7cd-4f9e-98a0-6fb80b0c81ae.png)

![image](https://user-images.githubusercontent.com/2418812/144834539-a545dbd3-d520-43a0-b0d3-04c3a7bdff27.png)

![image](https://user-images.githubusercontent.com/2418812/144834645-4b1870cf-a7b7-4c28-a2ac-e55c998a40f2.png)
