### ISSUE TITLE
[Feature Request]: FontDialog only has 16 colours, Bring back the ColourChooser button

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#384]
As per MS.. The "Older" font dialog used to have a colour chooser button that allowed more than the default 16 colours to be chosen:
![image](https://user-images.githubusercontent.com/2418812/134529117-66eccc01-a5d4-4f08-86f5-0a1798331666.png)
https://docs.microsoft.com/en-us/windows/win32/dlgbox/font-dialog-box?redirectedfrom=MSDN

See here for more info:
https://www.vbforums.com/showthread.php?794515-ChooseFont-dialog-more-colors

And how about bringing back the font description along the bottom ?
![image](https://user-images.githubusercontent.com/2418812/134529903-d7e3ab63-d6ed-4be0-b7eb-9339052ef995.png)

**Comment by Wagnerp** [comment]
I'd say yes

**Comment by Smurf-IV** [comment]
![CustomColours](https://user-images.githubusercontent.com/2418812/134950071-f15d594c-f14b-446e-94bb-afce3ccb3cd9.gif)

**Comment by Wagnerp** [comment]
Looks good!

**Comment by Smurf-IV** [comment]
Just got to sort out the custom colour actual selection and application, and it might be good to go ;-)
