### ISSUE TITLE
[Feature Request]: KryptonColorButton Modify Recent Colors

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#385]
Currently there is no way to modify the recent colors of a KryptonColorButton. Recommend adding the ability to modify recent colors at runtime and also potentially in the designer.

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

Had a look, I think you need to use `SetCustomColors(Color[][] colors)`

**Comment by Smurf-IV** [comment]
I have modified the example to show how to do this:
``` c#
        private int[] customColors;
        private void ButtonShowFontDialog_Click(object sender, EventArgs e)
        {
            var kfd = new KryptonColorDialog {
                AllowFullOpen = chkAllowFullOpen.Checked,
                ShowHelp = chkShowHelp.Checked,
                AnyColor = chkAnyColor.Checked,
                FullOpen = chkFullOPen.Checked,
                SolidColorOnly = chkSolidColorOnly.Checked,
                CustomColors = customColors
            };
            if (kfd.ShowDialog(this) == DialogResult.OK)
            {
                KryptonMessageBox.Show(this, kfd.Color.ToString(), @"Color chosen is");
                customColors = kfd.CustomColors;
            }
        }
```

**Comment by Smurf-IV** [comment]
oops, My mistake thought it was do with the Common control.

**Comment by Smurf-IV** [comment]
From inside the `KryptonColorButton` code, there is nothing that is passing the colors onto the KCD (As I showed above)
``` c#
private void OnClickMoreColors(object sender, EventArgs e)
        {
            // Give user a chance to cancel showing the Krypton more colors dialog
            CancelEventArgs cea = new();
            OnMoreColors(cea);

            // If not instructed to cancel then...
            if (!cea.Cancel)
            {
                // Use a Krypton color dialog for the selection of custom colors
                KryptonColorDialog cd = new()
                {
                    Color = SelectedColor,
                    FullOpen = _allowFullOpen
                };

                // Only if user selected a value do we want to use it
                if (cd.ShowDialog() == DialogResult.OK)
                {
                    SelectedColor = cd.Color;
                }
            }
        }
```

**Comment by Wagnerp** [comment]
Could the KCD have an optional feature to add colours to the `KryptonColorButton` recent list?

**Comment by Smurf-IV** [comment]
> `SetCustomColors`

Does this set the following:
![image](https://user-images.githubusercontent.com/2418812/134559485-f8eacace-9350-4cfd-9838-65c6cf155f82.png)

**Comment by Smurf-IV** [comment]
> 
> 
> Could the KCD have an optional feature to add colours to the `KryptonColorButton` recent list?

I think the KCD should take the colours from the recent colours list.

**Comment by sdreb3421** [comment]
Current behavior:

- It's not possible to add colors programmatically to the recent colors list (recommend implementing).
- Recent colors are not shown in the KCD custom color list (recommend implementing).
- The selected color in the KCD is added to the recent colors list (good).
- Colors selected in the Theme/Standard list are not added to recent colors (recommend implementing).

**Comment by jgreywolf** [comment]
Similar to #776

**Comment by Smurf-IV** [comment]
@sdreb3421 I know this is "old" but I'm a little confused (See below):

> Current behavior:
>     * It's not possible to add colors programmatically to the recent colors list (recommend implementing).

Ok, this is what **this** FR is about

>     * Recent colors are not shown in the KCD custom color list (recommend implementing).

Do you mean __KCD__ialog, or just miss-typed and you mean __KCB__utton?

>     * Colors selected in the Theme/Standard list are not added to recent colors (recommend implementing).

Do you mean __KCB__utton?

**Comment by Smurf-IV** [comment]
This is done:
![image](https://user-images.githubusercontent.com/2418812/205482811-b74c6731-4e63-48ad-910b-7f23754eb700.png)

**Comment by Wagnerp** [comment]
@sdreb3421 

Please re-test using build >= .338

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

Is this working now?

**Comment by sdreb3421** [comment]
Yes thank you
