### ISSUE TITLE
[Bug]: KryptonMessageBox cuts off text and background when displayed

### ISSUE THREAD

**Issue by Ash-IPRANOps** [Krypton-Suite/Standard-Toolkit#386]
When running  `KryptonMessageBox.Show("This is a test message") `
It is cutting off the text and the background as seen on screenshot below.

![image](https://user-images.githubusercontent.com/43791859/134558739-f062921f-2652-4efa-bf9b-318d363d54cd.png)

I am using .NET framework 4.6.1 and Krypton Canary v6.0.2108.1
It used to work fine when I had the original Krypton v4.6.0.0. the problem appeared after I replaced Krypton v4.6.0.0 by v6.0.2108.1

Any help how to fix that?

**Comment by Smurf-IV** [comment]
Thanks for reporting
Duplicate.
It has been fixed in the nightlies.

**Comment by Ash-IPRANOps** [comment]
@Smurf-IV Thank you for the wonderful updates you guys doing, it is truly very much appreciated. 

I am not sure what is "nightlies", is that a new release after Canary v6.0.2108.1? when will it be available?

**Comment by Ash-IPRANOps** [comment]
@Smurf-IV I downloaded the project to try to convert it to dll so I can use it with that fix, but unfortunately I only have .NET framework 4.8.0 and below, I can't install a newer one to be able to convert that projects, is it possible to have the latest dlls available soon? I use .NETframework v4.6.1 as mentioned on my original thread. if that is a problem, don't worry about it, I will wait until you have new release. again thank you for your help.

**Comment by Smurf-IV** [comment]
Latest "supported" starts @ TFM 4.6.2, See if you can upgrade your project to that.
Just search for `Krypton Nightly` and `prerelease` in nuget to get them.
![image](https://user-images.githubusercontent.com/2418812/134627041-64c6c236-7aa0-4a86-8afd-118ebde74b22.png)

**Comment by Ash-IPRANOps** [comment]
@Smurf-IV You are awesome, Thank you so much :) have a great day.
