### ISSUE TITLE
[Feature Request]: KryptonColorDialog Font Issue

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#392]
Linked to feature request #265. 

I just upgraded my production code to the latest Nightly and noticed an issue with the KryptonColorButton color dialog updated by #265. I'm having a font size issue I'm assuming because my palette uses a larger default form font (see image). I'm also seeing the Form Text cutoff, probably because I've adjusted the header content padding in the palette to fit nicely with my form icon.

Is there a way to specify the Styles/Fonts of the color dialog, or not have it use Krypton styling? And add a default icon to the color dialog?

Pallete Used: https://www.dropbox.com/s/3jgmj617epdvx6z/Palette.xml?dl=0

![image](https://user-images.githubusercontent.com/1911567/134782527-aa0612ab-2f62-4acb-b32d-ce0bd200ad14.png)

**Comment by Smurf-IV** [comment]
> Is there a way to specify the Styles/Fonts of the color dialog, 

Sounds reasonable, and this issue will cover that work.
<br />
<br />
> or not have it use Krypton styling? 

Isn't that just the normal OS "Font Dialog" then ?
<br />
<br />
> And add a default icon to the color dialog?

Good - One should be in a separate request, so that it can be applied to them all.
<br />
<br />

> Pallete Used: https://www.dropbox.com/s/3jgmj617epdvx6z/Palette.xml?dl=0

Please zip and attach, as not everyone has dropbox.

**Comment by sdreb3421** [comment]
Here is the entire palette. The only relevant palette property that is affecting the font is Common.StateCommon.Content.ShortText = Segoe UI, 12.5f.

[Palette.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7233981/Palette.zip)

Forget about not using Krypton Styling if its not relevant, I was just throwing out possible easy solutions. 

Thanks

**Comment by Smurf-IV** [comment]
> Forget about not using Krypton Styling if its not relevant, I was just throwing out possible easy solutions.

Well, I was thinking that perhaps you still wanted the theme background, and wrapped Form borders, but all internal controls were left as OS defaults.
Not that it would be be pretty as Default black text, on Dark theme background would be - well - dark !
But it could be something halfway like Do everything but change the font. (BTW this would also not be pretty, as some controls refused to have "Just" the text colour changed!!)

**Comment by Wagnerp** [comment]
> > Forget about not using Krypton Styling if its not relevant, I was just throwing out possible easy solutions.
> 
> Well, I was thinking that perhaps you still wanted the theme background, and wrapped Form borders, but all internal controls were left as OS defaults.
> Not that it would be be pretty as Default black text, on Dark theme background would be - well - dark !
> But it could be something halfway like Do everything but change the font. (BTW this would also not be pretty, as some controls refused to have "Just" the text colour changed!!)

The text colours have been fixed as per #371, but not on O2k7/10 themes

**Comment by Smurf-IV** [comment]
> The text colours have been fixed as per #371, but not on O2k7/10 themes

I was on about the Common Dialog controls - they do not accept colour, due to changes in the way they are displayed.

**Comment by sdreb3421** [comment]
I think it's fine if the dialog doesn't use krypton styling. Never even thought about it before. Or if it keeps krypton styling but ignores the global palette. Whatever is easiest for you guys, just want to be able to read it.

**Comment by Smurf-IV** [comment]
@sdreb3421 Q: Why are you making the fonts so big ? If this is for a high res screen, then the user should have already set font scaling to allow normal OS operations to be visible. Same applies to Vision imparement. User will have set a global Display Setting.

**Comment by sdreb3421** [comment]
Idk, thought it looked nice. This is for an industrial application so it's all about ergonomics.

**Comment by Smurf-IV** [comment]
So the Font size at the OS level can be set @ 150% (Or higher via "Advanced setting" <= 500%)

You can still keep all the rounded buttons etc. just that all fonts (And everything else) would be scaled correctly then.

**Comment by sdreb3421** [comment]
So you're suggesting making the entire application font size smaller? This is a very large application with tons of child windows and controls. Doing that would likely require layout changes across the entire UI.

**Comment by sdreb3421** [comment]
Would it be easy to have a property to set the palette for the dialog? That way I could just set it to not use the global palette, or apply a custom palette. Or allow providing my own instance of the dialog to the color button?

**Comment by Smurf-IV** [comment]
It was just a suggestion, as a workaround, as I obviously do not know the "Size" of the development.

As for actually implementing the palette changes for the Kryptonised Common Dialogs - that's a bit more involved - as this implementation is a wrapper replacement over the OS controls, that uses the Global palette (As you have found) to replace the controls in situ, regardless of their type.

Having palette / font / colour overrides for each type will take time, or something else, (Like a single palette just for them ?"!?);

And as such, I have not estimated the amount of time this is going to take. Hence the suggestion(s).

**Comment by sdreb3421** [comment]
Perhaps there is a way to disable the color button from automatically launching the dialog, and I can respond to an event to instead open my own dialog?

**Comment by Smurf-IV** [comment]
> Perhaps there is a way to disable the color button from automatically launching the dialog, and I can respond to an event to instead open my own dialog?

I agree, the RibbonBar implementation of the colorbutton allows this, and I use it to launch straight into the full colour dialog, rather the midstep, of displaying themed colours, then having to press another area to launch full (Via "More colors")

**Comment by sdreb3421** [comment]
Or can the change that implemented the krypton styling be backed out? I gotta imagine other people are going to run into issues with font sizes and/or palette colors. I noticed that the dialog textboxes are black background with black text with my palette.

**Comment by Smurf-IV** [comment]
> https://github.com/Krypton-Suite/Standard-Toolkit/issues/392#issuecomment-928898683

This is a nightly.. It'll have issues !

**Comment by Wagnerp** [comment]
@sdreb3421 I wouldn't use the nightly on production code, as these will have issues, Have you got a 'pre-release' branch you can test on?

**Comment by sdreb3421** [comment]
Oh it is a prerelease branch. I just wanted to get ahead of the game. Hoping to minimize bug resolution for the next stable release.

**Comment by Wagnerp** [comment]
> Oh it is a prerelease branch. I just wanted to get ahead of the game. Hoping to minimize bug resolution for the next stable release.

Ahh, that's ok. Yes, dark modes have issues, as the original code had hardly no documentation in the palettes. making it harder to figure out what's going on!

**Comment by Wagnerp** [comment]
@sdreb3421 & @Smurf-IV Can I close, as it's causing some confusion?

**Comment by Wagnerp** [comment]
Fixed in build 2201
