### ISSUE TITLE
[Feature Request]: Add ability to add form icon to common dialogs

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#395]
As indicated in #392, it would be good if the Kryptonised Common Dialogs had the ability to have a form icon

e.g.
`ShowIcon`
`Icon =` for override the Krypton default

Any ideas for the icons ?
Will they need to be different so that they show up for Black and  Silver standard themes?

**Comment by Wagnerp** [comment]
There are several generic colour icons in the extended toolkit resources that could be used

**Comment by Wagnerp** [comment]
As for the font dialog: https://icons8.com/iconizer/en/search/Free-for-commercial-use-no-link/0-128/1/font

**Comment by Smurf-IV** [comment]
Darn it.. CommonDialogs are `ToolWindows` and therefore do not have "Icons"

**Comment by Smurf-IV** [comment]
Hah.. take that !
![image](https://user-images.githubusercontent.com/2418812/135710401-b12229b5-c31f-467a-849f-cd4e8f410e8d.png)
