### ISSUE TITLE
[Feature Request]: Change the color button from automatically launching the dialog, and I can respond to an event to instead open my own dialog?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#396]
#392 

https://github.com/Krypton-Suite/Standard-Toolkit/issues/392#issuecomment-928898683

**Comment by Smurf-IV** [comment]
I'll check this in tomorrow:
![ClickOverride](https://user-images.githubusercontent.com/2418812/135903009-f4708123-024f-4759-af7d-ce43677f3dd8.gif)

**Comment by sdreb3421** [comment]
To simplify things on my end I'll likely try to inherit from KryptonColorButton to automatically launch a custom dialog. Will there be a new click method or event to override?

**Comment by Smurf-IV** [comment]
In the above, Just add a click event, and it calls that instead of the default drop / splitter menu thingy. 
It also removes the `Splitter` and `Dropdown` drawing from the button at runtime (Not in the designer - as it does not know about events!)

So if you derive from it (For whatever reason) then yes it will still do it's job correctly.

**Comment by sdreb3421** [comment]
So the presence of a click event listener is what turns off the automatic dialog? That works for me, but others may have a unique reason to handle a click event but still expect the auto dialog. Either way, looking good

**Comment by Smurf-IV** [comment]
> So the presence of a click event listener is what turns off the automatic dialog?

If they have a reason, then they can also call the existing function(s) that performed the drop / menu stuff, before the their existing click code.

So yes. It is a breaking change, but I feel that this has the least impact, but with the most sensible gain.

**Comment by sdreb3421** [comment]
I just noticed that I can't subscribe to the click event from within a derived class. But I can override the OnClick method. Will this also prevent the automatic dialog? I'm trying to avoid adding an event handler for every color button in the application just to launch the same dialog. Thanks

**Comment by Smurf-IV** [comment]
Just a thought, but in the Derived class contructor, 
just do `Click += func;`

**Comment by sdreb3421** [comment]
@Smurf-IV I implemented this change back in October using the Nightly build and everything worked (subscribed to click event in derived constructor). But it no longer works in latest Nightly or stable build (6.2111.312). The original color popup appears and the click event doesn't get called. Would you check and see if it got stripped out somewhere? Thanks

**Comment by Smurf-IV** [comment]
@Wagnerp ??

**Comment by Wagnerp** [comment]
> @Wagnerp ??

@Smurf-IV I remember changing it from the Windows colour dialog to the Krypton one. @sdreb3421 Is this what you mean?

**Comment by sdreb3421** [comment]
@Smurf-IV changed the code so that subscribing to the click event would prevent the standard pop up from showing. This allowed me to open my own dialog.

**Comment by sdreb3421** [comment]
Do you need any additional info? Is this fix going to be resolved in an upcoming release?

**Comment by Wagnerp** [comment]
> Do you need any additional info? Is this fix going to be resolved in an upcoming release?

If you can provide any additional info, that would be great!

**Comment by sdreb3421** [comment]
The code should be reupdated to disable the normal colorbutton pop up if the click event is subscribed to. The original reason for this fix was the new kryptoncolordialog does not properly support larger fonts. This allows us to use our own color dialog. Thank you!

**Comment by Wagnerp** [comment]
Adding a property (bool) to allow the usage of the Windows CD over the Krypton version

**Comment by sdreb3421** [comment]
A property would be great, but could there be an option to have no dialog?

**Comment by Wagnerp** [comment]
> A property would be great, but could there be an option to have no dialog?

@Smurf-IV Is this a possibility?

**Comment by Smurf-IV** [comment]
If the Override worked as before (i.e. detect if the callback had been set) then it is upt o the owner of that callback to perform _whatever_ action they require.
No need for extra properties or fields.

**Comment by Wagnerp** [comment]
> If the Override worked as before (i.e. detect if the callback had been set) then it is upt o the owner of that callback to perform _whatever_ action they require. No need for extra properties or fields.

I don't understand, as the implemented override code is still in there, but @sdreb3421 says it doesn't work, even though it worked before?

**Comment by sdreb3421** [comment]
What's the plan for this one? Are you guys able to verify the issue on your end? I have these color buttons in many places so need a direction to go before a customer release in January. Thanks

**Comment by Wagnerp** [comment]
> What's the plan for this one? Are you guys able to verify the issue on your end? I have these color buttons in many places so need a direction to go before a customer release in January. Thanks

@sdreb3421 Are you able to reuse the code in [this](https://github.com/Krypton-Suite/Standard-Toolkit-Demos/pull/63) demo. Nothing has changed with the feature since PR [#421](https://github.com/Krypton-Suite/Standard-Toolkit/pull/421).

**Comment by sdreb3421** [comment]
What do you mean reuse? How do I download the demo?

**Comment by Wagnerp** [comment]
> What do you mean reuse? How do I download the demo?

i.e. override it `myColorButton.Click += Click;`. Have a look at the color button examples in the latest [demos](https://github.com/Krypton-Suite/Standard-Toolkit-Demos/releases/download/6.2111/Samples.v6.2110.274-beta.Net48.msi).

**Comment by sdreb3421** [comment]
I am currently overriding it in my code, but still get the standard color popup. Are you seeing this as well in the latest stable release?

**Comment by Wagnerp** [comment]
It works in the latest canary/nightly build, not scheduled to enter the stable build 2201 until January.

![Animation](https://user-images.githubusercontent.com/949607/142987472-7c1d3324-36e8-4cad-be13-6e25a75adf18.gif)

**Comment by Wagnerp** [comment]
@sdreb3421 Which version was it working in, so I can compare the files?

**Comment by Wagnerp** [comment]
@sdreb3421 & @Smurf-IV According to WinMerge, the files in **both** PR #421 & the latest nightly are identical. Is there something missing?

**Comment by Wagnerp** [comment]
@Smurf-IV What does `_clickOverriden` do?

**Comment by Wagnerp** [comment]
Something is wrong here:

```cs
 private void OnButtonClick(object sender, MouseEventArgs e)
        {
            var showingContextMenu = false;

            // Do we need to show a drop down menu?
            if (!_clickOverriden
                && (!Splitter || (Splitter && _drawButton.SplitRectangle.Contains(e.Location)))
                )
            {
                showingContextMenu = ShowDropDown();
            }
            else
            {
                // Raise the standard click event
                OnClick(EventArgs.Empty);

                // Raise event to indicate it was a mouse activated click
                OnMouseClick(e);
            }

            // If not showing a context menu then perform cleanup straight away
            if (!showingContextMenu)
            {
                ContextMenuClosed();
            }
        }
```

I don't know what yet?

**Comment by Wagnerp** [comment]
@Smurf-IV Could the trick in PR #475 work here?

**Comment by Wagnerp** [comment]
@sdreb3421 & @Smurf-IV Found the issue, this is **not** currently, in the stable release, as this feature is pegged for build 2201. Therefore, I'm closing this thread. Tested and verified as working on the latest canary/nightly builds.

**Comment by sdreb3421** [comment]
Great, thanks guys
