### ISSUE TITLE
[BUG]: KryptonDataGridViewComboBoxCell does not contain property for Items

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#4]
`KryptonDataGridViewComboBoxCell` does not contain property for `Items`

**Comment by Smurf-IV** [comment]
@Wagnerp 
I think that this can be closed now:
![image](https://user-images.githubusercontent.com/2418812/147675604-5dbd5bed-a2fb-4435-9a74-31d1e3f8d427.png)
