### ISSUE TITLE
[Bug]: Double monitor and KryptonSplitContainer issue

### ISSUE THREAD

**Issue by Ash-IPRANOps** [Krypton-Suite/Standard-Toolkit#400]
When the user move the splitter (Divider) bar in the KryptonSplitContainer there is a gray/shadow bar move to show the user where to move the splitter, this should work just fine if the user is moving the splitter on the main monitor, but if the user have two or more monitors and if the splitter is not on the main monitor, the  gray bar will appear only on the main, which is a different monitor to where the splitter should be. This was not an issue on the old version of Krypton.

**To Reproduce**
1. Create Splitter in an app and have the app on a screen other than the main screen/monitor.
2. Move the splitter to resize its two panels
3. Notice the gray bar appear only on the main screen/monitor.

**Screenshots**
![image](https://user-images.githubusercontent.com/43791859/135124871-97abfae7-0a7a-4927-83ba-ebcb7a0f4ee1.png)

**Comment by sdreb3421** [comment]
See #364

**Comment by Ash-IPRANOps** [comment]
Thank you @sdreb3421, Yes it works, I was trying to avoid Pre-release, but I have no choice :).

**Comment by Smurf-IV** [comment]
@Ash-IPRANOps Can you state what OS and configuraiton you test this with please (in #364 ) so that this can be tracked as "Working in that version" - TIA

**Comment by Ash-IPRANOps** [comment]
@Smurf-IV , it is Windows 10 Enterprise, OS build 19042.1110

**Comment by Wagnerp** [comment]
@Ash-IPRANOps The next Canary version `6.2110.274` will be released on Friday, which will include the separator fix.

**Comment by Ash-IPRANOps** [comment]
@Wagnerp , @Smurf-IV I use this a lot, so if you require a tester on my Windows version, I will be glad to help. Thank you guys for maintaining Krypton, I can't thank you enough, I only add it to my application one year ago (the original one), but only one week ago I found that you guys kept it on and more. I am VB Net guy, so updating the C# for me wasn't easy :)

**Comment by Wagnerp** [comment]
@Ash-IPRANOps We always need testers to find bugs, the newly released nightly packages will always be rough around the edges, as they're based on the `alpha` branch, so I wouldn't recommend using them in production code.

**Comment by Ash-IPRANOps** [comment]
@Wagnerp Thank you for the advise, that is the reason I avoid pre-release, I hold off my app release until next Friday once you have the official one, thank you.

**Comment by Ash-IPRANOps** [comment]
> @Ash-IPRANOps The next Canary version `6.2110.274` will be released on Friday, which will include the separator fix.

Any update of when is the next official release date?

**Comment by Wagnerp** [comment]
> > @Ash-IPRANOps The next Canary version `6.2110.274` will be released on Friday, which will include the separator fix.
> 
> @Wagnerp, Any update of when is the next official release date?

@Ash-IPRANOps New stable & signed are due to be released on **Monday, 1st November 2021**, with .NET 6 support.
