### ISSUE TITLE
[Bug]: Krypton.Toolkit.Nightly" Version="6.2109.272-alpha" has removed code that was in 270

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#403]
![image](https://user-images.githubusercontent.com/2418812/135403599-8fa6adbf-2e35-4522-adfd-9002bac910ad.png)

**Comment by Wagnerp** [comment]
Do you remember the PR numbers, so I can compare them?

**Comment by Wagnerp** [comment]
Fixed, but it'll won't be in todays nightly build... sorry :( (30/09/21)

**Comment by Wagnerp** [comment]
Fixed in build 2111
