### ISSUE TITLE
[Feature Request]: KryptonInputBox to have a default button

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#404]
![image](https://user-images.githubusercontent.com/2418812/135451863-8fef6389-9ce4-4dfb-b9bd-17e79b754ef0.png)

**Comment by Wagnerp** [comment]
That was easy!

**Comment by Wagnerp** [comment]
Fixed in build 2111

**Comment by Smurf-IV** [comment]
@Wagnerp Morning.. Can I have nightly with these fixes in it now please ?

**Comment by Wagnerp** [comment]
@Smurf-IV Yup, was just building the Canary release
