### ISSUE TITLE
[Feature Request]: KryptonInputBox Message Size needs to be controllable by the developer

### ISSUE THREAD

**Issue by Ash-IPRANOps** [Krypton-Suite/Standard-Toolkit#407]
1- Can you please add the ability for the developer to set the size manually for KryptonInputBox and KryptonMessageBox?

This would help in the case of auto-size failure, or if the developer need to set a size for any reason.

**Comment by Smurf-IV** [comment]
See discussion in #402

**Comment by Smurf-IV** [comment]
Please retest if this is necessary now that #402 has been completed ...

**Comment by Smurf-IV** [comment]
Closing as #402 is fixed.
