### ISSUE TITLE
[Feature Request]: Checkbox text wrap

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#411]
**Is your feature request related to a problem? Please describe.**
Is it possible to make the `KryptonCheckBox` text wrap, similar to a `KryptonWrapLabel`?

**Comment by Smurf-IV** [comment]
The vertical location of the checkbox becomes a problem if this is done, 
and RTL !

**Comment by Wagnerp** [comment]
> The vertical location of the checkbox becomes a problem if this is done, and RTL !

Got another solution for the extended mbox checkbox, use a `KryptonTableLayoutPanel`
