### ISSUE TITLE
[Bug]: Artefacts when displaying the full colour dialog

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#416]
Whilst experimenting, I came across this...

![image](https://user-images.githubusercontent.com/949607/135819019-bdac300a-4698-4e2b-84aa-8a8054324e15.png)

Seems like a corner to a button, but I don't know which...

**Comment by Smurf-IV** [comment]
It is a "Hidden button" (Sometimes!) that is defined in the colour dialog OS template. 
Was not sure what to do with it.

**Comment by Wagnerp** [comment]
> It is a "Hidden button" (Sometimes!) that is defined in the colour dialog OS template. Was not sure what to do with it.

If this is a OS bug, then it needs to be reported in the feedback hub. I would just define it as a known unfixable bug in the changelog (well until MS decides to fix it)

**Comment by Smurf-IV** [comment]
I might be able "Ignore / disable / forcibly move it somewhere else" but left it in most cases in case it "Does" something.

**Comment by Wagnerp** [comment]
I've created a bug report https://aka.ms/AAdytw4

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/136687173-b211edb3-9544-41f0-a09d-920282ecf73b.png)

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/136687215-6b952913-0657-43d4-9db4-9129dd970e91.png)
