### ISSUE TITLE
[Bug]: KryptonDataGridButtons look disabled in the KDatagrid view

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#430]
![image](https://user-images.githubusercontent.com/2418812/136182863-f4656531-91fc-4185-9b82-c2c16eea3528.png)

They work (As in the code to detect the click fires, but it is probably not the button click), but do not show hover, or look active

**Comment by Wagnerp** [comment]
Seems to be using the `Disabled` colour, are you able to track it down?

**Comment by Smurf-IV** [comment]
Hmm.. Doing this from first principles (ie. trying to replicate the issue with new code) does not give the above picture.
Must be something wrong with the source code. Will park this until I can gain access to a repro.
