### ISSUE TITLE
[Bug]: Wrong Ribbon Form Height when Windows is using scaling; e.g. 200% dpi

### ISSUE THREAD

**Issue by rulai-yinqiang** [Krypton-Suite/Standard-Toolkit#441]
windows 11, 200% dpi, .NETFramework,Version=v4.7.2

I enabled PerMonitorV2 in  app.config.

I think the form header height is wrong.

See the Red Close button in screen shots.

**Screenshots**
![image](https://user-images.githubusercontent.com/33405365/137136353-83679f51-24d2-446c-af83-ab8ce888661e.png)

normal form header:
![image](https://user-images.githubusercontent.com/33405365/137137306-8ca48a5e-f6e1-439d-8b63-796391f59ecf.png)

**Comment by Smurf-IV** [comment]
What theme was that? 
Because Each theme has a set width of button in the form.

But this is also to with the height and "Will / may " be sorted by having a Office 2021 (Windows 11) theme set

**Comment by Wagnerp** [comment]
It's because the titlebar is taller on Windows 11 than older versions. @Smurf-IV & I have discussed this, might need 'Windows 11 only' versions.

**Comment by rulai-yinqiang** [comment]
It's not windows 11 only, I tested on a Windows 10, set it as 200% DPI:

BTW: The QAT Button images is also very small.

![image](https://user-images.githubusercontent.com/33405365/137283706-bdf6810e-3ee2-4c8d-8371-da8fea2977e2.png)

**Comment by Smurf-IV** [comment]
Under Win 10, using the example shown (After the fix for #487 ):
![image](https://user-images.githubusercontent.com/2418812/147817412-31eebb6d-2807-4f42-a655-3ded87958c2c.png)
![image](https://user-images.githubusercontent.com/2418812/147817485-c6f5e3a6-f575-4a96-820b-119f85fb5e51.png)

**Comment by Smurf-IV** [comment]
Issues:
- Form border draw area, is to small and the Ribbon area is encroaching upon it
which leads to
- Height left for Form area is too small
- Overlapped title text
- QAT buttons are too small,
- Ribbon actions are in the "Form title" area

**Comment by Smurf-IV** [comment]
All but "6)" done
![image](https://user-images.githubusercontent.com/2418812/147819577-05a158ac-7b07-4a53-b98d-ed9b380260c8.png)

**Comment by Smurf-IV** [comment]
Just discovered 
8. Actual QAT (File) round image thingy is also wrong for 2007 based themes (Which include the sparkle's)
![image](https://user-images.githubusercontent.com/2418812/147820319-a1ef97c7-d9e0-44f1-baa1-26f259649896.png)

**Comment by Smurf-IV** [comment]
This has led me down a rabbit hole of "ALL" the other things that are not scaled (e.g. Up down button images)
Will try to resolve them all..

**Comment by Smurf-IV** [comment]
Darn it.. If I try to solve it for `Palette` images then it does not solve it for User assigned images.
Need a common way of doing this !

**Comment by Smurf-IV** [comment]
And now I know abut this, and it causes all sorts of new problems:
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element#disabledpichangedmessagehandling
![image](https://user-images.githubusercontent.com/2418812/147873411-eaf37976-c3cb-431c-b232-befefd08090e.png)

**Comment by Smurf-IV** [comment]
This has turned into a complex problem:
- Global Palette
  - Changed via Code selection
  - Size change due to OS change (Monitor pref's or OS theme)
  - Size change due to "per monitor dpi"'s
- Per Form palette assignments
- Custom palette's
- User assigned images 
  - Global assignment
  - Per control
- Object lifetimes
- Try to keep the existing palette code working for custom loading

As I see it I have 2 options
1) Fix just this bug with some "code" that can be used / replaced later
2) Do the overhaul and not get it finished for quite some time

@Wagnerp votes please ?

**Comment by sneusse** [comment]
Thanks for tagging me but I'm not really involved here, I guess :) Still voting for 1.) because you can - like you said - replace it later with 2.) if needed.

**Comment by Wagnerp** [comment]
@Smurf-IV I'd go for #1, then submit a new FR for #2 with the 'backlog' tag attached to it

**Comment by Smurf-IV** [comment]
6) done:
![image](https://user-images.githubusercontent.com/2418812/147926912-5b038b75-160f-4608-b564-46bfb437e36d.png)
Just need to fix the rounding and the actual QAT File round thingy

**Comment by Smurf-IV** [comment]
oops:
![image](https://user-images.githubusercontent.com/2418812/147929170-69ee1dfc-43b6-458f-abd0-b4b5191c7413.png)

**Comment by Smurf-IV** [comment]
All Done.. And managed to get the menu to be positioned correctly as well:
![image](https://user-images.githubusercontent.com/2418812/147948240-080a2da4-9a8a-4d4d-98c3-810ffcde1477.png)

PR coming soon.
