### ISSUE TITLE
Cue Text in TextBox Clipping

### ISSUE THREAD

**Issue by waliarubal** [Krypton-Suite/Standard-Toolkit#446]
Cue text in text box is clipping. I am developing app on Windows 10 with .NET 5 project. See highlighted text box image below.

![image](https://user-images.githubusercontent.com/20422731/137998491-64185bb8-4be5-4f87-b2b8-220a82b6229b.png)

**Comment by Smurf-IV** [comment]
This has been fixed in later versions (Or should have been ;-)
Can you state what version you are using, and whether it still exists in the "Nightly" version please ?

**Comment by Wagnerp** [comment]
Closing, as fixes have been released since.
