### ISSUE TITLE
[Bug]: Can't edit the ribbon bar from the designer if the project is .net core5

### ISSUE THREAD

**Issue by Mode79** [Krypton-Suite/Standard-Toolkit#451]
**Describe the bug**
I have a project that is using the .net 5.0 and when i add a ribbon to the form, the designer isn't allowing me to edit the ribbon. it isn't handling any clicks

**To Reproduce**
- create simple project using .net core5
- change the Form1 : Form to Form1 : KryptonForm in the main form
- drag the ribbon bar from the toolkit
- double click on the ribbon bar to add more tabs or edit groups in the default tabs isn't allowed in the designer i.e. any clicks to the ribbon bar is doing nothing

**Expected behavior**
the designer shall respond to the mouse clicks on the ribbon bar

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 19042.1288

**Comment by Smurf-IV** [comment]
This does not happen in VS2022 (Apart from it not displaying the Krypton toolkit !)
But if you start with the demo Ribbon projects
- Change "Ribbon Controls" to be _JUST .net5....
- ![image](https://user-images.githubusercontent.com/2418812/147679764-9d83ebc3-e908-4acb-9564-69817a340178.png)
- Close Visual studio(To flush any designers loaded)
- Open the solution and then open the Ribbon Controls Form in designer
- Edit of the ribbon can occur:
![Net5RibbonDesigner](https://user-images.githubusercontent.com/2418812/147680102-3a95c27d-3b90-4384-b382-760d9ca544e1.gif)
