### ISSUE TITLE
[Bug]: KryptonDockingManager - KryptonPage - MinimumSize not working

### ISSUE THREAD

**Issue by raygraham442** [Krypton-Suite/Standard-Toolkit#452]
I've created a KryptonPage that has an attached UserControl.  I want to configure the page so that it can't be resized smaller than 682 x 533.  I'm setting the MinimumSize to 682 x 533.  Though as I move and pages around in the WorkSpace I find that the KryptonPage set the MinimumSize on can be resized smaller than the MinumumSize of 682 x 533.  Is there something more that I need to configure for the MinimumSize to work?

Thanks in advance,

**Comment by Smurf-IV** [comment]
This might have been fixed with the code changes in #459.
Please retest with a nightly from today 👍 (i.e. greater than 316)

**Comment by Smurf-IV** [comment]
> This might have been fixed with the code changes in #459. @raygraham442 Please retest with a nightly from today 👍 (i.e. greater than 316)

No it has not been fixed.

It appears that there are several issues here:
- `KryptonDockspace` doe snot have it's `MinimumSize` set to the pages it's contains minimum size.
-  `KryptonPage` doe snot respect the `MinimumSize` of any controls it contains when it is not docked (If at all !)
- Sizing in docking does not appear to work as expected when the docking is moved around on different edges.

**Comment by Smurf-IV** [comment]
Arggh.. I don't like this Docking code ....

**Comment by Smurf-IV** [comment]
Massive cleanup has been triggered to try and "see the wood for the trees"
https://github.com/Krypton-Suite/Standard-Toolkit/pull/542

**Comment by Smurf-IV** [comment]
The following video shows:
- Designer with Min Size set to the area shown
- Multi Control Demo App initial start showing the overlapping controls obeying the minimum Size
- Floating window showing minimum size to show
- Attempt to make the Docked control smaller
- Maximise app, then resize still works

![DEsignerControlHasMinSizeSet](https://user-images.githubusercontent.com/2418812/147356731-ed8fc012-9832-4e1d-bb63-0f27658d9c88.gif)
