### ISSUE TITLE
[Bug] KryptonDataGridView's cell cannot display multiple lines when `DefaultCellStyle.WrapMode` set `true`

### ISSUE THREAD

**Issue by ChenAGit** [Krypton-Suite/Standard-Toolkit#453]
How can I make KryptonDataGridView‘s cells display multiple rows?

**Comment by Smurf-IV** [comment]
So this turned out to be 2 problems
1) multiline not displayed for cell when wrap set in style,
2) Multiline editor not have scroll when ever multiline text present
![image](https://user-images.githubusercontent.com/2418812/144745936-009cb8d2-e0ff-48cd-ad76-11dbc6a493e3.png)

**Comment by Smurf-IV** [comment]
for 1 & 2:
![image](https://user-images.githubusercontent.com/2418812/144745997-ca66d5a7-697e-4c02-8fa2-e9d38298f809.png)
