### ISSUE TITLE
[Bug]: KryptonForm.MaximumSize doesn't have any effect

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Standard-Toolkit#459]
**Describe the bug**
Setting the `KryptonForm.MaximumSize` property does not restrict resizing the form beyond the selected size.

**To Reproduce**
1. Set the `MaximumSize` property of a form to any size other than `Size.Empty`.
2. Run the program and try to resize the form beyond the selected size.
3. It will resize as far as the screen allows.

**Expected behavior**
The form shouldn't resize beyond the `MaximumSize` property's value.

**Desktop:**
 - OS: Windows 10 64-bit
 - Version 21H1

**Additional context**
I've narrowed down the issue to the `OnWM_GETMINMAXINFO` method in `VisualForm`. That method gets called in `WndProc` and although I'm not entirely sure about the purpose of it or if it's really needed, there's a [comment](https://github.com/Krypton-Suite/Standard-Toolkit/blob/1c2e44a7f607ff27043af5a50921a628f13ffba7/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/VisualForm.cs#L1035) there about allowing the application to process its own min/max requirements by setting the `processed` bool variable to false. However, at the end of `WndProc` when it's time to call `base.WndProc`, there's a [check](https://github.com/Krypton-Suite/Standard-Toolkit/blob/1c2e44a7f607ff27043af5a50921a628f13ffba7/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/VisualForm.cs#L1138) for `m.Msg != PI.WM_.GETMINMAXINFO` (which contradicts with the comment referred to above).

**Comment by Wagnerp** [comment]
Linked to #415?

**Comment by Wagnerp** [comment]
Why did Phil link to this: https://web.archive.org/web/20121027192324/http://gallery.expression.microsoft.com:80/ZuneWindowBehavior in September 2011?

**Comment by Smurf-IV** [comment]
> 
> 
> Why did Phil link to this: https://web.archive.org/web/20121027192324/http://gallery.expression.microsoft.com:80/ZuneWindowBehavior in September 2011?

Maybe: So that the following could be implemented
`case WM_GETMINMAXINFO`

Which is in the same area as some of the fix for #415

**Comment by Smurf-IV** [comment]
> So, is this really classified as a bug, as it seems to be a deliberate decision?

Yes, The above code (I seem to recall) handles the Min Size, and it is either ignoring or overriding the Max size..
So yes.. It's a bug

**Comment by Smurf-IV** [comment]
I am unable to repro this:
Win 10 x64
Latest Alpha
Using the DateTimePicker example set to 800*700:

![MaxSizeIsRespected](https://user-images.githubusercontent.com/2418812/141675815-4ee6185b-abb4-433a-97c6-0aaa30750881.gif)

Note:
`OnWM_GETMINMAXINFO` was never called. (Breakpoint was never hit!)

@Ahmed-Abdelhameed Can you attach a zipped up project that simulates what you are seeing please ?

**Comment by Smurf-IV** [comment]
@Ahmed-Abdelhameed No worries about the example, I have just hit the problem.. It's when a Child form is opened (i.e. not mainform) when the Max size is not respected. :-(
I now have a repro.. So can try to fix !

**Comment by Ahmed-Abdelhameed** [comment]
@Smurf-IV  Thank you for your reply!
It actually happens with any form, not just a child form. Here's a demo:

![Demo](https://user-images.githubusercontent.com/18140178/141677102-e485a20b-1858-4287-b673-9efcfc45e5cc.gif)

And here's the project:

[KryptonForm_Test_MaxSize.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7533545/KryptonForm_Test_MaxSize.zip)
