### ISSUE TITLE
[Bug]:  Can't select/drag any krypton controls on a form

### ISSUE THREAD

**Issue by ticool** [Krypton-Suite/Standard-Toolkit#46]
I can't select/drag  any krypton controls on a form in a brand new projet. The Windowns form controls works fine !

**Expected behavior**
I could move controls on the form to design it.

OS:  Windows 10
Project : .Net 5
Krypton.Toolkit : 5.550.2101

thx for help !

**Comment by Wagnerp** [comment]
Hi @ticool 

This is a known bug of .NET 5. You can either follow [this guide](https://github.com/Krypton-Suite/Standard-Toolkit/blob/canary/Documents/Help/Designer%20Fix.md) or use the latest preview of Visual Studio to fix it.

**Comment by ticool** [comment]
Yea seems to work with the complete version but not with the krypton Light one that doesn't support 4.8  :(

**Comment by Wagnerp** [comment]
It's because the `lite` versions only support 4.5, .NET Core 3.5 & .NET 5. There isn't any planned support for older frameworks for the `lite` versions.
