### ISSUE TITLE
[Bug]: The Type Krypton.Toolkit.SeparatorStyle is in Target-Framework not available

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#465]
**Describe the bug**
After I updated Krypton from 5.550 to 6.2111.312.0 I get in Forms with Ribbon on saving the following error message:
Error to generate the code for SeparatorStyle-Property. Error: The Type "Krypton.Toolkit.SeparatorStyle" is not in Target-Framework available. (Free-Translated from a german Visual-Studio-Version)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/32876506/140959899-ddff8658-edf6-4230-9308-4522475ee7ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 
 - Version 20H2 - 19042.1288
 - TFM: .NET-Framework 4.7.2
 - VisualStudio Professional 2017 - 15.9.40

**Comment by Wagnerp** [comment]
@Smurf-IV Would that be caused by that weird separator bug a few months ago?

**Comment by DarthVader85PA** [comment]
Hey @Smurf-IV 
I don't know. But now, after I have closed completly the form in designer and the code window and re-opened it, the error was gone?!!!

**Comment by Smurf-IV** [comment]
> @Smurf-IV Would that be caused by that weird separator bug a few months ago?

No.

> after I have closed completly the form in designer and the code window and re-opened it, the error was gone?

It is because in the designer, it was probably referencing a hidden type, or one that has been moved. and just opening and closing reformatted the designer values. 
If you have a diff, it will show what has changed. And then "We" can mark it as a Breaking change.

**Comment by Smurf-IV** [comment]
@DarthVada85PA If you have a diff, it will show what has changed. And then "We" can mark it as a Breaking change.

**Comment by DarthVader85PA** [comment]
Hey @Smurf-IV 

Sorry. Unfortunately I don't have a diff in which you can see what has been changed here. 
I think, we can close that Bug. The Designer-View of the form was open while I updated Krypton over NuGet-Package-Manager. The error has not occurred since then! 

Thanks a lot.
Regards from Germany.
