### ISSUE TITLE
[Other Issues]: Ribbon-Style Office 365 - Blue Light Mode

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#466]
![grafik](https://user-images.githubusercontent.com/32876506/140961214-6ee1e18a-97c4-43b9-b8e2-e4a81f4f006b.png)

Is that a correct style after update?
Looks that something is missing? :)

Greetings Danny

**Comment by Wagnerp** [comment]
Hmm... is this linked to #371?

**Comment by Smurf-IV** [comment]
Should be similar to this style:
![image](https://user-images.githubusercontent.com/2418812/141077123-9be74925-3bbb-42df-b826-c892ba36dd8c.png)

i.e. borders, coloured same as selected tab, etc.

`Office 2013` is also in this "Broken" state

**Comment by Wagnerp** [comment]
The outlines are 'lost'. Need to reinstate the lines.

**Comment by DarthVader85PA** [comment]
> 
> 
> The outlines are 'lost'. Need to reinstate the lines.

How can I do this?

**Comment by Wagnerp** [comment]
> > The outlines are 'lost'. Need to reinstate the lines.
> 
> How can I do this?

It needs changing within the 'palette base' code itself. Not sure where it resides yet.

**Comment by DarthVader85PA** [comment]
Okay. Thanks. I set the `GlobalPaletteMode`-Property in `KryptonManager`-Component in my main form to `Office 2010 - Blue (Light Mode)`. It works for me, but Office 365 Blue has a better style! :)

**Comment by Wagnerp** [comment]
Not promising a fix yet, but I think I've solved it

**Comment by Wagnerp** [comment]
Does anyone own a copy of Office 2013, if so, could they upload screenshots of the themes please, as I think there is a huge colour identity issue with the O2k13 white theme?

**Comment by Smurf-IV** [comment]
I thought I had already done that in a previous issue ?

**Comment by Smurf-IV** [comment]
Seems like I did not attach the images (Or they have gone :-()
https://github.com/Krypton-Suite/Standard-Toolkit/issues/219#issuecomment-894773914

**Comment by Smurf-IV** [comment]
Installing into Win 7 VM now.....

**Comment by Smurf-IV** [comment]
White (Default)
![image](https://user-images.githubusercontent.com/2418812/141453265-9a5a75fb-a634-4381-b9c2-cad1812738f7.png)

Light Gray:
![image](https://user-images.githubusercontent.com/2418812/141453519-b5f6ba50-dc86-4e08-86a3-35e4f0703dfd.png)


Dark Gray:
![image](https://user-images.githubusercontent.com/2418812/141453607-87d677ed-3d0b-4b68-9b32-8fca4f1e5d4c.png)

**Comment by Wagnerp** [comment]
I'm still working on it, may take a bit longer ;)

**Comment by DarthVader85PA** [comment]
Hey @Wagnerp,

you need more time I think or is it solved?

This screenshot shows Office 365 - Blue (Light Mode) in the latest Alpha-Version!
![grafik](https://user-images.githubusercontent.com/32876506/161719981-5cacec61-1a3b-482f-a166-a1cc2f7bb792.png)

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

I'm starting on the light modes now, starting with the Office 2007 themes

**Comment by PWagner1** [comment]
Hi @Smurf-IV & @giduac 

Do we know how to reinstate the borders?

**Comment by Smurf-IV** [comment]
> Hi @Smurf-IV & @giduac
> 
> Do we know how to reinstate the borders?

Not sure I understand the question in relation to the "Current V85 / V90 themes" ? 

Going back to the last 2022 comment https://github.com/Krypton-Suite/Standard-Toolkit/issues/466#issuecomment-1088458850
Then it appears there _was_ a problem, but I don remember seeing anything like that recently.
Perhaps this can be closed now ?

**Comment by PWagner1** [comment]
Closing as this appears to be fixed (I don't know when). Please reopen if necessary.
