### ISSUE TITLE
[Feature Request]: Enable/disable checkboxes on KryptonTreeView by node level.

### ISSUE THREAD

**Issue by gordon-matt** [Krypton-Suite/Standard-Toolkit#468]
I'm looking to do something like this with the `KryptonTreeView`: https://stackoverflow.com/questions/698369/how-to-disable-a-winforms-treeview-node-checkbox.

There is no `DrawMode` property to override and no `DrawNode` event to handle. How can we support enabling checkboxes for only certain node levels instead of everything? Also, it would be best if we could make a node level as single select only, while the child nodes can be multi select.

My scenario: My treeview shows databases and tables.. I want to be able to select multiple tables and then iterate through those to generate code (data access classes, UI, etc) for the selected tables in the selected database.. Generating them 1-by-1 is not as productive.

**Comment by Smurf-IV** [comment]
1) Node level checkbox disable: 
- could be possible
2) Multi and single select for row,: 
- no, this is custom code

Please see the `VirtualTreeGrid` (When I finally get it into Extended controls) that will be able to disable checkbox's per row, and will have more control over the "selectability" of each row via a callback action

Note: Hope to have it sometime this weekend.

**Comment by gordon-matt** [comment]
Excellent. Looking forward to it.

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Extended-Toolkit/issues/261

**Comment by Smurf-IV** [comment]
@gordon-matt Can you have a look / use the `VirtualTreeColumnView` that has been implemented in the PR above, to see if this is adequate for your requirements. If so close this and add any issues requests to the linked Feature request. - Cheers

**Comment by gordon-matt** [comment]
Do you have a pre-release NuGet package I can reference?
