### ISSUE TITLE
[Bug]: The `KryptonListbox` component does not fire the double-click event.

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#473]
From user: Erik (Discord)

Hi guys. 

Posting here since I'm not on Github.

Looks like I found a small issue.
For a simple example see the attached file and further info below.

K.Toolkit version: 6.2111.312 and 5.550.2108.1
Framework: 4.8 (only version tested)
IDE: VS2019

KryptonListbox Double Click event does not fire.
Both Toolkit versions produce the same behavior.

To reproduce
1. Start a clean empty project .Net 4.8 / C# / windows / Desktop

2. Install Nuget Package Krypton.Toolkit 6.2111.312 || 5.550.2108.1
3. Add a KryptonListbox to the form
4. Add some listbox items
5. Add the doubleclick event and a showmessage to verify the event has been fired.
6. Add a standard WinForms listbox with some items
7. Attach the double click event created in step 5

Cheers, 

[KryptonTestApp3.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7536699/KryptonTestApp3.zip)

**Comment by Wagnerp** [comment]
Seems that the `DoubleClick` event has not been assigned?

**Comment by Wagnerp** [comment]
Think I've fixed it, needs testing...

**Comment by Smurf-IV** [comment]
Whatever you have "Fixed" then ensure that the other controls that expect double clicks also have them routed. (i.e. Tree;s Combo's, Grid's, etc.)

**Comment by Wagnerp** [comment]
> Whatever you have "Fixed" then ensure that the other controls that expect double clicks also have them routed. (i.e. Tree;s Combo's, Grid's, etc.)

Going to test it on the list box first

**Comment by Wagnerp** [comment]
Need help

**Comment by Wagnerp** [comment]
Not sure if these events should be in the `KryptonListItem`?

**Comment by mbsysde99** [comment]
To fix that problem:

1. In `KryptonListBox.cs`

```
public KryptonListBox()
{
    // add this
    _listBox.DoubleClick += OnListBoxDoubleClick; 
}

// add this
private void OnListBoxDoubleClick(object sender, EventArgs e)
{
    // ReSharper disable RedundantBaseQualifier
    base.OnDoubleClick(e);
    // ReSharper restore RedundantBaseQualifier
}
```
2. In VisualControlBase.cs

```
// remove this
/*
/// <summary>
/// Raises the DoubleClick event.
/// </summary>
/// <param name="e">A KeyEventArgs that contains the event data.</param>
protected override void OnDoubleClick(EventArgs e)
{
	// Cannot process a message for a disposed control
	if (!IsDisposed && !Disposing)
	{
		Point location = PointToClient(MousePosition);
		_toolTipManager.DoubleClick(ViewManager?.ActiveView ?? ViewManager?.Root, location);
		// Do we have a manager for processing mouse messages?
		ViewManager?.DoubleClick(location);
	}

	// Let base class fire events
	base.OnDoubleClick(e);
}
*/

```

**Comment by Wagnerp** [comment]
> To fix that problem:
> 
> 1. In `KryptonListBox.cs`
> 
> ```
> public KryptonListBox()
> {
>     // add this
>     _listBox.DoubleClick += OnListBoxDoubleClick; 
> }
> 
> // add this
> private void OnListBoxDoubleClick(object sender, EventArgs e)
> {
>     // ReSharper disable RedundantBaseQualifier
>     base.OnDoubleClick(e);
>     // ReSharper restore RedundantBaseQualifier
> }
> ```
> 
> 1. In VisualControlBase.cs
> 
> ```
> // remove this
> /*
> /// <summary>
> /// Raises the DoubleClick event.
> /// </summary>
> /// <param name="e">A KeyEventArgs that contains the event data.</param>
> protected override void OnDoubleClick(EventArgs e)
> {
> 	// Cannot process a message for a disposed control
> 	if (!IsDisposed && !Disposing)
> 	{
> 		Point location = PointToClient(MousePosition);
> 		_toolTipManager.DoubleClick(ViewManager?.ActiveView ?? ViewManager?.Root, location);
> 		// Do we have a manager for processing mouse messages?
> 		ViewManager?.DoubleClick(location);
> 	}
> 
> 	// Let base class fire events
> 	base.OnDoubleClick(e);
> }
> */
> ```

@mbsysde99 Thanks, I'll have a look tomorrow & push a nightly build

**Comment by Wagnerp** [comment]
Fixed in build 2201
