### ISSUE TITLE
[Bug]: Solution Build and platforms are now disabled in VS2019

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#476]
Since the "Move to 2022" the existing solution to work in VS2019 no longer displays the Build target or platform.
This applies to Both the standard and the Examples solutions:
![image](https://user-images.githubusercontent.com/2418812/142167550-b78f72c7-ede9-4818-b062-1d8c7fb959d1.png)

Which means that it is "IMPOSSIBLE" to start a target project (No actions allowed!)

**Comment by Wagnerp** [comment]
Will look into it

**Comment by Smurf-IV** [comment]
FYI> The above where on the master branch as of today.
About to test the alpha branches.

**Comment by Smurf-IV** [comment]
They show up in the alpha soluti0n , but are not selectable in VS2019:
![image](https://user-images.githubusercontent.com/2418812/142170418-5bc66725-e4df-423c-b254-6c563dcb157f.png)

**Comment by Smurf-IV** [comment]
I'm wondering if the "Clean install" of VS2019 onto "bare metal" has messed something up !

**Comment by Wagnerp** [comment]
I wonder what's going on, as 2022 isn't in `master` yet, has VS19 received an update?

**Comment by Smurf-IV** [comment]
Then it all starts to work ??? Just had to build twice !
