### ISSUE TITLE
[Bug]: Opening the Form Designer within VS2022 causes an Error

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#477]
![image](https://user-images.githubusercontent.com/2418812/142208198-c1a1df43-12cb-4361-993e-5daf48bcf8be.png)

![image](https://user-images.githubusercontent.com/2418812/142208386-90c6563f-9ef1-4039-b39f-340cbf6bbf17.png)

**Comment by Smurf-IV** [comment]
Setting **all** projects to be .net48 only allows the forms designer to open:
![image](https://user-images.githubusercontent.com/2418812/142210151-11039ed6-619b-4973-82be-90cca50a45e8.png)

**Comment by Wagnerp** [comment]
Normally cleaning & rebuilding sorts this out

**Comment by Smurf-IV** [comment]
Seems to have been fixed in a later vcs2022 build:
![image](https://user-images.githubusercontent.com/2418812/147679193-05424f3c-4705-4d81-b996-8c4c793cc7b2.png)
