### ISSUE TITLE
[Bug]: KryptonListBox MouseDoubleClick- and DoubleClick-Event is not triggered

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#481]
**Describe the bug**
Event `DoubleClick` or `MouseDoubleClick` on `KryptonListBox`-Item is not triggered.
I think another Thread handle this here on GitHub, but I am not find this. So I opened a new one. 😄

**Comment by Wagnerp** [comment]
Duplicate of #473, fixed in build 2201

**Comment by DarthVader85PA** [comment]
Thanks a lot @Wagnerp 
I close it now!
