### ISSUE TITLE
[Bug]: `KryptonForm` loses visibility when the form border property is set to None using certain themes

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#483]
![image](https://user-images.githubusercontent.com/949607/142734996-15fdd8c6-fdeb-41e6-9847-eb77e8922d23.png)

Happens with all themes except:
Professional - System
Professional - Office 2003
Office 2013
Office 365 – Black
Office 365 - Black (Dark Mode)
Office 365 - Blue
Office 365 - Blue (Dark Mode)
Office 365 - Blue (Light Mode)
Office 365 - Silver
Office 365 - Silver (Dark Mode)
Office 365 - Silver (Light Mode)
Office 365 - White

To reproduce:
Start the program:

1. Change the theme multiple times. All should work fine
2. Select the first theme in the combo-box
3. Click the “Remove Borders” button.
4. Change the theme multiple times until the window disappears.

Happens when the From property is changed as on the second statement (code behind the button):

```cs
//this works fine
this.StateCommon.Border.Draw = Krypton.Toolkit.InheritBool.False
//this causes the form to disappear
this.StateCommon.Border.DrawBorders = Krypton.Toolkit.PaletteDrawBorders.None;
//this works fine
this.StateCommon.Header.Border.Draw = Krypton.Toolkit.InheritBool.False;
this.StateCommon.Header.Border.DrawBorders = Krypton.Toolkit.PaletteDrawBorders.None
```
[KryptonTestApp1.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7574892/KryptonTestApp1.zip)

**Comment by mbsysde99** [comment]
To resolved this bug, look at [`KryptonForm.cs`](https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonForm.cs)

```
private void UpdateBorderRegion(Region newRegion)
{
       ////////////////////////////////////////////////
        // add this to resolved that problems
	if (newRegion == null) {
	    return;
	}
	if (newRegion.IsEmpty(this.CreateGraphics())) {
	    return;
	}
       ////////////////////////////////////////////////

	// Cache the current region setting
	Region oldRegion = Region;

	// Use the new region
	Region = newRegion;

	// Cleanup old region gracefully
	oldRegion?.Dispose();
}
```

**Comment by Wagnerp** [comment]
Fixed in build 2201
