### ISSUE TITLE
[Bug]: Using todays alpha, Active form does not show the title text when using QAT

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#484]
Form is active:
![image](https://user-images.githubusercontent.com/2418812/142756903-3e5241a7-330f-4dff-b20f-c8f076ca5aa9.png)

When inactive title is shown:
![image](https://user-images.githubusercontent.com/2418812/142756916-745985df-570c-4309-86d9-5cf7bad5b24c.png)

Same for "ALL" other themes in the sample above:

**Comment by Smurf-IV** [comment]
Does not seem to replicate using the toolkit examples.
Only the Ribbon ones (So far)

**Comment by Smurf-IV** [comment]
`Meme Editor` (Workspace examples) which uses the ribbon - is okay..

**Comment by Smurf-IV** [comment]
Commenting out the following, make it work as expected:

![image](https://user-images.githubusercontent.com/2418812/142759422-c3b14415-d749-481e-9aa2-b44629344ad3.png)


@Wagnerp Why was this done ?

**Comment by Wagnerp** [comment]
I don't remember commenting this out, build 10586 was from 4 or 5 years ago

**Comment by Smurf-IV** [comment]
I commented it to restore the working form title.

**Comment by Wagnerp** [comment]
Fixed in build 2201
