### ISSUE TITLE
[Bug]: The position of the `KryptonForm` Control Buttons are too low, when no desktop scaling preference is applied

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#487]
See PR #474 for details

**Comment by Smurf-IV** [comment]
Using yesterdays nightly with .net48 running on Windows 10 and did not see the problem.
@Wagnerp Can you copy the video to here please ?
And also test in win10 using your set-up ?

**Comment by Wagnerp** [comment]
> Using yesterdays nightly with .net48 running on Windows 10 and did not see the problem. @Wagnerp Can you copy the video to here please ? And also test in win10 using your set-up ?

@Smurf-IV Sure, might be a Win11 issue with having thicker titlebars. Bumped into a similar but rare issue where the ribbon collapse/expand button 'crunches' into the close button.

**Comment by Wagnerp** [comment]
Windows 11 - build 22000.348:

![Animation](https://user-images.githubusercontent.com/949607/143301985-6f69b737-63f5-46f8-a187-b98ae6a723cd.gif)

**Comment by Smurf-IV** [comment]
@Wagnerp Can yuo run the following app on Windows 11 and report what it looks like please
In .net48 and then in .net6
![image](https://user-images.githubusercontent.com/2418812/147676979-f9cef125-6d75-44ca-b9bf-5c51365dffcf.png)

**Comment by Wagnerp** [comment]
@Smurf-IV As of 22000.376 & latest alpha build

.NET 4.8

![KFENET48](https://user-images.githubusercontent.com/949607/147691976-79e01c3e-e3b7-48ee-8bc5-54ae0c9b5b58.gif)

.NET 6

![KFENET6](https://user-images.githubusercontent.com/949607/147692005-43656250-76f8-4aee-ae2b-1f1dd45b499b.gif)

The titlebars appear to be a tad thin

**Comment by Smurf-IV** [comment]
> The titlebars appear to be a tad thin

And, the Icon between the "(ExtraText)" has disappeared!
From the above, it looks like the items are being drawn 2 pixels too low, and Icon is clipped out because it is too big.

@Wagnerp  Is it the same for the other themes as well ?

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, the icons were changed to 16 x 16, which are the true native size, as the original icons were 11 x 9.

**Comment by Smurf-IV** [comment]
At **least** 2 pixels according to VM Windows 11 (i.e not HDPI!)
![image](https://user-images.githubusercontent.com/2418812/147742819-63206fe2-162e-40bf-9062-24a22a0757c5.png)

**Comment by Smurf-IV** [comment]
With scaling set to be 125%, then the position of the icons is correct in win 11:
![image](https://user-images.githubusercontent.com/2418812/147744810-f0c04ee3-f3de-4a0e-af44-c45ccb28fe13.png)

**Comment by Smurf-IV** [comment]
It is a Windows scaling problem, and not related to Win 11:
![image](https://user-images.githubusercontent.com/2418812/147754864-5ccf865b-2059-423f-8d03-6f1b7f8a4e88.png)

**Comment by Smurf-IV** [comment]
Without the code fix on Win 10 @ 200%
![image](https://user-images.githubusercontent.com/2418812/147763579-7eb607a8-f96c-4308-a0b9-21b04ef62d0a.png)

With "Part" of the code fix:
![image](https://user-images.githubusercontent.com/2418812/147763739-96d24a80-a0ab-4eab-926a-4996c9269820.png)

Things to do:
- Scale the App icon
- Fix usage of the ButtonSpec when using custom image
- Fix usage when scaling @ 100%

**Comment by Smurf-IV** [comment]
2 & 3 done:
![image](https://user-images.githubusercontent.com/2418812/147766365-c5ebcc72-4c7a-4420-9d67-bdaf0a773f91.png)

**Comment by Smurf-IV** [comment]
All Done..
Will go into a PR tomorrow:
![image](https://user-images.githubusercontent.com/2418812/147768250-c795e68e-e567-421e-a8b9-f6d830ae229e.png)
![image](https://user-images.githubusercontent.com/2418812/147768333-7d946f2c-0c06-4d41-b55b-f5172555d862.png)
![image](https://user-images.githubusercontent.com/2418812/147768413-9bec1472-6376-45db-87a3-929eede219dc.png)
