### ISSUE TITLE
[Bug]: `KryptonTextBox` DoubleClick event does not fire

### ISSUE THREAD

**Issue by Desgui1234** [Krypton-Suite/Standard-Toolkit#488]
Hello,

I don't know if this is normal, but the "DoubleClick" event on the "KryptonTextBox1" is not working. Nothing happens. The "Click" event works, but not the "DoubleClick"

    __Private Sub KryptonTextBox1_DoubleClick(sender As Object, e As EventArgs) Handles KryptonTextBox1.DoubleClick
        MsgBox("DXFGFDGF")
    End Sub__

**Comment by Wagnerp** [comment]
Fixed in build 2201

**Comment by Desgui1234** [comment]
The built 2201 will be available when approx?

**Comment by Wagnerp** [comment]
> The built 2201 will be available when approx?

@Desgui1234 It'll release on 5th January 2022
