### ISSUE TITLE
[Feature Request]: Support for .NET 6

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#49]
ETA: November 2021
Expected Version #: 5.600.2111 or 6.0.2111 (stable TBC)/6.1.2111 (canary)

Other notes:

Remove `netcoreapp3.1` & `net5.0-windows` from 'lite' configuration, to be replaced with `net6.0-windows` as de-facto LTS version.

**Comment by lszczygielek** [comment]
.NET Core 3.1 is LTS, so in my opinion should not be removed so early (https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

**Comment by Wagnerp** [comment]
> .NET Core 3.1 is LTS, so in my opinion should not be removed so early (https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

I've checked, 3.1 will remain in the 'lite' version until November 2022, but .NET 5 will go, since the EOL is February 2022.

**Comment by Wagnerp** [comment]
Build 2111 is finally released with .NET 6 support
