### ISSUE TITLE
[Bug]: Krypton.Toolkit.KryptonMessageBox wrong form height when YesNo or AbortRetryIgnore buttons selected

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Standard-Toolkit#491]
**Describe the bug**
Some types of Krypton.Toolkit.KryptonMessageBox form height is wrong when 
MessageBoxButtons.YesNo or MessageBoxButtons.AbortRetryIgnore selected.

**To Reproduce**
Select MessageBoxButtons.YesNo or MessageBoxButtons.AbortRetryIgnore
in Krypton.Toolkit.KryptonMessageBox.Show(...)

**Expected behavior**
Correct height

**Screenshots**

![image](https://user-images.githubusercontent.com/30633382/143489046-c3e0d064-a8a7-41a0-a4f3-b6e98240d07a.png)

Correct
![image](https://user-images.githubusercontent.com/30633382/143489059-b0186b14-7841-451c-9dd9-8af8a7ce63cd.png)![image](https://user-images.githubusercontent.com/30633382/143489074-c3ce2034-2f38-407d-bcea-486dc850742c.png)

Incorrect
![image](https://user-images.githubusercontent.com/30633382/143489067-d9e92469-20e9-459b-a1e4-78c74d9cc87e.png)![image](https://user-images.githubusercontent.com/30633382/143489081-2c8fb053-9249-4bf3-896e-7e20f95ac0f9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19043.1348

**Additional context**
i just tried it in Krypton.Toolkit.Canary 6.2111.326-beta version only

**Comment by Wagnerp** [comment]
Now that is odd, @Smurf-IV have you seen this behaviour?

**Comment by mbsysde99** [comment]
I downloaded the Canary version of `Standard-Toolkit-canary` from [here](https://github.com/Krypton-Suite/Standard-Toolkit/tree/canary), and after I tested it, the `KryptonMessageBox` results worked fine.

```
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Error, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Exclamation, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Hand, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Information, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.None, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Question, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Stop, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.OK, icon: MessageBoxIcon.Warning, showCtrlCopy: false);
```
Results:
![image](https://user-images.githubusercontent.com/38758714/143514258-1681f330-a8a2-4eb9-8d8d-252aab9a4c2e.png)![image](https://user-images.githubusercontent.com/38758714/143514277-b7f39725-94cc-48ee-952e-d6918f408cfa.png)![image](https://user-images.githubusercontent.com/38758714/143514291-a03f1123-06f0-471e-838c-ffdf053697a8.png)![image](https://user-images.githubusercontent.com/38758714/143514307-feef2e8b-58c1-4426-815b-e52d78c078c7.png)![image](https://user-images.githubusercontent.com/38758714/143514319-f97834b2-e493-435f-b177-1e0cad363a42.png)![image](https://user-images.githubusercontent.com/38758714/143514330-a9dbbadf-435a-469f-aea0-cbee1fef0d33.png)![image](https://user-images.githubusercontent.com/38758714/143514345-dc88a550-b3d2-4b77-a11e-b639e1609ca0.png)![image](https://user-images.githubusercontent.com/38758714/143514368-bec4d1b5-6a2d-4b9d-b69c-79b83bff17cd.png)![image](https://user-images.githubusercontent.com/38758714/143514389-eae6f293-e310-4ac3-9318-e33501f3ee74.png)

**Comment by W4TR1X** [comment]
Hi @mbsysde99  the error not appear when using MessageBoxButtons.OK button. Only visible when
`MessageBoxButtons.YesNo` or `MessageBoxButtons.AbortRetryIgnore`

**Comment by mbsysde99** [comment]
> Hi @mbsysde99 the error not appear when using MessageBoxButtons.OK button. Only visible when `MessageBoxButtons.YesNo` or `MessageBoxButtons.AbortRetryIgnore`. Please check again with this settings.

With `MessageBoxButtons.YesNo`
```
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Error, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Exclamation, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Hand, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Information, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.None, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Question, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Stop, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.YesNo, icon: MessageBoxIcon.Warning, showCtrlCopy: false);
```
Results:
![image](https://user-images.githubusercontent.com/38758714/143532088-6e1de504-2969-4c80-9d84-3e970cb91dc8.png)![image](https://user-images.githubusercontent.com/38758714/143532107-d593f5f3-5518-4633-93cf-0ba3bab8685a.png)![image](https://user-images.githubusercontent.com/38758714/143532137-e2c7e75f-3706-4f34-9213-98ba75e171d8.png)![image](https://user-images.githubusercontent.com/38758714/143532152-63dcaacf-7314-4079-8492-23664fcb1a1f.png)![image](https://user-images.githubusercontent.com/38758714/143532166-1135a201-a063-48cb-82b1-0620b6f0ff30.png)![image](https://user-images.githubusercontent.com/38758714/143532181-fffeb691-a792-41c0-989c-acde74a1ddb1.png)![image](https://user-images.githubusercontent.com/38758714/143532204-993bfc66-9bbe-4a2a-8919-f02e47a9b8ae.png)![image](https://user-images.githubusercontent.com/38758714/143532228-2748c255-98a4-49a0-9182-1381179e2762.png)![image](https://user-images.githubusercontent.com/38758714/143532274-2ad9a75d-dec0-49d6-a2da-61406988ec35.png)


With `AbortRetryIgnore`
```
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Error, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Exclamation, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Hand, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Information, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.None, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Question, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Stop, showCtrlCopy: false);
KryptonMessageBox.Show("This is text", "This is caption", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Warning, showCtrlCopy: false);
```

![image](https://user-images.githubusercontent.com/38758714/143532784-14d0d9d3-c528-4f66-a7dc-5cc12a42cc75.png)![image](https://user-images.githubusercontent.com/38758714/143532802-618f5d11-f1d7-4f2c-b349-6ae0a5495a7e.png)![image](https://user-images.githubusercontent.com/38758714/143532812-0af48c27-e9bf-4081-99e5-dccd9aa0f9f8.png)![image](https://user-images.githubusercontent.com/38758714/143532823-ad772267-3e8f-4312-88f6-377aabb00e25.png)![image](https://user-images.githubusercontent.com/38758714/143533040-0f479f86-6119-4f3c-b4c6-6c88bdf34830.png)![image](https://user-images.githubusercontent.com/38758714/143532848-9e114730-d7a1-4a4b-b194-1d47ba21bf99.png)![image](https://user-images.githubusercontent.com/38758714/143532870-cc3c0850-99e9-4888-8701-6f0dd5bb60fb.png)![image](https://user-images.githubusercontent.com/38758714/143532881-f15123c9-58d8-4a36-b05a-5e99d77f7a57.png)![image](https://user-images.githubusercontent.com/38758714/143532896-d5264dca-daac-4483-b803-58c43468f817.png)

**Comment by mbsysde99** [comment]
You do not fill in the value for the `caption`, so the display is truncated, the bug is there.

**Comment by Wagnerp** [comment]
> You do not fill in the value for the `caption`, so the display is truncated, the bug is there. Add space for caption will resolved your problem. Space like `" "` or `"\u0020"`.
> 
> ```
> KryptonMessageBox.Show("This is text", "\u0020", buttons: MessageBoxButtons.AbortRetryIgnore , icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
> ```
> 
> Or
> 
> ```
> KryptonMessageBox.Show("This is text", " ", buttons: MessageBoxButtons.AbortRetryIgnore , icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
> ```
> 
> Result: ![image](https://user-images.githubusercontent.com/38758714/143534554-7151bf50-8625-4599-aea7-2be20e7cd424.png)

Maybe a check to see if caption = string.Empty || "" || " " is needed

**Comment by mbsysde99** [comment]
To fix the bug at the source see [KryptonMessageBox.cs](https://github.com/Krypton-Suite/Standard-Toolkit/blob/canary/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonMessageBox.cs)

```
private static DialogResult InternalShow(IWin32Window owner, string text, string caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, HelpInfo helpInfo, bool? showCtrlCopy)
{
        ///////////////////////////////////////////
        // add this to fixed bug
	caption = String.IsNullOrEmpty(caption) ? @" " : caption;
        ///////////////////////////////////////////

	IWin32Window showOwner = ValidateOptions(owner, options, helpInfo);

	// Show message box window as a modal dialog and then dispose of it afterwards
	using KryptonMessageBoxForm kmb = new(showOwner, text, caption, buttons, icon, defaultButton, options, helpInfo, showCtrlCopy);
	kmb.StartPosition = showOwner == null ? FormStartPosition.CenterScreen : FormStartPosition.CenterParent;

	return kmb.ShowDialog(showOwner);
}
```
Testing:
```
KryptonMessageBox.Show("This is text", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
KryptonMessageBox.Show("This is text", null, buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);
KryptonMessageBox.Show("This is text", "", buttons: MessageBoxButtons.AbortRetryIgnore, icon: MessageBoxIcon.Asterisk, showCtrlCopy:false);

```
Result:
![image](https://user-images.githubusercontent.com/38758714/143556087-09f76f90-f5a1-4660-a44d-9a911f58da2c.png)

**Comment by Wagnerp** [comment]
Fixed in build 2201
