### ISSUE TITLE
[Question]: changes font in crystalreport viwer at runtime

### ISSUE THREAD

**Issue by uggaldeniya** [Krypton-Suite/Standard-Toolkit#497]
when a form was inherited from KryptonForm it changed fonts in crystalreport viewer at run time. how could I stop this?

before krypton 
![Capture](https://user-images.githubusercontent.com/11691372/143691520-c3d4137d-f83d-4162-9166-b8ccf7d660d4.PNG)

after 
![Capture2](https://user-images.githubusercontent.com/11691372/143691528-3cb4793a-0cfe-46f3-970a-8fe00837633b.PNG)

**Comment by Smurf-IV** [comment]
This will be down to the default font being used by the form and is not dependent on the KryptonForm (It is a property of all forms)
It is just that in the early Krypton version, this was set to the default font found on XP systems.
The newer version uses this by default, but I suggest changing this to "Tahoma" if targetting below 10, and if only win10 onwards then use "Segoe UI"

![image](https://user-images.githubusercontent.com/2418812/146672535-db2d50c0-7442-487f-838d-48cd452173a8.png)
