### ISSUE TITLE
[Bug]: Why does the font change automatically at runtime?

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#498]
***Originally posted to ComponentFactory\Krypton*** by [DongCher](https://github.com/DongCher)

I am Developer in South Korea.
I am testing Krypton5480 and GrapeCity.Spread.Net. (ver 11.45.20183.0)

==> vs2015, Win10 x64, C#, Winform, KryptonToolKit5480, .Net FrameWork 4.8
GrapeCity.SpreadNet

Why does the font change automatically at runtime?

==> Design Time

![DesignTime](https://user-images.githubusercontent.com/949607/143734551-a957613d-90fe-41b6-bf7a-706cfac162bd.png)

==> Runtime Normal

![RunTimeNormal](https://user-images.githubusercontent.com/949607/143734614-1aa99dda-a50d-45bb-98f1-a2d31a9aff7c.png)

==> Runtime Krypton

![RunTimeKrypton](https://user-images.githubusercontent.com/949607/143734622-9d0e6ec2-3ad1-47b2-a2ba-717ca11fbe05.png)

**Comment by Smurf-IV** [comment]
Even with "Runtime Normal" the font has changed, so this is nothing to do with Krypton, as it is not even a Krypton Form being used to host the ThirdParty control.
