### ISSUE TITLE
[Bug]: KDataGridView Cell Borders

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#499]
_Bug reported by Erik on Discord_

Toolkit version: Canary 6.2111.310-beta

Use the included program to reproduce.

Cell Borders are still displayed when set to false. Somewhat similar inconsistent behaviour with KForm
State.(Common, Normal, etc.).DataCell.Border has 2 properties that handle the cell borders:

1. Draw
2. DrawBorders

When DrawBorders has one one or more options checked and Draw is set to False the cell-borders are 
still shown. 

Also the KryptonFrom object has similar behaviour (pic. 2) Only some of the border are 

Is this the correct behaviour. 

This shows Draw = False and still cell borders are present.

![image](https://user-images.githubusercontent.com/949607/143915431-0fa9312c-8708-4375-9c79-638c58e58083.png)

KForm has somewhat similar behaviour. Although setting draw to False and using RED as the border colour will turn the border colour to Black. But still draws the border. Only deselecting all DrawBorders options will remove the border.State(Active, Inactive Common).Border & .Header.Border all have similar behaviour.

![image](https://user-images.githubusercontent.com/949607/143915578-634be0d6-b4fe-4326-a452-ffb4c72c1120.png)

[KDataGridViewBorders.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7620031/KDataGridViewBorders.zip)

**Comment by mbsysde99** [comment]
For `KryptonDataGridView` border bug, look at [KryptonDataGridView.cs](https://github.com/Krypton-Suite/Standard-Toolkit/blob/canary/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonDataGridView.cs)

```
protected override void OnCellPainting(DataGridViewCellPaintingEventArgs e)
{	
        // I hid the rest of the code for easy viewing.
        // ...

        // add this to correct behaviour.
	if (this.StateCommon.DataCell.Border.Draw == InheritBool.True)
	{
		Renderer.RenderStandardBorder.DrawBorder(renderContext, tempCellBounds, _borderForced, VisualOrientation.Top, state);
	}

        // I hid the rest of the code for easy viewing.
        // ...
}
```
Result:
![image](https://user-images.githubusercontent.com/38758714/144735856-fd3ad66a-ac51-4b4b-a385-0293af20ffe3.png)
![image](https://user-images.githubusercontent.com/38758714/144735870-8eb4dfd2-f734-4965-99e4-382ee37b39fb.png)
![image](https://user-images.githubusercontent.com/38758714/144735892-f744e0da-181d-4adb-a451-1504cc98d0e5.png)

**Comment by Smurf-IV** [comment]
cheers @mbsysde99 I'll create a PR and see if it still works in the Current test apps today.

**Comment by Smurf-IV** [comment]
I see why this has been missed in testing, If the _DrawBorders_ is set to `None` then nothing is drawn as expected. 
It never occurred for the test to also include the _Draw_ value as well !

**Comment by Smurf-IV** [comment]
I'll have to modify the code to take into account the other states..
Not going to be as quick as the solution given, but at least it's a start !

**Comment by Smurf-IV** [comment]
Done:
![Example](https://user-images.githubusercontent.com/2418812/144740877-716be705-2d3c-4a8e-b767-7f4bcecce755.gif)

**Comment by Smurf-IV** [comment]
Note: Please generate a new Bug for the form borders with a specific example just for that

**Comment by Wagnerp** [comment]
> Note: Please generate a new Bug for the form borders with a specific example just for that

Are the KForm borders messed up?

**Comment by Smurf-IV** [comment]
> > Note: Please generate a new Bug for the form borders with a specific example just for that
> 
> Are the KForm borders messed up?

Comment based on Original title and comment in original description.
This fix is "Just" for the DataGrid borders (Cell's / rows / headers)

**Comment by mbsysde99** [comment]
> > > Note: Please generate a new Bug for the form borders with a specific example just for that
> > 
> > 
> > Are the KForm borders messed up?
> 
> Comment based on Original title and comment in original description. This fix is "Just" for the DataGrid borders (Cell's / rows / headers)

For `KryptonForm` look at `PaletteBorder.cs`

```
public Color Color1
{
	get => _storage?.BorderColor1 ?? Color.Empty;

	set
	{
		if (_storage != null)
		{
			if (_storage.BorderColor1 != value)
			{
				_storage.BorderColor1 = value;

                                // add this to correct behaviour.
				if (Draw == InheritBool.True)
				{
					OnPropertyChanged("Color1");
					PerformNeedPaint();
				}
			}
		}
		else
		{
			if (value != Color.Empty)
			{
				_storage = new InternalStorage
				{
					BorderColor1 = value
				};
 
                                // add this to correct behaviour.
				if (Draw == InheritBool.True)
				{
					OnPropertyChanged("Color1");
					PerformNeedPaint();
				}
			}
		}
	}
}

```
