### ISSUE TITLE
[New Feature Request]: Progressbar

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#5]
[#234](https://github.com/Krypton-Suite-Legacy/Krypton-NET-5.470/issues/234)

**Comment by Wagnerp** [comment]
here is a starting point:
https://stackoverflow.com/questions/20584132/change-the-color-of-a-toolstripprogressbar-without-disabling-the-xp-visual-style

Using the above, I have got a "Reasonable colour background" with the following event added to the status strip:

        private void StatusStrip_RendererChanged(object sender, EventArgs e)
        {
            if ( ToolStripManager.Renderer is KryptonProfessionalRenderer kpr )
                progressBar.BackColor= kpr.KCT.StatusStripGradientEnd;
        }

I wonder if this would help https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/walkthrough-creating-a-professionally-styled-toolstrip-control

**Comment by Smurf-IV** [comment]
Closing as duplicate of #203

**Comment by Smurf-IV** [comment]
@Wagnerp How do I get the data associated with link 234 in the Opening comment ?

**Comment by Wagnerp** [comment]
> @Wagnerp How do I get the data associated with link 234 in the Opening comment ?

@Smurf-IV Do you mean #234?

**Comment by Wagnerp** [comment]
> No.. From the Archived , See the link details at the top

@Smurf-IV It should now work :)
