### ISSUE TITLE
[Bug]: `KryptonComboBox` bugs out while using a specific `AutoCompleteSource` option

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#503]
Only the value AutoCompleteSource.ListItems can be used when DropDownStyle is ComboBoxStyle.DropDownList and AutoCompleteMode is not AutoCompleteMode.None.

**Comment by Smurf-IV** [comment]
@Wagnerp 
I do not understand:
If `AutoCompleteMode is not AutoCompleteMode.None` 
then 
this "Turns on the usage" of the "types" of either `AutoCompleteSource` or `AutoCompleteCustomSource`.

What is this bug about ?

**Comment by Wagnerp** [comment]
I think it was when I was trying to get the `ThemeComboBox` to work correctly. Can be closed, as the issue has been fixed.
