### ISSUE TITLE
[Other Issues]: Warning CS3008: Identifier '_toolTipValues' is not CLS-compliant

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#517]
Might need to disable `CS3008` warnings

**Comment by Wagnerp** [comment]
Disabled warning in source file.

**Comment by Wagnerp** [comment]
@Smurf-IV Can I merge PR #518?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Can I merge PR #518?

I thought it had been hence the closure.. Must have missed the PR review email....
