### ISSUE TITLE
[Feature Request]: `PaletteDataGridViewAll` does not expose the border value of the `private readonly PaletteDouble _background`

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#519]
Need to be able to set the border for focus / disabled etc.

And the following class does not expose the Border part of the PaletteDouble:

![image](https://user-images.githubusercontent.com/2418812/145039087-178e9293-d478-404b-8dd1-6db157ebbaae.png)

**Comment by PWagner1** [comment]
Expose it in the constructor

**Comment by Smurf-IV** [comment]
> @Smurf-IV & @giduac
> 
> I don't understand, `IPaletteDouble` is never assigned, should I remove?


No derived classes assign values as needed to it:
![image](https://github.com/user-attachments/assets/44cac8f1-9769-495d-b9c1-ccb81a1892b2)
