### ISSUE TITLE
[Bug]: Nuget Package descriptions need to be consistent (And published!)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#52]
**Describe the bug**
As viewed in Visual Studio ....

![image](https://user-images.githubusercontent.com/2418812/112278151-731b4d80-8c7a-11eb-9491-5f49066521e7.png)

**Comment by Wagnerp** [comment]
I don't understand what's going on. The `Directory.Build.targets` file seems to be ok.

**Comment by Wagnerp** [comment]
Patched in 2103.1

**Comment by Smurf-IV** [comment]
@Wagnerp can this be closed now ?

**Comment by Wagnerp** [comment]
Yes, forgot about this.
