### ISSUE TITLE
[Bug]: KDataGridView: can column high lighting be turned off.

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#533]
Hi there,

With KDataGridView some themes by default enable high lighting a column on mouse-over.

The standard DataGridView has a possibility/property that can do that.
EnableHeadersVisualStyles, when set to false. ColumHeaderDefaultCellStyle is used and high lighting disabled.
Video show this.

Also tried the StateTracking.HeaderColumns and other State* properties. But this yielded no solution.

Can this be turned off in one or the other way?

Cheers,

https://user-images.githubusercontent.com/96108132/146638851-f153b211-7bf2-4060-9523-5660abd15642.mp4

**Comment by Smurf-IV** [comment]
It should be this, But "it" does not respect the false statement for the colours !
![image](https://user-images.githubusercontent.com/2418812/146668948-e9b6e777-4b83-4d9d-9be3-10d415fc1109.png)

I am converting this into a "Bug"

**Comment by Smurf-IV** [comment]
Done:
![TurnTrackingOff](https://user-images.githubusercontent.com/2418812/146670121-ead3a473-b8ad-4794-a904-cec5451662c1.gif)

**Comment by giduac** [comment]
Nice, ty!
