### ISSUE TITLE
[Feature Request]: A way to set the textbox / combobox / RichTextBox Cue font `Rendering hint` style

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#535]
From `sdreb3421` via Discord

_Is there a way to set the textbox or combobox font hint (i.e. AntiAliasGridFit)? I see no way to do it for a text box, and the combo box only allows it for the drop down items. If not I'll add a feature request._

**Comment by Smurf-IV** [comment]
Current settings are:
```
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.TextRenderingHint = TextRenderingHint.AntiAlias;
```
So to change these, it will have to become a feature request.

**Comment by sdreb3421** [comment]
Would be nice, but I would make it low priority if so

**Comment by Smurf-IV** [comment]
This: 
![image](https://user-images.githubusercontent.com/2418812/205440166-6932ed7c-83ac-4d44-bb7e-787158272bca.png)
