### ISSUE TITLE
[Bug]: KryptonListBox error inside the IDE

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#538]
Hi guys,

Not sure how that menu on the control is called.
The video explains it all.

KToolkit: Canary 6.2112.343-beta

Cheers,

https://user-images.githubusercontent.com/96108132/146689477-1204bd70-7b26-4bf3-8f75-8f2851cce15c.mp4

**Comment by Wagnerp** [comment]
Hi @giduac 

This has been fixed, please use nightly build > 353.
