### ISSUE TITLE
[Bug]: KryptonLabel mnemonic key does not activate next control in the tab order

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#543]
KTookit: Canary 6.2112.343-beta

When using a mnemonic (accelerator) key on a (System.Windows.Forms) Label this ALT + KEY combo activates the control next after the label in tab-control chain. For KLabels this doesn't work.

In the sample program (never mind the name) attached, this is done with the label textbox combinations:
KLabel KTextBox
KLabel TextBox
Label TexBox

Only the last one works / get activated on ALT + L (in this case).

To reproduce:
- place the cursor inside the first textbox
- press ALT + L (this works)
- press ALT + R or K  (this doesn't)
- 
[KGroupBoxAnchors.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7768972/KGroupBoxAnchors.zip)

**Comment by Smurf-IV** [comment]
@giduac You have to set the `Target` in the designer, so when the mnemonic is triggered, it "knows" which control to focus on:
![image](https://user-images.githubusercontent.com/2418812/147357654-a7962b81-ef31-40e1-9f38-cddd7baab4ac.png)

**Comment by Smurf-IV** [comment]
FYI: Also, the `target` is used for click actions as well. to force focus into the target control.

**Comment by giduac** [comment]
@Smurf-IV 
Thank you...!!
