### ISSUE TITLE
[Feature / Bug fix]: Palette and user control set images (Custom and built in) are not scaled corect within dpi scenarios

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#558]
As part of the investigation into fixing #441 (and previous knowledge of #487), has led to the following issues that need to be sorted:

-  Global Palette
    - Changed via Code selection
    - Size change due to OS change (Monitor pref's or OS theme)
    - Size change due to "per monitor dpi"'s
-  Per Form palette assignments
-  Custom palette's
-  User assigned images
   - Global assignment
   -  Per control
-  Object lifetimes
-  Try to keep the existing palette code working for custom loading
-  .net462 does not have the OS events
-  To enable most things the app.config needs to have the correct options set!

**Comment by Wagnerp** [comment]
> .net462 does not have the OS events

@Smurf-IV I would wait until the 'old' .NET Framework is retired (or at least the 4.6.x line is) before considering doing this

**Comment by Smurf-IV** [comment]
> > .net462 does not have the OS events
> 
> @Smurf-IV I would wait until the 'old' .NET Framework is retired (or at least the 4.6.x line is) before considering doing this

It's as simple as this in the code:
``` c#
#if !NET462
            DpiChanged += OnDpiChanged;
#endif
```
It'll be the documentation for enabling such, and the differences in the `app.config` settings that will be difficult to "Make clear" regardless.

**Comment by Smurf-IV** [comment]
Notes / reminders; whilst I back stuff out:
![image](https://user-images.githubusercontent.com/2418812/147920006-005d1674-016a-40fd-8f8e-8f86775efedb.png)
![image](https://user-images.githubusercontent.com/2418812/147920175-09b3cd4d-e32a-469c-83e8-82f4a2da2549.png)

**Comment by Smurf-IV** [comment]
Notes:
The above changes are no longer viable, because:
- The `PaletteBase` has no knowledge of the images in the derived classes
- When classes use following
   ```c#
    public void PopulateFromBase()
    {
    _plus = _redirect?.GetTreeViewImage(false);
    _minus = _redirect?.GetTreeViewImage(true);
    }
     ```
     Then there is nothing that allows the images to be resized afterward: i.e. via an in app dpi change (i.e. move monitor event!)

This leaves at least 3 ways of solving the issue
1. For every draw & size request make sure that the image is scaled (Very slow as it is a lots of bitmap cache throw away stuff !)
2. Add events to the things that are storing a cached version (See `PopulateFromBase` above), and get them to retrigger cached sizing
3. Use Icons instead of images, and then store many sizes, and get them dependent on current scaling 

1. Easy, but a lot of code to find, and a lot slower for the app
2. Makes use of the existing images, but can miss some code that uses them
3. Best option, but makes the storage of themes problematic

@PWagner1 @giduac Thoughts ?

**Comment by Smurf-IV** [comment]
Closing this, as everything has been superceded, and a different direction has been proposed for V100 (Via Multi-image Icons maybe ?)
