### ISSUE TITLE
[Feature Request]: Use KryptonForm 'Blur' facilities when displaying a messagebox 

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#56]
As title states.

**Comment by Smurf-IV** [comment]
I'm confused..
The "Owner Form" (With `BlurValues.EnableBlur = true;`) initially does blur for 
- a normal Winform.MessageBox and then appears clear once the box is stable
- Is blurred for a KryptonMessageBox (But is mashed up on Windows 10 with dpi scaling)
  - Does not remain blurred if then using a tool like "Snip'n'sketch to capture the image!

@Wagnerp 
So "As the title states" is on which OS and under what circumstances ?
And / or is it referring to the "Does not remained blurred" as above ?

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Standard-Toolkit-Demos/pull/5

**Comment by Wagnerp** [comment]
The window behind the messagebox needs to be blurred to attract the user's attention, but go back to 'normal' once the messagebox goes away.

But this should be optional in the arguments to give the developer freedom based on his/her needs.

**Comment by Smurf-IV** [comment]
![TheDisappearingBlur](https://user-images.githubusercontent.com/2418812/112718947-16c06400-8eee-11eb-9a74-568268c82d6e.gif)

**Comment by Smurf-IV** [comment]
I disagree about it being an option in the MessageBox params, as this is set in the Owner form.
And.. If the messageBox does not have an owner passed through, then it would not be able to adjust the blur functionality as it was shown anyway !

**Comment by Wagnerp** [comment]
Is it possible to 'feed' the blur values to a `KryptonForm` in a messagebox, as I don't think `EnableBlur` is enabled by default?

**Comment by Smurf-IV** [comment]
It is not "Enabled by default", but if the Developer knows they are calling a Messagebox and wants to blur just for that occasion, then - as per the code snippet behind the gif above - they can just set it for the duration of the MessageBox call.

**Comment by Wagnerp** [comment]
I was thinking for the duration that the messagebox is shown, as the owner would have lost its focus until the messagebox is dismissed.

**Comment by Smurf-IV** [comment]
``` c#
            if (chkUseBlurring.Checked)
            {
                BlurValues.EnableBlur = true;
                BlurValues.BlurWhenFocusLost = true;
            }
            else
            {
                ResetBlurValues();
            }
```

**Comment by Smurf-IV** [comment]
During the testing of this feature "turned on for for messageBox", I found 3 other bugs
1) When Blurring on Windows 10 with a large screen, the offset of the blur overlay is wrong
2) The MessageBox display clears the blur underneath (Due to the code thinking it has lost focus, even when the messageBox is owned)
3) If the `BlurWhenFocusLost ` is set and the app is underneath another, then it will still have the blur overlay topmost (i.e. on top of the other app which is currently fullscreen!)
These will need to be raised,and related back to this.

**Comment by Wagnerp** [comment]
Hold on, with the `BlurValues` are they only applied to an individual `KryptonForm` or is there a way to set a global preference for these values?

**Comment by Smurf-IV** [comment]
> Hold on, with the `BlurValues` are they only applied to an individual `KryptonForm` or is there a way to set a global preference for these values?

Individual Form values:
![image](https://user-images.githubusercontent.com/2418812/112719703-1a55ea00-8ef2-11eb-902c-ab448004b59d.png)

**Comment by Wagnerp** [comment]
> > Hold on, with the `BlurValues` are they only applied to an individual `KryptonForm` or is there a way to set a global preference for these values?
> 
> Individual Form values:
> ![image](https://user-images.githubusercontent.com/2418812/112719703-1a55ea00-8ef2-11eb-902c-ab448004b59d.png)

So... could there be a way to 'set and forget' these values in a application?

**Comment by Smurf-IV** [comment]
> So... could there be a way to 'set and forget' these values in a application?

It would have to be at the KManager / Theme level, 
and for the code to go and check that each time the "Visible Form is created"
And then for it to be a Only Set if true, otherwise use local value - Documenting that would be "Strange"
And is not really the scope of this "Feature Request"

Also if it is a KryptonMessageBox (Or alert or other pop-up style based of Visible-Form) then what settings would they have ?

**Comment by Wagnerp** [comment]
> > So... could there be a way to 'set and forget' these values in a application?
> 
> It would have to be at the KManager / Theme level,
> and for the code to go and check that each time the "`VisualForm` is created"
> And then for it to be a Only Set if true, otherwise use local value - Documenting that would be "Strange"
> And is not really the scope of this "Feature Request"
> 
> Also if it is a KryptonMessageBox (Or alert or other pop-up style based of `VisualForm`) then what settings would they have ?

Going to start a new thread to discuss this idea, but might have an idea for 'special cases'

**Comment by Wagnerp** [comment]
Issue closed
