### ISSUE TITLE
[Bug]: MessageBox Icons do not display well when dpi scaling is used

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#563]
![image](https://user-images.githubusercontent.com/2418812/147950303-7347f833-ceed-41bf-ba64-8c9afc6f2c07.png)

**Comment by Wagnerp** [comment]
This is also what it currently looks like in https://github.com/Krypton-Suite/Extended-Toolkit/pull/259

**Comment by Smurf-IV** [comment]
This appears to be "Fixed" in todays V85:
![image](https://github.com/user-attachments/assets/5b71ed90-b0cd-4dbc-8b0d-09a1b61495f5)

**Comment by Smurf-IV** [comment]
And appears to be "OK" in todays alpha..
![image](https://github.com/user-attachments/assets/95f08259-81a1-4b76-b3c4-a90f0a200b77)

Closing
