### ISSUE TITLE
[Bug]: When copy / pasting a KryptonGroupBox, the resulting 'new' groupbox has its controls shifted if those controls are NOT set to Anchor > Top, Left

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#568]
_Originally posted by 'MattH' on Discord_

Just upgraded to 6.2201.4 (from 6.2111.312) and have noticed the following
When copy / pasting a KryptonGroupBox, the resulting 'new' groupbox has its controls shifted if those controls are NOT set to Anchor > Top,Left  (the attached image has all the left hand text set to Top.Right

Any edit to any control in the groupbox, causes all controls to move

Further to this, it seems any edit on the form that contains a control that is anchored different to the default (which is Top,Left) completely screws the controls position.

It is  difficult to spot the missing/moved control as it is outside the host control, therefore not on screen

**Comment by Smurf-IV** [comment]
This was caused by the `CenterParent` / `CenterScreen` bug that has been fixed, see #571
