### ISSUE TITLE
[Bug]: Border Rounding Issue

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#569]
The latest stable release (6.2201.4) introduced a bug into how the library handles border rounding. This is only apparent if you create a rounded border but not draw the border edge. 

Perform the steps below. In previous versions, this would show the control with rounded corners but not draw the border edge. In the latest version, this stops drawing the rounding all together. I've found this to be true for KButtons, KCheckButtons, KGroupBoxes, so I assume it applies to the rounding code for all controls.

1. Set StateCommon.Border.Rounding = 10. 
2. Set StateCommon.Border.DrawBorders = Top | Bottom | Left | Right
3.  Set StateCommon.Border.Draw = False.

This affects almost all of the controls in our application. We rarely want to show a border on our controls, so rather than adjusting the palette to make sure the border colors match the back colors everywhere , we just don't draw them.

**Comment by Smurf-IV** [comment]
I'm confused. If Draw is set to false then it will not draw borders.. This was a bug fix from a while back..
Relevant bug is #510 
So what is required , Round controls but not the border line ?? If so then just set the border colour to be transparent.
``` c#
StateCommon.Border.Color1 = System.Drawing.Color.Transparent;
StateCommon.Border.DrawBorders = ((Krypton.Toolkit.PaletteDrawBorders)((((Krypton.Toolkit.PaletteDrawBorders.Top | Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | Krypton.Toolkit.PaletteDrawBorders.Left) 
            | Krypton.Toolkit.PaletteDrawBorders.Right)));
StateCommon.Border.Rounding = 10F;
```
This then gives:
![image](https://user-images.githubusercontent.com/2418812/148645001-f0003cbd-1f89-4116-9e35-8f4c4c4b6962.png)

**Comment by sdreb3421** [comment]
I can't really figure out why the previous behavior was considered a bug, but I can make this work.
