### ISSUE TITLE
[Feature Request]: `KTextBox` & `KRichTextBox` support Color.Transparent for a back colour

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#573]
The `KTextBox` & `KRichTextBox` does not support **_Color.Transparent_** as a back colour

**Comment by Smurf-IV** [comment]
But they do not support transparent in normal Form controls:
![image](https://user-images.githubusercontent.com/2418812/148640373-63a9c60c-8f07-45e2-84b5-487902fe7d26.png)

So why expect the Krypton to do different ?
![image](https://user-images.githubusercontent.com/2418812/148640394-059d872e-3fec-4296-aeed-3050dc920501.png)

If this is required then it's a feature request.

**Comment by Wagnerp** [comment]
I was going to use this in the extended toolkit toast module, since I don't think that KLabels support scrollbars. Having a white background looks out of place in this scenario.

**Comment by Smurf-IV** [comment]
>Having a white background looks out of place in this scenario.

They should be the "Client panel colour" of the current theme ?!?!

**Comment by Wagnerp** [comment]
> > Having a white background looks out of place in this scenario.
> 
> They should be the "Client panel colour" of the current theme ?!?!

Either that, or the 'Alternate Panel' colour

**Comment by Wagnerp** [comment]
@Smurf-IV This should be ready for testing in the next day or so! :)

**Comment by Wagnerp** [comment]
> How does it work for "Disabled" state ? Because that is what i have been struggling with for the Backcolours in the other Bug.

Another feature request would need to be opened for the disabled state. I have laid the groundwork for it, but haven't figured it out just yet. https://github.com/Krypton-Suite/Standard-Toolkit/pull/671/commits/21c5f88f85f52b0235cb45b3646738a8918df096

**Comment by Wagnerp** [comment]
@Smurf-IV The disabled state looks like this:

![image](https://user-images.githubusercontent.com/949607/158159071-d4e35617-a0c7-4902-8ecf-4f79e0d854ef.png)

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/158160982-0e420992-d3e9-4616-9480-e81f4d655d38.png)

**Comment by Wagnerp** [comment]
Implemented - 17/03/2022
