### ISSUE TITLE
[Bug]: KryptonLabel adds the Paint method by default

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#587]
When a KLabel is double clicked in the designer the paint method is assigned.
Normally the click method is. With KLinkLabel and KWrapLabal this works correct.

Ktoolkit: Latest Stable and earlier versions as well.
.Net: 4.8

**To Reproduce**
Drop a KLabel on the form and double click it.

**Comment by dax-leo** [comment]
It's just simple change in DefaultEvent Attribute. Currently assigned to Paint.
https://github.com/Krypton-Suite/Standard-Toolkit/blob/23396b2a2b3e7ca7084eddd92fa882e51bb6df00/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonLabel.cs#L21

**Comment by Wagnerp** [comment]
Resolved - 16/01/2022, both `KryptonLabel` & `KryptonWrapLabel` now default to the `Click` event.
