### ISSUE TITLE
[Bug]: KryptonThemeComboBox: list is empty

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#589]
KryptonThemeComboBox: list is empty

Toolkit: Stable 6.2201.4

Seems that this adjustment in earlier nightlies and canaries didn't make it into the latest stable release.
Was handled here before: https://github.com/Krypton-Suite/Standard-Toolkit/issues/500

**Comment by Wagnerp** [comment]
To be included in version `60.22.02.32`.
