### ISSUE TITLE
[Bug]: When Building "Alpha" branch on Clean machine - Compile errors are seen

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#59]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2418812/112717497-12437d80-8ee5-11eb-8f9e-0ac0b69e996d.png)

**To Reproduce**
- Clean Visual Studio (With "All .Net Targets selected/installed)
- Add .Net6 (Preview 2) SDK
-  Build debug

**Expected behavior**
A Readme.md file indicating anything else that should be on the developers machine (When recreating Visual Studio install from metal)
OR nuget packages to pull in the correct values to allow build to happen.

**Additional context**
Windows 10 Pro Latest
Visual Studio 16.9.2

**Comment by Smurf-IV** [comment]
FYI: The above errors are not seen when building the master branch.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Did you use `run.cmd` from cmd/Windows Terminal?

**Comment by Smurf-IV** [comment]
> Hi @Smurf-IV
> 
> Did you use `run.cmd` from cmd/Windows Terminal?

Nope
Didn't know I had to.

**Comment by Wagnerp** [comment]
@tbolon Created scripts when it was moved over. It's a lot faster than compiling in VS!

**Comment by Smurf-IV** [comment]
I think the "Speed Differnce" is now reduced since 16.9 was released.

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be closed?

**Comment by Smurf-IV** [comment]
Has a readme been created ?

**Comment by Wagnerp** [comment]
No, but I can add a `How to Compile` document?
