### ISSUE TITLE
[Bug]: Button text colour in certain themes is unreadable

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#590]
Theme Button colours unreadable

Toolkit: Stable 6.2201.4
Theme: Office 365 Black (Dark Mode)

The text color for the buttons has changed in this release leaving the text unreadable.

I came across this when updating to the latest stable.

This is probably (one) of the colours related to this (image).
`kryptonThemeComboBox1.KryptonManager.GlobalPalette.GetContentLongTextColor1( PaletteContentStyle.LabelNormalPanel, PaletteState.Normal );`
![image](https://user-images.githubusercontent.com/96108132/149303689-0cf3d39d-bb1d-4443-bc1b-c80daf7c0445.png)

**Comment by Wagnerp** [comment]
Needs to be white... might have inadvertently reversed the `disabled` colours

![image](https://user-images.githubusercontent.com/949607/149306006-34fbb0e4-a484-4c38-8d03-3230a2578f8f.png)

**Comment by giduac** [comment]
Yes, forgot to mention that: it was white before

**Comment by Wagnerp** [comment]
Fixed

![image](https://user-images.githubusercontent.com/949607/149381978-686b1649-1d54-49af-9f2a-c126c2bf6ce3.png)

**Comment by Wagnerp** [comment]
Fixed - 13/01/2022
