### ISSUE TITLE
[Bug]: Office 365 Blue Theme

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#591]
**Describe the bug**
After update to 6.2201.x (Latest Stable) the office 365 blue theme looks like incorrect?!

**Screenshots**
![grafik](https://user-images.githubusercontent.com/32876506/149313343-f198af00-5422-4201-bf70-9002fff965a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 Build 19042.1466
 - Visual Studio: Visual Studio 2017 Professional 15.9.43
 - TFM: .NET-Framework 4.7.2
 - Krypton: 6.2201.4.0 NuGet

Greetings from Germany

**Comment by DarthVader85PA** [comment]
For example: the same Screen with office 2010 blue theme:

![grafik](https://user-images.githubusercontent.com/32876506/149313845-8aa6aefe-1a8a-42fc-a6ed-be0a9ee18404.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Which colours do the tab areas use?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Which colours do the tab areas use?

Don't know without having a search through code..

But the above screenshots are also highlighting the fact that there is a shadow being created for the window that holds the accelerator text indicators.. That's a separate bug.

**Comment by Wagnerp** [comment]
> > @Smurf-IV Which colours do the tab areas use?
> 
> Don't know without having a search through code..
> 
> But the above screenshots are also highlighting the fact that there is a shadow being created for the window that holds the accelerator text indicators.. That's a separate bug.

Maybe a separate bug report needs to be opened for the shadowing glitch

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Is this still a issue with v85?

**Comment by giduac** [comment]
Closed due to no further response from the reporter.
If needed the ticket can be reopened.
