### ISSUE TITLE
[Bug]: ActionLists do not reflect the recommended or possible settings in the designer properties

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#596]
**Describe the bug**
e.g. for a KComboBox the following is seen in the designer "Tasks"
![image](https://user-images.githubusercontent.com/2418812/149654887-8a064194-9bc5-47d5-9508-84a10ecb4631.png)
From this 2 things are immediate
- "Context  Menu Strip" should be the recommended "Krypton Content Menu"
- Corner Rounding Radius is not visible in the Properties 
![image](https://user-images.githubusercontent.com/2418812/149654923-c05f9e0b-de11-49d9-b28f-2db154e06366.png)

**Comment by Wagnerp** [comment]
I'm going to assign this to myself, whilst fixing, should I add the 'Name' property to the tasks?

**Comment by Smurf-IV** [comment]
"Name" property will be confusing when it comes to ribbon controls and things, So it should be a separate "Feature Request"

**Comment by Smurf-IV** [comment]
"Corner Rounding Radius"
Needs to become "StateCommon Corner rounding radius" to reflect its true location.

**Comment by Smurf-IV** [comment]
Same for "Font"

**Comment by Wagnerp** [comment]
Fixed, but keeping open in case of any other properties that need fixing

**Comment by Smurf-IV** [comment]
You've done the "StateCommon" part, but not the "Context menu" replacement part.

**Comment by Wagnerp** [comment]
> You've done the "StateCommon" part, but not the "Context menu" replacement part.

Done :)

**Comment by giduac** [comment]
When https://github.com/Krypton-Suite/Standard-Toolkit/issues/1521 is complete this should be solved as well.

**Comment by Wagnerp** [comment]
> When #1521 is complete this should be solved as well.

Hi @giduac 

Is it ok to reassign to you as part of #1521?

**Comment by giduac** [comment]
That's OK and please stick the V100 label on both of them

**Comment by Wagnerp** [comment]
> That's OK and please stick the V100 label on both of them

Done & changed the milestones

**Comment by giduac** [comment]
Hi @Wagnerp,
This is referenced in https://github.com/Krypton-Suite/Standard-Toolkit/issues/1521 action lists general overhaul.
 Please close, ty.
