### ISSUE TITLE
[Bug]: KryptonMessageBox does not respond to ESC and CTRL-C (copy option)

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#599]
Hi there,

A normal MessageBox can be dismissed at any time with the ESC Key.
Also the CTRL+C key combo does not copy the KMessageBox text to the clipboard.

KT Version: 6.2201.4 Stable / also exists in older versions

To reproduce:
Launch a KMessageBox from code and try to use ESC and CTRL+C

Additional:
There seems to be code in KryptonMessageBoxForm.cs that could/should handle these events.

Cheers,

**Comment by Smurf-IV** [comment]
I thought that I had fixed this?
Perhaps it has come back !

**Comment by Wagnerp** [comment]
@Smurf-IV Is this also linked to #563?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is this also linked to #563?

No, Scaling is nothing to do with keyboard events.

**Comment by Smurf-IV** [comment]
I have been unable to replicate this in the current Alpha Branch:

![CtrlCAndEsc](https://user-images.githubusercontent.com/2418812/150639481-9622dc21-a846-4aec-97ad-ff354578faa2.gif)

**Comment by giduac** [comment]
Confirmed @Smurf-IV .
I tried this today:
- Stable release: both options don't work.
- Nightly 60.22.1.22-alpha both ESC and CTRL+C work

Thank you !!
