### ISSUE TITLE
[Bug]: Form icon is displaying stretched width (Canary)

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Standard-Toolkit#601]
**Describe the bug**
Form icon is displaying stretched width

**To Reproduce**
1. Fresh .net 6 project 
2. Add Krypton.Toolkit.Suite.Extended.Buttons.Canary
3. Change default form icon (i am using 64x64 pixel icon)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30633382/149674120-b7f675b8-cedf-400d-998e-7f843d9460c8.png)
![image](https://user-images.githubusercontent.com/30633382/149674148-3d782e0d-57dd-4919-a4cc-de34dff83763.png)
![image](https://user-images.githubusercontent.com/30633382/149674229-63ca992a-0a79-4593-8fdc-e448d742272c.png)

https://user-images.githubusercontent.com/30633382/149674417-28529bd3-6cd2-4f76-99a6-99538b9b5eb9.mp4

**Desktop (please complete the following information):**
 - OS: Win10
 - Vs Version: 2022
 - K Package: Krypton.Toolkit.Suite.Extended.Buttons.Canary

**Additional context**
Every version of canary package is having same result;
- 6.22.1.5-beta
- 6.22.1.8-beta
- 60.22.1.11-beta
- 60.22.1.12-beta

**Comment by Wagnerp** [comment]
> @W4TR1X Can you attach the icon you are using please ? And state what sizes it contains

According to the screenshot that @W4TR1X provided, the icon is 64 x 64

**Comment by W4TR1X** [comment]
> @W4TR1X Can you attach the icon you are using please ? And state what sizes it contains

Sorry for the delay. 

[lock.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7883889/lock.zip)

**Comment by Smurf-IV** [comment]
@W4TR1X It is "Good practice" to have other icon sizes in the file, as sometimes compressing an icon does not show some detail (Especially if running @ 16*16 from a large complicated icon.
Any way 64*64 will never be used uncompressed, as even when it is 225% it is only using a 36*36 in the form header pixel space

**Comment by W4TR1X** [comment]
> @W4TR1X It is "Good practice" to have other icon sizes in the file, as sometimes compressing an icon does not show some detail - Especially if running @ 16x16 from a large complicated icon. Any way 64x64 will never be used uncompressed, as even when it is 225% it is only using a 36x36 in the form header pixel space


@Smurf-IV Thanks for the tip, I'm aware of this and actually in production I'm trying to use 16px, 24px, 32px, 64px in the same file.
