### ISSUE TITLE
[Bug]: Title Bar Images Stretched/Cropped (Regression)

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#603]
The new canary build (60.22.1.17) has introduced stretching/cropping of the icons/images in the krypton form title bar. This could be related to #601.

Stable:
![image](https://user-images.githubusercontent.com/1911567/150245040-72a55450-8012-4e4e-a0a7-716d1d98e6a6.png)

Canary:
![image](https://user-images.githubusercontent.com/1911567/150244649-c98f7174-d5be-44ee-a476-01957ef7d727.png)

**Comment by Smurf-IV** [comment]
@sdreb3421 I am unable to replicate this (At any of the scaling I have on my QHD monitor with Win 10 20H2)
Can you state what 
- size display you are using
- scale applied
- Version of windows

**Comment by sdreb3421** [comment]
I was unable to resolve the issue with any scale setting unfortunately. The advanced scaling settings are disabled, but changing them didn't fix it either. Neither did changing the resolution of my monitor (native 1920x1080). The images below show my OS info, the results of various scaling (100%, 125%, 150%), and the images I used.

To replicate the issue, create an empty krypton form, no palette settings, and add button specs to the form using the three images below. The issue is most obvious when using smaller images that have rounded edges. If you're unable to replicate this I will go run some tests on other computers I can find.

![image](https://user-images.githubusercontent.com/1911567/150656246-31adadde-ca5e-4d11-a85c-1a6fbf7165de.png)

![Test](https://user-images.githubusercontent.com/1911567/150656154-5706e8e8-f844-4af0-889e-bae4cd04f6ad.png)

![help16](https://user-images.githubusercontent.com/1911567/150656173-7fd74a0c-b2d2-4ad7-9714-7c9e6fc87b4d.png)
![play20](https://user-images.githubusercontent.com/1911567/150656185-30d6bcf2-8363-447f-aa60-3be8df7c249c.png)
![recordredtop](https://user-images.githubusercontent.com/1911567/150656193-458642a4-94e0-4f7c-b877-03c8db618c1e.png)

**Comment by Wagnerp** [comment]
Hi @sdreb3421 is it possible to use images, which are 24 x 24?

**Comment by Smurf-IV** [comment]
> I was unable to resolve the issue with any scale setting unfortunately..... The images below show my OS info, the results of various scaling (100%, 125%, 150%), and the images I used.
Are you saying that this is a problem even when 100% on Native scaling ?

What is the size of the images (i.e. 16x16 or something else) ( cannot see from the images you have chosen as they are png's, and they will may be stored as bitmaps internally)

Note: at this size bmp is more efficient than png overhead.

**Comment by Smurf-IV** [comment]
FYI See the following PR demo of Form butts with round images:
https://github.com/Krypton-Suite/Standard-Toolkit/pull/604

**Comment by sdreb3421** [comment]
Yeah it would be okay to use 24px. Does that fix the issue? I can test it tomorrow morning...

**Comment by sdreb3421** [comment]
@Smurf-IV looks like you were able to replicate it in that PR. Is the issue the image size?

**Comment by Wagnerp** [comment]
> Yeah it would be okay to use 24px. Does that fix the issue? I can test it tomorrow morning...

Yes it does, please see @Smurf-IV previous comment for a demo.

**Comment by sdreb3421** [comment]
@Smurf-IV the images I'm using are 20px.

**Comment by Wagnerp** [comment]
> @Smurf-IV looks like you were able to replicate it in that PR. Is the issue the image size?

@sdreb3421 They are using 24 or 25px

**Comment by sdreb3421** [comment]
@Smurf-IV I'm confused, are you saying they had the issue when using 24px, or that is the fix?

**Comment by sdreb3421** [comment]
I'm assuming this image size requirement doesn't just apply to button specs, but also applies to the form control buttons and form icon?

**Comment by Smurf-IV** [comment]
> I'm assuming this image size requirement doesn't just apply to button specs, but also applies to the form control buttons and form icon?

Form Control buttons are ButtonSpecs.

The Form Icon is independent and should be an "Icon with multiple sized images " not a single bitmap image

**Comment by sdreb3421** [comment]
I just upgraded to the latest stable (60.22.2.32) and tried using a 24px button spec image, and the problem still exists. We have tested with 16, 20, 24 and 32px with the same issue. The issue is applying to form button specs and navigator button specs. Have you guys been able to replicate the issue?

**Comment by sdreb3421** [comment]
Looks like #623 is likely the same issue.

**Comment by Smurf-IV** [comment]
Using the images supplied:
![image](https://user-images.githubusercontent.com/2418812/152672597-f3574b79-126d-42a1-944b-d4941455be82.png)
![image](https://user-images.githubusercontent.com/2418812/152672607-52de7c6e-a1ea-4bb7-89f5-ae24376c61a1.png)
![image](https://user-images.githubusercontent.com/2418812/152672623-582098a9-23db-4ff7-be88-54675f268e86.png)

Results (Restart app between scale changes):
![image](https://user-images.githubusercontent.com/2418812/152672544-ece469d0-358a-4055-acdd-25d132a52d92.png)
![image](https://user-images.githubusercontent.com/2418812/152672522-324a8bfe-88cb-435d-b411-b0860bd21f54.png)
![image](https://user-images.githubusercontent.com/2418812/152672493-f5ffa32d-16cb-4668-a961-a32faa461d0b.png)
![image](https://user-images.githubusercontent.com/2418812/152672473-72ee167b-6737-4c5e-b0ac-2f577444a364.png)


I was only able to see "Compression" when the images are rescaled down to 16*16 as expected for 100%.

**Comment by Smurf-IV** [comment]
@sdreb3421 
tried to replicate by using the sample app to cover your repro steps:  _(To replicate the issue, create an empty krypton form, no palette settings, and add button specs to the form using the three images below. )_

1) What Windows theme are you using?
2) What Krypton theme are you using?

**Comment by Smurf-IV** [comment]
1 thing I have noticed ("Due to compression"), is that the images are compressed more vertically, that they are horizontally:
![image](https://user-images.githubusercontent.com/2418812/152672778-fb75803c-aca2-4a19-bdc1-31c1ca4bac84.png)

**Comment by Smurf-IV** [comment]
Fix for the compression artefacts:
![image](https://user-images.githubusercontent.com/2418812/152674072-6a4abdc6-0c37-4c9b-8322-6917a8747b54.png)

**Comment by Smurf-IV** [comment]
The above fix has "Now" rebroken the scaling of the images up:
![image](https://user-images.githubusercontent.com/2418812/152674687-110f63ac-2296-4e62-871c-ad107cd0fc9d.png)

**Comment by Smurf-IV** [comment]
I think I have fixed both scenarios:
![image](https://user-images.githubusercontent.com/2418812/152682025-4ef3408f-9a06-4a3e-8862-319e6fadcbf9.png)
![image](https://user-images.githubusercontent.com/2418812/152682053-61ba5af6-28a3-4eb6-a259-6bae49b9c7cc.png)
![image](https://user-images.githubusercontent.com/2418812/152682082-53eccd3b-2b02-49be-9f51-d985f260c4e9.png)

**Comment by sdreb3421** [comment]
> I think I have fixed both scenarios: ![image](https://user-images.githubusercontent.com/2418812/152682025-4ef3408f-9a06-4a3e-8862-319e6fadcbf9.png) ![image](https://user-images.githubusercontent.com/2418812/152682053-61ba5af6-28a3-4eb6-a259-6bae49b9c7cc.png) ![image](https://user-images.githubusercontent.com/2418812/152682082-53eccd3b-2b02-49be-9f51-d985f260c4e9.png)

The image you're showing at 125% looks like what I'm seeing. Will the next nightly have the fix for me to test?

**Comment by Smurf-IV** [comment]
> The image you're showing at 125% looks like what I'm seeing. Will the next nightly have the fix for me to test?

That is the idea, just not sure when the nightlies are built in relation to timezones (And manual prompts) , so get one that has least "day" .38  labelled (i.e today, as of writing)

**Comment by Smurf-IV** [comment]
.38 has just been released :-)
https://discord.com/channels/620577714889424916/940148840504373260

**Comment by sdreb3421** [comment]
@Smurf-IV @Wagnerp I'm not sure what happened, but I am seeing this same issue again after updating from 6.2201.4 to the latest version 65.22.6.152.

Can you confirm that the nightly fix was added to the code base? Thanks

**Comment by Smurf-IV** [comment]
@Wagnerp 

> Can you confirm that the nightly fix was added to the code base? Thanks

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> > Can you confirm that the nightly fix was added to the code base? Thanks

@sdreb3421 & @Smurf-IV 

It should be, check the latest canary to see if it exists in there

**Comment by sdreb3421** [comment]
@Wagnerp @Smurf-IV I went back to the nightly version that I originally found that it was fixed with and worked my way forward. It looks like it was fixed all the way to nightly 65.22.5.91-alpha, but broke again in 65.22.5.94-alpha. Is this enough to help locate the issue? Thanks

**Comment by Smurf-IV** [comment]
@Wagnerp in your court now.

**Comment by Wagnerp** [comment]
@sdreb3421 Please retry using today's nightly

@Smurf-IV Somehow, old code snuck back in :)

**Comment by sdreb3421** [comment]
Fixed in Nightly 70.22.7.185-alpha! 

However, when updating to this from stable 6.2201.4 I'm getting designer exceptions and a runtime exception. The runtime exception is occurring on ((System.ComponentModel.ISupportInitialize)(this.tabMain)).EndInit();

**Comment by Wagnerp** [comment]
> Fixed in Nightly 70.22.7.185-alpha!
> 
> However, when updating to this from stable 6.2201.4 I'm getting designer exceptions and a runtime exception. The runtime exception is occurring on ((System.ComponentModel.ISupportInitialize)(this.tabMain)).EndInit();

Old code might have got back in between 2201.4 & 70.22.7.185.

> ((System.ComponentModel.ISupportInitialize)(this.tabMain)).EndInit(); Is this expected?

Might be something to do with .NET 4.8.1, @Smurf-IV any ideas?

**Comment by sdreb3421** [comment]
I'm using VS 2022 with only NET6 as target framework. I can't also target net48 due to incompatible assemblies. However, designer looks good and no runtime exceptions with 6.2201.4.

**Comment by sdreb3421** [comment]
@Wagnerp @Smurf-IV should this fix have been included in the July canary release? I just installed and still see the icon distortion... Thanks

**Comment by Wagnerp** [comment]
> @Wagnerp @Smurf-IV should this fix have been included in the July canary release? I just installed and still see the icon distortion... Thanks

@sdreb3421 Yes it should be if it's fixed in the latest nightly.

**Comment by sdreb3421** [comment]
@Wagnerp @Smurf-IV you guys... what is happening here. It was fixed in nightly 70.22.7.185-alpha, but immediately broken again in 70.22.7.188-alpha. This is the second time the fix has been removed. I blame it on the aliens.

**Comment by Wagnerp** [comment]
@sdreb3421 The only fixed version I can think of was in [this](https://github.com/Krypton-Suite/Standard-Toolkit/pull/628) version. If I compile said version, are you able to test?

cc. @Smurf-IV

**Comment by Wagnerp** [comment]
Got it! The 'fix' is [here](https://github.com/Krypton-Suite/Standard-Toolkit/pull/627). Going to reimplement tomorrow.

**Comment by sdreb3421** [comment]
Awesome. Tag me and I'll test the nightly when it's time. Thanks

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

Please re-test using today's `nightly` build, 213

**Comment by sdreb3421** [comment]
Looks perfect. And no runtime exceptions. Well done, thank you
