### ISSUE TITLE
[Bug]: KryptonContextMenu: Item text unreadable with certain themes

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#609]
KToolkit (Windows 10 / .Net 4.8): 
Nightly 60.22.1.22-alpha
Nightly 60.22.1.24-alpha

Contextmenu components tested (see video):
CheckBox
CheckButton
RadioButton
LinkLabel

Occurs with the properties Text and ExtraText.

Themes:
Office 2007 Black
Office 2007 Black (Dark Mode)
Office 2010 Black
Office 2010 Black (Dark Mode)
Office 365  Black
ALL Sparkle Themes

https://user-images.githubusercontent.com/96108132/150948270-57800874-9edd-413a-a00d-3174b5725537.mp4

**Comment by Wagnerp** [comment]
@Smurf-IV Is there any way that we can introduce an alternate text colour, as at the moment, one colour controls everything?

**Comment by Smurf-IV** [comment]
> one colour controls everything?

?? If it's a menu, then shouldn't the colour be consistent regardless of it's location / usage

**Comment by Smurf-IV** [comment]
It appears that some themes are "Not good" with their colours in menus:
This is the expectation:
![image](https://user-images.githubusercontent.com/2418812/151696380-3275f4bb-007c-418e-832a-638df1440417.png)
Notice that the Radio and checkboxes are visible.

But if switching to the Dark version, it can be seen that the menu is still displayed in "white", but some of the text is also white:
![image](https://user-images.githubusercontent.com/2418812/151696450-46be0e43-e533-41c1-949e-a7f17ecfe92c.png)

It gets worse with the "Black Dark mode", where the expectation is for everything to be dark:
![image](https://user-images.githubusercontent.com/2418812/151696570-3055f64f-a8c1-40b2-9385-cc2063a69ad7.png)
But the background is white, therefore the text does not show up.

Some themes just do not work in menus, i.e. black should be "dark backgrounds" (Like the panels() and then a dark menu; Not this:
![image](https://user-images.githubusercontent.com/2418812/151696876-86edf0f3-6989-4440-ac50-a19cffd7197f.png)

But this is correct ;-) (Just that the calendar text needs sorting)
![image](https://user-images.githubusercontent.com/2418812/151696999-e459cc57-c1d1-42d8-940b-5d9c99f83bad.png)


The "Sparkle Themes" need a darker background to the menu (Bit like vis studio does), and also sort out the colours for the radio and checkboxes:
![image](https://user-images.githubusercontent.com/2418812/151696983-f0bc444f-7e9c-4dde-9cfa-cc7126a3a848.png)

@Wagnerp I think this needs to be an update to the themes, and possibly the theme generator app to include the menue test as per the sample app. Thought ?

**Comment by Wagnerp** [comment]
> I think this needs to be an update to the themes, and possibly the theme generator app to include the menue test as per the sample app. Thought ?

@Smurf-IV I agree, as looking at the code, ```cs Color.FromArgb( 70,  70,  70),    // TextButtonNormal (White)`` controls everything, not just the button text!

**Comment by Smurf-IV** [comment]
> looking at the code,
> ```cs
>          Color.FromArgb( 70,  70,  70),    // TextButtonNormal (White)
> ```
> controls everything, not just the button text!

So what actions are coming from this ?
Currently the list is:
- Change backgrounds of menus to reflect themes intentions and closely represent the colour used by the panel (Client) but lighter as per other apps (e.g. studio / word)
- Update Theme generator app to include All menu item types as per the above demo app, **and** also include disabled states of each type

And possibly (May not be necessary if the background is corrected)
- Add another colour control for checkbox / radio controls

**Comment by Wagnerp** [comment]
@Smurf-IV I did start to diagnose what each colour does in `PaletteOffice365BlackDarkMode` maybe that can help?

**Comment by Smurf-IV** [comment]
- https://github.com/Krypton-Suite/Theme-Palettes/issues/19 : [Enhancement] When changing the "BasePaletteMode", then the panel the objects are on should also change
- https://github.com/Krypton-Suite/Theme-Palettes/issues/20 : [Feature Request] Add menu displays to be able to "see" what is happening in the theme

**Comment by Smurf-IV** [comment]
With the new designer it is now possible to see the outcome of modifying colours:
![image](https://user-images.githubusercontent.com/2418812/152647665-f5a70442-7296-4a48-9d85-a155d47abcc2.png)

**Comment by Wagnerp** [comment]
@giduac & @Smurf-IV Getting somewhere...

![image](https://user-images.githubusercontent.com/949607/152679686-869a4095-b327-43f0-8a59-eccc23700410.png)

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac Do we know what `MenuStrip` menus are labelled under?

**Comment by Wagnerp** [comment]
@Smurf-IV Can I add new `SchemeOfficeColors` entries to identify menu objects more easily?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Can I add new `SchemeOfficeColors` entries to identify menu objects more easily?

Go ahead, not sure the themes need to be backward compatible with all these changes going in, so it might be a push to have a do-over for V 6.5 ?

**Comment by Wagnerp** [comment]
> > @Smurf-IV Can I add new `SchemeOfficeColors` entries to identify menu objects more easily?
> 
> Go ahead, not sure the themes need to be backward compatible with all these changes going in, so it might be a push to have a do-over for V 6.5 ?

@Smurf-IV Or a thing for V7? The good news is that this enum is labelled as `internal`, so it should not affect the client side. While I'm at it, I might rename it to `SchemeBaseColours` as there is a separate one for ribbons, buttons etc.

**Comment by Smurf-IV** [comment]
All because it is internal, does not stop it from being serialised out via text......

**Comment by Wagnerp** [comment]
@Smurf-IV Found the menu colours, we have 2 options:

A) Collapse 2 individual files into 1 file per theme
B) Create multiple files per theme

Which do you want me to undertake?

**Comment by Smurf-IV** [comment]
Option A please.. Lets try and keep this mess in a single location ;-)

**Comment by Wagnerp** [comment]
> Option A please.. Lets try and keep this mess in a single location ;-)

I agree!

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac 

A little update... (.39)

![image](https://user-images.githubusercontent.com/949607/152953001-8722d4f0-b4c2-4a10-9eb1-aea19d7533d5.png)

Still need to find the margin though

**Comment by Wagnerp** [comment]
Calendar day colours are now correct...

![image](https://user-images.githubusercontent.com/949607/153200483-8ba151f3-2038-4846-8de1-597e01c884b0.png)

**Comment by Smurf-IV** [comment]
> Calendar day colours are now correct...

Don't forget the "Disabled" option colours as well.

**Comment by Wagnerp** [comment]
> > Calendar day colours are now correct...
> 
> Don't forget the "Disabled" option colours as well.

Working on that today :)

**Comment by Wagnerp** [comment]
I've started again, as it was starting to get messy

**Comment by Wagnerp** [comment]
@giduac & @Smurf-IV 

Can you please test and give feedback on `Office 2007 - Black (Dark Mode)` > .41 please?

**Comment by giduac** [comment]
My findings (@Wagnerp):

The controls in the context-menu and the context-menu itself should be formatted in the same way as their stand-alone equivalents. This makes the interface / theme more uniform and consistent to work with.

Combo box, the text is not readable (think that was fixed before)
The combo box list might be formatted the same as the dropdown menu

The standalone calendar could do with a bit more contrasting colours in the header and footer bar.

![image](https://user-images.githubusercontent.com/96108132/153706908-ca771b1b-fbd8-4088-91fe-f70ba817fc9b.png)

**Comment by Wagnerp** [comment]
> My findings (@Wagnerp):
> 
> The controls in the context-menu and the context-menu itself should be formatted in the same way as their stand-alone equivalents. This makes the interface / theme more uniform and consistent to work with.
> 
> Combo box, the text is not readable (think that was fixed before) The combo box list might be formatted the same as the dropdown menu
> 
> The standalone calendar could do with a bit more contrasting colours in the header and footer bar.
> 
> ![image](https://user-images.githubusercontent.com/96108132/153706908-ca771b1b-fbd8-4088-91fe-f70ba817fc9b.png)

Hi @giduac 

Thanks for the feedback, I've done more work on it today. The calendar is a tricky one, as it seems that the day normal/disabled colour are the same, but I need help tracking this bug down.

**Comment by giduac** [comment]
@Wagnerp 
Is there a standard guideline you use to work with/edit themes in general?

**Comment by Wagnerp** [comment]
Hey @Smurf-IV & @giduac 

Just updated it to use the current Office 2021 dark theme colours, and it's near perfect!

![image](https://user-images.githubusercontent.com/949607/153747955-dc582273-e3d0-47a9-b096-b52ce8015f6c.png)

As a mention to @Smurf-IV I think there's a bug with KForm opacity

**Comment by Smurf-IV** [comment]
Opacity appears fine with the current alpha?
![image](https://user-images.githubusercontent.com/2418812/153749056-65865739-77c2-4e9d-8fe0-17cb084c737b.png)

**Comment by giduac** [comment]
Hi @Wagnerp ,

I've had a further look into this and seems like this is becoming a very good dark theme. I think documenting / keeping track what has been done could prove valuable and time-saving in future theme related work. 

I will look at other controls later on. Here's what I found until now.

Standard Calendar:
	Uses the same selector on dates that belong to the selected month as well as on those that not (are grayed) when the 
	mouse is moves over a date

KPropertyGrid
	(In categorized mode)
	Arrows to Collapse/Expand a group is not visible (might be white)

Listbox / CheckListbox / Combobox

Breadcrumbs dropdown
	If this is derived from the standard dropdown menu or other menu type formatting could be left to the 
	base control which is probably already themed correctly. Will give back the same selector, etc. which is probably already 	
	themed correctly.
	
Scrollbars
	Is it possible to theme those.
	
Standard selector (when the mouse moves over an item in a list (listbox, checkedlist, combobox,etc)
	The selector used on the menus would be better IMO...

**Comment by Wagnerp** [comment]
Hi @giduac 

Done some further modifications today in relation to grids & disabled controls. The KPropertyGrid & Scrollbars can't be done until #632. Still working on the calendars & selectors.

**Comment by giduac** [comment]
Hi @Wagnerp,

I found some time to look into the Office2007BlackDarkMode theme.
Here's what I found so far.

**Selector:**
- Selector in combobox and listbox types alike: the gradient interferes with the text readability.
- Imo the selector from the menustrip is more. Or use a slightly darker color for the gradient top 	colour.

**All Button types:**
- The gradient interferes with the text readability. Same as the above mentioned selectors.

**Combobox:**
- Disabled state possibly too light 

**Overall**
- Disabled state of controls might be more consistent if there’s a uniform/standard display of that among all controls.
- If a listbox/combobox (and possibly more controls) is disabled it’s actually more or less highlighted instead “pushed” to the background.

KPropertygrid (for now)
- Expanding and collapsing arrows not visible

MonthCalendar based controls (see video):
The days that do not belong to the month (those are grayed) do not get the highlight like the days from the month.
In the video the left calendar is the standard one which does highlight.

Back with more later on.
Cheers,

https://user-images.githubusercontent.com/96108132/157229171-db2ed10d-8093-4db6-a4d2-2fd43637c454.mp4

**Comment by Wagnerp** [comment]
Hi @giduac 

Thanks for the feedback. Most points can be easily addressed, however the KPropertyGrid may have to wait until #632 has been addressed.

**Comment by giduac** [comment]
> Hi @giduac
> 
> Thanks for the feedback. Most points can be easily addressed, however the KPropertyGrid may have to wait until #632 has been addressed.

This is a workaround to make the category arrow visible:
```cs
KryptonPropertyGrid.LineColor = Color.Silver;
```

**Comment by Wagnerp** [comment]
Hi @giduac 

> The KryptonScrollBar (in the toolbox) is already themed. Can this be used as the default scrollbar for all krypton components ???

Unfortunately, MS does not allow us to use a custom scrollbar yet, however I did raise a feature request

**Comment by Wagnerp** [comment]
Think the buttons have been toned down

![Office2k7BlckDM](https://user-images.githubusercontent.com/949607/157436408-a11f32ed-df27-4510-885a-fa1df5bdff39.gif)

**Comment by giduac** [comment]
Hi @Wagnerp 

In reaction to the above.

**Overall** 
If a gradient is used in a control, the text colour should contrast well with all colours that are used in the gradient on separate basis. To avoid a kind of transparency effect which makes part of the 	text getting lost in the background because the colours are the same.

**Disabled state**
- Text not readable.
- Might try a darker shade of grey for the background
- If the disable state of an item will have a lighter color, black or dark grey can be more contrasting for the text.

**Colours of the Button Normal and Pressed states could be switched**
- That would make the normal state more clearly to read. 
	
**If the buttons are made more readable**
- The selectors will need adapting too. Those look the same as the button normal state.

**A last question:** 
- Where can I find this program you are using for testing themes, like in the button video posted above?

**Comment by Wagnerp** [comment]
Hi @giduac 

> * Where can I find this program you are using for testing themes, like in the button video posted above?

You can find it here https://github.com/Krypton-Suite/Theme-Palettes, **but** you'll have to build it from source

**Comment by giduac** [comment]
@Wagnerp 
I think white text is OK. Maybe go with a somewhat darker grey in the top of the gradient. Take some more of the white out.

**Comment by giduac** [comment]
Hi @Wagnerp,

For me the Buttons Alternate style has a better contrast for the text.
I think Standalone & Alternate could be swapped ?
	
Could the Alternate colors be used as the base for some other controls/selectors ?
	
The alternate disabled style might be better for some controls' disabled state

![image](https://user-images.githubusercontent.com/96108132/159447686-1b4cdbdc-0eec-4995-812a-afc4e0927235.png)

**Comment by Wagnerp** [comment]
> Hi @Wagnerp,
> 
> For me the Buttons Alternate style has a better contrast for the text. I think Standalone & Alternate could be swapped ?
> 
> Could the Alternate colors be used as the base for some other controls/selectors ?
> 
> The alternate disabled style might be better for some controls' disabled state
> 
> ![image](https://user-images.githubusercontent.com/96108132/159447686-1b4cdbdc-0eec-4995-812a-afc4e0927235.png)

The problem with swapping Standalone & Alternate is that it'll affect all themes, as the change would need to be done on a control level. I'm not sure if there's a tweak that could be done in the theme itself?

**Comment by giduac** [comment]
Still getting used to how all of it works.... :)

Here's another one

KDataGridView selector
The current makes the text unreadable. 
Can this be made to look like the other selectors for lists?

**Comment by Wagnerp** [comment]
> 

Can you post a screenshot?

**Comment by Wagnerp** [comment]
> ![image](https://user-images.githubusercontent.com/96108132/159716037-c03efd96-c281-4139-b0f2-2bb0eb1a9291.png)

Next update... focusing on KMessageBoxExtended, for now...

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/161126473-9da7a9a5-8207-4d2a-9c58-01f67def0ffb.png)

![image](https://user-images.githubusercontent.com/949607/161126591-00414c04-e2bb-4a7b-8c02-148e1f6a0a03.png)

![image](https://user-images.githubusercontent.com/949607/161126698-13170d2b-0117-46fc-8fcb-580fc6e75a31.png)

**Comment by giduac** [comment]
Hi @Wagnerp 
Looks good ....
