### ISSUE TITLE
[Discussion]: Global Blur Values

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#61]
Global blur values for `KryptonForm`.

A `KryptonMessageBox` could theoretically be based on a new `KryptonPopupForm` with blur features disabled

**Comment by Smurf-IV** [comment]
What if the Pop-up then display a MessageBox.. 
This gets all a bit tangled !

**Comment by Wagnerp** [comment]
The `KryptonPopupForm` could be declared as 'internal' so you can't access it outside the codebase

**Comment by Smurf-IV** [comment]
Is this still needed ?
Windows 10 design criteria onwards do not seem to have "blurring"

**Comment by Wagnerp** [comment]
No, though could the blurring features be carried over to the extended toolkit as an optional feature?

**Comment by Smurf-IV** [comment]
They have been part of the Standard kit for a while, so this would be a breaking change ! 
Best leave for V7.x if it is ever going to happen.

**Comment by Smurf-IV** [comment]
@Wagnerp I vote to just leave them as they are. and close this as a `won't fix`

**Comment by Wagnerp** [comment]
> @Wagnerp I vote to just leave them as they are. and close this as a `won't fix`

Yes, think this was opened before the feature was changed.
