### ISSUE TITLE
[Bug]: Toolkit 6.2111.312.0 - 

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#616]
Krypton Groupbox (On the left & in the middle) with rounded border = OK
Krypton Header Group (On the right) with rounded border = Not OK
The border of the Header Group is still being drawing at 90 degress, not radiused

![image](https://user-images.githubusercontent.com/84494183/151567482-23934da3-33f4-4389-8913-7b5923c2e155.png)

**Comment by Smurf-IV** [comment]
@MattH-Work Can this replicated in the samples ?
Or can you supply a working example of what you see.

FYI: There have been fixes in the ribbon area to deal with scaling and form sizing in `highdpi` scenarios, are you in one of those (i.e. greater than 1080p and or with scaling either in Visual studio or on the target environment)

**Comment by MattH-Work** [comment]
Solved it (my bad)

Its a combination of 

KryptonHeaderGroup.StateCommon.Border.Rounding = 5

KryptonHeaderGroup.StateCommon.HeaderPrimary.Border.Rounding

KryptonHeaderGroup.StateCommon.HeaderPrimary.Border.DrawBorders = CType(((Krypton.Toolkit.PaletteDrawBorders.Top Or Krypton.Toolkit.PaletteDrawBorders.Left) Or Krypton.Toolkit.PaletteDrawBorders.Right), Krypton.Toolkit.PaletteDrawBorders)

Seems the StateCommon.HeaderPrimary.Border sits ontop of the StateCommon.Border.Rounding, I had only set one without setting the other
