### ISSUE TITLE
[Bug]: KButton and KListbox unclear text color in certain scenarios

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#619]
**Describe the bug**
365 black dark mode
	When the button has the focus the text is unclear.

2007 black dark mode 
	list box entries not readable

**To Reproduce**
See sample program attached (needs fetching the Nuget package because of the upload limit) .

**Desktop (please complete the following information):**
 - W10 / .Net 4.80
 - Version: 60.22.1.22-alpha / 60.22.1.30-alpha / 60.22.1.29-beta

**Additional context**
The sample prog changes the theme on double click and gives focus to Kbutton1
[KThemesTest.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7965809/KThemesTest.zip)

**Comment by Smurf-IV** [comment]
Once the following is sorted then these things will be easier to "spot":
- https://github.com/Krypton-Suite/Theme-Palettes/issues/19

**Comment by Smurf-IV** [comment]
Also Applicable to :
2k7 - Blue dark:
![image](https://user-images.githubusercontent.com/2418812/152644107-3e58926a-fd05-45d0-8ea7-e580b46ea142.png)

2k7 - Black dark
![image](https://user-images.githubusercontent.com/2418812/152644137-69f992e7-dae8-47a0-9ffa-425dbd6950df.png)

Sparkle (Dark modes) do not alter the list backdrops ??

**Comment by Wagnerp** [comment]
According to PowerToys Color Picker, the 'disabled text' colour is 92, 92, 92 for a Office 365/2021 theme

**Comment by Smurf-IV** [comment]
So, could the "Dark modes" be retired ?

**Comment by Wagnerp** [comment]
> So, could the "Dark modes" be retired ?

That's only for 'Black', need to check the 'White' theme.

**Comment by Wagnerp** [comment]
Plus, the ribbon area is another colour

![image](https://user-images.githubusercontent.com/949607/152650566-7daad041-a3f9-4913-a891-7520e8c2477f.png)

![image](https://user-images.githubusercontent.com/949607/152650626-cd024601-12a5-41ba-8bdb-86dd59d2fa6f.png)

![image](https://user-images.githubusercontent.com/949607/152650653-062f3c11-7fec-4818-8fc4-ade2767c66de.png)

![image](https://user-images.githubusercontent.com/949607/152650699-41ec9f90-57cb-4a79-994d-90c2317d288f.png)

**Comment by Wagnerp** [comment]
Linked to #609

**Comment by Smurf-IV** [comment]
@giduac Why was this closed ? 
@Wagnerp  I do not see a resolution ?

**Comment by giduac** [comment]
@Smurf-IV @Wagnerp,

This was included In all the work @Wagnerp has been doing on the themes.

Cheers,

**Comment by Wagnerp** [comment]
@Smurf-IV 

Working on it in `version-next`

**Comment by giduac** [comment]
@Wagnerp,

Can this be closed?

**Comment by Wagnerp** [comment]
> @Wagnerp,
> 
> Can this be closed?

@giduac Needs verification first

**Comment by giduac** [comment]
@Wagnerp 

Imo, this then needs attention to become completed...

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Imo, this then needs attention to become completed...

@giduac & @Smurf-IV I'm going to make the text colour for **all** black dark modes white. Thoughts?

**Comment by giduac** [comment]
@Wagnerp 
Can you post some samples of how that is going to look?

**Comment by Wagnerp** [comment]
> @Wagnerp Can you post some samples of how that is going to look?

@giduac Will do, going to be out today, but will start work on it tomorrow

**Comment by Wagnerp** [comment]
@giduac Think I've found the right colours for black - dark modes

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/4d51a353-e9d0-4060-b24b-0dacf59efcf6)

**Comment by giduac** [comment]
If you use the same disabled colors as the fourth listbox for all items (controls) that are disabled ??
Like the button above it.

That gives the user the same experience when something is disabled. That makes it easier to use. And easier to setup the theme as there is only one disabled state....

Nielssen are people that have lots of experience in usability (studies). You might find some of their reads interesting.
https://www.nielsen.com/

**Comment by Wagnerp** [comment]
> If you use the same disabled colors as the fourth listbox for all items (controls) that are disabled ?? Like the button above it.
> 
> That gives the user the same experience when something is disabled. That makes it easier to use. And easier to setup the theme as there is only one disabled state....
> 
> Nielssen are people that have lots of experience in usability (studies). You might find some of their reads interesting. https://www.nielsen.com/

@giduac Updated the test app

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/516e266d-4255-45ca-9893-ded0666eca8b)

**Comment by Wagnerp** [comment]
@giduac & @Smurf-IV 

This is better...

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/6dee2f51-9069-4824-95c5-be6413a9e52f)

You can play around with it in the [619-bug-kbutton-and-klistbox-unclear-text-color-in-certain-scenarios-v85](https://github.com/Krypton-Suite/Standard-Toolkit/tree/619-bug-kbutton-and-klistbox-unclear-text-color-in-certain-scenarios-v85) branch

**Comment by giduac** [comment]
Think mouse over / control up / down .....

**Comment by Wagnerp** [comment]
> Think mouse over / control up / down .....

Hi @giduac 

Do you mean the tracking colours? If so what should change, i.e. lighter or darker?

What do you think @Smurf-IV?

**Comment by giduac** [comment]
> Think mouse over / control up / down .....

No, I was hinting at the concept behind the choice of having a single display mode for a certain state.

Another application of this:
What happens when you press CTRL+P in: notepad, Word, Outlook, Chrome, FFox.....

**Comment by Wagnerp** [comment]
> > Think mouse over / control up / down .....
> 
> No, I was hinting at the concept behind the choice of having a single display mode for a certain state.
> 
> Another application of this: What happens when you press CTRL+P in: notepad, Word, Outlook, Chrome, FFox.....

Hi @giduac 

Could you provide a screenshot(s) please?

**Comment by giduac** [comment]
> > > Think mouse over / control up / down .....
> > 
> > 
> > No, I was hinting at the concept behind the choice of having a single display mode for a certain state.
> > Another application of this: What happens when you press CTRL+P in: notepad, Word, Outlook, Chrome, FFox.....
> 
> Hi @giduac
> 
> Could you provide a screenshot(s) please?

There's no screenshot. It's just about a conceptual way to bring consistency to a situation.
Do a bit of reading on this on the Nielsen site.

**Comment by Wagnerp** [comment]
> > > > Think mouse over / control up / down .....
> > > 
> > > 
> > > No, I was hinting at the concept behind the choice of having a single display mode for a certain state.
> > > Another application of this: What happens when you press CTRL+P in: notepad, Word, Outlook, Chrome, FFox.....
> > 
> > 
> > Hi @giduac
> > Could you provide a screenshot(s) please?
> 
> There's no screenshot. It's just about a conceptual way to bring consistency to a situation. Do a bit of reading on this on the Nielsen site.

Might be a new feature request if it does not exist yet

**Comment by Smurf-IV** [comment]
> > Think mouse over / control up / down .....
> 
> Hi @giduac
> 
> Do you mean the tracking colours? If so what should change, i.e. lighter or darker?
> 
> What do you think @Smurf-IV?

Tracking: Think glow / "lighten + border" with with a different hue This is then applied to all themes i.e. blue has lighter blue / green tinge.
But don't ask me to confirm because I'm partially colour blind :-)

**Comment by Wagnerp** [comment]
> > > Think mouse over / control up / down .....
> > 
> > 
> > Hi @giduac
> > Do you mean the tracking colours? If so what should change, i.e. lighter or darker?
> > What do you think @Smurf-IV?
> 
> Tracking: Think glow / "lighten + border" with with a different hue This is then applied to all themes i.e. blue has lighter blue / green tinge. But don't ask me to confirm because I'm partially colour blind :-)

@Smurf-IV & @giduac 

Suggestion, open a new feature/bug request to deal with tracking colours?
