### ISSUE TITLE
[Bug]: Krypton Toolkit 60.22.2.32 - ButtonSpec Images

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#623]
Squished images in Buttonspecs
Button height has changed, therefore image is 'stretching' to suit

6.2111.312 (Good)
![image](https://user-images.githubusercontent.com/84494183/151996672-53633493-ddd0-4ac6-9a08-0f7f9e0a6eb8.png)
![image](https://user-images.githubusercontent.com/84494183/151998144-e190ffce-1a62-4f2b-83c7-52e1ae0a07fb.png)

60.22.2.32 (Bad)
![image](https://user-images.githubusercontent.com/84494183/151996777-8b6eaca8-6348-422f-ae81-a8bec9d3c331.png)
![image](https://user-images.githubusercontent.com/84494183/151998178-d0b1d90f-cc48-4062-917e-d62c1e91c075.png)

**Comment by MattH-Work** [comment]
In Comboxes, the drop down 'button' has been centred (notice the slight reduction in white space under the drop down)
But this then changes the height of the control, which intern changes the height of the Buttonspec & image, and also changes the image due to the vertical compression

6.2111.312
![image](https://user-images.githubusercontent.com/84494183/151999406-3688089d-f0fe-49b6-8929-649390ffe496.png)

60.22.2.32
![image](https://user-images.githubusercontent.com/84494183/151999264-46098cdb-4c37-4ab3-81d5-015423e65705.png)

**Comment by MattH-Work** [comment]
Tying in with issue #615, the height of my Comboboxes have now reduced to 20 pixels, compared to the original 22


![image](https://user-images.githubusercontent.com/84494183/152004643-5a19785b-90f0-4ba8-afa9-417b7fbe9a1a.png)
![image](https://user-images.githubusercontent.com/84494183/152004696-b8c41078-c06b-411b-b463-ee24de4b1cd2.png)


Not much, but when there is a mix of heights bewtweeen all the different controls on my form (99% of which are Krypton.Toolkit) the OCD is firing left right & centre
![image](https://user-images.githubusercontent.com/84494183/152005607-4ed442c2-2d7e-42f9-a3d7-b12bc1ca8e1d.png)

**Comment by Smurf-IV** [comment]
> Tying in with issue #615, the height of my Comboboxes have now reduced to 20 pixels, compared to the original 22

Bit confused... #615 has had nothing done for it yet, so what reduced the size down to 20 ?

**Comment by Smurf-IV** [comment]
> In Comboxes, the drop down 'button' has been centred (notice the slight reduction in white space under the drop down) But this then changes the height of the control, which intern changes the height of the Buttonspec & image, and also changes the image due to the vertical compression

@MattH-Work 
_re: vertical compression:_ This may be sorted by the changes made to sort out that artefact in #603.
Please use a build after todays build date and re-test
Also, can you supply an example app that shows your rounding, and images in situ please ?

**Comment by MattH-Work** [comment]
![image](https://user-images.githubusercontent.com/84494183/152758788-31c13fdf-cab5-45bf-a63d-729c2248020f.png)
 Two combo boxes, one with 0 (-1) rounding radius & one with a radius of 5
Two panels, showing the iconds as expected (magnifying glass is 17x17, eye is 16x16)
As you can see, the vertical height is compressed
[ButtonSpecTest.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/8013895/ButtonSpecTest.zip)

**Comment by MattH-Work** [comment]
![image](https://user-images.githubusercontent.com/84494183/152767069-e439e503-c8a6-4c96-afcf-2221343f9a1a.png)

This is the same form updated to Krypton.Toolkit.Nightly 60.22.2.38-alpha (seems 'something' has reverted back to a previopus setting)

The icons now display correctly, BUT...
a) The Buttonspec position have reset to 'Far' for both (this can be fixed by me, so just an observation)
b)  Image Style has reset to 'Inherit' for both panels (were set to 'Center - Middle', again, this can be fixed by me, so just an observation)
c) The 'centred' drop down button now has more pixels below than above (a price I'm prepaped to pay for the improved icon display)
d) The overall height of the Comboboxes has increased (21 upto 23 & 25 upto 27). Is there a border/margin around the ButtonSpec / ButtonSpec image that can be tweaked rather than the overall height of the combo, I rather liked to clean 25 height! 

Edit.  The above observations actually just match the Buttonspec behaviour prior to the problem appearing in the February stable build, so it's actually just back to how it always was, so there's an agument to say nothing has changed, just a regression fixed.

**Comment by Smurf-IV** [comment]
> This is the same form updated to Krypton.Toolkit.Nightly 60.22.2.38-alpha (seems 'something' has reverted back to a previous setting)

Yes, that would be the fix for #603.

> 
> The icons now display correctly, BUT... 
> a) The Buttonspec position have reset to 'Far' for both (this can be fixed by me, so just an observation) 

Not sure what has happened there, as that will be a designer thing, and should have taken the value that you set.

> b) Image Style has reset to 'Inherit' for both panels (were set to 'Center - Middle', again, this can be fixed by me, so just an observation) 

Not sure what has happened there, as that will be a designer thing, and should have taken the value that you set.

> c) The 'centred' drop down button now has more pixels below than above (a price I'm prepaped to pay for the improved icon display) 

The min height has had to be restored to the original calc, and doe snot "Know" about the actual size until after the "Prefered size" has been calculated. Youmight be able to fix this by augmenting the "GetPreferredSize" API, and setting it to a hard coded value ( - just an idea, not sure how to accomplish without trying it, which I cannot at the moment!)

d) The overall height of the Comboboxes has increased (21 upto 23 & 25 upto 27). Is there a border/margin around the ButtonSpec / ButtonSpec image that can be tweaked rather than the overall height of the combo, I rather liked to clean 25 height!

See anser to c)

> Edit. The above observations actually just match the Buttonspec behaviour prior to the problem appearing in the February stable build, so it's actually just back to how it always was, so there's an agument to say nothing has changed, just a regression fixed.

Not quite, the icons now scale to whatever windows screen preference scaling the user has set when the application starts, please see the images during the investigation of #603

**Comment by Smurf-IV** [comment]
@MattH-Work Can this be closed now ?

**Comment by MattH-Work** [comment]
Yes, please close this.
I am happy to wait until the nightly build filters down to Stable (March / April?)

**Comment by Smurf-IV** [comment]
> Yes, please close this. I am happy to wait until the nightly build filters down to Stable (March / April?)

I think these recent changes are targeted for April

**Comment by MattH-Work** [comment]
Using 65.22.6.152 this issue has re-appeared

This 'eyeball' (from a combobox buttonspec)
![image](https://user-images.githubusercontent.com/84494183/172430693-0603e26a-2081-4ab9-ad65-f487ebc36d53.png)

Should look like this 'eyeball' (from a command button)
![image](https://user-images.githubusercontent.com/84494183/172430771-8d61e873-09ed-4361-a30c-779a37dd92b1.png)

Same vertical compression on all ButtonSpecs images
![image](https://user-images.githubusercontent.com/84494183/172431404-f66f8881-a6fb-4e57-9564-5b2280f059f8.png)

**Comment by Smurf-IV** [comment]
@MattH-Work Please create a new Linked bug, and state what OS and TFM you are using (I have a feeling that .net6 introduced a bigger margin for buttons, etc!!)
