### ISSUE TITLE
[Feature Request]: `KryptonPropertyGrid` should have a customisable back colour

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#632]
The `KryptonPropertyGrid` should have a customisable back colour instead of always having white

**Comment by Wagnerp** [comment]
@Smurf-IV I'm not sure if the `KryptonPropertyGrid` is using Krypton correctly, i.e. `StateCommon` etc options?

**Comment by Smurf-IV** [comment]
It doesn't. It uses the Panel background colour associated with the theme:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/a551e31f-006b-4b12-b94c-4558b54760f9)

**Comment by Smurf-IV** [comment]
@Wagnerp This is going to be a breaking change.
But: It will be more of a "1st class wrapped" control than the _hack_ it is now ;-)

**Comment by Smurf-IV** [comment]
This @ runtime with O2k7 BVlue Dark:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c10c3003-0500-4958-98b8-45b0179811b6)

And the designer set as:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/f8da5b59-f32f-488e-99eb-8724a7199320)

Bit more testing to do
