### ISSUE TITLE
[Other Issues]: Source contains licensing code

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#633]
Hi there,

I came, by accident, across some code that probably was used for licensed features in the original product from Component Factory.
It might be useful to remove this redundant code since there's no use for it currently.

Searched "EncryptedLicenseProvider" in *.cs files
```
-   Standard-Toolkit-alpha\Source\Krypton Components\Krypton.Ribbon\View Layout Demo\ViewLayoutRibbonAppButton.cs
	Line 130:             EncryptedLicenseProvider.SetParameters(_licenseParameters);
-   Standard-Toolkit-alpha\Source\Krypton Components\Krypton.Ribbon\View Layout Demo\ViewLayoutRibbonAppTab.cs
 	Line 89:             EncryptedLicenseProvider.SetParameters(_licenseParameters);
-   Standard-Toolkit-alpha\Source\Krypton Components\Krypton.Workspace\Palette Demo\WorkspacePageMenuBase.cs
 	Line 40:             EncryptedLicenseProvider.SetParameters(_licenseParameters);
```

Cheers,

**Comment by Wagnerp** [comment]
@Smurf-IV Are these all in the demo repo?

**Comment by giduac** [comment]
Also found (just looked) in the master repo

**Comment by Smurf-IV** [comment]
> @Smurf-IV Why are there is there a folder for a installer?

No idea, Are they in 4.80 ?

**Comment by Wagnerp** [comment]
@Smurf-IV Looks like these files are redundant if you look at them

**Comment by Wagnerp** [comment]
Resolved - 10/02/2022
