### ISSUE TITLE
[Bug]: Opacity no longer works (Nightly)

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#634]
The KryptonForm.Opacity property no longer works (Nightly 60.22.2.38). I tested a range of opacities from 0 to 90 percent without seeing an effect. Working on Windows 10 Winforms NET48.

@Wagnerp thinks it could be related to https://github.com/Krypton-Suite/Standard-Toolkit/pull/618.

**Comment by Smurf-IV** [comment]
Fixed: Parent set to 80% and has focus:
![image](https://user-images.githubusercontent.com/2418812/153705854-2c564a41-d4ee-43bf-b18e-9666cea90ec5.png)

**Comment by sdreb3421** [comment]
Just confirmed on my end, nice work.
