### ISSUE TITLE
[Bug]: KryptonContextMenu Designer has layout issues

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#64]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2418812/112803773-8f98fa80-906b-11eb-92e4-641da05d4ad2.png)

**To Reproduce**
Win 10 Pro
Visual Studio 16.9.2
Winform .net4.8 project

**Comment by Wagnerp** [comment]
Is that happening on a 4k display?

**Comment by Smurf-IV** [comment]
2160 (QHD)

**Comment by Wagnerp** [comment]
Need to test on my 43" UHD Display

**Comment by Wagnerp** [comment]
Its a 4k scaling issue, though I've got different results

**Comment by Smurf-IV** [comment]
Can you add a picture of the "4k results" please ?

**Comment by Wagnerp** [comment]
![Screenshot 2021-03-30 075329](https://user-images.githubusercontent.com/949607/112946322-49a46b00-912d-11eb-8633-1ef0997ee75c.png)

**Comment by Smurf-IV** [comment]
Sorted:
![image](https://user-images.githubusercontent.com/2418812/128608166-b518b023-a340-4fab-975a-66d3a2bfaeef.png)
