### ISSUE TITLE
[Feature Request]: KForm add an option to align the title text.

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#640]
**Is your feature request related to a problem? Please describe.**
Currently the title text in a KForm is always left aligned

**Describe the solution you'd like**
Add a (designer & runtime) property to KForm that makes it possible to align the title LEFT, CENTER or RIGHT
The alignment should be retained if the form-width changes.

**Describe alternatives you've considered**
N/A

**Additional context**
Edit:
A possible KForm standard that separates the title from the icon and lets title be left/center/right aligned.

For example center the Title:
Leave the system menu icon on it's default spot
add (left aligned) ButtonSpecs right next to the sysmenu icon

**Comment by Smurf-IV** [comment]
How about this:
![FormTitleAlign](https://user-images.githubusercontent.com/2418812/153759522-af8e3799-4204-4336-8135-7e4401f7753c.gif)

> add (left aligned) ButtonSpecs right next to the sysmenu icon

This will have to be a separate Feature request, as it _**may**_ be a big change
