### ISSUE TITLE
[Feature Request]: KForm add an option to align SpecButtons in the title bar

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#641]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently Specbuttons on a KForm are right aligned on the title bar.
Add a (designer & runtime) property to KForm/Specbuttons that makes it possible to align the buttons LEFT, CENTER or RIGHT

**Describe alternatives you've considered**
EDIT: Maybe an extra option to hide system menu (that's the one where the form icon is) to have the options to have Specbuttons fully left aligned. Leaves the question if the system menu remains accessible from the taskbar button associated with the program....??

**Additional context**
EDIT: (After @DarthVader85PA tip below )
Leaves the idea to hide the System Menu / place the specbutton right of the system menu....
As it seems the title is attached to the system menu. Probably the point why the ButtonSpecs are placed in front of it.

**Comment by DarthVader85PA** [comment]
Hey @giduac 

is there a property that contains options `Near` and `Far`? 
Most of Special-Buttons have this options. If you set `Far`, the Buttons are left... 

But no Center-Option is available. That's what I know.

Greetings...

**Comment by giduac** [comment]
> Hey @giduac
> 
> is there a property that contains options `Near` and `Far`? Most of Special-Buttons have this options. If you set `Far`, the Buttons are left...
> 
> But no Center-Option is available. That's what I know.
> 
> Greetings...

Thanks,
I found it. 
Updated the request text accordingly

![image](https://user-images.githubusercontent.com/96108132/153575659-284f8bd2-ee35-41f1-8de3-4284b6fc423b.png)

**Comment by giduac** [comment]
@Smurf-IV 
Not sure if that would make sense after all...??
Removing/hiding the system menu might be a good addition (which could be coupled with a centered/right aligned title.

On the other hand if something like a toolstrip could be added like discussed in the other thread. That would be a much more flexible solution. In that way it would come close to Visual Studio style tool bar.

...........

**Comment by giduac** [comment]
Just saw that when the ButtonSpecs are left aligned the System Menu icon does not react to the click event any more.
ALT+SPACE does popup the system menu though.

**Comment by giduac** [comment]
Possibly that controls like a tab control could be integrated like that

**Comment by Smurf-IV** [comment]
@giduac according to the title,  "this" is no longer needing development.
But, according to the comments a bug has been found with the "System menu" when left aligned buttonspecs are used.
