### ISSUE TITLE
[Bug/Question]: KryptonMessageBox cut New Lines?

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#652]
I don't know: I think it is already handled and closed?
But in my Version 60.22.2.32 of Krypton the `KryptonMessageBox` cut my Text after a new line?!

```
Dim frage_einfach As String = $"Es sind für '{Plz}' keine Ortsinformationen vorhanden."
Dim frage_dialog As String = frage_einfach & vbNewLine & "Möchten Sie diese nun anlegen?"

KryptonMessageBox.Show(frage_dialog, Objekte.AppTitel, MessageBoxButtons.YesNo, MessageBoxIcon.Question)
```
![grafik](https://user-images.githubusercontent.com/32876506/154052361-346b2f56-838c-4e7b-b742-1c828a0b51fe.png)

**Comment by giduac** [comment]
Seemed to be fixed....
https://github.com/Krypton-Suite/Standard-Toolkit/issues/607

**Comment by giduac** [comment]
@DarthVader85PA 

As a workaround you can add a "\n" (vbNewLine) before the message text and a "\n\n" at the end.
That should show the full string.

**Comment by giduac** [comment]
@Wagnerp @DarthVader85PA 
This fix  [https://github.com/Krypton-Suite/Standard-Toolkit/issues/607](https://github.com/Krypton-Suite/Standard-Toolkit/issues/607) is not included in: 60.22.2.32 

Canary: 60.22.2.36-beta and higher (including nightlies) do include the fix.
Can this be included in the next Stable release please ?

If you want to retain 60.22.2.32 the above workaround can be used.
Or try Canary 60.22.2.36-beta.

**Comment by Wagnerp** [comment]
> @Wagnerp @DarthVader85PA This fix #607 is not included in: 60.22.2.32 and master repo.
> 
> Canary: 60.22.2.36-beta and higher (including nightlies) do include the fix. Can this be included in the next Stable release please ?
> 
> If you want to retain 60.22.2.32 the above workaround can be used. Or try Canary 60.22.2.36-beta.

Hi @giduac 

Yes, it will be in the next stable release. The reason why #607 is not in .32 was due to the implementation and testing phase. Usually development on a stable release takes 2 - 3 months before rollout, hence why #607 is attached to the April 2022 milestone.

**Comment by giduac** [comment]
@Wagnerp 
This can be closed then...?

**Comment by Wagnerp** [comment]
> @Wagnerp This can be closed then...?

@giduac 

Yes it can :)
