### ISSUE TITLE
[Bug]: Krypton DomainUpDown control: Nearly impossible to place the cursor via the mouse

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#660]
**Describe the bug**
When moving the mouse pointer over a certain spot of the text inside the control and then click there to enter the control for editing
the cursor tends to jump al kind of locations. The standard DUD control does not have this behaviour.
[A similar issue was fixed for KNumericUpDown](https://github.com/Krypton-Suite/Standard-Toolkit/issues/37)

**To Reproduce**
1. Place KDUD control on the form
2. Add some items
3. When running it try to place the cursor and enter the control the exact position
-- See video

**Expected behavior**
Cursor should be positioned at the selected spot where than editing can begin.

**Desktop (please complete the following information):**
 - OS: 7-11
 - Version All Toolkit versions

https://user-images.githubusercontent.com/96108132/155970660-8911c97e-05e8-44e0-bf47-5feae8c94593.mp4

**Comment by Smurf-IV** [comment]
Done:
![DomainUDFixed](https://user-images.githubusercontent.com/2418812/173227029-2b62fbe3-864b-417a-a93c-73c5a2ddbda3.gif)

PR Coming
