### ISSUE TITLE
[Bug]: Can not "Control / Set Disabled" Background Colour Of Comboboxes, in `DropDown` mode

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#662]
![image](https://user-images.githubusercontent.com/84494183/156185082-7d45f7a8-40ba-4d24-9594-e383bec3969d.png)

All of the comboxes in the attached image are using the DropDownStyle "DropDownList" and behave as expected
I am overriding the Back colour for both StateCommon & StateDisabled to be LightYellow 

The Description combobox is using DropDownStyle "DropDown" and as you can see has the LightYellow backround (again I am overriding  both StateCommon & StateDisabled)  

BUT...

Where has the Grey box come from?
Is this a bug, or do I need to override soemthing else?

I find the same issue with any combobox using DropDownStyle "DropDown"

Note, the Groupbox that hosts all the controls is currently disabled (Enabled = False), when enabled ALL comboxes display as expected
![image](https://user-images.githubusercontent.com/84494183/156186184-bb6215bc-c8f6-4056-8d02-fe66b347fffc.png)

Cheers

MattH

**Comment by Smurf-IV** [comment]
Trying to remember of the top of my head, but when in "DropDown" then there is an edit component, therefore it will also need to be overridden.
If you can wait, I can check at the weekend.

**Comment by MattH-Work** [comment]
I can wait

Thanks for the help

**Comment by Smurf-IV** [comment]
Grey box is also being applied to the KRTF in the disabled state:
![image](https://user-images.githubusercontent.com/2418812/156877122-44037198-ec30-47ff-b3ed-f9d2895ece1d.png)

**Comment by Smurf-IV** [comment]
Hmm. I wonder..
https://stackoverflow.com/questions/1946139/how-to-change-the-background-color-of-a-rich-text-box-when-it-is-disabled

**Comment by Smurf-IV** [comment]
It gets worse..
![image](https://user-images.githubusercontent.com/2418812/156916180-3d406396-18c9-4da2-bda8-bc7889475643.png)

**Comment by Wagnerp** [comment]
@Smurf-IV This also applies to the `KryptonRichTextBox`

![image](https://user-images.githubusercontent.com/949607/161314140-b7c5f742-ed7e-4d21-9fcf-865f9e31b551.png)

**Comment by Smurf-IV** [comment]
> @Smurf-IV This also applies to the `KryptonRichTextBox`

Already displayed in the "green circles"

**Comment by Smurf-IV** [comment]
This is turning me in circles..
I think that each ToolBox Item should be separated into new issues; Then focus on each in turn. (It also means I can the restart the whole process !)

**Comment by Smurf-IV** [comment]
@MattH-Work @Wagnerp 
As you can see, I have refocused this item, and added 2 new ones for the other types that "Do not work"
I can now refocus and restart this with the Current Alpha codebase ;-)

**Comment by Smurf-IV** [comment]
Sorted:
![image](https://user-images.githubusercontent.com/2418812/171993700-83e0f328-a095-4e80-ac1e-807f0a0982f1.png)
PR coming soon.
