### ISSUE TITLE
[Feature Request]: `CueHint` features to be configured via the `KryptonPalette`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#669]
**Is your feature request related to a problem? Please describe.**
Can the `CueHint` features be configured via the `KryptonPalette`, i.e. colour and font?

**Comment by Smurf-IV** [comment]
Is #535 related to this ?

**Comment by Wagnerp** [comment]
> Is #535 related to this ?

See latest comment on #703

**Comment by Smurf-IV** [comment]
Seems to be a thing now:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/1ae291a8-9c3b-445c-87c0-a88a4144274a)
