### ISSUE TITLE
[Bug]: `KryptonRibbonGroup` does not have entries for either `StateContextPressed` or `StateContextTracking`

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#673]
**Describe the bug**
When the Ribbon page is active. 
And "Red Context" is clicked.
Palette designer crashed.

In the video it is shown how the Ribbon produces errors in the VS designer.

**To Reproduce**
See video and pictures 

**Desktop (please complete the following information):**
 - OS: W10
 - Build locally from master repos

**Error occurring in the designer** 
https://user-images.githubusercontent.com/96108132/158578440-1628fb0b-054a-46b6-b737-b2c7e044a7bb.mp4

**This is the error at runtime**
![4UjLb35fJa](https://user-images.githubusercontent.com/96108132/158577037-b44fe7c4-934c-489a-a58c-5fcf82ae8b25.png)

**Errors at design time taken while the video was recorded** 
![Ss3wS3J86o](https://user-images.githubusercontent.com/96108132/158577076-62d0a889-0649-4aaa-a864-bc203878c7e9.png)
![YLCq98JrUV](https://user-images.githubusercontent.com/96108132/158577079-99d2efc0-ed91-4231-be15-634c2f409e45.png)
![devenv_oK4rD9rn6c](https://user-images.githubusercontent.com/96108132/158577081-e3339f14-397e-4889-b720-7566246a79a2.png)
![Qf8sqE8uaP](https://user-images.githubusercontent.com/96108132/158577082-a7944c77-795c-439f-affc-2e62a3363953.png)
![RtbApjDg0W](https://user-images.githubusercontent.com/96108132/158577085-feff507f-68eb-4b91-ae20-fd062e0d40ac.png)

**Comment by Wagnerp** [comment]
Hi @giduac 

Please retry using `nightly` build >= .76

**Comment by giduac** [comment]
@Wagnerp 
Seems to be gone now....

**Comment by Wagnerp** [comment]
Resolved - 17/03/2022
