### ISSUE TITLE
[Bug]: Dropdown list background & text colour are the same (Office 2010 - Black (Dark Mode))

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#678]
**Describe the bug**
Theme: 2010 black dark mode
Combo-box dropdown list background & font have the same colour.

**Desktop (please complete the following information):**
 - Version TK 65.22.3.87-beta

**Comment by Wagnerp** [comment]
Hi @giduac 

Thanks for posting, could you re-test using `nightly` build >= .88 please?

**Comment by giduac** [comment]
@Wagnerp 

The above looks ok now.

The calendar needs a bit of work..

![image](https://user-images.githubusercontent.com/96108132/160618748-d8d1456b-8610-4376-bbf7-3140d06767fb.png)
