### ISSUE TITLE
[Other Issues]: KryptonComboBox item height

### ISSUE THREAD

**Issue by NintendoPlayer** [Krypton-Suite/Standard-Toolkit#685]
Hi!

I'm using an objectlistview and changing a cell for a KryptonComboBox when I try to edit.  I've made this with a KryptonTextBox and works well changing autosize to false.

The issue is that the ComboBox does not change its height.  This is the code

`KryptonComboBox kryptonComboBox = new KryptonComboBox();

kryptonComboBox.DrawMode = DrawMode.OwnerDrawVariable;
kryptonComboBox.Bounds = e.CellBounds;
kryptonComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
kryptonComboBox.ItemHeight = e.CellBounds.Height;
`
I also change the font accordingly to the objectlistview font.  Any idea?

Thank you!

**Comment by Smurf-IV** [comment]
Related ? #688

**Comment by Smurf-IV** [comment]
@NintendoPlayer What does `objectlistview ` do with a standard winform `comboBox` ?

**Comment by NintendoPlayer** [comment]
Hi @Smurf-IV !  Sorry for being late.

If I change the control to a Winform ComboBox, the size and family of the font changes and so does the height.  If I use a KryptonComboBox the size does not change and the font is the one selected on the designer.

**Comment by Smurf-IV** [comment]
Not sure you are setting the correct font..
This is what I get when I change the Font to be 48:
![image](https://user-images.githubusercontent.com/2418812/174306197-06f5a219-76cd-4bac-b3f9-6ac82e6194a2.png)

In the `*.designer.cs` it looks like this:
```
this.kryptonComboBox1.StateCommon.ComboBox.Content.Font = new System.Drawing.Font("Segoe UI", 48F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
```

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer 

cc. @Smurf-IV 

You can set the fonts on all applicable controls using the action lists, rather than trawling through the properties.
