### ISSUE TITLE
[Feature Request]: Extend ToolTipManager designer to also allow "open/close" interval properties.

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#686]
The ToolTipManager properties (open/close interval) are only available programatically. Should be in designer properties to match standard windows forms tooltips.

**Comment by Wagnerp** [comment]
@sdreb3421 Does this affect all controls?

@Smurf-IV I thought that something similar was already implemented?

**Comment by Smurf-IV** [comment]
> @sdreb3421 Does this affect all controls?

All controls that allow a KryptonToolTip will need to be updated.

> @Smurf-IV I thought that something similar was already implemented?

I have changed the title to reflect what is actually needed, as a KryptonToolTip should (At least) be in all Toolkit controls (May not be in all navigator / workspace / etc dlls tho !)

**Comment by Smurf-IV** [comment]
Winform Tooltip:
![image](https://user-images.githubusercontent.com/2418812/175817715-3274f533-188e-4a2f-8ed3-8e229b4a7a15.png)

Krypton is missing those values:
![image](https://user-images.githubusercontent.com/2418812/175817743-551daf8c-b4f3-452a-9c5f-7485e6da267e.png)

**Comment by sdreb3421** [comment]
Yeah, those values should be editable from somewhere.

**Comment by Smurf-IV** [comment]
Done:
![image](https://user-images.githubusercontent.com/2418812/222954249-67bea591-89d2-4a5d-81f1-12ff51224196.png)
