### ISSUE TITLE
[Feature Request]: Add TabMouseDown event to KryptonNavigator.

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#687]
It would be nice to be able to handle right click events for each KryptonNavigator tab. The existing TabClicked event is not fired for right clicks. The standard winforms tab control allows this via handling the mouse down event and calling the method TabControl.GetTabRect to check if the mouse is over any tab.

**Comment by Smurf-IV** [comment]
@sdreb3421 I am unable to reproduce:
![image](https://user-images.githubusercontent.com/2418812/173224130-d62b312b-86e0-4774-94b5-c49a7fc4aee3.png)

``` c#
        private void kryptonNavigator1_MouseClick(object sender, MouseEventArgs e)
        {
            AddOutput($"kryptonNavigator MouseClick  {e.Button}");
        }
```

**Comment by sdreb3421** [comment]
@Smurf-IV I would like an event to fire when clicking the tab portion only. The goal is to have a context menu when right clicking a tab. The regular mouse click event will fire anywhere on the navigator, not just the tab. Therefore I was using the tab clicked event. Is there something I'm confused about?

**Comment by Smurf-IV** [comment]
> I would like an event to fire when clicking the tab portion only. 

Is that the same as in Other Navigator implementations ?

Would it be better if the click event also included the tab id in some way ? (i.e. not just the default mousevent)

**Comment by sdreb3421** [comment]
Like i mentioned in the original post, the standard winforms tab control allows handling the mouse down event and calling the method TabControl.GetTabRect to check if the mouse is over any tab.

**Comment by Smurf-IV** [comment]
@sdreb3421 Ok, having taken a little time away and re-read this, I can see that there is "Almost" an API that you require:
![image](https://user-images.githubusercontent.com/2418812/179350377-a517cfc8-917c-4c0e-af78-e3a20e2ec3e1.png)

The `KryptonPageEventArgs` has the page Id - Yay.
BUT, the right click does not fire for this  - boo.

I think that this is the feature that you need ?
I.e. if Right click tab, then change etc, and also fire the `kryptonNavigator1_TabClicked MouseClick` when the right button is used.

**Comment by Smurf-IV** [comment]
Hold-Up....
There is already code to display a `KryptonContextMenu` on a tab right click...
![image](https://user-images.githubusercontent.com/2418812/179350581-20c1b4b8-805b-438e-a5e2-8d07f364d4d3.png)

Which by following the sample shown below allows a specific menu for a right click:
![image](https://user-images.githubusercontent.com/2418812/179350678-9e2ec432-701c-4f3f-a8ca-928ee3de7f91.png)

**Comment by sdreb3421** [comment]
Updated code on my end and confirmed. Thanks for pointing me in the right direction.
