### ISSUE TITLE
[Bug]: KryptonComboBox / KryptonNumericUpDown / KryptonDomainUpDown Anchor Sizing no as expected when anchored Top & Bottom

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#688]
When a KryptonComboBox is anchored on all four sides and its parent container size is reduced so that the combo box width is reduced below its minimum width, the combo box will be larger once the parent is re-expanded. This only occurs if adjusting the parent container height while the combo box is reduced below its minimum width.

This is an issue on the current and previous releases of Krypton. To reproduce, add a standard winforms combo box and a krypton combo box to a form. Anchor on all four sides and adjust the form size with the mouse ensuring to shrink the combo boxes until they cannot be seen. Only the krypton combo box size will be larger than the original size.

**Comment by giduac** [comment]
Hi,

I've been trying this.
The right side of the Kcombo becomes anchored beyond the right border of it's parent control.

There are two ways this occurs.
1. The way described by sdreb3421. After it occurs the width can be reset. And the error reproduced.

https://user-images.githubusercontent.com/96108132/165462959-dc45d36e-5a6d-4c8f-b0f5-ed0bf13b6225.mp4

2. Also occurs on window minimize/restore 

https://user-images.githubusercontent.com/96108132/165463099-cef53544-e045-4f6c-8850-369b185016e7.mp4

**Comment by Smurf-IV** [comment]
Workaround:
- It does not make sense to anchor height (Top & bottom) of a combo / Numeric / Domain / Single line edit box.

Yes this is a bug, not sure it's a must fix ?
I'll keep looking to see if there is something obvious !

**Comment by Smurf-IV** [comment]
![NumericEtc](https://user-images.githubusercontent.com/2418812/173179137-2610fd51-742b-4851-8221-70059374d740.gif)

Above shows that the fix for the KComboBox, also needs to be applied to the Numeric and Domain controls. Edit box is okay.

**Comment by Smurf-IV** [comment]
Fixed.. PR coming soon....
![NumericEtcFixed](https://user-images.githubusercontent.com/2418812/173179392-dfbec020-163d-4411-ae13-ec69abbab1a7.gif)
