### ISSUE TITLE
Update Project landing pages with links to Help file downloads.

### ISSUE THREAD

**Issue by bakerhillpins** [Krypton-Suite/Standard-Toolkit#691]
Currently the download link for the Standard-Toolkit API help.exe installer isn't posted on the [main page](https://github.com/Krypton-Suite/Standard-Toolkit) of the Standard-Toolkit project. This can make it difficult to locate information about the APIs and lead to unnecessary discussion in issues/discussion.

The main/landing page of the[ Help Files ](https://github.com/Krypton-Suite/Help-Files)project is also empty.

**Describe the solution you'd like:**
Having a[ link to the help file releases](https://github.com/Krypton-Suite/Help-Files/releases) co-located with the link to the [online help](https://github.com/Krypton-Suite/Standard-Toolkit#online-help) on the main page of the Standard-Toolkit project would probably be the best place for it, along with a note at the landing page of the [ Help Files ](https://github.com/Krypton-Suite/Help-Files)project

**Comment by Wagnerp** [comment]
Hi @bakerhillpins 

All feedback has been addressed (pending merging) ;)

**Comment by Wagnerp** [comment]
Implemented 09/04/2022
