### ISSUE TITLE
DateChanged-Event fired when selecting month in KryptonContextMenuMonthCalendar

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#7]
Is it possible that the Event DateChanged only fired, wenn closed the KryptonContextMenuMonthCalendar?

Thanks and best regards,
Danny

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

Looks like the event hasn't been setup yet. Which control is affected?

**Comment by DarthVader85PA** [comment]
Hi @Wagnerp 

I added a `KryptonContextMenuMonthCalendar`-Control into `KryptonContextMenuItems`-Collection with Visual Studio Designer:
![grafik](https://user-images.githubusercontent.com/32876506/80715768-1d383700-8af7-11ea-9120-36053e3a26bf.png)

In running App, when I change the month, a datechanged event is fired, but I not selected a new date. The MonthCalendar-Control is still opened.
![grafik](https://user-images.githubusercontent.com/32876506/80715930-596b9780-8af7-11ea-92ad-4d3735d74c8d.png)

The name of my `KryptonContextMenuMonthCalendar`-Control is **kcmCalReZeitraumTag**
And here my code for the event handle (event `DateChanged`):
```
Private Sub kcmCalReZeitraumTag_DateChanged(sender As Object, e As DateRangeEventArgs) Handles kcmCalReZeitraumTag.DateChanged
            If _loaded = False Then Exit Sub
            Me.kcmiReZeitraumJahr.Checked = False
            Me.kcmiReZeitraumMonat.Checked = False
            Me.kcmiReZeitraumTag.Checked = True
            Me.AendereRechnungenZeitraum("tag", e.Start)
End Sub
```
In DateChanged-Event Handle I call a method that reloads data from database with the selected day.

![grafik](https://user-images.githubusercontent.com/32876506/80716712-473e2900-8af8-11ea-9c9c-7da3dba2aa31.png)

Thanks a lot.
Danny

**Comment by Wagnerp** [comment]
Hi @DarthVader85PA 

It looks like it's doing what it is intended to do. Is it only changing the date when the context menu is closed when it should not?

**Comment by Smurf-IV** [comment]
Can this be closed ?

**Comment by DarthVader85PA** [comment]
@Smurf-IV: Sorry. Yes I close this Request. Thanks vor all.
