### ISSUE TITLE
[Bug]: If the BlurWhenFocusLost is set and the app is underneath another, then it will still have the blur overlay topmost (i.e. on top of the other app which is currently fullscreen!)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#70]
**Describe the bug**
As found in #56 

https://github.com/Krypton-Suite/Standard-Toolkit/issues/56#issuecomment-808719860

**To Reproduce**
win 10 (currently 21H2 but was 1901)
Start app with blurring enabled
Does not always happen, but when it does it looks pants! 

Below shows IDE being clicked onto to bring to top:

![BlurIsOnTop](https://user-images.githubusercontent.com/2418812/150639876-77313d5c-6b0f-48c8-bf59-6e88c00058f3.gif)

**Comment by Smurf-IV** [comment]
@Wagnerp Can this be dropped, as it is not a recommended feature of Windows since win 10 came out (Due to deprecation of the API#s started in Vista)

**Comment by Wagnerp** [comment]
> @Wagnerp Can this be dropped, as it is not a recommended feature of Windows since win 10 came out (Due to deprecation of the API#s started in Vista)

@Smurf-IV Should the `Obsolete` tag be used?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Should the `Obsolete` tag be used?

No, as that infers that some functionality may be working (And also brings up a warning during build, which can be ignored)

In it's current guise - It does not work as intended (Or did in win 7!)

Some of the parameters will need to be removed (Like the opacity, as I cannot get that to work in Win 10)
And it does not do what it was intended even in Win 7, because if you have a window (another app) partially over the Form, and you click on the window to bring to foreground, then that part of the window is used as part of the opaque image(i.e. move the foreground and it still shows ), Also it is using "TopMost" which means that the opaque window is on top of everything in Win 10, due to a slightly different message sequence !!

I propose to remove some values, change the explanation on the existing, and get it to work consistently amongst the supported OS's (i.e. Win 7 onwards)

**Comment by Wagnerp** [comment]
> I propose to remove some values, change the explanation on the existing, and get it to work consistently amongst the supported OS's (i.e. Win 7 onwards)

I agree with that, since a few years ago support for Vista was dropped.

**Comment by Smurf-IV** [comment]
So this has been a ride into the unknown.....
Some issues:
- Gaussian blur API now longer works on win 10
- TopMost windows make a mess of things
- Anything krypton handles painting so completely ignores the DWM mode of the form
- When something takes focus away then capturing a valid bitmap is a pain !

Following demonstrates:
- a KForm with a mixture of standard Winform and Krypton Controls
- Focus lost to app click
- Focus lost to Standard messageBox
- Focus lost to a KForm (Via KMessagebox)
- Movement of top app not impacting the picture underneath
- Transparency through to the underneath object
![BlurWithMessageBox](https://user-images.githubusercontent.com/2418812/151669057-2789c371-10f4-4e66-8c89-cf506e7e3e5a.gif)


Things that need sorting:
- Blurring
- Shadowing
- Better handling of the modification to the bmp pixels (i.e. try not to use `unsafe` keyword)
- Testing on Win 7 / 8 / 10 / 11 etc.
- Testing with different frameworks
