### ISSUE TITLE
[Feature Request]: ButtonSpecs

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#700]
Is it possible to change the format / look / feel of button specs?

I would like to change the size, border rounding and colour of button specs

![image](https://user-images.githubusercontent.com/84494183/164038439-ac846ed8-83d9-4a2e-8331-c832cebe9958.png)

Regards

Matt

**Comment by sdreb3421** [comment]
I just saw this so I'll chime in. Each button spec has a style property associated with a palette style. I use the Form button style for my applications button specs. Within the palette, go to button styles and then form, then set the properties you need (rounding, etc).

**Comment by MattH-Work** [comment]
Well there you go!
Every day is a learning day...
Cheers

**Comment by MattH-Work** [comment]
Works like a charm!
Follow up question, is there a way to rename and/or add additional styles. Custom1, Custom2 & Custom3 could get used up very quickly

**Comment by sdreb3421** [comment]
I don't believe so. With other controls you can modify their individual style properties which overrides what the palette would otherwise set. This gives you unlimited individual styling choices. But I don't think button specs allow this...
