### ISSUE TITLE
[Bug]: `CueHint` in `KryptonPalette` does not work

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#701]
Just started to use Palettes to override the look & feel of ButtonSpecs
Found a couple of issues 

Whenever I change a setting within the Palettes I get the following error
![image](https://user-images.githubusercontent.com/84494183/164214545-ddc03b2f-d5e2-4d94-a9d6-cecf3b459cba.png)
Although it doesnt seems to cause any problems, I would like to know the cause / workaround / fix

In addition, any changes I make to the Palette (in this case, ButtonStyles > ButtonCustom1>StateCommon>....) are ignored by the control next time I start VB studio, its an easy fix, I just need to make a change to anything within the Palette and all the settings magically appear in the relevant controls BUT I need to remember to do this every time VB starts

**Comment by MattH-Work** [comment]
_"I just need to make a change to anything within the Palette and all the settings magically appear in the relevant controls BUT I need to remember to do this every time VB starts"_

It may be that the settings are being applied, it just takes a finite amount of time, which is longer than it takes me to notice the controls are not correct, therfore I keep fixing it...

Hhmmm, will keep an eye on this

**Comment by Wagnerp** [comment]
Resolved 21/04/2022
