### ISSUE TITLE
[Feature Request]: Can BaseFontSize be moved up to IPalette? (and/or be easily modified in kryptonPalette)

### ISSUE THREAD

**Issue by ismdiego** [Krypton-Suite/Standard-Toolkit#703]
**Describe the solution you'd like**
I would like to easily change the base font size of a palette. In order to show all texts bigger and respect the size ratio between different styles.

**Describe alternatives you've considered**
My best alternative has been to do this in code:
```
public Form1()
{
    InitializeComponent();

    if (this.kryptonManager1.GlobalPalette is PaletteBase paletteBase)
    {
        paletteBase.BaseFontSize = 14.0f;
    }
}
```

But doing this the effect cannot be visualized in the designer. It should be an easier method to just change the base size and be able to display the changes in design-time.

**Additional context**
Sorry if this is a newbie question, I have been looking for alternatives with no luck...

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be done, as well as the font, style etc?

**Comment by Wagnerp** [comment]
Needs testing build >= .176

**Comment by Smurf-IV** [comment]
#288 is related ?

**Comment by Wagnerp** [comment]
> #288 is related ?

Yes it is, the question is how to integrate it into `KryptonPalette` a new Font section, same with #669?

**Comment by Wagnerp** [comment]
So, I've been doing some digging around, and found these in `KryptonPaletteCargo.cs`

![image](https://user-images.githubusercontent.com/949607/175916055-e49bae57-7fca-4ad4-a661-654c5a0f2fd3.png)

Question: Should these be moved to a new `KryptonPaletteFont` class?

**Comment by Smurf-IV** [comment]
Yes, and better naming of what they are used for.
But it will break existing code that uses them (If they are used) - So a line in the "Breaking changes" for V7
And then include colour(s) as well ?

**Comment by Wagnerp** [comment]
> Yes, and better naming of what they are used for. But it will break existing code that uses them (If they are used) - So a line in the "Breaking changes" for V7 And then include colour(s) as well ?

Problem is that in testing, these properties do absolutely nothing! **But** it _might_ be possible to route them in the right direction.

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be part of the recent work done on removal of `IPalette`?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Can this be part of the recent work done on removal of `IPalette`?

`IPalette` no longer exists!
So this will / may already be in `PaletteBase`

**Comment by Smurf-IV** [comment]
> > @Smurf-IV Can this be part of the recent work done on removal of `IPalette`?
> 
> `IPalette` no longer exists! So this will / may already be in `PaletteBase`

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/b6aafe3b-3208-4725-bbae-7dc046f6db50)

**Comment by Smurf-IV** [comment]
PR Coming Soon:
![FontThemChanges](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/ccd4e1fc-0731-444f-b415-35db84925ae2)

**Comment by Smurf-IV** [comment]
![DesignerFontThemChanges](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/7c23f19d-0a3b-4211-ac93-e64b95538890)

**Comment by Wagnerp** [comment]
@Smurf-IV Does that mean that all built in palettes use the 'newer' Segoe default font now?

**Comment by Smurf-IV** [comment]
Yes; as it was being set in the PaletteBase, and **also** in the Base implementation renderer's, Hence the removal of the functionality check from the Base renderers
