### ISSUE TITLE
[Question]: AutoScale support?

### ISSUE THREAD

**Issue by ismdiego** [Krypton-Suite/Standard-Toolkit#704]
I want to be able to AutoScale my current Windows Forms application from a lower resolution (1366x768) to a higher one (1920x1080, same aspect ratio).

I know this is not easy with Windows Forms (completely different with WPF). The best solution I have found is to:
- Set AutoScaleMode to `AutoScaleMode.Font`
- Change the main form Font in the Main() method to:
```
var factor = 1920.0f / 1366.0f;
var font = mainForm.Font;
var newFont = new Font(font.FontFamily, font.Size * factor, font.Style, font.Unit);
mainForm.Font = newFont;
```
_(this way, the sizes and positions of the form scale well enough, but not the Krypton texts... as it should be setting the Font size to the original one)_
- In the main form code-behind, just after the `InitializeComponent();´ in the parameter-less constructor, set the new BaseFontSize of the GlobalPalette, but this only works if GlobalPalette is a PaletteBase:
```
if (this.kryptonManager1.GlobalPalette is PaletteBase paletteBase)
{
    paletteBase.BaseFontSize = paletteBase.BaseFontSize * factor;
}
```
_(this way the Krypton texts are resized correctly)_

Can I achieve the same effect easier? Also, the changes in the BaseFontSize cannot be displayed on the designer... which is really an inconvenience. I have also filed a feature request #703 with this improvement.

**Comment by ismdiego** [comment]
It should be that easy... but in reality it isn't... I don't know exactly why, but the NET runtime does some rounding and the real scale factor is not the one that is expected.

I did some extensive testing some weeks ago because I had a resize problem in a project that now it's near completion. I can retest it in a few weeks if you think that this should be already working out of the box.

**Comment by Smurf-IV** [comment]
I always set my scale to DPI or none. Font always gives troubles

**Comment by ismdiego** [comment]
I actually use AutoScaleMode = None and then I handle the scaling manually in the constructor just after the InitializeComponent().

The problem I had with krypton components is that I could not easily change the font size without doing the paletteBase.BaseFontSize trick.

I don't mind doing this, I just want to know if this is a valid trick or maybe it will be broken in a future release.

**Comment by ismdiego** [comment]
Sorry I have just found that my original question was about setting AutoScaleMode = Font. But now I am following a different pattern, as I just summarized in my previous comment.

Right now, I am doing:
- Set AutoScaleMode = None
- In the constructor of the first form of the app, initialize a new scaled font based on the current one.
- On sucesive forms / user controls, invoke an "AutoScaleManual" extension method just after the InitializeComponents() that recursively traverses all inner controls repositioning and scaling them.

It really feel redundant to manually do the third step, just because it's that the AutoScaling functionality should be doing... but...

**Comment by Smurf-IV** [comment]
@ismdiego How does the above work when using "Normal" winform controls ?

**Comment by ismdiego** [comment]
I have created a sample minimal repository for this. It's on: https://github.com/ismdiego/kryptonAutoScaleTest

There is a simplified version of my "AutoScaleManual" method that only takes into account the basic properties of controls. In the real method used in production there are some special cases for table layout panels, split container, DataGridview, etc.. I don't mind sharing if you really need it. It is really simple coding with no black magic into it :-)

The "problem" is that changing the Font in the krypton controls does not work, because of its internals. You have to change the "BaseFontSize" of the palette (if it is PaletteBase based). As I said before, I don't really mind if I must do so. My only concern is that doing this I am using some implementation details that may change in the future and the code will break.

Right now the code that changes the BaseFontSize is commented, so you can view the effect of the krypton controls not changing the Font size, although their Font property has already been changed.

I understand that the Font property in the krypton controls is probably not used, as they use the palette/type defined one. But maybe it's an opportunity to process the regular Font property set to internally change "something" (in this case, the BaseFontSize for instance) in each implementation. And thus we will not need to know the implementation details. Just a guess.

**Comment by Wagnerp** [comment]
For this to work, #703 might need to be implemented too

**Comment by ismdiego** [comment]
> For this to work, #703 might need to be implemented too

It would be really nice to view the base font size effect in designer, yes. But this simpler option is also OK for my scenario.

**Comment by Smurf-IV** [comment]
Are you using the latest .Net6 >= 6.0.2 ?
RE: https://github.com/dotnet/winforms/pull/6203
https://github.com/dotnet/winforms/pull/6182

**Comment by Smurf-IV** [comment]
Linked to  #794 maybe ?

**Comment by Smurf-IV** [comment]
As the Theme font can now be set, then the OP is covered
Closing as this has both a workaround and the same application as the OP
