### ISSUE TITLE
[Bug]: Ability to Hide Close (X) Button on a KryptonPage does not work while moving to a new docked position

### ISSUE THREAD

**Issue by pixelinkmedia** [Krypton-Suite/Standard-Toolkit#711]
**Is your feature request related to a problem? Please describe.**
Not technical problem, but usability problem. I don't use us Krypton Docking because of not being able to hide the X button.
I don't want users to be able to close docking windows because sometimes I would put related controls on another docking window that would disrupt the app from from running.

**Describe the solution you'd like**
To be able to hide or disable the "X" button on all docking windows.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by pixelinkmedia** [comment]
Also, just so you know. I can hide the close button at design time. But, If I drag (dock) it in another window, the the X button reappears.

**Comment by pixelinkmedia** [comment]
Here is a screen shot.
Before dragging (docking) a window = NO "X" button
After with the "X" button displayed again.

![image](https://user-images.githubusercontent.com/51757955/168917642-a4cf6b17-48c6-492a-820a-eedd1474c409.png)

**Comment by Wagnerp** [comment]
Hi @pixelinkmedia 

Thanks for your feedback. Hiding the close button is already supported. To hide the close button, please toggle the `CloseLogic` property to `Hide`.

**Comment by pixelinkmedia** [comment]
Two things.

1) I don't want to hide a docking window, neither do I want it closed at all
2) The is no CloseLogic property. There is a "ButtonDisplayLogic" which doesn't have a Hide

![image](https://user-images.githubusercontent.com/51757955/169022366-4749d5ec-4af9-4e4a-b664-fd3642e01780.png)

Did you read my previous posts?

It hides at design time and when I run it. BUT when I drag a window at runtime into another window it then RE=APPEARS.

I can hide the button, but it doesn't stay hidden

Thanks

**Comment by Wagnerp** [comment]
Hi @pixelinkmedia 

Sorry, I meant the `Close Display` property. You can set the `Close Action` to None, to prevent pages being closed.

![image](https://user-images.githubusercontent.com/949607/169049470-6019f74b-22cf-477d-ae6a-e189c9a80ac3.png)

**Comment by pixelinkmedia** [comment]
That is what I have
![image](https://user-images.githubusercontent.com/51757955/169050481-868bff23-8db5-4f75-a2ef-ae7321312a55.png)

**Comment by Wagnerp** [comment]
Hi @pixelinkmedia 

Having a look at the help file, as I'm not that familiar with the docking library.

**Comment by Smurf-IV** [comment]
> Here is a screen shot. Before dragging (docking) a window = NO "X" button After with the "X" button displayed again.
> 
> ![image](https://user-images.githubusercontent.com/51757955/168917642-a4cf6b17-48c6-492a-820a-eedd1474c409.png)

The red circled are is to do with the creation of a new Navigator area..
Just set the correct settings to not display the buttonSpecs in the "New navigator" when it is created for the new doc position
