### ISSUE TITLE
[Bug]: `KryptonNumericUpDown` Control cannot be change size at design time

### ISSUE THREAD

**Issue by xxl-cc** [Krypton-Suite/Standard-Toolkit#717]
**Describe the bug**
KryptonNumericUpDown Control cannot be change size at design time

**Comment by YellowberryHN** [comment]
The MinimumSize and MaximumSize can be used.

**Comment by Smurf-IV** [comment]
> **Describe the bug** A clear and concise description of what the bug is. KryptonNumericUpDown Control cannot be change size at design time

@xxl-cc 
@YellowberryHN 
Please state 
- Version of Krypton
- Version of windows
- Version of Visual Studio
- Target Framework of project
- How this is achieved with normal .net framework control
- A screen recording of the problem would also help us
Thanks

**Comment by Smurf-IV** [comment]
Combining with #724
