### ISSUE TITLE
[Bug]: Can't drag anything into kryptongroup or kryptongroupbox

### ISSUE THREAD

**Issue by qq1845826382** [Krypton-Suite/Standard-Toolkit#719]
Can't drag anything into kryptongroup or kryptongroupbox
Framework: .Net 6.0

**Comment by Wagnerp** [comment]
Hi @qq1845826382 

The workaround is to select the control, then double click the controls from the toolbox

**Comment by qq1845826382** [comment]
> Hi @qq1845826382
> 
> The workaround is to select the control, then double click the controls from the toolbox

![image](https://user-images.githubusercontent.com/93645101/170740270-9ad7a300-aafe-4ca4-827f-8eb7309c9227.png)

**Comment by Wagnerp** [comment]
Hi @qq1845826382 

Is it possible to provide a video of the bug in action?

**Comment by qq1845826382** [comment]
> Hi @qq1845826382
> 
> Is it possible to provide a video of the bug in action?

The following is from machine translation
My recording software is not capturing the error report popup, but the content of the error report is the same as the content of the previous image.
I can drag other items out normally, but I can't put them into KryptonGroup or KryptonGroupBox.

https://user-images.githubusercontent.com/93645101/170742877-92b58296-9885-44db-b429-9335fad03a7c.mp4

**Comment by Wagnerp** [comment]
Hi @qq1845826382 

In your csproj file, can you add the following line: `<TargetFrameworks>net48;net6.0-windows</TargetFrameworks>`, then retry?

**Comment by Wagnerp** [comment]
Hi @qq1845826382 

Ok, now replace the **first** two lines with the following: `<Project Sdk="Microsoft.NET.Sdk">`, once completed, you should be ok.

**Comment by Wagnerp** [comment]
Hi @qq1845826382 

Are the changes working for you now?

**Comment by qq1845826382** [comment]
> Hi @qq1845826382
> 
> Are the changes working for you now?

The following is from machine translation
No, I got the following error: invalid nullable value: C# 7.3 "Enable". Please use language version 8.0 or later.
I tried adding the following statement '<langversion>preview</langversion>' to my CSproj file and I got the following error: The type or namespace name 'System.Net' does not exist in the namespace 'Http' (are you missing an assembly reference?)

**Comment by Wagnerp** [comment]
> > Hi @qq1845826382
> > Are the changes working for you now?
> 
> The following is from machine translation No, I got the following error: invalid nullable value: C# 7.3 "Enable". Please use language version 8.0 or later. I tried adding the following statement" preview" to my CSproj file and I got the following error: The type or namespace name 'System.Net' does not exist in the namespace 'Http' (are you missing an assembly reference?)

I think there are now NuGet packages that fixes this, see: https://www.nuget.org/packages?q=System.Net

**Comment by qq1845826382** [comment]
> > > Hi @qq1845826382
> > > Are the changes working for you now?
> > 
> > 
> > The following is from machine translation No, I got the following error: invalid nullable value: C# 7.3 "Enable". Please use language version 8.0 or later. I tried adding the following statement" preview" to my CSproj file and I got the following error: The type or namespace name 'System.Net' does not exist in the namespace 'Http' (are you missing an assembly reference?)
> 
> I think there are now NuGet packages that fixes this, see: https://www.nuget.org/packages?q=System.Net

![image](https://user-images.githubusercontent.com/93645101/171997313-d539a17c-cfe6-4578-a7fa-15672ae9e4e4.png)
The name 'ApplicationConfiguration' does not exist in the current context

**Comment by Wagnerp** [comment]
> > > > Hi @qq1845826382
> > > > Are the changes working for you now?
> > > 
> > > 
> > > The following is from machine translation No, I got the following error: invalid nullable value: C# 7.3 "Enable". Please use language version 8.0 or later. I tried adding the following statement" preview" to my CSproj file and I got the following error: The type or namespace name 'System.Net' does not exist in the namespace 'Http' (are you missing an assembly reference?)
> > 
> > 
> > I think there are now NuGet packages that fixes this, see: https://www.nuget.org/packages?q=System.Net
> 
> ![image](https://user-images.githubusercontent.com/93645101/171997313-d539a17c-cfe6-4578-a7fa-15672ae9e4e4.png) The name 'ApplicationConfiguration' does not exist in the current context

Maybe this can help https://docs.microsoft.com/en-us/dotnet/desktop/winforms/whats-new/net60?view=netdesktop-6.0

**Comment by qq1845826382** [comment]
> > > > > Hi @qq1845826382
> > > > > Are the changes working for you now?
> > > > 
> > > > 
> > > > The following is from machine translation No, I got the following error: invalid nullable value: C# 7.3 "Enable". Please use language version 8.0 or later. I tried adding the following statement" preview" to my CSproj file and I got the following error: The type or namespace name 'System.Net' does not exist in the namespace 'Http' (are you missing an assembly reference?)
> > > 
> > > 
> > > I think there are now NuGet packages that fixes this, see: https://www.nuget.org/packages?q=System.Net
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93645101/171997313-d539a17c-cfe6-4578-a7fa-15672ae9e4e4.png) The name 'ApplicationConfiguration' does not exist in the current context
> 
> Maybe this can help https://docs.microsoft.com/en-us/dotnet/desktop/winforms/whats-new/net60?view=netdesktop-6.0

Problem solved! Thank you for your patience, please forgive my poor grammar.
