### ISSUE TITLE
[Bug]: Control(editbox, numericupdown..) not accept '9' key

### ISSUE THREAD

**Issue by chihsiliu1966** [Krypton-Suite/Standard-Toolkit#720]
**Describe the bug**

KryptonRibbon.c should modify as 
 if (keyData.HasFlag(Keys.Tab)) ----->      if (keyData==Keys.Tab)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. 10.0.22000]

**Additional context**

**Comment by Wagnerp** [comment]
Fixed in June 2022 release
