### ISSUE TITLE
[Bug]: Width of NumericUpDown controls can not be manually specified anymore.

### ISSUE THREAD

**Issue by kmsbecker** [Krypton-Suite/Standard-Toolkit#724]
in all Krypton.toolkit versions released after krypton.toolkit.canary.6.0.2109 it is unfortunately not possible anymore to custom-define the width of a NumericUpDown control manually. Instead its width seems to be solely determined by the specified number of total digits before and after the colon. Maybe this behaviour sometimes is even desired for cetrain applications, However, having several NUmericUpDown controls of different width does definitely not look very nice, if you need to arange them in a grid  with multiple lines and columns. 
best,
Klaus

**Comment by Smurf-IV** [comment]
Done:
![NumericUpDowner](https://user-images.githubusercontent.com/2418812/172793146-96736561-2f91-418a-b8fc-66d91707273f.gif)

**Comment by Smurf-IV** [comment]
@Wagnerp The changes for this are no longer in alpha, I think the merge from version next wiped them out !!

**Comment by Smurf-IV** [comment]
I'll put them back in as part of the next PR I'm working on.

**Comment by Wagnerp** [comment]
> @Wagnerp The changes for this are no longer in alpha, I think the merge from version next wiped them out !!

@Smurf-IV Ok, I was going to say that I'll put them back in. Need to also check if any other changes were wiped out inadvertently

**Comment by Smurf-IV** [comment]
> @Smurf-IV Ok, I was going to say that I'll put them back in. Need to also check if any other changes were wiped out inadvertently

eek.. Ok, I'll leave the rest to you..

**Comment by Wagnerp** [comment]
@Smurf-IV Will do, I don't think there is much
