### ISSUE TITLE
[Feature Request]: Bring MessageBox `States` inline with latest .Net 6 

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#728]
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/whats-new/net60?view=netdesktop-6.0#updated-apis

![image](https://user-images.githubusercontent.com/2418812/172110241-715207b0-a14b-4052-b489-b55b4fe3272c.png)

===================
Edit: 
The "Idea" of these changes is to bring the functionality "Down" from .Net 6 / 7 into the earlier versions, so that a Single code base will work for multi-target builds.
===================

**Comment by Wagnerp** [comment]
@Smurf-IV Just thinking about it, do these new features need the `#if` definition to work? If so, I'll try to tackle some of the messagebox portion of it today.

**Comment by Smurf-IV** [comment]
`#if` would be one way to "Limit" the functionality,
But... It would be nice if it could be made "Backward compatible" (i.e all the way down down to .net 4.6.2)

**Comment by Wagnerp** [comment]
Needs testing >= .162

**Comment by Wagnerp** [comment]
@Smurf-IV Do we know if this is working, also what is `button4` used for?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Do we know if this is working, also what is `button4` used for?

![image](https://user-images.githubusercontent.com/2418812/179389608-5779f355-3555-45b4-abf7-aee683475547.png)

**Comment by Wagnerp** [comment]
> > @Smurf-IV Do we know if this is working, also what is `button4` used for?
> 
> ![image](https://user-images.githubusercontent.com/2418812/179389608-5779f355-3555-45b4-abf7-aee683475547.png)

So, is there a `help` button now?

**Comment by Wagnerp** [comment]
@Smurf-IV I assume the "new" button4 option would go to the left of the existing buttons _if_ it's a dedicated help button?

**Comment by Smurf-IV** [comment]
You will have to create a demo app in .Net 6 and try....

**Comment by Wagnerp** [comment]
I'm not sure if we even need this, as a button for help is already catered for

**Comment by Wagnerp** [comment]
Got it!! PR coming soon

**Comment by Smurf-IV** [comment]
@Wagnerp I think in order to get "Backward compatible with previous versions of TFM", _we_would need to use a krypton type for buttons etc. Like you did for the Icons. e.g.
`MessageBoxButtons` -> `KyrptonMessageBoxButtons`

Thuoghts ?

**Comment by Wagnerp** [comment]
> @Wagnerp I think in order to get "Backward compatible with previous versions of TFM", _we_would need to use a krypton type for buttons etc. Like you did for the Icons. e.g. `MessageBoxButtons` -> `KyrptonMessageBoxButtons`
> 
> Thuoghts ?

@Smurf-IV No problem, I may look into the feasibility of #866

**Comment by Wagnerp** [comment]
@Smurf-IV I think I did something similar in the extended toolkit, regarding buttons, so you can borrow that code

**Comment by Smurf-IV** [comment]
Point 1 done:
![MBox](https://user-images.githubusercontent.com/2418812/206915398-68b8915a-eac1-49a4-b3f1-39f458caa20a.gif)
