### ISSUE TITLE
[Feature Request]: Allow setting height of KryptonForm title bar

### ISSUE THREAD

**Issue by hopla** [Krypton-Suite/Standard-Toolkit#731]
I'm looking into updating an MDI application to a new look, with Krypton components and a custom theme.
To save screen space I would like to decrease the height of the title bar of the MDI forms.

In the PaletteDesigner there seems to be no reference to height.
In code it seems to be requested from the OS through the AdjustWindowRectEx-function, in a way that is not overridable?

Ideally this would be configurable in the palette but I would very much appreciate it if there was a short-term workaround in code to achieve this.

The alternative would be to implement my own form class, deriving from VisualForm or Form. I would rather not go in that direction.

**Comment by Smurf-IV** [comment]
@hopla You could set the `FormBorderStyle` to `None` and just add a tool area (Or similar) that simulates a Form title (To allow drag drop / double click / etc)
![image](https://user-images.githubusercontent.com/2418812/179349925-ea73516c-4cfa-4c5e-a8fa-741f5a2af761.png)
