### ISSUE TITLE
[Bug]: Krypton Toolkit 65.22.6.152 - ButtonSpec Images 'squashed'

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#733]
Windows 10
Visual Studio (VB) 2019
.Net 4.8
Krypton Toolkit 65.22.6.152

The is a re-occurance of previous issue affecting 60.22.2.32 ( #623 )

This 'eyeball' (from a combobox buttonspec)
![image](https://user-images.githubusercontent.com/84494183/172791828-fecbf341-6a35-4789-9130-1f04361a5708.png)

Should look like this 'eyeball' (from a command button)
![image](https://user-images.githubusercontent.com/84494183/172791865-a6526269-00b1-4216-8eda-725fc69b3745.png)

Same vertical compression on all ButtonSpecs images
![image](https://user-images.githubusercontent.com/84494183/172791904-d44a2b76-2d9d-4a18-ae1c-041b574bbe16.png)

Changing border 'Rounding' size or setting the Minimum & Maximum size of the control (to allow height changes on controls that are usaully fixed height, like comboboxes) has no effect on the ButtonSpec image, but does affect the drop down button
![image](https://user-images.githubusercontent.com/84494183/172794053-0b054aef-335c-4c8c-a7ab-7d3d98c2289b.png)  (the +3 should look like this)  ![image](https://user-images.githubusercontent.com/84494183/172794616-d5e5b1c9-bffa-4570-98ad-08c494d63b77.png)

This alludes to the fact this issue is not related to control size

**Comment by Smurf-IV** [comment]
@Wagnerp Has this been sorted with the correct merging of the fix from the initial issue #623 and then the subsequent fix for the Width sizing ?

**Comment by Wagnerp** [comment]
> @Wagnerp Has this been sorted with the correct merging of the fix from the initial issue #623 and then the subsequent fix for the Width sizing ?

@Smurf-IV Not sure if I need to reinstate the fixes from https://github.com/Krypton-Suite/Standard-Toolkit/pull/627?

**Comment by Wagnerp** [comment]
@MattH-Work Can you re-test using the latest nightly build please?

cc. @Smurf-IV

**Comment by MattH-Work** [comment]
> @MattH-Work Can you re-test using the latest nightly build please?
> 
> cc. @Smurf-IV

Tried with nightly build 70.22.8.213, seems to work

![image](https://user-images.githubusercontent.com/84494183/182659156-5a97fa3f-5268-4949-bcdc-9940619000c0.png)

![image](https://user-images.githubusercontent.com/84494183/182659231-cc7c8bdd-a9e2-4618-a521-f8895cae0fa7.png)

![image](https://user-images.githubusercontent.com/84494183/182659297-4304db72-d92c-4041-9311-31f23aaba983.png)

I also appreciate that NumberUpDown disabled values now show correctly #734

![image](https://user-images.githubusercontent.com/84494183/182660124-8bd00c62-0ca2-497c-a041-c400002a7092.png)


Are the nightly builds considered 'OK' for production (probably not, by vertue of being nightly)
Are the canary builds production ready, and if so, if / when will the fixes be 'canary fied'
Do I just have to wait for the stable build in November

**Comment by Wagnerp** [comment]
@MattH-Work The nightly & canary builds are not considered to be production ready, due to possible unstable code.
