### ISSUE TITLE
[Bug]: Disabled Text in NumericUpDown Not visible - Krypton Toolkit 65.22.6.152

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#734]
Windows 10
Visual Studio (VB) 2019
.Net 4.8
Krypton Toolkit 65.22.6.152

Think I found an issue with NumericUpDown control

As can be seen in the attached video, the control is disabled by default, but once its enabled state is cycled, the value text disappears when the control is disabled again

Should the value not display, regardless of enabled state?

I am experiencing this in my main appliction as the Grpbox containing the NumericUpDown control is disbled by default (displays no value) but once the GrpBx is enabled the value appears

https://user-images.githubusercontent.com/84494183/172853845-db6df25d-0a71-4cec-80ed-645153942f03.mp4

**Comment by MattH-Work** [comment]
Same issue with build 65.22.4.94

Works as expected with 60.22.2.32

**Comment by Smurf-IV** [comment]
Done.. PR Coming Soon...
![image](https://user-images.githubusercontent.com/2418812/172905719-bd6fa2f4-c93f-461e-80eb-22ece4d24c51.png)
