### ISSUE TITLE
[Feature Request]: ButtonSpec - Enable state independant of host

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#736]
Is it possible to have ButtonSpec ( hosted by a KryptonHeaderGroup ) always in an 'enabled' state, regardless of the enabled state of the host KryptonHeaderGroup.

![image](https://user-images.githubusercontent.com/84494183/172863953-54eb674b-315c-4e44-a2f3-911f5d8db1bb.png)
Would like to be
![image](https://user-images.githubusercontent.com/84494183/172864273-e1a6015c-7d78-47f2-a231-9de80e061554.png)

Currently faking the effect by having buttons float above HeaderGroupBox, but border rounding has graphical glitches as it picks up the colour of the host ( the grey form ) rather than the control (  blue HeaderGroupBox ) below it 
( mockup below )
![image](https://user-images.githubusercontent.com/84494183/172865254-e44d1ed5-06b1-48ca-83c1-91ec90f4b8e9.png)

**Comment by Smurf-IV** [comment]
> Currently faking the effect by having buttons float above HeaderGroupBox, but border rounding has graphical glitches as it picks up the colour of the host ( the grey form ) rather than the control ( blue HeaderGroupBox ) below it ( mockup below ) 

FYI: Workaround for the glitch is to place a panel behind the buttons.

**Comment by MattH-Work** [comment]
Overnight inspiration
The KryprtonHeaderGroup already has an inbuilt panel, so all I need to do is keep the KryptonHeaderGroup enabled (thus giving access to the buttonspec) and just control the enabled state of the sub panel.
