### ISSUE TITLE
[Bug]: Selecting `Office 2013 - Dark Grey` for `PaletteMode` in designer causes a crash

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#737]
Todays Alpha Code base
Windows 10 22.H1
VS2022.Preview3.1

![CrashPalleteMode](https://user-images.githubusercontent.com/2418812/172866278-9aa44536-cbeb-4904-8302-ee034be451a8.gif)

**Comment by Smurf-IV** [comment]
Same applies to the "Office 2010 - Dark Grey"
and "Office 2010 - Light Grey"
And the Offices 2k7 equivalents

**Comment by Wagnerp** [comment]
@Smurf-IV I'm going to disable these options until the themes are done

**Comment by Wagnerp** [comment]
Resolved 10/06/2022
