### ISSUE TITLE
[Bug]: "Office 2010 - Blue (Dark Mode)": Form title text cannot be read

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#738]
![image](https://user-images.githubusercontent.com/2418812/172866725-7d46fc36-6803-49f8-8003-fc00a49eff2e.png)

**Comment by Smurf-IV** [comment]
Same for the Office 2010 - Silver (Dark Mode)

**Comment by Wagnerp** [comment]
@Smurf-IV Still looking! :) Might need to be black text...

**Comment by Smurf-IV** [comment]
It will need to be tested for the other "Dark Gray" Themes

**Comment by Wagnerp** [comment]
Fixed, PR incoming

![738](https://user-images.githubusercontent.com/949607/173299318-06d72e88-1154-48c4-a7ed-c2dd2e6cedd3.gif)

**Comment by Wagnerp** [comment]
Fixed - 13/06/2022
