### ISSUE TITLE
[Bug]: KryptonButton - Image stretches with increased border rounding

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#739]
Windows 10
Visual Studio (VB) 2019
.Net 4.8
Krypton Toolkit 65.22.6.15

With border rounding set to above '7', image applied to button streches to full width of control, unless we increase control height
To keep consistent control sizes, can the strech be avoided?
Is it possible to shift the image a few pixels to the right?

![image](https://user-images.githubusercontent.com/84494183/172869230-2d45f20e-70c5-4681-801a-ad052caabc10.png)

**Comment by Smurf-IV** [comment]
> Proposed fix.. Make the Preferred size ignore whether text can be drawn fully, and force clipping to be used.

That will not work !
As the following code gets "Triggered" when the available height left after rounding is less than the height of the image:
![image](https://user-images.githubusercontent.com/2418812/173221272-ebcb52d7-e8e1-415f-b0e1-d5e495d3e77d.png)

Resulting in an image taking the full width.
Not sure why this was done.

**Comment by Smurf-IV** [comment]
> Not sure why this was done.

It is to allow a very large image to be scaled down !!
Doesn't seem to work as expected tho !

**Comment by Smurf-IV** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/2418812/173222304-b66d5bd9-ff78-46ca-b840-c187943d8f3e.png)

Note: All the images are taller than the available space, and the Blue icon is 128 wide, so is wider as well

PR Coming soon.
