### ISSUE TITLE
[Bug]: Double clicking the 'File' button in `KryptonRibbon` closes the application 

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#74]
Bug as reported by user @herledant: 

> Hello, I'm facing a strange behavior with the kryptonRibbon. When i accidentaly double click on the appButton this is send an application.exit.
Is there a way to avoid this?

**Comment by herledant** [comment]
Only when i double click on the appButton ("File"), this fire an application exit...
![image](https://user-images.githubusercontent.com/9166449/114433927-b0606480-9bc2-11eb-85dc-9029de639c96.png)

If i double click on the other tab, it reduce the ribbon as expected or as Office ribbon will do it.

**Comment by Smurf-IV** [comment]
Unable to replicate using latest nightly and the existing example from Ribbons:
![DoubleClickFile](https://user-images.githubusercontent.com/2418812/147564303-f93de8a4-3eed-4fa8-af9b-30638be75b1c.gif)

BUT:
Some of the examples do have the double click -> Close functionality, so it must be something that can be overridden by the developer.

**Comment by Smurf-IV** [comment]
Well.. This is "quite damming":
![image](https://user-images.githubusercontent.com/2418812/147564944-57f711fb-03c9-4872-802e-cc52eb3a950d.png)

**Comment by Wagnerp** [comment]
Why does O2K10 - 365 need to close on double clicking?

**Comment by Smurf-IV** [comment]
That if statement is rubbish..
This is what it looks like now:
``` c#
            // Office 2010 does not close on a double click
            if (_ribbon.IgnoreDoubleClickClose
                || _ribbon.RibbonShape != PaletteRibbonShape.Office2010
                )
            {
                return;
            }
```

**Comment by Smurf-IV** [comment]
Done:
New Designer value to `Ignore Double click close` independent of theme  type override:
![image](https://user-images.githubusercontent.com/2418812/147571230-f81a4271-b53b-414e-a53d-8c94e44ca310.png)
