### ISSUE TITLE
[Other Issues]: Autosize in KryptonTextbox

### ISSUE THREAD

**Issue by mikel3361** [Krypton-Suite/Standard-Toolkit#742]
Text descenders are truncated by autosize in the text box. Is there a way to disable autosize in the text box?

**Comment by Wagnerp** [comment]
Bought over from extended toolkit issues

**Comment by mikel3361** [comment]
1. Signed Version 65.22.4.94
2. Framework 4.72 with VB from VS.2017

Sample follows - current app is too big...

**Comment by mikel3361** [comment]
Will solve Autosize for the moment being via Multiline (Catch Newline and remove)

**Comment by mikel3361** [comment]
Thanks for give me a push in the right direction ;-)

Btw, if i use KryptonPalette inside a Form a CueHint Error for it appears: CueHint Property for Palette is empty...

**Comment by Smurf-IV** [comment]
> Btw, if i use KryptonPalette inside a Form a CueHint Error for it appears: CueHint Property for Palette is empty...

Raise a new issue for this please ?
