### ISSUE TITLE
[Question]: Does the `KryptonCheckBox` contain the 'AutoEllipsis' property

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#75]
Does the `KryptonCheckBox` contain the 'AutoEllipsis' property, or am I missing something?

**Comment by Smurf-IV** [comment]
Where did my comment go from yesterday ?

**Comment by Smurf-IV** [comment]
It is part of the `State######` area:
![image](https://user-images.githubusercontent.com/2418812/114979534-ee8bab80-9e82-11eb-91c3-c40a210052b2.png)

**Comment by Wagnerp** [comment]
> It is part of the `State######` area:
> ![image](https://user-images.githubusercontent.com/2418812/114979534-ee8bab80-9e82-11eb-91c3-c40a210052b2.png)

I may include a shortcut for this in the actionlist.

**Comment by Wagnerp** [comment]
Including multiline support
