### ISSUE TITLE
[Bug]: KryptonComboBox does not follow theme settings when DropDownStyle is DropDownList

### ISSUE THREAD

**Issue by hopla** [Krypton-Suite/Standard-Toolkit#751]
The KryptonComboBox component does not follow theme settings when DropDownStyle is set to DropDownList.
I have verified this in the Palette Designer in the branches Canary and Alpha.

See this screenshot:
![image](https://user-images.githubusercontent.com/1023939/173252177-53e25e16-81ca-4824-9427-6980aa6a68ae.png)

I am running Windows 11 Pro 21H2.

**Comment by hopla** [comment]
This seems to be related to issue #723

**Comment by hopla** [comment]
This PR fixes the issue... https://github.com/Krypton-Suite/Theme-Palettes/pull/38

**Comment by Smurf-IV** [comment]
@hopla Thanks for the PR
