### ISSUE TITLE
[Bug]: Error with KryptonPalette in WindowsForm (VB)

### ISSUE THREAD

**Issue by mikel3361** [Krypton-Suite/Standard-Toolkit#753]
VS2017 VB Forms Projekt with Framework 4.72 by dropping KryptonManager and KryptonPalette inside Form following Error appears:
CueHintText property is null

CueHintText property in KryptonPalette is empty and not changeable. KryptonManager palette set to KryptonPalette in Form - maybe i use it wrong, cant save form or project as sample anyway.

**Comment by Wagnerp** [comment]
Part of #669

**Comment by Wagnerp** [comment]
Hi @mikel3361 

Which version of the toolkit are you using, and can you provide any screenshots?

**Comment by mikel3361** [comment]
I Use all with VB.2017 and Framework 4.72:
![image](https://user-images.githubusercontent.com/42733572/173567470-4f2bdd10-a9ad-42c1-b027-cb58aefd45c6.png)

Krypton.Toolkit.Extended Signed Version from NuGet
![image](https://user-images.githubusercontent.com/42733572/173566749-cc4e3dc4-2fa7-4b83-9717-6d01b25eb17c.png)

KryptonPalette assigned to KryptonManager inside Form1 properties:
![image](https://user-images.githubusercontent.com/42733572/173567006-1cadf4b1-812c-4ee5-b498-03c63f8b4075.png)

After try to save following error:
![image](https://user-images.githubusercontent.com/42733572/173567115-7921eb70-2b88-467f-8205-3f4c43775ab6.png)

Sorry, but i use german version of VS 2017 professional with all updates so messages in that language...

**Comment by Wagnerp** [comment]
> 

Hi @mikel3361 

Is it possible to upgrade to the June release, as I think it was fixed in there?

**Comment by mikel3361** [comment]
I thought the signed version was the release version, so I waited for a new signed one to update. I will reference the June version...

**Comment by Wagnerp** [comment]
> I thought the signed version was the release version, so I waited for a new signed one to update. I will reference the June version... Takes a little bit time - there is no way via NuGet to Switch Versions ;-)

What type of configuration are you using, the older format, or the newer SDK style?

**Comment by mikel3361** [comment]
I Think Old Style - never change old app with that.

When i try to get Extended June Version from NuGet i get an error:
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	NU1103	Ein stabiles Paket "Krypton.Toolkit.Suite.Extended.Effects.Nightly" der Version (>= 65.22.6.152) wurde nicht gefunden.

Try to Install this:
![image](https://user-images.githubusercontent.com/42733572/173570250-531c686b-17dd-46e8-8199-b0b34a451c3d.png)

**Comment by mikel3361** [comment]
Not installed Krypton has Nightly References inside:
![image](https://user-images.githubusercontent.com/42733572/173572217-c9ea33a2-59f7-4744-a570-6cdcca7cda03.png)
![image](https://user-images.githubusercontent.com/42733572/173572312-1308f5c6-9e94-45b1-ac32-dcc5fa736946.png)
![image](https://user-images.githubusercontent.com/42733572/173572400-7c5aeb87-2499-496d-980e-fb48ce9213c3.png)
![image](https://user-images.githubusercontent.com/42733572/173572477-97eb6669-e747-4a4e-97cc-e10e2a8a25c7.png)
![image](https://user-images.githubusercontent.com/42733572/173572583-0105752d-cd03-44f3-8f16-86ace4300c25.png)
![image](https://user-images.githubusercontent.com/42733572/173572700-58e6c74a-95d5-4369-ae02-dfa0b9229cc5.png)
![image](https://user-images.githubusercontent.com/42733572/173572789-ceb4f217-af0b-4fc6-b180-c26ce4f461be.png)
...

**Comment by mikel3361** [comment]
Error belong to Extended Toolkit, can you move it...

**Comment by mikel3361** [comment]
Installable packages holds controls for test, KryptonPalette CueHintText Error not in current version.
