### ISSUE TITLE
[Bug]: Error when (re-)saving palette.xml with images

### ISSUE THREAD

**Issue by hopla** [Krypton-Suite/Standard-Toolkit#758]
In older palette.xml files, such as the files in "Theme-Palettes\Palettes\Community\Themes by Byte#7189", the images in the xml file are serialized Image objects.
When these files are saved, an ArgumentNullException is thrown, with description "Value cannot be null. Parameter name: encoder.

![image](https://user-images.githubusercontent.com/1023939/174498316-dc35a9e0-6b34-4e6b-a0fe-daf6cf4d4554.png)

This occurs because the Image's Format is set to MemoryBmp as opposed to the original Format of the bitmap.
In the method KryptonPalette.ExportImagesToElement(), Bitmap.Save() is called with the RawFormat of the image that is being saved. 
In this Save method, the .NET framework tries to find an ImageCodecInfo structure for the format that is being saved. This structure cannot be found for an in-memory bitmap. This would not be the case for the original images which are loaded from disk (e.g. PNG of BMP).

**Comment by hopla** [comment]
This issue is fixed with pull-request https://github.com/Krypton-Suite/Standard-Toolkit/pull/759

**Comment by Wagnerp** [comment]
Fixed - 18/06/2022
