### ISSUE TITLE
[Bug]: KryptonDataGridView lost columns and creates new after Debug when binding to a DataSource.

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#76]
Hey @Wagnerp 

Now here my issue description:

I have a `BindingSource` binded to a `DataSet` with `DataTables` and `DataColumn`s. 
Now I set in Designer the property `DataSource` to the `BindingSource` that is binded to the `DataSet`. The Designer creates the columns for the DataGridView automatically. 

First of all, it is not use the `Caption`-Property from the `DataColumn`. 

In the `Columns`-Property of the `KryptonDataGridView` I change the settings for the columns (Visible, Heading, Name and something other things). Now when I start a Debug the Grid is display nothing. 
After ending the Debug, the Designer is reloading the form and all my settings of columns are resetted. Interesting: When i set the Name-Property for a column, Visual Studio says, that a control with this name is already exists. I look into the Designer-File (VB.Net) and I see that the Designer created new Columns with Defaults. After I deleted the old columns that I have customized and make the changes again in the Designer, it will works until the next Debug!?!?!? Sometimes I have luck and it hold on for 3 or 4 Debug-Runs. 

It's really annoying :frowning: 
I tested it with Windows-Default-`DataGridView`-Control and it works everything fine!

**Comment by DarthVader85PA** [comment]
@Wagnerp 
@Smurf-IV 

Have you some kind of solution here? Today i had the issue again! I can't use this DataGrid then!?! :(

**Comment by Smurf-IV** [comment]
Sorry @DarthVader85PA I've not looked into this. 
Is it possible for you to create a quick Small Demo app? (Or can be added to the Standard-Toolkit-demo's DataGrid Example)
So that "we" can try and see if it still exists in the latest.

**Comment by DarthVader85PA** [comment]
Hey @Smurf-IV 

Thanks. I created a Demo Project for you.
On that picture you will see in the background the form in designer of Visual Studio 2017. And in the foreground you see debugging session. I changed the Header-Text in Columns-Collection in DataGridView-Column-Property.
![grafik](https://user-images.githubusercontent.com/32876506/132104736-e3054dfe-dda2-4ca9-8e8c-a2c7fe680766.png)

In following animated gif you see how I created a DataSet with DataTable and DataColumn and how I bind it over BindingSource to KryptonDataGridView.
![KryptonDataGridView_AddBindingSource](https://user-images.githubusercontent.com/32876506/132104779-844cc07c-15a2-4909-a3ec-852f736fce54.gif)

And here for you the Demo-Project for testing by yourself:
[KryptonDataGridViewDemo.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/7110342/KryptonDataGridViewDemo.zip)

Greetings to UK, 
Danny

**Comment by Smurf-IV** [comment]
Can you repeat your test steps with a normal windows DataGridView.. 
I'm a little lost as to what the problem is - i.e. if you are changing columns after attaching the dataSource, then the designer will not know what to do...

**Comment by giduac** [comment]
@DarthVader85PA 
Is this still a problem or can this ticket be closed ?

**Comment by DarthVader85PA** [comment]
Hey @Smurf-IV, @giduac,

@Smurf-IV: With a Windows DataGridView it works as expected. Windows DataGridView use the `Caption`-Property too of the columns created in `DataSet`. With `KryptonDataGridView` I lose my changes on columns sometimes after Debug-Session or changes on `DataSet`. My workaround: I add in the Designer-File of the form `Me.MyDataGridName.AutoGenerateColumns = False`. Then I set the `BindingSource` to `DataSource`-Property on the Grid. 

@giduac: No, please let it open still the issue is identified and fixed. Thannks.

**Comment by giduac** [comment]
Hi @DarthVader85PA,

Please see the doc/link below. Especially the remarks section. There it is clearly described how the AutoGenerateColumns property affects the grid.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.autogeneratecolumns?view=windowsdesktop-6.0

**Comment by jdelestre** [comment]
Hello
I'm French so sorry for the bad langage...
First of all thank you for all the hard work.

Allow me to repeat this issue.

User of the KryptonDataGridView, I also have the same problem: namely, the column headers reset.
KryptonDataGridView connected to a BindingSource not manually.
The columns of the linked table are displayed by default: normal.
In the column management module, if you delete some of them or make them invisible, or change their name or even their type (textbox to combobox for example), the columns are displayed correctly , as you want them to appear. But when you launch the application, they are reset.
The strangest thing is that it happens randomly. Sometimes the setting stays, sometimes it resets?
It's disturbing and impossible to put into production...

Microsoft's DatagridView works very well.

Cordially
J.DELESTRE

**Comment by Wagnerp** [comment]
@Smurf-IV Is there something that is not exposed from the standard `DataGridView`?

**Comment by Smurf-IV** [comment]
@DarthVader85PA I have run your example, and yes I see the column names,
But the Tableset column names are the ones displayed ??
![image](https://user-images.githubusercontent.com/2418812/206895740-8877f718-d126-4489-a9eb-f2043d83123c.png)

**Comment by Smurf-IV** [comment]
> Hello I'm French so sorry for the bad langage... First of all thank you for all the hard work.
> 
> Allow me to repeat this issue.
> 
> User of the KryptonDataGridView, I also have the same problem: namely, the column headers reset. KryptonDataGridView connected to a BindingSource not manually. The columns of the linked table are displayed by default: normal. In the column management module, if you delete some of them or make them invisible, or change their name or even their type (textbox to combobox for example), the columns are displayed correctly , as you want them to appear. But when you launch the application, they are reset. The strangest thing is that it happens randomly. Sometimes the setting stays, sometimes it resets? It's disturbing and impossible to put into production...
> 
> Microsoft's DatagridView works very well.
> 
> Cordially J.DELESTRE

Please raise a separate issue for the above, and add an example.
