### ISSUE TITLE
[Feature Request]: Can TFM also include .NET Framework 4.8.1?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#761]
Now Available as an option in VS installs...

![image](https://user-images.githubusercontent.com/2418812/175288523-45241ac1-5221-4549-b542-a269c00af57b.png)

So should the TFM also be in the V7 release ?

**Comment by Wagnerp** [comment]
@Smurf-IV I didn't even know 4.81 even existed :) but yes, I'll add it in for tomorrows nightly build.

**Comment by Wagnerp** [comment]
Might need to keep `net48` in place, since 4.8.1 seems to be for VS 2022 only

**Comment by Smurf-IV** [comment]
Yes, Must Still keep 4.8

**Comment by Smurf-IV** [comment]
Until 4.8.1 is official and has a separate installer for 2017 and / Or an update to VS 2019

**Comment by Smurf-IV** [comment]
> Please test using `nightly` build >= .175

Nuget dependencies state 4.8.1
![image](https://user-images.githubusercontent.com/2418812/175763928-fb7dfbf0-b886-4b14-b537-7498cff78e88.png)


BUT, Description paragraph does not:

![image](https://user-images.githubusercontent.com/2418812/175763959-7e135328-8e02-423b-835b-7356f3cd817c.png)

**Comment by Wagnerp** [comment]
> 

Fixed yesterday after the upload

**Comment by Wagnerp** [comment]
Please re-check using today's build

**Comment by Wagnerp** [comment]
Completed - 26/06/2022
