### ISSUE TITLE
[Other Issues]: `Development-Workflow.md` needs to state what the builds are (i.e. nightly)

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#764]
The above page is linked to the text "Cadence" which indicates / infers a release cycle. but it just mentions branches ??

![image](https://user-images.githubusercontent.com/2418812/175763805-9755a005-6b18-4e5a-91dc-25c274447286.png)

**Comment by Wagnerp** [comment]
I'll look into it

**Comment by Wagnerp** [comment]
Done!

![image](https://user-images.githubusercontent.com/949607/175769859-35177fb1-9d21-4fd0-bda2-fbb79761d44d.png)

**Comment by Smurf-IV** [comment]
` and are the last stable` 
Needs to be `least stable`

**Comment by Smurf-IV** [comment]
Canary statement states `2-3 month cadence` is contradicted by bullet point

**Comment by Smurf-IV** [comment]
And Main needs to be 2 - 3 times a year, otherwise "whats the point of Canary" ?

**Comment by Wagnerp** [comment]
Modified in latest commit

**Comment by Wagnerp** [comment]
Completed - 26/06/2022
