### ISSUE TITLE
[Bug]: Help buttonspec icon "disappears" after assigning a KCommand to it

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#769]
If you add a help buttonspec to a KForm, the icon "disappears" if you assign a KCommand to it. Is this normal?

**Comment by Smurf-IV** [comment]
ButtonSpec icons are replaced by the Command image.
Perhaps the bug is that the image should not be replaced iff the KCommand does not have one ?

**Comment by Wagnerp** [comment]
> ButtonSpec icons are replaced by the Command image. Perhaps the bug is that the image should not be replaced iff the KCommand does not have one ?

Maybe this needs to be documented somewhere, as it could be confusing? Also fix the KCommand bug in the help buttonspec?

**Comment by Wagnerp** [comment]
Opened up #791
