### ISSUE TITLE
[Feature Request]: Krypton Dialog Button

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#771]
Since the KManager stores strings for Ok, Cancel, Yes, No etc, maybe we should use this feature to create a standalone `KryptonDialogButton` control?

**Comment by Smurf-IV** [comment]
Or remove KManager string the usage,
Or, do the localisation properly (As there are many areas that need to have localised strings !)

**Comment by Wagnerp** [comment]
Not needed, as something similar is implemented in the extended toolkit
