### ISSUE TITLE
[Bug]: KryptonTableLayoutPanel throwing exception when a form is minimized

### ISSUE THREAD

**Issue by ZXBITLES** [Krypton-Suite/Standard-Toolkit#774]
**Describe the bug**
KryptonTableLayoutPanel throwing exception when a form is minimized

**To Reproduce**
Add KryptonTableLayoutPanel to a form and minimize it in runtime.

**Expected behavior**
No Exception should ne thrown.

**Solution**
KryptonTableLayoutPanel.cs must be modified like this:
        private void BackGroundPanel_Refreshed()
        {
            **if (_backGroundPanel.Height == 0 || _backGroundPanel.Width == 0) return;**
            _bm = new Bitmap(_backGroundPanel.Width, _backGroundPanel.Height, PixelFormat.Format32bppRgb);
            _backGroundPanel.DrawToBitmap(_bm,
                new Rectangle(0, 0, _backGroundPanel.Width, _backGroundPanel.Height));
            BackgroundImage = _bm;
        }

**Comment by Wagnerp** [comment]
Please retry using nightly build >= .188

**Comment by ZXBITLES** [comment]
Thanks!

**Comment by Wagnerp** [comment]
@ZXBITLES Is this working now?

**Comment by ZXBITLES** [comment]
Sorry. I tried branch "alfa", but it has no changes. Have no idea where is "nightly" branch. :)

**Comment by Wagnerp** [comment]
The changes were made in [this](https://github.com/Krypton-Suite/Standard-Toolkit/tree/alpha-fix%23603) branch

**Comment by ZXBITLES** [comment]
Thanks. Will check it on weekend.

**Comment by Wagnerp** [comment]
@ZXBITLES Can I close this now?

**Comment by ZXBITLES** [comment]
Yeah! Thanks!
