### ISSUE TITLE
[Bug]: Menu no longer scales on a 96 -> 240 DPI monitor

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#778]
From user **gumby** via Discord

Hoping somebody can help.  As soon as we set the `GlobalApplyToolstrips` to true the menu no longer scales on a 96 -> 240 DPI monitor.  Are we missing something?

```cs
            KryptonManager manager = new KryptonManager();
            manager.GlobalApplyToolstrips = false;
            manager.GlobalPaletteMode = PaletteModeManager.ProfessionalSystem;
```

No exception is thrown just the MenuStrip scales incorrectly.  i.e. The font becomes really small when moving from the 96 to 240 DPI

**Comment by Smurf-IV** [comment]
Seems to be okay in the Demo App:
![image](https://user-images.githubusercontent.com/2418812/179348298-2191979e-7ae5-4ec5-a7dc-a1f89765b57a.png)

with the following setting:
![image](https://user-images.githubusercontent.com/2418812/179348317-0014cbdf-245e-4623-b0d5-848a7ac816bb.png)

**Comment by Wagnerp** [comment]
Here's the start of the Discord message exchange https://canary.discord.com/channels/620577714889424916/620577714889424918/994516359847366716

**Comment by greengumby** [comment]
@Smurf-IV Isn't your demo app .net 4?

**Comment by Smurf-IV** [comment]
As a workaround, use the following in `programs.cs`:
`Application.SetHighDpiMode(HighDpiMode.SystemAware);`

The `PerMonitorV2` setting is all confused for the Krypton if monitor 2 is set to 200% scaling and is also set as the main monitor, when Monitor 1 is set to a different dpi setting
