### ISSUE TITLE
[Feature Request]: Remove shadows for context menus

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#789]
Remove shadows for context menus. Or add property to turn on and off.

**Comment by Wagnerp** [comment]
I would make this an optional feature...

**Comment by Smurf-IV** [comment]
@sdreb3421 do you mean `KryptonContextMenus` or the standard winform `Contextmenu`
Also can you give some pictures and OS this is on please>

**Comment by Smurf-IV** [comment]
In the mean time, to "negate" the obvious effect of the OS drop shadow, remove the Right and Bottom outer border drawing:
![image](https://user-images.githubusercontent.com/2418812/192138894-bffc1ea8-a425-4fe8-ac96-98112299d13b.png)

**Comment by sdreb3421** [comment]
Using Windows 10. Here is a screenshot I have from a previous post #689 to show the KContextMenu shadows. 

![161946480-1ed25373-5657-4584-9ae7-645932a39496](https://user-images.githubusercontent.com/1911567/192155453-6840853a-e3a6-46db-8a13-feb38ccb6bc5.png)

**Comment by Smurf-IV** [comment]
This can "Now" be done by setting the designer value as follows:
![image](https://user-images.githubusercontent.com/2418812/198879851-c9cbbddf-7abd-4f17-a495-af31f4948a77.png)

This then leads to the following: (No shadow on the controls menu)
![MenuShadow](https://user-images.githubusercontent.com/2418812/198879865-32a68d95-beb5-430f-8010-1a41c8f80e5d.gif)

**Comment by sdreb3421** [comment]
Nice!

**Comment by sdreb3421** [comment]
I just updated to the newly released stable version and this is not included. Should it have been?

**Comment by Wagnerp** [comment]
> I just updated to the newly released stable version and this is not included. Should it have been?

Hi @sdreb3421, no, this fix is currently in v80. The first canary release will be 21st November.

**Comment by sdreb3421** [comment]
@Wagnerp I just installed the v80 canary and tested the KryptonContextMenu.HasShadow property. I am able to see the property in designer properties window, but it does not get updated in the designer.cs file. I'm also not able to access the property programatically.

**Comment by Wagnerp** [comment]
@Smurf-IV 

> I just installed the v80 canary and tested the KryptonContextMenu.HasShadow property. I am able to see the property in       > designer properties window, but it does not get updated in the designer.cs file. I'm also not able to access the property             
> programatically.

?

**Comment by Wagnerp** [comment]
> @Wagnerp has the merge been mangled when it was moved into canary ?

@Smurf-IV It might have been overwritten by a later merge in `alpha`. Wonder if it exists in today's nightly, .327?

**Comment by Wagnerp** [comment]
If not, assign this to me & I'll reintroduce it

**Comment by Smurf-IV** [comment]
@Wagnerp `HasShadow` is no longer in the alpha branch

**Comment by Smurf-IV** [comment]
@Wagnerp FYI: pushed directly into alpha

**Comment by Wagnerp** [comment]
@Smurf-IV Will apply the fixes to the branch that I'm currently working on

**Comment by sdreb3421** [comment]
I just installed the latest canary. The property StateCommon.HasShadow is accessible programmatically and works. However, the property is no longer shown in designer properties.

**Comment by Wagnerp** [comment]
> I just installed the latest canary. The property StateCommon.HasShadow is accessible programmatically and works. However, the property is no longer shown in designer properties.

@sdreb3421 This might be fixed with the next (unreleased) `nightly` build

**Comment by Wagnerp** [comment]
@sdreb3421 I can confirm that it'll be fixed in tomorrows `nightly` build

**Comment by sdreb3421** [comment]
Awesome, I'll test it out
