### ISSUE TITLE
[Feature Request]: Remove tool tip shadows for Min, Max, Close buttons

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#790]
Remove tool tip shadows for Min, Max, Close buttons. Alternatively, give access to their tooltip properties, which already  includes tooltip shadows.

**Comment by Smurf-IV** [comment]
@sdreb3421 Can you give the OS and some sample pictures please ?

**Comment by sdreb3421** [comment]
Using Windows 10. Here is a screenshot I have from a previous post #689 to show the tool tip shadows. This image isn't for the min max buttons, but it looks exactly the same. 

![161946398-a460c579-8ef2-4ad8-9e16-7d1860060af8](https://user-images.githubusercontent.com/1911567/192155389-ce207e3a-894e-4548-990e-7f5ecc4047e7.png)

**Comment by Smurf-IV** [comment]
This is already possible by setting the shadow property on the Form buttons you need to not have the shadow on:
![Tooltips](https://user-images.githubusercontent.com/2418812/198878256-f519ec93-725e-4d90-aa1b-8f4bea997c6d.gif)

**Comment by sdreb3421** [comment]
Oh thank you, I didn't realize we could access those objects.
