### ISSUE TITLE
[Bug]: Unable to use mouse to select KNavigator page in designer 

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#793]
Using Visual Studio 2022 and NET6 designer. I assume this is an issue with NET6 designer. I am unable to target multiple frameworks due to Nuget library incompatibilities.

Cannot use mouse to select KNavigator page in designer.

**Comment by Smurf-IV** [comment]
>  I assume this is an issue with NET6 designer

Correct, Just tested it with the "Navigator Modes 2022" example, and with just .net6 as the type, it does not work, but including .net48 (As per other workarounds for the designer) then it's okay.
I used VS 2022 17.7.3

**Comment by Smurf-IV** [comment]
This is now documented as the recommended way of doing things
