### ISSUE TITLE
[Feature Request]: PerMonV2 Support

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#794]
I don't know if this is relevant, but it may aid in fixing scaling issues... https://github.com/dotnet/winforms/issues/6268

**Comment by Smurf-IV** [comment]
Using todays V85 code base:
- Set Left monitor to 200%
- Right monitor (Same make) to 125%
- Record app transitioning (Dragging) from left to right
- Works as expected ;-)

![PerMon](https://github.com/user-attachments/assets/b8f89450-ef40-476f-9703-3e8a2e58f66c)

@PWagner1 Can this be closed now ?
