### ISSUE TITLE
[Question]: Issue with adding components on toolbox

### ISSUE THREAD

**Issue by rahulmaxi** [Krypton-Suite/Standard-Toolkit#798]
Hi,

Post installation of package via command line and I tried to add the control on the toolbox but got the following error.
Really appreciate your help to understand what has gone wrong. I am using VS2015 with .Net 4.8.

![image](https://user-images.githubusercontent.com/51871905/184496851-43f02530-f5ec-49f3-8a64-0aa52cb8e252.png)

Thanks,
Rahul

**Comment by Wagnerp** [comment]
> 

Hi @rahulmaxi 

If you've installed by NuGet, you may need to rebuild your project for the toolbox to populate

**Comment by rahulmaxi** [comment]
Hi @Wagnerp ,

Thank you for prompt response.
I rebuild the solution but no luck. It is still same error.

**Comment by Wagnerp** [comment]
> Hi @Wagnerp ,
> 
> Thank you for prompt response. I rebuild the solution but no luck. It is still same error.

Hi @rahulmaxi 

Is it possible to create a video or get step by step screenshots of how you're installing the packages?

**Comment by rahulmaxi** [comment]
Hi @Wagnerp ,

Please find below the document with snippets.

[KryptonNugetInstallation.docx](https://github.com/Krypton-Suite/Standard-Toolkit/files/9331592/KryptonNugetInstallation.docx)

Thanks,
Rahul.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

Hopefully this video is useful to you.

![Install Krypton](https://user-images.githubusercontent.com/949607/184502423-5bc75bc9-87c6-4ea7-b242-c8790f1ebf2c.gif)

**Comment by DarthVader85PA** [comment]
Hi @rahulmaxi 

This is not necessary.
Save your project and build it once. Then the entries are generated automatically by Visual Studio. You may need to restart Visual Studio and reload your project.

It always works fine for me and Visual Studio 2017/2019/2022 Pro.

Greetings from Germany,
DarthVader85PA

**Comment by rahulmaxi** [comment]
Hi @Wagnerp and @DarthVader85PA 

Thank you for your comments. I was using VS2015. I install VS2017 CE now and could see those.
But it do not have icons visible. It is fine as the tools are appearing however would be great if you can help me to get the icons as well. :) 

Thank you so much for your help.

![image](https://user-images.githubusercontent.com/51871905/184524182-6374ef40-9dc1-4cdc-a07d-cd0de70e7875.png)

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

This is normal for VS 2017/2019 as it's a bug with Visual Studio itself. The bug is fixed in VS 2022, if you want to install that.

**Comment by Wagnerp** [comment]
Hi @rahulmaxi 

Can this be closed?

**Comment by Wagnerp** [comment]
Closing, no action needed.
