### ISSUE TITLE
[Question]: Ribbon theme is different at runtime

### ISSUE THREAD

**Issue by rahulmaxi** [Krypton-Suite/Standard-Toolkit#799]
Hi,

I'm getting different theme and color than what was selected in VS Studio.
I have changed the default ribbon style - BackInactiveStyle to **Header - Dock - Active** in this example. But whatever I select, I always have the same output.
Not sure what I'm really missing now. 

![image](https://user-images.githubusercontent.com/51871905/184526107-41978a98-c36a-43ca-9e04-90eab56e2dd7.png)

Thanks,
Rahul.

**Comment by DarthVader85PA** [comment]
Hi @rahulmaxi 

I use on the main form the components `KryptonThemeManager` and `KryptonPalette`.
In properties of `KryptonThemeManager` you can set `GlobalPalette`. Use your component of `KryptonPalette`.
In properties of `KryptonPalette` you can change many settings for your individual design. ;)

I hope this could help?

Greetings, 
DarthVader85PA
