### ISSUE TITLE
[Bug]: KryptonTextBox not raising KeyUp event

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Standard-Toolkit#800]
**Describe the bug**
As in the video

**Screenshots**
https://user-images.githubusercontent.com/30633382/184606403-8a5ae3d5-7ef1-4389-83e9-137f37d98a12.mp4

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Version 21H2

**Additional context**
Used package
Krypton.Toolkit.Nightly 70.22.8.225-alpha

**Comment by Wagnerp** [comment]
Hi @W4TR1X 

This has now been fixed, it'll be in Monday's `nightly` build.

**Comment by Wagnerp** [comment]
Resolved - 22/08/2022
