### ISSUE TITLE
[Bug]: Button spacing is too small

### ISSUE THREAD

**Issue by kfcalf** [Krypton-Suite/Standard-Toolkit#808]
**Describe the bug**
The Button in Ribbon tab spacing is too small.
![Snipaste_2022-08-24_14-06-58](https://user-images.githubusercontent.com/28503355/186343157-ac3c95c8-f5ab-480c-bf83-d5a202540af8.png)

**Comment by Smurf-IV** [comment]
There is now spacing around the image:
![image](https://user-images.githubusercontent.com/2418812/198869442-38688450-1c63-4b6d-aa05-4fc2b58f7678.png)
