### ISSUE TITLE
[Bug]: Office 2010 - Silver (Light Mode) - KryptonDataGridView throw exception on hover

### ISSUE THREAD

**Issue by onezerotrash** [Krypton-Suite/Standard-Toolkit#809]
**Describe the bug**
When use "Office 2010 - Silver (Light Mode)" datagridview produce System.IndexOutOfRangeException when hover row cells or column header cells with a lot of text which does not fit in the column. In this situation should appear tooltip popup.

**To Reproduce**
1. Add MainForm which inherit form KryptonForm.
2. Add KryptonManager to form and set Office 2010 - Silver (Light Mode).
3. Add KryptonDataGridView and text colums.
4. Add rows with cells which contains a lot of text.
5. Hover cell and wait for tooltip popup.

**Expected behavior**
Should appear tooltip popup.

**Desktop:**
 - OS: Windows 10
 - Krypton.Toolkit 65.22.6.152
 - .NET Framework 4.8

**StackTrace**
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in Krypton.Toolkit.dll
Indeks wykraczał poza granice tablicy.
   w Krypton.Toolkit.PaletteOffice2010SilverLightModeBase.GetBackColor2(PaletteBackStyle style, PaletteState state)
   w Krypton.Toolkit.PaletteRedirect.GetBackColor2(PaletteBackStyle style, PaletteState state)
   w Krypton.Toolkit.PaletteBackInheritRedirect.GetBackColor2(PaletteState state)
   w Krypton.Toolkit.PaletteBack.GetBackColor2(PaletteState state)
   w Krypton.Toolkit.RenderStandard.DrawBack(RenderContext context, Rectangle rect, GraphicsPath path, IPaletteBack palette, VisualOrientation orientation, PaletteState state, IDisposable memento)
   w Krypton.Toolkit.ViewDrawCanvas.RenderBefore(RenderContext context)
   w Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   w Krypton.Toolkit.ViewManager.Paint(RenderContext context)
   w Krypton.Toolkit.ViewManager.Paint(IRenderer renderer, PaintEventArgs e)
   w Krypton.Toolkit.VisualPopup.OnPaint(PaintEventArgs e)
   w System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   w System.Windows.Forms.Control.WmPaint(Message&amp;amp; m)
   w System.Windows.Forms.Control.WndProc(Message&amp;amp; m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message&amp;amp; m)
   w System.Windows.Forms.ContainerControl.WndProc(Message&amp;amp; m)
   w Krypton.Toolkit.VisualPopup.WndProc(Message&amp;amp; m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp;amp; m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp;amp; m)
   w System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Wagnerp** [comment]
Hi @onezerotrash 

Could you upload a sample app for investigation please?

**Comment by onezerotrash** [comment]
[SampleKryptonDataGridView.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/9432100/SampleKryptonDataGridView.zip)

**Comment by Wagnerp** [comment]
Hi @onezerotrash 

Thanks for the upload, under further investigation, it turns out that this theme has not been completed yet.

**Comment by Wagnerp** [comment]
Hi @onezerotrash 

Found the issue, will be fixed in tomorrows `nightly` build

**Comment by Wagnerp** [comment]
Hi @onezerotrash 

Please retry using `nightly` build >= `241`

**Comment by onezerotrash** [comment]
Now it looks fine and it works.

**Comment by Wagnerp** [comment]
Fixed - 29/08/2022
