### ISSUE TITLE
[Other Issues]: Can the "6.x.Lite" version only support `.net48;net5.0-windows;net6.0-windows`

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#81]
**Is your feature request related to a problem? Please describe.**
Win7 can install 4.8 and is the default framework for Win 10

**Describe the solution you'd like**
A breaking change to go with the introduction of .Net 6

**Describe alternatives you've considered**
Going back to individual builds into individual nugets ..

**Comment by Wagnerp** [comment]
Will change it in the `alpha` branch
