### ISSUE TITLE
[Bug]: Krypton Form opened as child does not allow Text box claret positioning

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#812]
Krypton Toolkit 65.22.6.152

All my forms where originally created as normal Windows Forms ( Inherits System.Windows.Forms.Form )

I change the line to ' Inherits Krypton.Toolkit.KryptonForm ' to convert the existing forms into Krypton forms

All works well except for forms that are children ( Frm_Admin_Staff.MdiParent = Me ) do not allow the claret to be positioned arbitrarily within a textbox / combobox. Double clicking a word in the textbox, highlights the full words as expected, but the claret will only position itself at the end ( requiring arrow keys to move it )

Windows form ( Inherits System.Windows.Forms.Form )
![2022-08-30_10h21_53](https://user-images.githubusercontent.com/84494183/187400806-80a73ca0-eb3e-4e09-b1ed-57339d487636.gif)

Converteds to Krypton Form ( Inherits Krypton.Toolkit.KryptonForm )
![2022-08-30_10h25_13](https://user-images.githubusercontent.com/84494183/187401260-ac7f1979-6945-42a5-b982-93212c2126ba.gif)

Is this a bug, or is there something else I need to do to convert from Windows to Krypton forms

**Comment by Smurf-IV** [comment]
you have stated:
> Converteds to Krypton Form ( Inherits Krypton.Toolkit.KryptonForm )

does this mean that you have not converted the contained controls to be also Krypton components.
Perhaps that is the missing step

**Comment by MattH-Work** [comment]
EVERYTHING bar one control ( DG.AdvancedDataGridView, https://github.com/davidegironi/advanceddatagridview  )  in the form is a Krypton control of some description. As you can see in the original video, there are rounded borders to the textboxes, indicative of a Krypton control.

**Comment by Smurf-IV** [comment]
I have tried to replicate, (and setting parent when opening - see code), but I have not been able to:
Is there something else ?
![TextBox](https://user-images.githubusercontent.com/2418812/205437446-081679e1-32b4-4b42-9a99-59dd4d656538.gif)

Also you state that you have set the `MDIParent` if so then this needs to use the Docking / Workspace toolkits (I think)
