### ISSUE TITLE
[Feature Request]: `KryptonForm` Enhancement - A option to disable/enable the close button

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#819]
There are already options to do this with the maximise & minimise, but why not the close button?

**Comment by Smurf-IV** [comment]
@Wagnerp Do you mean the equivalent of these ?
![image](https://user-images.githubusercontent.com/2418812/198869633-9b692224-b707-4bb3-a745-79cc4271088f.png)

i.e. to make them visible or not,
Or, is this a runtime setting you have found ?

**Comment by Wagnerp** [comment]
> @Wagnerp Do you mean the equivalent of these ? ![image](https://user-images.githubusercontent.com/2418812/198869633-9b692224-b707-4bb3-a745-79cc4271088f.png)
> 
> i.e. to make them visible or not, Or, is this a runtime setting you have found ?

@Smurf-IV Yes, currently the only similar way to do it is to 'hide' the control box. But that then hides the other two controls.

**Comment by Smurf-IV** [comment]
Ok, I have found the code:
![image](https://user-images.githubusercontent.com/2418812/198869816-89004da2-8699-4f12-b5ee-e0c03f70522a.png)

And in the Max / min button classes this sort of thing:
![image](https://user-images.githubusercontent.com/2418812/198869836-925ddd3b-b7a8-47fa-b29f-5531bbfd89d1.png)

So to make it "Work" it will need to be both a designer AND a programmatic thing?
i.e.
1) Make is Visible / invisible like the max . min designer
2) AND make it programmatic based on a "User" condition value as well ?

**Comment by Wagnerp** [comment]
Something similar to this https://www.codeproject.com/Articles/93959/WinForm-Extended

> CloseButton:

> I added a new property called `CloseButton`. By setting this property to false, the window close button will be grayed out and > the user will no longer be able to close the form. The form is still closable if: The parent form gets closed, the task manager   > closes the application, windows shuts down or there is a call to Application.Exit()

**Comment by Wagnerp** [comment]
> Ok, I have found the code: ![image](https://user-images.githubusercontent.com/2418812/198869816-89004da2-8699-4f12-b5ee-e0c03f70522a.png)
> 
> And in the Max / min button classes this sort of thing: ![image](https://user-images.githubusercontent.com/2418812/198869836-925ddd3b-b7a8-47fa-b29f-5531bbfd89d1.png)
> 
> So to make it "Work" it will need to be both a designer AND a programmatic thing? i.e.
> 
> 1. Make is Visible / invisible like the max . min designer
> 2. AND make it programmatic based on a "User" condition value as well ?

Colour changes may need to be done in the 2010/13/365 themes as well. I think I've added a '// Note:' prompt in them

**Comment by Smurf-IV** [comment]
There is something in the "Ribbon Control" that ignores the settings !!
Anyway, Does this need to disable "Alt+F4" if the Close is Disabled / inivisible ?

**Comment by Wagnerp** [comment]
> Does this need to disable "Alt+F4" if the Close is Disabled / inivisible ?

No, though it could be added sometime in the future...

**Comment by Smurf-IV** [comment]
Design time visibility (Similar to the Max / Min):
![image](https://user-images.githubusercontent.com/2418812/198876162-08973e6a-9b65-48ac-8fc4-c87b6e137bb7.png)

Programmatic Enabled (Disable) of the button:
![image](https://user-images.githubusercontent.com/2418812/198876127-e506612f-c456-4289-83e6-94ca0b068b51.png)
