### ISSUE TITLE
[Feature Request]: ComboBox Should be able to have *Hint's*

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#82]
**Describe the solution you'd like**
Similar to the Current Text Box implementation(s) and not just when it is an edit box

**Describe alternatives you've considered**
2 ways are described in the same way that the Current text box does it via `"EM_SETCUEBANNER"`
and also via `CB_SETCUEBANNER`:

https://jasonkemp.ca/blog/the-missing-net-1-cue-banners-in-windows-forms-em_setcuebanner-text-prompt/

**Comment by Smurf-IV** [comment]
@Wagnerp VS has done it again..
Please review the changes : https://github.com/Krypton-Suite/Standard-Toolkit/commit/a142638ae5cbfb5787574e867a5f2198fe0dc77a and then close this (I haven't updated the readme!)

**Comment by Wagnerp** [comment]
@Smurf-IV On it, looks good to me. Will update Readme
