### ISSUE TITLE
[Question]: `KryptonChekedListBox` - How do we check the boxes programmatically

### ISSUE THREAD

**Issue by jdelestre** [Krypton-Suite/Standard-Toolkit#823]
Hello

How do we check the boxes programatically?
There is no "Checked" property?
And the KryptonListItem object only has ShortText and longtext property.

Thanks

**Comment by Smurf-IV** [comment]
A: The same way you would do in a Winform `CheckedListBox`..
i.e. `kryptonCheckedListBox.SetItemCheckState(2, CheckState.Checked);`
