### ISSUE TITLE
[Feature Request]: Expose `IPalette / PaletteBase` as a public interface in `KryptonManager`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#827]
The `KryptonManager` needs an overhaul to accept palette files (non-XML based) that might be out of the range of this toolkit. Currently, `KryptonManager` is a _sealed_ class, which makes injecting new themes more difficult. See https://github.com/Krypton-Suite/Theme-Palettes/issues/33 for more discussion.

**Comment by Wagnerp** [comment]
@Smurf-IV Just a thought, since all built-in palettes use `IPalette`, can't we just expose it in `KryptonManager`? See `PaletteBase` for details.

**Comment by Smurf-IV** [comment]
@Wagnerp What "Other things" is this "Overhaul" expected to do?
Otherwise this issues is just to expose `IPalette` and then wait for the rest of the theming to catch up ?

**Comment by Wagnerp** [comment]
@Smurf-IV We can just test exposing `IPalette` is there also a way to 'open' up `PaletteBase`, so that we can build external classes, like the ones' in the 'builtin' directory?

**Comment by Smurf-IV** [comment]
Progress:
- Remove `IPalette` and use `PaletteBase` instead
- Fix fallout in abstract class useage
- Rename `KryptonPalette` to `KryptonCustomPaletteBase` to reflect usage
- _Start_ to sort out code in `ThemeManager`
- More fixes for the ThemeComboBoxSelector

**Comment by Wagnerp** [comment]
I'll update the Extended Toolkit where required
