### ISSUE TITLE
[Bug]: Krypton Combobox - Not honouring hosts enabled state

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#836]
Below worked as expected in 65.22.6.152
Broken 70.22.11.312

I have a 100's of Krypton comboboxes hosted within 10's of KryptonHeaderGroup's in LOTS of forms
The KryptonHeaderGroup panel is disabled (enable = false) via the designer

I enable/disable the KryptonGroupPanel programatically during runtime as and when required
ALL other controls hosted by the KryptonGroupPanel  enable/disable correctly, BUT KryptonComboBoxes do not, they stay disabled (but look enabled, ie not greyed out)

It seems that Comboxes a honouring the enabled state initially, but do not change when the host enabled states changes (See video below "Disabled in Designer")

I have found that setting the enabled state to TRUE in the designer, then setting it to FALSE as the last line of code in the Forms 'Shown' event solves the issue, but this is a workaround (see video below "Enabled In Desiner, Disabled in Shown event")

Annoyingly, I can not replicate this issue in a new 'Test' solution, but I am logging it here 'just in case' someone else has a similar issue, or has a fix

https://user-images.githubusercontent.com/84494183/202461758-694bcc7b-fa8a-4106-9a4e-0e306aba1402.mp4

https://user-images.githubusercontent.com/84494183/202461777-cd42776e-6b07-40c0-81cc-c5599cb06bf4.mp4

**Comment by Smurf-IV** [comment]
Agreed; cannot replicate:
![DisabledParent](https://user-images.githubusercontent.com/2418812/204144439-abc85188-3000-4b0e-8ba5-e983e25cb0e7.gif)
