### ISSUE TITLE
[Bug]: Cannot add items to KryptonGroupBox in WinForms Designer

### ISSUE THREAD

**Issue by bytehammer2** [Krypton-Suite/Standard-Toolkit#838]
Bug #91 Has not been resolved. 

I'm using Krypton.Toolkit Stable Version 70.22.11.312, VS 2022 Version 17.4, Windows 10.

**Comment by Wagnerp** [comment]
Hi @bytehammer2 

Are you using .NET or .NET Framework? If you're using .NET, then we're all waiting for MS to implement [this](https://github.com/Krypton-Suite/Standard-Toolkit/discussions/684), since the WinForms Designer has been broken since .NET Core.

**Comment by imerzan** [comment]
Is there any workaround? I've tried the net48 targeting to no avail, nothing shows up in designer (using both the nuget pkg and built it myself).

**Comment by Smurf-IV** [comment]
> Is there any workaround? I've tried the net48 targeting to no avail, nothing shows up in designer (using both the nuget pkg and built it myself).

If you are using VS2022 then you have to change the vsproj to target the `WindowsDesktop` as the SDK type (First line) or
add  `<UseWindowsForms>true</UseWindowsForms>`

Sometimes it's both, but VS is a pain.

Also try turning on (or off) the preview feature : 
![image](https://user-images.githubusercontent.com/2418812/205241412-4c4d2fba-aa9c-42dd-8d8b-5a8fd537ff15.png)

**Comment by imerzan** [comment]
> > Is there any workaround? I've tried the net48 targeting to no avail, nothing shows up in designer (using both the nuget pkg and built it myself).
> 
> If you are using VS2022 then you have to change the vsproj to target the `WindowsDesktop` as the SDK type (First line) or add `<UseWindowsForms>true</UseWindowsForms>`
> 
> Sometimes it's both, but VS is a pain.
> 
> Also try turning on (or off) the preview feature : ![image](https://user-images.githubusercontent.com/2418812/205241412-4c4d2fba-aa9c-42dd-8d8b-5a8fd537ff15.png)

Thank you for the suggestion(s)! I've tried everything but can't seem to get the controls to load in my Toolbox. I even created a Fresh .NET Framework 4.8 project.

I am using VS 2022 Community (latest updates)

```Install-Package Krypton.Toolkit
Install-Package Krypton.Ribbon```

Not sure if I am doing something wrong or not. I tried resetting the Toolbox to no avail.

**Comment by imerzan** [comment]
> > Is there any workaround? I've tried the net48 targeting to no avail, nothing shows up in designer (using both the nuget pkg and built it myself).
> 
> If you are using VS2022 then you have to change the vsproj to target the `WindowsDesktop` as the SDK type (First line) or add `<UseWindowsForms>true</UseWindowsForms>`
> 
> Sometimes it's both, but VS is a pain.
> 
> Also try turning on (or off) the preview feature : ![image](https://user-images.githubusercontent.com/2418812/205241412-4c4d2fba-aa9c-42dd-8d8b-5a8fd537ff15.png)

Thank you for the suggestion(s)! I've tried everything but can't seem to get the controls to load in my Toolbox. I even created a Fresh .NET Framework 4.8 project.

I am using VS 2022 Community (latest updates)

Install-Package Krypton.Toolkit
Install-Package Krypton.Ribbon

Not sure if I am doing something wrong or not. I tried resetting the Toolbox to no avail.

**Comment by Wagnerp** [comment]
Hi @imerzan 

Would you mind posting a video of how you install the packages, as the toolbox should populate automatically?

Note to all: I'll soon be uploading a VSIX template package, which will make project creation easier.

**Comment by imerzan** [comment]
I was able to get it working w/o the designer, so it's all good. I am still testing the waters whether I will use this long term or not. May wait and see RE: Designer Support from Microsoft.

**Comment by Smurf-IV** [comment]
Coming to a PR Soon:
![DropOntoGroupBox](https://user-images.githubusercontent.com/2418812/230764949-382de860-4c1b-4d7b-a51c-7a7ce4403471.gif)

**Comment by Smurf-IV** [comment]
With TFM of .net6 the following message is visible:
![image](https://user-images.githubusercontent.com/2418812/230765337-a50fda52-2e73-4fb2-ac8e-0ef77e6df787.png)

**Comment by goldorakiller** [comment]
Hello,
I still have this error.
Winforms net8.0 project and Krypton 105.26.4.110

**Comment by PWagner1** [comment]
> Hello, I still have this error. Winforms net8.0 project and Krypton 105.26.4.110

Hi @goldorakiller 

Please can you try https://krypton-suite.github.io/Standard-Toolkit-Online-Help/articles/Support/DesignerFix.html? The design server does not work with .NET projects only yet.

cc. @Krypton-Suite/reviewers
