### ISSUE TITLE
[Question]: what are the differences between the Nightly,Canary and Stable。

### ISSUE THREAD

**Issue by HardToFail** [Krypton-Suite/Standard-Toolkit#840]

**Comment by Wagnerp** [comment]
Hi @HardToFail 

Please read [this](https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/Documents/Development/Development-Workflow.md), as it describes all the versions

**Comment by HardToFail** [comment]
@Wagnerp Thanks

**Comment by Wagnerp** [comment]
@HardToFail A better document will be coming soon

**Comment by Smurf-IV** [comment]
>  A better document will be coming soon

Will leave this open so that it can be tracked

**Comment by Wagnerp** [comment]
Implemented 11/12/2022
