### ISSUE TITLE
[Feature Request]: Theme ComboBox - Live previews

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#843]
When hovering over an item in the `KryptonThemeComboBox`, it should show a 'live' preview of the theme without it changing the actual theme. This would act like the Office live previews feature, 2007 & newer.

**Comment by Smurf-IV** [comment]
@Wagnerp Can you add an animated gif please ?

**Comment by Wagnerp** [comment]
> @Wagnerp Can you add an animated gif please ?

@Smurf-IV Similar to this feature

![843](https://user-images.githubusercontent.com/949607/222950176-fafc778d-8bda-4efe-af06-a7c0c3d1c59f.gif)

**Comment by Smurf-IV** [comment]
Scrolling the Theme ComboBox is fast enough.

**Comment by Wagnerp** [comment]
Closing, as scrolling performs a similar action.
