### ISSUE TITLE
[Bug]: Krypton Toolit 70.22.11.312 - Combobox drop down button height

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#845]
Not sure if this is a bug, limitation, or I can't find where to change

Notice that when the control height changes, DateTimePickers automatically adjust the drop down button, whereas Comboboxes have a fixed height, can Comboboxes be modified to act in the same way as DateTimePickers

![image](https://user-images.githubusercontent.com/84494183/203832214-662c68ab-4710-4953-b61a-c95b23fce3c7.png)

**Comment by Smurf-IV** [comment]
Note: the `KDateTimePicker` is a wholly owned control by Krypton, whereas the `KComboBox` is a derived class with drawing overrides.

**Comment by Smurf-IV** [comment]
The "Height" of the button is related to the "MeasureItem" size of the contents being displayed in the text area.
So If the font size is set large, 
![image](https://user-images.githubusercontent.com/2418812/204145375-3c2ae37f-b8e4-45cb-a1ab-6fa2c265a287.png)

then the button height is also large:
![image](https://user-images.githubusercontent.com/2418812/204145354-47f63270-f4b9-4462-a1c3-bd8ad229a442.png)
