### ISSUE TITLE
[Bug]: KryptonTreeView Font Issues

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#848]
The KryptonTreeView does not set/match the TreeView.Font property when setting the StateCommon Node Font property. 

This causes the following two issues:

1. Label edit does not show the proper font size.
2. Horizontal scroll bars do not use the proper width calculation and nodes can be scrolled out of view.

The workaround for this is to programmatically set the TreeView.Font property to match the palette Font setting for the Nodes.

**Comment by Smurf-IV** [comment]
I am unable to see this bug:
![KTreeView](https://user-images.githubusercontent.com/2418812/205436709-802be95b-c2e9-4a61-8ef8-a347f383dc80.gif)

**Comment by sdreb3421** [comment]
I didn't see the horizontal scroll bar appear in your video, which is necessary for the test. Try making the node names longer and the horizontal scroll bar either won't appear or won't scroll to the right far enough to show all the text. 

The other half of the test involves editing node text with label edit, which I didn't see you try either.

**Comment by Smurf-IV** [comment]
Thanks for the clarifications.

**Comment by Smurf-IV** [comment]
Hmm:
![image](https://user-images.githubusercontent.com/2418812/205485162-15ffa639-8537-40ed-a586-37f278707ae0.png)

**Comment by Smurf-IV** [comment]
Done:
![TreeViewFont](https://user-images.githubusercontent.com/2418812/205490205-85be364e-39b4-4a29-8a16-184fbb32269a.gif)

**Comment by Wagnerp** [comment]
Completed 04/12/2022

**Comment by sdreb3421** [comment]
I looked at the source changes and it appears the fix was the same as my work around, that's rare. Nicely done!
