### ISSUE TITLE
[Bug]: KryptonDataGridView unbound cell - cannot set value

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#849]
**Describe the bug**
If `KryptonDataGridView` binded to a `DataSet` with `DataTable`'s and a `BindingSource` a unbound cell is not possible to change a value. Not by user and not by programmatically.

I tested it with a Standard-DataGridView and it works.

I use the last Krypton-NuGet-Package 70.22.11.312 with Visual Studio 2019 and .NET-Framework 4.8

"Projekt" is our unbound column:
![KryptonDataGridView_UnboundCellValue](https://user-images.githubusercontent.com/32876506/204813576-fbac2a55-9958-403c-bdae-4e11bd6c79e7.gif)

**Comment by giduac** [comment]
KryptonDataGridView and it components have several shortcomings which we will try to address in the V100 release or earlier if possible.

**Comment by giduac** [comment]
Hi @DarthVader85PA,

I gave this a try and could not reproduce the error. 
The column in the middle is the unbound column.
The TK version used: 90.24.10.296-beta

https://github.com/user-attachments/assets/8a41ebd6-bbbc-4dc5-8a69-860434f43bb6


Can you please have a look at the sample project:
<https://github.com/giduac/B849_UnboundCellCannotSetValue>

**Comment by giduac** [comment]
Cannot reproduce.
No further reaction from the reporter.

Will close, ticket can be reopened if needed.
