### ISSUE TITLE
[Other Issues]: Update the project names from `2019` to `2022`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#85]
As part of v6, **all** project names need to be updated to `2022` to reflect the upcoming Visual Studio 2022 release.

**Comment by Smurf-IV** [comment]
At least wait until 2022 is released please.

**Comment by Wagnerp** [comment]
They are planning to release a beta version in the summer, with the RTM in the autumn. Won't be changed until then.

**Comment by Smurf-IV** [comment]
OK, Just that i have seen 2022 labelled branches, which may / will be out of date by then

**Comment by Wagnerp** [comment]
Will pull in the changes when the time comes, and will rename using `ctrl + v`

**Comment by Wagnerp** [comment]
Implemented in the August 2021 (Canary) update

**Comment by Wagnerp** [comment]
Implemented in build 2201
