### ISSUE TITLE
[Question / Bug] Cannot localize toolkit controls

### ISSUE THREAD

**Issue by waleedmakarem** [Krypton-Suite/Standard-Toolkit#851]
Dear sir,

for Component factory krypton controls, does it support localization ? I tried to localize form with normal winform controls, it works pretty good. when I add component factory toolkit controls, localization does not work. 
Please advise. 

Thanks,
Waleed

**Comment by Smurf-IV** [comment]
@waleedmakarem Do you Mean "Component factory krypton" (Which is another repo which uses an older set of these) or this "Krypton-Toolkit"?

**Comment by waleedmakarem** [comment]
Dear Smurf_IV, 
Actually I have tested into original (old) control . I assume it is the same case into this repo. 
Kindly advise if this repo can support localization or not. if So, does it support .Net Framework 4.0 ?
Thanks for support

**Comment by Wagnerp** [comment]
Hi @waleedmakarem 

Are you using the `KryptonManager` `Strings` property to localise your app, or are you doing it another way?

**Comment by waleedmakarem** [comment]
I am using default .net localization process . ie set form to localizable . then having Forms design for each language. changing language will change the winform design/language settings.
Do you want me to send sample project (simple one) ?

**Comment by Wagnerp** [comment]
@waleedmakarem 

Yes please

**Comment by waleedmakarem** [comment]
Dear Wagnerp,
Thanks so much for support . During creating the demo , I found the point I was missing. 
Thanks for support , much appreciated.

**Comment by Wagnerp** [comment]
Hi @waleedmakarem 

Good to know that it's sorted out. Could you tell me what you did please, so that I can put it into the docs to help others out?
