### ISSUE TITLE
[Bug]: Ribbon QAT Button downscaled when disabling HiDPI 

### ISSUE THREAD

**Issue by tbolon** [Krypton-Suite/Standard-Toolkit#861]
**Describe the bug**

The QAT button images are resized from 16px in height to 14px when dpiAwaire=false, resulting in bad display.

**To Reproduce**
1. Use MDI Ribbon 2022 Example
2. Switch dpiAware to false
3. Change Form1: Set QATLocation to Visible (instead of Hidden)
4. Add a 16x16 png resource image
5. Add a QAT Button with this image
6. Start the app: the button is rendered resized as 16x14 instead of original 16x16

![bug](https://user-images.githubusercontent.com/127185/206705846-5eab5259-655e-4572-88d5-0cb06a08dbdd.jpg)

**Expected behavior**

The image should be left untouched.

![ok](https://user-images.githubusercontent.com/127185/206705865-eb97b67b-ae25-4b23-a3d3-5db6d82c0f43.jpg)

**Additional context**

The problem is caused by this line: https://github.com/Krypton-Suite/Standard-Toolkit/blob/896008b760dea81505c1a30aa38c4b1b56a46452/Source/Krypton%20Components/Krypton.Ribbon/View%20Draw/ViewDrawRibbonQATButton.cs#L251

If you comment this line, the image is correctly rendered.

I could not reproduce a case where this line is needed, Git history stops at * Build 2201 in 01/04/2022 where this file was added.

I suggest we simply remove this line.

**Comment by Wagnerp** [comment]
@tbolon Thanks for reporting, would you mind re-testing using todays nightly (.344)?

**Comment by tbolon** [comment]
I can confirm that this problem is not visible on Nightly, 80.22.12.344-alpha. I suppose it's visible on the alpha branch?

Do you have a timeline to share about nightly / canary / and stable releases?

**Comment by Wagnerp** [comment]
> Do you have a timeline to share about nightly / canary / and stable releases?

@tbolon Eventually, it'll be [here](https://github.com/Krypton-Suite/Documentation/blob/main/Documents/Packages/Package-Version-Descriptions.md) but [this](https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/Documents/Development/Development-Workflow.md) is the current document

**Comment by tbolon** [comment]
I am still trying to reproduce it on nightly vs stable. Can you confirm that the alpha branch on Standard-Toolkit is the current code used for nightly builds?

**Comment by Wagnerp** [comment]
@tbolon The fix is currently on branch `alpha-fr#813`

**Comment by tbolon** [comment]
Ok, so I can confirm that the bug is not present when using the nightly build.

**Comment by Wagnerp** [comment]
@tbolon https://github.com/Krypton-Suite/Standard-Toolkit/commit/852525e6385938ef14947d469551364721877d7e#diff-d80da5f703554318f715fc180e5a04312cddb752bc2761e6c0a3dfc894096b07

**Comment by tbolon** [comment]
Ok, I see your change. Are the changes in the Palette also expected?

**Comment by Wagnerp** [comment]
> Are the changes in the Palette also expected?

@tbolon Yes, as the orange borders around controls look a bit strange in dark/light themes. Hoping to also re-work the `KryptonManager` to accept external palettes in class form, in addition to the XML based ones :)
