### ISSUE TITLE
[Feature Request]: `KryptonMessageBox` Option to use system icons

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#866]
I wonder if it's possible to add an option to use native system icons in the `KryptonMessageBox`?

**Comment by Smurf-IV** [comment]
Isn't that what the 2 options that used to exist used to do ? i.e. option to use KryptonIcons used that type, whereas to use System would use `MessageBoxIcon`s type

**Comment by Wagnerp** [comment]
@Smurf-IV I don't think that option existed, I can have a look though?

**Comment by Smurf-IV** [comment]
Yupe, it did:
![image](https://user-images.githubusercontent.com/2418812/206904560-42f4fde8-7d48-4e67-9ebe-da67e4760333.png)

https://github.com/Krypton-Suite/Standard-Toolkit/blob/2421165a119e7abda0759d44effa024cfd6072d2/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Toolkit/KryptonMessageBox.cs

**Comment by Wagnerp** [comment]
Did it pull in system icons though or use third party images?

**Comment by Wagnerp** [comment]
i.e.

![image](https://user-images.githubusercontent.com/949607/206904866-b4719e91-d059-4f8d-a38c-365e16cd219b.png)

![image](https://user-images.githubusercontent.com/949607/206904895-6bdeaa4a-54b5-4cd2-8d1d-3c61b121a512.png)

![image](https://user-images.githubusercontent.com/949607/206904919-c54db8dc-4729-4a88-9ad7-11251f515678.png)

**Comment by Smurf-IV** [comment]
cannot remember,
But it will be easier to have the Multiple API's and then the icon to be used can be set in the internal code, rather than having "Yet Another Default Value" parameter passed in.

**Comment by Wagnerp** [comment]
Or just have a `useSystemIcon` as a nullable bool value?

**Comment by Smurf-IV** [comment]
> Or just have a `useSystemIcon` as a nullable bool value?

Nooo,, no more options... Lets combine all the "Options" into a flags enum to make life easy ?

**Comment by Wagnerp** [comment]
Ok, need to look at the `winforms` code to see how they get those icons from the system

**Comment by Wagnerp** [comment]
Found the appropriate API: https://learn.microsoft.com/en-us/dotnet/api/system.drawing.systemicons?view=windowsdesktop-7.0

**Comment by Wagnerp** [comment]
Done

![kmb866](https://user-images.githubusercontent.com/949607/207933745-83ee915b-675d-4ec2-ac04-9dab1b10ae47.gif)

**Comment by Wagnerp** [comment]
Implemented 17/12/2022
