### ISSUE TITLE
[Question]: How to make the caption of kGroupBox horizontal and centered?

### ISSUE THREAD

**Issue by HardToFail** [Krypton-Suite/Standard-Toolkit#870]
![image](https://user-images.githubusercontent.com/118651630/207051188-f61211c5-1e7d-4697-8f48-a50c96741c62.png)

**Comment by Smurf-IV** [comment]
Like this:
![image](https://user-images.githubusercontent.com/2418812/208238913-ea5dc94d-7336-433d-8a49-d5657e208e9f.png)
