### ISSUE TITLE
[Feature Request]: ToolStrips in the non client area of a `KryptonForm`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#872]
Similar to how the quick access toolbar works in the `KryptonRibbon` control.

https://www.codeproject.com/Articles/55180/Extending-the-Non-Client-Area-in-Aero

https://www.codeproject.com/Articles/32623/Vista-Aero-ToolStrip-on-Non-Client-Area

**Comment by Wagnerp** [comment]
Progress... 

![image](https://user-images.githubusercontent.com/949607/223206389-1404a319-db9e-4e4b-a7c9-e6f06cd2ee08.png)

@Smurf-IV Is there a way to 'shift' `ButtonSpecs` to the left after the window title?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is there a way to 'shift' `ButtonSpecs` to the left after the window title?


Can you "Mock" something up please ?
Otherwise it's just the normal padding.
I think what you are asking is to have the following order:
1) App icon
2) App title
3) Buttons
4) Elastic space
5) Close window etc. buttons 

If so, then 3 and 4 cannot currently be done.

**Comment by Wagnerp** [comment]
> Can you "Mock" something up please ?

Something like this...

![Mockup](https://user-images.githubusercontent.com/949607/223359150-ce98f8ce-495f-429c-936d-b3535b664bc7.png)

**Comment by Wagnerp** [comment]
Completed 11/03/2023
