### ISSUE TITLE
[Feature Request]: Krypton Page with CheckBox

### ISSUE THREAD

**Issue by yp25** [Krypton-Suite/Standard-Toolkit#881]
**Describe the solution you'd like**
I would like to request feature for adding checkbox in krypton page (krypton page inside krypton navigator with navigator mode : Bar - Tab- Group) like this one

![kryptonpagewithcheckbox](https://user-images.githubusercontent.com/2161156/209037788-c820f8c7-1d87-43b9-82eb-e4f2b8fda170.jpg)

Or please help to give some clue how to implement this idea. Thanks

**Comment by Smurf-IV** [comment]
You can do it with the existing functionality like this: (Choose images of the checkbox states)

![image](https://user-images.githubusercontent.com/2418812/209091832-d6b01498-bde7-4fcf-888a-01a73a04a6b0.png)

**Comment by yp25** [comment]
hi @Smurf-IV , thank you for your answer. I have tried it, but unfortunately it seems if checked set to unchecked there's no option to change the image

**Comment by Smurf-IV** [comment]
`ImageCheckNormal` is the unchecked equivalent

**Comment by Smurf-IV** [comment]
@yp25 Can this be closed?
If not can you provide an example of what you have tried with the advice above please ?
