### ISSUE TITLE
[Other Issues]: Why does the "alpha" branch think it is behind "master"

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#885]
![image](https://user-images.githubusercontent.com/2418812/209335785-e479bf2e-ae05-407e-9bb0-e65a205cc46d.png)

**Comment by Wagnerp** [comment]
@Smurf-IV It might be because all the template, workflow files are just in `master` & not in `alpha`/`canary` branches

**Comment by Wagnerp** [comment]
Resolved, but it won't take effect until `master` is updated
