### ISSUE TITLE
[Feature Request]: Is it possible to add the `LinkArea` property to a `KryptonLinkLabel`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#886]
![image](https://user-images.githubusercontent.com/949607/209390575-eb623764-b1b1-4eba-9bc5-502f7d2389ed.png)

**Comment by Smurf-IV** [comment]
Isn't this the same as #22

**Comment by Wagnerp** [comment]
> Isn't this the same as #22

Yes it is, wonder if it would be a good idea to do something similar to the rounded corners?

**Comment by Wagnerp** [comment]
Closing, can be achieved using the `KryptonLinkWrapLabel`
