### ISSUE TITLE
[Feature Request]: A 'LinkLabel' version of the `KryptonWrapLabel`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#887]
Since the `KryptonWrapLabel` is based on a standard WinForm label, can it be done with a linklabel?

**Comment by Wagnerp** [comment]
Yes, it can be done... PR coming soon!

**Comment by Smurf-IV** [comment]
Or, Just make the `KryptonLinkLabel` work like a wrap label!

**Comment by Wagnerp** [comment]
> Or, Just make the `KryptonLinkLabel` work like a wrap label!

The new `KryptonLinkWrapLabel` works really well. Possible intended usages for KMBox, where a dev may want to inlay a link into the message text.

**Comment by Wagnerp** [comment]
Done

![887](https://user-images.githubusercontent.com/949607/209431546-ed6cca53-e975-4509-86af-bddfe114318d.gif)
