### ISSUE TITLE
[Bug]: `KryptonContextMenu` .NET Core Designer Edit

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#893]
This could already be a known issue, but the NET CORE designer does not allow editing context menu items. When clicking on the Items (Collection) property in the VS Properties window there is no ... for dialog window access. Instead, you have to go to the designer.cs file and make the edits manually, or program it all in the constructor.

I'm hoping this could be fixed with a new attribute or something simple unlike the other NET CORE designer issues (ribbon edits, etc.).

**Comment by Wagnerp** [comment]
Hi @sdreb3421 

Is it just with .NET Core, or with .NET as well?

**Comment by giduac** [comment]
Hi @Wagnerp,

This related to:
- https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Support/Designer%20Fix.html
- https://github.com/Krypton-Suite/Standard-Toolkit/discussions/684

I suggest to close this call...
