### ISSUE TITLE
[Feature Request]: `KryptonPropertyGrid` needs to have full Krypton support

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#894]
`KryptonPropertyGrid` needs to have full Krypton support, i.e. 'StateCommon', 'StateDisabled' etc.

**Comment by Smurf-IV** [comment]
@Wagnerp Does the existing `KryptonPropertyGrid` have an example app / usage

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, I think it's used in `Krypton Theme Playground`

![image](https://user-images.githubusercontent.com/949607/213861965-e284851b-d6f8-477b-825f-a9d150b6d2e2.png)

You might have to set a `SelectedObject` though...

**Comment by Wagnerp** [comment]
I'll create a dedicated example

**Comment by Wagnerp** [comment]
Done

![example](https://user-images.githubusercontent.com/949607/213863705-ffd2e90d-051c-42e3-805c-9b5f6f14fe3e.gif)

**Comment by Wagnerp** [comment]
The 'problem' with the existing implementation is _how_ it manages it's colours

![image](https://user-images.githubusercontent.com/949607/213863859-66d0b6aa-551e-4855-8a8d-b8d6942a6f33.png)

**Comment by Smurf-IV** [comment]
Something like this ?
![KPropGrid](https://user-images.githubusercontent.com/2418812/232123375-a7379238-b8ae-4d23-8944-78d7f972165b.gif)

**Comment by Smurf-IV** [comment]
@Wagnerp Is this in the PaletteDesigner ?

**Comment by Wagnerp** [comment]
> Something like this ? ![KPropGrid](https://user-images.githubusercontent.com/2418812/232123375-a7379238-b8ae-4d23-8944-78d7f972165b.gif) [ ![KPropGrid](https://user-images.githubusercontent.com/2418812/232123375-a7379238-b8ae-4d23-8944-78d7f972165b.gif) ](https://user-images.githubusercontent.com/2418812/232123375-a7379238-b8ae-4d23-8944-78d7f972165b.gif) [ ](https://user-images.githubusercontent.com/2418812/232123375-a7379238-b8ae-4d23-8944-78d7f972165b.gif)

@Smurf-IV Yes, as I don't think it had proper support, as you had to 'force' it to redraw when you changed palettes.

> Is this in the PaletteDesigner ?

Yes, I changed it a few years' ago
