### ISSUE TITLE
[Feature Request]: Is it possible to modify the `FolderBrowserDialog` to use Krypton

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#896]
https://www.codeproject.com/Articles/14454/Extended-Folder-Browser

![image](https://user-images.githubusercontent.com/949607/211192873-b6e66eeb-e90f-426f-9b5b-a7d578bf316e.png)

**Comment by Smurf-IV** [comment]
The above is based on the XP control. This is the "Vista" and later style:
![image](https://user-images.githubusercontent.com/2418812/212535433-00f5fbb2-1a91-4f8d-b947-1a9ce2bc32d5.png)

Also most Folder browsers use a version of the FileOpen browser; see #267 
OOki.Dialogs now has a Winform code base which could be used to fix #267

**Comment by Smurf-IV** [comment]
Darn it.. Prior to .Net Core 3, the `FolderBrowserDialog` was **Always** the xp style =  https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog.autoupgradeenabled?view=windowsdesktop-8.0

As Krypton supports TFM 4.62 onwards, then there needs to be  a wrapper done that always give the "Same" experience.

**Comment by Smurf-IV** [comment]
Coming to a PR soon
![example](https://user-images.githubusercontent.com/2418812/230603866-c827617f-9a3e-4235-9446-99569a8233a5.png)
