### ISSUE TITLE
[Bug]: When Attempting to override the  'hide' the dotted focus border on a `KryptonLinkLabel`, Designer throws an exception / warning

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#901]
Is it possible to 'hide' the dotted border on a `KryptonLinkLabel` when pressed?

![901](https://user-images.githubusercontent.com/949607/212549998-9a538c98-5176-4225-aef0-663b0fdfeb03.gif)

**Comment by Smurf-IV** [comment]
A: That is the focus rectangle, and it is supposed to be possible to disable / hide it :
![image](https://user-images.githubusercontent.com/2418812/213862126-1c13897b-72e3-4fc1-87ee-b4d89f2d87e6.png)

But it doesn't !.. So this is now a **`[Bug]`**

**Comment by Smurf-IV** [comment]
OK, It's not a bug for the Common areas, but it supposed to be done via this:
![image](https://user-images.githubusercontent.com/2418812/213862452-34df50db-c615-40c7-afce-c8872f1480dd.png)

But that just leads to another bug in the designer when the `*.designer.cs` file is attempting to save within visual studio

**Comment by Smurf-IV** [comment]
> The same is also true for both `KryptonListView` _and_ `KryptonTreeView`

Please retest these statements and create a new bug if they still exist.

**Comment by Smurf-IV** [comment]
> OK, It's not a bug for the Common areas, but it supposed to be done via this: ![image](https://user-images.githubusercontent.com/2418812/213862452-34df50db-c615-40c7-afce-c8872f1480dd.png)
> 
> But that just leads to another bug in the designer when the `*.designer.cs` file is attempting to save within visual studio

This is no longer the case with todays alpha and VS 17.9.5
