### ISSUE TITLE
[Doc update]: `*.Nightly` builds are no longer visible in Visual Studio

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#904]
![image](https://user-images.githubusercontent.com/2418812/213700791-b9fb9094-471a-4139-aad1-bcf433b862d0.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Have you tried putting in `Krypton.` then check the 'Include prerelease' checkbox?

**Comment by Smurf-IV** [comment]
D'oh:
![image](https://user-images.githubusercontent.com/2418812/213859610-3c7c27b2-c9d8-4b3f-a993-2e04546f8288.png)

Okay, perhaps a note in the landing page dewscription on how to get to that listing (If it is not already there in the several places nightly is listed ;-))

**Comment by giduac** [comment]
Seems to work normally here...


https://user-images.githubusercontent.com/96108132/213859994-651479f7-b5ca-430d-bb7f-75472a18ae5b.mp4

**Comment by Wagnerp** [comment]
Implemented 21/01/2023
