### ISSUE TITLE
[Bug]: NuGet description for `Lite` versions is incorrect

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#905]
![image](https://user-images.githubusercontent.com/2418812/213701182-c327c9fb-8df1-427c-a7df-cd09ad45bee7.png)

**Comment by Smurf-IV** [comment]
Also .net48 is included, so that needs to be in the 1st line as well:
![image](https://user-images.githubusercontent.com/2418812/213701413-3e4e92de-fe89-430a-90a1-ff31e1db3e69.png)

**Comment by Wagnerp** [comment]
Fixed 21/01/2023
