### ISSUE TITLE
[Question]: What is the 'correct' way to insert a Krypton Form into by solution ( using Visual Basic 2019 )

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#906]
What is the 'correct' way to insert a KryptonForm into my solution ( using Visual Basic 2019 )

I currently edit the *.Designer.vb file with something similar to the following

' Inherits System.Windows.Forms.Form
  Inherits Krypton.Toolkit.KryptonForm 

As I have no way of creating a KryptonForm from scratch
![image](https://user-images.githubusercontent.com/84494183/213741135-fc23531c-66d9-4daa-85f4-bc27418a044c.png)

Cheers

MattH

**Comment by Wagnerp** [comment]
Hi @MattH-Work 

I have created a 'VSIX' package to allow new items to be created from the 'New Item/Project' dialog, but upon polling devs, people didn't really want it. If you're interested, please create a new feature request :)

**Comment by Wagnerp** [comment]
Rolled into #908
