### ISSUE TITLE
[Question]: Lite Packages

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#907]
Please can someone confirm my thinking.

The LITE packages contain everything the non LITE packages have, BUT they are only .NET 4.8 and above

If so, can I simply remove my 'full' Krypton toolkit and install the LITE version and not lose anything within my .NET 4.8 application?

Cheers

MattH

**Comment by Wagnerp** [comment]
Hi @MattH-Work 

Yes, that will work ***but*** remove the 'full' packages _first_ before installing 'lite'

**Comment by MattH-Work** [comment]
Thanks for the quick response

On a side note, I had to create the Krypton Toolkit folder myself in the Toolbox and add the controls manually, BUT I now have icons which I have never had before!!!
![image](https://user-images.githubusercontent.com/84494183/213747618-9f3287ac-ed4b-46f6-935f-4efde1c78170.png)

vs

![image](https://user-images.githubusercontent.com/84494183/213747876-1ab82c02-538a-4fdc-b1bb-0ca457757fe7.png)

**Comment by Wagnerp** [comment]
Yes, something was fixed inside Visual Studio, so icons should work now (4.8+). There are some controls wit no icon though (that's on our part).
