### ISSUE TITLE
[Feature Request]: Can the colour picker support alpha blends

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#909]
Can the colour picker used in some controls support alpha blends https://www.codeproject.com/Articles/14823/ColorEditorEx-An-extension-to-the-ColorEditor-to-s

**Comment by Smurf-IV** [comment]
e.g.: another slider next to the existing one ?
![image](https://user-images.githubusercontent.com/2418812/213859254-4d1125d8-8571-4473-a2b8-d0616da8290e.png)
And an "option in the designer" to enable it, and programmatically as well ?

The trouble - with the layout - will be adding the new entry values above the "Add to Custom colours" button, and still getting the font usage to look good.

**Comment by Smurf-IV** [comment]
A thought:
It might be possible to replace this area, with a masked edit (4 values) / text / and a slider
![image](https://user-images.githubusercontent.com/2418812/213859420-84980caa-fe16-4637-9f40-1e061be62378.png)

Reason being, is that the existing slider uses whatever space is available to draw the arrow, and the hit context for moving it.

**Comment by Wagnerp** [comment]
I was thinking about the one found in the KColorButton, ContextMenus etc?

**Comment by Wagnerp** [comment]
i.e. A slider in here maybe?

![image](https://user-images.githubusercontent.com/949607/213859859-5108fef5-95b8-4959-adea-6a212cd1aa96.png)

**Comment by Smurf-IV** [comment]
> i.e. A slider in here maybe?


Deffo - not.

**Comment by Wagnerp** [comment]
Is this something for extended?

**Comment by Smurf-IV** [comment]
> Is this something for extended?

Normally I would have said yes, but now, so many colours are alpha blended I think it could / should be in standard

**Comment by Wagnerp** [comment]
> A thought: It might be possible to replace this area, with a masked edit (4 values) / text / and a slider ![image](https://user-images.githubusercontent.com/2418812/213859420-84980caa-fe16-4637-9f40-1e061be62378.png)
> 
> Reason being, is that the existing slider uses whatever space is available to draw the arrow, and the hit context for moving it.

Maybe a better idea

**Comment by Smurf-IV** [comment]
Coming to a PR soon:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/941073de-6588-4fcf-9c6e-f88f1cb4fb3f)
