### ISSUE TITLE
[Bug]: Cannot add items to KryptonGroupBox in designer

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#91]
**Describe the bug**
![DropInDesigner](https://user-images.githubusercontent.com/2418812/117564732-670e1280-b0a5-11eb-88b8-21df354e20f0.gif)

**To Reproduce**
Project type:
``` c#
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <LangVersion>latest</LangVersion>
        <OutputType>WinExe</OutputType>
    </PropertyGroup>
```

**Expected behaviour**
Select -> Drag -> Drop 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
- `<ProjectReference Include="..\..\..\..\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2019.csproj" />`

**Additional context**
Visual Studio Pro 16.9.4

**Comment by Smurf-IV** [comment]
Also the Document outline does not allow the hierarchy to be altered 
i.e. 
- the drag and drop within it
- - and the arrows icons are disabled !

**Comment by Smurf-IV** [comment]
Available August 2021 (Canary)

**Comment by bytehammer2** [comment]
I understand bug #91 is claimed to be resolved, but I can't add items to a KryptonGroupBox in the WinForm designer.  I'm using Krypton.Toolkit Stable Version 65.22.6.152, VS 2019 Version 16.10.1, Windows 10.  I also tried adding items using VS 2022 Version 17.3.3 with the same results. ?

**Comment by Smurf-IV** [comment]
Duplicate:
Will be done as part of #838, as that has a lot of information it.
