### ISSUE TITLE
[Feature Request]: Progress Bar - Border Rounding

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#910]
Is it possible to round the border on a Progressbar?
Is a similar way to 'most' other Krytpon controls

![image](https://user-images.githubusercontent.com/84494183/213736835-dd1f6b87-6d97-48b2-bd6d-ea62fe70685f.png)

I appreciate that ' KryptonProgressBarExtendedVersion1 ' has some rounding, but would like to alter it to match other controls in my form(s)

Cheers

MattH

**Comment by Wagnerp** [comment]
@HardToFail has provided the following link on extended toolkit repo: https://www.cnblogs.com/lesliexin/p/13575517.html

Project download: 
[LProgressBar.zip](https://github.com/Krypton-Suite/Standard-Toolkit/files/10569690/LProgressBar.zip)

**Comment by Smurf-IV** [comment]
Coming to a PR Soon:
![example](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/e7a9ac0d-a78f-4c25-b2a5-1a0d29155e24)
