### ISSUE TITLE
[Feature Request]: Continue work on the `Palette` import / export usage 

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#913]
As per  #827 there are still outstanding things to be _voted_ upon:

Next:
- [ ] #1450
- [x] Aim for a single set of strings for the theme names
- [x] Sort loading of Themes (xml)
- ~~[ ] Sort loading of Themes (Designer)~~
- [ ] Sort loading of Themes (Binary) ?
- [x] Add / Update example projects
- [ ] Update [Theme creator](https://github.com/Krypton-Suite/Theme-Palettes/issues/68) so "save / load" in "Designer / Binary" format ??

**Comment by Wagnerp** [comment]
Adding to discord as a pinned comment

**Comment by hopla** [comment]
My votes go to

1. Add doc's on how to use the various theming options (xml, base, designer, programmatic, etc.)
2.  Add / Update example projects

The rest I could do in my application if needed...

**Comment by sdreb3421** [comment]
I agree with hopla. I never use the

**Comment by cuppm** [comment]
Documentation and examples.  I think there's way more cool stuff that's available in the current version of Krypton than I know about.  And having new showcase for them in examples and documentation would be good.

**Comment by Smurf-IV** [comment]
After sorting the usage of themes via `KrptonManager` updates here are my observations on the comments above
>  Sort loading of Themes (Binary) 

No, as binary serialisation always appears to be replaced with a newer version that does not have x security or performance Y thing. So it will stick with xml. It's fast enough for these "One off" stylings

> Add / Update example projects

There already are examples on "Custom" Palette usages
- Loading and applying a saved palette
- Using the designer to create palete modification and applying that via the "GlobalCustom Palette" equivalent
- Being able to override the base font used regardless of the colour theme being used.

**Comment by SteveAndrews** [comment]
The documentation is wrong:
https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/palettes.html

There is no KryptonPalette type, among the HUNDREDS!?!? of *Palette* types.

Is there somewhere else I should be looking? I'm trying to import an XML theme (you could you json), and I've tried dozens of ways that don't work.

**Comment by Wagnerp** [comment]
> The documentation is wrong: https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/palettes.html
> 
> There is no KryptonPalette type, among the HUNDREDS!?!? of _Palette_ types.
> 
> Is there somewhere else I should be looking? I'm trying to import an XML theme (you could you json), and I've tried dozens of ways that don't work.

Hi @SteveAndrews 

Thanks for notifying, yes this documentation is out-of-date. As of V80, you need to be using `KryptonCustomPaletteBase` then assign it to the `KryptonManager` as a 'Custom' palette.

@Smurf-IV Should this documentation be removed or updated?

**Comment by Smurf-IV** [comment]
@Wagnerp Should have been done as part of the 1st option, but never got done.
Perhaps re-open this or create a new one, and link back to here ?

**Comment by Wagnerp** [comment]
@Smurf-IV Going to reopen

**Comment by Wagnerp** [comment]
Hi @SteveAndrews 

Does this solve your issue https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Overview/Palettes.html

**Comment by Smurf-IV** [comment]
Closing, as Themes work is being superceded with newer ideas.
