### ISSUE TITLE
[Bug]: Button Designer adds values it shouldn't

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#915]
Using todays alpha branch and saving a designer file, the button has values added that cause an application to crash:

![image](https://user-images.githubusercontent.com/2418812/213864378-dfabdec7-f0e9-4f2e-ac29-589ce2605ccf.png)

I do not want any UAC stuff for a "normal" button, and if it is a default value, then do not add it (i.e. rounding)

![image](https://user-images.githubusercontent.com/2418812/213864301-d6859c76-e9a6-4b2f-a8c9-38d7b303ccd5.png)

**Comment by Wagnerp** [comment]
Those values **should** only be triggered _if_ the user decides to show the UAC icon

**Comment by Smurf-IV** [comment]
> Those values **should** only be triggered _if_ the user decides to show the UAC icon

Agreed, I just changed something else, and nearly the whole button was changed in the diff view

**Comment by Wagnerp** [comment]
> > Those values **should** only be triggered _if_ the user decides to show the UAC icon
> 
> Agreed, I just changed something else, and nearly the whole button was changed in the diff view

Plus it adds an invisible image to `Values`

**Comment by Wagnerp** [comment]
Think I've figured out the issue... need to test using build >= .24

**Comment by Smurf-IV** [comment]
> build >= .24

Still the same in 24

**Comment by Wagnerp** [comment]
> > build >= .24
> 
> Still the same in 24

Please retry using today's build, >= .26

**Comment by Wagnerp** [comment]
Resolved 27/01/2023

**Comment by Smurf-IV** [comment]
> Please retry using today's build, >= .26

Confirmed "Fixed" in `80.23.1.30-alpha`
