### ISSUE TITLE
[Doc Update/Other Issues]: Update documentation on `IPalette` removal

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#919]
Update the documentation on `IPalette` removal

**Comment by Smurf-IV** [comment]
It is already in the "Breaking changes" for V80
https://github.com/Krypton-Suite/Standard-Toolkit/tree/canary#palette-usages

**Comment by Wagnerp** [comment]
The reason for this was that someone on Discord wasn't sure if the 'fix' was to do a simple find & replace

https://canary.discord.com/channels/620577714889424916/705475523559686197/1067126438559498380

https://canary.discord.com/channels/620577714889424916/705475523559686197/1067127602533388298

Could do a GIF animation?

**Comment by Wagnerp** [comment]
I think this is done?
