### ISSUE TITLE
[Bug]: Cannot add a group to the `KryptonRibbon` while using .NET

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#928]
Cannot add a group to the `KryptonRibbon` while using .NET via the designer. Affected versions are .NET 6 - 7 (plus older versions that are now sunset).

**Comment by Smurf-IV** [comment]
@Wagnerp Using todays the V85 branch and the test-Form project.
![GroupV85](https://github.com/user-attachments/assets/bd82b0c5-6ee4-4d6c-a5a6-5748d67e088d)

It appears to be working, Is this something that only affects .net6 "Only" projects?

**Comment by Wagnerp** [comment]
> @Wagnerp Using todays the V85 branch and the test-Form project. ![GroupV85](https://private-user-images.githubusercontent.com/2418812/356863805-bd82b0c5-6ee4-4d6c-a5a6-5748d67e088d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk1MTksIm5iZiI6MTcyMzM2OTIxOSwicGF0aCI6Ii8yNDE4ODEyLzM1Njg2MzgwNS1iZDgyYjBjNS02ZWU0LTRkNmMtYTVhNi01NzQ4ZDY3ZTA4OGQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDk0MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0NDJiMzA0YzFlM2I4ZmNlMDY4ZjhjYzI3NTAxYWY1NDRjN2M1ZWI0OTU3NmVjNDdjOTVhZjI3ODkyNGZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6I6irmv1juOOapMtBzcc1dP26rivdHxdjf6N8Jv9ckM) [ ![GroupV85](https://private-user-images.githubusercontent.com/2418812/356863805-bd82b0c5-6ee4-4d6c-a5a6-5748d67e088d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk1MTksIm5iZiI6MTcyMzM2OTIxOSwicGF0aCI6Ii8yNDE4ODEyLzM1Njg2MzgwNS1iZDgyYjBjNS02ZWU0LTRkNmMtYTVhNi01NzQ4ZDY3ZTA4OGQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDk0MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0NDJiMzA0YzFlM2I4ZmNlMDY4ZjhjYzI3NTAxYWY1NDRjN2M1ZWI0OTU3NmVjNDdjOTVhZjI3ODkyNGZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6I6irmv1juOOapMtBzcc1dP26rivdHxdjf6N8Jv9ckM) ](https://private-user-images.githubusercontent.com/2418812/356863805-bd82b0c5-6ee4-4d6c-a5a6-5748d67e088d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk1MTksIm5iZiI6MTcyMzM2OTIxOSwicGF0aCI6Ii8yNDE4ODEyLzM1Njg2MzgwNS1iZDgyYjBjNS02ZWU0LTRkNmMtYTVhNi01NzQ4ZDY3ZTA4OGQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDk0MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0NDJiMzA0YzFlM2I4ZmNlMDY4ZjhjYzI3NTAxYWY1NDRjN2M1ZWI0OTU3NmVjNDdjOTVhZjI3ODkyNGZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6I6irmv1juOOapMtBzcc1dP26rivdHxdjf6N8Jv9ckM) [ ](https://private-user-images.githubusercontent.com/2418812/356863805-bd82b0c5-6ee4-4d6c-a5a6-5748d67e088d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk1MTksIm5iZiI6MTcyMzM2OTIxOSwicGF0aCI6Ii8yNDE4ODEyLzM1Njg2MzgwNS1iZDgyYjBjNS02ZWU0LTRkNmMtYTVhNi01NzQ4ZDY3ZTA4OGQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDk0MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0NDJiMzA0YzFlM2I4ZmNlMDY4ZjhjYzI3NTAxYWY1NDRjN2M1ZWI0OTU3NmVjNDdjOTVhZjI3ODkyNGZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6I6irmv1juOOapMtBzcc1dP26rivdHxdjf6N8Jv9ckM)
> 
> It appears to be working, Is this something that only affects .net6 "Only" projects?

@Smurf-IV 

If it's only affecting .NET 6, then I'd say close as support is being dropped in V90.
