### ISSUE TITLE
[Question]: Missing 'SelectedIndex' property for `KryptonDomainUpDown`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#930]
Why is the 'SelectedIndex' property for `KryptonDomainUpDown` hidden in the designer and set to '-1'?

![image](https://user-images.githubusercontent.com/949607/215318516-6056c412-0454-43c7-9689-d07f93d28a07.png)

**Comment by Smurf-IV** [comment]
It's because the Winform DomainUpDown also has it set in net4.x -> net7:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/42a0d0fe-2b91-47b0-9fa4-df1945f4f938)
