### ISSUE TITLE
[Feature Request]: `KryptonNavigator` - close button on tabs

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#937]
Make the close button on tabs option on `KryptonNavigator` the default

**Comment by HardToFail** [comment]
It's great if there is an Enum attribute just like "CloseButtonDisplayPosition",we can show the closebutton on the selectedTab or  every Tab or on the default position

**Comment by Wagnerp** [comment]
Hi @Smurf-IV & @giduac

I think this should be a V100 item, thoughts?

**Comment by Smurf-IV** [comment]
I do not understand what this could be; because there are already options to put "Buttons" onto each tab:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/decda5da-c7cf-4207-a53d-0dd231a948ee)

**Comment by Smurf-IV** [comment]
And the location is already controllable:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/04392e7a-e2a8-4cb5-a930-a0d2702b3586)

**Comment by Wagnerp** [comment]
Closing, existing feature
