### ISSUE TITLE
[Feature Request/Bug]: `KryptonRibbon` designer does not follow selected theme

### ISSUE THREAD

**Issue by PWagner1** [Krypton-Suite/Standard-Toolkit#938]
Upon testing #929, it is noticeable that the `KryptonRibbon` designer does not follow selected theme, as it appears to be using just the `Office 2010 - Blue` theme.

![Ribbon](https://user-images.githubusercontent.com/949607/216927534-54c6b59d-147e-49c0-9dd8-6c9661fc2c2a.gif)

**Comment by Smurf-IV** [comment]
It appears to be stuck in whatever palette, the designer uses when it first opens.
You then change the style in the associated `KryptonManager` to change it in the designer:
![RibbonDesigner](https://github.com/user-attachments/assets/e5bec88f-6f26-4cfe-8573-c71bee17f973)
