### ISSUE TITLE
[Question]: Is it time to 'sunset' old LTS versions

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#939]
So, is it time to unlist the old LTS versions? These versions have the version number of `5.500.2103` and were last updated in March 2021, which was nearly 2 years ago.

**Comment by Smurf-IV** [comment]
?: The Nuget website _should_ be able to tell you the download rate for packages.
?: If 5.5 is removed, then what is the alternative that supports 3.5 -> 4.6.1 ?

**Comment by Wagnerp** [comment]
> ?: The Nuget website _should_ be able to tell you the download rate for packages. ?: If 5.5 is removed, then what is the alternative that supports 3.5 -> 4.6.1 ?

Yes, it's 2 per day. For an alternative for 3.5 -> 4.6.1, could build one from https://github.com/Krypton-Suite-Legacy-Archive/Krypton-Toolkit-Suite-NET-Core, taking out anything 4.6.2+?
