### ISSUE TITLE
[Question]: How to switch the ColumnType at the Runtime?And how to choose a Specific EditingControl of a column

### ISSUE THREAD

**Issue by HardToFail** [Krypton-Suite/Standard-Toolkit#941]
When the application is running,I need to change the dgv columntype,for example,Convert from KryptonDataGridViewTextBoxColumn to KryptonDataGridViewComboBoxColumn。Is there an Simple way to do it?
Besides,it is great if a  KryptonDataGridViewTextBoxColumn can choose its editingcontrol(ComboBoxEditingControl,RichTextBoxEditingControl...).Is there an Simple way to do it?

**Comment by Smurf-IV** [comment]
The action to change the column type will be whatever can be done with the standard DataGrid Control.
So, please perform a search for the solution for winform.
