### ISSUE TITLE
[Feature Request]: `ThemeManager` should be in a single file

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#943]
The `ThemeManager` should be in a single file, as per discussion [here](https://github.com/Krypton-Suite/Standard-Toolkit/pull/936#discussion_r1103623023)

**Comment by Smurf-IV** [comment]
Coming to a PR tomorrow..
![SingleThemName](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/4a560c8e-570f-4255-bf8d-72531d6f46f1)
