### ISSUE TITLE
[Feature Request]: `Yes/No/Ok to All` option for `KryptonMessageBox`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#946]
Please add a `Yes/No/Ok to All` option for `KryptonMessageBox`

**Comment by Smurf-IV** [comment]
@Wagnerp 
The `Ok to All` is not a base winform feature:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxbuttons?view=windowsdesktop-7.0#fields

But `CancelTryContinue` is, and that is already in the `KryptonMessageBoxButtons` enum.
