### ISSUE TITLE
[Bug]: No Help-Button displayed on KrytonForm

### ISSUE THREAD

**Issue by DarthVader85PA** [Krypton-Suite/Standard-Toolkit#95]
**Describe the bug**
On `KryptonForm` the property in designer `HelpButton` is set on `True`, but no Help-Button will displayed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/32876506/117569949-54f19b80-b0c8-11eb-88f3-99000cbb3268.png)
![grafik](https://user-images.githubusercontent.com/32876506/117569979-8702fd80-b0c8-11eb-9648-81b5460c0bce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 19042.928 (20H2)

Best regards, 
Danny from Germany :)

**Comment by Wagnerp** [comment]
Linked to #219

**Comment by Smurf-IV** [comment]
Closing this, working on 219
