### ISSUE TITLE
[Feature Request]: Please add `-t:rebuild` to the msbuild command line.

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#950]
This is so that the report at the end of the build command line reflects the actual build status.

Or perform a `clean` msbuild command line, 
then the existing build;
To make sure that any trailing project references are built in "build order"

**Comment by Smurf-IV** [comment]
Should this also be duplicated in the extended kit as well ?

**Comment by Wagnerp** [comment]
> Should this also be duplicated in the extended kit as well ?

No, as that's built inside of Visual Studio. Did try to do a similar thing, but it's way to complex.

**Comment by Wagnerp** [comment]
Needs a bit of working out, as appending the switch doesn't work

@Smurf-IV Do we necessarily need the build log to be printed out to a external `log` file? Obviously, any changes made will _just_ only affect the `nightly` config, as we use that for dogfooding.

**Comment by Wagnerp** [comment]
Done, had to do it via the [proj](https://learn.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2022) file

**Comment by Wagnerp** [comment]
Completed 19/02/2023
