### ISSUE TITLE
[Bug]: Issue with KryptonSplitContiner when **Only** targeting .net 7

### ISSUE THREAD

**Issue by Bonio55** [Krypton-Suite/Standard-Toolkit#955]
**Describe the bug**
When attempting to use the KryptonSplitContainer on a winform project targeting .net 7 the 2 panels do not appear to be created properly and on attempt to add a control to the KryptonSplitContainer an error is recieved 

Failed to create component 'KryptonTextBox'. The error message follows:
'Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: ReadOnly controls collection
at
'Microsoft.DotNet.DesignTools.Client.DesignToolsClient. <SendRequestAsync>d__49`1.MoveNext()

**To Reproduce**
1. Create new winform project targeting .net 7
2. Create New Form
3. Add new KryptonSplitContainer Control
4. Attempt to add any control i.e. TextBox to one of the panel (or where a panel should be located) of the splitcontainer.

**Note**

This procedure has been repeated step for step but on a second project targeting .net framework 4.7.2 and the issue is not pressent and the splitcontainer works as expected. only when targeting .net 7 in stead does this issue occur.

**Expected behavior**
New Item should appear in the splitcontainer.

**Screenshots**
Screenshot one shows the Krypton split container after being added to the form (the panels of which do not appear to be rendered as expected as suspect this is where the problem my originate and possible the internal panels being created may at fault? )

Screenshot two is the error message received.

**Desktop (please complete the following information):**
 - OS: Windows 10 64Bit
 - Version	10.0.19045 Build 19045
 - Visual Studio 2022 (Version 17.4.5)

**Additional context**
![SplitContainerError_1](https://user-images.githubusercontent.com/39240946/220619068-809cfdba-3c8a-483d-8b64-6e7b162b0529.png)
![SplitContainerError_2](https://user-images.githubusercontent.com/39240946/220619070-870f3769-b3d6-449e-b179-7f9cd42423a9.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Seems to be another designer issue?

**Comment by Bonio55** [comment]
Hi, I dont know if this needs to be raised as a seperate report but I have also just come across this same issue with a KryptonGroupBox when tryingto add a control in at designtime.

Im my limited experience with .net  (oposed to framework) as a process of attempting to migrate my existing project from framework 4.7.2 to .net 7   -  I dont know if this is of any help or is just me not understanding how the controls are programmed but I re-run my test project used to demo the above issue and compiled the Krypton Suite from source and attempted to debug to see if could narrow down the issue at all.  I did observe that tho the parent control (KryptonSplitContiner and KryptonGroupBox) show the internal 'Panel' controlls as not being in design mode when the parent controll is.   Sorry if this is a wild goose chase but thought would mention incase this information helps at all.

Kind Regards 
Shaun

**Comment by Wagnerp** [comment]
Hi @Bonio55 

Unfortunately, MS seems to have broken a lot of WinForms designer stuff since moving to .NET. We're waiting for a specific SDK which should fix these issues.

**Comment by Bonio55** [comment]
Thats no problem i think i may revert back to framework for the time being and wait on the migration but its not a lost cause and now using the nuget packages as was previously on a couple year old source code set but in mean time if you need me to look into anything with regards to above / my findings let me know and I will shelf a copy of the project files incase. 

Also a big thanks to you all for the Suite itself and the ongoing development you all put in :-)

**Comment by Smurf-IV** [comment]
> revert back to framework for the time being

@Bonio55 
You only need to have the `net48` in the sdk style project to allow the designer to work (as expected)
And still have your projects building out to the latest net core (V8 now) so that you get the speed benefits (etc)

**Comment by giduac** [comment]
Hi @Wagnerp,

This is a standard OOP Designer case, and can be closed.
Not much we can do about this currently.

Ty.
