### ISSUE TITLE
[Feature Request]: `KryptonForm` - Include a `KryptonPanel` by default

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#959]
`KryptonForm` - Include a `KryptonPanel` as the background by default

**Comment by Wagnerp** [comment]
Using a KPanel won't work, as it 'locks' everything up

**Comment by giduac** [comment]
If the KForm had an option to retrieve and set the background colour that would handy.

This works nice in the form constructor although it's not dynamic / changes on a theme change at runtime. And saves the use of a KPanel.
```cs
this.BackColor = kryptonManager1.GlobalPalette.GetBackColor1( PaletteBackStyle.FormMain, PaletteState.Normal );
```

Still the dev can choose if he wants to use a panel.

**Comment by Wagnerp** [comment]
@giduac 

Thanks for the tip, personally I was getting fed up of repeatedly using a KPanel, just to make the form fit in with everything else.

**Comment by giduac** [comment]
If you use a KPanel as the first item on the form and set its Dock property to Fill than your good as well...

So you get:
KForm
  KPanel
    All items that used to be on the forrm.

And in the designer source you can move the items that are added to form's Control property to the Panel's Control property.
Dockt the panel and you get the same result...

**Comment by Wagnerp** [comment]
Unfortunately, there isn't a separate designer class for either `VirtualForm` or `KryptonForm`. Instead, they're one single class for each.

**Comment by giduac** [comment]
Easiest way to make all blend in with the theming is to use a kpanel

**Comment by Wagnerp** [comment]
> where are things like border kform colours handled or the caption bar (allowFormChrome) it could be done from there??

I think it's done in `VirtualForm`

**Comment by Wagnerp** [comment]
@Smurf-IV & @giduac It might be easier (and quicker) to do this as part of #908

**Comment by giduac** [comment]
@Smurf-IV @Wagnerp 
I think these State* objects within KForm deserve a better look and make the form behave and adjustable like other objects that use state-objects

**Comment by Wagnerp** [comment]
> @Smurf-IV @Wagnerp I think these State* objects within KForm deserve a better look and make the form behave and adjustable like other objects that use state-objects

@giduac This might be a separate feature request, so that it can be easily tracked

**Comment by giduac** [comment]
@Smurf-IV @Wagnerp 
It's not clear to me why that never worked that way and you need a KPanel for a dynamic background colour.

IMHO, A FR for this would be a good moment to bring this inline with the central approach of the TK objects

**Comment by Wagnerp** [comment]
Been folded into #1117
