### ISSUE TITLE
[Question]: How to modify a `KryptonForm` to look like a UWP app

### ISSUE THREAD

**Issue by SmartSuperAppSuperApp** [Krypton-Suite/Standard-Toolkit#964]
![image](https://user-images.githubusercontent.com/120347917/223619721-344d310f-1dbd-4929-b587-686061f1745b.png)
Can you help me, where to design this interface forms?
I tried everything to debug KryptonForm, but no success.
![image](https://user-images.githubusercontent.com/120347917/223620076-45145346-58df-4a5a-b9f1-f1c14b555c66.png)

**Comment by Wagnerp** [comment]
Hi @SmartSuperAppSuperApp 

You could do this by setting `FormBorderStyle` to 'None', then design it as you wish

**Comment by Smurf-IV** [comment]
> but if possible, I'd really like to add the attribute, handle it directly on the KryptonForm too.

If it can be done in the designer, then the code is available to be called programmatically as well.

**Comment by Smurf-IV** [comment]
Can this be closed now ?
