### ISSUE TITLE
[Question]: Should 'Olive Green' & 'Silver' be part of the official 2k3 themes

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#965]
Should 'Olive Green' & 'Silver' be part of the official 2k3 themes, as they're supported in Windows XP?

Olive Green

![image](https://user-images.githubusercontent.com/949607/223660268-e383beb4-c2ab-48d3-a40e-ed7b7a6f13a6.png)

Silver

![image](https://user-images.githubusercontent.com/949607/223661044-b2e375ed-7d8c-45e2-b48d-d56fa313ad25.png)

If so, then I'll convert this into a feature request

**Comment by Smurf-IV** [comment]
Well.. MS "thought" it was a good idea:
Q) So why not ?
A) Because the green does not handle well for the modern day and age, and does not handle well for colour blindness etc.!
A2) Silver is nice, but is that too similar to the other silver themes ?
