### ISSUE TITLE
[Question]: Help design KryptonForm

### ISSUE THREAD

**Issue by SmartSuperAppSuperApp** [Krypton-Suite/Standard-Toolkit#967]
![image](https://user-images.githubusercontent.com/120347917/224465354-02cfd661-80af-4796-aeae-ce8e544a8c55.png)
I'm recoding kryptonForm, designing the header into 2 parts (1, 2)
- (1): I use ButtonSpec to add any kind of control?
- (2): Still design the same ControlBox.
So can you help me with the code that needs to be processed?
Because, for me, design is about taking advantage of every space available on Forms, simple and flexible in design.

**Thank you!**

**Comment by Wagnerp** [comment]
Hi @SmartSuperAppSuperApp 

The majority of what you're looking to do can be done using `ButtonSpecs`, but you need to attach a KCommand to them to actually do anything with them. See https://github.com/Krypton-Suite/Standard-Toolkit-Demos for examples.
