### ISSUE TITLE
[Feature Request]: Notification Banners

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#970]
It would be great to have 'notification banners' like the one seen here (red):

![Notification Banner](https://user-images.githubusercontent.com/949607/224493492-188238d9-fec0-4b42-8df8-2464f8ff2eb8.png)

**Comment by Smurf-IV** [comment]
Please explain why this cannot be done with the existing toolkit via a form that "pops up" at a location with width set to parent app width ?
it would need to have 
- no form border
- a single Panel Border thickness
- Probably some translucent background
- A way of closing it.
- s

**Comment by Wagnerp** [comment]
Not planned.
