### ISSUE TITLE
[Question]: Any forum/discord/community anywhere?

### ISSUE THREAD

**Issue by stigzler** [Krypton-Suite/Standard-Toolkit#973]
Firstly to the team - amazing job. To have this as open source and the fact you are keeping this project alive is just amazing. Well done to all - truth being it seems a lot better authored then a lot of other free-to-indies like myself.

I know how much of a pain documentation is when your focus is the code. I'm just wondering whether you've thought about a forum or discord server or something so people can access a knowledge base over time around using your controls. An example is I've spent some time today trying to get to grips with the docking manager and whilst I can get so far with the code examples, it's those little undocumented things that take up the time. Google searches are showing nothing. 

I never like using github issues for question like "how do I...."

**Comment by hopla** [comment]
You'll find a reference to the Discord server in the readme file.

**Comment by stigzler** [comment]
derp. missed it - thanks.

**Comment by Wagnerp** [comment]
Hi @stigzler 

You can find all the documentation & examples [here](https://github.com/Krypton-Suite/Releases/releases)
