### ISSUE TITLE
[Bug]: KryptonDockableNavigator with pages without AllowConfigSave flag are incorrectly saved

### ISSUE THREAD

**Issue by jmairboeck** [Krypton-Suite/Standard-Toolkit#980]
**Describe the bug**
When saving the layout of a `KryptonDockableNavigator` where some (or all) pages have the `AllowConfigSave` flag cleared (so that they are not saved), the page count attribute (`C="x"`) still contains them. This causes an exception when trying to load the resulting XML again.

**To Reproduce**
1. Define a `KryptonDockableNavigator`
2. Add some pages to it with the `AllowConfigSave` flag cleared
3. Save the resulting config (`dockingManager.SaveConfigToFile("...")`)
4. Observe that the resulting XML has a count attribute that includes the excluded pages (e.g. `<DN N="Navigator" C="4"></DN>`)
5. Try to reload the saved layout
6. A `System.ArgumentException` is thrown in `KryptonDockingNavigator.LoadElementFromXml`: "Element name 'KP' was expected but found 'DN' instead."

**Expected behavior**
The panels which are not saved, should be excluded from the count attribute also, when saving the XML.

Change this line

https://github.com/Krypton-Suite/Standard-Toolkit/blob/896008b760dea81505c1a30aa38c4b1b56a46452/Source/Krypton%20Components/Krypton.Docking/Elements%20Impl/KryptonDockingNavigator.cs#L747

like this:

`xmlWriter.WriteAttributeString(@"C", DockableNavigatorControl.Pages.Count(static page => page.AreFlagsSet(KryptonPageFlags.AllowConfigSave)).ToString());`

**Additional context**
Using version Krypton.Docking.Lite version 70.22.11.312 for .NET Framework 4.8.

**Comment by Smurf-IV** [comment]
Due to the date this was found, it should be fixed in V85.
Also check that the suggested change above goes into the `Docking "Control / Workspace / Floating"` areas
AND, also into the `Workspace` standalone saving workflows as well.
