### ISSUE TITLE
[Bug]: Double click on the Form1 file in the Krypton toolkit test project results in a designer error

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#982]
**Describe the bug**

**To Reproduce**
- Get "Todays" alpha branch of the toolkit (2023-04-25)
- Build Debug in Visual Studio 2022 (I'm using 17.6 P2)
- Open the included Test form project and double click the Form1.cs file
  - ![image](https://user-images.githubusercontent.com/2418812/227711478-99c6b02d-4915-4113-9978-b549372e83c1.png)

**Expected behaviour**
- For the designer to load

**Screenshots**
![image](https://user-images.githubusercontent.com/2418812/227711292-2cdc2feb-0e55-4125-9192-983d41c388e9.png)
(The above is stuck in a loop if you click ignore - about 100 times I tried - and also by pressing and holding "Alt+I" !!)

When attaching a Debugger (via retry) you see this:
![image](https://user-images.githubusercontent.com/2418812/227711279-0b286251-0a2b-47a8-97af-b3d5c073d93c.png)

Attempting to run the "TestForm" app results in these (Again holding "Alt+I" results in loads of these pairs!!)
- ![image](https://user-images.githubusercontent.com/2418812/227711546-e0120fb2-f499-4a2b-b23b-9e3f0695cd78.png)
- ![image](https://user-images.githubusercontent.com/2418812/227711569-b808115b-611d-42c9-87ca-4d2ee8cf2a88.png)

I suspect it is something to do with the Toolbar buttons

**Comment by Wagnerp** [comment]
The 'new' buttonspecs aren't invoked. @Smurf-IV Does this happen for all themes?

**Comment by Smurf-IV** [comment]
> The 'new' buttonspecs aren't invoked. @Smurf-IV Does this happen for all themes?

No idea, Just cannot use the "TestForm" project in any way !
I'm just about to go to the Toolkit examples next to see if affects them.

**Comment by Wagnerp** [comment]
Easy Resharper fix

![image](https://user-images.githubusercontent.com/949607/227712499-b5662678-e82b-46ee-97b1-39e2c86f859a.png)

**Comment by Smurf-IV** [comment]
> Easy Resharper fix

It'll still throw the Debug.Assert in the designer !!

**Comment by Wagnerp** [comment]
> > Easy Resharper fix
> 
> It'll still throw the Debug.Assert in the designer !!

Could it also be something to do with `Source\Krypton Components\Krypton.Toolkit\Values\IntegratedToolBarValues.cs`?

**Comment by Wagnerp** [comment]
@Smurf-IV Think I got it now, school boy error, I forgot to 'add' the images to the base palettes!

**Comment by Wagnerp** [comment]
Update: Got `Form1` back to a working state, but it's bugged when using O2k13

**Comment by Wagnerp** [comment]
Going back to `Canary` as the last known 'good' build

**Comment by Wagnerp** [comment]
@Smurf-IV Is there a way to write assert messages out to log files, so I can properly read them, rather than having them truncated?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/562a5a2e-64e8-4009-b4f1-def718c04672)

**Comment by Smurf-IV** [comment]
Clicking retry will got Visual Studio, and then the stack trace will be available in the CallStack window

**Comment by Smurf-IV** [comment]
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/cd619f5f-ec17-4503-87a3-2c82a4814582)
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.defaulttracelistener?view=net-7.0

**Comment by Smurf-IV** [comment]
Note: The designer appears to be working with o2k13 white now.

**Comment by Wagnerp** [comment]
> ![image](https://user-images.githubusercontent.com/2418812/253790607-cd619f5f-ec17-4503-87a3-2c82a4814582.png) https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.defaulttracelistener?view=net-7.0

@Smurf-IV Might be good to enable this for `Canary` & `Nightly` configurations only. Maybe a new feature request?

**Comment by Smurf-IV** [comment]
Should not be part of the Framework, as this is an Application setting. And Some OS's are not even on the C: drive (See Chinese default drive usages)

**Comment by giduac** [comment]
Hi @Wagnerp & @Smurf-IV,

Is this still a problem since then TestForm has undergone quite a few changes....?

**Comment by Wagnerp** [comment]
> Hi @Wagnerp & @Smurf-IV,
> 
> Is this still a problem since then TestForm has undergone quite a few changes....?

Hi @giduac 

I don't know... are you able to repeat the steps above?

**Comment by giduac** [comment]
@Wagnerp 
You have a try and double click form1 ....

**Comment by Wagnerp** [comment]
> @Wagnerp You have a try and double click form1 ....

@giduac 

Seems to be working as of v85...

**Comment by giduac** [comment]
@Wagnerp 
And in alpha as mentioned in the call there's no form1.
This one can be put to bed I guess...

**Comment by Wagnerp** [comment]
> @Wagnerp And in alpha as mentioned in the call there's no form1. This one can be put to bed I guess...

@giduac 

I'll put it as part of v85 and close it

**Comment by giduac** [comment]
@Wagnerp 
Says fixed...Please close, ty.
