### ISSUE TITLE
[Question]: Krypton Datagridview - Border

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#989]
I can set a 'normal' System.Windows.Forms.DataGridView borderstyle
Where do I need to go to do the equivalent with a Krypton DataGridView
![image](https://user-images.githubusercontent.com/84494183/230422242-6e077cf6-7e0e-4279-8466-1e9da68b0a7a.png)
I would like to set the Krypton DataGridView borderstyle to Fixed3D

**Comment by MattH-Work** [comment]
BorderStyle is accessible via code ( Kryptn_DGV_Notes.BorderStyle = BorderStyle.Fixed3D ) but it does nothing
It is not exposed to the Designer
![image](https://user-images.githubusercontent.com/84494183/230429986-77db0840-841a-495f-9798-1d9193461828.png)

**Comment by Smurf-IV** [comment]
The looks like the following:
![image](https://user-images.githubusercontent.com/2418812/230570866-67033636-9fb3-4828-9c96-06e162649b3e.png)

Must have been a reason for it !
