### ISSUE TITLE
[Question]: Button border rounding background

### ISSUE THREAD

**Issue by Gebrochener** [Krypton-Suite/Standard-Toolkit#994]
Hey, 

so i just wanted to create a kryptonbutton which is ontop of a picturebox. I put the rounding of the button to 25 but now the background color of the windows forms is there, where I rounded off the corners. Does somebody know how I can fix this?

![Bild_2023-04-07_201518114](https://user-images.githubusercontent.com/111308632/230657642-8c85057b-e6ad-4607-a123-493a87b6636d.png)

**Comment by Smurf-IV** [comment]
A: Stick the button onto a panel of the same size, and set the panel to be transparent.

**Comment by Gebrochener** [comment]
> A: Stick the button onto a panel of the same size, and set the panel to be transparent.

I tried it but this doesn't work either. When I create the panel and set its background to transparent, the panel gets the color of the form. 
![Bild_2023-04-08_130007348](https://user-images.githubusercontent.com/111308632/230717561-7fd4efe0-e3b5-4632-a0b4-6d395decf02a.png)

**Comment by Smurf-IV** [comment]
So it must be an ordering problem.
How is the picture drawn?
Is it on a KPanel, with the background set to the picture ?

**Comment by Gebrochener** [comment]
I fixed the problem. At first I just created a pictureBox and there it didnt work but when i put the image onto my form as background it worked just fine.
