### ISSUE TITLE
[Bug]: DataGridView ComboBox Adding list over and over

### ISSUE THREAD

**Issue by DavidLanham** [Krypton-Suite/Standard-Toolkit#996]
Krypton.Toolkit.KryptonDataGridView and KryptonDataGridViewComboBoxColumn producing a strange behavior.   

1. Click on the combo box and cause the list to pop down
2.  Don't select anything from the list.
3. Click off somewhere else causing the list to close
4. Click on the combo box again and cause the list to pop down again.
5. Now the list has duplicated itself.
6. You can keep doing this and the list keeps duplicating
 
I have tried this will all version of the Krypton Toolkit. Knightly, Canary, stable.  They all produce the same behavior'. 

If I change the ColumnType to use DataGridViewComboBoxColumn instead of the KryptonDataGridViewComboBoxColumn it does not duplicate the list, it works correctly.

 - OS: Windows 11 VS: 2022 Pro using latest and greatest.
-

**Comment by DavidLanham** [comment]
Here you go

https://user-images.githubusercontent.com/114610313/232265436-cae5f4f4-749d-47d0-81a8-e368ea1a1472.mp4

**Comment by DavidLanham** [comment]
https://user-images.githubusercontent.com/114610313/234270191-833d86ad-86e2-4aff-8274-c8e65a3d3fea.mp4

So I was playing around with this issue and I figure something else out that may be helpful when looking at this issue

**Comment by varshneydevansh** [comment]
This bug seems like a little beginner-friendly, can I look into this?

**Comment by Smurf-IV** [comment]
> This bug seems like a little beginner-friendly, can I look into this?

Assign this to yourself, and set to `in-progress` etc.
Make a branch from alpha
Name it like `alpha-996-DGVComboBox`
Work on it.
Create PR
Show that it builds via the run command in the root directory (alpha build option) by adding a screenshot

Make sure that the Demo's still work.

Have a look at past PR's for the commenting screenshot styles

**Comment by DavidLanham** [comment]
How can I check if this has been fixed?

**Comment by Wagnerp** [comment]
> How can I check if this has been fixed?

@DavidLanham I don't think it's been fixed yet @Smurf-IV any ideas?

**Comment by Wagnerp** [comment]
@DavidLanham Have you tried setting a breakpoint, then stepping through to see where it gets duplicated?

**Comment by DavidLanham** [comment]
I am not sure that I am good enough programmer to do this.  I have downloaded the Master code and opened it in VS2022.  I have added my project to the Project and I am able to start my project with reference to the Master Project.  Can you suggest where in the Source\Krypton.Toolkit 2022 code to look?

**Comment by Smurf-IV** [comment]
Still there:
![StrangeDropBox](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/2c61b054-b2a5-431a-a1ac-78343c5f650e)

**Comment by Wagnerp** [comment]
@Smurf-IV Which browser are you using, as I can see them?

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/ad185714-a639-4efb-97f9-fb2170fbc241)

**Comment by Smurf-IV** [comment]
Firefox.

**Comment by Smurf-IV** [comment]
PR in Coming:
![FixDropClickOff](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/74008c7d-5a20-492a-b48e-c47e3f78ca81)

**Comment by Smurf-IV** [comment]
> I am sorry not sure what you mean, did you make a change 

Yes, Hence the PR reference above.

> or is there something that I am not going correctly? 

No, you where doing stuff fine, because it was replicated in the Example code that is used Krypton.


> If you made a change would it be in the Nightly build? Can I test it?

Yes, It should be in the nightly build that has a number greater than 337 (Not done yet..)

**Comment by Wagnerp** [comment]
> I am sorry not sure what you mean, did you make a change or is there something that I am not going correctly? If you made a change would it be in the Nightly build? Can I test it? Thanks for looking at this.

Hi @DavidLanham 

Please retry using `nightly` >= 338. Please be aware that there are some breaking changes in this build, documented in the 'alpha' `Readme`.

**Comment by DavidLanham** [comment]
I used the Nightly 338 and it worked.  Thank you for looking into this and making the change.  No hurry, but when do you think it will make it to the stable release?
